### PR TITLE
[VCDA-2187] Nsxt gateway delete dnat rule

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
  Added helper in nsxt_backed_gateway_service to delete dnat rule by name. Tested that this is able to successfully delete a dnat rule.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @sakthisunda @arunmk @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 253 at r1](https://reviewable.io/reviews/vmware/container-service-extension/936#-MUqxt9AA3b03D2P7-xf:-MUqxt9AA3b03D2P7-xg:b-qcp0ru) ([raw file](https://github.com/vmware/container-service-extension/blob/12b67ed377f501c5a5d4f73ca1100935442861a3/container_service_extension/nsxt_backed_gateway_service.py#L253)):*
> ```Python
> 
>         try:
>             self._cloudapi_client.do_request(
> ```

The creation and deletion cloudapi calls are async. They return a taskID and expect the caller to wait. Does this call do it behind the scenes? If not, the task may fail and there may be dangling rules.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 253 at r1](https://reviewable.io/reviews/vmware/container-service-extension/936#-MUqxt9AA3b03D2P7-xf:-MUrJpsc2zMv_U2ncXxy:byzkcox) ([raw file](https://github.com/vmware/container-service-extension/blob/12b67ed377f501c5a5d4f73ca1100935442861a3/container_service_extension/nsxt_backed_gateway_service.py#L253)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

The creation and deletion cloudapi calls are async. They return a taskID and expect the caller to wait. Does this call do it behind the scenes? If not, the task may fail and there may be dangling rules.
</blockquote></details>

We should wait on the task, pyvcloud has a built in method to wait on tasks, all you need is to give it the task id.
Every pyvcloud client has a task monitor in built.
___
*[container_service_extension/server_constants.py, line 504 at r1](https://reviewable.io/reviews/vmware/container-service-extension/936#-MUrKKmMDaBbIUdskDmn:-MUrKKmMDaBbIUdskDmo:brh55iz) ([raw file](https://github.com/vmware/container-service-extension/blob/12b67ed377f501c5a5d4f73ca1100935442861a3/container_service_extension/server_constants.py#L504)):*
> ```Python
> 
> # Nat rules pagination constants
> DEFAULT_FIRST_PAGE = 1
> ```

It seems that we have quite a few default values for pagination related keys. Can we please consolidate all these constants?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @arunmk and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 253 at r1](https://reviewable.io/reviews/vmware/container-service-extension/936#-MUqxt9AA3b03D2P7-xf:-MUtUl-j5-QQ3PmR5oHR:brs6ru8) ([raw file](https://github.com/vmware/container-service-extension/blob/12b67ed377f501c5a5d4f73ca1100935442861a3/container_service_extension/nsxt_backed_gateway_service.py#L253)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should wait on the task, pyvcloud has a built in method to wait on tasks, all you need is to give it the task id.
Every pyvcloud client has a task monitor in built.
</blockquote></details>

Done. Thank you; I missed this and the function now waits for the task.
___
*[container_service_extension/server_constants.py, line 504 at r1](https://reviewable.io/reviews/vmware/container-service-extension/936#-MUrKKmMDaBbIUdskDmn:-MUtUpjA3-tbYGrnbdH0:b-8wbm35) ([raw file](https://github.com/vmware/container-service-extension/blob/12b67ed377f501c5a5d4f73ca1100935442861a3/container_service_extension/server_constants.py#L504)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

It seems that we have quite a few default values for pagination related keys. Can we please consolidate all these constants?
</blockquote></details>

Done. Yes, I will just use DEFAULT_FIRST_PAGE

There is another `CSE_PAGINATION_FIRST_PAGE_NUMBER`, but this is currently used for requests to the CSE server, so I chose to kept these separate,

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936#-:-MUzv-pK-dWq3mNhSO5z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/cloudapi/cloudapi_client.py, line 159 at r3](https://reviewable.io/reviews/vmware/container-service-extension/936#-MV340XR0r60wwx6KR6n:-MV340XS8nMpV085qkTg:b-y8bh21) ([raw file](https://github.com/vmware/container-service-extension/blob/d3c9dc0bc82b8d9f9e68d0e946c79fd5db5fa53f/container_service_extension/cloudapi/cloudapi_client.py#L159)):*
> ```Python
>                 cursor_list = parsed_query_map.get('cursor')
>                 if cursor_list:
>                     return cursor_list[0]
> ```

Can you please add some comment over here, as to why there is a list and returning the first cursor is ok?

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/936)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

**Pull request merged**
