### PR TITLE
[VCDA-2959] Populate cpu/mem fields in status section of RDEs while upgrading from CSE 3.1.0 to CSE 3.1.1

### PR DESCRIPTION
**Pull request by rocknes**
We have introduced new fields to RDE 2.0.0 in CSE 3.1.1 which were not present in RDE 2.0.0 of CSE 3.1.0. Hence, any upgrade from CSE 3.1.0 -> CSE 3.1.1 should update the existing RDEs to have proper value in the new fields viz. status.nodes.[control_plane|worker].[cpu|memory]

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 2809 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxdo1J73G5mRfun6-z:-Mkxdo1J73G5mRfun60-:bic6zg3) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2809)):*
> ```Python
> 
>             nodes_to_process = [native_entity_2_x.nodes.control_plane]
>             if native_entity_2_x.nodes.workers:
> ```

shouldn't this be `native_entity_2_x.status.nodes`?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 2811 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-MkxdupY7KBB-JMpdRn4:-MkxdupY7KBB-JMpdRn5:bk0isz3) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2811)):*
> ```Python
>             if native_entity_2_x.nodes.workers:
>                 nodes_to_process.extend(native_entity_2_x.nodes.workers)
>             if native_entity_2_x.nodes.nfs:
> ```

I think this should be `native_entity_2_x.status.nodes.nfs`

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 2808 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxe52n-Su4_JXdj5xd:-Mkxe52n-Su4_JXdj5xe:bobotml) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2808)):*
> ```Python
>             vapp = VApp(client, href=vapp_href)
> 
>             nodes_to_process = [native_entity_2_x.nodes.control_plane]
> ```

should be `native_entity_2_x.status.nodes.control_plane`

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 2817 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxeq-a00d6ld6GW4Qw:-Mkxeq-a00d6ld6GW4Qx:bfh831b) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2817)):*
> ```Python
>             # RDE 2.0.0 of CSE 3.1.0. In CSE 3.1.0, RDE 2.0.0 didn't
>             # have cpu/memory fields in status.
>             for node in nodes_to_process:
> ```

nfs nodes don't have cpu and memory properties. So we shouldn't be updating nfs nodes with cpu/mem

**Review by sakthisunda — APPROVED** [review]
:lgtm: ( after review comments )

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223#-:-Mkxs8K-Aibn2p0CV349:bblodtm)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/server/vcdbroker.py, line 1640 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxrg0o4J2jULT-PRt9:-Mkxrg0pA-T-p2aYZb-v:b-rrfgk) ([raw file](https://github.com/vmware/container-service-extension/blob/d578b00f25c1e827d0444b3fba1fc3f6d3f5e917/container_service_extension/server/vcdbroker.py#L1640)):*
> ```Python
>         page_number=None,
>         page_size=None
> ) -> Union[List, Dict]:
> ```

nit: List[Dict]

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223#-:-MkxtqLFBiKX_yNeNi3l:bg7igkv)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 2808 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxe52n-Su4_JXdj5xd:-MkxoULk5ctxx_v62LOH:b-tnkzbm) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2808)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should be `native_entity_2_x.status.nodes.control_plane`
</blockquote></details>

thanks for catching this
___
*[container_service_extension/installer/configure_cse.py, line 2809 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxdo1J73G5mRfun6-z:-MkxoWbHAiDihRqpCSB4:bb5c5mi) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2809)):*
> thanks for catching this
___
*[container_service_extension/installer/configure_cse.py, line 2811 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-MkxdupY7KBB-JMpdRn4:-MkxoXD8EL0YKXC0RgFo:b-tnkzbm) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2811)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this should be `native_entity_2_x.status.nodes.nfs`
</blockquote></details>

thanks for catching this
___
*[container_service_extension/installer/configure_cse.py, line 2817 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxeq-a00d6ld6GW4Qw:-MkxoXxo7-qnr6ixAFdG:b-30i0gf) ([raw file](https://github.com/vmware/container-service-extension/blob/f33535cd7f550ffec5b97ff6f0080602fdf9113d/container_service_extension/installer/configure_cse.py#L2817)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nfs nodes don't have cpu and memory properties. So we shouldn't be updating nfs nodes with cpu/mem
</blockquote></details>

you are right, will remove the nfs nodes

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/server/vcdbroker.py, line 1640 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxrg0o4J2jULT-PRt9:-Mky5rKQCZN5N0OxCpMm:bb3ccsb) ([raw file](https://github.com/vmware/container-service-extension/blob/d578b00f25c1e827d0444b3fba1fc3f6d3f5e917/container_service_extension/server/vcdbroker.py#L1640)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit: List[Dict] 
</blockquote></details>

No, this function can actually send back a list of a dictionary or just a dictionary ..

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1223)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/server/vcdbroker.py, line 1640 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1223#-Mkxrg0o4J2jULT-PRt9:-MkyILVX6ifj1x7fEy7n:b-306eyb) ([raw file](https://github.com/vmware/container-service-extension/blob/d578b00f25c1e827d0444b3fba1fc3f6d3f5e917/container_service_extension/server/vcdbroker.py#L1640)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

No, this function can actually send back a list of a dictionary or just a dictionary .. 
</blockquote></details>

Sorry, I didn't notice two return statements. Saw the docstring and commented

**Pull request merged**
