### PR TITLE
[VCDA-2063, 2072] Auto negotiate api version to use from CSE client based on output of /api/cse/system

### PR DESCRIPTION
**Pull request by rocknes**
Currently CSE client blindly picks up the api version specified by the Server to communicate. However with CSE 3.1, we are expanding the number of api versions that the CSE server can concurrently support. As a result of this change the client should chose to use the highest version of api that both the server and the client understands. This PR makes the above mentioned change.

Changes:
1. Updated output of /api/cse/system to contain all api versions supported by server, boolean flag to indiicate if server is running in legacy mode.
2. Stream lined the client code to make CSE server REST calls via the CSE_CLIENT module.
3. Added logging around REST calls being made to CSE server
4. Added logging around profile management by CSE client to keep track of cli command hiding
5. Added logic in CSE client to negotiate the api version to use to talk to CSE server to be the max supported by the server and the client. In case the server is running in legacy mode, the api version is capped at 34.0.
6. Remove 'api_version' key from config file. For the interim generate the key value pair dynamically, until all it's references are removed from server side.

Testing done:
* Ran server at api v34.0, executed commands from cli, verified in wire log that the initial call is made at api 36.0 and then successive calls are made at 34.0
* Ran server at api v36.0, executed commands from cli, verified in wire log that the initial call is made at api 36.0 and then successive calls are also made at 36.0

This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/common/constants/shared_constants.py, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVXZGE07ZW910dEf5_9:-MVXZGE18ImkAAmzZV13:bxshn7k) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/common/constants/shared_constants.py#L26)):*
> ```Python
> 
> RESPONSE_MESSAGE_KEY = "message"
> CSE_SERVER_API_VERSION = "cse_server_api_version"
> ```

question: is there a standard way the code base should us single quote `'` vs double quote `"`?
___
*[container_service_extension/server/service.py, line 221 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVX_-c724VUoq2PoK0t:-MVX_-c724VUoq2PoK0u:bjewhap) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/server/service.py#L221)):*
> ```Python
>         result[shared_constants.CSE_SERVER_API_VERSION] = server_config['vcd']['api_version']  # noqa: E501
>         result[shared_constants.CSE_SERVER_SUPPORTED_API_VERSIONS] = server_config['service']['supported_api_versions']  # noqa: E501
>         result[shared_constants.CSE_SERVER_LEGACY_MODE] = server_config['service']['legacy_mode']  # noqa: E501
> ```

Will `legacy_mode` be a required param in the config? If not, then could this access for legacy_mode be a safe `get` call?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/common/constants/shared_constants.py, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVXZGE07ZW910dEf5_9:-MVXvNH_D8JjPSPBd2UQ:b2l1lwb) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/common/constants/shared_constants.py#L26)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

question: is there a standard way the code base should us single quote `'` vs double quote `"`?
</blockquote></details>

I don't think there is PEP standard for it,
How I do it - 
if it is a single small word use single quote,
if it is multiple words or a long word use double quotes.
___
*[container_service_extension/server/service.py, line 221 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVX_-c724VUoq2PoK0t:-MVXve9X2g3kCs0Cjx6D:b-ls1qo3) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/server/service.py#L221)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Will `legacy_mode` be a required param in the config? If not, then could this access for legacy_mode be a safe `get` call?
</blockquote></details>

It is a required param.

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 765 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVY24hL-_LHB_HZqXis:-MVY24hL-_LHB_HZqXit:b-tlcdx3) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/installer/configure_cse.py#L765)):*
> ```Python
>     schema_file = None
>     max_vcd_api_version_supported = \
>         max([float(x) for x in config['service']['supported_api_versions']])
> ```

While we are here, we should use semver and use max (https://python-semver.readthedocs.io/en/latest/usage.html#getting-minimum-and-maximum-of-multiple-versions)

The reason is  35.2 < 35.10 in semver but not in float for example.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955#-:-MVYvCcP38hgduSux1AM:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

___
*[container_service_extension/installer/configure_cse.py, line 765 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVY24hL-_LHB_HZqXis:-MVYrxqL6X_6kFehVNzU:biefeif) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/installer/configure_cse.py#L765)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

While we are here, we should use semver and use max (https://python-semver.readthedocs.io/en/latest/usage.html#getting-minimum-and-maximum-of-multiple-versions)

The reason is  35.2 < 35.10 in semver but not in float for example.
</blockquote></details>

Will CSE server support 35.2? Because I remember discussing this and the decision was CSE will reject calls made using minor CSE api versions.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

___
*[container_service_extension/installer/configure_cse.py, line 765 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVY24hL-_LHB_HZqXis:-MVbQiRE3T9-6udfcN63:be0hxwy) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/installer/configure_cse.py#L765)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Will CSE server support 35.2? Because I remember discussing this and the decision was CSE will reject calls made using minor CSE api versions.
</blockquote></details>

I agree with Tim, weather we support the dot versions or not, we should use semver, we already use it during upgrades. I will make the change.

**Comment by arunmk** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 765 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVY24hL-_LHB_HZqXis:-MVckQoLCyFvY49AkoQj:breai43) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/installer/configure_cse.py#L765)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I agree with Tim, weather we support the dot versions or not, we should use semver, we already use it during upgrades. I will make the change.
</blockquote></details>

Yeah irrespective of current support we should do it. @rocknes did you mean me, or am I missing a comment from Tim? My reviewable usage is quite flaky :)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2, 11 of 12 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955#-:-MVwlbNH6b-O4sisrbWW:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 21 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVwfOx_8geLY_6z7EZZ:-MVwfOx_8geLY_6z7EZ_:bno2sd2) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/cse_client/api_35/ovdc_api.py#L21)):*
> ```Python
>         self._org_vdcs_uri = f"{self._uri}/orgvdcs"
>         self._ovdc_uri = f"{self._uri}/ovdc"
>         # NOTE: The request page size is overridden because the CSE server
> ```

Shoot, I think I forgot to remove this comment. The issue is now fixed. Can you please remove this comment?
___
*[container_service_extension/server/service.py, line 221 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVwhW34-aKtDFq2Y6C1:-MVwhW34-aKtDFq2Y6C2:b56n8sj) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/server/service.py#L221)):*
> ```Python
>         result[shared_constants.CSE_SERVER_API_VERSION] = server_config['vcd']['api_version']  # noqa: E501
>         result[shared_constants.CSE_SERVER_SUPPORTED_API_VERSIONS] = server_config['service']['supported_api_versions']  # noqa: E501
>         result[shared_constants.CSE_SERVER_LEGACY_MODE] = server_config['service']['legacy_mode']  # noqa: E501
> ```

We should validate the legacy mode value against the one in the extension right?
Is this part of another task?

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 6 files at r2, 11 of 12 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/client/utils.py, line 57 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-cVCrEmNzmJRpQQ9V:-MW-cVCrEmNzmJRpQQ9W:be8pmu7) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L57)):*
> ```Python
>     :return:
>     """
>     # Always override the vcd_client by new client with CSE server api version.
> ```

Does it mean we override the api_version even when it is specified by the user as a cmd line param?
___
*[container_service_extension/client/utils.py, line 109 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-cnbL-Xkstx9Qrzhh:-MW-cnbL-Xkstx9Qrzhi:b-n8haxw) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L109)):*
> ```Python
>     cse_server_api_version = profiles.get(CSE_SERVER_API_VERSION)
>     if not is_cse_server_running:
>         CLIENT_LOGGER.debug("CSE server not running as per profile, restricting CLI to only TKG operations.")  # noqa: E501
> ```

"CSE server unreachable (or) service down". Its better we rename the variable "is_server_running" in profiles.yaml as well to "is_cse_server_reachable"
___
*[container_service_extension/client/utils.py, line 121 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-deZkBHrrhLHR2rLr:-MW-deZlEhDWk_EQQ6JV:b7r81le) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L121)):*
> ```Python
> 
>             is_pre_cse_3_1_server = False
>             if CSE_SERVER_LEGACY_MODE not in sys_info or \
> ```

Do we really need this check? Are we expecting the CSE 3.1 client to work with servers <= CSE 3.0?
We can raise an error from the Client if it finds missing values from the server response.
___
*[container_service_extension/client/utils.py, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-hIt11F91Ji8mHaYl:-MW-ewp70EHGCdK29Qpi:bk6umz4) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L130)):*
> ```Python
>                 cse_server_supported_api_versions = \
>                     set(sys_info.get(CSE_SERVER_SUPPORTED_API_VERSIONS))
>                 cse_client_supported_api_versions = \
> ```

If CSE client 3.1 talks to CSE server 3.2, then cse_client3.1 supported versions would include 37.0 as well.
I think we need separate client_supported_api_versions constant.
___
*[container_service_extension/installer/config_validator.py, line 233 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-i33d-dCTxoHdWDPL:-MW-i33d-dCTxoHdWDPM:b-mp4r6q) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/installer/config_validator.py#L233)):*
> ```Python
>         supported_api_versions_float = \
>             [float(x) for x in config['service']['supported_api_versions']
>                 if float(x) < 35.0]
> ```

It is better we do semantic version checks here.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/client/utils.py, line 54 at r5](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW0Pb4n290-1-12G1Xr:-MW0Pb4n290-1-12G1Xs:b-5k8z1v) ([raw file](https://github.com/vmware/container-service-extension/blob/7b871bb88cd59b306ef1f03776d9bc781b370be9/container_service_extension/client/utils.py#L54)):*
> ```Python
> 
>     :param <click.core.Context> ctx: click context
>     :param bool vdc_required: is vdc required or not
> ```

Would removing 'vdc_required' cause any side effect?  
nit: docstring to be updated as  vdc_required is not an method argument anymore.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955)* status: 16 of 22 files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/client/utils.py, line 57 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-cVCrEmNzmJRpQQ9V:-MW1LzE59-o3GVeJDVGr:bg5awkq) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L57)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Does it mean we override the api_version even when it is specified by the user as a cmd line param?
</blockquote></details>

Not the api_version. The original api_version is preserved in the profile. However the call to CSE server will be done at the computed api version and not what the user specified.
___
*[container_service_extension/client/utils.py, line 109 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-cnbL-Xkstx9Qrzhh:-MW1N59E0XNYTnGHi3mZ:b-k2fhy) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L109)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

"CSE server unreachable (or) service down". Its better we rename the variable "is_server_running" in profiles.yaml as well to "is_cse_server_reachable"
</blockquote></details>

Will do it in a separate story where we tackle the whole command hiding based on server reachability.
___
*[container_service_extension/client/utils.py, line 121 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-deZkBHrrhLHR2rLr:-MW1NCKh5FYNUUFt4P-B:b-no7tcu) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L121)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do we really need this check? Are we expecting the CSE 3.1 client to work with servers <= CSE 3.0?
We can raise an error from the Client if it finds missing values from the server response.
</blockquote></details>

I see this as defensive coding, instead of failing with a cryptic error, since we have a good fallback value, we should use it.
___
*[container_service_extension/client/utils.py, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-hIt11F91Ji8mHaYl:-MW1NW8RDDelsBjMP5kn:b9r1jxt) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L130)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If CSE client 3.1 talks to CSE server 3.2, then cse_client3.1 supported versions would include 37.0 as well.
I think we need separate client_supported_api_versions constant.
</blockquote></details>

The 3.1 client's binary will have the values 34.0, 35.0, 36.0
while 3.2 server's binary will have the values 35.0, 36.0, 37.0

We don't need two separate variables. The different binaries will have different supported api values.
___
*[container_service_extension/client/utils.py, line 54 at r5](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW0Pb4n290-1-12G1Xr:-MW1OHl504QjLYzMWI7i:btevweu) ([raw file](https://github.com/vmware/container-service-extension/blob/7b871bb88cd59b306ef1f03776d9bc781b370be9/container_service_extension/client/utils.py#L54)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Would removing 'vdc_required' cause any side effect?  
nit: docstring to be updated as  vdc_required is not an method argument anymore. 
</blockquote></details>

I didn't find a single call to cse_restore_session that uses the param.
Thanks for catching the doc string error, will fix it.
___
*[container_service_extension/client/cse_client/api_35/ovdc_api.py, line 21 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVwfOx_8geLY_6z7EZZ:-MW1O1hk45bY8vohqLI8:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/cse_client/api_35/ovdc_api.py#L21)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Shoot, I think I forgot to remove this comment. The issue is now fixed. Can you please remove this comment?
</blockquote></details>

done
___
*[container_service_extension/installer/config_validator.py, line 233 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-i33d-dCTxoHdWDPL:-MW1O3x93W303YdEh4ld:b-fws016) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/installer/config_validator.py#L233)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It is better we do semantic version checks here.
</blockquote></details>

Yes, will address it in the next PR
___
*[container_service_extension/installer/configure_cse.py, line 765 at r1](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVY24hL-_LHB_HZqXis:-MVtgEZI2u2rctFnBCy5:bfnzd6t) ([raw file](https://github.com/vmware/container-service-extension/blob/83705ff80b8bc9b9820ad29f708830cf0535c30e/container_service_extension/installer/configure_cse.py#L765)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Yeah irrespective of current support we should do it. @rocknes did you mean me, or am I missing a comment from Tim? My reviewable usage is quite flaky :)
</blockquote></details>

Sorry I mistyped Tim :)
___
*[container_service_extension/server/service.py, line 221 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MVwhW34-aKtDFq2Y6C1:-MW1O8f5-DX--m2fk3cy:byjd6f6) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/server/service.py#L221)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

We should validate the legacy mode value against the one in the extension right?
Is this part of another task?
</blockquote></details>

Yes, it will be done as part of the next PR, where we would write the value to the extension and read it back for validation during cse run etc.

**Review by sahithi — APPROVED** [review]
:lgtm: _is_pre_cse_31_server check seems unnecessary to me. I think the logic will look simple without it.

> Reviewed 1 of 1 files at r5, 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/955#-:-MW1WU8A-BsVtzfB7Min:blwohr9)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/client/utils.py, line 121 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-deZkBHrrhLHR2rLr:-MW1VpRq0_YIxVzoQ_Qm:bek7csn) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L121)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I see this as defensive coding, instead of failing with a cryptic error, since we have a good fallback value, we should use it.
</blockquote></details>

I don't see the need as there is no real use-case.
___
*[container_service_extension/client/utils.py, line 130 at r4](https://reviewable.io/reviews/vmware/container-service-extension/955#-MW-hIt11F91Ji8mHaYl:-MW1V8Kn5Zrdb1GgTnjo:b-lr06h0) ([raw file](https://github.com/vmware/container-service-extension/blob/ef924e0c76e459cf21f2af20d213a568d8ca4fe4/container_service_extension/client/utils.py#L130)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The 3.1 client's binary will have the values 34.0, 35.0, 36.0
while 3.2 server's binary will have the values 35.0, 36.0, 37.0

We don't need two separate variables. The different binaries will have different supported api values.
</blockquote></details>

yes, that's right!

**Pull request merged**
