### PR TITLE
[VCDA-3194] Make accessing CSE server runtime config thread safe

### PR DESCRIPTION
**Pull request by rocknes**
Introduced a new object `ServerConfig` that encapsulates the configuration dictionary of Service object and makes access to the configuration thread safe.

This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
> Reviewed 2 of 7 files at r1, 4 of 12 files at r2, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303)* status: 18 of 23 files reviewed, all discussions resolved (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed 3 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by ltimothy7 — COMMENTED** [review]
This looks good to me, but just a comment for clarification before approving

> Reviewed 2 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303#-:-Mv_9DUr8GjUMWKM1Py5:b-rfi0rq)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 221 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1303#-Mv_7VmX7mUJntohcdgu:-Mv_7VmYBArojz_6QmK1:burwv19) ([raw file](https://github.com/vmware/container-service-extension/blob/4c2a32b659e82272c9a2e16c1aa5a470dc266a87/container_service_extension/installer/config_validator.py#L221)):*
> ```Python
>         vcd_host=config['vcd']['host'],
>         vcd_username=config['vcd']['username'],
>         vcd_password=config['vcd']['password'],
> ```

Should this config also use the thread safe config map and the `get_value_at` function?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/installer/config_validator.py, line 221 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1303#-Mv_7VmX7mUJntohcdgu:-Mv_LQcIBqj7e-pa0HK5:b-6r9yf) ([raw file](https://github.com/vmware/container-service-extension/blob/4c2a32b659e82272c9a2e16c1aa5a470dc266a87/container_service_extension/installer/config_validator.py#L221)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this config also use the thread safe config map and the `get_value_at` function?
</blockquote></details>

Thread safety comes into picture only  when the server is running. All the server CLI commands are running in a single thread and are the only one accessing the config dict, so it is safe to not use the ServerConfig object for these operations.

To  be honest, I tried changing them too, but there are so many indirect references to  the dict object, changing all  of them to the new object model turned out to be a lot more complicated that I imagined and hence left  them alone.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1303)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/config/server_config.py, line 190 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1303#-Mv_WU7I0ScHMV_bIR7t:-Mv_jlQf4evzVd0JlAEq:bjs3x3z) ([raw file](https://github.com/vmware/container-service-extension/blob/4c2a32b659e82272c9a2e16c1aa5a470dc266a87/container_service_extension/config/server_config.py#L190)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just curious, Is there any use of returning the old value for the key?
</blockquote></details>

Nothing specific,  it is just the same pattern used for stacks/queues. There is no intrinsic value in doing this though :)

**Pull request merged**
