### PR TITLE
[VCDA-1612] vcd cse cluster remove-nfs CLI

### PR DESCRIPTION
**Pull request by sakthisunda**
- CLI support for`vcd cse cluster remove-nfs <cluster-name> <nfs-node-name>` for native Kubernetes cluster
- Manually tested and verified (screenshot below)
-------
image

image

image

@Anirudh9794 @rocknes @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/731)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/731)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/client/cse.py, line 655 at r1](https://reviewable.io/reviews/vmware/container-service-extension/731#-MGLJlcu6So36zdk1SOz:-MGLJlcu6So36zdk1SP-:bfzytmy) ([raw file](https://github.com/vmware/container-service-extension/blob/541cb2c57505b697ae58d16d0c100ad74cccb2ac/container_service_extension/client/cse.py#L655)):*
> ```Python
> 
> 
> @cluster_group.command('remove-nfs',
> ```

Can we use _delete-nfs_ instead of _remove-nfs_ to keep it consistent with other _delete_ commands.

Please rename at all other places too.
___
*[container_service_extension/client/cse.py, line 686 at r1](https://reviewable.io/reviews/vmware/container-service-extension/731#-MGLKsD55TqPolB73HF2:-MGLKsD55TqPolB73HF3:b-qkr6hs) ([raw file](https://github.com/vmware/container-service-extension/blob/541cb2c57505b697ae58d16d0c100ad74cccb2ac/container_service_extension/client/cse.py#L686)):*
> ```
> cluster = Cluster(client)
>         result = cluster.remove_nfs_node(cluster_name, node_name, org=org, vdc=vdc)  # noqa: E501
> ```
We can directly initialize _NativeClusterApi_ here as NFS deletion is relevant to only Native.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/731)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/client/cse.py, line 655 at r1](https://reviewable.io/reviews/vmware/container-service-extension/731#-MGLJlcu6So36zdk1SOz:-MGLTPWb4igonntHTOhF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/541cb2c57505b697ae58d16d0c100ad74cccb2ac/container_service_extension/client/cse.py#L655)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we use _delete-nfs_ instead of _remove-nfs_ to keep it consistent with other _delete_ commands.

Please rename at all other places too.
</blockquote></details>

Done.
___
*[container_service_extension/client/cse.py, line 686 at r1](https://reviewable.io/reviews/vmware/container-service-extension/731#-MGLKsD55TqPolB73HF2:-MGLTQwr8YpdZWuOCB5-:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/541cb2c57505b697ae58d16d0c100ad74cccb2ac/container_service_extension/client/cse.py#L686)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> cluster = Cluster(client)
>         result = cluster.remove_nfs_node(cluster_name, node_name, org=org, vdc=vdc)  # noqa: E501
> ```
We can directly initialize _NativeClusterApi_ here as NFS deletion is relevant to only Native.
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/731)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @sahithi)

**Comment by Anirudh9794** [comment]
:lgtm: once merge conflicts are resolved

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/731#-:-MGon9Bb4FauQPPuaC9T:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)

**Pull request merged**
