### PR TITLE
[VCDA 1950] Add source to telemetry

### PR DESCRIPTION
**Pull request by sakthisunda**
-  Add source of CSE server request to telemetry tables 
-  CSE telemetry to record the type of client that make HTTP Requests to CSE server
-  Added two new columns to telemetry table: source_id and source_description
-  Testing done by running CLI thru `vcd cli, postman, curl
-  Retested all native cluster commands 
-  Retested all defined entity cluster commands 
- SOURCE_ID getting processed from thread local data
- **TODO - Adding source to PKS telemetry tables (Testbed build is failing)**

--------
cse_v35_cluster_list 
image

cse_v35_cluster_info
image

cse_v35_cluster_apply
image

cse_ovdc_enable
image

cse_ovdc_list
image

@Anirudh9794 @rocknes @ltimothy7 

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/857)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 9 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/857#-:-MOrhs3S2uHVXPfAp25_:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/857)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/server_constants.py, line 87 at r2](https://reviewable.io/reviews/vmware/container-service-extension/857#-MOrsJEm9LGTA7NRCXnq:-MOrsJEm9LGTA7NRCXnr:b-5qev60) ([raw file](https://github.com/vmware/container-service-extension/blob/1483ee0af7296a7809c6d6479fe67f400a209d47/container_service_extension/server_constants.py#L87)):*
> ```Python
> REQUEST_ID = 'request_id'
> 
> # User Agent for telemetry
> ```

nit: Would you be able to  put REQUEST_ID and USER_AGENT into an Enum for THREAD_DATA_KEYS or a similar name?
___
*[container_service_extension/telemetry/constants.py, line 193 at r2](https://reviewable.io/reviews/vmware/container-service-extension/857#-MOrtwBB86ezV8WO1CDb:-MOrtwBB86ezV8WO1CDc:b-80qpce) ([raw file](https://github.com/vmware/container-service-extension/blob/1483ee0af7296a7809c6d6479fe67f400a209d47/container_service_extension/telemetry/constants.py#L193)):*
> ```Python
>             return SourceMap.UNKNOWN.name
>         for source_entry in SourceMap:
>             if source_entry.value in user_agent.lower():
> ```

Isn't it possible for the user_agent str to contain multiple sources? For example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36" contains both chrome and safari. What was the conclusion on how we should handle these cases?
Even though we are including the full source description, I think it is a bit misleading if we only include one of the source id's.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/857)* status: 2 of 11 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/server_constants.py, line 87 at r2](https://reviewable.io/reviews/vmware/container-service-extension/857#-MOrsJEm9LGTA7NRCXnq:-MOsHPH9Dx4QeqJFdY7H:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/1483ee0af7296a7809c6d6479fe67f400a209d47/container_service_extension/server_constants.py#L87)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: Would you be able to  put REQUEST_ID and USER_AGENT into an Enum for THREAD_DATA_KEYS or a similar name?
</blockquote></details>

Done
___
*[container_service_extension/telemetry/constants.py, line 193 at r2](https://reviewable.io/reviews/vmware/container-service-extension/857#-MOrtwBB86ezV8WO1CDb:-MOsHWe5-hX7zgmPKme9:b-dos0zh) ([raw file](https://github.com/vmware/container-service-extension/blob/1483ee0af7296a7809c6d6479fe67f400a209d47/container_service_extension/telemetry/constants.py#L193)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Isn't it possible for the user_agent str to contain multiple sources? For example: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36" contains both chrome and safari. What was the conclusion on how we should handle these cases?
Even though we are including the full source description, I think it is a bit misleading if we only include one of the source id's.
</blockquote></details>

Based on: https://www.whatismybrowser.com/guides/the-latest-user-agent/safari: user agent for safari doesn't have 'Chrome'.
Also, for other supported browsers (user agents), the order of  enum keys defined here catches the correcct user-agent. For microsoft edge, you have uniquely identifiable string. In this code, that is checked first, then chrome and finally safari.  Any unsupported browser, we record the user agent and UNKNOWN as id.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/857)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Pull request merged**
