### PR TITLE
[VCDA-2319]Allow conditional firing of the hooks

### PR DESCRIPTION
**Pull request by sahithi**
Suppress hooks while updating RDEs.
Tested in a CSE-VCD environment with hook-based behaviors for native entity type 2.0

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1016)

### CODE REVIEW

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 229 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1016#-MYpFQRr1EhfH-mEj4i5:-MYpFQRr1EhfH-mEj4i6:b-2fszmt) ([raw file](https://github.com/vmware/container-service-extension/blob/8790ed8582cd33f124a7bfd4c88c5d34892b54b8/container_service_extension/rde/common/entity_service.py#L229)):*
> ```Python
>         """Update entity instance.
> 
>         :param invoke_hooks:
> ```

duplicate doc string to be removed

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1016#-:-MYpt2e7A5nz0MLJUDvT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 239 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1016#-MYpt7pVEoZYPkilmmT_:-MYpt7pVEoZYPkilmmTa:bjqizls) ([raw file](https://github.com/vmware/container-service-extension/blob/8790ed8582cd33f124a7bfd4c88c5d34892b54b8/container_service_extension/rde/common/entity_service.py#L239)):*
> ```Python
>         resource_url_relative_path = f"{CloudApiResource.ENTITIES}/{entity_id}"
>         vcd_api_version = self._cloudapi_client.get_api_version()
>         if float(vcd_api_version) >= float(ApiVersion.VERSION_36.value):
> ```

Just FYI: the float way of comparing api versions is becoming dangerous with the introduction of minor api versions.

e.g. float(35.10) is < float(35.2)

Sakthi has a task in backlog to unify vcd api version comparison via tuple comparisons.

(35,10) is > (35, 2)

Please add a ToDo here to track it.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1016)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/rde/common/entity_service.py, line 229 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1016#-MYpFQRr1EhfH-mEj4i5:-MYq9HMY8rT7zwjVUaKC:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8790ed8582cd33f124a7bfd4c88c5d34892b54b8/container_service_extension/rde/common/entity_service.py#L229)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

duplicate doc string to be removed
</blockquote></details>

Done.
___
*[container_service_extension/rde/common/entity_service.py, line 239 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1016#-MYpt7pVEoZYPkilmmT_:-MYq9JV8-J5vzPegAQ9S:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/8790ed8582cd33f124a7bfd4c88c5d34892b54b8/container_service_extension/rde/common/entity_service.py#L239)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Just FYI: the float way of comparing api versions is becoming dangerous with the introduction of minor api versions.

e.g. float(35.10) is < float(35.2)

Sakthi has a task in backlog to unify vcd api version comparison via tuple comparisons.

(35,10) is > (35, 2)

Please add a ToDo here to track it.
</blockquote></details>

Done

**Pull request merged**
