### PR TITLE
[VCDA-2479] prevent AMQP configuration with CSE 3.1 non-legacy mode and 10.3 VCD

### PR DESCRIPTION
**Pull request by Anirudh9794**
…on-legacy mode

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

As CSE 3.1 uses behaviors when configured with VCD 10.3 and behaviors can only work with MQTT, it is not possible to support AMQP with CSE 3.1 and VCD 10.3 vcd.
Changes done:
- Config validator raises error when AMQP is configured and maximum api version is 36.0

Testing done:
- Install CSE with AMQP and vcd 10.3, check for error messages
- Install CSE with MQTT and 10.3, no errors should be thrown

@rocknes @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/installer/config_validator.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNMqHAfuhDPZOd8tH:-MaoNMqHAfuhDPZOd8tI:b-kincvu) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L62)):*
> ```Python
> 
> 
> _AMQP_MAX_API_VERSION = '35.0'
> ```

_AMQP_MAX_API_VERSION_FOR_LEGACY_MODE_FALSE
___
*[container_service_extension/installer/config_validator.py, line 296 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNa7X9QWMiRZ1K_Yw:-MaoNa7X9QWMiRZ1K_Yx:bnoq6yd) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L296)):*
> ```Python
>     :raises: AmqpError
>     """
>     if not is_mqtt_used and float(default_api_version) > float(_AMQP_MAX_API_VERSION):  # noqa: E501
> ```

AMQP still should continue to work if legacy_mode is set to true, even with api_version=36. Is this condition taken care of?

**Review by sahithi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/config_validator.py, line 296 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNa7X9QWMiRZ1K_Yw:-Mb7YN7B7n74YgA1xymV:bc16v71) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L296)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

AMQP still should continue to work if legacy_mode is set to true, even with api_version=36. Is this condition taken care of?
</blockquote></details>

yes. if legacy_mode is set to true, the boolean `is_mqtt_used` will be false.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNMqHAfuhDPZOd8tH:-Mb93AlfEOhNNIXeveAA:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L62)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

_AMQP_MAX_API_VERSION_FOR_LEGACY_MODE_FALSE
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm: once the variable name is fixed.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048#-:-MbD2r4WC9FlTcZu2dot:b-g5esv4)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNMqHAfuhDPZOd8tH:-MbD2QjZ1f7wue21nVHt:bkp8dex) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L62)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

_MAX_API_VERSION_TO_RUN_CSE_WITH_AMQP_IN_NON_LEGACY_MODE

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1048#-MaoNMqHAfuhDPZOd8tH:-MbDF09n8I-y5qdlLjWk:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/4ecb39442a55e16bbd048ae787a7e350339a0c11/container_service_extension/installer/config_validator.py#L62)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

_MAX_API_VERSION_TO_RUN_CSE_WITH_AMQP_IN_NON_LEGACY_MODE
</blockquote></details>

Done.

**Pull request merged**
