### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by gmcelhoe**
Adds an implemenation of a Dockerfile, to deliver the CSE
command line as a single container.

Following VMware open source policies, the base image of the Dockerfile
is Photon OS, and the source code for the extension is loaded
from source instead of downloading from PyPi, for cleaner provenance.

Because the code isn't loaded by PyPi, the version
code that used pkgconfig needed to be changed.  Now
the version file will be built from environment
variables.

Finally, to build the docker images, added a makefile.
It may be a good chance to add some of the random script
files currently in the project into the makefile.

Included is a manually generated OSS tracking file.

Signed-off-by: Glenn McElhoe <gmcelhoe@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @gmcelhoe)

___
*[Makefile, line 56 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6BuQ3u9TTRja3Yc4:-Lav6BuQ3u9TTRja3Yc5:b-kfguyz) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/Makefile#L56)):*
> ```Makefile
> 		requirements.txt \
> 		cse.sh \
> 		container_service_extension/*.py \
> ```

I am not sure if we are planning to have pks support in the dockerized cse or not.
But we might want to include the folders inside container_service_extension folder.
___
*[container_service_extension/cse.py, line 114 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6mRF3we-BqtAeON5:-Lav6mRG9JbJUhCBY3gy:b-okjhaf) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/container_service_extension/cse.py#L114)):*
> ```Python
>     if local:
>         try:
>             from container_service_extension.version import __version__
> ```

Did you forget to check-in version.py ? I don't see it as part of the review.
___
*[container_service_extension/cse.py, line 117 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav710XA2slfnag3RqP:-Lav710XA2slfnag3RqQ:b-24gihx) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/container_service_extension/cse.py#L117)):*
> ```Python
>             ver_obj = __version__
>         except ImportError:
>             ver_obj = {}
> ```

Probably we should fill in the minimum set of key-value pairs that we are referencing in next few lines, else we will hit a KeyError for sure.

**Review by gmcelhoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @rocknes)

___
*[Makefile, line 56 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6BuQ3u9TTRja3Yc4:-Lav7lHs6R0d2GY7BZdH:boi17nz) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/Makefile#L56)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I am not sure if we are planning to have pks support in the dockerized cse or not.
But we might want to include the folders inside container_service_extension folder.
</blockquote></details>

I wasn't putting client code in the container (I thought that would be part of containerizing the `vcd` command)
___
*[container_service_extension/cse.py, line 114 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6mRF3we-BqtAeON5:-Lav88173YnZ99rKXfnx:belwxdn) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/container_service_extension/cse.py#L114)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Did you forget to check-in version.py ? I don't see it as part of the review.
</blockquote></details>

version.py is generated by the gobuild scripts.  If it doesn't exist, then we assume this is a non-containerized build.  In that case, it should fall back to the old code which assumes that the pypi dependency is the correct version.
___
*[container_service_extension/cse.py, line 117 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav710XA2slfnag3RqP:-LavJdCnAtd67MCnY2Qn:btypeye) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/container_service_extension/cse.py#L117)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Probably we should fill in the minimum set of key-value pairs that we are referencing in next few lines, else we will hit a KeyError for sure.
</blockquote></details>

Fixed the code to reflect my intent above.

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273#-:-Lavqi37CSQtrAPXgZ20:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @gmcelhoe)

___
*[Makefile, line 56 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6BuQ3u9TTRja3Yc4:-LavpguR1hX3yN2GIK19:b7jhbzb) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/Makefile#L56)):*
<details><summary><i>Previously, gmcelhoe (Glenn McElhoe) wrote…</i></summary><blockquote>

I wasn't putting client code in the container (I thought that would be part of containerizing the `vcd` command)
</blockquote></details>

The server code right now is aware of PKS and relies on the contents of the folder pksclient to talk to PKS instances.  If we are deciding to package the server without those files, we will not be able to deploy clusters on PKS. I just want to make sure that this is an informed choice :)

**Review by gmcelhoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[Makefile, line 56 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6BuQ3u9TTRja3Yc4:-Lavszvp9pL0SlRKXnAM:b-xx6cac) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/Makefile#L56)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The server code right now is aware of PKS and relies on the contents of the folder pksclient to talk to PKS instances.  If we are deciding to package the server without those files, we will not be able to deploy clusters on PKS. I just want to make sure that this is an informed choice :)
</blockquote></details>

I double-checked and the copy is a deep copy, so they are there.  But in testing I realized I had made a mistake on the requirements.txt file.   That is fixed, so we should be good to go.

**Comment by gmcelhoe** [comment]
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lc2kv_tBQXYAJFUEsSp:-Lc2kv_u-pTVhl6D0seS:bzazl96) (no related file):*
Any more concerns?

---

**Review by gmcelhoe — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[Makefile, line 56 at r4](https://reviewable.io/reviews/vmware/container-service-extension/273#-Lav6BuQ3u9TTRja3Yc4:-LazS9GH79RSsCThj1oV:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/31f1a6f9a3a0197bce7583682ac2608494b9038c/Makefile#L56)):*
<details><summary><i>Previously, gmcelhoe (Glenn McElhoe) wrote…</i></summary><blockquote>

I double-checked and the copy is a deep copy, so they are there.  But in testing I realized I had made a mistake on the requirements.txt file.   That is fixed, so we should be good to go.
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/273)* status: all files reviewed, 1 unresolved discussion

**Pull request closed without merging**
