### PR TITLE
[VCDA-2472 & VCDA-2545] Use version key in template yaml instead of depending on naming

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Template .yaml should contain a version key which will help identifying the template script structure
* Remove hard coding of script directory path. Use script_directory key in template.yaml

Testing done:
* Install CSE 3.1 using cookbook with version 1.0 -> should fail with proper error message
* Install CSE 3.1 using cookbook with version 2.0 and install a template

@rocknes @sahithi @sakthisunda @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/installer/configure_cse.py, line 1612 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-xT7B5ft7Dq11Lwv:-MbD-xT7B5ft7Dq11Lww:b-d907uw) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/configure_cse.py#L1612)):*
> ```Python
>         catalog_item_name = ltm.get_revisioned_template_name(
>             template[server_constants.LocalTemplateKey.NAME],
>             template[server_constants.LocalTemplateKey.REVISION])
> ```

Why the change from RemoteTemplateKey.Name => LocalTemplateKey.NAME 
Is it for backward compatibility?
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-F9T1Mah5cD2z7Pr:-MbD-F9T1Mah5cD2z7Ps:b-7rep9m) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_template_manager.py#L188)):*
> ```
> f"incompatible with CSE executing in legacy_mode:
> ```
f"incompatible with CSE running in legacy_mode:"
___
*[container_service_extension/installer/templates/remote_cookbooks/cookbook_model, line 0 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-j4K4yOSETHBOJVf:-MbD-j4K4yOSETHBOJVg:b-bo5gdh) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_cookbooks/cookbook_model#L0)):*
showing up as empty file. Is this intended for deletion?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/installer/templates/remote_template_manager.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-F9T1Mah5cD2z7Pr:-MbD6c5aC_TCP-ejEX1t:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_template_manager.py#L188)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> f"incompatible with CSE executing in legacy_mode:
> ```
f"incompatible with CSE running in legacy_mode:"
</blockquote></details>

Done.
___
*[container_service_extension/installer/templates/remote_cookbooks/cookbook_model, line  at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-j4K4yOSETHBOJVf:-MbD69oM3UTmgB64YXjL:b46pimi) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_cookbooks/cookbook_model#L)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

showing up as empty file. Is this intended for deletion?
</blockquote></details>

Created this file by mistake. Will remove this file

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 1612 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-xT7B5ft7Dq11Lwv:-MbD6znVElbjGQOt26OH:brsehpi) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/configure_cse.py#L1612)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Why the change from RemoteTemplateKey.Name => LocalTemplateKey.NAME 
Is it for backward compatibility?
</blockquote></details>

The `template` dictionary here is a local template (VCD template metadata) and not a remote template (Cookbook template descriptor). So I thought it makes more sense to use `LocalTemplateKey`

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/common/utils/server_utils.py, line 111 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDB1FOCvsYl3-Attc5:-MbDB1FP-1uCU3_iJ14L:b-3hn6vf) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/common/utils/server_utils.py#L111)):*
> ```Python
> 
> 
> def get_template_descriptor_keys(cookbook_version):
> ```

def get_template_descriptor_keys(cookbook_version) -> enum.EnumMeta:

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/common/constants/server_constants.py, line 330 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDZ6yn10INnXMjbfkJ:-MbDZ6yoAL0_aBUNjQmg:b-ptz2wg) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/common/constants/server_constants.py#L330)):*
> ```Python
>     CNI = 'cni'
>     CNI_VERSION = 'cni_version'
>     COMPUTE_POLICY = 'compute_policy'
> ```

This can be removed. Since we no longer allow user defined compute policy for templates
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-F9T1Mah5cD2z7Pr:-MbD_bINE59FKGy5cJNU:bcqz3cc) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_template_manager.py#L188)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

make the legacy mode part of the msg conditional

if self.legacy_mode:
 msg += "running in legacy mode"
else:
 msg+= "running in non legacy mode"
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 69 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDZurtEZVZcyxDAmKx:-MbDZuru49rMZlcV0hLR:b-b3veil) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/installer/templates/remote_template_manager.py#L69)):*
> ```Python
>         self.scripts_directory_path = None
> 
>     def _get_base_url_from_remote_template_cookbook_url(self):
> ```

Add a doc string explaining what is returned with an example.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 111 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD_A1O9h4F7DGLJAtY:-MbD_A1O9h4F7DGLJAtZ:b-5v37z3) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/installer/templates/remote_template_manager.py#L111)):*
> ```Python
>             return
>         # Cookbook version 1.0 doesn't have supported version information.
>         if self.cookbook_version == '1.0':
> ```

The version should be 1.0.0, 2.0.0 etc.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 330 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDZ6yn10INnXMjbfkJ:-MbE1fXP2KwoeFZFCQoF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/common/constants/server_constants.py#L330)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This can be removed. Since we no longer allow user defined compute policy for templates
</blockquote></details>

Done.
___
*[container_service_extension/common/utils/server_utils.py, line 111 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDB1FOCvsYl3-Attc5:-MbE2-HoBah3aUchAdnc:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/common/utils/server_utils.py#L111)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

def get_template_descriptor_keys(cookbook_version) -> enum.EnumMeta:
</blockquote></details>

Done.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD-F9T1Mah5cD2z7Pr:-MbEBCW_7rU3hEGv5wKZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c00ea8268bd979ef6aa4e9219fcda4177da64058/container_service_extension/installer/templates/remote_template_manager.py#L188)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

make the legacy mode part of the msg conditional

if self.legacy_mode:
 msg += "running in legacy mode"
else:
 msg+= "running in non legacy mode"
</blockquote></details>

Done.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 69 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbDZurtEZVZcyxDAmKx:-MbE2oKC-fcVWPsIyggs:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/installer/templates/remote_template_manager.py#L69)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Add a doc string explaining what is returned with an example.
</blockquote></details>

Done.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 111 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbD_A1O9h4F7DGLJAtY:-MbE3tY16GautQqUMWQy:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c6e04cd2e6b56a7295584a970c407cd5b44b1061/container_service_extension/installer/templates/remote_template_manager.py#L111)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The version should be 1.0.0, 2.0.0 etc.
</blockquote></details>

Done.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @rocknes and @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/installer/templates/remote_template_manager.py, line 121 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbHhXWH-yxV9LtnTlaD:-MbHhXWI75hlgwG9WI2c:b-y0odig) ([raw file](https://github.com/vmware/container-service-extension/blob/d9efdc456745b0e6c1b61dd16d5e7dde200aebf2/container_service_extension/installer/templates/remote_template_manager.py#L121)):*
> ```Python
>             return
>         # Cookbook version 1.0 doesn't have supported version information.
>         if self.cookbook_version < \
> ```

cookbook_version is a string, are we comparing strings?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 121 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbHhXWH-yxV9LtnTlaD:-MbHnml7DJgLlSrAi-OE:bm81vyy) ([raw file](https://github.com/vmware/container-service-extension/blob/d9efdc456745b0e6c1b61dd16d5e7dde200aebf2/container_service_extension/installer/templates/remote_template_manager.py#L121)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

cookbook_version is a string, are we comparing strings?
</blockquote></details>

Sorry, I forgot to update the annotation in init() but I changed the value of cookbook_version to Version object (in get_unfiltered_templates() where value is being assigned)

**Review by rocknes — CHANGES_REQUESTED** [review]
> please see my comment in server_utils.py
:lgtm: once all outstanding comments are taken care of.

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1052#-:-MbePdh_0kBVmcgppBzn:b-vbzmw1)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/common/utils/server_utils.py, line 112 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbeOri42OnX4CvH2ZnI:-MbeOri68ETR0nnvo_xi:bv2jjyk) ([raw file](https://github.com/vmware/container-service-extension/blob/d4e18dd3f9fad4f8355b09066ed46f4490229472/container_service_extension/common/utils/server_utils.py#L112)):*
> ```Python
> 
> 
> def get_template_descriptor_keys(cookbook_version: str) -> enum.EnumMeta:
> ```

I would suggest that the param be Version object. I am seeing a lot of str() calls on the params before calling this method.
We can convert the Version object into string inside this method, thereby .excusing all the callers from doing type conversions.
___
*[container_service_extension/server/cli/server_cli.py, line 1045 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1052#-MbePVvY1PA4ok-Edevx:-MbePVvY1PA4ok-Edevy:b-h0hkle) ([raw file](https://github.com/vmware/container-service-extension/blob/d4e18dd3f9fad4f8355b09066ed46f4490229472/container_service_extension/server/cli/server_cli.py#L1045)):*
> ```Python
>             remote_template_definitions = remote_template_cookbook['templates']
>             remote_template_keys = server_utils.get_template_descriptor_keys(
>                 str(rtm.cookbook_version))
> ```

please see my comment in server_utils.py

**Pull request merged**
