### PR TITLE
VCDA-2146: Implement Behavior service

### PR DESCRIPTION
**Pull request by sahithi**
Implemented _behavior_service.py_

1. CRUDL methods to operate behaviors on the interface.
2. Get, override, list, and delete behaviors on the entity type. Note that creating behavior directly on the entity type throws an error and it may be removed altogether in the subsequent PRs. Currently under discussion with the Extensibility team.
3. Methods to retrieve and update ACLS on the behaviors of the entity type.

Tested all the methods individually. Added TODO in those methods with bugs (or) errors.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 105 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFA1erE-vS2Y-NnVfe:-MUFA1es0xdhlp4mDwfw:bz5839x) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L105)):*
> ```Python
>         """
>         behaviors = self.list_behaviors_on_interface(interface_id=interface_id)
>         matched_behaviors = [behavior for behavior in behaviors
> ```

```
for behavior in behaviors:
  if behavior.name == behavior_name:
    return behavior
```
this prevents making additional REST calls to find all the behaviors.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFAdJL-liBZijm5_ou:-MUFAdJL-liBZijm5_ov:b-x4qjr7) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L109)):*
> ```Python
>         return matched_behaviors[0]
> 
>     def delete_behavior_on_interface(self, behavior_id, interface_id):
> ```

nit: `delete_behavior_on_interface` to`delete_behavior_on_interface_by_id`

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUFBJh3Dlf0Lp_6dnPw:bwo7wo5) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
> ```Python
>         """
>         if not self._cloudapi_client.is_sys_admin:
>             raise ValueError("Cloud API Client should be sysadmin.")
> ```

Won't the cloudAPi client return error if non-sysadmin users use this method?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 152 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBnmA2lodnDOniXfR:-MUFBnmA2lodnDOniXfS:b7rz4e1) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L152)):*
> ```Python
>         Only Execution portion of the Behavior can be overridden.
> 
>         @param behavior: The updated behavior to be overridden on the entity-type.  # noqa: E501
> ```

is `@` in docstrings intended. If so, when should @ should be used in doctrings?

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFG9NB_OwQ4fur5Ft:-MUFFG9NB_OwQ4fur5Fu:bpeztn4) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L59)):*
> ```Python
>         return Behavior(**response_body)
> 
>     def list_behaviors_on_interface(self, interface_id) -> List[Behavior]:
> ```

Return type hint should be `Iterator[Behavior]`
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 168 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFuv8A11hZhZmhMvL:-MUFFuv8A11hZhZmhMvM:b-iocotc) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L168)):*
> ```Python
>         return Behavior(**response_body)
> 
>     def list_behaviors_on_entity_type(self, entity_type_id) -> List[Behavior]:
> ```

return hint should be `Iterator[Behavior]`
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 220 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFCRP7EryuO-voUfsw:-MUFCRP7EryuO-voUfsx:b-cggvm6) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L220)):*
> ```Python
>         #  endpoint.
>         behaviors = self.list_behaviors_on_entity_type(entity_type_id=entity_type_id)  # noqa: E501
>         matched_behaviors = [behavior for behavior in behaviors
> ```

Multiple REST calls can be avoided here too by using `for .... return` code.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFEUDS66ZPfH4z_8ib:-MUFEUDS66ZPfH4z_8ic:b3unrpe) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L224)):*
> ```Python
>         return matched_behaviors[0]
> 
>     def delete_behavior_on_entity_type(self, behavior_interface_id, entity_type_id):  # noqa: E501
> ```

Is there any reason `behavior_interface_id` is used instead of just `behavior_id`? If there are no difference, which term is the correct one?
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFUec-1LVSpckpt4L:-MUFFUec-1LVSpckpt4M:b-cvl7p7) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L242)):*
> ```Python
>                                        f"/{behavior_interface_id}")
> 
>     def get_behavior_acls_on_entity_type(self, entity_type_id: str) -> List[BehaviorAclEntry]:  # noqa: E501
> ```

nit: `get_behavior_acls_on_entity_type` -> `list_behavior_acls_on_entity_type`
and why is the return type a list unlike Iterators in other list operations?
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFGeEg9a7NAm29GiEJ:-MUFGeEg9a7NAm29GiEK:b5b6yrl) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L283)):*
> ```Python
> 
>     def invoke_behavior(self, entity_id: str, behavior_interface_id: str,
>                         arguments: dict = None):
> ```

Is it ok if `None` is sent as payload for a POST request?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: all files reviewed, 10 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFG9NB_OwQ4fur5Ft:-MUFMd1F477vCliBW9UM:b43eaps) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L59)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Return type hint should be `Iterator[Behavior]`
</blockquote></details>

thanks for catching this.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 105 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFA1erE-vS2Y-NnVfe:-MUFMh-C8GdhQpy9ggC0:br2klx) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L105)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

```
for behavior in behaviors:
  if behavior.name == behavior_name:
    return behavior
```
this prevents making additional REST calls to find all the behaviors.
</blockquote></details>

I intentionally made it this way for now. It is not yet clear if duplicate behaviors can exist. I  have sent this out as part of my Q-list to Teo.
I will add a TODO here until then.

If  duplicates are allowed, GET call also would end up returning a list 
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFAdJL-liBZijm5_ou:-MUFTu6dAaf5kY1mvQXL:b-df488b) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L109)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nit: `delete_behavior_on_interface` to`delete_behavior_on_interface_by_id`
</blockquote></details>

There is no other option to delete the interface. This is the only way.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUFTaY-A24SwiO4pzla:biiilsz) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Won't the cloudAPi client return error if non-sysadmin users use this method?
</blockquote></details>

Why would it throw any error unless we make an explicit check? Maybe, I did not understand the question.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 152 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBnmA2lodnDOniXfR:-MUFTAHc7WvLiM11WkwQ:bc6thzq) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L152)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

is `@` in docstrings intended. If so, when should @ should be used in doctrings?
</blockquote></details>

Just a mistake. I was trying out the available docstring formats in my editor.  We use restructuredText for our docstrings.
Fixed it.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 168 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFuv8A11hZhZmhMvL:-MUFT1TdCy2A0PpNuAdn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L168)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

return hint should be `Iterator[Behavior]`
</blockquote></details>

Done.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 220 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFCRP7EryuO-voUfsw:-MUFRsEcEiWvYX0W-_15:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L220)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Multiple REST calls can be avoided here too by using `for .... return` code.
</blockquote></details>

Done.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFEUDS66ZPfH4z_8ib:-MUFP5ZR9FhhrtWeDGiQ:b-u1fa35) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L224)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is there any reason `behavior_interface_id` is used instead of just `behavior_id`? If there are no difference, which term is the correct one?
</blockquote></details>

There are two types of IDs associated with any behavior: a) behavior-interface-id b) behavior-type-id. They are analogous to Java interface method and overridden class method respectively.

I just wanted to highlight that id to be used must be behavior-interface-id but not behavior-type-id
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFFUec-1LVSpckpt4L:-MUFP-_-3j9Gp2tFaLz2:b-df4c47) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L242)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nit: `get_behavior_acls_on_entity_type` -> `list_behavior_acls_on_entity_type`
and why is the return type a list unlike Iterators in other list operations?
</blockquote></details>

I missed it. Done, thanks.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFGeEg9a7NAm29GiEJ:-MUFSHUy2KC12s_V1Ux3:bdfunxr) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L283)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is it ok if `None` is sent as payload for a POST request?
</blockquote></details>

I intentionally left the return type blank. I should have added a comment or TODO.
Invocation of behavior would return an empty payload but it would have task_id inserted into the response headers. This is yet to be implemented by the Extensibility team. So, once they implement it, we will have to return the task-id.

I will add a TODO here, thanks.

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUFYpzUCJptH4P6BGny:bdy0pal) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why would it throw any error unless we make an explicit check? Maybe, I did not understand the question.
</blockquote></details>

If the client doesn't have the required rights to perform the operation, the request should fail with a 401 status.  If cloudapi_client will raise this error, is it really necessary to handle the error condition with another if check?
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFGeEg9a7NAm29GiEJ:-MUFZrED0CB4uxXPDo_N:bvsg375) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L283)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I intentionally left the return type blank. I should have added a comment or TODO.
Invocation of behavior would return an empty payload but it would have task_id inserted into the response headers. This is yet to be implemented by the Extensibility team. So, once they implement it, we will have to return the task-id.

I will add a TODO here, thanks.
</blockquote></details>

Thanks for clarifying. But my question was about the request payload (`arguments` parameter). Can the request payload be empty?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUG0brE8ZWMD_kEqXg4:bae1ag0) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If the client doesn't have the required rights to perform the operation, the request should fail with a 401 status.  If cloudapi_client will raise this error, is it really necessary to handle the error condition with another if check?
</blockquote></details>

Anyone with FC rights can edit the entity type, but we want this method to be only invoked by an account with sys-admin-level privileges (or) System user (or) CSE service account. This is a way to suppress accidental misuse of the method in the code other than installation and upgrade (which is usually done by System users) areas. We have these similar checks in ComputePolicyManager.py, SchemaService.py among others.

Hope that clarifies. 
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 283 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFGeEg9a7NAm29GiEJ:-MUG01D70oFdQ7idGpa4:b3xisjz) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L283)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Thanks for clarifying. But my question was about the request payload (`arguments` parameter). Can the request payload be empty?
</blockquote></details>

Yes, it can be empty. That's why I set the default value for arguments as None.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUID88H5I43HaS73zW3:b-kv5z3) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Anyone with FC rights can edit the entity type, but we want this method to be only invoked by an account with sys-admin-level privileges (or) System user (or) CSE service account. This is a way to suppress accidental misuse of the method in the code other than installation and upgrade (which is usually done by System users) areas. We have these similar checks in ComputePolicyManager.py, SchemaService.py among others.

Hope that clarifies. 
</blockquote></details>

To be honest, the is_sys_admin check is very weak, all it checks is that the user belongs to the org 'System', it doesn't guarantee that the user will have the necessary rights.

Compute Policy manager has the check because the compute policies are not guarded by separate set of rights. In my opinion, RDE related service classes can leave the enforcement of the RBAC to vCD.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 75 at r2](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUICo5K1dKUrBWEx10G:-MUICo5L2jmVDiJ5YWK7:b-u1b73v) ([raw file](https://github.com/vmware/container-service-extension/blob/b8935f7ae65d2006c559349f8b5ac51bd1ca1bce/container_service_extension/rde/behaviors/behavior_service.py#L75)):*
> ```Python
>                                            f"/{CloudApiResource.BEHAVIORS}?"
>                                            f"page={page_num}")
>             if len(response_body['values']) > 0:
> ```

If an invalid/out of range page number is specified, do we get a 200 with 0 results or 404?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/rde/behaviors/behavior_service.py, line 137 at r1](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUFBJh3Dlf0Lp_6dnPv:-MUK8-za58Sp6I2EcWmg:baiv5xy) ([raw file](https://github.com/vmware/container-service-extension/blob/979a7fe3223b6b719a1d48be0a4c11cafcf63b9d/container_service_extension/rde/behaviors/behavior_service.py#L137)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

To be honest, the is_sys_admin check is very weak, all it checks is that the user belongs to the org 'System', it doesn't guarantee that the user will have the necessary rights.

Compute Policy manager has the check because the compute policies are not guarded by separate set of rights. In my opinion, RDE related service classes can leave the enforcement of the RBAC to vCD.
</blockquote></details>

My real intention was to restrict these methods only to few specific modules in the code-base and the check is not meant to provide RBAC. 

With that said, I think the ideal way to protect the modules is to mark them for certain packages only. Not sure python has a way to restrict modules to certain packages like Java. Using _is_sys_admin checks sounds indeed a hacky way to accomplish that. I will remove those.
___
*[container_service_extension/rde/behaviors/behavior_service.py, line 75 at r2](https://reviewable.io/reviews/vmware/container-service-extension/923#-MUICo5K1dKUrBWEx10G:-MUKIqMC9V9QwHf49Iv3:bj37so9) ([raw file](https://github.com/vmware/container-service-extension/blob/b8935f7ae65d2006c559349f8b5ac51bd1ca1bce/container_service_extension/rde/behaviors/behavior_service.py#L75)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If an invalid/out of range page number is specified, do we get a 200 with 0 results or 404?
</blockquote></details>

200 with Zero results.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923#-:-MUKOyAW14hlezDkQSed:bg7igkv)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923#-:-MUPCUUpBsqWi3rIw0ak:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by rocknes — COMMENTED** [review]
Please fix the flake8 errrors.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/923#-:-MUPCY0540VhA3-VeSSU:b-ikiy9v)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
