### PR TITLE
[VCDA-2530] Add cluster tests for RDE based tests

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Added tests for the following:
* cluster apply
* cluster delete nfs
* cluster delete
* cluster info
* cluster list

@rocknes @sakthisunda @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/system_test_framework/utils.py, line 106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiX8Onv0r31TDRuj3DC:-MiX8Onw0OX6IpW3bjv2:bu7p01b) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L106)):*
> ```Python
> 
> def _update_cluster_apply_spec_for_2_0(apply_spec, properties):
>     modified_spec = apply_spec.copy()
> ```

nit: if apply_spec needs to have the original intact, then deepcopy() is required as the following assignments might change the original apply_spec
___
*[system_tests_v2/test_cse_client.py, line 1070 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXBHReEqgT1De0lpn0:-MiXBHReEqgT1De0lpn1:b-xm4nuo) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/system_tests_v2/test_cse_client.py#L1070)):*
> ```Python
>         testutils.CMD_BINDER(cmd=f"cse cluster delete {cluster_delete_param.cluster_name}",  # noqa: E501
>                              exit_code=2 if cluster_delete_param.expect_failure else 0,  # noqa: E501
>                              validate_output_func=_follow_apply_output(expect_failure=cluster_delete_param.expect_failure),  # noqa: E501
> ```

Just curious, how validate_output_func is used or not. or will that be used impliciity. since it is a method reference.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/system_test_framework/utils.py, line 106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiX8Onv0r31TDRuj3DC:-MiXNsKv4BydhSDVuEb8:b-fdgcwi) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L106)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit: if apply_spec needs to have the original intact, then deepcopy() is required as the following assignments might change the original apply_spec
</blockquote></details>

+1 Not sure about callers of the method and the intent to preserve the input spec.
___
*[container_service_extension/system_test_framework/utils.py, line 113 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXOQ4NCYAUzqpwKNh-:-MiXOQ4NCYAUzqpwKNh0:bgxz0w2) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L113)):*
> ```Python
>     for key, value in properties.items():
>         if key == 'worker_count':
>             modified_spec['spec']['topology']['workers']['count'] = value
> ```

Hardcoding property names can make any future refactoring work a nightmare. Why can't we use objects/instances of the Spec to navigate through these properties?

Keep future refactoring (RDE property renaming, change in hierarchical structure) in mind.

Please create another jira task if you want to address this in another PR.
___
*[container_service_extension/system_test_framework/utils.py, line 192 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXP_C614rK6oEyhmtI:-MiXP_C614rK6oEyhmtJ:b-vn2ggs) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L192)):*
> ```Python
> 
> def get_worker_count_from_1_0_0_entity_dict(cluster_dict):
>     return len(cluster_dict['status']['nodes']['workers'])
> ```

As mentioned above, we must refrain as much as possible from using string values to navigate through the object. We can use data class instances.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/system_test_framework/utils.py, line 106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiX8Onv0r31TDRuj3DC:-MigEPE_6ebZskPKWB_w:bhq8daa) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L106)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1 Not sure about callers of the method and the intent to preserve the input spec.
</blockquote></details>

There is no need to preserve the values as there is no real reason for it.
Will change to direct assignment.
___
*[container_service_extension/system_test_framework/utils.py, line 113 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXOQ4NCYAUzqpwKNh-:-MigF1zq6W1EHrLTU6Zi:bktpb33) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L113)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Hardcoding property names can make any future refactoring work a nightmare. Why can't we use objects/instances of the Spec to navigate through these properties?

Keep future refactoring (RDE property renaming, change in hierarchical structure) in mind.

Please create another jira task if you want to address this in another PR.
</blockquote></details>

Used NativeEntity class to create objects and converted the objects back to dict.
___
*[container_service_extension/system_test_framework/utils.py, line 192 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXP_C614rK6oEyhmtI:-MigX3Qs5NYlrCXViYw4:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/container_service_extension/system_test_framework/utils.py#L192)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

As mentioned above, we must refrain as much as possible from using string values to navigate through the object. We can use data class instances.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177#-:-MigsO-L7xQ4Oe3H9QtX:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1177#-:-MigtiDg12K5rMx21w8D:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

**Comment by Anirudh9794** [comment]
___
*[system_tests_v2/test_cse_client.py, line 1070 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1177#-MiXBHReEqgT1De0lpn0:-Migrk-sDGUxcCMsS9-r:b-bn8m32) ([raw file](https://github.com/vmware/container-service-extension/blob/5fabe7fba88321931083a58b8088bf077992c08a/system_tests_v2/test_cse_client.py#L1070)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Just curious, how validate_output_func is used or not. or will that be used impliciity. since it is a method reference.
</blockquote></details>

The function will be called implicitly in `testutils.execute_commands()` if provided. Else it will be ignored

**Pull request merged**
