### PR TITLE
Let CSE register CAPVCD schema

### PR DESCRIPTION
**Pull request by sahithi**
1. Added a new CAPVCD schema json file (copied the TKGm 2.0 content and removed irrelevant items like NFS, rollback)
2. CSE registers CAPVCD schema if and only if _register_capvcd_schema_ is set to True in the Config file.

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1251)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
Minor comments. I think the part where a check is made to ensure if CSE is already installed should be uncommented.
:lgtm: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1251#-:-MnXyO597l2CQlX6TUwF:bt78m7y)* status: all files reviewed, 3 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-MnXoLuW63X0uAaBtPe9:-MnXoLuW63X0uAaBtPeA:bw7434l) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/container_service_extension/installer/configure_cse.py#L318)):*
> ```Python
> 
>         ext_type = _get_existing_extension_type(client)
>         # if ext_type != server_constants.ExtensionType.NONE:
> ```

Was this commented out intentionally?
___
*[docs/cse3_1/CLUSTER_MANAGEMENT.md, line 186 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-MnXxzUc2yKfB7GsMwGi:-MnXxzUc2yKfB7GsMwGj:b3fhzum) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/docs/cse3_1/CLUSTER_MANAGEMENT.md#L186)):*
> ```Markdown
> <a name="cse31_cluster_share"></a>
> ### CSE 3.1 `Cluster share` command
> The `vcd cse cluster share` command is supported for both TKG-S and native clusters. 
> ```

Are these changes supposed to be in this change set?
___
*[docs/cse3_1/CLUSTER_MANAGEMENT.md, line 187 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-MnXxhNpEHRv9_n50R0B:-MnXxhNpEHRv9_n50R0C:b8ogcw9) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/docs/cse3_1/CLUSTER_MANAGEMENT.md#L187)):*
> ```Markdown
> ### CSE 3.1 `Cluster share` command
> The `vcd cse cluster share` command is supported for both TKG-S and native clusters. 
> - Sharing TKG-s clusters would simply share the corresponding RDEs with the other user(s).
> ```

Since docs are hosted in master, I think the doc changes should also be done in master branch

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1251)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-MnXoLuW63X0uAaBtPe9:-MnarYJf9uuvtKy0Q8-5:b4qqx11) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/container_service_extension/installer/configure_cse.py#L318)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Was this commented out intentionally?
</blockquote></details>

Thanks for catching this, I had to do this for my testing. I will revert it.
___
*[container_service_extension/installer/configure_cse.py, line 1451 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-Mna7sJ9EUEEQJbew-cQ:-MnbdBT95RHpsSk_78UQ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/container_service_extension/installer/configure_cse.py#L1451)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think the noqa here got pushed to the next line and for the next two lines
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 1459 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-Mna81Tn4l5pVLMn-5fp:-MnbdB2n7k4IFbql6Fsw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/container_service_extension/installer/configure_cse.py#L1459)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

noqa is also moved to a new line here
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 1567 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-Mna8ETi908i0KJWwiBB:-MnbdAan6qmNv0ThE4dq:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/container_service_extension/installer/configure_cse.py#L1567)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think this function should be renamed to `_register_entity_type`
</blockquote></details>

Done.
___
*[docs/cse3_1/CLUSTER_MANAGEMENT.md, line 186 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1251#-MnXxzUc2yKfB7GsMwGi:-Mnbcb0N5q5-YPq8VWfY:b3xkh1d) ([raw file](https://github.com/vmware/container-service-extension/blob/dbd9b342be64382621e3b2931d72c295dab68996/docs/cse3_1/CLUSTER_MANAGEMENT.md#L186)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are these changes supposed to be in this change set?
</blockquote></details>

Not sure how these files got into my changeset, reverting them.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1251)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
As part of this PR, can we also increment the version in `allowed_source_cse_versions` so that upgrade from CSE 3.1.2 -> CSE 3.1.2 is also possible?

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1251#-:-MngRrpt3GWnuyvZAODn:bhcjem6)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

**Pull request merged**
