### PR TITLE
[VCDA-1890]Implement CSE server CLI to create service account

### PR DESCRIPTION
**Pull request by ChintanShahVMware**
CSE on CDS doesn't have access to VCD System Administrator Role; hence
it is important to find out what all roles are necessary for CSE to
operate and provide a mechanism to provider-admin, using which such role
can be created.
This commit takes care of above requirement. As part of this requirement
it provides a new optional:
cse create-service-role
CSE server-cli.

The CLI takes care of creating CSE Service Role for CSE operations.
Optionally it also offers user to create a user of this role.

Signed-off-by: Chintan Shah <schintan@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/815)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/815)* status: all files reviewed, 5 unresolved discussions (waiting on @ChintanShahVMware)

___
*[container_service_extension/create_cse_service_role.py, line 37 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ1JPNA4ERfkiiiiOS:-MLJ1JPNA4ERfkiiiiOT:bzbj6aw) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/create_cse_service_role.py#L37)):*
> ```Python
>     msg_update_callback.general(msg)
>     SERVER_CLI_LOGGER.info(msg)
>     return
> ```

nit: unneeded return
___
*[container_service_extension/server_cli.py, line 326 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ2_jG9TeUVto1vsPT:-MLJ2_jG9TeUVto1vsPU:b1sgmr) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L326)):*
> ```Python
> @click.option(
>     '-ssl_verify',
>     '--ssl_verify',
> ```

I think this should be `{--ssl-verify}`to fit the style of the over params
Also, it would be helpful to have a shorter option such as `{-s}`. 
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLJ3hYI47WF1J4Yxvcb:bagm51x) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
> ```Python
>     required=False,
>     is_flag=True,
>     default=True,
> ```

If the default is true, how does a user specify not to have SSL credentials verified?
___
*[container_service_extension/server_cli.py, line 361 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5JgnCLrMXLu9oRyS:-MLJ5JgnCLrMXLu9oRyT:blz988t) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L361)):*
> ```Python
>         SERVER_CLI_LOGGER.error(msg)
>         SERVER_CLI_LOGGER.error(str(err))
>         return
> ```

Instead of return, I think it is more common for us to use `{raise}` to propagate the exception
___
*[container_service_extension/server_constants.py, line 398 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5wUO0YIa-iNVUHGA:-MLJ5wUO0YIa-iNVUHGB:b-snxqdt) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_constants.py#L398)):*
> ```Python
>     "vCenter: View",
>     "vSphere Server: View",
>     "vmware:tkgcluster: Administrator Full access",
> ```

@rocknes Chintan and I encountered that not all of the TKG rights always show up, such as `{vmware:tkgcluster: Administrator Full Access}` and `{vmware:tkgcluster: Administrator View}`. Should these TKG rights be added through the TKG rights bundle then?

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 326 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ2_jG9TeUVto1vsPT:-MLJuh8S1s6CNhPMzeU7:b-f5xtuo) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L326)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think this should be `{--ssl-verify}`to fit the style of the over params
Also, it would be helpful to have a shorter option such as `{-s}`. 
</blockquote></details>

Agreed. Addressing it.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLJum58EkBSK6ZM445B:b4yebhe) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

If the default is true, how does a user specify not to have SSL credentials verified?
</blockquote></details>

Its a flag, so if you only need to specify -ssl-verify to change the value.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 361 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5JgnCLrMXLu9oRyS:-MLJuz2o2WO97vcHvJji:bw495qk) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L361)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Instead of return, I think it is more common for us to use `{raise}` to propagate the exception
</blockquote></details>

Cant really raise the exception from this level; this is basically the command handle for CLI, if i raise an exception here, it will be thrown to customer :)
About return, it basically makes sure that if the login fails CLI do not pursue next steps :)

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLJvhDa2zR7dzYnvl8Z:bd5iya) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Its a flag, so if you only need to specify -ssl-verify to change the value.
</blockquote></details>

change the default value*

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/815)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @ChintanShahVMware and @ltimothy7)

___
*[container_service_extension/create_cse_service_role.py, line 27 at r2](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLKFY1a-Id9j0WMzSBp:-MLKFY1b52IyKacwUheM:bssgv5w) ([raw file](https://github.com/vmware/container-service-extension/blob/558a871bcd6997fe011cf605f4bf9cb738f265f0/container_service_extension/create_cse_service_role.py#L27)):*
> ```Python
>     # as the values will need to be hardcoded.
>     # For now just check if its system org or not.
>     vcd_utils.raise_error_if_not_sysadmin(client)
> ```

fyi: this method will change once you merge in the other PR.
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLKGeI56KCOMS6HuMc3:bpwemrr) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

change the default value*
</blockquote></details>

The flag should be `skip-ssl-verify`, default is not necessary as missing flag is construed as False.
So if user doesn't specify the flag, we verify ssl, if they specify then we don't.
___
*[container_service_extension/server_cli.py, line 361 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5JgnCLrMXLu9oRyS:-MLKHk6c2DVTdky3SC1X:btjth2p) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L361)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Cant really raise the exception from this level; this is basically the command handle for CLI, if i raise an exception here, it will be thrown to customer :)
About return, it basically makes sure that if the login fails CLI do not pursue next steps :)
</blockquote></details>

Please reuse _get_clients_from_config

And please follow the tempalte of the other commands

One big try catch block to catch all exceptions and logout the client and then inner try catch blocks to handle individual exceptions.

The inner blocks should raise and not return
___
*[container_service_extension/server_cli.py, line 28 at r2](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLKFlLz-SrAoU0f4bXQ:-MLKFlLz-SrAoU0f4bXR:b1pv5yx) ([raw file](https://github.com/vmware/container-service-extension/blob/558a871bcd6997fe011cf605f4bf9cb738f265f0/container_service_extension/server_cli.py#L28)):*
> ```Python
> from container_service_extension.config_validator import get_validated_config
> import container_service_extension.configure_cse as configure_cse
> from container_service_extension.create_cse_service_role import (
> ```

Recently we have been moving away from the "from X import Y" style.

import container_service_extension.create_cse_service_role as ccs_manager

and then use ccs_manager.create_cse_service_role wherever necessary.

nit: I will prefer if we rename the `create_cse_service_role` module to `cse_service_role_manager`
___
*[container_service_extension/server_cli.py, line 321 at r2](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLKGOlu7Wv66sT9AlDr:-MLKGOlv1U4P-L-ct3Op:b-h8bsn9) ([raw file](https://github.com/vmware/container-service-extension/blob/558a871bcd6997fe011cf605f4bf9cb738f265f0/container_service_extension/server_cli.py#L321)):*
> ```Python
>     metavar='VCD_HOST',
>     required=True,
>     default=None,
> ```

No need to set `default`, if `required` is set to True
___
*[container_service_extension/server_constants.py, line 398 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5wUO0YIa-iNVUHGA:-MLKF1ei5uzOHbTKFITe:b-4z5uqo) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_constants.py#L398)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@rocknes Chintan and I encountered that not all of the TKG rights always show up, such as `{vmware:tkgcluster: Administrator Full Access}` and `{vmware:tkgcluster: Administrator View}`. Should these TKG rights be added through the TKG rights bundle then?
</blockquote></details>

They show up as such because the rights hasn't been internationalized properly. Ideally yes, we should leverage the rights bundle, but for the time being, in interest of time and 3.0.1 let's leave them as hardcoded.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 28 at r2](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLKFlLz-SrAoU0f4bXQ:-MLOt24DBOh8ALnPQAtO:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/558a871bcd6997fe011cf605f4bf9cb738f265f0/container_service_extension/server_cli.py#L28)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Recently we have been moving away from the "from X import Y" style.

import container_service_extension.create_cse_service_role as ccs_manager

and then use ccs_manager.create_cse_service_role wherever necessary.

nit: I will prefer if we rename the `create_cse_service_role` module to `cse_service_role_manager`
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 321 at r2](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLKGOlu7Wv66sT9AlDr:-MLOtZdZDgOHzA3gove4:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/558a871bcd6997fe011cf605f4bf9cb738f265f0/container_service_extension/server_cli.py#L321)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

No need to set `default`, if `required` is set to True
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 326 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ2_jG9TeUVto1vsPT:-MLOta4eEW_LY_qf3WqS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L326)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Agreed. Addressing it.
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLOvA1c-DjK8elp7zp7:ba47po8) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The flag should be `skip-ssl-verify`, default is not necessary as missing flag is construed as False.
So if user doesn't specify the flag, we verify ssl, if they specify then we don't.
</blockquote></details>

hmm.. agreed that name should be skip-ssl-verify (thats more intuitive).
So when customers do not specify it, its value will be false.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 329 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ3hYI47WF1J4Yxvca:-MLOy3fBBcWTzWJ8uZhA:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L329)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

hmm.. agreed that name should be skip-ssl-verify (thats more intuitive).
So when customers do not specify it, its value will be false.
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/server_cli.py, line 361 at r1](https://reviewable.io/reviews/vmware/container-service-extension/815#-MLJ5JgnCLrMXLu9oRyS:-MLOyRQl3BbKlyC5pKAx:b-9pdjfm) ([raw file](https://github.com/vmware/container-service-extension/blob/72514d7051230d78318fdf8e887f30cf10bec27a/container_service_extension/server_cli.py#L361)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please reuse _get_clients_from_config

And please follow the tempalte of the other commands

One big try catch block to catch all exceptions and logout the client and then inner try catch blocks to handle individual exceptions.

The inner blocks should raise and not return
</blockquote></details>

hmm.. using _get_clients_from_config requires me to prepare the config_dict using config_fil, which needs to come in as user input! (even if its unvalidated, it will still be a file); something which is an overkill from our previous discussion.

Yep, moving to outer try/catch and inner try/catch way of handling exceptions; should be right thing to do.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/815)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @rocknes)

**Review by ltimothy7 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/815#-:-MLPX_Pi5oda2k4YHmBZ:bg7igkv)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @rocknes)

**Comment by rocknes** [comment]
Closing this since we will be cherry picking commits from cse_3_0_1 and not merge this PR.

**Pull request closed without merging**
