### PR TITLE
[VCDA-2150] Pick cluster_service file using rde in use

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Use the rde_in_use to determine which cluster_service.py file needs to be used for handling the request.

Testing done:
Checked if the right cluster_service file is being invoked using debugger and log statements

@sahithi @sakthisunda @rocknes @arunmk @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 37 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBRbvqEqEH8Hxiqfoi:-MUBRbvqEqEH8Hxiqfoj:bokkqpf) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L37)):*
> ```Python
>     svc = cluster_service_factory.ClusterServiceFactory(op_ctx). \
>         get_cluster_service(rde_in_use)
>     # TODO find out the RDE version from the request spec
> ```

# TODO Insert RDE converters and validators.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 58 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBT1RPB4PFKXlL0BsH:-MUBT1RPB4PFKXlL0BsI:boxkg6p) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L58)):*
> ```Python
>         get_cluster_service(rde_in_use)
>     cluster_id = data[RequestKey.CLUSTER_ID]
>     # TODO find out the RDE version from the request spec
> ```

We can only guess the RDE version of the input spec. Input payload will not have the RDE version as it is just _RDE.entity_.
Based on the input API version, we will guess the input RDE version and cast it to the RDE_in_use if there is no major version difference, else use the explicit converter.

@sakthisunda tagging Sakthi as he is going to work on this area.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBS_1iEDxBhpDYWYBx:-MUBS_1iEDxBhpDYWYBy:b-i7a1dh) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L27)):*
> ```Python
>     """
>     # rde_in_use = server_utils.get_rde_version_in_use()
>     # TODO Reject request if rde_in_use is less than 2.0.0
> ```

There is no need to reject the request. Converters will take care of everything and they will throw the error if the conversion fails for any reason.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBSlsE1SRt8Jqr90de:-MUBSlsE1SRt8Jqr90df:bne9ymq) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L30)):*
> ```Python
>     # TODO find out the RDE version from the request spec
>     # TODO convert the spec to rde_in_use
>     svc = cluster_svc.ClusterService(op_ctx)
> ```

Any reason why you did not update this with cluster_service_factory call?

    rde_in_use = server_utils.get_rde_version_in_use()
    svc = cluster_service_factory.ClusterServiceFactory(op_ctx). \
        get_cluster_service(rde_in_use)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 37 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBRbvqEqEH8Hxiqfoi:-MUBTjSL5285nZzRIhNI:bbv5nw7) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L37)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

# TODO Insert RDE converters and validators.
</blockquote></details>

sorry I don't know how the font became so big.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBSlsE1SRt8Jqr90de:-MUC-OAG4YLmjZqeCH0Y:b-grc2aa) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L30)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any reason why you did not update this with cluster_service_factory call?

    rde_in_use = server_utils.get_rde_version_in_use()
    svc = cluster_service_factory.ClusterServiceFactory(op_ctx). \
        get_cluster_service(rde_in_use)

</blockquote></details>

If API v36 is used, is it not confirmed that RDE 2.0 is used? Because of this logic, I thought it is not necessary to do this logic to get the cluster service. If my assumption is correct, we will be using clusterService_2_x only

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/service.py, line 497 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUEb_DV0ovW6pjbU8XP:-MUEb_DYEi05-FCkAUOM:btsr0az) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/service.py#L497)):*
> ```Python
>             self.config['service']['rde_version_in_use'] = \
>                 def_utils.get_rde_version_by_vcd_api_version(max_vcd_api_version_supported)  # noqa: E501
>             msg_update_callback.general(f"Using RDE version: {self.config['service']['rde_version_in_use']}")  # noqa: E501
> ```

The Service object exists at this point right, can't we call the util method instead of accessing the config via keys?
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 37 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBRbvqEqEH8Hxiqfoi:-MUEbjdE4PVmadrSBiji:bz4udqx) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L37)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

sorry I don't know how the font became so big.
</blockquote></details>

double hash :P same formatting as md files
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBS_1iEDxBhpDYWYBx:-MUEcAd-EI3gORiBavj0:bb03t0i) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L27)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

There is no need to reject the request. Converters will take care of everything and they will throw the error if the conversion fails for any reason.
</blockquote></details>

Nopes, we should reject the call at api 36.0. Since we are not required to support forward compatibility in payload.
36.0 specifies payload as RDE 2.0.0, if client provides anything below 2.0.0 or above 3.0.0, the request should be rejected.
For 35.0, RDE 1.0.0 is the specification, but the clusters are represented as 2.0.0 in vCD hence the convertor is being used.


General rule of thumb, server should try to accept the payload only at the version the api specifies, but is free to do conversion for backend communication with vCD.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBS_1iEDxBhpDYWYBx:-MUF49Vt9jhezXcfqwbR:b-gqpcmr) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L27)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Nopes, we should reject the call at api 36.0. Since we are not required to support forward compatibility in payload.
36.0 specifies payload as RDE 2.0.0, if client provides anything below 2.0.0 or above 3.0.0, the request should be rejected.
For 35.0, RDE 1.0.0 is the specification, but the clusters are represented as 2.0.0 in vCD hence the convertor is being used.


General rule of thumb, server should try to accept the payload only at the version the api specifies, but is free to do conversion for backend communication with vCD.
</blockquote></details>

Sorry, I misread the TODO as "Reject the request if the _input payload rde version_ is less than 2.0.0". 
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBSlsE1SRt8Jqr90de:-MUFBK7SDLetmxIn7pYh:b-93qi4v) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L30)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If API v36 is used, is it not confirmed that RDE 2.0 is used? Because of this logic, I thought it is not necessary to do this logic to get the cluster service. If my assumption is correct, we will be using clusterService_2_x only
</blockquote></details>

Few releases down the line, say at 38, if we introduce another major bump up in RDE, say RDE 3.0, then this v36, v37 would need a way to dynamically figure out the backend which would be cluster_service_2X.py but not cluster_service_3X.py.

Then, we don't have to come back again to older handlers and redo this exercise.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/server/service.py, line 497 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUEb_DV0ovW6pjbU8XP:-MUGPnN-E4rz4AaAaxxs:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/service.py#L497)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The Service object exists at this point right, can't we call the util method instead of accessing the config via keys?
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 37 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBRbvqEqEH8Hxiqfoi:-MUGQBAG7vY3kkqCPFk0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L37)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

double hash :P same formatting as md files
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBSlsE1SRt8Jqr90de:-MUGQg0m4pnlUzCtrJOq:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L30)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Few releases down the line, say at 38, if we introduce another major bump up in RDE, say RDE 3.0, then this v36, v37 would need a way to dynamically figure out the backend which would be cluster_service_2X.py but not cluster_service_3X.py.

Then, we don't have to come back again to older handlers and redo this exercise.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922#-:-MUGd7RB0aoH2S3aZrge:bg7igkv)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 34 at r2](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUGcTBy-p9d2hH2LmdG:-MUGcTBy-p9d2hH2LmdH:b-rw0941) ([raw file](https://github.com/vmware/container-service-extension/blob/d881be668120630285c18fa5d8f2d1419f0e5d70/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L34)):*
> ```Python
>     svc = cluster_service_factory.ClusterServiceFactory(op_ctx). \
>         get_cluster_service(rde_in_use)
>     NativeEntityClass = rde_factory.get_rde_model(rde_in_use)
> ```


NativeEntityClass: AbstractNativeEntity = .... at all the places.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 34 at r2](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUGcTBy-p9d2hH2LmdG:-MUGkteN0R46RUnttf8b:bm6dms0) ([raw file](https://github.com/vmware/container-service-extension/blob/d881be668120630285c18fa5d8f2d1419f0e5d70/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L34)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

NativeEntityClass: AbstractNativeEntity = .... at all the places.
</blockquote></details>

I think this is not correct as NativeEntityClass is not an object of type AbstractNativeEntity. I will annotate the objects created with AbstractNativeEntitiy

**Review by rocknes — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/922#-:-MUI9vLx5E1qF902RaaB:bnfp4nl)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 58 at r1](https://reviewable.io/reviews/vmware/container-service-extension/922#-MUBT1RPB4PFKXlL0BsH:-MUI9IaGCWsHlICy8O7S:b-b5d9bw) ([raw file](https://github.com/vmware/container-service-extension/blob/288e88da3626a4fe308c390941302d8ec7b2331a/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L58)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can only guess the RDE version of the input spec. Input payload will not have the RDE version as it is just _RDE.entity_.
Based on the input API version, we will guess the input RDE version and cast it to the RDE_in_use if there is no major version difference, else use the explicit converter.

@sakthisunda tagging Sakthi as he is going to work on this area.
</blockquote></details>

This is worrisome in my opinion, if we have no way to know what has been passed in.
Server should always validate payload sent to it and not assume that the client is always doing the right thing.

**Pull request merged**
