### PR TITLE
[VCDA-2316] Extract out entity status updates to a separate funciton

### PR DESCRIPTION
**Pull request by Anirudh9794**
…unction

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Extract out entity status updates to a separate function to allow future changes to use Optimistic locking

Testing - 
* Create cluster using create cluster behaviors (TODO)
* 
@sahithi @sakthisunda @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 254 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFehPM-JuvDkEDvpea:-MZFehPN7qEI_GlSiFjt:b4jx4q5) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L254)):*
> ```Python
>         new_entity_status.cloud_properties.k8_distribution.template_name = template_name  # noqa: E501
>         new_entity_status.cloud_properties.k8_distribution.template_revision = template_revision  # noqa: E501
>         new_entity_status.cloud_properties.org_name = org_name
> ```

I wonder why we did not use initializers of the class to construct the Status object. This looks lengthy and error-prone. We may miss out on adding required properties.

Status(Cloudproperties=cloudProperties(..), os=os...)
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 356 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFfo6I4152fp-hQzFl:-MZFfo6I4152fp-hQzFm:b-cp1baw) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L356)):*
> ```Python
>               f"nfs count {desired_nfs_count}"
>         self._update_task(BehaviorTaskStatus.RUNNING, message=msg)
>         new_entity_status: rde_2_x.Status = curr_native_entity.status
> ```

Any reason why you called it "new_entity_status", is misleading. How about "new_status"?
We already have two types - input_entity and curr_entity.
Let us not add another term 'new_entity'.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1679 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFgXuN1rK4sWzAcJSb:-MZFgXuN1rK4sWzAcJSc:b-hd77bh) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1679)):*
> ```Python
>     def _update_cluster_entity(self, cluster_id: str,
>                                native_entity_status: rde_2_x.Status,
>                                cluster_rde: common_models.DefEntity = None,
> ```

cluster_rde param is not needed. When we will get to the implementation of optimistic locking, it becomes imperative that we do an explicit GET call anyway in this method, whether the caller has already sent a rde as a param or not.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1687 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFcvQ94KEF5fuBrxdv:-MZFcvQ94KEF5fuBrxdw:b-o1v7he) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1687)):*
> ```Python
> 
>         :param str cluster_id: ID of the defined entity
>         :param rde_2_x.Status native_entity_status: Defined entity status to be
> ```

Docstrings missing for few params.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1710 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFhAF20bIdSfY3qFXQ:-MZFhAF20bIdSfY3qFXR:b-b5r0eu) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1710)):*
> ```Python
>     def _fail_operation(self, cluster_id: str, op: DefEntityOperation):
>         def_entity: common_models.DefEntity = self.entity_svc.get_entity(cluster_id)  # noqa: E501
>         cluster_status: rde_2_x.Status = def_entity.entity.status
> ```

Please use the same term for consistency -"new_status"

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 463 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFijQf00qNzS9RxiQJ:-MZFijQf00qNzS9RxiQK:b-yc3pyn) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L463)):*
> ```Python
>         :rtype: def_models.DefEntity representing the cluster
>         """
>         curr_entity = self.entity_svc.get_entity(cluster_id)
> ```

Please get rid of GET calls like this unless they are really needed. Move it to the place where they are really being used. I know this particular method is properly using it. Please check at other places.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 464 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFjkBf-YgEkHw_nqTG:-MZFjkBf-YgEkHw_nqTH:bhlh15g) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L464)):*
> ```Python
>         """
>         curr_entity = self.entity_svc.get_entity(cluster_id)
>         curr_native_entity: rde_2_x.NativeEntity = curr_entity.entity
> ```

Please also ensure that the terms _input_entity_ and _curr_entity_ are being used appropriately at all other places in the file.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: all files reviewed, 7 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 254 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFehPM-JuvDkEDvpea:-MZJcEo4D6waZKi1wqej:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L254)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I wonder why we did not use initializers of the class to construct the Status object. This looks lengthy and error-prone. We may miss out on adding required properties.

Status(Cloudproperties=cloudProperties(..), os=os...)
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 356 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFfo6I4152fp-hQzFl:-MZGSLg9CtV2XX3jGmTp:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L356)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any reason why you called it "new_entity_status", is misleading. How about "new_status"?
We already have two types - input_entity and curr_entity.
Let us not add another term 'new_entity'.

</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 463 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFijQf00qNzS9RxiQJ:-MZLDRiYDFlqfSY2zOge:b-15vnf2) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L463)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please get rid of GET calls like this unless they are really needed. Move it to the place where they are really being used. I know this particular method is properly using it. Please check at other places.
</blockquote></details>

I went over all the operations. We should be making the call for get entity wherever we are accessing the status (because the status might be over-written by a parallel thread). Cluster create is the only exception and I am constructing the status manually.

Another thing I noticed is that even if we make use of locking, we should make a call to get_entity  in the sync portion. But we can remove the get entity calls in the async portion.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 464 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFjkBf-YgEkHw_nqTG:-MZLEPbU5-hlnvto6Fte:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L464)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please also ensure that the terms _input_entity_ and _curr_entity_ are being used appropriately at all other places in the file.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1679 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFgXuN1rK4sWzAcJSb:-MZLF3b4CuVGYp2KOl7Z:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1679)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

cluster_rde param is not needed. When we will get to the implementation of optimistic locking, it becomes imperative that we do an explicit GET call anyway in this method, whether the caller has already sent a rde as a param or not.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1687 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFcvQ94KEF5fuBrxdv:-MZLFUhh7Y5foXsuRLDq:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1687)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Docstrings missing for few params.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1710 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFhAF20bIdSfY3qFXQ:-MZLFagr55CAcunAVZU0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1710)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please use the same term for consistency -"new_status"
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comments

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020#-:-MZOPZ4OBM04XO0NQOR3:b-3tyihq)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 463 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFijQf00qNzS9RxiQJ:-MZOPN1mAjpPFMVdt22R:b2oa5np) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L463)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I went over all the operations. We should be making the call for get entity wherever we are accessing the status (because the status might be over-written by a parallel thread). Cluster create is the only exception and I am constructing the status manually.

Another thing I noticed is that even if we make use of locking, we should make a call to get_entity  in the sync portion. But we can remove the get entity calls in the async portion.
</blockquote></details>

As I mentioned, we will be getting the curr_entity also as part of the behavior payload. Please add a TODO.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 61 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZONaWX1T6BDgkYNmhi:-MZONaWX1T6BDgkYNmhj:bspuk3f) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L61)):*
> ```Python
> 
> 
> CLUSTER_CREATE_IN_PROGRESS_MESSAGE = 'create_cluster_in_progress'
> ```

We can send proper messages with spaces in between. Sorry, I think I added this confusion. I put this message with underscores initially for testing and forgot to format it.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 390 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOMpdi4FC5N7_uhuET:-MZOMpdi4FC5N7_uhuEU:b-31fr97) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L390)):*
> ```Python
>         self._monitor_resize(cluster_id=cluster_id,
>                              cluster_spec=input_native_entity)
>         return self.mqtt_publisher.construct_behavior_payload(
> ```

Is resize being called by Update_cluster() method, if yes, please check and the return response in the appropriate place. Ensure we are not sending the sync responses from multiple threads.

We can do this as part of "test PUT operation" Jira task as well (if you want this PR in by tomorrow). 
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 396 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOO-LM-9NJR0cKvsKf:-MZOO-LN3xQ__s3l74vw:b-3e1yrl) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L396)):*
> ```Python
>     def delete_cluster(self, cluster_id):
>         """Start the delete cluster operation."""
>         # Get entity required here to get the org and vdc in which the cluster
> ```

Teo just updated me that we are going to get the curr entity (in addition to the input_entity) also as part of the behavior payload in the upcoming VCD builds.
add a TODO to use that.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 447 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOOkF8EKGcqI3e0xSv:-MZOOkF8EKGcqI3e0xSw:b-m0ak9b) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L447)):*
> ```Python
>                                    org_name=org_name, ovdc_name=ovdc_name,
>                                    def_entity=curr_entity)
>         return self.mqtt_publisher.construct_behavior_payload(
> ```

Same here, resize involves addition and deletion, 
Please check, add a TODO to verify this thoroughly as part of the test-delete jira task.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 463 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZFijQf00qNzS9RxiQJ:-MZOy4rr0c3frWE1LtiQ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/35a4f18d16dfcde8a186b55b4485eac6361bf4c2/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L463)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

As I mentioned, we will be getting the curr_entity also as part of the behavior payload. Please add a TODO.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 61 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZONaWX1T6BDgkYNmhi:-MZOsETkCqdmPEgW-p1c:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L61)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can send proper messages with spaces in between. Sorry, I think I added this confusion. I put this message with underscores initially for testing and forgot to format it.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 390 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOMpdi4FC5N7_uhuET:-MZOsXGxDnYH-2S4EAVt:b9v2ccu) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L390)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is resize being called by Update_cluster() method, if yes, please check and the return response in the appropriate place. Ensure we are not sending the sync responses from multiple threads.

We can do this as part of "test PUT operation" Jira task as well (if you want this PR in by tomorrow). 
</blockquote></details>

The update_cluster() response is either resize_cluster() response or upgrade_cluster() response.

So the message will be published only once
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 396 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOO-LM-9NJR0cKvsKf:-MZOxPv13S9NQ0HCDVX8:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L396)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Teo just updated me that we are going to get the curr entity (in addition to the input_entity) also as part of the behavior payload in the upcoming VCD builds.
add a TODO to use that.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 447 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZOOkF8EKGcqI3e0xSv:-MZOxQeN9Nt7y4qUxoxV:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fcd138484d6a9720ba2efa6437bf9b500a135d9d/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L447)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here, resize involves addition and deletion, 
Please check, add a TODO to verify this thoroughly as part of the test-delete jira task.
</blockquote></details>

Done.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 309 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPItk-AUUDN36tnriz:-MZPItk-AUUDN36tnrj-:b-yupnnh) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L309)):*
> ```Python
>         and task_href.
> 
>         :rtype: DefEntity
> ```

Is rtype a DefEntity ?
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 501 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPKPkD4Scyjxs_ge4E:-MZPKPkD4Scyjxs_ge4F:b677w6p) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L501)):*
> ```Python
>         # check if cluster is in a valid state
>         phase: DefEntityPhase = DefEntityPhase.from_phase(
>             input_native_entity.status.phase)
> ```

Does **cur_native_entity.status.phase**  provide the current status right?  Or because of behaviors it is different?  
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1709 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPLWQn2ZaoaV-XxTdo:-MZPLWQn2ZaoaV-XxTdp:bu3jkot) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1709)):*
> ```Python
>         return self._update_cluster_entity(cluster_id, new_status)
> 
>     def _update_cluster_entity(self, cluster_id: str,
> ```

**_update_cluster_entity_status()**    vs  **_update_cluster_entity()**.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1020)* status: all files reviewed, 14 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 309 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPItk-AUUDN36tnriz:-MZPceuQ3m-7D42FYU9N:b-8nzi4) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L309)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is rtype a DefEntity ?
</blockquote></details>

No. This should be a dict. Thanks for catching this.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 501 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPKPkD4Scyjxs_ge4E:-MZPcxWm5lUQLhAwDO7A:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L501)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Does **cur_native_entity.status.phase**  provide the current status right?  Or because of behaviors it is different?  
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1709 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1020#-MZPLWQn2ZaoaV-XxTdo:-MZPd0-h6SYU2cU143a1:b-vka2rj) ([raw file](https://github.com/vmware/container-service-extension/blob/da7f0f194d141c219202f88af2468df7907e9cd3/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1709)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

**_update_cluster_entity_status()**    vs  **_update_cluster_entity()**. 
</blockquote></details>

Not only status of the entity is updated, we are updating the external ID as well. So will keep the same name for now.

**Pull request merged**
