### PR TITLE
[VCDA-1669] Optimize list vdc query using typed query

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Instead of making multiple calls to get ovdc list, we can optimize the output by using a typed query.
* changed ovdc_service and ovdc_handler to make use of a common function to get all the ovdcs
Testing done:
* checked if the changes increased the speed for the query to get `ovdc list`

@sakthisunda @sahithi @rocknes @ltimothy7 @ChintanShahVMware

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809#-:-MKgM5BG7D_52IYIR7vA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/def_/ovdc_service.py, line 133 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgLteI8-qF2jbA8jpK:-MKgLteJAGZXKiWTWDvN:b-8fbrg9) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/def_/ovdc_service.py#L133)):*
> ```Python
>         org_name = ovdc.get('orgName')
>         ovdc_details = asdict(
>             get_ovdc_k8s_runtime_details(operation_context.sysadmin_client,
> ```

This method still makes a REST call to vCD right?
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgM9CP0sv15JTtUYmI:-MKgM9CP0sv15JTtUYmJ:b-6riksc) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/request_handlers/ovdc_handler.py#L162)):*
> ```Python
>         ovdc_name = ovdc.get('name')
>         org_name = ovdc.get('orgName')
>         k8s_metadata = ovdc_utils.get_ovdc_k8s_provider_metadata(
> ```

This is still one REST call per ovdc :(

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/def_/ovdc_service.py, line 133 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgLteI8-qF2jbA8jpK:-MKq5cO1BvBijIlZV-pe:b-xf69g5) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/def_/ovdc_service.py#L133)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This method still makes a REST call to vCD right?
</blockquote></details>

Modified `get_ovdc_k8s_runtime_details` to only make the additional call to get vdc if either vdc_id or vdc_name is missing in the request.
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgM9CP0sv15JTtUYmI:-MKq5rpZCpT7Nl0UYOC_:bteaoqn) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/request_handlers/ovdc_handler.py#L162)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is still one REST call per ovdc :(
</blockquote></details>

Modified `get_ovdc_k8s_runtime_details` to only make the additional call to get vdc if either vdc_id or vdc_name is missing in the request.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/def_/ovdc_service.py, line 133 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgLteI8-qF2jbA8jpK:-MKsiP-38_DgY_XICeQ0:b-wqah8o) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/def_/ovdc_service.py#L133)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Modified `get_ovdc_k8s_runtime_details` to only make the additional call to get vdc if either vdc_id or vdc_name is missing in the request.
</blockquote></details>

Nice :-)
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgM9CP0sv15JTtUYmI:-MKsizFZCY4tVChs21qM:b-1b2ro0) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/request_handlers/ovdc_handler.py#L162)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Modified `get_ovdc_k8s_runtime_details` to only make the additional call to get vdc if either vdc_id or vdc_name is missing in the request.
</blockquote></details>

We have access to the ovdc id here too right? Shouldn't we use it?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgM9CP0sv15JTtUYmI:-MLFPoQd0F_lesfJvii_:b7u9z6a) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/request_handlers/ovdc_handler.py#L162)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We have access to the ovdc id here too right? Shouldn't we use it?
</blockquote></details>

yes, It would be more efficient if ovdc-id is also passed. Thanks for catching this :-)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_handlers/ovdc_handler.py, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/809#-MKgM9CP0sv15JTtUYmI:-MLFU4h27Yt5yj3lwhdO:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/1208591eb4d5452daec3c1e5148eaa9f4e16d943/container_service_extension/request_handlers/ovdc_handler.py#L162)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

yes, It would be more efficient if ovdc-id is also passed. Thanks for catching this :-) 
</blockquote></details>

Done.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/809#-:-MLJTYEbEnIstSKE6w7j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
