### PR TITLE
[VCDA-2272] Update rde 2.0.0 schema

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Change all fields in snake_case to camelCase
* Include fields `site` and `uid` in the schema

Testing done:
* create cluster (RDE 2.0)
* resize cluster (RDE 2.0)
* upgrade cluster (RDE 2.0)
* cluster config (RDE 2.0)
* cluster upgrade-plan
* cse install
* cse run
* cse upgrade

@rocknes @sahithi @sakthisunda @arunmk @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
Aniruddh,

Thanks for doing this refactoring! 

We want to avoid conditional statements interspersed with code. We may have to revisit this change. Please ensure to address the non-critical review comments as part of CLI design task. Create a server-side umbrella task for any comments you want to address later. For now, please submit this if basic tests are passing. 

:lgtm: 

> Reviewed 13 of 15 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983#-:-MXJ74s_BEuxXWNo0jgx:b-4yen5n)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster_native.py, line 218 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ4V7X2g-tOcINtJcf:-MXJ4V7X2g-tOcINtJcg:bw9jzuy) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/de_cluster_native.py#L218)):*
> ```Python
>         return self._native_cluster_api.get_upgrade_plan_by_cluster_id(cluster_id)  # noqa: E501
> 
>     def upgrade_cluster(self, cluster_name, template_name,
> ```

upgrade_cluster method - is it still applicable for RDE 2.0? Everything must be handled by the update operation.
Note this point for your CLI design. 
___
*[container_service_extension/client/de_cluster_native.py, line 271 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ2kGF8h0FT3ru8fFJ:-MXJ2kGG1mXCFsYwKYmu:b8rnz8z) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/de_cluster_native.py#L271)):*
> ```Python
>         entity_svc = def_entity_svc.DefEntityService(self._cloudapi_client)
>         NativeEntityClass = rde_factory.get_rde_model(self._server_rde_version)
>         cluster_spec = NativeEntityClass(**cluster_config)
> ```

As discussed, user input can be simply forwarded to the server in the dict form. Then, we will not have to deal with these conditional cases. I understand this is a side-effect of our design in the last release.

Deserialization into models can be done only with the responses received from the CSE server.

- You can design this as part of CLI. This is okay for now.
___
*[container_service_extension/client/sample_generator.py, line 142 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ9jkg71vWayrVc-iG:-MXJ9jkg71vWayrVc-iH:bh9n2uo) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/sample_generator.py#L142)):*
> ```Python
>     )
> 
>     # TODO Temporary solution for generating sample for RDE 2.0
> ```

Please create Jira tasks for anything that you think must be addressed in the Andromeda. For any non-critical and future enhancements, TODOs are enough.
___
*[container_service_extension/installer/configure_cse.py, line 2123 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJB3dV63h4VJcT9ZoU:-MXJB3dV63h4VJcT9ZoV:b3q0tea) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2123)):*
> ```Python
>         max([float(x) for x in config['service']['supported_api_versions']])
>     # TODO: get proper site information
>     site = config['vcd']['host']
> ```

We are not yet multisite. I think this may create some confusion for users.
site is anyway going to be optional property. I am rethinking about this, do we need to add this in Andromeda - @arunmk ? 

Two options:
1. Add it in the schema, but leave the value empty and ignore the value of it in the user-specified request.
2. Remove the site completely to eliminate any sign of confusion.

@arunmk

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: 13 of 16 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/client/de_cluster_native.py, line 218 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ4V7X2g-tOcINtJcf:-MXJEVX47fABW24bnuw5:b-tts4du) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/de_cluster_native.py#L218)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

upgrade_cluster method - is it still applicable for RDE 2.0? Everything must be handled by the update operation.
Note this point for your CLI design. 
</blockquote></details>

Yes, upgrade is not applicable for RDE 2.0. I can remove the rde 2_0_0  part from this function. Thank you!
___
*[container_service_extension/client/de_cluster_native.py, line 271 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ2kGF8h0FT3ru8fFJ:-MXJPoxK3iSN7Mq6PT6o:bkd5ega) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/de_cluster_native.py#L271)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

As discussed, user input can be simply forwarded to the server in the dict form. Then, we will not have to deal with these conditional cases. I understand this is a side-effect of our design in the last release.

Deserialization into models can be done only with the responses received from the CSE server.

- You can design this as part of CLI. This is okay for now.

</blockquote></details>

Added a TODO
___
*[container_service_extension/client/sample_generator.py, line 142 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJ9jkg71vWayrVc-iG:-MXJQDKH0Tmmg3Ril3ZR:b-ifqaxi) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/client/sample_generator.py#L142)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please create Jira tasks for anything that you think must be addressed in the Andromeda. For any non-critical and future enhancements, TODOs are enough.
</blockquote></details>

I will add this into description of the CLI task

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 2211 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJIX9B48IFihW4NRiV:-MXJIX9B48IFihW4NRiW:bzan8iv) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2211)):*
> ```Python
>         import container_service_extension.rde.models.rde_2_0_0 as rde_2_x
>         native_entity_2_x: rde_2_x.NativeEntity = def_entity.entity
>         native_entity_2_x.status.uid = def_entity_id
> ```

native_entity_2_x : Is the above piece of code is a place holder for future use? Because native_entity_2_x is not used anywhere below
___
*[container_service_extension/installer/configure_cse.py, line 2279 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJJOGxAoE2fKgT9gXq:-MXJIwxND2R6GgRh4VFr:b-wpf7ml) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2279)):*
> ```Python
>         native_entity_2_x.status.uid = def_entity_to_upgrade.id
>         native_entity_2_x.status.cloudProperties.site = site
>         native_entity_2_x.metadata.site = site
> ```

native_entity_2_x is not used below

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: 13 of 16 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1515 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJYk2N2X_JGp4Jhfyd:-MXJYk2N2X_JGp4Jhfye:b-ohhnd1) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1515)):*
> ```
>  self._sync_def_entity(cluster_id, curr_entity)
> ```
self._sync_def_entity(cluster_id, **curr_native_entity**)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 2211 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJIX9B48IFihW4NRiV:-MXJ_MkfBkcoKM0eAEC4:b-q126ol) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2211)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

native_entity_2_x : Is the above piece of code is a place holder for future use? Because native_entity_2_x is not used anywhere below
</blockquote></details>

since def_entity belongs to common models, python lint cannot recognize that the fields `status.uid`.
native_entity_2_x is a reference to the def_entity.entity.

This helped to reduce the pycharm warnings.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 2279 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJJOGxAoE2fKgT9gXq:-MXJa0hc5Ur3ltYFN07_:bynk7my) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2279)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

native_entity_2_x is not used below
</blockquote></details>

The same as above comment. native_entity_2_x is a reference to def_entity.entity field.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1515 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJYk2N2X_JGp4Jhfyd:-MXJlF9N3vfxfrz0aUxk:bj62rbm) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1515)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
>  self._sync_def_entity(cluster_id, curr_entity)
> ```
self._sync_def_entity(cluster_id, **curr_native_entity**)
</blockquote></details>

 sync_def_entity accepts a defined entity right? Please correct me if i am wrong

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1515 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJYk2N2X_JGp4Jhfyd:-MXJlv7J3ncODPpcC7ci:b85lb5p) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1515)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

 sync_def_entity accepts a defined entity right? Please correct me if i am wrong
</blockquote></details>

Sorry, I closed this right away after realizing that I am wrong. I noticed that it was resolved. Still, it appeared in the review.

The existing code is correct.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1, 2 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/client/cluster_commands.py, line 609 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXK87435cpYYj2d1qSH:-MXK87445o1ofOXysqhZ:bna283t) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/client/cluster_commands.py#L609)):*
> ```Python
>                         output=output,
>                         k8_runtime=k8_runtime,
>                         server_api_version=client.get_api_version())  # noqa: E501
> ```

Can we determine the RDE version here and send in that instead of api version.
I will prefer if we don't proliferate api_version any more than already it is.
___
*[container_service_extension/client/de_cluster_native.py, line 19 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXK8Omp8nQBxLUZ5pNw:-MXK8Omp8nQBxLUZ5pNx:b-9wqdef) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/client/de_cluster_native.py#L19)):*
> ```Python
> import container_service_extension.logging.logger as logger
> import container_service_extension.rde.common.entity_service as def_entity_svc
> import container_service_extension.rde.constants as def_constants
> ```

nit: rde_constants
___
*[container_service_extension/rde/utils.py, line 107 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKA4VeCKZqtmeGd4H8:-MXKA4Vf-ZaZ-BEsycNd:b84bwaa) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/utils.py#L107)):*
> ```Python
>     # Currently only single control-plane is supported.
>     control_plane = rde_2_0_0.ControlPlane(
>         sizingClass=entity_status.nodes.controlPlane.sizingClass,
> ```

This camel casing in code, will generate a lot of warnings..
@sahithi @arunmk Having the spec field in camel case doesn't really mean that the model class fields should be camel case too, right?
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 212 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKAgbxEV4phAtMDPbT:-MXKAgby9fbNUZZy_I7P:bbf2uch) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/backend/cluster_service_2_x.py#L212)):*
> ```Python
>             cluster_spec.spec.k8Distribution = rde_2_0_0.Distribution(
>                 templateName=server_config['broker']['default_template_name'],
>                 templateRevision=int(server_config['broker']['default_template_name']))  # noqa: E501
> ```

templateRevision=int(server_config['broker']['default_template_name']))  <-- wrong key
default_template_revision

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: all files reviewed, 7 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/client/cluster_commands.py, line 609 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXK87435cpYYj2d1qSH:-MXNgoAW55GnWAqLUFIW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/client/cluster_commands.py#L609)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can we determine the RDE version here and send in that instead of api version.
I will prefer if we don't proliferate api_version any more than already it is.
</blockquote></details>

Done.
___
*[container_service_extension/client/de_cluster_native.py, line 19 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXK8Omp8nQBxLUZ5pNw:-MXNh5uO6OdBiGtZg96y:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/client/de_cluster_native.py#L19)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: rde_constants
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 2123 at r2](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXJB3dV63h4VJcT9ZoU:-MXNhiWj6Dfc5zdIK_1a:b5z5mu9) ([raw file](https://github.com/vmware/container-service-extension/blob/15d0dd8d4e878981cc53ba8d78164e889355ced3/container_service_extension/installer/configure_cse.py#L2123)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We are not yet multisite. I think this may create some confusion for users.
site is anyway going to be optional property. I am rethinking about this, do we need to add this in Andromeda - @arunmk ? 

Two options:
1. Add it in the schema, but leave the value empty and ignore the value of it in the user-specified request.
2. Remove the site completely to eliminate any sign of confusion.

@arunmk  
</blockquote></details>

As per the discussion https://vca-bos.slack.com/archives/GD555K9J5/p1617398397268400 decided to keep `site` as a required property.
___
*[container_service_extension/rde/utils.py, line 107 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKA4VeCKZqtmeGd4H8:-MXNi-qq73ccevt9KcZN:bv6wfsy) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/utils.py#L107)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This camel casing in code, will generate a lot of warnings..
@sahithi @arunmk Having the spec field in camel case doesn't really mean that the model class fields should be camel case too, right?
</blockquote></details>

Yes, I agree that camel casing will generate lot of warnings.
Swagger also maintains models with variable names in snake_case and underlying representation in camelCase (tkgclient is an example). Each underlying class will have a dict mapping variable name to type mapping. A method `to_dict()` is present to recursively parse the json representation.

But one thing that I noticed is that the warnings are limited to the model classes. Pycharm doesn't complain when the class variable is used in a different module
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 212 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKAgbxEV4phAtMDPbT:-MXNhRF52rVj9WDKd9hI:bu9gah8) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/backend/cluster_service_2_x.py#L212)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

templateRevision=int(server_config['broker']['default_template_name']))  <-- wrong key
default_template_revision
</blockquote></details>

Done. Thanks for catching this.

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: 12 of 16 files reviewed, 7 unresolved discussions (waiting on @arunmk, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 107 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKA4VeCKZqtmeGd4H8:-MXNzOg00nQQqsKpRu4F:b-elkyyy) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/utils.py#L107)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Yes, I agree that camel casing will generate lot of warnings.
Swagger also maintains models with variable names in snake_case and underlying representation in camelCase (tkgclient is an example). Each underlying class will have a dict mapping variable name to type mapping. A method `to_dict()` is present to recursively parse the json representation.

But one thing that I noticed is that the warnings are limited to the model classes. Pycharm doesn't complain when the class variable is used in a different module
</blockquote></details>

I don't think we need the camelCase in the python variable names itself. Are there any autogenerated variable names? If not, we should continue using the default python conventions IMo.

(Swagger does things which are not necessarily ideal since it also generates some golang code with snake_case.)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/utils.py, line 107 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKA4VeCKZqtmeGd4H8:-MXO22gU0-YUavlhmnkd:b3ne7is) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/utils.py#L107)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I don't think we need the camelCase in the python variable names itself. Are there any autogenerated variable names? If not, we should continue using the default python conventions IMo.

(Swagger does things which are not necessarily ideal since it also generates some golang code with snake_case.)
</blockquote></details>

the problem is with how we read a json and parse it into a dataclass object. The variable names should have 1-1 Mapping with the json representation. We can change the class variables to snake_case. include an init function for all the model classes and let the init function have camel case. But Pycharm doesn't seem to give warning for class variable names being camel case but it gives warnings for init function parameters (So the problem will still persist)

**Review by sahithi — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/983)* status: all files reviewed, 7 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/rde/utils.py, line 107 at r4](https://reviewable.io/reviews/vmware/container-service-extension/983#-MXKA4VeCKZqtmeGd4H8:-MXT3dxu7Z139Nw-GVOB:b-h7tlmx) ([raw file](https://github.com/vmware/container-service-extension/blob/c96f1463fa1a7602dc6b7381bea4778bad9c577f/container_service_extension/rde/utils.py#L107)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

the problem is with how we read a json and parse it into a dataclass object. The variable names should have 1-1 Mapping with the json representation. We can change the class variables to snake_case. include an init function for all the model classes and let the init function have camel case. But Pycharm doesn't seem to give warning for class variable names being camel case but it gives warnings for init function parameters (So the problem will still persist)
</blockquote></details>

If warnings are confined to just model classes, I am okay leaving the properties in camelCase for now and find a way to suppress the warnings with some built-in suppress decorator if there exists.

We can add a TODO/Jira task to refine it later. Hope that is okay.

**Pull request merged**
