### PR TITLE
VCDA-2670, 2706, 2895: DNS and site validations

### PR DESCRIPTION
**Pull request by arunmk**
VCDA-2670: vcd['host'] should not specify scheme in config file (MQTT does not understand it)
VCDA-2706: RDE should validate site (validates http format and also if the value is same as set in config)
VCDA-2895: Remove DNS related configuration (use VCD setup)

The additional change is that the requirements.txt did not have a few dependencies that were called from source. The PyCharm IDE added them cleanly.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1198)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1198)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @rocknes)

___
*[requirements.txt, line 53 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk3NPKR-Eg4pzyaIv2G:-Mk3NPKR-Eg4pzyaIv2H:b-ccm7i8) ([raw file](https://github.com/vmware/container-service-extension/blob/70aab6dffa15d8316c9939f5aaf45853736bc1a0/requirements.txt#L53)):*
> ```help
> lxml~=4.6.3
> PyYAML~=5.4.1
> click~=8.0.1
> ```

nit: missing newline
___
*[container_service_extension/installer/config_validator.py, line 347 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk3Nvbs9nYO6Pyjo8xi:-Mk3Nvbs9nYO6Pyjo8xj:bapxcv6) ([raw file](https://github.com/vmware/container-service-extension/blob/70aab6dffa15d8316c9939f5aaf45853736bc1a0/container_service_extension/installer/config_validator.py#L347)):*
> ```Python
> 
> 
> def _validate_vcd_url(vcd_url: Optional[str]) -> None:
> ```

Could this be renamed to `_validate_vcd_url_format` or something similarly since it is checking if the scheme is present? 

With the current name, it's unclear how this function is different from ``is_valid_vcd_url` in terms of what they check for.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1917 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk3OUEz9QeO0zrjnwdC:-Mk3OUEz9QeO0zrjnwdD:b-32xwqg) ([raw file](https://github.com/vmware/container-service-extension/blob/70aab6dffa15d8316c9939f5aaf45853736bc1a0/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1917)):*
> ```Python
>         for spec in vm_specs:
>             spec['cust_script'] = templated_script.format(
>                 vcd_host=vcd_host.replace("/", r"\/"),
> ```

This is cleaner than what I had been trying; it's helpful to see :)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1198#-:-Mk3VfvM1g34EfAApwOJ:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk and @rocknes)

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1198)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @arunmk, @ltimothy7, and @rocknes)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1917 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk3OUEz9QeO0zrjnwdC:-Mk45LFv-uXGVxivOCVI:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/70aab6dffa15d8316c9939f5aaf45853736bc1a0/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1917)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

This is cleaner than what I had been trying; it's helpful to see :)
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 248 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk46MowECq9ioNKtIZ9:-Mk48Fy25moE4MF8b1wq:bf2rkc3) ([raw file](https://github.com/vmware/container-service-extension/blob/56239ccbe66954be86ebf579e296c14cbbc69e47/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L248)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this say "shouldn't have an https scheme"
</blockquote></details>

This should have a https scheme. I have made the error more verbose.

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1198)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 347 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1198#-Mk3Nvbs9nYO6Pyjo8xi:-Mk48Ng578f_9hvA6fgB:b-m79ir) ([raw file](https://github.com/vmware/container-service-extension/blob/70aab6dffa15d8316c9939f5aaf45853736bc1a0/container_service_extension/installer/config_validator.py#L347)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Could this be renamed to `_validate_vcd_url_format` or something similarly since it is checking if the scheme is present? 

With the current name, it's unclear how this function is different from ``is_valid_vcd_url` in terms of what they check for.
</blockquote></details>

renamed to _validate_vcd_url_scheme

**Pull request merged**
