### PR TITLE
[VCDA-1777] CLI for cse configure-pks

### PR DESCRIPTION
**Pull request by sakthisunda**
- `cse pks-configure
Usage: cse pks-configure [OPTIONS] PKS_CONFIG_FILE_PATH
Try "cse pks-configure -h" for help.
 `
- Configure nsxt servers for CSE using the information provided in configuration file
- Manually tested and verified with PKS testbed

image

@Anirudh9794 @rocknes @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/726)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server_cli.py, line 613 at r1](https://reviewable.io/reviews/vmware/container-service-extension/726#-MGiS4Fa9GpdknGhxepl:-MGiS4Fa9GpdknGhxepm:b-wbhxwn) ([raw file](https://github.com/vmware/container-service-extension/blob/d12d97e521a15cb96bb5253e6d7fe6a78babfdef/container_service_extension/server_cli.py#L613)):*
> ```Python
>     is_flag=True,
>     help='Skip decryption of PKS config file')
> def pks_configure(ctx, pks_config_file_path, skip_config_decryption):
> ```

I think this command should be hidden if the CSE server is not running.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/726#-:-MGiTjkh5A1E5gtmTr0m:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rocknes — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/726#-:-MGqzIMF4eMGk4b-hTTd:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[container_service_extension/server_cli.py, line 630 at r1](https://reviewable.io/reviews/vmware/container-service-extension/726#-MGqywjGCS6p8luGS0g1:-MGqywjI1DOVFXaXZCZf:blxagb6) ([raw file](https://github.com/vmware/container-service-extension/blob/d12d97e521a15cb96bb5253e6d7fe6a78babfdef/container_service_extension/server_cli.py#L630)):*
> ```Python
>                 pks_config_file_path,
>                 msg_update_callback=console_message_printer)
>             if skip_config_decryption:
> ```

This code to read the pks yaml can be made common between cse install and this command.
Atleast add a todo here.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/726)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[container_service_extension/server_cli.py, line 613 at r1](https://reviewable.io/reviews/vmware/container-service-extension/726#-MGiS4Fa9GpdknGhxepl:-MGjWfDS6J2hZ02XoIL0:b-x2ua4i) ([raw file](https://github.com/vmware/container-service-extension/blob/d12d97e521a15cb96bb5253e6d7fe6a78babfdef/container_service_extension/server_cli.py#L613)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this command should be hidden if the CSE server is not running.
</blockquote></details>

This is a server cli that relies on NSXT-server only.
___
*[container_service_extension/server_cli.py, line 630 at r1](https://reviewable.io/reviews/vmware/container-service-extension/726#-MGqywjGCS6p8luGS0g1:-MGsz9_oCI0Dl8JgGEDu:bh0ayex) ([raw file](https://github.com/vmware/container-service-extension/blob/d12d97e521a15cb96bb5253e6d7fe6a78babfdef/container_service_extension/server_cli.py#L630)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This code to read the pks yaml can be made common between cse install and this command.
Atleast add a todo here.
</blockquote></details>

TODO added .

**Pull request merged**
