### PR TITLE
[VCDA-3345] CSE Upgrade to 3.1.3

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested upgrading 3.1.2->3.1.3 and successfully deployed a cluster with no changes needed for right bundles.
More testing will be done during testfest

- (Optional) Names of reviewers using @ sign + name
- @sahithi @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330)

### CODE REVIEW

**Review by sahithi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 316 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1330#-MzGpxgc6VJu3gvzHfqT:-MzGpxgc6VJu3gvzHfqU:b-hzo0wy) ([raw file](https://github.com/vmware/container-service-extension/blob/dfa1c2dcd197e6f04a6679f204a031bf4e123b64/container_service_extension/rde/models/rde_2_1_0.py#L316)):*
> ```Python
>                 # Upgrade RDE 2.0 -> 2.1
>                 # Ensure settings.cni is deprecated
>                 upgraded_native_entity = cls(
> ```

Have you already made the changes for the RDE upgrade from 1.0 to 2.1?

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 316 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1330#-MzGpxgc6VJu3gvzHfqT:-MzO7jXt1KbJ1QUS-2j0:b-1sf2cv) ([raw file](https://github.com/vmware/container-service-extension/blob/dfa1c2dcd197e6f04a6679f204a031bf4e123b64/container_service_extension/rde/models/rde_2_1_0.py#L316)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Have you already made the changes for the RDE upgrade from 1.0 to 2.1?
</blockquote></details>

what is cls here? I don't see any other reference to it.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 316 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1330#-MzGpxgc6VJu3gvzHfqT:-MzQgOQi33O_n_wwQt6J:b68moez) ([raw file](https://github.com/vmware/container-service-extension/blob/dfa1c2dcd197e6f04a6679f204a031bf4e123b64/container_service_extension/rde/models/rde_2_1_0.py#L316)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

what is cls here? I don't see any other reference to it.
</blockquote></details>

Yes, the changes for 1.0->2.1 are below this code; it was made as part of another PR.
cls is the class constructor; we use it in the code below.

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330#-:-MzRdGGXC6uA1kYgbuGV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 316 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1330#-MzGpxgc6VJu3gvzHfqT:-MzRdDuz5rtPwW8MWTLA:b-q8jzb0) ([raw file](https://github.com/vmware/container-service-extension/blob/dfa1c2dcd197e6f04a6679f204a031bf4e123b64/container_service_extension/rde/models/rde_2_1_0.py#L316)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Yes, the changes for 1.0->2.1 are below this code; it was made as part of another PR.
cls is the class constructor; we use it in the code below.
</blockquote></details>

got it

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1330#-:-MzRnIEc6ExLFUSjE9Zf:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Pull request merged**
