### PR TITLE
[VCDA-2847] Machine token changes in CSE

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Create clients for /oauth and /token api endpoints

During creation of cluster - create machine user tokens, supply machine user token to control plane
During deletion - revoke the created machine user tokens

Testing done:
Check if the file in /root/vcloud-basic-auth.yaml of the created control plane node has the right content

@arunmk @sakthisunda @ltimothy7 @rocknes 

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
:lgtm: with some small changes needed

> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193#-:-Mjbu9FA3bRo6C1pzgIY:b-v7iqz8)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 157 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_cF60-UYH1mgUMoOh:-Mj_cF60-UYH1mgUMoOi:btsk3v8) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/cluster_scripts/v2_x_tkgm/control_plane.sh#L157)):*
> ```Shell
> vmtoolsd --cmd "info-set guestinfo.postcustomization.kubectl.cpi.install.status in_progress"
>   wget -O $vcloud_basic_auth_path https://raw.githubusercontent.com/vmware/cloud-provider-for-cloud-director/0.1.0-beta/manifests/vcloud-basic-auth.yaml
>   sed -i "s/username\: \\\"\\\"/username\: \\\"$username\\\"/; s/machineUserToken\: \\\"\\\"/machineUserToken\: \\\"$refresh_token\\\"/" $vcloud_basic_auth_path
> ```

Can we have the file in-place here and do a string-replace? That will make things clearer. The kubeadm conf in this file has a similar setup.

We should note that, doing this string replacement here means that the shell script in this VM has the machine token embedded in it. It is not a security risk, since root-access to the control-plane VM essentially means that the k8s cluster is compromised. However it is better to keep this in mind.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 47 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_jimb8mDr8NVbh24M:-Mj_jimb8mDr8NVbh24N:b-pc3jam) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L47)):*
> ```Python
>         # we need to format the cloudapi_url so that only https://vcd-host
>         # part is retained
>         host_url_parts = cloudapi_url.split('/')[:-1]
> ```

Better to use urllib.parse for such operations.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 58 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_jwsu0BP5GNXBtEw5:-Mj_jwsu0BP5GNXBtEw6:b-fmdqfy) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L58)):*
> ```Python
>         register_client_url = \
>             f"{self._host_url}{BASE_OAUTH_ENDPOINT_FRAGMENT}"
>         # /oauth endpoint is tenanted. Whcih means, system administrators can
> ```

typo: Whcih
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 95 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_kn5DEPB2KzWBIPZQ:-Mj_kn5DEPB2KzWBIPZR:b7kri6d) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L95)):*
> ```Python
>             content_type="application/json")
> 
>         self.oauth_client_id = response['client_id']
> ```

Check if response is `None`
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_kr080jRPWjFgZDW8:-Mj_kr080jRPWjFgZDW9:b-9ad84o) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L115)):*
> ```Python
>             payload=payload)
> 
>         self.refresh_token = response['refresh_token']
> ```

Check is response is `None`
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_l8HrCKF-cW3TC0GQ:-Mj_l8HrCKF-cW3TC0GR:b9iwdsn) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/tokens_client/tokens_service.py#L17)):*
> ```Python
>         self._cloudapi_client = cloudapi_client
> 
>     def get_refresh_token_by_oauth_client_name(self, oauth_client_name: str):
> ```

Verify that oauth_client_name is non-empty
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1746 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_m2Q950NyDc8I4oYm:-Mj_m2Q950NyDc8I4oYn:b-v86uz2) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1746)):*
> ```Python
> 
> def _get_oauth_client_name_from_cluster_id(cluster_id):
>     return f"cluster-{cluster_id}"
> ```

Raise if `cluster_id` is None. We should not hit this issue, but there is a number of locations where we do default cluster_id to None.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @arunmk)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 157 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_cF60-UYH1mgUMoOh:-MjeGZeBEcM2UTdw_wFS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/cluster_scripts/v2_x_tkgm/control_plane.sh#L157)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we have the file in-place here and do a string-replace? That will make things clearer. The kubeadm conf in this file has a similar setup.

We should note that, doing this string replacement here means that the shell script in this VM has the machine token embedded in it. It is not a security risk, since root-access to the control-plane VM essentially means that the k8s cluster is compromised. However it is better to keep this in mind.
</blockquote></details>

Done.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 47 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_jimb8mDr8NVbh24M:-MjeUEr43xsYIAdfUcli:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L47)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Better to use urllib.parse for such operations.
</blockquote></details>

Done.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 58 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_jwsu0BP5GNXBtEw5:-MjeWP3a1H05gIdG-c1o:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L58)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

typo: Whcih
</blockquote></details>

Done.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 95 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_kn5DEPB2KzWBIPZQ:-MjeX6pT84gQbZKu0bUx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L95)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Check if response is `None`
</blockquote></details>

Done.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_kr080jRPWjFgZDW8:-MjeZXc99UhmbdD6brVm:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/oauth_client/oauth_service.py#L115)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Check is response is `None`
</blockquote></details>

Done.
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_l8HrCKF-cW3TC0GQ:-Mje_9YmAkSZmpi5VM26:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/lib/tokens_client/tokens_service.py#L17)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Verify that oauth_client_name is non-empty
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1746 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mj_m2Q950NyDc8I4oYm:-Mje_o82A1dps7n_sKCn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd54818745300c59198d900cda90aecd77e3986c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1746)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Raise if `cluster_id` is None. We should not hit this issue, but there is a number of locations where we do default cluster_id to None.
</blockquote></details>

Done.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)* status: 1 of 7 files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 165 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mjfkm1nDHPujz6dxrUA:-Mjfkm1nDHPujz6dxrUB:bi9ge7h) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/cluster_scripts/v2_x_tkgm/control_plane.sh#L165)):*
> ```Shell
>   namespace: kube-system
> END
>   kubectl apply -f $vcloud_basic_auth_path
> ```

$vcloud_basic_auth_path does not have any value internally set in the script; Also not seeing any value gets injected from outside
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1005 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjflreB1DInpiFWdBrq:-MjflreB1DInpiFWdBrr:b-yj2k2i) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1005)):*
> ```Python
>                                      f"'{curr_rde.state}'", exc_info=True)
>                     else:
>                         LOGGER.error("Failed to delete the defined entity for "
> ```

Shouldn't this be an fstring : f"Failed to .....

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 3 of 7 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 109 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjVTSqDa72byXEfRLU:-MjjVTSr9nL-oHHbiIMm:b-ezh522) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/oauth_client/oauth_service.py#L109)):*
> ```Python
>         """
>         payload = {
>             "grant_type": GRANT_TYPE_JWT_BEARER,
> ```

it would be cleaner to make these enum constants
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 133 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjVWp7D_eH4bxKXimD:-MjjVWp7D_eH4bxKXimE:b5sr3au) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/oauth_client/oauth_service.py#L133)):*
> ```Python
>         payload = {
>             "grant_type": "refresh_token",
>             "refresh_token": self.refresh_token
> ```

similar to above, it would be cleaner to make these enum tokens if possible
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 21 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjWB824nXdQUrYyyEK:-MjjWB824nXdQUrYyyEL:b-9ou4fj) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/tokens_client/tokens_service.py#L21)):*
> ```Python
>         # NOTE: Oauth client name is uniqe to a refresh token
>         if not oauth_client_name:
>             raise ValueError(f"Invalid value supplied for oauth_client_name: {oauth_client_name}")  # noqa: E501
> ```

since the name would be empty here, I think it would be clearer to say `No oauth_client_name provided`
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjWT1u63iYlsx8SvtS:-MjjWT1u63iYlsx8SvtT:b-z394p5) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/tokens_client/tokens_service.py#L30)):*
> ```Python
>             method=RequestMethod.GET,
>             cloudapi_version=CloudApiVersion.VERSION_1_0_0.value,
>             resource_url_relative_path=f"{CloudApiResource.TOKENS.value}?filter={filter_string}")  # noqa: E501
> ```

should also check if response is None

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 165 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mjfkm1nDHPujz6dxrUA:-MjjzZ2X5DyBysQ8fIe_:bc50mkp) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/cluster_scripts/v2_x_tkgm/control_plane.sh#L165)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

$vcloud_basic_auth_path does not have any value internally set in the script; Also not seeing any value gets injected from outside
</blockquote></details>

vcloud_basic_auth_path is set to "/root/vcloud-basic-auth.yaml" in line number 33
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 109 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjVTSqDa72byXEfRLU:-MjkBb-WCOZP_z8hu1eN:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/oauth_client/oauth_service.py#L109)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

it would be cleaner to make these enum constants
</blockquote></details>

Done.
___
*[container_service_extension/lib/oauth_client/oauth_service.py, line 133 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjVWp7D_eH4bxKXimD:-MjkB_a-DhAXoXmySnPZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/oauth_client/oauth_service.py#L133)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

similar to above, it would be cleaner to make these enum tokens if possible
</blockquote></details>

Done.
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 21 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjWB824nXdQUrYyyEK:-Mjk0zX0BX7bGmpoajgw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/tokens_client/tokens_service.py#L21)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

since the name would be empty here, I think it would be clearer to say `No oauth_client_name provided`
</blockquote></details>

Done.
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjjWT1u63iYlsx8SvtS:-Mjk1V5R-M3c0TbPd_LE:b-pt2ipc) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/lib/tokens_client/tokens_service.py#L30)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

should also check if response is None 
</blockquote></details>

Done. Thank you
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1005 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1193#-MjflreB1DInpiFWdBrq:-Mjjzpkh0Vc08NoTyER5:b-grw7rn) ([raw file](https://github.com/vmware/container-service-extension/blob/337785b491846cb2266110c20f86f8b985565b05/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1005)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Shouldn't this be an fstring : f"Failed to .....
</blockquote></details>

It is not really necessary as the next line which contains the variable is an f-string.
But the line got converted to an fstring when rebasing.

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: minor comments

> Reviewed 3 of 7 files at r1, 1 of 2 files at r4, 3 of 5 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193#-:-MkA17TZ1bGq5Z4UaYYt:b-kfw89e)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/lib/oauth_client/oauth_constants.py, line 19 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9xvR41dK3idsH0bZo:-Mk9xvR5ESoRn5NwzIin:b-2mppfx) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/oauth_client/oauth_constants.py#L19)):*
> ```Python
> @unique
> class GrantType(str, Enum):
>     JWT_BEARER = "urn:ietf:params:oauth:grant-type:jwt-bearer"
> ```

Can reuse the constants above, right?
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 19 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9yFoSChf3fBRrhgkF:-Mk9yFoSChf3fBRrhgkG:b2980h7) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/tokens_client/tokens_service.py#L19)):*
> ```Python
>     def get_refresh_token_by_oauth_client_name(self, oauth_client_name: str):
>         """Get refresh token information by oauth client name."""
>         # NOTE: Oauth client name is uniqe to a refresh token
> ```

nit: unique
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 44 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9ysvk2F7eyO95eqFy:-Mk9ysvk2F7eyO95eqFz:b-e9ooq9) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/tokens_client/tokens_service.py#L44)):*
> ```Python
>             method=RequestMethod.DELETE,
>             cloudapi_version=CloudApiVersion.VERSION_1_0_0.value,
>             resource_url_relative_path=f"{CloudApiResource.TOKENS.value}/{refresh_token['id']}",  # noqa: E501
> ```

I would guard this entire REST call with 
if refresh_token.get('id'):

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1193)* status: 8 of 10 files reviewed, 14 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/lib/oauth_client/oauth_constants.py, line 19 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9xvR41dK3idsH0bZo:-MkERcNg6hDgAHwutX2_:b-elqof) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/oauth_client/oauth_constants.py#L19)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can reuse the constants above, right?
</blockquote></details>

Sorry, The above constants were unused so I removed them.
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 19 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9yFoSChf3fBRrhgkF:-MkE06x0AaYVYikMHEpD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/tokens_client/tokens_service.py#L19)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: unique
</blockquote></details>

Done.
___
*[container_service_extension/lib/tokens_client/tokens_service.py, line 44 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1193#-Mk9ysvk2F7eyO95eqFy:-MkE0_oT7LHX84JlHjVT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90ec678c668509c862ae4922ca5d4e7806508ea1/container_service_extension/lib/tokens_client/tokens_service.py#L44)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I would guard this entire REST call with 
if refresh_token.get('id'):
</blockquote></details>

Done.

**Pull request merged**
