### PR TITLE
[VCDA-2132] Expose cluster in cluster create workflow

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
-Allow cluster to be exposed when specifying intent_to_expose flag to true

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Added logic to expose the cluster, checking if the gateway is NSX-T backed, routed network, and the user has enough rights to update the NAT and gateway. If so, an ip for the edge gateway is allocated and a dnat rule is created, mapping the control plane ip to the allocated ip.

The spec and status section of the schema have new fields: intent_to_expose and expose.

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)

### CODE REVIEW

**Comment by arunmk** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 620 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVGrfn2JiFNKDS0HJ_:-MUVGrfn2JiFNKDS0HJa:boywnzh) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L620)):*
> ```Python
> 
>             # Handle exposing cluster
>             expose_ip = None
> ```

Can we add types here, say:
expose_ip: str = ""
or the appropriate class etc

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @ltimothy7)

___
*[requirements.txt, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVFOyK01QouTmQECt3:-MUVFOyK01QouTmQECt4:btz1ep5) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/requirements.txt#L32)):*
> ```vimhelp
> 
> # vcd-cli >= 24.0.0, < 25.0.0
> vcd-cli == 24.0.1.dev2
> ```

If possible, we should not have dev builds in the `requirements.txt`. There seems to be a precedent here.
___
*[container_service_extension/nsxt_backed_gateway_service.py, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVHCHS5HDyAiMlyYdr:-MUVHCHS5HDyAiMlyYds:b-bplj9c) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/nsxt_backed_gateway_service.py#L131)):*
> ```Python
>             except Exception:
>                 if subnet_index == len(subnet_values) - 1:
>                     raise Exception('No subnet found with available ips')
> ```

IIRC, we are looking at one subnet here. Could we record the subnet in the exception.
___
*[container_service_extension/def_/cluster_service.py, line 620 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVGrfn2JiFNKDS0HJ_:-MUVO6mnBHUfs-sUuZ5I:b-w4my7a) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L620)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we add types here, say:
expose_ip: str = ""
or the appropriate class etc
</blockquote></details>

I think there is benefit of adding the output classes in general in this code. However, it depends on timelines etc, so you decide about it.
___
*[container_service_extension/def_/cluster_service.py, line 621 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVHcUi26ED-7JFjR23:-MUVHcUi26ED-7JFjR24:b9mxfjj) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L621)):*
> ```Python
>             # Handle exposing cluster
>             expose_ip = None
>             if intent_to_expose and float(api_version) >= float(vcd_client.ApiVersion.VERSION_36.value):  # noqa: E501
> ```

Should we check that the gateway is NSX-T backed here?
___
*[container_service_extension/def_/cluster_service.py, line 711 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVLAAxC4sw7y4bThzn:-MUVLAAxC4sw7y4bThzo:b-p2gqsw) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L711)):*
> ```Python
> 
>             # Update defined entity with exposed ip
>             if expose_ip and def_entity.entity.status.nodes:
> ```

This is a bit of a weird state. The spec will say `expose = True` but the status will always say `expose = False` in case of an NSX-V situation. Is that expected?
___
*[container_service_extension/def_/cluster_service.py, line 1844 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVIU3b5WV7TV0jRu63:-MUVIU3b5WV7TV0jRu64:b-adpph6) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L1844)):*
> ```Python
>         # Expose cluster if given external ip
>         if expose_ip:
>             script = script.replace(
> ```

This is a bit of a dangerous thing. For example, suppose the script already has `kubeadm init --control-plane-endpoint=blah`, this replace will lead to a string like `kubeadm init --control-plane-endpoint={expose_ip} --control-plane-endpoint=blah`. We should change the whole line, or use placeholders rather than replace.
___
*[container_service_extension/def_/cluster_service.py, line 2077 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVL_RH1ZUIYxoBXbV7:-MUVL_RH1ZUIYxoBXbV8:b-jsixok) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2077)):*
> ```Python
>         client=client,
>         resource=network_resource)
>     network_id = utils.extract_id_from_href(routed_vdc_network.href)
> ```

Probably not part of this PR, but it feels like these operations should be part of a vcd client library rather than utils
___
*[container_service_extension/def_/cluster_service.py, line 2104 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVM0Or07C6vmv2329u:-MUVM0Or07C6vmv2329v:bl0e27b) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2104)):*
> ```Python
>     cloudapi_client = vcd_utils.get_cloudapi_client_from_vcd_client(client)
>     user_ctx = user_context.UserContext(client, cloudapi_client)
>     if not _user_has_edit_gateway_rights(user_ctx.rights):
> ```

This should throw an exception and should be below the check for NSX-T/NSX-V
___
*[container_service_extension/def_/cluster_service.py, line 2113 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVM6qk97geploFBKqH:-MUVM6qk97geploFBKqI:bm53hiv) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2113)):*
> ```Python
>         network_resource=routed_network_resource,
>         ovdc=ovdc)
>     if not gateway or not gateway.is_nsxt_backed():
> ```

If not gateway should throw an exception, correct? I mean, any situation that is NSX-T but the expose operation does not work should fail if expose=True.
___
*[container_service_extension/def_/cluster_service.py, line 2119 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVMNWZ7008jIsx5y7o:-MUVMNWZ7008jIsx5y7p:b-2ct2uj) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2119)):*
> ```Python
>     nsxt_gateway_svc = NsxtBackedGatewayService(gateway, client)
>     expose_ip = nsxt_gateway_svc.quick_ip_allocation()
>     if not expose_ip:
> ```

This should definitely raise.

**Comment by arunmk** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 1818 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVXBXJEvmQYPFrMVk6:-MUVXBXJEvmQYPFrMVk7:b-y3ytoj) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L1818)):*
> ```Python
> 
>     node_names = _get_node_names(vapp, NodeType.CONTROL_PLANE)
>     result = _execute_script_in_nodes(sysadmin_client, vapp=vapp,
> ```

`_execute_script_in_nodes` has `check_tools` defaulted to True while this function defaults this to `False`. So it would mean that only for worker nodes it is `False`. What is the reasoning here?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @arunmk, @ltimothy7, and @rocknes)

___
*[requirements.txt, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVFOyK01QouTmQECt3:-MUjYNykEWt4-OES02BT:b-4djiyu) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/requirements.txt#L32)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

If possible, we should not have dev builds in the `requirements.txt`. There seems to be a precedent here.
</blockquote></details>

@rocknes For 3.0.2, will we have a non-dev build vcd-cli and pyvcloud?
___
*[container_service_extension/nsxt_backed_gateway_service.py, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVHCHS5HDyAiMlyYdr:-MUjYh-f161WDys4FjV-:bp0uspg) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/nsxt_backed_gateway_service.py#L131)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

IIRC, we are looking at one subnet here. Could we record the subnet in the exception.
</blockquote></details>

This exception is raised if none of the subnets have available ip's, so this exception is not related to a particular subnet
___
*[container_service_extension/def_/cluster_service.py, line 621 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVHcUi26ED-7JFjR23:-MUjZ2OL6Wux1W0enF-e:b78nwtq) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L621)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Should we check that the gateway is NSX-T backed here?
</blockquote></details>

This will be handled in the `_expose_cluster` function. I think it is better to leave this checking to that function since it performs other checks as well such as the rights of the current user. If there is any error or if the gateway is not NSX-T backed, then we will catch the exception and set `expose_ip` to be the empty string.
___
*[container_service_extension/def_/cluster_service.py, line 711 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVLAAxC4sw7y4bThzn:-MUj_gsc-MqWfxrIO4VF:bjznuz) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L711)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is a bit of a weird state. The spec will say `expose = True` but the status will always say `expose = False` in case of an NSX-V situation. Is that expected?
</blockquote></details>

The spec field is called `intent_to_expose`; it is possible that the user may want to expose, but the expose operation may fail to a reason such as not having an NSX-T backed gateway. In this case `expose` in the status section will be set to False. I think the field naming makes sense here, but what do you think?
___
*[container_service_extension/def_/cluster_service.py, line 1818 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVXBXJEvmQYPFrMVk6:-MUj_c3d8pheyEcgQIu2:b-vesrj) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L1818)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

`_execute_script_in_nodes` has `check_tools` defaulted to True while this function defaults this to `False`. So it would mean that only for worker nodes it is `False`. What is the reasoning here?
</blockquote></details>

@rocknes Could you comment on this reasoning for the worker nodes? I am not sure

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: 0 of 6 files reviewed, 10 unresolved discussions (waiting on @arunmk, @ltimothy7, and @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 620 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVGrfn2JiFNKDS0HJ_:-MUjj1Iv18pzYSl0zvl8:bfnpiaj) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L620)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think there is benefit of adding the output classes in general in this code. However, it depends on timelines etc, so you decide about it.
</blockquote></details>

Done. Thank you; I agree with this and will try to incorporate as much as I can.
___
*[container_service_extension/def_/cluster_service.py, line 2077 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVL_RH1ZUIYxoBXbV7:-MUjkle_3t0eSAdSsAAK:b3gcd0g) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2077)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Probably not part of this PR, but it feels like these operations should be part of a vcd client library rather than utils
</blockquote></details>

I think that would be helpful too. I think this will be better for master instead of the updates branch.
___
*[container_service_extension/def_/cluster_service.py, line 2104 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVM0Or07C6vmv2329u:-MUkEuxQ1KJgkdbxaOJF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2104)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should throw an exception and should be below the check for NSX-T/NSX-V
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 2113 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVM6qk97geploFBKqH:-MUkGHfM-Zf5inxvBfjt:b-flvwqt) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2113)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

If not gateway should throw an exception, correct? I mean, any situation that is NSX-T but the expose operation does not work should fail if expose=True.
</blockquote></details>

Done. Thank you Arun, I have added two exceptions here: one for not finding the gateway and one for the gateway not being nsx-t based. I was trying to make sure that the create cluster operation goes through in the case there is an issue in the `_expose_cluster` function. I agree with you it is better to raise here and allow the caller to handle the exception.
___
*[container_service_extension/def_/cluster_service.py, line 2119 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVMNWZ7008jIsx5y7o:-MUkGtph4Jf21Va7gERx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L2119)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This should definitely raise.
</blockquote></details>

Done.

**Comment by ltimothy7** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 1844 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVIU3b5WV7TV0jRu63:-MUoQSWX4GwnGk_OWcXF:bvl8562) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L1844)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is a bit of a dangerous thing. For example, suppose the script already has `kubeadm init --control-plane-endpoint=blah`, this replace will lead to a string like `kubeadm init --control-plane-endpoint={expose_ip} --control-plane-endpoint=blah`. We should change the whole line, or use placeholders rather than replace.
</blockquote></details>

Thank you Arun; that is helpful. I have updated the code to call a helper that will replace the whole line and will handle if `--control-plane-endpoint` is present already.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: all files reviewed, 13 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[requirements.txt, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVFOyK01QouTmQECt3:-MUrKWNr8LxJJcsHdIZJ:bfyyt68) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/requirements.txt#L32)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@rocknes For 3.0.2, will we have a non-dev build vcd-cli and pyvcloud?
</blockquote></details>

Yes, before we release 3.0.2, we will publish proper builds for pyvcloud and vcd-cli and consume them here.
These dev builds are there for internal use only.
___
*[container_service_extension/def_/cluster_service.py, line 711 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVLAAxC4sw7y4bThzn:-MUrMkUeA7eO09dDBW1v:b-k8kx3u) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L711)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

The spec field is called `intent_to_expose`; it is possible that the user may want to expose, but the expose operation may fail to a reason such as not having an NSX-T backed gateway. In this case `expose` in the status section will be set to False. I think the field naming makes sense here, but what do you think?
</blockquote></details>

The spec can specify the field 'expose', the status will specify the field 'exposed'
___
*[container_service_extension/def_/cluster_service.py, line 1818 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVXBXJEvmQYPFrMVk6:-MUrN5Ih6ABFhn3AiP10:b-vhsenq) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L1818)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@rocknes Could you comment on this reasoning for the worker nodes? I am not sure
</blockquote></details>

If the vm is up and configured via init/join few seconds back, it means that it has not been restarted yet and the guest tool is still running. I guess this is just an optimistic optimization :)
___
*[container_service_extension/def_/cluster_service.py, line 622 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrM64ICm51bKMmtMwL:-MUrM64ICm51bKMmtMwM:bu9ddkt) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/cluster_service.py#L622)):*
> ```Python
>             # Handle exposing cluster
>             expose_ip: str = ''
>             if intent_to_expose and float(api_version) >= float(vcd_client.ApiVersion.VERSION_36.value):  # noqa: E501
> ```

We are planning to ship this feature in 3.0.2 that would work with vCD 10.2.2. 
vCD 10.2.2 is still api v35.0.

I think it is ok to drop the api version check altogether. Since this service can't be called with api v 34.0 or below.
___
*[container_service_extension/def_/cluster_service.py, line 2155 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrLO422ui1scc_Refn:-MUrLO422ui1scc_Refo:b-4k2ai2) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/cluster_service.py#L2155)):*
> ```Python
> 
>     # Check user has gateway view and edit rights
>     user_ctx = user_context.UserContext(client, cloudapi_client)
> ```

Do we really need to check for the missing rights?
We can try the operations and if they fail we raise exception, the cluster create workflow can catch the generic exception and continue with rest of the workflow.

RBAC is better left for vCD. We work assuming the user has the necessary rights, if not then catch the exception, log it and move on.
___
*[container_service_extension/def_/models.py, line 178 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrL9NoD2QYkyRPbWAU:-MUrL9NoD2QYkyRPbWAV:b-v0pmyk) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/models.py#L178)):*
> ```Python
>     k8_distribution: Distribution
>     settings: Settings
>     intent_to_expose: bool
> ```

we can call this value just 'expose'

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @arunmk and @rocknes)

___
*[requirements.txt, line 32 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVFOyK01QouTmQECt3:-MUtBQeL9QdY6TzyP7xo:b-v17pan) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/requirements.txt#L32)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Yes, before we release 3.0.2, we will publish proper builds for pyvcloud and vcd-cli and consume them here.
These dev builds are there for internal use only.
</blockquote></details>

Thanks Aritra.
___
*[container_service_extension/def_/cluster_service.py, line 711 at r1](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUVLAAxC4sw7y4bThzn:-MUtCC9u1Ds6GN5MN13M:b-82lww6) ([raw file](https://github.com/vmware/container-service-extension/blob/a12957f5150b130ab4826782cdfa37d6b2ddcb87/container_service_extension/def_/cluster_service.py#L711)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The spec can specify the field 'expose', the status will specify the field 'exposed'
</blockquote></details>

I was using the naming specified in the task, but I can update `intent_to_expose` -> `expose` in the spec, and update `expose` -> `exposed` in the status
___
*[container_service_extension/def_/cluster_service.py, line 622 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrM64ICm51bKMmtMwL:-MUtBlvl5OwH8dkAsglC:bc9wwzt) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/cluster_service.py#L622)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We are planning to ship this feature in 3.0.2 that would work with vCD 10.2.2. 
vCD 10.2.2 is still api v35.0.

I think it is ok to drop the api version check altogether. Since this service can't be called with api v 34.0 or below.
</blockquote></details>

Done. Thanks Aritra
___
*[container_service_extension/def_/cluster_service.py, line 2155 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrLO422ui1scc_Refn:-MUtCmQu9fn-I8S02v84:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/cluster_service.py#L2155)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we really need to check for the missing rights?
We can try the operations and if they fail we raise exception, the cluster create workflow can catch the generic exception and continue with rest of the workflow.

RBAC is better left for vCD. We work assuming the user has the necessary rights, if not then catch the exception, log it and move on.
</blockquote></details>

Done.
___
*[container_service_extension/def_/models.py, line 178 at r2](https://reviewable.io/reviews/vmware/container-service-extension/929#-MUrL9NoD2QYkyRPbWAU:-MUtDYWfCm7A8X-qKs03:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/df83876dd54a92b50b1be05186e9199018c093eb/container_service_extension/def_/models.py#L178)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

we can call this value just 'expose'
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929#-:-MUzvYW59HYkjOCtb-OS:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @arunmk)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/929)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk)

**Pull request merged**
