### PR TITLE
[VCDA-1973] Client and server changes for including upgrade in apply command

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Add a v36 handler for cluster apply which routes to both resize and upgrade after validation
* Deprecate `vcd cse cluster upgrade` command for api version 36.0

Testing done:
* create a cluster
* upgrade and resize the cluster at the same time and check if it throws an error
* upgrade a cluster
* resize a cluster

@rocknes @sakthisunda @sahithi @ChintanShahVMware @arunmk @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/853)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/853)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/request_processor.py, line 476 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObTTT958ZUAJSkjnmL:-MObTTT958ZUAJSkjnmM:b-dfzld7) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_processor.py#L476)):*
> ```Python
> 
> 
> def _get_v35_plus_cluster_url_data(method: str, tokens: list, api_version: str) -> dict:  # noqa: E501
> ```

Is this the new naming convention we will use? It seems that we may break this convention if a later api version requires a separate handler. 
___
*[container_service_extension/request_processor.py, line 500 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObUlZPC7oJ6Pyh5USG:-MObUlZPC7oJ6Pyh5USH:b33al1w) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_processor.py#L500)):*
> ```Python
>                 shared_constants.RequestKey.CLUSTER_ID: tokens[5]
>             }
>         if method == shared_constants.RequestMethod.PUT:
> ```

Could we raise an exception if the api version is less than 35.0
___
*[container_service_extension/def_/utils.py, line 69 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObVF-0CzP3A-w3fnd_:-MObVF-0CzP3A-w3fnda:bb9nctw) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/def_/utils.py#L69)):*
> ```Python
>         DefKey.ENTITY_TYPE_VERSION: DEF_NATIVE_ENTITY_TYPE_VERSION,
>         DefKey.ENTITY_TYPE_NAME: DEF_NATIVE_ENTITY_TYPE_NAME,
>         DefKey.ENTITY_TYPE_SCHEMA_VERSION: 'api_v35',
> ```

Will this be updated in the future to api_v36?
___
*[container_service_extension/request_handlers/request_utils.py, line 127 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObVnpj4aLzMx67FeA0:-MObVnpj4aLzMx67FeA1:b-2aj55s) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_handlers/request_utils.py#L127)):*
> ```Python
> 
>     # Raise exception if fields which cannot be changed are updated
>     valid_fields = [FlattenedClusterSpecKey.WORKERS_COUNT.value, FlattenedClusterSpecKey.NFS_COUNT.value,  # noqa: E501
> ```

This array should be moved to server_constants.py

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_processor.py, line 476 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObTTT958ZUAJSkjnmL:-MObaP6QB-To2ONC8k7R:bnmhcil) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_processor.py#L476)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Is this the new naming convention we will use? It seems that we may break this convention if a later api version requires a separate handler. 
</blockquote></details>

You are right. Fixing the request processor to handle different api version calls will be done in a separate story after the decision on the api strategy

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_processor.py, line 500 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObUlZPC7oJ6Pyh5USG:-MObb5GW5k5z5xwiZRDD:b8pls3r) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_processor.py#L500)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Could we raise an exception if the api version is less than 35.0
</blockquote></details>

`_get_v35_plus_url_data` which calls this function will handle this

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/utils.py, line 69 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObVF-0CzP3A-w3fnd_:-MObbDSu-wY-WxW0nmfJ:bvn9be9) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/def_/utils.py#L69)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Will this be updated in the future to api_v36?
</blockquote></details>

Right now, the same schema is used as `api_v35`. Since there is no change to the schema, I thought it is better to avoid duplicate schema. @rocknes do you think we should create another schema?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_handlers/request_utils.py, line 127 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObVnpj4aLzMx67FeA0:-MOboPP45GqpQqMuY5OO:ba71ils) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_handlers/request_utils.py#L127)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

This array should be moved to server_constants.py
</blockquote></details>

As discussed, moved to `shared_constants.py`

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_handlers/request_utils.py, line 127 at r1](https://reviewable.io/reviews/vmware/container-service-extension/853#-MObVnpj4aLzMx67FeA0:-MOboXrzEbAae0esSrOT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/16649324d441a8c16473fab7cca3c6cdbe916081/container_service_extension/request_handlers/request_utils.py#L127)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

As discussed, moved to `shared_constants.py`
</blockquote></details>

Done.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/853)* status: all files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @rocknes)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/853)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Pull request merged**
