### PR TITLE
[VCDA-2217]Release check-list

### PR DESCRIPTION
**Pull request by sahithi**
Added a developer-guide file.
Created placeholders for all the areas we would need to touch at the beginning of each release. Tagged the feature owners to do further updates.
Filled in RDE section.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/995)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/995)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/developer_guide.md, line 20 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHpmNk-IZedfdkexcg:-MYHpmNlD0G199sHEfbX:b-3dmvg2) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L20)):*
> ```Markdown
> 
> ## RDE
> RDE is a persistent object in VCD representing CSE's K8 cluster. It contains two 
> ```

RDE can also represent something other than CSE cluster right?
___
*[container_service_extension/developer_guide.md, line 36 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHqtqWDlxgplZmNsyu:-MYHqtqWDlxgplZmNsyv:bx13wqj) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L36)):*
> ```Markdown
>   Use https://semver.org/ for versioning guidelines. In short, bump up the 
>   major version only when there is an addition of new required properties, deletion of 
>   existing required properties, strict dependency on features of a particular VCD version.
> ```

... existing required properties **or** strict dependency on features ...
___
*[container_service_extension/developer_guide.md, line 66 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHshDR3_C40XTWRlEn:-MYHshDR3_C40XTWRlEo:baw63v) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L66)):*
> ```Markdown
> 
> ## CSE start-up
> (To be updated by Aniruddha)
> ```

* Make sure feature flags, VCD api version in extension are not changed after CSE install/upgrade
* Ensure that un-supported templates (templates having min_cse_version and max_cse_version which are incompatible with CSE version that is running) are not loaded into runtime config.
* Ensure native placement policies are setup and are loaded to runtime config
___
*[container_service_extension/developer_guide.md, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHsCMfCsJGK992LJRC:-MYHsCMfCsJGK992LJRD:b-l5qum8) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L75)):*
> ```Markdown
> 
> # CLI
> (To be updated by Aritra sen and Aniruddha)
> ```

* Update any new NativeEntity models with sample_native_entity()
* Ensure proper mapping between VCD api version and Runtime RDE version for all supported VCD API versions are available.
* Update mappings in command_filter.py and make sure right commands are exposed at the right API versions
___
*[container_service_extension/developer_guide.md, line 84 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHyzzED84vxffsbGKj:-MYHyzzED84vxffsbGKk:b3r8ew5) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L84)):*
> ```Markdown
> 1. Update min and max versions of CSE version in each of the template definition
>    at https://github.com/vmware/container-service-extension-templates/blob/upgrades/template_v2.yaml
> 2. Ensure metadata on existing templates is updated correctly during the upgrade process.
> ```

* Ensure all scripts for each of the template descriptor in template.yaml and template_v2.yaml is present in scripts and scripts_v2 directories respectively
* Make sure that only one revision of a template (not necessarily the same) is present in tempalte.yaml and template_v2.yaml
* Block non-legacy template install, CSE upgrade or CSE install if remote template cookbook doesn't contain required keys (min_cse_version and max_cse_version).
* Ensure only supported templates are installed during CSE install/CSE upgrade
* Make sure non-legacy CSE upgrade with skip-template-install option ignores update to unsupported templates (definition can be added to terminologies).
* Ensure `cse template list` yields only the list of templates supported by the CSE version.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/995#-:-MYI1n2FAgF2Hp6CF2WW:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/995)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/developer_guide.md, line 20 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHpmNk-IZedfdkexcg:-MYIKy4p2CHdhI58rtvj:bjaf1x8) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L20)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

RDE can also represent something other than CSE cluster right?
</blockquote></details>

Yes, I will correct the wording.
___
*[container_service_extension/developer_guide.md, line 36 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHqtqWDlxgplZmNsyu:-MYIL1RTBjIjQqs6REQ0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L36)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

... existing required properties **or** strict dependency on features ...
</blockquote></details>

Done.
___
*[container_service_extension/developer_guide.md, line 66 at r1](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYHshDR3_C40XTWRlEn:-MYIL2FQ44WgwPDcepD7:bon4yua) ([raw file](https://github.com/vmware/container-service-extension/blob/14a4d47b9c297401d223434085b7695353be668f/container_service_extension/developer_guide.md#L66)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

* Make sure feature flags, VCD api version in extension are not changed after CSE install/upgrade
* Ensure that un-supported templates (templates having min_cse_version and max_cse_version which are incompatible with CSE version that is running) are not loaded into runtime config.
* Ensure native placement policies are setup and are loaded to runtime config
</blockquote></details>

As discussed, you can take this in separate PR

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/995)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/developer_guide.md, line 3 at r2](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYIZP6g5XHCX-6U_saH:-MYIZP6g5XHCX-6U_saI:baukr6o) ([raw file](https://github.com/vmware/container-service-extension/blob/becb09a99579b9bdd6411efb4c870b69e466ccba/container_service_extension/developer_guide.md#L3)):*
> ```Markdown
> # Check-list
> 
> This is the check-list of steps to be performed at the beginning of each 
> ```

nit:checklist
___
*[container_service_extension/developer_guide.md, line 24 at r2](https://reviewable.io/reviews/vmware/container-service-extension/995#-MYIblOk5u2PL7YZ2giQ:-MYIblOk5u2PL7YZ2giR:byvprmi) ([raw file](https://github.com/vmware/container-service-extension/blob/becb09a99579b9bdd6411efb4c870b69e466ccba/container_service_extension/developer_guide.md#L24)):*
> ```
> Runtime RDE version represents the RDE version chosen by the CSE server to
> ```
Runtime RDE version represents unique identifiers chosen by the CSE server to

**Pull request merged**
