### PR TITLE
added description for rde 2.1 csi/cpi/cni fields for TKG clusters for cluster spec sample

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1350#-N-ZLuiZ0vN2DSlQUSKa:-N-ZLuiZ0vN2DSlQUSKb:b169o7q) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85e7d40eb58ba11c68d9828424271ab9f1fb05/container_service_extension/rde/models/rde_2_1_0.py#L636)):*
> ```Python
> # the version will be the one specified in the cse server config file. If no corresponding version is specified in the cse server
> # config file for one of these components, then a default version will be used in the case of cpi and csi, and a TKG specific version will be used in the case of cni.
> # spec.settings.network.cni.name: Only \"antrea\" is supported.
> ```

all these are specified in <b>spec.settings</b> . right?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1350#-N-ZLuiZ0vN2DSlQUSKa:-N-ZMStn9mlu58Ci2EQp:be4dgre) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85e7d40eb58ba11c68d9828424271ab9f1fb05/container_service_extension/rde/models/rde_2_1_0.py#L636)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

all these are specified in <b>spec.settings</b> . right? 
</blockquote></details>

I mean they are not under network.

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1350#-N-ZLuiZ0vN2DSlQUSKa:-N-ZMbqk-wpssd4o9g3m:b-ijzi1u) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85e7d40eb58ba11c68d9828424271ab9f1fb05/container_service_extension/rde/models/rde_2_1_0.py#L636)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

I mean they are not under network.
</blockquote></details>

spec.settings.cni.name
spec.settings.cni.version

**Review by rocknes — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1350#-N-ZLuiZ0vN2DSlQUSKa:-N-ZZwvMAo5Lx2tv8vNV:bt8o59a) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85e7d40eb58ba11c68d9828424271ab9f1fb05/container_service_extension/rde/models/rde_2_1_0.py#L636)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

spec.settings.cni.name
spec.settings.cni.version
</blockquote></details>

^+1to Sakthi

**Comment by ltimothy7** [comment]
*[container_service_extension/rde/models/rde_2_1_0.py, line 636 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1350#-N-ZLuiZ0vN2DSlQUSKa:-N-ZfqW6AjJsFjzC-KVl:b7md1n9) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85e7d40eb58ba11c68d9828424271ab9f1fb05/container_service_extension/rde/models/rde_2_1_0.py#L636)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

^+1to Sakthi
</blockquote></details>

Thank you Sakthi and Aritra. My bad. Just fixed

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350#-:-N-ZkAwl1Ql417_34Ra_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1350#-:-N-Zr-Q39gDOrVFlqOT4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Pull request merged**
