### PR TITLE
[VCDA-2129] Report exception for Script execution error

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Update exception handling code to correctly report the error for Script execution error.

@arunmk @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911)

### CODE REVIEW

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/def_/cluster_service.py, line 1950 at r1](https://reviewable.io/reviews/vmware/container-service-extension/911#-MTfxOac4H6M87Nlo_g6:-MTfxOac4H6M87Nlo_g7:bnnfp8g) ([raw file](https://github.com/vmware/container-service-extension/blob/17df60011de76ae104590f2b66007dcd8836f5b0/container_service_extension/def_/cluster_service.py#L1950)):*
> ```Python
>             all_results.append(result)
>         except Exception as e:
>             raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(e)}")  # noqa: E501
> ```

ScriptExecutionError is a custom exception defined in exceptions.py and imported : import container_service_extension.exception.exceptions as e
Is it also an attribute of Exception as e?

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 1950 at r1](https://reviewable.io/reviews/vmware/container-service-extension/911#-MTfxOac4H6M87Nlo_g6:-MTgbqoV6Y2Ey7Wti7OY:bkv8xa0) ([raw file](https://github.com/vmware/container-service-extension/blob/17df60011de76ae104590f2b66007dcd8836f5b0/container_service_extension/def_/cluster_service.py#L1950)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

ScriptExecutionError is a custom exception defined in exceptions.py and imported : import container_service_extension.exception.exceptions as e
Is it also an attribute of Exception as e?
</blockquote></details>

import container_service_extension.exceptions as e

This will be masked by the `as e` here. 
Please rename the imported exception package as E instead of e.

**Review by rocknes — APPROVED** [review]
:lgtm: once the comments are taken care of 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911#-:-MTgc4s-CcdjCIRmxVCx:bpmxwx8)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 1950 at r1](https://reviewable.io/reviews/vmware/container-service-extension/911#-MTfxOac4H6M87Nlo_g6:-MTgjAmd9sBbxT1QMSNV:b-fwaem9) ([raw file](https://github.com/vmware/container-service-extension/blob/17df60011de76ae104590f2b66007dcd8836f5b0/container_service_extension/def_/cluster_service.py#L1950)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

import container_service_extension.exceptions as e

This will be masked by the `as e` here. 
Please rename the imported exception package as E instead of e.
</blockquote></details>

Even if `e` is masked, `e.ScriptExecutionError` will raise another exception.
Renamed exception to `err` and changed import to `E`

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/911)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Pull request merged**
