### PR TITLE
[VCDA-1781,1803, 1735] - Fix missing references to missing methods in cluster_service.py

### PR DESCRIPTION
**Pull request by rocknes**
Refactored cluster_service and vcdbroker to 
1. Hide non public methods
2. Remove references to non existent methods
3. Added additional log statements
4. Fixed an issue where async tracker task was never marked as failed on encountering errors.
5. Fixed an issue where the defined entity lingered around even if the vApp backing the cluster couldn't be deployed.

Testing done:
Ran all cluster operations from cli and POSTman to make sure that the functionality is working as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/724)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAUgUdD1YKEbIivn06:-MGAUgUdD1YKEbIivn07:bab5s8f) ([raw file](https://github.com/vmware/container-service-extension/blob/c474db292bbd447855934d72fc8b9694b6a5a2c1/container_service_extension/def_/cluster_service.py#L45)):*
> ```
> noinspection PyTypeChecker
> ```
Was this line intended to be pushed to master?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 1106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAnfWX18P1btvl_9fo:-MGAnfWX18P1btvl_9fp:b4plr45) ([raw file](https://github.com/vmware/container-service-extension/blob/ec27eb271ae6b725db0125b6665d7d2804ceaf32/container_service_extension/def_/cluster_service.py#L1106)):*
> ```Python
>                                                     vapp)
>         except Exception as err:
>             self._fail_operation_and_resolve_entity(cluster_id,
> ```

If there is an exception and this function is called by `_monitor_resize()`, The entity wont be resolved at all.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/724#-:-MGFD2hZ-QXduFZPiEF9:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/724)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAUgUdD1YKEbIivn06:-MGIDJ969Gxtlm6CMVtG:b4ia6g7) ([raw file](https://github.com/vmware/container-service-extension/blob/c474db292bbd447855934d72fc8b9694b6a5a2c1/container_service_extension/def_/cluster_service.py#L45)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

> ```
> noinspection PyTypeChecker
> ```
Was this line intended to be pushed to master?
</blockquote></details>

No, sorry, I will remove it.
___
*[container_service_extension/def_/cluster_service.py, line 224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAtpVi3UdJBNLKfN50:-MGIDx8a9Uta9ZDYE9w_:bvljs2o) ([raw file](https://github.com/vmware/container-service-extension/blob/c474db292bbd447855934d72fc8b9694b6a5a2c1/container_service_extension/def_/cluster_service.py#L224)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit:The above if statement may be moved just after phase:DefEntityPhase= (compute desired_worker_count etc unless entity is in correct phase)
</blockquote></details>

Addressed.
___
*[container_service_extension/def_/cluster_service.py, line 613 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAymsZ7DmfJEb83JVF:-MGIHTRy76qsTbR2wta_:b9zgupy) ([raw file](https://github.com/vmware/container-service-extension/blob/c474db292bbd447855934d72fc8b9694b6a5a2c1/container_service_extension/def_/cluster_service.py#L613)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Calling `_fail_operation_and_resolve_entity()` is redundant if rollback is True, because we delete the entity itself in the rollback logic.  I think you may have a valid reason.
</blockquote></details>

Thanks for catching this, made the change.
___
*[container_service_extension/def_/cluster_service.py, line 1106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAnfWX18P1btvl_9fo:-MGIOCrA3ORZNxmGc1gv:b-4bbc89) ([raw file](https://github.com/vmware/container-service-extension/blob/ec27eb271ae6b725db0125b6665d7d2804ceaf32/container_service_extension/def_/cluster_service.py#L1106)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If there is an exception and this function is called by `_monitor_resize()`, The entity wont be resolved at all.
</blockquote></details>

I don't think I am following why that would be the case?
We are resolving the entity via the call _fail_operation_and_resolve_entity, right?

This thread is setting the task state as ERROR, when the joins finish in monitor_resize thread, it will look at the task status and realize that something went wrong, and it will update the def entity once again.

Do we need to call resolve after update call too?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 1106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/724#-MGAnfWX18P1btvl_9fo:-MGKCE_D5-gfrcB6sPgc:b85wqrb) ([raw file](https://github.com/vmware/container-service-extension/blob/ec27eb271ae6b725db0125b6665d7d2804ceaf32/container_service_extension/def_/cluster_service.py#L1106)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I don't think I am following why that would be the case?
We are resolving the entity via the call _fail_operation_and_resolve_entity, right?

This thread is setting the task state as ERROR, when the joins finish in monitor_resize thread, it will look at the task status and realize that something went wrong, and it will update the def entity once again.

Do we need to call resolve after update call too?
</blockquote></details>

My bad, Im sorry, i think this is not a valid comment.

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/724#-:-MGKDJHKB6CSrICLeXeR:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/724)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Pull request merged**
