### PR TITLE
[VCDE-986]: Migrate to pika 1.1.0

### PR DESCRIPTION
**Pull request by arunmk**
- Code works with pika==1.1.0. Changes are mainly limited to function signatures of callbacks.
- removed `ssl` and `ssl_accept_all` from the config
- Cleaned up a set of logging statements

This will not support ssl and there need to be more config parameters added to support it. I am not clear if the earlier version supported it. If it did, we can hold off this PR and merge it with SSL included. If it did not, we could take SSL support as a separate ticket.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
:lgtm: with minor comments

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847#-:-MOD26llBVpCiDq1Lfs1:b-ij5eeu)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @rocknes)

___
*[requirements.txt, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/847#-MO7hXq25k7Id94gbVra:-MO7hXq25k7Id94gbVrb:b-7bdjbf) ([raw file](https://github.com/vmware/container-service-extension/blob/d7a33d4865ce2e6d5063ee8432324fa99ccce596/requirements.txt#L17)):*
> ```vimhelp
> 
> # pika 0.13.1
> pika >= 1.0.0
> ```

I think there should also be a < requirement
___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MOCu8I22UCrmbU5vt3C:bf00ouo) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
> ```Python
>             retry_delay=2,
>             socket_timeout=5,
>             blocked_connection_timeout=5)
> ```

Hi @arunmk, could you explain why this `blocked_connection_timeout` parameter is set from the default in Pika? 
___
*[container_service_extension/consumer/amqp_consumer.py, line 212 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOD1JLp35sjavoQwTrr:-MOD1JLp35sjavoQwTrs:bwa0810) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L212)):*
> ```Python
>         properties: pika.spec.BasicProperties,
>         body: bytes
>     ):
> ```

nit: we usually put the closing parenthesis on the same line as the last param. See __init__ of the AMQPConsumer

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, and @rocknes)

___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MODOWZ74LQJbs2IPMqO:b5y8vfa) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Hi @arunmk, could you explain why this `blocked_connection_timeout` parameter is set from the default in Pika? 
</blockquote></details>

There was a `self._connection.add_timeout(5, self.reconnect)` . I was thinking this would replace it, but now I have made changes in `on_connection_closed` similar to earlier code and also as pika examples have it.
___
*[container_service_extension/consumer/amqp_consumer.py, line 212 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOD1JLp35sjavoQwTrr:-MODS8cpBKtU0Ras-MtE:b2nha9w) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L212)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: we usually put the closing parenthesis on the same line as the last param. See __init__ of the AMQPConsumer
</blockquote></details>

ACK

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[requirements.txt, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/847#-MO7hXq25k7Id94gbVra:-MODTHdT1D6B8iW2v2mi:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d7a33d4865ce2e6d5063ee8432324fa99ccce596/requirements.txt#L17)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think there should also be a < requirement
</blockquote></details>

Done.

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MOHriWE1dh9cWR9pIgb:b-993vgy) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

There was a `self._connection.add_timeout(5, self.reconnect)` . I was thinking this would replace it, but now I have made changes in `on_connection_closed` similar to earlier code and also as pika examples have it.
</blockquote></details>

I see; should that `blocked_connection_timeout` parameter not be set in this call?

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MODTKAy6ePLZ1lq8fOw:bksfh6n) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I see; should that `blocked_connection_timeout` parameter not be set in this call?
</blockquote></details>

Yes, that does not exist anymore. I have removed the parameter from the function call.

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MOI4C6R0uW6W91Bnry2:b4wxzyk) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Yes, that does not exist anymore. I have removed the parameter from the function call.
</blockquote></details>

Thank you, Arun; sorry, my screen was not updated, but I see the parameter removed now

**Comment by arunmk** [comment]
___
*[container_service_extension/consumer/amqp_consumer.py, line 58 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOCu8I22UCrmbU5vt3B:-MOIDqWp2rkr51YmUbvk:bts52q2) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L58)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thank you, Arun; sorry, my screen was not updated, but I see the parameter removed now
</blockquote></details>

no worries :)

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847#-:-MOVWwZi8n8m4TS52Rij:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[container_service_extension/consumer/amqp_consumer.py, line 212 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOD1JLp35sjavoQwTrr:-MOVWFDDEVvoyFdU-L3N:b-w2dob5) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L212)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

ACK
</blockquote></details>

The function param and the body are on same alignment, is this not causing a flake8 error?
___
*[docs/cse2_6/CSE_CONFIG.md, line 28 at r4](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOVWlFi-zZdxwMC1BDz:-MOVWlFi-zZdxwMC1BE-:b-9afhu4) ([raw file](https://github.com/vmware/container-service-extension/blob/2a85313e190debec538f63c90cca0c7b5ddb1566/docs/cse2_6/CSE_CONFIG.md#L28)):*
> ```Markdown
>   prefix: vcd
>   routing_key: cse
>   ssl: false
> ```

Please don't change CSE 2.6 documentation.

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/consumer/amqp_consumer.py, line 212 at r2](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOD1JLp35sjavoQwTrr:-MOXb0sR7KrkcoLV-zK5:b-886gsx) ([raw file](https://github.com/vmware/container-service-extension/blob/06815cd016670ab9bad7e78be5cb2f8e767f31bd/container_service_extension/consumer/amqp_consumer.py#L212)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The function param and the body are on same alignment, is this not causing a flake8 error?
</blockquote></details>

Fixed
___
*[docs/cse2_6/CSE_CONFIG.md, line 28 at r4](https://reviewable.io/reviews/vmware/container-service-extension/847#-MOVWlFi-zZdxwMC1BDz:-MOXb4ZkDadgSqsLwP4h:b2nha9w) ([raw file](https://github.com/vmware/container-service-extension/blob/2a85313e190debec538f63c90cca0c7b5ddb1566/docs/cse2_6/CSE_CONFIG.md#L28)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please don't change CSE 2.6 documentation.
</blockquote></details>

ACK

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/847#-:-MOXcCPZ5_zvSUT9yAuV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
