### PR TITLE
[VCDA-1787] Add --id option for cluster commands

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Commands affected:
  * cluster apply
  * cluster delete
  * cluster config
  * cluster info

* Testing done: Checked if the above commands with and without id are working fine
* Screenshot:
Screen Shot 2020-09-15 at 10 50 54 PM
Screen Shot 2020-09-15 at 10 58 28 PM

@sahithi @sakthisunda @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/749)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/749)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/cse.py, line 202 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNBpwP8BmyW31QubNP:-MHNBpwQB-YTI9nVupXx:bofvb9c) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L202)):*
> ```Python
>     metavar='CLUSTER_ID',
>     help="ID of the cluster whose cluster config has to be obtained;"
>          "Supported only for vcd api version >= 35")
> ```

Supported only for CSE API version >=35.
___
*[container_service_extension/client/cse.py, line 207 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNApzZ6cBsPtvvRlhl:-MHNApzZ6cBsPtvvRlhm:b-prai1u) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L207)):*
> ```Python
> 
> \b
> Example
> ```

Can you add an example? Add a note that _id_is applicable only for api version >= 35.
___
*[container_service_extension/client/cse.py, line 219 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNBLS26WCXq_I81ns1:-MHNBLS3-hNgUo0Lo79X:b-p5klzh) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L219)):*
> ```
> Please specify cluster name or cluster id using --id flag if available"
> ```
Please specify cluster name (or) cluster Id. Note that "--id" flag is applicable for API versions >= 35 only.
___
*[container_service_extension/client/cse.py, line 1035 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNCSN3BDXS8iyWrqbh:-MHNCSN3BDXS8iyWrqbi:b-rcrs7t) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L1035)):*
> ```Python
>             result = cluster.get_cluster_info_by_id(cluster_id, org=org)
>         else:
>             result = cluster.get_cluster_info(name, org=org, vdc=vdc)
> ```

Can you rename _get_cluster_info_ -> _get_cluster_info_by_name_ for better clarity? 

(or) 

Have _get_cluster_info_ internally call _get_cluster_info_by_id_. That way, we can avoid if-else blocks here.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/749)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/command_filter.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHPoxyI04WFM1cL1tY7:-MHPoxyJ2Zz2gS_NKl6T:bis5745) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/command_filter.py#L76)):*
> ```Python
>             CommandNameKey.DELETE: ['k8_runtime', 'cluster_id'],
>             CommandNameKey.INFO: ['k8_runtime', 'cluster_id'],
>             CommandNameKey.UPGRADE: ['k8_runtime'],
> ```

Shouldn't upgrade and upgrade-plan also get the 'id' option?
There can be two clusters with same how do you upgrade a specific one?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/command_filter.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHPoxyI04WFM1cL1tY7:-MHPtTPj9O5K6WuAMt7g:bivl2br) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/command_filter.py#L76)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Shouldn't upgrade and upgrade-plan also get the 'id' option?
There can be two clusters with same how do you upgrade a specific one?
</blockquote></details>

upgrade and upgrade plan are currently only available for native clusters and names will be unique for native clusters. So I didn't add the --id option as it is not necessary

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/cse.py, line 1035 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNCSN3BDXS8iyWrqbh:-MHPtlKl2lpfZtzeVwSV:b-iou1u9) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L1035)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you rename _get_cluster_info_ -> _get_cluster_info_by_name_ for better clarity? 

(or) 

Have _get_cluster_info_ internally call _get_cluster_info_by_id_. That way, we can avoid if-else blocks here.
</blockquote></details>

Made changes to call _by_id functions from their respective operation functions

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/cse.py, line 219 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNBLS26WCXq_I81ns1:-MHNTZkz7VMptsVvaVCB:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L219)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> Please specify cluster name or cluster id using --id flag if available"
> ```
Please specify cluster name (or) cluster Id. Note that "--id" flag is applicable for API versions >= 35 only.
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/cse.py, line 207 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNApzZ6cBsPtvvRlhl:-MHNTAxoB1-BUT2iqseu:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L207)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you add an example? Add a note that _id_is applicable only for api version >= 35.
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/cse.py, line 202 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNBpwP8BmyW31QubNP:-MHNRnsE4Hx4q1CR_8hx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L202)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Supported only for CSE API version >=35.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/749)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/client/cse.py, line 1035 at r1](https://reviewable.io/reviews/vmware/container-service-extension/749#-MHNCSN3BDXS8iyWrqbh:-MHmHyKAAx8mjSxlPuAp:bwpgq6g) ([raw file](https://github.com/vmware/container-service-extension/blob/dcf6b544d307577c0dd5787b1a29c104c9ae9e5b/container_service_extension/client/cse.py#L1035)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Made changes to call _by_id functions from their respective operation functions
</blockquote></details>

cool, thanks for doing the latter.

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/749#-:-MHmrCxv2mG1LHoCQbfS:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Pull request merged**
