### PR TITLE
[VCDA-2245] Modify-v36-Handler-Validate-Input-Based-On-Payload-Version

### PR DESCRIPTION
**Pull request by sakthisunda**
- Common handler for V36 and above
- Validation of input based on payload version
- Conversion of input entity to runtime rde model
- Raise exception for invalid payload version  
- TODO: Deprecate v36 handler
- TODO: Testing 

@Anirudh9794 @sahithi @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: all files reviewed, 8 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 231 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjcX0cDm5KpLDzIf6r:-MWjcX0cDm5KpLDzIf6s:b-3vx5zv) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/rde/models/rde_2_0_0.py#L231)):*
> ```Python
>         """Construct rde_2.0.0 native entity from different rde_x.x.x.
> 
>         Use case: converts rde of given payload version to rde of runtime rde
> ```

converts the NativeEntity of the specified RDE version to RDE 2.0.0
___
*[container_service_extension/server/request_dispatcher.py, line 447 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjd6rRDTx4d7FUxGZh:-MWjd6rRDTx4d7FUxGZi:b-t12osu) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_dispatcher.py#L447)):*
> ```Python
>                 'payload_type': '*',
>                 'operation': CseOperation.V36_CLUSTER_CREATE,
>                 'handler': def_cluster_handler.cluster_create,
> ```

Rename it to common_cluster_handler (or) cluster_handler.py
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjhoheBURx1qNEF6EF:-MWjhoheBURx1qNEF6EG:bwegs9j) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L26)):*
> ```Python
> import container_service_extension.security.context.operation_context as ctx
> import container_service_extension.server.request_handlers.request_utils as request_utils  # noqa: E501
> ```

Please add a TODO here to evaluate if we want to handle 1.0 requests coming in at 36.0 in this handler.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjdO-rD9LdqQp9CV-d:-MWjdO-rD9LdqQp9CV-e:b-owmbka) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L27)):*
> ```Python
> import container_service_extension.server.request_handlers.request_utils as request_utils  # noqa: E501
> ```

Please add the docstring to define the responsibility of the functions in this file. Something like below.

# Starting CSE 3.1, this handler handles all the cluster requests coming in at any RDE version (>= 2.0) and at any request api_version (>=36).
# Responsibility of the functions in this file:
# 1. Validate the Input payload based on the (Operation, payload_version). Get the validator based on the payload_version.
# 2. Convert the input entity to runtime rde format.
# 3. Based on the runtime rde, call the appropriate backend method.
# 4. Convert the response to be compatible with the request payload version (If request = X.Y, the response must be X.Z where Z>=Y)
# 5. Return the response
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 46 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjfEn_874JVRckWpV1:-MWjfEna7Qx9zkQJj1Ue:bhf40gf) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L46)):*
> ```Python
>                                        entity=input_entity)
> 
>     converted_rde = _get_runtime_entity_from_input_spec(input_entity)
> ```

1. Consider renaming _get_runtime_entity_from_input_spec -> _convert_input_rde_to_runtime_rde_format()
2. Can you move these methods to rde/utils? behavior_handler.py can also use these methods
_convert_input_rde_to_runtime_rde_format()
_get_runtime_cluster_service
3. Highlight the steps mentioned (in the above docstring) in the form of comments.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjgjBlEvbk6c38hB9V:-MWjgjBlEvbk6c38hB9W:bxx827z) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L48)):*
> ```Python
>     converted_rde = _get_runtime_entity_from_input_spec(input_entity)
>     svc = _get_runtime_cluster_service(op_ctx)
>     return asdict(svc.create_cluster(converted_rde))
> ```

Please add a TODO here for the future.
Response RDE must be compatible with the request RDE. Conversions may be needed especially if there is a major version difference in the input RDE and runtime RDE.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 151 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjhkVDA9xFQ0c9B5I8:-MWjhkVDA9xFQ0c9B5I9:b-4iv2sg) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L151)):*
> ```Python
>                  operation=BehaviorOperation.UPDATE_CLUSTER)
> 
>     converted_rde = _get_runtime_entity_from_input_spec(input_entity)
> ```

Same here comments and TODO
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 251 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjiPqM5REuqcJqUAQn:-MWjiPqM5REuqcJqUAQo:bf8wkmv) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L251)):*
> ```Python
>         rde_constants.MAP_INPUT_PAYLOAD_VERSION_TO_RDE_VERSION[payload_version])  # noqa: E501
>     input_rde: AbstractNativeEntity = InputNativeEntityClass(**input_entity)  # noqa: E501
>     return RuntimeNativeEntityClass.from_native_entity(input_rde)
> ```

I think it is safe enough to remove the converters package as you embedded conversions into the model class. As long as we don't hit any cyclic dependencies we can rely on _from_native_entity()_ method.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: all files reviewed, 8 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjdO-rD9LdqQp9CV-d:-MWjjA110BJQNr85NWDz:b-fbrf45) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L27)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add the docstring to define the responsibility of the functions in this file. Something like below.

# Starting CSE 3.1, this handler handles all the cluster requests coming in at any RDE version (>= 2.0) and at any request api_version (>=36).
# Responsibility of the functions in this file:
# 1. Validate the Input payload based on the (Operation, payload_version). Get the validator based on the payload_version.
# 2. Convert the input entity to runtime rde format.
# 3. Based on the runtime rde, call the appropriate backend method.
# 4. Convert the response to be compatible with the request payload version (If request = X.Y, the response must be X.Z where Z>=Y)
# 5. Return the response
</blockquote></details>

Sorry about the big font. I added hash to indicate comment .

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 231 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjcX0cDm5KpLDzIf6r:-MWk5Xqk6E4zI0nUomx7:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/rde/models/rde_2_0_0.py#L231)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

converts the NativeEntity of the specified RDE version to RDE 2.0.0
</blockquote></details>

Done.
___
*[container_service_extension/server/request_dispatcher.py, line 447 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjd6rRDTx4d7FUxGZh:-MWk5YrxDFmEkW_uZVXP:bs7wumx) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_dispatcher.py#L447)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename it to common_cluster_handler (or) cluster_handler.py
</blockquote></details>

Done. 
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 26 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjhoheBURx1qNEF6EF:-MWk5dSv79cR-V7nU_TM:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L26)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a TODO here to evaluate if we want to handle 1.0 requests coming in at 36.0 in this handler.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 27 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjdO-rD9LdqQp9CV-d:-MWk5etR0S7PgJ8coLFg:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L27)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Sorry about the big font. I added hash to indicate comment .
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 46 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjfEn_874JVRckWpV1:-MWk5iUN5aEKof10ReVt:bgy0qyi) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L46)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

1. Consider renaming _get_runtime_entity_from_input_spec -> _convert_input_rde_to_runtime_rde_format()
2. Can you move these methods to rde/utils? behavior_handler.py can also use these methods
_convert_input_rde_to_runtime_rde_format()
_get_runtime_cluster_service
3. Highlight the steps mentioned (in the above docstring) in the form of comments.
</blockquote></details>

Done. Moved the methods to corresponding utils to avoid circular import.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjgjBlEvbk6c38hB9V:-MWk61BP5zPs7COKXQYm:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L48)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a TODO here for the future.
Response RDE must be compatible with the request RDE. Conversions may be needed especially if there is a major version difference in the input RDE and runtime RDE.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 151 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjhkVDA9xFQ0c9B5I8:-MWk61rW3s8hCDyEsoKT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L151)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here comments and TODO
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/def_cluster_handler.py, line 251 at r1](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWjiPqM5REuqcJqUAQn:-MWk6P3KBjzA0OmnW8AT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/84354f298616fa13a7b205537b3172080159eaa6/container_service_extension/server/request_handlers/def_cluster_handler.py#L251)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think it is safe enough to remove the converters package as you embedded conversions into the model class. As long as we don't hit any cyclic dependencies we can rely on _from_native_entity()_ method.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: two minor comments

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972#-:-MWkM1wt51UCpfGnEi4O:b96a5fm)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/common/utils.py, line 10 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLUcM5cuul2EbXr7R:-MWkLUcM5cuul2EbXr7S:b-3hopwz) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/rde/common/utils.py#L10)):*
> ```Python
> 
> 
> def get_runtime_cluster_service(op_ctx: ctx.OperationContext):
> ```

There is already a utils file under rde package
rde/utils.py. we can move that function to there.
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLmJSDyjT8Y4eDVjO:-MWkLmJSDyjT8Y4eDVjP:bb6ht36) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/server/request_handlers/cluster_handler.py#L2)):*
> ```Python
> # container-service-extension
> # Copyright (c) 2020 VMware, Inc. All Rights Reserved.
> ```

2021

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972#-:-MWkNCqLDhQgxZJKaeJK:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/common/utils.py, line 10 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLUcM5cuul2EbXr7R:-MWkOCQCDrCAnQRXEwQY:b-f0hfwc) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/rde/common/utils.py#L10)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

There is already a utils file under rde package
rde/utils.py. we can move that function to there.
</blockquote></details>

Having this method in rde/utils.py cause import errors that blocks cse startup : cse run
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLmJSDyjT8Y4eDVjO:-MWkO8io0aK-66sUpEMq:b-pyycz9) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/server/request_handlers/cluster_handler.py#L2)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done. thx

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: 9 of 10 files reviewed, 10 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/common/utils.py, line 10 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLUcM5cuul2EbXr7R:-MWkQ4_W3IXFIDztQFPK:b-v4d8mq) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/rde/common/utils.py#L10)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Having this method in rde/utils.py cause import errors that blocks cse startup : cse run
</blockquote></details>

For example:
it starts with server_utils ... -> pyvcloud_utils.py ----> server_utils.py

File "/Users/sakthis/container-service-extension/container_service_extension/common/utils/pyvcloud_utils.py", line 28, in <module>
    from container_service_extension.common.utils.server_utils import get_server_runtime_config  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/common/utils/server_utils.py", line 14, in <module>
    import container_service_extension.rde.models.common_models as common_models
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/models/common_models.py", line 11, in <module>
    from container_service_extension.rde import utils as def_utils
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/utils.py", line 27, in <module>
    import container_service_extension.rde.backend.cluster_service_factory as cluster_service_factory  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/backend/cluster_service_factory.py", line 8, in <module>
    from container_service_extension.rde.backend.cluster_service_1_x import ClusterService as ClusterService1X  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/backend/cluster_service_1_x.py", line 43, in <module>
    import container_service_extension.installer.templates.local_template_manager as ltm  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/installer/templates/local_template_manager.py", line 20, in <module>
    from container_service_extension.common.utils.pyvcloud_utils import get_org
ImportError: cannot import name 'get_org' from 'container_service_extension.common.utils.pyvcloud_utils' (/Users/sakthis/container-service-extension/container_service_extension/common/utils/pyvcloud_utils.py)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/972)* status: 8 of 10 files reviewed, 10 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/common/utils.py, line 10 at r2](https://reviewable.io/reviews/vmware/container-service-extension/972#-MWkLUcM5cuul2EbXr7R:-MWkQSej7skcZnu6e6vB:b-77poev) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa6742946e32c1529f471c5d6a17ac305e2b597/container_service_extension/rde/common/utils.py#L10)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

For example:
it starts with server_utils ... -> pyvcloud_utils.py ----> server_utils.py

File "/Users/sakthis/container-service-extension/container_service_extension/common/utils/pyvcloud_utils.py", line 28, in <module>
    from container_service_extension.common.utils.server_utils import get_server_runtime_config  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/common/utils/server_utils.py", line 14, in <module>
    import container_service_extension.rde.models.common_models as common_models
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/models/common_models.py", line 11, in <module>
    from container_service_extension.rde import utils as def_utils
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/utils.py", line 27, in <module>
    import container_service_extension.rde.backend.cluster_service_factory as cluster_service_factory  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/backend/cluster_service_factory.py", line 8, in <module>
    from container_service_extension.rde.backend.cluster_service_1_x import ClusterService as ClusterService1X  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/rde/backend/cluster_service_1_x.py", line 43, in <module>
    import container_service_extension.installer.templates.local_template_manager as ltm  # noqa: E501
  File "/Users/sakthis/container-service-extension/container_service_extension/installer/templates/local_template_manager.py", line 20, in <module>
    from container_service_extension.common.utils.pyvcloud_utils import get_org
ImportError: cannot import name 'get_org' from 'container_service_extension.common.utils.pyvcloud_utils' (/Users/sakthis/container-service-extension/container_service_extension/common/utils/pyvcloud_utils.py)
</blockquote></details>

Moved this functionality to ClusterServiceFactory.get_cluster_service() with default handling for arg: rde_version_in_use=None

**Pull request merged**
