### PR TITLE
Move set -e command so script does not fail on lsb_release

### PR DESCRIPTION
**Pull request by andrew-ni**
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-ni)

___
*[cluster_scripts/v2_x/control_plane.sh, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yGAG5AJm9hcfvpFz:-Mw2yGAG5AJm9hcfvpG-:b-s5sd6j) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L22)):*
> ```Shell
>     fi
> fi
> ```

Does there need to be a `set e` here?
___
*[cluster_scripts/v2_x/node.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yL91-QwpCJSy4Jfk:-Mw2yL91-QwpCJSy4Jfl:biy67bl) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/node.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> while [ `systemctl is-active docker` != 'active' ]; do echo 'waiting for docker'; sleep 5; done
> ```

Should `set e` be before here too? Might be helpful to get more input @sakthisunda can you comment

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-ni and @ltimothy7)

___
*[cluster_scripts/v2_x/node.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yL91-QwpCJSy4Jfk:-Mw3Ei5REKDb_m5sgHRG:bzhpg2k) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/node.sh#L2)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should `set e` be before here too? Might be helpful to get more input @sakthisunda can you comment
</blockquote></details>

set -e has the scope from where it is set to the end of file. So it may be moved just before <b>if loop</b> but after <b>lsb_release -a</b>. So, it is one time setting.

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-ni and @ltimothy7)

___
*[cluster_scripts/v2_x/control_plane.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw3F_N6C8R3mHcZRDFh:-Mw3F_N70kJ1IN5Y9hVx:b6ano45) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> tkg_plus_kind="TKG+"
> ```

I think it is helpful to leave `set -e` for the whole script, and then we can disable `set -e` by doing `set +x` when we don't want failures to cause the script to fail

I think we should have this structure for both the control plane and worker script:

`set -e` at the top of the script

`set +e` right before lsb_release
lsb_release
`set -e` right after after lsb_release

**Comment by ltimothy7** [comment]
___
*[cluster_scripts/v2_x/node.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yL91-QwpCJSy4Jfk:-Mw3G9GB442Dr-UfhYlG:bo4ij10) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/node.sh#L2)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

set -e has the scope from where it is set to the end of file. So it may be moved just before <b>if loop</b> but after <b>lsb_release -a</b>. So, it is one time setting.
</blockquote></details>

Thank you Sakthi

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-ni and @ltimothy7)

___
*[cluster_scripts/v2_x/control_plane.sh, line 12 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw4QQ5U9p5AOXc85r43:-Mw4QQ5U9p5AOXc85r44:b-5ifmfa) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L12)):*
> ```Shell
>     kubeadm init --config=$kubeadm_config_path > /root/kubeadm-init.out
> else
>     lsb_release -a | grep -q 20.04
> ```

Using,  <b>lsb_release -rs | grep -q 20.04</b> you won't need to move around set -e around. It can be kept where it was.

Else wrong <b>kubeadm init</b> will be executed.

I executed the following commands in ubuntu vm . Noticed that <b>lsb_release -rs</b>  is the only change we require to execute the right kubeadm init.



_Code snippet:_
```Shell
root@mstr-qxww:~# lsb_release -a | grep -q 20.04
No LSB modules are available.
root@mstr-qxww:~# lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
root@mstr-qxww:~# lsb_release -rs | grep -q 20.04
root@mstr-qxww:~# echo $?
1
root@mstr-qxww:~#
```
___
*[cluster_scripts/v2_x/node.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yL91-QwpCJSy4Jfk:-Mw4OEp90gSCNh2v_Ciw:b-zfaf3z) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/node.sh#L2)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thank you Sakthi
</blockquote></details>

Sorry I am wrong. Having set -e just after lsb_release -a will always set the exit status to 0  which is incorrect.

 lsb_release -a | grep -q 20.04 is important to execute the right <b>kubeadm join</b>

Using,  <b>lsb_release -rs | grep -q 20.04</b> you won't need to move set -e around. It can be kept where it was



_Code snippet:_
```Shell
root@mstr-qxww:~# lsb_release -a | grep -q 20.04
No LSB modules are available.
root@mstr-qxww:~# lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
root@mstr-qxww:~# lsb_release -rs | grep -q 20.04
root@mstr-qxww:~# echo $?
1
root@mstr-qxww:~#
```

**Comment by andrew-ni** [comment]
I think I found a better way to do this; i'll implement tomorrow

```bash
cmd="$(lsb_release -rs)"
if [[ $cmd =~ "20.04" ]]; then
  # do ubuntu 20.04 stuff
else
  # do non ubuntu 20.04 stuff
fi
```

**Review by andrew-ni — COMMENTED** [review]
> Dismissed @ltimothy7 and @sakthisunda from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x/control_plane.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw3F_N6C8R3mHcZRDFh:-MwEPNg6ETmkeQS0Wsl9:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L2)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it is helpful to leave `set -e` for the whole script, and then we can disable `set -e` by doing `set +x` when we don't want failures to cause the script to fail

I think we should have this structure for both the control plane and worker script:

`set -e` at the top of the script

`set +e` right before lsb_release
lsb_release
`set -e` right after after lsb_release
</blockquote></details>

Done.
___
*[cluster_scripts/v2_x/control_plane.sh, line 12 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw4QQ5U9p5AOXc85r43:-MwEPOqI823uQNtpWXc-:b-jfmg6s) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L12)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

Using,  <b>lsb_release -rs | grep -q 20.04</b> you won't need to move around set -e around. It can be kept where it was.

Else wrong <b>kubeadm init</b> will be executed.

I executed the following commands in ubuntu vm . Noticed that <b>lsb_release -rs</b>  is the only change we require to execute the right kubeadm init.
</blockquote></details>

Resolved with new changes
___
*[cluster_scripts/v2_x/control_plane.sh, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yGAG5AJm9hcfvpFz:-MwEPVBWBPXgek07onyT:b-jfmg6s) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/control_plane.sh#L22)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Does there need to be a `set e` here?
</blockquote></details>

Resolved with new changes
___
*[cluster_scripts/v2_x/node.sh, line 2 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1309#-Mw2yL91-QwpCJSy4Jfk:-MwEPadE0VqgaMZL4Kid:b-d8ftvg) ([raw file](https://github.com/vmware/container-service-extension/blob/90cf8ebe09ae602983d3d5390151bddf3036ffef/cluster_scripts/v2_x/node.sh#L2)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

Sorry I am wrong. Having set -e just after lsb_release -a will always set the exit status to 0  which is incorrect.

 lsb_release -a | grep -q 20.04 is important to execute the right <b>kubeadm join</b>

Using,  <b>lsb_release -rs | grep -q 20.04</b> you won't need to move set -e around. It can be kept where it was


</blockquote></details>

thanks! resolved with new changes

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1309)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

**Pull request merged**
