### PR TITLE
Port [VCDE-986]: Migrate to pika 1.1.0 (#847) from cse_3_0_updates

### PR DESCRIPTION
**Pull request by rocknes**
Port [VCDE-986]: Migrate to pika 1.1.0 (#847) from cse_3_0_updates to master.

Testing done:
Checked that no errors were reported by flake8

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/881)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/881)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/881#-:-MRb_LctBYg4cwI8ydr3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by arunmk — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/881)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Comment by arunmk** [comment]
LGTM, thanks!

**Comment by arunmk** [comment]
:lgtm:

**Pull request merged**
