### PR TITLE
[VCDA-2197] Framework to connect behavior processor to the backend.

### PR DESCRIPTION
**Pull request by sahithi**
1. Added Exception handling to the behavior_handler.py
2. Made the validator more generic so that it can be used by behavior handlers and enhanced the validate method to perform more checks.
3. Refactored v36_handler to accommodate the above changes in validators.
4. Added new method in rde/utils.py to get_rde_version_introduced_at_vcd_version; renamed get_rde_version_by_vcd_api_version -> get_runtime_rde_version_by_vcd_api_version
5. Modified BehaviorOperationContext- float(api_version).
6. End to end (dummy) cluster creation workflow tested.
7. Return payloads (success and error) tested and made some changes.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 4 of 18 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 71 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVriBktEUhd1i6Tot_6:-MVriBku5eoEOAwVTOpy:b-l7j04h) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L71)):*
> ```
> input_entity: AbstractNativeEntity = NativeEntityClass(**entity)
> ```
My understanding is for validation, input_spec is always from input_entity and
the current entity should be from entity_id.

Here we try to get input from either of these.  In this case, if we don't specify one of them say entity dictionary as input, validation will be using input spec and current spec from the same cluster.  Is this to handle behavior processing.?

**Review by sakthisunda — APPROVED** [review]
> Reviewed 10 of 18 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: all files reviewed, 4 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/constants.py, line 99 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsKujT2xBWvhfNw2y6:-MVsKujT2xBWvhfNw2y7:bfv1a0n) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/constants.py#L99)):*
> ```Python
> # Examples:
> # Mapping for CSE 3.1:
> # MAP_VCD_API_VERSION_TO_RDE_VERSION = {
> ```

Comment is still using the old name
___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 18 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsLOMiDS8j29E0CfSy:-MVsLOMiDS8j29E0CfSz:b7fuoga) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/backend/cluster_service_factory.py#L18)):*
> ```Python
> 
> class ClusterServiceFactory:
>     def __init__(self, op_ctx: Union[ctx.OperationContext, BehaviorOperationContext]):  # noqa: E501
> ```

I think it will be better to create a superclass which both OperationContext and BehaviorOperationContext inherits
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 48 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsNhz45edRn7k-VuVA:-MVsNhz45edRn7k-VuVB:b5xw5ai) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L48)):*
> ```Python
>         entity_svc = DefEntityService(cloudapi_client=cloudapi_client)
> 
>         # Reject the request if rde_in_use is less than rde version introduced
> ```

Is this check necessary? I think this code is checking the validity of CSE code itself.
This check is out of scope of validation as it is independent of the entity supplied by the User. If we are adding such checks, it should be added in CSE run
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 86 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsa-B064n2F98dkC7R:-MVsa-B1BEoNRP2mLuCG:b-2ep3eb) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L86)):*
> ```Python
>             current_entity_spec = \
>                 rde_utils.construct_cluster_spec_from_entity_status(
>                     current_entity_status, rde_constants.RDEVersion.RDE_2_0_0.value)  # noqa: E501
> ```

If in future, we are validating RDE 2-0-0 input (request to v36 handler) and VCD has RDE 2.1.0 registered, are we not comparing Spec from 2 different RDE versions? Is this expected behavior?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 71 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVs_Yx60-3dFvIQs3UZ:-MVs_Yx705BDD5LzcOki:b-gigh4q) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L71)):*
> ```Python
>             input_entity: AbstractNativeEntity = NativeEntityClass(**entity)
>         elif entity_id:
>             input_entity: AbstractNativeEntity = entity_svc.get_entity(entity_id).entity  # noqa: E501
> ```

elif entity_id:

When is this else part is used in validation? some comment will be useful for more understanding.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/constants.py, line 99 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsKujT2xBWvhfNw2y6:-MVsuwk78TdIW2lhEw1y:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/constants.py#L99)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Comment is still using the old name
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 18 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsLOMiDS8j29E0CfSy:-MVsvAUUCkCE5K65HJPh:b-z8k4df) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/backend/cluster_service_factory.py#L18)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think it will be better to create a superclass which both OperationContext and BehaviorOperationContext inherits
</blockquote></details>

I still hold the same opinion as I shared a year ago -  on renaming the _OperationContext_ to _SecurityContext_ (or) _UserContext_ (or) _AuthContext_. If we take a look at the current _OperationContext_, all it has is user and client details. It does not hold any information about the actual operation.

In contrast, BehaviorOperationContext really holds the details about the requested operation like behavior_id, entity_id, task_id, request_id, and user_ctx. That's why I made BehaviorOperationContext compose the OperationContext (which I think is supposed to be User/SecurityContext) instead of inheritance.

If you still think we need inheritance here, let us discuss and we can take this up in another PR.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 48 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsNhz45edRn7k-VuVA:-MVsxwiO9O_3aO3M04b_:b-fmbc8t) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L48)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is this check necessary? I think this code is checking the validity of CSE code itself.
This check is out of scope of validation as it is independent of the entity supplied by the User. If we are adding such checks, it should be added in CSE run
</blockquote></details>

This check is made on the basis of the api_version specified by the end-user in the HTTP request header. Hence, I put this in the validator that validates the input request.

Say, the user sends RDE 2.0 with api_version=36.0, when rde_in_use =1.0, how and where do we want to throw the reject error? Makes sense?
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 71 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVriBktEUhd1i6Tot_6:-MVtBqVz1-4D9mdgIzK0:bpo4zu3) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L71)):*
> My understanding is for validation, input_spec is always from input_entity and
> the current entity should be from entity_id.
That's right.

I was trying to get the validator signature to look like we are validating the input request in its entirety rather than operation-specific validation. Because the only operation we compare against the current entity is "update". But we may still want to call this method for create, delete, get_kubeconfig operations. That is why I modified the signature to be a generic validate method, but not necessarily for a particular "update" operation. Hope this makes sense. 
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 71 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVs_Yx60-3dFvIQs3UZ:-MVtD-a8720s4avVT4ex:bt42pjp) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L71)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

elif entity_id:

When is this else part is used in validation? some comment will be useful for more understanding.
</blockquote></details>

I am rethinking a bit here. I will remove the else block, as there is no use-case as of today. We can add later if there is a need.
I  have augmented the docstring with more details on the params. Let me know if you still find it confusing.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 86 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsa-B064n2F98dkC7R:-MVtB6qe4c0-cEV1BDIG:bio88qt) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L86)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If in future, we are validating RDE 2-0-0 input (request to v36 handler) and VCD has RDE 2.1.0 registered, are we not comparing Spec from 2 different RDE versions? Is this expected behavior?
</blockquote></details>

It is expected.

As long as we continue to support RDE 2.0.0 request, we need to compare the status of the current RDE version with the spec of 2.0.0.
If you go another level into construct_cluster_spec_from_entity_status, you will see RDE version-specific construct methods.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 48 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsNhz45edRn7k-VuVA:-MVtHt8C0hUOtkkXM_hU:b-nccr66) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L48)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This check is made on the basis of the api_version specified by the end-user in the HTTP request header. Hence, I put this in the validator that validates the input request.

Say, the user sends RDE 2.0 with api_version=36.0, when rde_in_use =1.0, how and where do we want to throw the reject error? Makes sense?
</blockquote></details>

I think i am missing something? If api_version=36.0 is not supported, VCD will reject the request. And if api_version=36.0, then the request is valid as rde_in_use should be 2.0

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: 11 of 18 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 18 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsLOMiDS8j29E0CfSy:-MVtXg7w8Ck5QW7AsdhV:bfhibu2) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/backend/cluster_service_factory.py#L18)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I still hold the same opinion as I shared a year ago -  on renaming the _OperationContext_ to _SecurityContext_ (or) _UserContext_ (or) _AuthContext_. If we take a look at the current _OperationContext_, all it has is user and client details. It does not hold any information about the actual operation.

In contrast, BehaviorOperationContext really holds the details about the requested operation like behavior_id, entity_id, task_id, request_id, and user_ctx. That's why I made BehaviorOperationContext compose the OperationContext (which I think is supposed to be User/SecurityContext) instead of inheritance.

If you still think we need inheritance here, let us discuss and we can take this up in another PR.
</blockquote></details>

Renamed BehaviorOperationContext to BehaviorRequestContext to avoid confusion. If there is any ambiguity, let us discuss offline.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 48 at r2](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVsNhz45edRn7k-VuVA:-MVtWy0G61xrJ6J96M6Q:ba94xdy) ([raw file](https://github.com/vmware/container-service-extension/blob/34ab120bd3cecb7f2fcb4a67f7248eb1636dfbe5/container_service_extension/rde/validators/validator_rde_2_x.py#L48)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think i am missing something? If api_version=36.0 is not supported, VCD will reject the request. And if api_version=36.0, then the request is valid as rde_in_use should be 2.0
</blockquote></details>

Ah, you are right. VCD will be the first gatekeeper. I missed that point. This is a redundant check.
Thanks Aniruddh.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 5 of 5 files at r5, 1 of 1 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957#-:-MVxVg3v4HADe621kCFQ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 39 at r8](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVxVFRm3cAHvrRKMiUv:-MVxVFRm3cAHvrRKMiUw:b53irpa) ([raw file](https://github.com/vmware/container-service-extension/blob/2936d5f930a4d4b00aa8ae9b4eaaec6051400c8d/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L39)):*
> ```Python
>     # Validate the input
>     rde_validator_factory.get_validator(
>         rde_version=rde_constants.RDEVersion.RDE_2_0_0). \
> ```

Should the validation here be done by getting the validator according to the RDE_version_introduced_at_api_version? instead of hard-coding it to 2.0.0?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 39 at r8](https://reviewable.io/reviews/vmware/container-service-extension/957#-MVxVFRm3cAHvrRKMiUv:-MW-X8o209BNX0bJ610-:b9juv35) ([raw file](https://github.com/vmware/container-service-extension/blob/2936d5f930a4d4b00aa8ae9b4eaaec6051400c8d/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L39)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should the validation here be done by getting the validator according to the RDE_version_introduced_at_api_version? instead of hard-coding it to 2.0.0?
</blockquote></details>

We can either do as you suggested or this. We have separate API handlers anyway for each API version. If there had been only one handler for all API versions, your suggestion is the right way to go and that's what I did in the behavior_handler. 

Given we have individual handlers already, I am leaving this as now, it improves readability. Readers will get to instantly know that 2.0.0 is what is introduced at Api 36.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/957)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
