### PR TITLE
[VCDA-2168] Upgrader for CSE 3.1

### PR DESCRIPTION
**Pull request by sakthisunda**
- Upgrade for CSE 3.1.0
- Upgrade CSE code from CSE 3.0.x to 3.1.0
- Tests done
- 33/34 native cluster upgrade to v36/RDE 2.0
- 33/44 native cluster upgrade to v35/RDE 1.0
- v35/RDE 1.0 upgrade to v35/RDE 2.0
- TODO : CSE 3.1/v34 upgrade to CSE 3.1 v35/v36 legacy_mode=True
- Fobidden upgrade checks, user tests
@Anirudh9794  @rocknes @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 2472 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-dLqC0QbM_0PEayE:-MVr-dLqC0QbM_0PEayF:b-z3vugg) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/installer/configure_cse.py#L2472)):*
> ```Python
>     cse_supported_api_versions = set(server_constants.SUPPORTED_VCD_API_VERSIONS)  # noqa: E501
>     common_supported_api_versions = list(cse_supported_api_versions.intersection(vcd_supported_api_versions))  # noqa: E501
>     target_vcd_api_version = max([float(x) for x in common_supported_api_versions])  # noqa: E501
> ```

How about "runtime_vcd_api_version"? @rocknes 
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 209 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-WokERjjaDJgYRym:-MVr-WokERjjaDJgYRyn:b-p6u7ln) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/rde/models/rde_1_0_0.py#L209)):*
> ```Python
> 
>     @classmethod
>     def from_cluster_data(cls, cluster: dict, kind: str):
> ```

I don't think we would need these methods. Constructors of Native entity are self-sufficient to construct the entity from dict.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 259 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-8ZN-Ys-7R8NtWpz:-MVr-8ZO4qCWcyBlWI8v:b-p6u7ln) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/rde/models/rde_2_0_0.py#L259)):*
> ```Python
> 
>     @classmethod
>     def from_cluster_data(cls, cluster: dict, kind: str):
> ```

I don't think we would need these methods. Constructors of Native entity are self-sufficient to construct the entity from dict.

**Review by sahithi — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 2472 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-dLqC0QbM_0PEayE:-MVraWPM2l5pEoNlgFSH:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/installer/configure_cse.py#L2472)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

How about "runtime_vcd_api_version"? @rocknes 
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 209 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-WokERjjaDJgYRym:-MVraXZi-prtjnEq1p8D:bjymkmd) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/rde/models/rde_1_0_0.py#L209)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't think we would need these methods. Constructors of Native entity are self-sufficient to construct the entity from dict.
</blockquote></details>

To make the purpose of this method more clear, changed the doc string correctly as discussed. thx
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 259 at r1](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVr-8ZN-Ys-7R8NtWpz:-MVrao0_4YxqJ9t0E8hE:b-kgkqij) ([raw file](https://github.com/vmware/container-service-extension/blob/c72057fe56af8c182b0f8921ed51deede7065b84/container_service_extension/rde/models/rde_2_0_0.py#L259)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't think we would need these methods. Constructors of Native entity are self-sufficient to construct the entity from dict.
</blockquote></details>

To make the purpose of this method more clear, changed the doc string correctly as discussed. thx

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor comments

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956#-:-MVsJD0D4wU63NKvkbKz:b-kfw89e)* status: all files reviewed, 7 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1494 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVs2bqR0ApJ1V7O9ME4:-MVs2bqR0ApJ1V7O9ME5:b-ump6z7) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1494)):*
> ```Python
>             raise Exception(update_path_not_valid_msg)
> 
>         if target_vcd_api_version in (vCDApiVersion.VERSION_35.value, vCDApiVersion.VERSION_36.value):  # noqa: E501
> ```

TODO for addressing CSE upgrade from 33.0/34.0 -> 34.0 with legacy_mode=True
___
*[container_service_extension/installer/configure_cse.py, line 1589 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVs2y34CQYjnGDzQyDv:-MVs2y34CQYjnGDzQyDw:baxe95b) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1589)):*
> ```Python
>                             admin_password, msg_update_callback=utils.NullPrinter(),  # noqa: E501
>                             log_wire=False):
>     """Handle upgrade to supported api version and rde.
> ```

Handle upgrade when VCD supports RDE
___
*[container_service_extension/installer/configure_cse.py, line 1640 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsIo-QEdc6bT0e9kXW:-MVs9YFuEsQAPKXYujk4:b-lltv4n) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1640)):*
> ```Python
> 
>     # Update clusters to have auto generated password and fix their metadata
>     _fix_cluster_metadata(
> ```

Do we need this step now since fixing cluster metadata is taken care of in CSE 3.0?
___
*[container_service_extension/installer/configure_cse.py, line 2330 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsD-TbDGmI3q9RNuXs:-MVsD-TbDGmI3q9RNuXt:b-gdslsr) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L2330)):*
> ```Python
>     schema_svc = def_schema_svc.DefSchemaService(cloudapi_client)
>     server_rde_version: str = \
>         def_utils.get_rde_version_by_vcd_api_version(float(_get_computed_target_vcd_version(client=client)))  # noqa: E501
> ```

Instead of re-calculating, can this be passed down from the caller as a parameter? I think this should be a required parameter for the funcion.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 1494 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVs2bqR0ApJ1V7O9ME4:-MVsiSOLDRQnlbU95WUC:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1494)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

TODO for addressing CSE upgrade from 33.0/34.0 -> 34.0 with legacy_mode=True
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 1589 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVs2y34CQYjnGDzQyDv:-MVsil54AM-JrJiXkHRf:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1589)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Handle upgrade when VCD supports RDE
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 1640 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsIo-QEdc6bT0e9kXW:-MVsiuUqB_6d5a2z7QIw:bmvfk0o) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1640)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Do we need this step now since fixing cluster metadata is taken care of in CSE 3.0?
</blockquote></details>

_fix_cluster_metadata()
_fix_cluster_admin_password()

@rocknes : please validate if these two method are required or going away in this upgrade.
___
*[container_service_extension/installer/configure_cse.py, line 2330 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsD-TbDGmI3q9RNuXs:-MVsla78DNkPavmR8A5o:b-73bpev) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L2330)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Instead of re-calculating, can this be passed down from the caller as a parameter? I think this should be a required parameter for the funcion.
</blockquote></details>

Getting the target version may change in the upcoming other commits. I will wait and do that because this is currently common to both installer and upgrader.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 13 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1494 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVs2bqR0ApJ1V7O9ME4:-MVvgQNI5eZJAnxX_aa4:b-cwhvy2) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1494)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Have we not decided to do upgrades only from the n-1 version?
In the context of legacy mode, that means "allow upgrade from CSE 3.0 running at 34.0 to CSE 3.1at 36.0 with legacy_mode=true". This is the only valid upgrade path when legacy_mode is set to true.
@rocknes is this correct?
___
*[container_service_extension/installer/configure_cse.py, line 1475 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvenp4Arb4ZeRpbs3x:-MVveUG34PKHrE1D1D3r:b-d9rs8b) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L1475)):*
> ```Python
>         legacy_mode = config['service']['legacy_mode']
>         update_path_not_valid_msg = f"CSE upgrade path (CSE '{ext_cse_version}', vCD api 'v{ext_vcd_api_version}') -> "  # noqa: E501
>         update_path_not_valid_msg += f"(CSE '{target_cse_version}', vCD api " \
> ```

nit: upgrade_path_not_valid_msg
___
*[container_service_extension/installer/configure_cse.py, line 1495 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvk1eL6g5K4AYUTLYr:-MVvk1eL6g5K4AYUTLYs:bbi8aqb) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L1495)):*
> ```Python
>             raise Exception(update_path_not_valid_msg)
> 
>         if target_vcd_api_version in (vCDApiVersion.VERSION_35.value, vCDApiVersion.VERSION_36.value):  # noqa: E501
> ```

Wondering if we still need to condition our if-else blocks on vcd_api_version? Shouldn't it be the CSE version alone? And then once we are inside the block, we can determine runtime_rde based on the runtime_api_version @rocknes 
___
*[container_service_extension/installer/configure_cse.py, line 1496 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvjZKH81N50nOq-LRZ:-MVvjZKI6_t8_iGV-axf:b1ib8s7) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L1496)):*
> ```Python
> 
>         if target_vcd_api_version in (vCDApiVersion.VERSION_35.value, vCDApiVersion.VERSION_36.value):  # noqa: E501
>             _upgrade_to_rde_cluster(
> ```

This method can be renamed. Upgrade from one version to another version can encompass several other things other than upgrading RDEs like preparing placement policies, Avi LB etc

How about _upgrade_to_CSE_3_1() (or) _upgrade_to_36()?

_upgrade_to_cse31 may have something about preparing AVI LB or SEGs, please check with Arun.
___
*[container_service_extension/installer/configure_cse.py, line 2311 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvj3yNE4h0gqALmOFV:-MVvj3yNE4h0gqALmOFW:b-k1kr49) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2311)):*
> ```Python
> 
> 
> def _create_def_entity_for_existing_clusters(
> ```

Method name suggests something else.
We don't want to create brand new RDEs for every upgrade.
___
*[container_service_extension/installer/configure_cse.py, line 2330 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvjEokAmFWO0DNo4Qc:-MVvjEokAmFWO0DNo4Qd:bb8u09m) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2330)):*
> ```Python
> 
>     schema_svc = def_schema_svc.DefSchemaService(cloudapi_client)
>     server_rde_version: str = \
> ```

rde_in_use (or) runtime_rde to keep it consistent across the code
___
*[container_service_extension/installer/configure_cse.py, line 2356 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvigue2OvpKgzUKpAq:-MVvigufDfGBz7wyGGxz:b-mpgnzl) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2356)):*
> ```Python
>                 org_resource = vcd_utils.get_org(client, org_name=cluster['org_name'])  # noqa: E501
>                 org_id = org_resource.href.split('/')[-1]
>                 entity_svc.create_entity(entity_type_id=target_entity_type.id,
> ```

We don't want to create a new entity altogether when we are upgrading from 1.0 to 2.0. Upgrading an entity from one version to another version is as simple as changing the entity type value and updating the entity compliant with the new schema.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1496 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvjZKH81N50nOq-LRZ:-MVyQVxh-Eq6q2_r-qMx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L1496)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This method can be renamed. Upgrade from one version to another version can encompass several other things other than upgrading RDEs like preparing placement policies, Avi LB etc

How about _upgrade_to_CSE_3_1() (or) _upgrade_to_36()?

_upgrade_to_cse31 may have something about preparing AVI LB or SEGs, please check with Arun.
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 2311 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvj3yNE4h0gqALmOFV:-MVyQXg30zK8Jzx9kTas:b-ryl5r4) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2311)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Method name suggests something else.
We don't want to create brand new RDEs for every upgrade.
</blockquote></details>

renamed method
___
*[container_service_extension/installer/configure_cse.py, line 2330 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvjEokAmFWO0DNo4Qc:-MVyQadI50NmMg8GFoU3:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2330)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

rde_in_use (or) runtime_rde to keep it consistent across the code
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 2356 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvigue2OvpKgzUKpAq:-MVyQbi74fcJGAw328tP:b-dp5fne) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2356)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We don't want to create a new entity altogether when we are upgrading from 1.0 to 2.0. Upgrading an entity from one version to another version is as simple as changing the entity type value and updating the entity compliant with the new schema.
</blockquote></details>

update_entity() does not allow changing entity_type. For now, create new rde and delete old rde of the cluster remains.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 2356 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvigue2OvpKgzUKpAq:-MW0QJ8jBEL_C83M0_88:b2od5qx) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2356)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

update_entity() does not allow changing entity_type. For now, create new rde and delete old rde of the cluster remains.
</blockquote></details>

Please add a TODO.
___
*[container_service_extension/installer/configure_cse.py, line 2349 at r6](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW0P4bY8jnOmacNmvrZ:-MW0P4bY8jnOmacNmvr_:b-xyn6kf) ([raw file](https://github.com/vmware/container-service-extension/blob/be1860f6bdb3ca598aabde6cdaba23fee01e10fc/container_service_extension/installer/configure_cse.py#L2349)):*
> ```Python
>                 # Get the right rde model for getting new defined entity
>                 TargetNativeEntity = get_rde_model(runtime_rde_version)
>                 new_native_entity = TargetNativeEntity.from_native_entity(def_entity.entity)  # noqa: E501
> ```

Casting will fail from 1.0 to 2.0 as we are introducing a required param "apiVersion" to indicate payloadversion.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 226 at r6](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW0PRS_7z14EoPk6_Sb:-MW0PRS_7z14EoPk6_Sc:bv50e8e) ([raw file](https://github.com/vmware/container-service-extension/blob/be1860f6bdb3ca598aabde6cdaba23fee01e10fc/container_service_extension/rde/models/rde_2_0_0.py#L226)):*
> ```Python
> 
>     @classmethod
>     def from_native_entity(cls, native_entity: AbstractNativeEntity):
> ```

This method is basically a converter from 1.0 to 2.0. Can you please move this logic to convert_strategy_1X_2X.py?

This will come in handy to use in our v35 handler as well. Converters do bidirectional conversions, that way we don't need to bunch of methods in these RDE files.

**Review by sahithi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: all files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 14 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 2356 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvigue2OvpKgzUKpAq:-MW0jHxADrnUEwJlnZQp:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2356)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a TODO.
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 2349 at r6](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW0P4bY8jnOmacNmvrZ:-MW0j9BpE9Eatwyysq0j:b-83xtii) ([raw file](https://github.com/vmware/container-service-extension/blob/be1860f6bdb3ca598aabde6cdaba23fee01e10fc/container_service_extension/installer/configure_cse.py#L2349)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Casting will fail from 1.0 to 2.0 as we are introducing a required param "apiVersion" to indicate payloadversion.
</blockquote></details>

added a TODO() for revisit when "apiVersion" is in real use
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 226 at r6](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW0PRS_7z14EoPk6_Sb:-MW0jIkc0t7s18fsVSBd:b6bpqlt) ([raw file](https://github.com/vmware/container-service-extension/blob/be1860f6bdb3ca598aabde6cdaba23fee01e10fc/container_service_extension/rde/models/rde_2_0_0.py#L226)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This method is basically a converter from 1.0 to 2.0. Can you please move this logic to convert_strategy_1X_2X.py?

This will come in handy to use in our v35 handler as well. Converters do bidirectional conversions, that way we don't need to bunch of methods in these RDE files.
</blockquote></details>

As we discussed, currenty these methods are closer to their dataclasses. Each rde class will take care of changing the other RDE version to their own version.

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

I will touch this area again in my upcoming tasks, Since I will make changes to the data we stamp on the extension.

> Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956#-:-MW3SMM33cfFwMajBAiQ:b-o9hn5t)* status: all files reviewed, 15 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1640 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsIo-QEdc6bT0e9kXW:-MW3QSAR-4x01ypLRWvL:b-micyuo) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1640)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

_fix_cluster_metadata()
_fix_cluster_admin_password()

@rocknes : please validate if these two method are required or going away in this upgrade.
</blockquote></details>

these methods are going away
___
*[container_service_extension/installer/configure_cse.py, line 2311 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvj3yNE4h0gqALmOFV:-MW3Rn1X8JFf_D0S9fOE:b-e76epl) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2311)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

renamed method
</blockquote></details>

I think `if_needed` is a bad pattern to follow.

The method should always create the defined entity
The invocation of the method should be guarded by a separate piece of logic which determines if the call should be made or not.

Anytime a method tries to do too many thing, it leads to bad code organization.
___
*[container_service_extension/installer/configure_cse.py, line 1481 at r7](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW3R7W5Aj1C-fZWrdZV:-MW3R7W5Aj1C-fZWrdZW:b-4lrxkf) ([raw file](https://github.com/vmware/container-service-extension/blob/4e4bb83b0ad549164bc82c11ae69c181380b9ffc/container_service_extension/installer/configure_cse.py#L1481)):*
> ```Python
>                 float(target_vcd_api_version) < float(ext_vcd_api_version):
>             raise Exception(upgrade_path_not_valid_msg)
>         if target_vcd_api_version in (vCDApiVersion.VERSION_35.value, vCDApiVersion.VERSION_36.value) and config['service']['legacy_mode']:  # noqa: E501
> ```

Instead of checking the upgrade path the way we are doing it currently, 

We should read the api version stamped on the existing extension. And if it is 33.0 and 34.0 we set the bool
source_cse_running_in_legacy_mode = True

Then we pick the legacy_mode value from config file and set
target_cse_running_in_legacy_mode = True

If source != target and target == legacy then throw exception 

We should try to move away from the api version based checks as much as possible.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/956)* status: 3 of 4 files reviewed, 15 unresolved discussions (waiting on @Anirudh9794, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1640 at r3](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVsIo-QEdc6bT0e9kXW:-MW6SwPv6ypuXzi9FMS_:b-pyycz9) ([raw file](https://github.com/vmware/container-service-extension/blob/d2ae3398338713b1981744ba6e805602900b2bc4/container_service_extension/installer/configure_cse.py#L1640)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

these methods are going away
</blockquote></details>

Done. thx
___
*[container_service_extension/installer/configure_cse.py, line 2311 at r5](https://reviewable.io/reviews/vmware/container-service-extension/956#-MVvj3yNE4h0gqALmOFV:-MW6T5qn-5C7kaRkMFrN:b-py1vw1) ([raw file](https://github.com/vmware/container-service-extension/blob/26cd7ba3a8d8f4bd77feb1dd722da3a9a8269676/container_service_extension/installer/configure_cse.py#L2311)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think `if_needed` is a bad pattern to follow.

The method should always create the defined entity
The invocation of the method should be guarded by a separate piece of logic which determines if the call should be made or not.

Anytime a method tries to do too many thing, it leads to bad code organization.
</blockquote></details>

Made create and upgrade rde as two separate methods.
___
*[container_service_extension/installer/configure_cse.py, line 1481 at r7](https://reviewable.io/reviews/vmware/container-service-extension/956#-MW3R7W5Aj1C-fZWrdZV:-MW6SpFM3xB-hroSqJVz:bjn6k5q) ([raw file](https://github.com/vmware/container-service-extension/blob/4e4bb83b0ad549164bc82c11ae69c181380b9ffc/container_service_extension/installer/configure_cse.py#L1481)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Instead of checking the upgrade path the way we are doing it currently, 

We should read the api version stamped on the existing extension. And if it is 33.0 and 34.0 we set the bool
source_cse_running_in_legacy_mode = True

Then we pick the legacy_mode value from config file and set
target_cse_running_in_legacy_mode = True

If source != target and target == legacy then throw exception 

We should try to move away from the api version based checks as much as possible.
</blockquote></details>

Added checks based on source and targe legacy modes.

**Pull request merged**
