### PR TITLE
[VCDA-1958] update PKS telemetry with source

### PR DESCRIPTION
**Pull request by sakthisunda**
- PKS telemetry changes to include source id and description of the cluster CRUD
- Implemented all PKS detailed table for PKS cluster operations
- Include source and description in addition to pks metrics
- Minor runtime error on LOGGER 
- Updated acl list and update telemetry payload to include source id and description
- PKS ovdc telemetry changes to include source id
- Manually tested all the changes using a working PKS testbed
------------------------------------------------------------------------
image
image
image
image
image
image

image
image
image
image

@Anirudh9794 @rocknes @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/telemetry/payload_generator.py, line 767 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MPCBxfL3VzJydcx31qm:-MPCBxfL3VzJydcx31qn:bo6tupy) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L767)):*
> ```Python
>         PayloadKey.K8S_VERSION: params.get(PayloadKey.K8S_VERSION),
>         PayloadKey.PKS_VERSION: params.get(PayloadKey.PKS_VERSION),
>         PayloadKey.NUMBER_OF_MASTER_NODES: 1,
> ```

Are we hardcoding the number of master nodes to be 1 here?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/telemetry/payload_generator.py, line 767 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MPCBxfL3VzJydcx31qm:-MPCMUJo1t1hMDu6tf-4:bvf2xo7) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L767)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we hardcoding the number of master nodes to be 1 here?
</blockquote></details>

Since no multi master support in the PKS command, it is hard coded for now (same as vCD cluster)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864#-:-MPCOrk34DQzbjpIcBdj:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: Once the outstanding comments are resolved.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864#-:-MQNcGH79jNlnznjOBps:bgdh1cz)* status: all files reviewed, 4 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/def_/cluster_service.py, line 477 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNahRY3q2sTUm87Pmy:-MQNahRZ5wIkJN7twGwl:b-bcy1id) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/def_/cluster_service.py#L477)):*
> ```Python
>             shared_constants.PaginationKey.PAGE_NUMBER: page,
>             shared_constants.PaginationKey.PAGE_SIZE: page_size,
>             telemetry_constants.PayloadKey.SOURCE_DESCRIPTION: thread_local_data.get_thread_local_data(ThreadLocalData.USER_AGENT)  # noqa: E501
> ```

Why is this change in this PR? This doesn't look related to PKS telemetry.
___
*[container_service_extension/request_handlers/pks_cluster_handler.py, line 289 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbwIe1wTY0u-yjarh:-MQNbwIe1wTY0u-yjari:b-p3kqb7) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/request_handlers/pks_cluster_handler.py#L289)):*
> ```Python
>     """
>     cse_params = copy.deepcopy(request_data)
>     cse_params[PayloadKey.K8S_VERSION] = cluster_data.get(PayloadKey.K8S_VERSION)  # noqa: E501
> ```

Does PKS cluster expose K8s version?
___
*[container_service_extension/telemetry/payload_generator.py, line 357 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbUuz0r1_aZekXOua:-MQNbUv-8hKEilsc6trO:bnxe5vx) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L357)):*
> ```Python
>         PayloadKey.PAGE: str(page),
>         PayloadKey.PAGE_SIZE: str(page_size),
>         PayloadKey.SOURCE_ID: SourceMap.get_source_id(cluster_acl_list_info.get(PayloadKey.SOURCE_DESCRIPTION)),  # noqa: E501
> ```

Same concern as above, this doesn't look related to this PR
___
*[container_service_extension/telemetry/payload_generator.py, line 386 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbaxQ90aRvWcn-6w2:-MQNbaxQ90aRvWcn-6w3:bnxe5vx) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L386)):*
> ```Python
>         PayloadKey.ACCESS_SETTING: json.dumps(filtered_acl_info),
>         PayloadKey.SOURCE_ID: SourceMap.get_source_id(cluster_acl_update_info.get(PayloadKey.SOURCE_DESCRIPTION)),  # noqa: E501
>         PayloadKey.SOURCE_DESCRIPTION: cluster_acl_update_info.get(PayloadKey.SOURCE_DESCRIPTION)  # noqa: E501
> ```

Same concern as above, this doesn't look related to this PR

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 477 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNahRY3q2sTUm87Pmy:-MQO55m52c6X54h7hyF9:b-7egc5b) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/def_/cluster_service.py#L477)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Why is this change in this PR? This doesn't look related to PKS telemetry.
</blockquote></details>

No. This is not PKS specific telemetry.
But this small telemetry update due to checkin for "Cluster acl" task happened just after "Adding Source to telemetry task". So is this minor change.
___
*[container_service_extension/request_handlers/pks_cluster_handler.py, line 289 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbwIe1wTY0u-yjarh:-MQO7AFL9eKwXwik0EhZ:b-y3k4gp) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/request_handlers/pks_cluster_handler.py#L289)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Does PKS cluster expose K8s version?
</blockquote></details>

Yes. 
kubo@jumper:~$ pks cluster mycluster---2d090f44-5b19-47ca-ab5a-2ebfec91c6fd

PKS Version:              1.7.0-build.26
Name:                     mycluster---2d090f44-5b19-47ca-ab5a-2ebfec91c6fd
K8s Version:              1.16.7
Plan Name:                Plan 1
UUID:                     85f94948-3b84-483e-b3bf-cb2c52ba6874
Last Action:              UPDATE
Last Action State:        succeeded
Last Action Description:  Instance update completed
Kubernetes Master Host:   mycluster.mydomain.com
Kubernetes Master Port:   8443
Worker Nodes:             2
Kubernetes Master IP(s):  192.168.160.109
___
*[container_service_extension/telemetry/payload_generator.py, line 357 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbUuz0r1_aZekXOua:-MQO7CzoBo2XNz0px1Qc:b-9zz3cj) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L357)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Same concern as above, this doesn't look related to this PR
</blockquote></details>

No. This is not PKS specific telemetry.
But this small telemetry update due to checkin for "Cluster share/unshare CLI" task happened just after "Adding Source to telemetry task". So is this minor change.
___
*[container_service_extension/telemetry/payload_generator.py, line 386 at r1](https://reviewable.io/reviews/vmware/container-service-extension/864#-MQNbaxQ90aRvWcn-6w2:-MQO7Gip6CR4R1oDpuif:b-9zz3cj) ([raw file](https://github.com/vmware/container-service-extension/blob/abb5d3396b78ad3d7a8856de0377d222e9f35945/container_service_extension/telemetry/payload_generator.py#L386)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Same concern as above, this doesn't look related to this PR
</blockquote></details>

No. This is not PKS specific telemetry.
But this small telemetry update due to checkin for "Cluster share/unshare CLI" task happened just after "Adding Source to telemetry task". So is this minor change.

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
