### PR TITLE
edit apply help string

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Optional) Names of reviewers using @ sign + name
@sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1113)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1113)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/client/cluster_commands.py, line 516 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1113#-MeWlQN-DcLaVcA53gTr:-MeWlQN-DcLaVcA53gTs:b-olz70) ([raw file](https://github.com/vmware/container-service-extension/blob/37f089904088b84b52febddfaec4b6a076def181/container_service_extension/client/cluster_commands.py#L516)):*
> ```Python
>                        short_help='apply a configuration to a cluster resource'
>                                   ' by filename. The resource will be created '
>                                   'if it does not exist. This cannot be used '
> ```

Instead of specifying what cannot be done, we can state what operations can be achieved by the apply command.
How about the below?
"The command can be used to create the cluster, scale-up/down worker count, scale-up NFS nodes, upgrade the cluster to a new K8s version. Note that for api_version <36.0, upgrades are not supported with this command).

Can these statements come in a separate line (or) at least put these two statements inside brackets?

**Review by sakthisunda — APPROVED** [review]
:lgtm: ( after any outstanding review comments)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1113#-:-MeX2FFt9GpisXxmOe_0:bt6devm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Comment by ltimothy7** [comment]
___
*[container_service_extension/client/cluster_commands.py, line 516 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1113#-MeWlQN-DcLaVcA53gTr:-MeX58H_10r_Nq2YuRl0:b-vcybpd) ([raw file](https://github.com/vmware/container-service-extension/blob/37f089904088b84b52febddfaec4b6a076def181/container_service_extension/client/cluster_commands.py#L516)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Instead of specifying what cannot be done, we can state what operations can be achieved by the apply command.
How about the below?
"The command can be used to create the cluster, scale-up/down worker count, scale-up NFS nodes, upgrade the cluster to a new K8s version. Note that for api_version <36.0, upgrades are not supported with this command).

Can these statements come in a separate line (or) at least put these two statements inside brackets?
</blockquote></details>

Done. Thanks Sahithi; these lines can't go on new lines, so I put them in parenthesis.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1113#-:-MeXFE768AMAKoQYHzjV:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Pull request merged**
