### PR TITLE
[VCDA-3567] include list for cluster list

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1362)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
Wondering, why is the existing exclude capvcd type is removed from the list? Is that because <b>vcd cluster list</b> supports capvcd cluster also as part of the list? 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1362#-:-N4mTESJ0N9eZszBBN01:bmudp1m)* status: 0 of 3 files reviewed, all discussions resolved

**Review by sahithi — APPROVED** [review]
Please test this thoroughly and can you document the current behavior of CLI somewhere before we all forget?
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1362#-:-N5m4dHJ5Op91IibJu8X:bmvev03)* status: 0 of 3 files reviewed, all discussions resolved

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1362)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by ltimothy7 — COMMENTED** [review]
Thanks @sahithi. I have been testing this, and I have updated the developer guide.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1362#-:-N5mfpy-BfzhpX9Jgmey:b-9oh2ej)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
