### PR TITLE
[VCDA-3104] Update-cpi-csi-version

### PR DESCRIPTION
**Pull request by sakthisunda**
- update CSE to use latest CPI and CSI
- Testing completed

image

image

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1266)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1266)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1266#-MqQKz6t7fRs3Rzek3yt:-MqQKz6t7fRs3Rzek3yu:b-md1q2v) ([raw file](https://github.com/vmware/container-service-extension/blob/6dc1566ee5c9cc43c9c065612c3540e4cf7293ee/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L76)):*
> ```Python
> CNI_NAME = "antrea"
> ANTREA_CNI_VERSION = 'v0.11.3'
> CPI_VERSION = '1.0.x'
> ```

I suggest parameterizing in CSE config.yaml
This will prevent providing CSE patches for every CPI, CSI patch that get released.

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1266#-MqQKz6t7fRs3Rzek3yt:-MqQM8oO9N8ujX6VpoL_:b4zg7cu) ([raw file](https://github.com/vmware/container-service-extension/blob/6dc1566ee5c9cc43c9c065612c3540e4cf7293ee/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L76)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest parameterizing in CSE config.yaml
This will prevent providing CSE patches for every CPI, CSI patch that get released.
</blockquote></details>

I agree to this. In one of the previous meetings it was vetoed by @rocknes . We should revisit it.

However this needs to be either part of cluster spec rather than CSE config since we cannot upgrade all previously created clusters. The third option is a mix. Let us discuss about this.

**Comment by arunmk** [comment]
:lgtm:

**Review by arunmk — APPROVED** [review]
looks good to me, thanks

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1266#-:-MqQMizM3KzVzAHCe4DE:br6e0dk)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

**Comment by Anirudh9794** [comment]
:lgtm:

**Pull request merged**
