### PR TITLE
[VCDA-2703, VCDA-2699] Fix RDE creation/update during CSE upgrade

### PR DESCRIPTION
**Pull request by rocknes**
Legacy native K8s clusters are converted to RDE 1.0.0 or RDE 2.0.0 (depending on the VCD) during CSE upgrade. However during this conversion, the `StorageProfile` field in status section is not updated properly. This PR fixes it.

Additionally, this PR also 
1. improves the error message when RDE validation fails during various CSE workflows viz. cluster apply.
2. Refreshes the user context after native entitlement rights are added to roles explicitly by CSE or implicitly by VCD (e.g. built in roles)

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 415 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWpMrbD4yC1HS74AuJ:-MeWpMrbD4yC1HS74AuK:b-ifqag) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/models/rde_2_0_0.py#L415)):*
> ```Python
>                     name=item['name'],
>                     ip=item['ipAddress'],
>                     storage_profile=cluster['storage_profile_name']
> ```

I think rde_1_0_0.py will also require this change.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 415 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWpMrbD4yC1HS74AuJ:-MeWpr3zB3_rqKZ7ujBA:b-yp4db5) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/models/rde_2_0_0.py#L415)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think rde_1_0_0.py will also require this change.
</blockquote></details>

No, 1.0.0 doesn't have storage profile field in status worker, control plane or nfs

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114#-:-MeWyuPLEilRFD-yTWQy:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 132 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWyFPE0EgYZEXjMxNc:-MeWyFPF0IpzhYlg6xpf:b-hqnijp) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L132)):*
> ```Python
>     # Raise exception if fields which cannot be changed are updated
>     if len(keys_with_invalid_value.keys()) > 0:
>         err_msg = "Invalid input values found in fields ["
> ```

Does 'Immutable properties changed' sound better?
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 141 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWwfHY054qQMp1Xres:-MeWwfHY054qQMp1Xret:b8fabvo) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L141)):*
> ```Python
> 
>     is_resize_operation = False
>     if FlattenedClusterSpecKey2X.WORKERS_COUNT.value in diff_fields.keys() or \
> ```

diff_fields.keys() can be stored in a variable instead of repeating invocations

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 141 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWwfHY054qQMp1Xres:-MeWzC1v2ekdV5LNJ_4y:b-s4yy6h) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L141)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

diff_fields.keys() can be stored in a variable instead of repeating invocations
</blockquote></details>

Actually now I think of it .. we don' really need the .keys().

when a `in` clause is used on a dict, the keys() call is made implicitly

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 141 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWwfHY054qQMp1Xres:-MeX0rL-8I4vQGSh1JLT:bt7f1l2) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L141)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Actually now I think of it .. we don' really need the .keys().

when a `in` clause is used on a dict, the keys() call is made implicitly
</blockquote></details>

I read that  in dict vs in dict.keys()  =>  O(1) vs O(n)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114#-:-MeXEqIpB-W4zRBAVPvo:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 132 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWyFPE0EgYZEXjMxNc:-MeYr9Eo3gQtTWrsMZVK:b4qk1cu) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L132)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Does 'Immutable properties changed' sound better?
</blockquote></details>

Kinda awkward imo :|
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 141 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWwfHY054qQMp1Xres:-MeYrI3W5Y0rd1zoa480:b562lhh) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L141)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

I read that  in dict vs in dict.keys()  =>  O(1) vs O(n) 
</blockquote></details>

Thanks Sakthi :)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1114#-:-MebEiVmDbtv09JQMQV_:bg7igkv)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 132 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1114#-MeWyFPE0EgYZEXjMxNc:-MebDnlT5ZlZ2hjQL7Bv:b7buirw) ([raw file](https://github.com/vmware/container-service-extension/blob/94f23a28005a7e01c63ad7cc889850bbd99c8555/container_service_extension/rde/validators/validator_rde_2_x.py#L132)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Kinda awkward imo :|
</blockquote></details>

The term "immutable" can send the right message to the users that they touched something they are not supposed to.

**Pull request merged**
