### PR TITLE
[VCDA-3191, VCDA-3204] Remove option to install templates during CSE install/upgrade

### PR DESCRIPTION
**Pull request by rocknes**
Removed the option to install K8s templates during CSE install/upgrade.
Associated telemetry payload was modified too.

Additionally, updated the system tests to accommodate the change in behavior of `cse install`.

Testing Done:
Ran `cse install` and `cse upgrade` and made sure that the option to skip templates is gone, and templates are not installed during the command execution anymore.

Pending: Run CToT.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1274)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @arunmk)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @arunmk)

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794 and @arunmk)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arunmk)

**Pull request merged**
