### PR TITLE
[VCDA-1883] Improve client wire logging

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Logging request/response headers in client wire logging, even if there are errors.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

I reviewed the logs during errors and without errors. The response/request headers and other fields were logged.

- (Optional) Names of reviewers using @ sign + name
@sakthisunda @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/802)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/response_processor.py, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/802#-MKBEn5mDlA_-RAVbMp0:-MKBEn5n3B1FO_45QZF1:b1vgg64) ([raw file](https://github.com/vmware/container-service-extension/blob/6375a99bb7f89cab475440ab916cae8affaf262c/container_service_extension/client/response_processor.py#L51)):*
> ```Python
>     wire_logger.debug(f"Response headers: {response.headers}")
> 
>     response_content = deserialize_response_content(response)
> ```

possible null pointer exception here if `response` is `None` because `deserialize_response_content` is calling `response.content`.

**Comment by ltimothy7** [comment]
___
*[container_service_extension/client/response_processor.py, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/802#-MKBEn5mDlA_-RAVbMp0:-MKBba0-DqRYhFYSoLrV:bmybj7f) ([raw file](https://github.com/vmware/container-service-extension/blob/6375a99bb7f89cab475440ab916cae8affaf262c/container_service_extension/client/response_processor.py#L51)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

possible null pointer exception here if `response` is `None` because `deserialize_response_content` is calling `response.content`.
</blockquote></details>

This function seems to assume that `<response>` is not `<None>` because it is assumed that the `<request>` field can always be accessed prior to this PR. Do you think there should be a CseResponseError raised then?

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/802)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/response_processor.py, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/802#-MKBEn5mDlA_-RAVbMp0:-MKLZUisDFwMVw3w1Xjs:boj7lol) ([raw file](https://github.com/vmware/container-service-extension/blob/6375a99bb7f89cab475440ab916cae8affaf262c/container_service_extension/client/response_processor.py#L51)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

This function seems to assume that `<response>` is not `<None>` because it is assumed that the `<request>` field can always be accessed prior to this PR. Do you think there should be a CseResponseError raised then?
</blockquote></details>

Yes. you are right. I think it is okay not to check for None because at least the request object and the headers will be present.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/802#-:-MKMgyaW7CYPp24oLsji:bg7igkv)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @ltimothy7, and @sakthisunda)

**Pull request merged**
