### PR TITLE
Fix cpu,memory size defaults to Tkgm node size; Fix vm update issues

### PR DESCRIPTION
**Pull request by sakthisunda**
- Fix cpu,memory size defaults to Tkgm node size; 
- Fix vm update to change cpu, memory
- VCDA-3565,VCDA-3569
- Tested with defaults 
- Tested with memory, cpu in cluster specifction
- Tested with sizingClass in cluster specification

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 886 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Pz1om82ymaK4f3iYF:-N-Pz1om82ymaK4f3iYG:b-kz91mw) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/common/constants/server_constants.py#L886)):*
> ```Python
>         return self._memory
> 
>     SMALL = (2, 4096)
> ```

Nit: in general it is good to do `32*1024` etc so that one does not make mistakes in computation. (No need to change this)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: all files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2435 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Q5tq-8hE_ddrhxzPf:-N-Q5tq-8hE_ddrhxzPg:b-8u91n4) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2435)):*
> ```Python
>                 vapp.reload()
> 
>             if not (cpu_count and cpu_count > 0) and not sizing_class_name:
> ```

Can we please move this block to the else section of the other cpu based if check check ?

if cpu_count and cpu_count > 0:
 # do the old stuff
elif not sizing_class_name:
 # do the update to tkgm default size
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2443 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Q6DPd0DwjMUYDlKL1:-N-Q6DPd0DwjMUYDlKL2:bbrmmql) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2443)):*
> ```Python
>                 vapp.reload()
> 
>             if not (memory_mb and memory_mb > 0) and not sizing_class_name:
> ```

same comment as above, can you please move it to the e4lse section of the if memory check?

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: all files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2435 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Q5tq-8hE_ddrhxzPf:-N-Q7HdPE6_TtwngTt45:bhw5012) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2435)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can we please move this block to the else section of the other cpu based if check check ?

if cpu_count and cpu_count > 0:
 # do the old stuff
elif not sizing_class_name:
 # do the update to tkgm default size
</blockquote></details>

github messed up my comment, updated code

```
task = None
if cpu_count and cpu_count > 0:
	task = vm.modify_cpu(cpu_count)
elif not sizing_class_name:
	task = vm.modify_cpu(TkgmNodeSizing.SMALL.cpu)
if task:
	sysadmin_client.get_task_monitor().wait_for_status(task, callback=wait_for_cpu_update)
	vm.reload()
	vapp.reload()
```



_Code quote:_
```Python
vm.modify_cpu(TkgmNodeSizing.SMALL.cpu)
```

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: all files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @arunmk, @ltimothy7, and @rocknes)

___
*[container_service_extension/common/constants/server_constants.py, line 886 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Pz1om82ymaK4f3iYF:-N-QITND99Gqiyh7kBwn:b-ajbx49) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/common/constants/server_constants.py#L886)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: in general it is good to do `32*1024` etc so that one does not make mistakes in computation. (No need to change this)
</blockquote></details>

␆.Thx
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2435 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Q5tq-8hE_ddrhxzPf:-N-QJ66_BFnmGdhWYF8S:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2435)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

github messed up my comment, updated code

```
task = None
if cpu_count and cpu_count > 0:
	task = vm.modify_cpu(cpu_count)
elif not sizing_class_name:
	task = vm.modify_cpu(TkgmNodeSizing.SMALL.cpu)
if task:
	sysadmin_client.get_task_monitor().wait_for_status(task, callback=wait_for_cpu_update)
	vm.reload()
	vapp.reload()
```
</blockquote></details>

Done
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2443 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1344#-N-Q6DPd0DwjMUYDlKL1:-N-QIqgrDbpLqA--TBmB:b-el1byb) ([raw file](https://github.com/vmware/container-service-extension/blob/ea791ebae79c0de7d7bb9b99173fc34e3f63055a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2443)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

same comment as above, can you please move it to the e4lse section of the if memory check?
</blockquote></details>

Done.thx

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1344#-:-N-QfuNj1tmKMZ3Ug4_w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

**Pull request merged**
