### PR TITLE
docs added 1.20 template announcement

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1022)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1022#-:-MZPh3tIB2QBfp9ERp1y:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1022)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md, line 19 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1022#-MZPy5tR1UdFodUkd6qN:-MZPy5tTCPf9QrookqzH:b-mcx9hg) ([raw file](https://github.com/vmware/container-service-extension/blob/b5f5295b904cc679d16ad4a80e0a1df7b1bc29bc/docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md#L19)):*
> ```Markdown
> | ubuntu-16.04_k8-1.19_weave-2.6.5     | 1        | Ubuntu-16.04      | 1.19.3      | 2.6.5     | Docker-ce 19.03.12      |
> | ubuntu-16.04_k8-1.18_weave-2.6.5     | 1        | Ubuntu-16.04      | 1.18.6      | 2.6.5     | Docker-ce 19.03.12      |
> | ubuntu-16.04_k8-1.17_weave-2.6.0     | 2        | Ubuntu 16.04      | 1.17.9      | 2.6.0     | Docker-ce 19.03.5       |
> ```

Remove the v1.15 line, strike out the v1.16 line and mark 1.17 as deprecated. Please make the appropriate change in the templates.yaml file too.

1.21 is current which will get support for 1 year.
1.17 and older has no support from Kubernetes community any longer.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1022)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

___
*[docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md, line 19 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1022#-MZPy5tR1UdFodUkd6qN:-MZQTyvy6bHNnLxIgKRd:bc9wwzt) ([raw file](https://github.com/vmware/container-service-extension/blob/b5f5295b904cc679d16ad4a80e0a1df7b1bc29bc/docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md#L19)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Remove the v1.15 line, strike out the v1.16 line and mark 1.17 as deprecated. Please make the appropriate change in the templates.yaml file too.

1.21 is current which will get support for 1 year.
1.17 and older has no support from Kubernetes community any longer.
</blockquote></details>

Done. Thanks Aritra

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1022)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Pull request merged**
