### PR TITLE
[VCDA-4174] getting control plane ip through vapp without sleep

### PR DESCRIPTION
**Pull request by ltimothy7**
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1389)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1389)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[`container_service_extension/def_/cluster_service.py` line 2136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1389#-N8ejgBSDzK-FDyjAb56:-N8ejgBSDzK-FDyjAb57:bxxjbyk) ([raw file](https://github.com/vmware/container-service-extension/blob/5cc336c3b07f98f1860640e04d81e23b8d396453/container_service_extension/def_/cluster_service.py#L2136)):*
> ```Python
>                  f"{vapp.get_resource().get('name')}")
>     node_names = _get_node_names(vapp, NodeType.CONTROL_PLANE)
>     control_plane_ip = vapp.get_primary_ip(node_names[0])
> ```

We have similar logic in cse_3_1_updates as well. (cluster_service_2_x.py and cluster_service_1_x.py)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1389)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[`container_service_extension/def_/cluster_service.py` line 2136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1389#-N8ejgBSDzK-FDyjAb56:-N8ek5d07AiGHDh2RkV8:bp313i) ([raw file](https://github.com/vmware/container-service-extension/blob/5cc336c3b07f98f1860640e04d81e23b8d396453/container_service_extension/def_/cluster_service.py#L2136)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

We have similar logic in cse_3_1_updates as well. (cluster_service_2_x.py and cluster_service_1_x.py)
</blockquote></details>

I meant, please suggest if they also should be also replaced.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1389#-:-N8empokAjaH8nJ-7X6G:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Comment by ltimothy7** [comment]
*[`container_service_extension/def_/cluster_service.py` line 2136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1389#-N8ejgBSDzK-FDyjAb56:-N8fmah--bpQiw604xOg:bvgotgb) ([raw file](https://github.com/vmware/container-service-extension/blob/5cc336c3b07f98f1860640e04d81e23b8d396453/container_service_extension/def_/cluster_service.py#L2136)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

I meant, please suggest if they also should be also replaced.
</blockquote></details>

Yes, I agree with you that these should be replaced. I will add it in tech debt

**Comment by ltimothy7** [comment]
*[`container_service_extension/def_/cluster_service.py` line 2136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1389#-N8ejgBSDzK-FDyjAb56:-N8fnNBj15tB1PqA0Wc0:bl752ta) ([raw file](https://github.com/vmware/container-service-extension/blob/5cc336c3b07f98f1860640e04d81e23b8d396453/container_service_extension/def_/cluster_service.py#L2136)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Yes, I agree with you that these should be replaced. I will add it in tech debt
</blockquote></details>

I added the following task for CSE (not tech debt):

https://jira.eng.vmware.com/browse/VCDA-4177

**Comment by ltimothy7** [comment]
*[`container_service_extension/def_/cluster_service.py` line 2136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1389#-N8ejgBSDzK-FDyjAb56:-N8fnWW5BKQUCV6lqVHh:b6su4j0) ([raw file](https://github.com/vmware/container-service-extension/blob/5cc336c3b07f98f1860640e04d81e23b8d396453/container_service_extension/def_/cluster_service.py#L2136)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I added the following task for CSE (not tech debt):

https://jira.eng.vmware.com/browse/VCDA-4177
</blockquote></details>

Note: the combination of using ubuntu 20 + VCD 10.3.3.2 may be the issue

**Pull request merged**
