### PR TITLE
[VCDA-2283] CLI changes to harden against RDE changes

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Constructing filters in entity_service.py: filters created in entity_service module supports only snake case. Make changes to change the case of the filter string based on RDE version used.
* Sample generator: Generate sample cluster-apply specification based on server-rde version in use.
* Skip converting the input yaml into NativeEntity object before calling create / update endpoints. Only responses sent from the CSE server should be converted into model objects.
* Make sure responses from cluster list populate all the required fields, even if RDE version changes.

@sahithi @sakthisunda @rocknes @ltimothy7 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster_native.py, line 293 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6QZyPA4gOZkhD4GOZ:-MY6QZyPA4gOZkhD4GO_:b-k0ttfa) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/de_cluster_native.py#L293)):*
> ```Python
>             def_entity = entity_svc.get_entity(cluster_id)
>         else:
>             def_entity = entity_svc.get_native_rde_by_name_and_rde_version(
> ```

Will this call raise an exception if the entity does not exist?
___
*[container_service_extension/client/sample_generator.py, line 96 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6OCRSA3pDXJ0dT3cA:-MY6OCRSA3pDXJ0dT3cB:b-oeja8x) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/sample_generator.py#L96)):*
> ```Python
> 
> 
> def _get_sample_cluster_configuration_by_k8_runtime(k8_runtime, server_rde_in_use):  # noqa: E501
> ```

What will be the output when CSE server is not reachable?
___
*[container_service_extension/rde/constants.py, line 151 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6SKRbDCTUz3Z-qF1s:-MY6SKRbDCTUz3Z-qF1t:b79nhyx) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/rde/constants.py#L151)):*
> ```Python
> 
> 
> class ClusterEntityFilterKeyV1(Enum):
> ```

Naming is a bit confusing. It feels like ClusterEntityFilterKeyV1 is recent one than ClusterEntityFilterKey.
How about ClusterEntityFilterKey1X and ClusterEntityFilterKey2X?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/client/de_cluster_native.py, line 293 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6QZyPA4gOZkhD4GOZ:-MY70kUa2h2Th3teYlAD:bv1laup) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/de_cluster_native.py#L293)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Will this call raise an exception if the entity does not exist?
</blockquote></details>

No, if entity doesn't exist, def_entity will be None
___
*[container_service_extension/client/sample_generator.py, line 96 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6OCRSA3pDXJ0dT3cA:-MY71XzS9_BcqrG45eO-:b-qkvkj3) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/sample_generator.py#L96)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What will be the output when CSE server is not reachable?
</blockquote></details>

apply command (which is also used to generate the sample apply-config) will not be shown to the user if CSE server is not reachable.

However, there were other parts of the code which are exposed even when CSE server is not running. Added a function to get the  highest entity type version registered with VCD.
___
*[container_service_extension/rde/constants.py, line 151 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6SKRbDCTUz3Z-qF1s:-MY7RyaW4dZ847tFfbAT:bak5o4m) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/rde/constants.py#L151)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Naming is a bit confusing. It feels like ClusterEntityFilterKeyV1 is recent one than ClusterEntityFilterKey.
How about ClusterEntityFilterKey1X and ClusterEntityFilterKey2X?
</blockquote></details>

Done. Also separated out NativeEntity filter keys from Defined entity filter keys. Please let me know if this is okay.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996#-:-MY7cgCK8osff7gEe84l:bg7igkv)* status: 5 of 12 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/schema_service.py, line 200 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7ccTjD9zZLM9gvbli:-MY7ccTjD9zZLM9gvblj:b-w20ly5) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L200)):*
> ```Python
> 
>     @handle_schema_service_exception
>     def get_latest_registered_schema_version(self) -> str:
> ```

where are you using this method?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/schema_service.py, line 200 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7ccTjD9zZLM9gvbli:-MY7dBPN0y_3Qs5mE8SP:b-yybtzt) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L200)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

where are you using this method?
</blockquote></details>

in de_cluster and de_cluster_native

**Review by sakthisunda — APPROVED** [review]
> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/client/de_cluster_native.py, line 293 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6QZyPA4gOZkhD4GOZ:-MY7mB361z-mwALZgWWi:bs573a6) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/de_cluster_native.py#L293)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

No, if entity doesn't exist, def_entity will be None
</blockquote></details>

In upgrader code,  I noticed entity_svc.get_entity(cluster_id) raises exception if entity not found.
___
*[container_service_extension/rde/schema_service.py, line 206 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7ou3g75h-i3Hq049w:-MY7ou3g75h-i3Hq049x:bg62yr) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L206)):*
> ```
> max_entity_type_version = None
> ```
max_entity_type_version = semantic_version.Version('0.0.0')
___
*[container_service_extension/rde/schema_service.py, line 211 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7p09H2sy4862zbpSG:-MY7p09H2sy4862zbpSH:bd8m6mu) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L211)):*
> ```Python
>             if not max_entity_type_version or \
>                     semantic_version.Version(max_entity_type_version) < entity_type_version:  # noqa: E501
>                 max_entity_type_version = str(entity_type_version)
> ```

if max_entity_type_version < entity_type_version:
     max_entity_type_version = entity_type_version

nit: may be useful to avoid multiple conversions and if not check every time.

**Review by sakthisunda — COMMENTED** [review]
:lgtm: (minor comments)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996#-:-MY7png3D3kd3bGKvmbG:bk4hhe9)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/996)* status: 9 of 12 files reviewed, 6 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/client/de_cluster_native.py, line 293 at r1](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY6QZyPA4gOZkhD4GOZ:-MYB9hFu-Bzk8V52lT_F:b-n4czvk) ([raw file](https://github.com/vmware/container-service-extension/blob/c6d7950cdade879da3b2ef21175160198e764092/container_service_extension/client/de_cluster_native.py#L293)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

In upgrader code,  I noticed entity_svc.get_entity(cluster_id) raises exception if entity not found.
</blockquote></details>

get_native_rde_by_name_and_rde_version makes use of cluster list and not get entity by id. List clusters return an empty list if there are no entities.
___
*[container_service_extension/rde/schema_service.py, line 206 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7ou3g75h-i3Hq049w:-MYBNjiy1r1RWNnn4UFb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L206)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> max_entity_type_version = None
> ```
max_entity_type_version = semantic_version.Version('0.0.0')
</blockquote></details>

Done.
___
*[container_service_extension/rde/schema_service.py, line 211 at r2](https://reviewable.io/reviews/vmware/container-service-extension/996#-MY7p09H2sy4862zbpSG:-MYBNk32B8NzHvzqB8ew:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/49f3db1fb074c974b0ca1c5d4610e7713ea87370/container_service_extension/rde/schema_service.py#L211)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

if max_entity_type_version < entity_type_version:
     max_entity_type_version = entity_type_version

nit: may be useful to avoid multiple conversions and if not check every time.
</blockquote></details>

Done.

**Pull request merged**
