### PR TITLE
Trimmed down schema of CAPVCD

### PR DESCRIPTION
**Pull request by sahithi**
- Trimmed down the schema to hold the just the minimum required properties for the first cut version (Jan'22 release)
- Made everything optional (removed the required section).
- Added two sections ClusterApiStatus and NodeStatus in the Status section.
-

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1257)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1257#-:-Mo_YFB92LXcmsqtCVD_:bg7igkv)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1257)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[cse_def_schema/capvcd_schema_1_0_0.json, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1257#-Mo_uGyhEaUzLM2WpXtz:-Mo_uGyhEaUzLM2WpXu-:b-16a8oc) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa17b076a775a0995a4c12eb9dd52a029a531d5/cse_def_schema/capvcd_schema_1_0_0.json#L45)):*
> ```JSON
>                                 "count":{
>                                     "type":"integer",
>                                     "description":"Single control plane node is supported; More than single control plane node is not yet supported.",
> ```

Not valid anymore?

**Comment by arunmk** [comment]
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1257#-Mo_ugAL-k3OxIjMW8UJ:-Mo_ugAMDD9hQaYl8oG4:bg7igkv) (no related file):*
:lgtm: 

---

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1257)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[cse_def_schema/capvcd_schema_1_0_0.json, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1257#-Mo_uGyhEaUzLM2WpXtz:-Mo_uuOo7R3gWd7Ee7Qt:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6fa17b076a775a0995a4c12eb9dd52a029a531d5/cse_def_schema/capvcd_schema_1_0_0.json#L45)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Not valid anymore?
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1257#-Mo_ugAL-k3OxIjMW8UJ:-Moa2gTm4OEGSdNM1hYt:bg7igkv) (no related file):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

:lgtm: 

---

**Pull request merged**
