### PR TITLE
[VCDA-1878] Add native def rights for CSE non sys-admin role during C…

### PR DESCRIPTION
**Pull request by ChintanShahVMware**
…SE install/upgrade

During CSE install/upgrade proceudre, native defined entity gets
created in VCD. VCD automatically creates a rights-bundle associated
with this defined entity.
As the rights bundle gets created dynamically, the user who performs CSE
install/upgrade procedure may/may-not have this rights bundle with him,
depending upon if the user role is "SharingRole" or not.
In case its not, CSE install/upgrade procesure need to add these rights to
user's role. This commit takes care of these steps.

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ChintanShahVMware)

___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCe0vf4kS5uCw7ieuo:-MKCe0vf4kS5uCw7ieup:b6ehiom) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
> ```Python
> 
> 
> def _update_user_role_with_native_def_rights(defined_entity_right_bundle_name,
> ```

Hi Chintan, thank you for the helpful comments; it made it easier to go through the PR. I have a few questions:

For the system administrator, do they receive these rights automatically without `<_update_user_role_with_native_def_rights>`?

If the system administrator doesn't need this function to have the native def rights, is this function idempotent if the user is the system administrator? 
--If this is idempotent, then it seems like this function should only be executed if the user is not the system administrator.
___
*[container_service_extension/configure_cse.py, line 733 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCdtRK2fQG0mEHlNTS:-MKCdtRK2fQG0mEHlNTT:b-u1zljp) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L733)):*
> ```Python
>     # and login the user again.
> 
>     return
> ```

I don't think this return is needed.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 4 unresolved discussions (waiting on @ChintanShahVMware and @ltimothy7)

___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCe0vf4kS5uCw7ieuo:-MKIHSqu5pvmX0_diBOs:b-5esvcr) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Hi Chintan, thank you for the helpful comments; it made it easier to go through the PR. I have a few questions:

For the system administrator, do they receive these rights automatically without `<_update_user_role_with_native_def_rights>`?

If the system administrator doesn't need this function to have the native def rights, is this function idempotent if the user is the system administrator? 
--If this is idempotent, then it seems like this function should only be executed if the user is not the system administrator.

</blockquote></details>

+1 to Tim's comment. 
___
*[container_service_extension/configure_cse.py, line 688 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIHfDl1YujhiadjGMp:-MKIHfDl1YujhiadjGMq:bb3glwk) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L688)):*
> ```Python
>     # Currently this function should only be called during CSE install/upgrade
>     # procedure; these operations are only supported by sysadmin user.
>     vcd_utils.raise_error_if_not_sysadmin(client)
> ```

This check needs to be removed. The whole point of this task is to add rights on the fly to non-sysadmin roles.
___
*[container_service_extension/configure_cse.py, line 730 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIIZphBV8lrG-4MGbL:-MKIIZphBV8lrG-4MGbM:bmsyqqj) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L730)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     # VCD has a concept called: SecurityContext, which determines rights owned
>     # by a user. This is determined only once during the lifetime of an HTTP
>     # session. In order to make above rights effective, we will need to logout
>     # and login the user again.
> ```
</details>

It means upgrade is not a one-step process? Can we add a call to refresh the session at the end of this method?

**Review by rocknes — CHANGES_REQUESTED** [review]
flake8 validation is failing for this PR. Please fix the flake8 errors.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803#-:-MKP9brD24iGljMWmlKm:b7ruv8a)* status: all files reviewed, 8 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7YDlCeG1YWNVH87a:-MKP7YDlCeG1YWNVH87b:badfuic) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
> ```Python
> 
> 
> def _update_user_role_with_native_def_rights(defined_entity_right_bundle_name,
> ```

If we know that we are adding native right bundle, does it make sense to take the native defined entity right bundle name as param? The name can be hard coded inside this method right?
___
*[container_service_extension/configure_cse.py, line 688 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIHfDl1YujhiadjGMp:-MKP6Kz5428KqTZVtFt6:b-psi0k) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L688)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This check needs to be removed. The whole point of this task is to add rights on the fly to non-sysadmin roles.
</blockquote></details>

Funnily this method just checks if the user belongs to System org or not. Which I think is still a requirement. Maybe rename it properly?
___
*[container_service_extension/configure_cse.py, line 701 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7oa-0OmmPEBFP1w3:-MKP7oa0Cr5v46J1zKsQ:byoc2ng) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L701)):*
> ```Python
> 
>     # Given that this user is sysadmin, Org must be System
>     # If its not, we should receive an exception during one of the below
> ```

Exceptions should not leak out of this method. At least not the ones we can predict.
___
*[container_service_extension/configure_cse.py, line 730 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIIZphBV8lrG-4MGbL:-MKP8FPSDXNvnnr9E5tr:bmohbk9) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L730)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>     # VCD has a concept called: SecurityContext, which determines rights owned
>     # by a user. This is determined only once during the lifetime of an HTTP
>     # session. In order to make above rights effective, we will need to logout
>     # and login the user again.
> ```
It means upgrade is not a one-step process? Can we add a call to refresh the session at the end of this method?
</blockquote></details>

I agree with Sahithi, let's just refresh the client before returning. client.py in pyvcloud has methods like rehydrate_from_token, one of them should do the trick.
___
*[container_service_extension/right_bundle_manager.py, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP8ckf5OvWWcbIVDsm:-MKP8ckf5OvWWcbIVDsn:b-8q37k6) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/right_bundle_manager.py#L59)):*
> ```Python
> 
>     def get_rights_for_right_bundle(self, right_bundle_name):
>         right_bundle_info = self.get_right_bundle_by_name(right_bundle_name)
> ```

Please add doc string explaining the return type and structure of the returned json
___
*[container_service_extension/def_/utils.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP9I_s43LOzZ50x5yk:-MKP9I_s43LOzZ50x5yl:bcj0il7) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/def_/utils.py#L22)):*
> ```Python
> DEF_NATIVE_ENTITY_TYPE_VERSION = '1.0.0'
> DEF_NATIVE_ENTITY_TYPE_NAME = 'nativeClusterEntityType'
> DEF_NATIVE_ENTITY_TYPE_RIGHT_BUNDLE = 'cse:nativeCluster Entitlement'
> ```

Seems like a duplicate of right_bundle_manager.CSE_NATIVE_RIGHT_BUNDLE_NAME

Also let's not add any more constants in utils file! We should actively move these constants to server_constant /shared_constants

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCe0vf4kS5uCw7ieuo:-MKbB_378RdQLX1MPq6Z:b-qzw1r) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1 to Tim's comment. 
</blockquote></details>

Hi @ltimothy7 @sahithi 

Yes. The administrator is a user created with a SharingRole "Syatem Administrator". The Role is read-only from provider/user perspective, and it automatically gets all the dynamically created rights (VCD adds all dynamically created rights to Read-only roles).

Yes, when the admin user executed CSE install/update operation, it will be no-op from VCD perspective.
Meaning, CSE will still call the same API to assign the rights, but given that VCD has already published the same rights to system administrator role, this operation is no-op. P.S. VCD will not return any exceptions per say in such cases.

About executing this function only if user is non-system-administrator; 
I tried to check to this. Basically I can add a check at start of the method, checking if the user-name is "administrator" or its role is "System Administrator". 
Couldn't find an existing method to do so.
What it basically means is, in CSE code-base, a certain role/user-name is hard-coded; and given that the entire concept of "administrator" user is going away, I thought doing so would require certain cleanup later; and given that this method is essentially a no-op for "administrator" user, keeping this call is not big deal.

Let me know if you disagree or if there is a better way.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7YDlCeG1YWNVH87a:-MKbDRoGEdS7ndx2R2Zb:bp6etc) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If we know that we are adding native right bundle, does it make sense to take the native defined entity right bundle name as param? The name can be hard coded inside this method right?
</blockquote></details>

Hmm,  i wanted to keep this as a generic utility function like _register_def_schema.
Lets say in future we come up with another def_schema to register, same function can be called, and keeping it dedicated to native_def_entity_rights will make it a little too rigid. Its just one variable which needs to be passed on.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 688 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIHfDl1YujhiadjGMp:-MKbDt1wDOeO9M0BGw-k:b1fn5l3) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L688)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Funnily this method just checks if the user belongs to System org or not. Which I think is still a requirement. Maybe rename it properly?
</blockquote></details>

@sahithi Yep, the above method only checks if the user is part of "System" Org or not.
We still need this check, basically, users from "System" org should be the only ones who can install/upgrade CSE.

@rocknes  sure I can rename it.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 688 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIHfDl1YujhiadjGMp:-MKbEDwHCuvzaF0e1hFZ:bwr6mw8) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L688)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

@sahithi Yep, the above method only checks if the user is part of "System" Org or not.
We still need this check, basically, users from "System" org should be the only ones who can install/upgrade CSE.

@rocknes  sure I can rename it.
</blockquote></details>

renaming it to: _raise_error_if_user_not_from_system_org (I know its a little too lonng/verbose, but should serve the purpose meaningfully).
Let me know if you think otherwise.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 701 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7oa-0OmmPEBFP1w3:-MKbEUo9AIhjf7CR88Iw:b29vdnf) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L701)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Exceptions should not leak out of this method. At least not the ones we can predict.
</blockquote></details>

Yes, the only exception i could find was a network connection related error. Hence kept it uncaught.
I simulated some errors like (wrong org name, wrong role name etc) via postman before, which threw bad HTTP statuses from underlying pyvcloud code; but given that such is never a possibility (config is always validated before calling this function); hence dint keep any try/catch here.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 701 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7oa-0OmmPEBFP1w3:-MKbF63l6W9nN96FeyHE:b-fomxix) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L701)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Yes, the only exception i could find was a network connection related error. Hence kept it uncaught.
I simulated some errors like (wrong org name, wrong role name etc) via postman before, which threw bad HTTP statuses from underlying pyvcloud code; but given that such is never a possibility (config is always validated before calling this function); hence dint keep any try/catch here.
</blockquote></details>

Let me modify comment to mention the same here, this method should always be called after validating config.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 730 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIIZphBV8lrG-4MGbL:-MKbFD_GDGOir80GqoS0:biw5xpa) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L730)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I agree with Sahithi, let's just refresh the client before returning. client.py in pyvcloud has methods like rehydrate_from_token, one of them should do the trick.
</blockquote></details>

Major mistake from me here; I already had a call to rehydrate_from_token here, but its in my local git repo.
@sahithi  & @rocknes Thanks a ton for catching it.

Making upgrade/install 2-step process is never an option; this was an error only.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 733 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCdtRK2fQG0mEHlNTS:-MKbFnyO0-g_hIBSuVCt:b6fbgo2) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L733)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I don't think this return is needed.
</blockquote></details>

habit :) 
returns make function entry/exits more readable and clear so..

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/right_bundle_manager.py, line 59 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP8ckf5OvWWcbIVDsm:-MKbFwKtD0esErpzEZS7:b-g7mo93) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/right_bundle_manager.py#L59)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please add doc string explaining the return type and structure of the returned json
</blockquote></details>

Yeah; will modify it for all methods in same class.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/def_/utils.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP9I_s43LOzZ50x5yk:-MKbG0Sc6K2dq1Lvd_p6:blwd34j) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/def_/utils.py#L22)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Seems like a duplicate of right_bundle_manager.CSE_NATIVE_RIGHT_BUNDLE_NAME

Also let's not add any more constants in utils file! We should actively move these constants to server_constant /shared_constants
</blockquote></details>

Mistake. For some reason dint catch this.
Thanks for pointing it out.

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803#-:-MKch3vU21b4FmcFaum1:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 8 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCe0vf4kS5uCw7ieuo:-MKgPoZH7QDFZ6gsqxBq:b-x9dah4) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Hi @ltimothy7 @sahithi 

Yes. The administrator is a user created with a SharingRole "Syatem Administrator". The Role is read-only from provider/user perspective, and it automatically gets all the dynamically created rights (VCD adds all dynamically created rights to Read-only roles).

Yes, when the admin user executed CSE install/update operation, it will be no-op from VCD perspective.
Meaning, CSE will still call the same API to assign the rights, but given that VCD has already published the same rights to system administrator role, this operation is no-op. P.S. VCD will not return any exceptions per say in such cases.

About executing this function only if user is non-system-administrator; 
I tried to check to this. Basically I can add a check at start of the method, checking if the user-name is "administrator" or its role is "System Administrator". 
Couldn't find an existing method to do so.
What it basically means is, in CSE code-base, a certain role/user-name is hard-coded; and given that the entire concept of "administrator" user is going away, I thought doing so would require certain cleanup later; and given that this method is essentially a no-op for "administrator" user, keeping this call is not big deal.

Let me know if you disagree or if there is a better way.
</blockquote></details>

From what I understand, the administrator role is not going away, but our access to it in the future will go away. @rocknes Is this correct?

If the administrator role will remain as is, I think adding the check and not executing the commands would be cleaner and easier to understand that this operation is only for the non-sys-admin.

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7YDlCeG1YWNVH87a:-MKnZgLq0rPm-nZixVWo:bwfjrwm) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Hmm,  i wanted to keep this as a generic utility function like _register_def_schema.
Lets say in future we come up with another def_schema to register, same function can be called, and keeping it dedicated to native_def_entity_rights will make it a little too rigid. Its just one variable which needs to be passed on.
</blockquote></details>

In that case the method and param should be called
_update_user_role_with_native_def_rights -> _update_user_role_with_right_bundle
defined_entity_right_bundle_name -> right_bundle_name
___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCe0vf4kS5uCw7ieuo:-MKnaFLh9h9w_73HwY1a:b-4czo8a) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

From what I understand, the administrator role is not going away, but our access to it in the future will go away. @rocknes Is this correct?

If the administrator role will remain as is, I think adding the check and not executing the commands would be cleaner and easier to understand that this operation is only for the non-sys-admin.
</blockquote></details>

sys admin role is a read only role, it can't be modified anyways via REST.
We need a way to identify roles in System org that are editable from non editable roles in System org.

To be honest, I feel the core of this method can be moved into some util module, whose job is to just take a right bundle and add the rights in it to a given user's role (+refresh the user session). And this update should happen only if the role is editable else throw appropriate exception.

In context of CSE installation, we call this method with the user that is provided to us via the config file + the defined entity right bundle that is generated during the installation process.
The restriction that the user should belong to System org is a CSE ask, and not inherently built into the operation we are trying to do.

Keep the concerns separate will lead to better code organization in my opinion.
___
*[container_service_extension/configure_cse.py, line 733 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKCdtRK2fQG0mEHlNTS:-MKnZzVM3mY5bnSXRnZ5:bibam7r) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L733)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

habit :) 
returns make function entry/exits more readable and clear so..
</blockquote></details>

please remove it. :)
___
*[container_service_extension/configure_cse.py, line 730 at r3](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKn_1gm6Ui6SF5LHhFa:-MKn_1gn2EzyvrL4gP9q:b-qmglzz) ([raw file](https://github.com/vmware/container-service-extension/blob/6c72590fee7bdfb8fe25417c8cec68323cb5065c/container_service_extension/configure_cse.py#L730)):*
> ```Python
>     # need to create a new HTTP Session, which will create new Security Context
>     # for logged in user.
>     vcd_auth_token = client.get_xvcloud_authorization_token()
> ```

xvcloud token can be empty .. if only access token (jwt) is being used.
The refresh logic isn't as straight forward as you might think. Let's discuss this tomorrow.

**Review by rocknes — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 6 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @sahithi)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 9 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 710 at r4](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLLeAgC534YalKnBnkI:-MLLeAgD8KIAnw2UdTfH:bfe6n7p) ([raw file](https://github.com/vmware/container-service-extension/blob/2284d833fd5393ec04d53f2abfc557e9c6f1d344/container_service_extension/configure_cse.py#L710)):*
> ```Python
>     role_record_read_only = role_record.get("isReadOnly").lower() in ["true"]
>     if (role_record_read_only):
>         msg = "User is created using predefined role in System Org; no need to add Rights to it" # noqa: E501
> ```

nit: User has predefined non editable role.  Not adding native entitlement rights.
___
*[container_service_extension/configure_cse.py, line 730 at r4](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLLek2w7b1GNKQNnyzd:-MLLek2w7b1GNKQNnyze:b5lhdto) ([raw file](https://github.com/vmware/container-service-extension/blob/2284d833fd5393ec04d53f2abfc557e9c6f1d344/container_service_extension/configure_cse.py#L730)):*
> ```Python
>         role_obj.add_rights(rights, system_org)
>     except AccessForbiddenException as err:
>         msg = "User doesn't have right to edit its Role. Please try with user who has this right." # noqa: E501
> ```

nit: User doesn't have permission to edit Roles.

No need to specify anything else.
___
*[container_service_extension/configure_cse.py, line 733 at r4](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLLfX3M-o9nTwnd6E7e:-MLLfX3M-o9nTwnd6E7f:bvx9v4l) ([raw file](https://github.com/vmware/container-service-extension/blob/2284d833fd5393ec04d53f2abfc557e9c6f1d344/container_service_extension/configure_cse.py#L733)):*
> ```Python
>         msg_update_callback.error(msg)
>         msg_update_callback.error(str(err))
>         return False
> ```

I think we should raise here and stop the install/upgrade process.. no point in carrying out the operation with a less privileged user.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 10 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 49 at r4](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLLggMZAfcYCNZGM70l:-MLLggMa6rYkLWVT2qFq:b33f62r) ([raw file](https://github.com/vmware/container-service-extension/blob/2284d833fd5393ec04d53f2abfc557e9c6f1d344/container_service_extension/configure_cse.py#L49)):*
> ```Python
> from container_service_extension.remote_template_manager import \
>     RemoteTemplateManager
> from container_service_extension.right_bundle_manager import RightBundleManager
> ```

I am not blocking the review for this line, but we should actively avoid using from X import Y syntax.

I think we actually need a team wide discussion on standardizing the import notation we all should be using.

fyi: I too like using from X import Y, since it allows flake8 to catch some static errors. But import X as alias_X is the community preference.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 733 at r4](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLLfX3M-o9nTwnd6E7e:-MLOmbYM4HFCNE6YJqke:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2284d833fd5393ec04d53f2abfc557e9c6f1d344/container_service_extension/configure_cse.py#L733)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we should raise here and stop the install/upgrade process.. no point in carrying out the operation with a less privileged user.
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 667 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP7YDlCeG1YWNVH87a:-MLOo-8x4CWcvXDPN0Pa:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L667)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

In that case the method and param should be called
_update_user_role_with_native_def_rights -> _update_user_role_with_right_bundle
defined_entity_right_bundle_name -> right_bundle_name
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/def_/utils.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKP9I_s43LOzZ50x5yk:-MLOqVMW4X45VUtaNTGf:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/def_/utils.py#L22)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Mistake. For some reason dint catch this.
Thanks for pointing it out.
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 730 at r1](https://reviewable.io/reviews/vmware/container-service-extension/803#-MKIIZphBV8lrG-4MGbL:-MLOqazt3DvnrxWu_Udl:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a7299543b13fc90a47c017d0b246c50a07524f4d/container_service_extension/configure_cse.py#L730)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Major mistake from me here; I already had a call to rehydrate_from_token here, but its in my local git repo.
@sahithi  & @rocknes Thanks a ton for catching it.

Making upgrade/install 2-step process is never an option; this was an error only.
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803#-:-MLOyrDKE3JW7bNL9KrK:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
:lgtm

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803#-:-MLP6PtU-ixRDcrEuaFn:b-8eqf7b)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 708 at r5](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLP5epq-ew4vPntuQLn:-MLP5epq-ew4vPntuQLo:b-8ck5ub) ([raw file](https://github.com/vmware/container-service-extension/blob/e4ac3739dbc1e77d6865490d6ea503663156f807/container_service_extension/configure_cse.py#L708)):*
> ```Python
>     # Using the Org, determine Role object (using Role-name we identified)
>     role_record = system_org.get_role_record(role_name)
>     role_record_read_only = role_record.get("isReadOnly").lower() in ["true"]
> ```

Minor: should just directly check if `role_record.get("isReadOnly").lower() == "true"`
___
*[container_service_extension/configure_cse.py, line 709 at r5](https://reviewable.io/reviews/vmware/container-service-extension/803#-MLP5v_w0Z4Y_TMYfMgq:-MLP5v_w0Z4Y_TMYfMgr:b7zy77m) ([raw file](https://github.com/vmware/container-service-extension/blob/e4ac3739dbc1e77d6865490d6ea503663156f807/container_service_extension/configure_cse.py#L709)):*
> ```Python
>     role_record = system_org.get_role_record(role_name)
>     role_record_read_only = role_record.get("isReadOnly").lower() in ["true"]
>     if (role_record_read_only):
> ```

Minor: parenthesis not needed

**Review by ltimothy7 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803#-:-MLP6aHB59t2HbRMyLuj:bnfp4nl)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, @rocknes, and @sahithi)

**Review by sahithi — APPROVED** [review]
> Reviewed 7 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/803)* status: all files reviewed, 7 unresolved discussions (waiting on @ChintanShahVMware, @ltimothy7, and @sahithi)

**Pull request merged**
