### PR TITLE
[VCDA-1711] Logger with request Id

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Each logging message now includes the request id if there is one present

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

This change included using a thread's local data to store the request id and propagating this request id to spawned threads.
I tested this logging with vcd cse ovdc enable because it spawned threads. I saw for both AMQP and MQTT that the request id was maintained.

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800)

### CODE REVIEW

**Review by sahithi — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/request_id_formatter.py, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7AqdoCORTzUjObFXr:-MK7Aqdp9IxBwk8z7N5E:b7bw03f) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/request_id_formatter.py#L18)):*
> ```Python
>         orig_format = self._style._fmt
> 
>         # Remove the request id from being printed is there is no request id
> ```

is -> if
___
*[container_service_extension/security.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Hvu30ogPqEPeOoaZ:-MK7Hvu30ogPqEPeOoa_:b-e9xoj4) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/security.py#L73)):*
> ```Python
>         """
>         record.msg = self.redact(record.msg)
>         record.requestId = get_thread_request_id()
> ```

Does it matter whether this line is present or not in this filter?
___
*[container_service_extension/thread_local_data.py, line 14 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Jolb2OSMNHTbB0Dx:-MK7Jolb2OSMNHTbB0Dy:b-fixtul) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/thread_local_data.py#L14)):*
> ```Python
> 
> 
> @run_once
> ```

Why does it matter if this method is run once or multiple times? It's just a read call.
Does invoking threading.local() wipes off old entries or variables?
___
*[container_service_extension/thread_local_data.py, line 20 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7JXdg1JmvomPp-T79:-MK7JXdg1JmvomPp-T7A:b-mb31rc) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/thread_local_data.py#L20)):*
> ```Python
> 
> 
> def set_thread_request_id(request_id):
> ```

I think this setter method needs to be wrapped by @run_once, if I am understanding the flow correctly.
___
*[container_service_extension/utils.py, line 384 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7IvLc1l59zH9LLevp:-MK7IvLd0LIJ0A6zHbu0:bghx1p6) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/utils.py#L384)):*
> ```Python
>     @functools.wraps(func)
>     def wrapper(*args, **kwargs):
>         set_thread_request_id(cur_thread_req_id)
> ```

Don't you have to call _init_thread_local_data()_ before setting it with _request_id_?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/security.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Hvu30ogPqEPeOoaZ:-MK7RHWk1VaIG4_Z2u52:beq4bcc) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/security.py#L73)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Does it matter whether this line is present or not in this filter?
</blockquote></details>

Yes, this line is needed to set the record's requestId to the appropriate value.
___
*[container_service_extension/thread_local_data.py, line 14 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Jolb2OSMNHTbB0Dx:-MK7RUkD67b0kuEj9zdg:b8uqw0x) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/thread_local_data.py#L14)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why does it matter if this method is run once or multiple times? It's just a read call.
Does invoking threading.local() wipes off old entries or variables?
</blockquote></details>

Yes, invoking threading.local() wipes off old entries, so it needs to be initialized once so that all threads can access 
___
*[container_service_extension/thread_local_data.py, line 20 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7JXdg1JmvomPp-T79:-MK7ReYc-jmy7_ffEHdy:bxyfmko) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/thread_local_data.py#L20)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think this setter method needs to be wrapped by @run_once, if I am understanding the flow correctly.
</blockquote></details>

A single thread's request id will change multiple times, so it will need to call this method more than once.
___
*[container_service_extension/utils.py, line 384 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7IvLc1l59zH9LLevp:-MK7RvxeDEGLhmRpTCxc:bb792jq) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/utils.py#L384)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Don't you have to call _init_thread_local_data()_ before setting it with _request_id_?
</blockquote></details>

init_thread_local_data()  only needs to be called once in the entire program. Then, other threads will read from the variable THREAD_DATA in thread_local_data.py; THREAD_DATA looks different to each thread. This usage wasn't intuitive, but this example helped me: 

https://www.bogotobogo.com/python/Multithread/python_multithreading_Thread_Local_Specific_Data.php

I will include a comment in thread_local_data.py to explain this better.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/thread_local_data.py, line 15 at r2](https://reviewable.io/reviews/vmware/container-service-extension/800#-MKBjdLO3a1gAEB0WsBr:-MKBjdLO3a1gAEB0WsBs:br72ebq) ([raw file](https://github.com/vmware/container-service-extension/blob/a10c1b559d13a5101e9b84b0424a1dda57b9fb0d/container_service_extension/thread_local_data.py#L15)):*
> ```Python
> 
> @run_once
> def init_thread_local_data():
> ```

This function is called in the main thread during __init__.py. This will be guaranteed to run only once. Is there a reason why it is decorated with `@run_once`?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800#-:-MKBsrcPA49qvynkQJRO:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @ltimothy7 and @sahithi)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800)* status: 9 of 19 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/request_id_formatter.py, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7AqdoCORTzUjObFXr:-MKB9jOf1lFZy7Z4NSiP:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/request_id_formatter.py#L18)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

is -> if
</blockquote></details>

Done.
___
*[container_service_extension/thread_local_data.py, line 15 at r2](https://reviewable.io/reviews/vmware/container-service-extension/800#-MKBjdLO3a1gAEB0WsBr:-MKCYSeR6NgG3DsR1Xzm:bvnjdsy) ([raw file](https://github.com/vmware/container-service-extension/blob/a10c1b559d13a5101e9b84b0424a1dda57b9fb0d/container_service_extension/thread_local_data.py#L15)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This function is called in the main thread during __init__.py. This will be guaranteed to run only once. Is there a reason why it is decorated with `@run_once`?
</blockquote></details>

This decorator is just an extra guarantee. It is similar to the two functions `<configure_all_file_loggers()>` and `<configure_null_logger()>`in logger.py called in init.py

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/800#-:-MKI95Pu7rSPYZpj1ubg:b593w57)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[container_service_extension/security.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Hvu30ogPqEPeOoaZ:-MKI8Ea091Nb2j5BdrLq:b-i5u1nw) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/security.py#L73)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Yes, this line is needed to set the record's requestId to the appropriate value.
</blockquote></details>

I mean there is nothing to be redacted in the requestId.
___
*[container_service_extension/thread_local_data.py, line 14 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Jolb2OSMNHTbB0Dx:-MKI8Plb3b8FqmFYkhAt:b-o78yda) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/thread_local_data.py#L14)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Yes, invoking threading.local() wipes off old entries, so it needs to be initialized once so that all threads can access 
</blockquote></details>

Got it, but sounds counterintuitive. 
___
*[container_service_extension/utils.py, line 384 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7IvLc1l59zH9LLevp:-MKI8r5v4hzuCmMKBuaT:b-y4s0bc) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/utils.py#L384)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

init_thread_local_data()  only needs to be called once in the entire program. Then, other threads will read from the variable THREAD_DATA in thread_local_data.py; THREAD_DATA looks different to each thread. This usage wasn't intuitive, but this example helped me: 

https://www.bogotobogo.com/python/Multithread/python_multithreading_Thread_Local_Specific_Data.php

I will include a comment in thread_local_data.py to explain this better.
</blockquote></details>

Thanks Tim.

**Comment by ltimothy7** [comment]
___
*[container_service_extension/security.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/800#-MK7Hvu30ogPqEPeOoaZ:-MKLFrve1GGAWhnRhaFi:biy0l0h) ([raw file](https://github.com/vmware/container-service-extension/blob/45969ab6f7b0fb63261a0f486243e70927d482b9/container_service_extension/security.py#L73)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I mean there is nothing to be redacted in the requestId.
</blockquote></details>

This line is just setting the requestId variable with no redactions. I placed this line in the RedactingFilter class because one way of adding a field in the logger is editing the filter function of the logger. It seemed simplest to add this to the existing Redacting Filter class than to reorganize/rename the Redacting Filter class to incorporate setting the request id.

**Pull request merged**
