### PR TITLE
[VCDA-3343] Implement RDE 2.1 backend

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
This PR allows for successful TKGm R1 RDE 2.1 cluster creation, resize, info, and delete (all of these have been tested).
(Note: cse upgrade will be part of a different set of tasks as well as PUT operations for CSI, CNI, and CPI)

- (Optional) Names of reviewers using @ sign + name
@sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: all files reviewed, 8 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/installer/configure_cse.py, line 1593 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBfGc_430fKRT78Aup:-MxBfGc_430fKRT78Auq:b-ja36ax) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/installer/configure_cse.py#L1593)):*
> ```Python
>     schema_svc = rde_schema_svc.DefSchemaService(cloudapi_client)
>     try:
>         current_entity_type: common_models.DefEntityType2_1 = \
> ```

This needs to stay DefEntityType2_0.
Only the value of the version property needs to be changed to 2.1.0
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 280 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBfsxH7k-xCspNmjZJ:-MxBfsxH7k-xCspNmjZK:bk5ixg2) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L280)):*
> ```Python
>             self._update_task(BehaviorTaskStatus.RUNNING, message=msg)
> 
>             # Handle defaults for csi
> ```

can you add a comment on the order of precedence?
1. RDE params 2. CSE config file 3.hard-coded defaults.

Can you also move the below logic to create_cluster_async() and update the RDE.status at the end of that method?
There is no problem as such logically, but it doesn't feel right to modify the input_native_entity.spec and pass it around.
It gives the false impression to the readers of other methods that these values are indeed actual inputs coming from the user.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 793 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBlknI4eJ5qu8MGmUZ:-MxBku0X1EceBVMv1cUf:b-x8ne1y) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L793)):*
> ```Python
>             default_storage_class = input_native_entity.spec.settings.csi[0].default_k8s_storage_class  # noqa: E501
>             create_default_storage_class: bool = default_storage_class is not None  # noqa: E501
>             dsc_storage_profile_name = None
> ```

Please add a comment "dsc" stands for default storage class.
At first, I read it as a description and wondered if we added a new property for the description.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2296 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBnfei6w7LN7zWXK34:-MxBnfei6w7LN7zWXK35:b-imii4n) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2296)):*
> ```Python
>         for spec in vm_specs:
>             # TODO: replace default storage values with user values
>             spec['cloud_init_spec'] = templated_script.format(
> ```

Also, for my benefit, is there any value in setting this property spec['cloud_init_spec'] as we use extraconfig options to set the cloudinit script?
I know this question is not relevant to this PR, let me know if you are aware of the reasoning.
@sakthisunda can answer

why are we setting cloud_init_spec twice, somewhere below too?
___
*[container_service_extension/rde/models/common_models.py, line 83 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBikBR0QEtzsBGmsGr:-MxBikBR0QEtzsBGmsGs:b-tc6x8d) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/models/common_models.py#L83)):*
> ```Python
> @dataclass_json(undefined=Undefined.EXCLUDE)
> @dataclass(frozen=True)
> class DefEntityType2_1:
> ```

This needs to stay DefEntityType2_0
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBp6VP0QNhPcyuZ0ic:-MxBp6VQ08d1MVfwiV_7:b9fr1ho) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
> ```Python
>     ]
> 
>     if is_tkgm_cluster:
> ```

Any PUT operation with the changes in these properties must throw 400, please ensure that.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 82 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjBor3A9YBeLRgYna:-MxBjBor3A9YBeLRgYnb:bdooij3) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L82)):*
> ```Python
> 
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_1_0.value):  # noqa: E501
> ```

All of these conditions need to stay as is

If 2.1 >= 2.0
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 4 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjXum5L-If20Gpb1L:-MxBjXum5L-If20Gpb1M:bspnsdz) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L4)):*
> ```Python
> # Copyright (c) 2020 VMware, Inc. All Rights Reserved.
> # SPDX-License-Identifier: BSD-2-Clause
> from typing import Type
> ```

Thought you deleted this file in the previous PR.

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: all files reviewed, 12 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 274 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjYCJ-imPDm1akP-0:-MxBjYCJ-imPDm1akP-1:b88cm0t) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L274)):*
> ```YAML
>       kubectl apply -f $csi_controller_path
>       kubectl apply -f $csi_node_path
> ```

there can be another `vmtoolsd` command here and at the end of this section to propagate installation progress to CSE.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 284 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBw9nT5Amcqu2Uw4Ef:-MxBw8Df2QgEiTYAv4qk:b-n2foc5) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L284)):*
> ```Python
>             if input_native_entity.spec.settings.csi is None or \
>                     len(input_native_entity.spec.settings.csi) == 0:
>                 input_native_entity.spec.settings.csi = [rde_2_x.CsiElement()]
> ```

Can there be more than one CSI
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 320 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxByUp98ljlhJDiRMBV:-MxByUp98ljlhJDiRMBW:b8ms3ts) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/models/rde_2_1_0.py#L320)):*
> ```Python
>                     cni_version_list = upgraded_native_entity.spec.settings.network.cni.split()  # noqa: E501
>                     upgraded_native_entity.spec.settings.cni.name = cni_version_list[0]  # noqa: E501
>                     if len(cni_version_list) > 0:
> ```

should this check be done before accessing `cni_version_list[0]` in the previous line?
Also we should be checking for `len(cni_version_list) > 1` here I think.
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 325 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBzfXu3ZShWgYMooH7:-MxBzfXu3ZShWgYMooH8:b9lcejz) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/models/rde_2_1_0.py#L325)):*
> ```Python
>                 return upgraded_native_entity
> 
>         if isinstance(native_entity, rde_1_0_0.NativeEntity):
> ```

Is this section still relevant? If CSE 3.1.3 can only be upgraded from CSE 3.1.2 which can only work with RDE 2.0 right?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: all files reviewed, 12 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2296 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBnfei6w7LN7zWXK34:-MxCG0L273Rsi9K_HFIk:b-plk3dg) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2296)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Also, for my benefit, is there any value in setting this property spec['cloud_init_spec'] as we use extraconfig options to set the cloudinit script?
I know this question is not relevant to this PR, let me know if you are aware of the reasoning.
@sakthisunda can answer

why are we setting cloud_init_spec twice, somewhere below too?

</blockquote></details>

I notice spec['cloud_init_spec'] is a plain text ;  may be useful for debugging. 
Actual setting in extraconfig is a base64 encoded.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: 2 of 11 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 274 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjYCJ-imPDm1akP-0:-MxC9ZCH1-oxzDY3UNAN:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L274)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

there can be another `vmtoolsd` command here and at the end of this section to propagate installation progress to CSE.
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 1593 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBfGc_430fKRT78Aup:-MxCA-La11jQ3kuzJui9:b-f56ui4) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/installer/configure_cse.py#L1593)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This needs to stay DefEntityType2_0.
Only the value of the version property needs to be changed to 2.1.0
</blockquote></details>

Done. Thanks Sahithi, this had gotten reverted when I did the merge
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 284 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBw9nT5Amcqu2Uw4Ef:-MxCE2c23W9M1mdkfFqd:b-aym9y0) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L284)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can there be more than one CSI
</blockquote></details>

Done. Yes, (resolved offline)
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 280 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBfsxH7k-xCspNmjZJ:-MxCE1fP8HPqllpM2W6k:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L280)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

can you add a comment on the order of precedence?
1. RDE params 2. CSE config file 3.hard-coded defaults.

Can you also move the below logic to create_cluster_async() and update the RDE.status at the end of that method?
There is no problem as such logically, but it doesn't feel right to modify the input_native_entity.spec and pass it around.
It gives the false impression to the readers of other methods that these values are indeed actual inputs coming from the user.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 793 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBlknI4eJ5qu8MGmUZ:-MxCE86N0TZOoDn8STkW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L793)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a comment "dsc" stands for default storage class.
At first, I read it as a description and wondered if we added a new property for the description.
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/common_models.py, line 83 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBikBR0QEtzsBGmsGr:-MxCEEP3BtfgAHLxGrkw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/models/common_models.py#L83)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This needs to stay DefEntityType2_0
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 320 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxByUp98ljlhJDiRMBV:-MxCEU2y9PowpqZJukHR:bt664kh) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/models/rde_2_1_0.py#L320)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should this check be done before accessing `cni_version_list[0]` in the previous line?
Also we should be checking for `len(cni_version_list) > 1` here I think.
</blockquote></details>

Done. We already checked that cni is not empty or None, so we know there is a string with at least one part, so when we call split(), we have at least one element, so we can get the 0th element

Thank you for the catch, I have changed this
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 325 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBzfXu3ZShWgYMooH7:-MxCEspv10bud99__vFM:b29mibv) ([raw file](https://github.com/vmware/container-service-extension/blob/50fc1cd1ecb4a2980f8e12ff945065dbd6083fda/container_service_extension/rde/models/rde_2_1_0.py#L325)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is this section still relevant? If CSE 3.1.3 can only be upgraded from CSE 3.1.2 which can only work with RDE 2.0 right?
</blockquote></details>

I am still getting clarity for upgrades path, and upgrades will be part of a separate task
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBp6VP0QNhPcyuZ0ic:-MxCF6FF52eYHtqrNwhY:b-xk19bx) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any PUT operation with the changes in these properties must throw 400, please ensure that.
</blockquote></details>

Yes, that will be part of another task in the backlog
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 82 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjBor3A9YBeLRgYna:-MxCFHZ419_Ig10HDC85:b-gdw7vl) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L82)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

All of these conditions need to stay as is

If 2.1 >= 2.0
</blockquote></details>

Done. Thank you, this also got overwritten from the merge
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 4 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBjXum5L-If20Gpb1L:-MxCG5E3CP2JrgEZP7Ye:b99umhw) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L4)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Thought you deleted this file in the previous PR.
</blockquote></details>

Done. Yes, it got rea-dded in my merge

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: 2 of 11 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2296 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBnfei6w7LN7zWXK34:-MxCJf_J7gYfhXsmhESf:bjzaxu8) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2296)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

I notice spec['cloud_init_spec'] is a plain text ;  may be useful for debugging. 
Actual setting in extraconfig is a base64 encoded. 

</blockquote></details>

I am not sure, but it seems like it has something to do with the second setting of the script being used with the exposed ip while the first may not use the exposed ip

**Review by sahithi — APPROVED** [review]
:lgtm: one last comment

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316#-:-MxCNnnP7j951tocF-a4:b-32r8zm)* status: all files reviewed, 13 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 762 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxCMi9u-vMRx722sKU6:-MxCMi9v6_Lf3Z6jMpsx:b-44i50p) ([raw file](https://github.com/vmware/container-service-extension/blob/4b1c27427640ac668d1247f3fe1717b877dab29e/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L762)):*
> ```Python
>             if input_native_entity.spec.settings.cpi is None:
>                 input_native_entity.spec.settings.cpi = rde_2_x.Cpi()
>             input_native_entity.spec.settings.cpi.name = CPI_NAME
> ```

we must not modify input_native_entity.spec, please use a separate variable for cpi and cni as well.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316#-:-MxCPA3fA_SgfwVLEO4W:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2296 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxBnfei6w7LN7zWXK34:-MxCOBu55LzI8BOlsgRe:bw9oze7) ([raw file](https://github.com/vmware/container-service-extension/blob/7afb1f41da497bcb0f464f783c5bac4d8db5fe45/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2296)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I am not sure, but it seems like it has something to do with the second setting of the script being used with the exposed ip while the first may not use the exposed ip
</blockquote></details>

I think the pyvcloud api `vapp.add_vms` also doesn't expect a key with name `cloud_init_spec`.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1316)* status: 10 of 11 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 762 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1316#-MxCMi9u-vMRx722sKU6:-MxClglB9BLg1FIsIubI:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/4b1c27427640ac668d1247f3fe1717b877dab29e/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L762)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

we must not modify input_native_entity.spec, please use a separate variable for cpi and cni as well.
</blockquote></details>

Done.

**Pull request merged**
