### PR TITLE
Update init-photon-v2.sh

### PR DESCRIPTION
**Pull request by tironside**
To help us process your pull request efficiently, please include: 

- (Required) update init script to remove # from sshd_config AuthorizedKeysFile

- (Required) Current template builds wont allow ssh login as the authorized keys file location is commented out; this is a simple sed to fix it.

Signed-off-by: Tony Ironside <tony@ironside.ca>

### CODE REVIEW

**Comment by andrew-ni** [comment]
Can you elaborate on why this change is needed? We have not had problems with ssh key access into VMs created using our current template scripts.

**Comment by tironside** [comment]
To be honest it came about as part user error on a public key

it does actually work as is with a correct key, from a hygiene point of
view it is more consistent.

Thx

T

**Comment by andrew-ni** [comment]
Would you be able to explain this in some more detail (why is this more hygienic?) and specify some use cases that require this fix?

Or if there's an external source where we can read more about this that'd be great too.

**Comment by tironside** [comment]
Hi Andrew

from a hygene standpoint it is  a case of implied vs explicit parameters.
I don't like implied parameters (ssh keys etc) and prefer to have them
explicitly defined.

That being said; the ssh standard appears to be that this parameter is
optional unless you want to change it; I will cancel the pull, as it is
more a preference than a requirement at this point

Thanks!

T

**Pull request closed without merging**
