### PR TITLE
[VCDA-2073] Update handlers to work with request dispatcher

### PR DESCRIPTION
**Pull request by rocknes**
We are in processing of replacing request_processor.py with request_dispatcher.py. In the new module a lot of the url matching and request dispatching is state machine driven. As a result of this change, the handlers need to adapt to the new style of invocation. This PR modifies the handlers, specially the non defined entity based ones, to adhere to the new way of handling requests

ToDo:
Test end to end workflows.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/935)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor comments

> Reviewed 10 of 13 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/935#-:-MUptdJ19euuqCRX6Moe:b-kfw89e)* status: all files reviewed, 3 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/server/request_dispatcher.py, line 271 at r1](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUpFs9z0t5FUjijYv7C:-MUpFs9z0t5FUjijYv7D:b-fg5u3v) ([raw file](https://github.com/vmware/container-service-extension/blob/58e199296845a01449d1eb1a2895a08ac90c81ba/container_service_extension/server/request_dispatcher.py#L271)):*
> ```Python
> ]
> 
> # /cse/cluster/{id}/nodes end points
> ```

comment is wrong. /cse/nodes* end points
___
*[container_service_extension/server/request_dispatcher.py, line 137 at r2](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUptH6o8yXRB4PSnYxB:-MUptH6o8yXRB4PSnYxC:b-1rz0n7) ([raw file](https://github.com/vmware/container-service-extension/blob/8522130503cae86f85267c0c6d695b6a8e1debaa/container_service_extension/server/request_dispatcher.py#L137)):*
> ```Python
>         RequestMethod.GET: {
>             tuple(server_constants.SUPPORTED_VCD_API_VERSIONS): {
>                 'allowed_params': [],
> ```

`list_pks_plans` should be added here
___
*[container_service_extension/server/request_handlers/pks/pks_cluster_handler.py, line 184 at r2](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUpppig0i1cyhIsIIqA:-MUpoxo-8gsFtjMFw4lI:bn5uzfe) ([raw file](https://github.com/vmware/container-service-extension/blob/8522130503cae86f85267c0c6d695b6a8e1debaa/container_service_extension/server/request_handlers/pks/pks_cluster_handler.py#L184)):*
> ```Python
>         cse_operation=CseOperation.PKS_CLUSTER_DELETE,
>         cse_params=_get_telemetry_data(request_data, cluster))
>     return broker.delete_cluster(data=request_data)
> ```

Do we have to flatten query_params? Because `org_name` and `ovdc_name` is specified in `allowed_params` for pks cluster delete

Actually it is specified for all the pks cluster operations. But only the handler for cluster info is using them.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/935)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/request_dispatcher.py, line 271 at r1](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUpFs9z0t5FUjijYv7C:-MUqDE7jDbvOGogSxfCF:b4wn5r6) ([raw file](https://github.com/vmware/container-service-extension/blob/58e199296845a01449d1eb1a2895a08ac90c81ba/container_service_extension/server/request_dispatcher.py#L271)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

comment is wrong. /cse/nodes* end points
</blockquote></details>

thanks fixed
___
*[container_service_extension/server/request_dispatcher.py, line 137 at r2](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUptH6o8yXRB4PSnYxB:-MUqChzl5QT9j_4B-qY_:b-xa0z3i) ([raw file](https://github.com/vmware/container-service-extension/blob/8522130503cae86f85267c0c6d695b6a8e1debaa/container_service_extension/server/request_dispatcher.py#L137)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`list_pks_plans` should be added here
</blockquote></details>

Thanks for catching this :) Really annoying to comb through all the files to determine the params etc.
___
*[container_service_extension/server/request_handlers/pks/pks_cluster_handler.py, line 184 at r2](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUpppig0i1cyhIsIIqA:-MUqDKZ1BYCfqRX_Y6Cv:b9pearo) ([raw file](https://github.com/vmware/container-service-extension/blob/8522130503cae86f85267c0c6d695b6a8e1debaa/container_service_extension/server/request_handlers/pks/pks_cluster_handler.py#L184)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Do we have to flatten query_params? Because `org_name` and `ovdc_name` is specified in `allowed_params` for pks cluster delete

Actually it is specified for all the pks cluster operations. But only the handler for cluster info is using them.
</blockquote></details>

I think I should have explained this better, currently the allowed param list is useless, it is not being used anywhere .
I envision that in future we would use this list to prune out unwanted query params sent by clients (as a security measure). Or do some early validation.


Right now the query prams are stuffed into request_data dict with the key RequestKey.QUERY_PARAMS

However the legacy handlers (vdc broker, template handler, pks handlers, system handlers, legacy ovdc handlers) want the dict to be flat, the RDE based cluster and ovdc handlers wants the Query param and input spec to be distinct.

To accommodate both the needs, I am passing the request data dict with query param and input spec (request body) as separate key-value pairs. And the individual handlers are deciding what they want and how the information should be presented to the backend layer (e.g. vcd broker wants the request body and query param as a single flat dictionary).

**Review by sahithi — APPROVED** [review]
:lgtm: with one comment.
It seems like this PR requires more testing than reviewing :) 

> Reviewed 8 of 13 files at r1, 3 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/935#-:-MUtm8sL8Payb4l7Xphy:bwrwvz8)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/server/request_dispatcher.py, line 816 at r3](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUtlfwHAKpKAa-rMoXy:-MUtlfwI4IZHRu_WsYhg:bw1v742) ([raw file](https://github.com/vmware/container-service-extension/blob/cc293f5c4960cc7d587c97bdc64ed5b484552538/container_service_extension/server/request_dispatcher.py#L816)):*
> ```Python
>     if request_body:
>         request_data[RequestKey.INPUT_SPEC] = request_body
>         LOGGER.debug(f"request body: {request_data}")
> ```

Logger message -> request_body?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/935)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/request_dispatcher.py, line 816 at r3](https://reviewable.io/reviews/vmware/container-service-extension/935#-MUtlfwHAKpKAa-rMoXy:-MUtrQSy0FFZ0Q-g6LwJ:bwk5d5h) ([raw file](https://github.com/vmware/container-service-extension/blob/cc293f5c4960cc7d587c97bdc64ed5b484552538/container_service_extension/server/request_dispatcher.py#L816)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Logger message -> request_body?
</blockquote></details>

Thanks, fixed it.

**Pull request merged**
