### PR TITLE
[VCDA-1875] Update template announcements page

### PR DESCRIPTION
**Pull request by sakthisunda**
- Updated template announcement page for CSE 2.6 and CSE 3.0  
- New templates
- Existing templates with updated version
- NOTE: Placeholder value for Date ( will be replaced as per the recommendation )

@rocknes @sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/776)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/776#-:-MJ90FVa5Sht0l7bQwHF:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by rocknes — APPROVED** [review]
:lgtm:

The upgrades -> master change should be made in sample_config_generator too

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/776#-:-MJ9G4wlBxayUFIacD5c:b2mxrmv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
sample_config_generator changed as well

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/776#-:-MJ9IRaUErU30BeQhZfN:busnt92)* status: 3 of 4 files reviewed, all discussions resolved

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/776)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
