### PR TITLE
[VCDA-2739] Implement 'cse template import` command

### PR DESCRIPTION
**Pull request by rocknes**
Implemented `cse template import` command to import TKGm OVA into CSE catalog.

Testing Done:
* Uploaded a proper TKGm OVA and checked that the VApp template is in the CSE catalog, and the catalog item has correct metadata.
* Tried to upload a directory. Received proper error message.
* Tried to upload an existing VApp template, received proper error message.
* Tried to upload an existing VApp template with -f flag, the operation was successful.
* Tried uploading random OVA. Was prompted correctly for confirmation and additional questions were asked by CSE to construct the metadata correctly.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 3 unresolved discussions (waiting on @arunmk, @rocknes, and @sakthisunda)

___
*[container_service_extension/installer/templates/tkgm_template_manager.py, line 28 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVLdj28UO47dFcOEq3:-MhVLdj28UO47dFcOEq4:b-tprm13) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/installer/templates/tkgm_template_manager.py#L28)):*
> ```Python
>         g = m.groups()
>         if len(g) == 2:
>             os_version = g[0]
> ```

If ubuntu-2004-kube-v1.19.8-vmware.1-tkg.0-18171857641727074969.ova is used as an example, the OS version will be 2004, which is not correct right?
___
*[container_service_extension/server/cli/server_cli.py, line 1304 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVNmBQCPtou0hKTWTk:-MhVNmBQCPtou0hKTWTl:b7om1da) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1304)):*
> ```Python
> )
> @click.option(
>     '-F',
> ```

should there be another option to import from another catalog?
___
*[container_service_extension/server/cli/server_cli.py, line 1462 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVPOSF0xLQvTw5AS0q:-MhVPOSF0xLQvTw5AS0r:b-p8n29h) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1462)):*
> ```Python
>         if client:
>             client.logout()
>         # block the process to let telemetry handler to finish posting data to
> ```

I don't see any telemetry calls made for this command? I might be missing something though

**Review by rocknes — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sakthisunda)

___
*[container_service_extension/installer/templates/tkgm_template_manager.py, line 28 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVLdj28UO47dFcOEq3:-MhViaF62mr_PPbJeIMf:b7j0li6) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/installer/templates/tkgm_template_manager.py#L28)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If ubuntu-2004-kube-v1.19.8-vmware.1-tkg.0-18171857641727074969.ova is used as an example, the OS version will be 2004, which is not correct right?
</blockquote></details>

That's the best we can get right now. However, the actual version is again computed from the product section and that takes precendence.
___
*[container_service_extension/server/cli/server_cli.py, line 1304 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVNmBQCPtou0hKTWTk:-MhVihfP7X7_-W9nPa1v:bdsqrlu) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1304)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should there be another option to import from another catalog?
</blockquote></details>

Yes, there will be but that's a future work
___
*[container_service_extension/server/cli/server_cli.py, line 1462 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhVPOSF0xLQvTw5AS0q:-MhVikVr25H1jcipuVHx:bse1xir) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1462)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I don't see any telemetry calls made for this command? I might be missing something though
</blockquote></details>

No the telemetry work is pending. I will add a ToDo. I copied the code from other commands, so these lines also got copied.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @rocknes)

___
*[container_service_extension/installer/templates/tkgm_template_manager.py, line 21 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhX-Y6mDI2kuZpPLwC_:-MhWuu6l95rN76jOa-6P:b-smsbn) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/installer/templates/tkgm_template_manager.py#L21)):*
> ```
> ubuntu-2004-kube-v1.19.8-vmware.1-tkg.0-18171857641727074969.ova
> ```
seeing optional zero or more repetition pattern. This might accept non standard .ova names as well. But that may not be important.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sakthisunda)

___
*[container_service_extension/installer/templates/tkgm_template_manager.py, line 21 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhX-Y6mDI2kuZpPLwC_:-MhZar9L-JLe1n3ioksn:bil7559) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/installer/templates/tkgm_template_manager.py#L21)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> ubuntu-2004-kube-v1.19.8-vmware.1-tkg.0-18171857641727074969.ova
> ```
seeing optional zero or more repetition pattern. This might accept non standard .ova names as well. But that may not be important.
</blockquote></details>

Yeah correct but not really important since we will trim those extra part anyways for version matching in future.

**Review by Anirudh9794 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @sakthisunda)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/server/cli/server_cli.py, line 1408 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhZbI6mDXRBwmDwNpn4:-MhZbI6mDXRBwmDwNpn5:b-gilsk9) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1408)):*
> ```Python
>         kubernetes = "TKGm"
> 
>         os_name = os_name_from_property_map
> ```

At some point in future we could always ask the user with the values we have deciphered as default values. That will help them verify and change things if needed.

**Comment by arunmk** [comment]
:lgtm:

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1166)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @sakthisunda)

___
*[container_service_extension/server/cli/server_cli.py, line 1408 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1166#-MhZbI6mDXRBwmDwNpn4:-MhZtcrpBanIR_AfVmCk:b-18596t) ([raw file](https://github.com/vmware/container-service-extension/blob/ed94494a9cc0b4a4592a0a623bd2bbffb696ab74/container_service_extension/server/cli/server_cli.py#L1408)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

At some point in future we could always ask the user with the values we have deciphered as default values. That will help them verify and change things if needed.
</blockquote></details>

Sounds good. Will add it in the next PR.

**Pull request merged**
