### PR TITLE
[VCDA-2588] Set up environment for RDE based tests (#1070)

### PR DESCRIPTION
**Pull request by Anirudh9794**
- copy system_tests to system_tests_v2 which contain tests for RDE based operations
- add functions in system tests framework module to help create and teardown environment for RDE based tests.
  - added new role cluster_admin and cluster_author. (No module to clean up the roles created though)
  - Add support for MQTT in system tests
  - Create base_config.yaml with legacy_mode: false

Testing done:
- Run` test_cse_server.py` and make sure all the tests pass

@rocknes @sakthisunda @sahithi @ltimothy7 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794)

___
*[test-requirements.txt, line 7 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgMhWaGDkFDGVOX4QXS:-MgMhWaGDkFDGVOX4QXT:blrbei1) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/test-requirements.txt#L7)):*
> ```help
> pytest
> pydocstyle < 4
> pytest-logger
> ```

nit: does this need a newline? The strange rectangles from other reviews is showing up
___
*[container_service_extension/system_test_framework/environment.py, line 529 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN80OvE9FGsWySnaQA:-MgN80OvE9FGsWySnaQB:b-iidwwo) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/container_service_extension/system_test_framework/environment.py#L529)):*
> ```Python
>     except EntityNotFoundException:
>         logger.debug(f"Failed to delete catalog {catalog_name}")
>         pass
> ```

nit: this isn't needed anymore 
similarly: other places that handle exceptions don't need a `pass` statement unless there is no other code executed
___
*[container_service_extension/system_test_framework/environment.py, line 559 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8BLV136p9wc7BgBz:-MgN8BLV136p9wc7BgC-:b-88z6vt) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/container_service_extension/system_test_framework/environment.py#L559)):*
> ```Python
>     except Exception as e:
>         logger.debug(f"Failed to unregister CSE from MQTT: {e}")
>         pass
> ```

not needed also along with other places such as the following two functions
___
*[system_tests_v2/conftest.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8UYC2f2n_7TtKLt2:-MgN8UYC2f2n_7TtKLt3:b-cgwfta) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/system_tests_v2/conftest.py#L73)):*
> ```Python
>                     env.CLUSTER_AUTHOR_ROLE_NAME,
>                     logger=pytest_logger.PYTEST_LOGGER)
>     yield
> ```

is this yield no longer needed since there is no code after to execute?
___
*[system_tests_v2/conftest.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8kPMAFAemuL4sOZs:-MgN8kPMAFAemuL4sOZt:b-27rmpk) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/system_tests_v2/conftest.py#L115)):*
> ```Python
>     - assign appropriate rights to roles in test org
>     """
>     yield
> ```

could you explain why this test starts with a `yield`?
___
*[system_tests_v2/README.md, line 141 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgNDrks3DVGsIGgH_lD:-MgNDrks3DVGsIGgH_lE:bydhe8r) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/system_tests_v2/README.md#L141)):*
> ```Markdown
> - Fixtures: <https://docs.pytest.org/en/latest/fixture.html>
> - Click Testing: <http://click.palletsprojects.com/en/7.x/testing/>
> - Logging: <https://pypi.org/project/pytest-logger/>
> ```

nit: newline needed

**Review by ltimothy7 — COMMENTED** [review]
Nice Job, Aniruddha
Just minor changes requested

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155#-:-MgNGk0K4FUyC7g53srg:bcy2duf)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[system_tests_v2/conftest.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8kPMAFAemuL4sOZs:-MgNOHIgAFbm5fEIbNzp:b-1cb43o) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/system_tests_v2/conftest.py#L115)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

could you explain why this test starts with a `yield`?
</blockquote></details>

When executing a fixture, pytest executes the code before the yield before the test is executed and executes the code after the yield after the test is finished. In this case, publishing of right bundles should be done after installation test is done. Hence the fixture starts with a yield.

**Comment by Anirudh9794** [comment]
___
*[system_tests_v2/conftest.py, line 73 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8UYC2f2n_7TtKLt2:-MggEyTQCVaDIKWR40wX:bkdwbcx) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/system_tests_v2/conftest.py#L73)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

is this yield no longer needed since there is no code after to execute?
</blockquote></details>

I guess this can be ignored. I believe this was added to maintain common type of codes across fixtures.
Have removed the yield.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/system_test_framework/environment.py, line 559 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1155#-MgN8BLV136p9wc7BgBz:-MggDfVA7ehLhG7TsfXc:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6471c04b0995e50c6a0e2fbdf1822b3b69a985a5/container_service_extension/system_test_framework/environment.py#L559)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

not needed also along with other places such as the following two functions
</blockquote></details>

Done.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @ltimothy7)

___
*[system_tests_v2/test_cse_server.py, line 209 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1155#-Mgm2hNo04TpuTPmfJ0H:-Mgm2hNpAoVJBQqegh7I:b-cp80eq) ([raw file](https://github.com/vmware/container-service-extension/blob/3841ac6e46ddc3250cd3082d413169723be0fb44/system_tests_v2/test_cse_server.py#L209)):*
> ```Python
>             PYTEST_LOGGER.debug("Validation failed as expected due "
>                                 f"to invalid keys: {e}")
>             pass
> ```

nit: this `pass` is also not needed

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 2 of 4 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1155)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @ltimothy7)

___
*[system_tests_v2/base_config.yaml, line 54 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1155#-Mho5Vs30gnSKVdJTpGf:-Mho5Vs30gnSKVdJTpGg:b614y7x) ([raw file](https://github.com/vmware/container-service-extension/blob/02f13bc269807dbd40d163cd85377666f216ceb1/system_tests_v2/base_config.yaml#L54)):*
> ```YAML
> broker:
>   catalog: cse                          # public shared catalog within org where the template will be published
>   default_template_name: photon-v2_k8-1.14_weave-2.5.2
> ```

In the current state, 3_1_updates does not support photon based cluster operations. FYI

**Comment by Anirudh9794** [comment]
___
*[system_tests_v2/base_config.yaml, line 54 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1155#-Mho5Vs30gnSKVdJTpGf:-MhoAO8PCmPKfkw0qbgX:b-6nxmow) ([raw file](https://github.com/vmware/container-service-extension/blob/02f13bc269807dbd40d163cd85377666f216ceb1/system_tests_v2/base_config.yaml#L54)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

In the current state, 3_1_updates does not support photon based cluster operations. FYI
</blockquote></details>

Changed default template to ubuntu k8s 1.21

**Pull request merged**
