### PR TITLE
Fix TKG cluster list operation when CLI is enabled only for TKG

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Currently, cluster list operation will fail because TKG client pagination changes were removed.

This PR Adds back the TKG client changes

The changes in TKG client for pagination are still needed if CSE server is not running (CLI will be enabled only for TKG clusters)

Testing done:
* `vcd cse cluster list` when CLI is enabled only for TKG clusters

@sahithi @sakthisunda @rocknes @ltimothy7 @ChintanShahVMware @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/872)

### CODE REVIEW

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/872#-:-MR62EYICtNZE8ckk36R:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/872)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/client/tkgclient/api/tkg_cluster_api.py, line 60 at r1](https://reviewable.io/reviews/vmware/container-service-extension/872#-MRWsGsq0424j7WErwTP:-MRWsGsq0424j7WErwTQ:b-7be5it) ([raw file](https://github.com/vmware/container-service-extension/blob/1403f40485824da9a7f075f7d11762882a546eec/container_service_extension/client/tkgclient/api/tkg_cluster_api.py#L60)):*
> ```
> if params.get('query_params'):
> ```
This statement seems redundant

**Review by sakthisunda — APPROVED** [review]
:lgtm: (minor comment)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/872#-:-MRWsaf87c8PMiS7qx6u:b-3xlrhu)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/tkgclient/api/tkg_cluster_api.py, line 60 at r1](https://reviewable.io/reviews/vmware/container-service-extension/872#-MRWsGsq0424j7WErwTP:-MRY0jnc8nj2VorBWsVZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/1403f40485824da9a7f075f7d11762882a546eec/container_service_extension/client/tkgclient/api/tkg_cluster_api.py#L60)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> if params.get('query_params'):
> ```
This statement seems redundant
</blockquote></details>

Done.

**Pull request merged**
