### PR TITLE
[VCDA-2855] Let CSE server startup without a default native template

### PR DESCRIPTION
**Pull request by rocknes**
Removed code that 
1. Checked for presence of at least one native template as well as default template during CSE server startup
2. Chose default template if none is provided during cluster operations. Now, an error would be thrown instead.
3. Generated default template and revision in sample config

Fixed a bunch of flake8 errors.

Testing:
Was able to successfully startup CSE with no native templates in system.

Tried to deploy a native cluster and verified that it failed with proper error.
```
(cse) D:\code\cse\container-service-extension>vcd task wait 12f5ef7a-d112-4c44-a218-73bde685c7ed
task: 12f5ef7a-d112-4c44-a218-73bde685c7ed, result: error, message: Template 'ubuntu-16.04_k8-1.20_weave-2.6.5' at revision 2 not found.
```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1182)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Minor comments

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1182#-:-Mj0_OEoD-Hoe7stmeBA:by0nmtq)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0WAJQ-FoA2XMJiufi:-Mj0WAJQ-FoA2XMJiufj:bq8dbrr) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1822)):*
> ```Python
>         expose=False,
>         cluster_name=None,
>         cluster_id=None) -> Tuple[str, List[Dict]]:
> ```

Docstring info regarding information that is returned would be helpful
___
*[container_service_extension/server/cli/server_cli.py, line 1105 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0Zycg3Q-EV03xUlYf:-Mj0Zycg3Q-EV03xUlYg:b-hfvtkk) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/server/cli/server_cli.py#L1105)):*
> ```Python
>                     if legacy_mode:
>                         local_template['compute_policy'] = definition[server_constants.LegacyLocalTemplateKey.COMPUTE_POLICY]  # noqa: E501
>                     local_template['default'] = 'No'
> ```

Since there are no default templates, should we remove displaying default templates from CSE server CLI?

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1182)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/installer/sample_generator.py, line 127 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0SiLH2ZQEtyj2i-l8:-Mj0SiLH2ZQEtyj2i-l9:b-7vh7yx) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/installer/sample_generator.py#L127)):*
> ```Python
>         'ip_allocation_mode': 'pool',
>         'storage_profile': '*',
>         'remote_template_cookbook_url': 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/template_v2.yaml',  # noqa: E501
> ```

nit: redundant comma after /template_v2.yaml
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2324 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0UnU51DX9y-qEUe5K:-Mj0UnU51DX9y-qEUe5L:bxs3jvi) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x.py#L2324)):*
> ```Python
>     if not name or not revision:
>         raise ValueError(
>             "Template name and revision both must be is specified."
> ```

nit: typo

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1182)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0WAJQ-FoA2XMJiufi:-Mj1-9o_D__SfgL17gDL:bh0j2z6) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1822)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Docstring info regarding information that is returned would be helpful
</blockquote></details>

hmm...I added this return. Do we add docstrings for internal functions (starting with `_`) as well?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1938 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj1-NplB8wtJOHFJFMi:-Mj1-NplB8wtJOHFJFMj:b-d2m5la) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1938)):*
> ```Python
>             # 1. run script with parameter "precustomization"
>             # 2. set up network
>             # 3. convert script with parameter "precustomization" to service
> ```

Could you please change this (3.) to "postcustomization" ? I messed up the description.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1182)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sakthisunda)

___
*[container_service_extension/installer/sample_generator.py, line 127 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0SiLH2ZQEtyj2i-l8:-Mj1Lg-0-0-ZgLSkl2E5:b-k73z76) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/installer/sample_generator.py#L127)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit: redundant comma after /template_v2.yaml
</blockquote></details>

thanks
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2324 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0UnU51DX9y-qEUe5K:-Mj1Lf8O93cDfno5C62_:b-k73z76) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x.py#L2324)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

thanks
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0WAJQ-FoA2XMJiufi:-Mj1LWnA6lnT4JvZzodb:b7asuy) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1822)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

hmm...I added this return. Do we add docstrings for internal functions (starting with `_`) as well?
</blockquote></details>

Generally, we don't add docstring for internal functions, but if the function is complex enough, I guess it doesn't hurt to add the docstring for better maintainability.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1938 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj1-NplB8wtJOHFJFMi:-Mj1LV7H9hnnDY39JDhy:bb7oryy) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1938)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Could you please change this (3.) to "postcustomization" ? I messed up the description.
</blockquote></details>

sure
___
*[container_service_extension/server/cli/server_cli.py, line 1105 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1182#-Mj0Zycg3Q-EV03xUlYf:-Mj1LLqx7Tdj1y1xKLTy:b-5zy74i) ([raw file](https://github.com/vmware/container-service-extension/blob/13b98338fa86b060602223b31efab36c3a455622/container_service_extension/server/cli/server_cli.py#L1105)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since there are no default templates, should we remove displaying default templates from CSE server CLI?
</blockquote></details>

Yes, I will remove the field from cli output, but will keep the field around in REST response to retain backward compatibility.

**Pull request merged**
