### PR TITLE
[VCDA-2122] Add utility methods for fetching rde_schema_version

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Add mapping to get rde_schema_version to be used during CSE configuration

Add method to get currently used schema version when CSE is running

@sahithi @sakthisunda @rocknes @ltimothy7 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/913)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/913)* status: 2 of 3 files reviewed, all discussions resolved

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/913)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/constants.py, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTlStGBEcO71y9o96y1:-MTlStGBEcO71y9o96y2:b-3lx4xh) ([raw file](https://github.com/vmware/container-service-extension/blob/a94f379c068644a951bb48153438bfc4a0806e91/container_service_extension/rde/constants.py#L91)):*
> ```Python
> 
> 
> # Dictionary indicating RDE version to use
> ```

An elaborate comment on how to update this table for the developers in the future releases.

Examples on how the table needs to be updated on major and minor bump-ups.

Example: Below table would change to this when minor version is bumped up. Similar example for major bump-up. 
35	1.0.     
36	2.0
37	2.1
      |
      V
35	1.0
36	2.1
37	2.1

Add the other table (RDE version -> VCD API version) in the comment. Add a one-liner on the min and max thing we discussed. That would help readers understand how we came up to follow this approach.
___
*[container_service_extension/server/service.py, line 499 at r1](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTlVvuQBZVJOSXW8WD4:-MTlVvuQBZVJOSXW8WD5:bdofjta) ([raw file](https://github.com/vmware/container-service-extension/blob/a94f379c068644a951bb48153438bfc4a0806e91/container_service_extension/server/service.py#L499)):*
> ```
>             self._rde_schema_version = \
>                 def_utils.get_rde_schema_version_by_vcd_api_version(max_vcd_api_version_supported)  # noqa: E501
> ```
 Can you put this variable in the config at the time of start-up, install and upgrade?
config['service']['rde_to_use'] = def_utils.get_rde_schema_version_by_vcd_api_version(max_vcd_api_version_supported)

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/913)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/constants.py, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTlStGBEcO71y9o96y1:-MTm6pJ03SbNGOc3n-DJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a94f379c068644a951bb48153438bfc4a0806e91/container_service_extension/rde/constants.py#L91)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

An elaborate comment on how to update this table for the developers in the future releases.

Examples on how the table needs to be updated on major and minor bump-ups.

Example: Below table would change to this when minor version is bumped up. Similar example for major bump-up. 
35	1.0.     
36	2.0
37	2.1
      |
      V
35	1.0
36	2.1
37	2.1

Add the other table (RDE version -> VCD API version) in the comment. Add a one-liner on the min and max thing we discussed. That would help readers understand how we came up to follow this approach.

</blockquote></details>

Done.
___
*[container_service_extension/server/service.py, line 499 at r1](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTlVvuQBZVJOSXW8WD4:-MTlk9FMBZjyoqQsW_QW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a94f379c068644a951bb48153438bfc4a0806e91/container_service_extension/server/service.py#L499)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>             self._rde_schema_version = \
>                 def_utils.get_rde_schema_version_by_vcd_api_version(max_vcd_api_version_supported)  # noqa: E501
> ```
 Can you put this variable in the config at the time of start-up, install and upgrade?
config['service']['rde_to_use'] = def_utils.get_rde_schema_version_by_vcd_api_version(max_vcd_api_version_supported) 
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/913#-:-MTmPIgKAa57yHnHXszZ:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/constants.py, line 93 at r2](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTmJIO11dKSXkPe-q2Z:-MTmJIO2BG6dSJFOEnL0:b-a21so9) ([raw file](https://github.com/vmware/container-service-extension/blob/cd76a499aa8bfc0663ae6a67b3f5f3247e237d07/container_service_extension/rde/constants.py#L93)):*
> ```Python
> # Dictionary indicating RDE version to use
> # for the VCD API version
> # During runtime, the max RDE version supported
> ```

Based on the VCD-version CSE server is configured with, CSE server dynamically determines the RDE-version-to-use at runtime.
___
*[container_service_extension/rde/constants.py, line 96 at r2](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTmKfxiAPuU9nU21pfR:-MTmKfxiAPuU9nU21pfS:by9gzsp) ([raw file](https://github.com/vmware/container-service-extension/blob/cd76a499aa8bfc0663ae6a67b3f5f3247e237d07/container_service_extension/rde/constants.py#L96)):*
> ```Python
> # with the VCD API version is used.
> # MAP_VCD_API_VERSION_TO_RDE_SCHEMA_VERSION is a dictionary
> # depicting the current max RDE version in use for each
> ```

Below dictionary essentially answers this question:
"When CSE is configured with VCD of a given api-version, what is the compatible RDE-version CSE-server must use on that VCD?"

- Key represents the VCD api-version CSE is configured with.
- Value represents the RDE-version CSE-server must use for that VCD environment.

This map must be carefully updated for every major/minor/patch version increments of RDE for each official CSE release. Below are few examples on how this map could be updated.
___
*[container_service_extension/rde/constants.py, line 101 at r2](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTmM5cH07NnxmrUZpeH:-MTmM5cH07NnxmrUZpeI:brszl6j) ([raw file](https://github.com/vmware/container-service-extension/blob/cd76a499aa8bfc0663ae6a67b3f5f3247e237d07/container_service_extension/rde/constants.py#L101)):*
> ```Python
> # be different in other CSE releases.
> # Example -
> # Current mapping:
> ```

Replace current mapping with CSE 3.1
___
*[container_service_extension/rde/constants.py, line 106 at r2](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTmMU4i6sgpCpHAKcj7:-MTmMU4i6sgpCpHAKcj8:b-aw9hzl) ([raw file](https://github.com/vmware/container-service-extension/blob/cd76a499aa8bfc0663ae6a67b3f5f3247e237d07/container_service_extension/rde/constants.py#L106)):*
> ```
> # For CSE 3.2 with vCD 10.4 (API Version 37) with minor
> # version bump in RDE
> ```
 Say, CSE 3.2 introduces minor version bump in RDE - 2.1 (and say CSE 3.2 releases alongside of VCD 10.4 (api version 37))
___
*[container_service_extension/rde/constants.py, line 113 at r2](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTmN23h0vJ9KqgKOyUH:-MTmN23h0vJ9KqgKOyUI:bnj7hl0) ([raw file](https://github.com/vmware/container-service-extension/blob/cd76a499aa8bfc0663ae6a67b3f5f3247e237d07/container_service_extension/rde/constants.py#L113)):*
> ```Python
> # 37.0: 2.1.0 (Newly introduced RDE),
> # }
> # For CSE 3.2 with vCD 10.4 (API version 37) with major
> ```

same as above
___
*[container_service_extension/server/service.py, line 499 at r1](https://reviewable.io/reviews/vmware/container-service-extension/913#-MTlVvuQBZVJOSXW8WD4:-MTmNqWJBNKbXc1ST5qp:b6gf2uh) ([raw file](https://github.com/vmware/container-service-extension/blob/a94f379c068644a951bb48153438bfc4a0806e91/container_service_extension/server/service.py#L499)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You updated the variable for service start-up, but not yet for instal and upgrade.

**Pull request merged**
