### PR TITLE
[VCDA-2732] Replace vsphere guest scripts execution by consolidated post boot script

### PR DESCRIPTION
**Pull request by sakthisunda**
-  Control plane node creation using consolidated post customization script
-  Currently, control plane node creation uses vsphere tools guest library. This PR replaces this logic with post guest customization script. TODO: added for upcoming tasks
- Tested with Ubuntu template and native cluster.
- Tested wait polling on customization phases. Error handling in the script: error out on first error.
- Tested with expose_ip logic with dummy values. 
- NOTE: Currently, the control_plane script is in a new bash script file. 

image
image
image

-------
kubeconfig in vm extra config
image

@arunmk @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[cluster_scripts/v2_x/control_plane_new.sh, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgHyQKJACuYIR507WMV:-MgHyQKJACuYIR507WMW:b-cogz5m) ([raw file](https://github.com/vmware/container-service-extension/blob/002248419a920041477afa377dcc66aad5d3bcbe/cluster_scripts/v2_x/control_plane_new.sh#L51)):*
> ```Shell
>     vmtoolsd --cmd "info-set guestinfo.postcustomization.kubectl.apply.weave.status in_progress"
>     export kubever=$(kubectl version --client | base64 | tr -d '\n')
>     export KUBECONFIG=/etc/kubernetes/admin.conf
> ```

This also needs to be exported into a guestinfo parameter
___
*[cluster_scripts/v2_x/control_plane_new.sh, line 63 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgHy_Wd0J83Z7ebtjln:-MgHy_Wd0J83Z7ebtjlo:b-rb08is) ([raw file](https://github.com/vmware/container-service-extension/blob/002248419a920041477afa377dcc66aad5d3bcbe/cluster_scripts/v2_x/control_plane_new.sh#L63)):*
> ```Shell
>     echo "$(date) post customization script execution completed" &>> /var/log/cse/customization/status.log
> else
>     echo "$(date) This script was called with $1" &>> /var/log/cse/customization/status.log
> ```

Nit: ideally we could just early-exit if the $1 is not "postcustomization". This will help with the logic and remove the block for default operation.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 998 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgI0m9f0KCg5gFBTc7s:-MgI0m9f0KCg5gFBTc7t:b-a5n66h) ([raw file](https://github.com/vmware/container-service-extension/blob/002248419a920041477afa377dcc66aad5d3bcbe/container_service_extension/rde/backend/cluster_service_2_x.py#L998)):*
> ```Python
>             vapp.reload()
>             # TODO: Replace this line
>             #  Use the join info from control plane vm
> ```

Nit: this needs to be RDE in the comment as we discussed. It will in any case be replaced soon, so no need to change it.

**Comment by arunmk** [comment]
:lgtm: with basic comments. Many of these issues / TODOs should be addressable by future tickets / commits.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arunmk)

___
*[cluster_scripts/v2_x/control_plane_new.sh, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgHyQKJACuYIR507WMV:-MgIrY8N7gINLVsqjr1Y:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/002248419a920041477afa377dcc66aad5d3bcbe/cluster_scripts/v2_x/control_plane_new.sh#L51)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This also needs to be exported into a guestinfo parameter
</blockquote></details>

Done.
___
*[cluster_scripts/v2_x/control_plane_new.sh, line 63 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgHy_Wd0J83Z7ebtjln:-MgIr_M-6N-IjcwLBllX:bpj63d4) ([raw file](https://github.com/vmware/container-service-extension/blob/002248419a920041477afa377dcc66aad5d3bcbe/cluster_scripts/v2_x/control_plane_new.sh#L63)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: ideally we could just early-exit if the $1 is not "postcustomization". This will help with the logic and remove the block for default operation.
</blockquote></details>

Done. Removed the redundant code

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comment

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152#-:-MgQxUWj8weg5PhDAiSo:bgl953l)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @arunmk and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2533 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgQwA_N94HPrGxSQQ4Y:-MgQwA_N94HPrGxSQQ4Z:b-83nmut) ([raw file](https://github.com/vmware/container-service-extension/blob/4730c7f15e6378bee5feef64da9a98b544edf3e1/container_service_extension/rde/backend/cluster_service_2_x.py#L2533)):*
> ```Python
>                 if expose:
>                     try:
>                         expose_ip = nw_exp_helper.expose_cluster(
> ```

Is this the boolean flag or the actual control plane IP?
If it is the actual IP, I suggest renaming it to "control_plane_vip" (or) "control_plane_public_ip"

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2533 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1152#-MgQwA_N94HPrGxSQQ4Y:-MgRKDBG67aqPakbLO1R:b-bp86iu) ([raw file](https://github.com/vmware/container-service-extension/blob/4730c7f15e6378bee5feef64da9a98b544edf3e1/container_service_extension/rde/backend/cluster_service_2_x.py#L2533)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this the boolean flag or the actual control plane IP?
If it is the actual IP, I suggest renaming it to "control_plane_vip" (or) "control_plane_public_ip"
</blockquote></details>

yes. this is a boolean flag that is just getting passed. It is not the actual IP, that is getting computed inside control plane node creation logic

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1152)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @arunmk, @sahithi, and @sakthisunda)

___
*[cluster_scripts/v2_x/control_plane_new.sh, line 1 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1152#-Mgq1Fn0A7EGfFS33dEY:-Mgq1Fn12JoKlPGXXLrC:b-ol6fh7) ([raw file](https://github.com/vmware/container-service-extension/blob/4730c7f15e6378bee5feef64da9a98b544edf3e1/cluster_scripts/v2_x/control_plane_new.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can we please name the script something other than x_new?
___
*[container_service_extension/common/constants/server_constants.py, line 203 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1152#-Mgq1Syz29i6G2uDAyk4:-Mgq1Syz29i6G2uDAyk5:b1a0a3s) ([raw file](https://github.com/vmware/container-service-extension/blob/4730c7f15e6378bee5feef64da9a98b544edf3e1/container_service_extension/common/constants/server_constants.py#L203)):*
> ```Python
>     SCRIPTS_DIR = "cluster_scripts"
>     CONTROL_PLANE = 'control_plane.sh'
>     CONTROL_PLANE_NEW = 'control_plane_new.sh'
> ```

Please rename this variable to not have  _new

**Pull request closed without merging**
