### PR TITLE
[VCDA-3330 and VCDA-3343] Install Tanzu Core packages and read versions from extra config

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
  Testing: Deployed using TKGm 1.4.1 with pods running and TKGm 1.3.0 (versions not in TKR, so successful cluster creation without core packages)

- (Optional) Names of reviewers using @ sign + name
@arunmk @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: all files reviewed, 6 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 114 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCpitSEHnANV34wd1U:-MzCpitSEHnANV34wd1V:b-uj5vhi) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L114)):*
> ```YAML
>           kubectl apply -f https://github.com/vmware-tanzu/carvel-kapp-controller/releases/download/v$OPEN_BRACKETkapp_controller_versionCLOSE_BRACKET/release.yml
> 
>           # Wait for kapp-controller to be ready for 8 minutes to be running so that tanzu cli can run
> ```

8 minutes wait time is too much in my opinion. Customers expect the entire cluster to be up in 8 minutes. We may not be yet there, but hardcoding 8 minutes is not a good idea.

How long does it take for kapp controller to come up?

If core packages installation fails for any reason, what are our steps of recommendation for the users to install core packages on any given cluster? Do they need to go to each node and install them?
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 164 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCpLtg3BSUEF5S39bo:-MzCpLtg3BSUEF5S39bp:bfc6x9s) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L164)):*
> ```YAML
>         vmtoolsd --cmd "info-set guestinfo.postcustomization.core_packages.metrics_server_version $metrics_server_version"
>       fi
>     vmtoolsd --cmd "info-set guestinfo.postcustomization.core_packages.install successful"
> ```

What happens if kappcontroller installation fails (or) tanzu-cli installation fails?  We will still end up setting "guestinfo.postcustomization.core_packages.install" extra config to "successful"?
___
*[container_service_extension/common/constants/server_constants.py, line 822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCrCrb2XmMHFuiJ-ow:-MzCrCrb2XmMHFuiJ-ox:b828mue) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/common/constants/server_constants.py#L822)):*
> ```Python
> @unique
> class PostCustomizationVersions(Enum):
>     TKR_KAPP_CONTROLLER = 'guestinfo.postcustomization.tkr.get_versions.kapp_controller'  # noqa: E501
> ```

Can you rename it to TKR_KAPP_CONTROLLER_VERSION_TO_INSTALL? same with TKR_METRICS_SERVER_VERSION_TO_INSTALL.
INSTALLED_VERSION_OF_KAPP_CONTROLLER...
It is not obvious to understand the difference between the top two and bottom two enums.
From the code, I had to infer that the control plane script is what extracts the versions and node scripts will then use the versions to install the packages. Please add a comment.

Btw, why do even we need two sets of enums? Can they ever be different versions?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2536 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCuB-21CGCI97ujyqG:-MzCuB-21CGCI97ujyqH:b-751wnq) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2536)):*
> ```Python
> 
>         installed_core_pkg_versions = {}
>         for ind in range(len(vm_specs)):
> ```

what is the full form of "ind"?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2538 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCuMTq9d08Iv7pJkgt:-MzCuMTq9d08Iv7pJkgu:b6o6cr4) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2538)):*
> ```Python
>         for ind in range(len(vm_specs)):
>             spec = vm_specs[ind]
>             # Core packages will only be installed during cluster creation
> ```

Don't we install core packages on the newer worker nodes during resize operation? Why?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2631 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCv9Bo4rT3uJ8Bv3ee:-MzCv9Bp2-3M2WMSCtL2:bnht08b) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2631)):*
> ```Python
>             # remove kubeconfig from extra config and
>             # get installed core pkg versions
>             if should_install_core_pkgs:
> ```

I assume the below piece of code gets executed for every worker node. 
That means installed_core_pkg_versions is getting overwritten for every VM. The last VM in the for loop values are the ones that get stored in the map.

I think we need to check the core packages' installation success state for each VM and then return the values if the installation is successful in all of the VMs.

I also think we may not even need to store the INSTALLED_KAPP_CONTROLLER version, instead, the success string is what would come in handy. Versions are already retrieved by the control-plane script.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: all files reviewed, 7 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1009 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCwx3yD5Xi7-Kl75EC:-MzCwx3yD5Xi7-Kl75ED:b-pnyhw0) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1009)):*
> ```Python
>                 'entity.status.cpi.version': cpi_version,
>                 'entity.status.csi': [csi_elem_rde_status_value],
>                 'entity.status.tkg_core_packages.kapp_controller': installed_kapp_controller_version,  # noqa: E501
> ```

What if the installation of these packages fails on one of the worker nodes?

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: 3 of 6 files reviewed, 14 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 192 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRW8xl33mLykp4tBK-:-MzRW8xl33mLykp4tBK0:b98dxv1) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L192)):*
> ```YAML
>       k8s_version=$(echo $init_k8s_version | tr -s "+" "_")
> 
>       # install imgpkg, which is needed for getting the components yaml file
> ```

Can we do the following before running kubeadm init:
1. download of relevant binaries
2. parsing the bom to get the versions

If there are failures here and we need to exit early, it'll help to do it before creating the control-plane node
___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 211 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRUa4T1av6RDb9eRps:-MzRUa4T1av6RDb9eRpt:b-u2j5el) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L211)):*
> ```YAML
> 
>       mv $bom_path/*.yaml $components_path
>       # install yq for yaml parsing
> ```

nit: can we comment as download instead of install
___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 231 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRUz56ByA1bkuTwBNh:-MzRUz56ByA1bkuTwBNi:bf6i94) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L231)):*
> ```YAML
>       fi
> 
>       # get kapp-controller version
> ```

Can you add a comment mentioning that we also look for kapp and metrics versions here because:
1. antrea needs to be done here
2. the other two need to be done in the worker
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 108 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRc5cB-BkA0ChsUrTY:-MzRc5cC4g_RrdoWGrXU:b-jv2812) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L108)):*
> ```YAML
>       kapp_controller_version=$(echo $kapp_controller_version | sed 's/+.*//' | sed 's/v//')
>       if [[ "$install_kapp_controller" = true ]]; then
>         vmtoolsd --cmd "info-get guestinfo.postcustomization.control_plane.kubeconfig" > $kubeconfig_path
> ```

Can we delete this variable immediately after this step so that the worker does not have this leaked.
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 143 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRcy8_-gYRGYzlA9ux:-MzRcy8_-gYRGYzlA9uy:b-qzn23k) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L143)):*
> ```YAML
>           wget https://github.com/vmware-tanzu/tanzu-framework/releases/download/v0.17.0/tanzu-cli-linux-amd64.tar.gz -O $tanzu_tar_path
>           tar -zxvf $tanzu_tar_path -C $tanzu_path
>           sudo install $OPEN_BRACKETtanzu_pathCLOSE_BRACKET/v0.17.0/tanzu-core-linux_amd64 /usr/local/bin/tanzu
> ```

I think `{{` or `\{` may just work rather than OPENBRACKET. If not, can we call this as __OPENBRACKET__ or something that is clearer?
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 171 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRcTnl8S_YBiJUmLZM:-MzRcTnl8S_YBiJUmLZN:byoauzx) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L171)):*
> ```YAML
>         fi
> 
>         rm $kubeconfig_path
> ```

We should try to put this into the error report path so that the kubeconfig is always deleted. We should also try to reset the vmtoolsd variable there itself.
___
*[container_service_extension/common/constants/server_constants.py, line 858 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRlAfr1dvfxmwUkMdy:-MzRlAfr1dvfxmwUkMdz:bce5rua) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/common/constants/server_constants.py#L858)):*
> ```Python
> # CPI/CNI/CSI constants
> CPI_NAME = "cloud-provider-for-cloud-director"
> CPI_DEFAULT_VERSION = "1.1.1"
> ```

Maybe this should come up as a separate ticket?

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: 3 of 6 files reviewed, 16 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/common/constants/server_constants.py, line 822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCrCrb2XmMHFuiJ-ow:-MzRwXaq2poczQQ4Fgca:biqv9oa) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/common/constants/server_constants.py#L822)):*
>Btw, why do even we need two sets of enums? Can they ever be different versions?
can you please answer the above?
___
*[container_service_extension/common/constants/server_constants.py, line 822 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRwOSE5TaEE3MdRy3s:-MzRwOSE5TaEE3MdRy3t:b-e9myco) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/common/constants/server_constants.py#L822)):*
> ```Python
> # TO_INSTALL versions indicate versions that the control plane node retrieved
> # for worker node(s) to install. INSTALLED_VERSION refers to the version
> # that the worker node(s) were able to install.
> ```

Can these versions ever be different - to_install and installed? In that case, why do we need two sets?
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1427 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRwr4-EHWoceFRmpzU:-MzRwr4-EHWoceFRmpzV:bxrm6o7) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1427)):*
> ```Python
>                         CorePkgVersionKeys.KAPP_CONTROLLER.value, "")
>                     if installed_kapp_controller_version:
>                         changes['entity.status.tkg_core_packages.kapp_controller'] = installed_kapp_controller_version  # noqa: E501
> ```

What if the installation of these corepackages failed for some reason? Will we be giving false impression to the users by setting the installed_*_version in the RDE?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: 2 of 6 files reviewed, 15 unresolved discussions (waiting on @arunmk and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 192 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRW8xl33mLykp4tBK-:-MzSeRlI0Eyk68DMiFtm:b-51g6kr) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L192)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we do the following before running kubeadm init:
1. download of relevant binaries
2. parsing the bom to get the versions

If there are failures here and we need to exit early, it'll help to do it before creating the control-plane node
</blockquote></details>

Done. Thanks this sounds good
___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 231 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRUz56ByA1bkuTwBNh:-MzSeqBTBy6-WgNlR_3k:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L231)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can you add a comment mentioning that we also look for kapp and metrics versions here because:
1. antrea needs to be done here
2. the other two need to be done in the worker
</blockquote></details>

Done.
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 114 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCpitSEHnANV34wd1U:-MzGlyk-9zyCC-JCymol:bip8hpv) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L114)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

8 minutes wait time is too much in my opinion. Customers expect the entire cluster to be up in 8 minutes. We may not be yet there, but hardcoding 8 minutes is not a good idea.

How long does it take for kapp controller to come up?

If core packages installation fails for any reason, what are our steps of recommendation for the users to install core packages on any given cluster? Do they need to go to each node and install them?
</blockquote></details>

Addressed offline; this is the max time out, and we will try to install kapp controller on the first worker node and install tanzu cli and metrics server on the last worker node to account for time. We will leave the timeout of 8 minutes in case the cluster only has 1 worker node. 

If core package installation fails, we can give steps to install kapp controller based on our script, but they would only need to do this once for the cluster (not on each worker node); If the cluster already has >=1 worker node, then kapp controller should be able to be installed on the control plane node
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 164 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCpLtg3BSUEF5S39bo:-MzGluDMEVVtkeKFhZbW:bkbv9rz) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L164)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What happens if kappcontroller installation fails (or) tanzu-cli installation fails?  We will still end up setting "guestinfo.postcustomization.core_packages.install" extra config to "successful"?
</blockquote></details>

Addressed offline. This phase is renamed to `attempted_install`
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 108 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRc5cB-BkA0ChsUrTY:-MzSmC3p9vyycc_w2UjR:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L108)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we delete this variable immediately after this step so that the worker does not have this leaked.
</blockquote></details>

Done.
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 143 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRcy8_-gYRGYzlA9ux:-MzSgHQMBdbCuJ4gO-xP:bvn9a7q) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L143)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think `{{` or `\{` may just work rather than OPENBRACKET. If not, can we call this as __OPENBRACKET__ or something that is clearer?
</blockquote></details>

`{{` and `\{` won't work because python will see any `{replace_variable}` pattern as something to replace and will warn that the variable is not being replaced. I have changed OPEN_BRACKET to OPENBRACKET and CLOSE_BRACKET CLOSEBRACKET
___
*[cluster_scripts/v2_x_tkgm/cloud_init_node.yaml, line 171 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRcTnl8S_YBiJUmLZM:-MzSmAhE3gsiHol43H_v:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/cluster_scripts/v2_x_tkgm/cloud_init_node.yaml#L171)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We should try to put this into the error report path so that the kubeconfig is always deleted. We should also try to reset the vmtoolsd variable there itself.
</blockquote></details>

Done.
___
*[container_service_extension/common/constants/server_constants.py, line 822 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCrCrb2XmMHFuiJ-ow:-MzGQG46-NaEnsP7HaSW:b-8yn155) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/common/constants/server_constants.py#L822)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you rename it to TKR_KAPP_CONTROLLER_VERSION_TO_INSTALL? same with TKR_METRICS_SERVER_VERSION_TO_INSTALL.
INSTALLED_VERSION_OF_KAPP_CONTROLLER...
It is not obvious to understand the difference between the top two and bottom two enums.
From the code, I had to infer that the control plane script is what extracts the versions and node scripts will then use the versions to install the packages. Please add a comment.

Btw, why do even we need two sets of enums? Can they ever be different versions?
</blockquote></details>

Done. Thank you, this is clearer, and I have added a comment

It is possible for the `TO_INSTALL` version to be different from the `INSTALLED` version. For example, control plane node can find a version for kapp controller and metrics server. If kapp controller does not install successfully, then metrics server will not be able to install. In this case INSTALLED* versions of kapp controller and metrics server will be null
___
*[container_service_extension/common/constants/server_constants.py, line 822 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRwOSE5TaEE3MdRy3s:-MzSmEwg1zvF2Nm6xzGb:b-61lssy) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/common/constants/server_constants.py#L822)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can these versions ever be different - to_install and installed? In that case, why do we need two sets?
</blockquote></details>

Yes the sets can be different, as discussed in another comment (the to_install version may not be as successful, so the installed version would be different)
___
*[container_service_extension/common/constants/server_constants.py, line 858 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRlAfr1dvfxmwUkMdy:-MzSmW-a4UfWp53FfKH6:b67u8ir) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/common/constants/server_constants.py#L858)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Maybe this should come up as a separate ticket?
</blockquote></details>

Done. will change this back to 1.1.0
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1009 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCwx3yD5Xi7-Kl75EC:-MzGROrs7nUeT0bqxjNn:b-z6vobm) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1009)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What if the installation of these packages fails on one of the worker nodes?
</blockquote></details>

The installed version will be "null" in case of failure, but cluster creation should go through
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2536 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCuB-21CGCI97ujyqG:-MzGRVq_AsNuaWMGUpvP:bagoxqv) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2536)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

what is the full form of "ind"?
</blockquote></details>

the full form is `index`
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2538 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCuMTq9d08Iv7pJkgt:-MzGRagXBui1PqLdBWA4:b-pnk0ds) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2538)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Don't we install core packages on the newer worker nodes during resize operation? Why?
</blockquote></details>

core packages only needs to be installed once for the cluster, similar to antrea
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2631 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzCv9Bo4rT3uJ8Bv3ee:-MzGku8O7yWInvMeYTRm:bshljr6) ([raw file](https://github.com/vmware/container-service-extension/blob/14cab8858604898c45a93cad37269e6efd8ab24c/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2631)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I assume the below piece of code gets executed for every worker node. 
That means installed_core_pkg_versions is getting overwritten for every VM. The last VM in the for loop values are the ones that get stored in the map.

I think we need to check the core packages' installation success state for each VM and then return the values if the installation is successful in all of the VMs.

I also think we may not even need to store the INSTALLED_KAPP_CONTROLLER version, instead, the success string is what would come in handy. Versions are already retrieved by the control-plane script.

</blockquote></details>

should_install_core_pkgs checks if this vm is the correct one to install core packages on; the current logic involves checking if the vm is the first added worker, so this will not run on every node

at this point in the code, we know that the attempted core pkg installation phase is complete. We could do your suggestion for not using INSTALLED_KAPP_CONTROLLER, but I think having the separate INSTALLED_VERSION is helpful. For example, the TKR_VERSION looks like `0.23.0-vmware...tkg.X` substring, and the worker node parses this string to get the kapp controller version from github, so the INSTALLED kapp controller version is just `0.23.0`, for example
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1427 at r5](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzRwr4-EHWoceFRmpzU:-MzSmcMA-q3kXEs3KfBg:bwh2zta) ([raw file](https://github.com/vmware/container-service-extension/blob/443f2248dedb7cd31e39337973442a122be010ac/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1427)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What if the installation of these corepackages failed for some reason? Will we be giving false impression to the users by setting the installed_*_version in the RDE?
</blockquote></details>

Addressed offline 
if the core package is not installed successfully , the versions will be set to “”, so the RDE will have  null for the version

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329)* status: 2 of 6 files reviewed, 16 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1329#-MzaZvP58zKCi3sxR64w:-MzaZvP58zKCi3sxR64x:bnfp4nl) (no related file):*
:lgtm:

---

**Review by ltimothy7 — COMMENTED** [review]
Verbal :lgtm: from @sahithi 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1329#-:-MzacOvQ7V9H4lxDyPRu:b-3zcigp)* status: 2 of 6 files reviewed, 16 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

**Pull request merged**
