### PR TITLE
[VCDA-2435] Update the RDE schema to accommodate R1

### PR DESCRIPTION
**Pull request by sahithi**
RDE 2.0 Schema changes in schema_2_0_0.json to accommodate CSE 3.1 features (CSI, CPI, TKGm integration)

Signed-off-by: sayloo <sahithi.ayloo@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040#-:-MaXRDdG0UgmBpAFDxE4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/common/constants/shared_constants.py, line 35 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaXQuwC7HqSp27CJ5Lc:-MaXQuwD0sk-SnEmvSYy:blgxsxe) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/container_service_extension/common/constants/shared_constants.py#L35)):*
> ```Python
>     TKG = 'TanzuKubernetesCluster'
>     TKG_PLUS = 'TKG+'
>     TKGm = 'TKGm'
> ```

TKG_M = 'TKGm'?

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)

___
*[cse_def_schema/schema_2_0_0.json, line 231 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZcpXw8ZznshkMYxRR:-MaZcpXw8ZznshkMYxRS:bfli4pc) ([raw file](https://github.com/vmware/container-service-extension/blob/5ed118ebc2499a89dc3e718a1997ea15c4a8d41d/cse_def_schema/schema_2_0_0.json#L231)):*
> ```JSON
>                 },
>                 "cni":{
>                     "type":"string"
> ```

Will this also include the CNI version?

**Comment by arunmk** [comment]
:lgtm:

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[cse_def_schema/schema_2_0_0.json, line 107 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZeu0GBEsapMnaZpD5:-MaZeu0GBEsapMnaZpD6:b-ipsyic) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L107)):*
> ```JSON
>                                     "type":"integer",
>                                     "description":"Worker nodes can be scaled up and down.",
>                                     "maximum":100,
> ```

Can we relax this maximum and make it more like 200?
___
*[cse_def_schema/schema_2_0_0.json, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZf0k57XSPXfogW-E-:-MaZf0k57XSPXfogW-E0:b-w3o0gr) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L131)):*
> ```JSON
>                                     "type":"integer",
>                                     "description":"Nfs nodes can only be scaled-up; they cannot be scaled-down.",
>                                     "maximum":100,
> ```

This will also potentially need to match the worker node count if that's increased.
___
*[cse_def_schema/schema_2_0_0.json, line 245 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZf9YO94yFmaHyLiJX:-MaZf9YO94yFmaHyLiJY:b-6h0mvg) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L245)):*
> ```JSON
>                     ],
>                     "properties":{
>                         "controlPlane":{
> ```

This needs to be an array for multi-master. We will also need a controlPlaneIP outside this which will represent the VIP in multimaster, and a copy of the control plane IP in single-master.
___
*[cse_def_schema/schema_2_0_0.json, line 307 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZfYQ_BV6eEmQZDive:-MaZfYQ_BV6eEmQZDivf:bbniwy4) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L307)):*
> ```JSON
>                     "additionalProperties":true
>                 },
>                 "private": {
> ```

For AuthZ/N, we will need:
1. machineUserToken as a private string

Pinniped stuff we can consider as a Kubernetes application and not include it here.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1040)* status: 0 of 2 files reviewed, 5 unresolved discussions

___
*[cse_def_schema/schema_2_0_0.json, line 107 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZeu0GBEsapMnaZpD5:-Ma_Z8Ka5erFZ2jpsWjQ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L107)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Can we relax this maximum and make it more like 200?
</blockquote></details>

Done.
___
*[cse_def_schema/schema_2_0_0.json, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZf0k57XSPXfogW-E-:-Ma_Z8lvD8VIdtBwAMzF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L131)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This will also potentially need to match the worker node count if that's increased.
</blockquote></details>

Done.
___
*[cse_def_schema/schema_2_0_0.json, line 245 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZf9YO94yFmaHyLiJX:-Ma_YyRcDoLhB9scvk6G:b-owrze7) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L245)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This needs to be an array for multi-master. We will also need a controlPlaneIP outside this which will represent the VIP in multimaster, and a copy of the control plane IP in single-master.
</blockquote></details>

As discussed, this is out of the scope of R1, leaving as-is
___
*[cse_def_schema/schema_2_0_0.json, line 307 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZfYQ_BV6eEmQZDive:-Ma_Z1WP7aiIf2Qv_Ws_:b-1qz8iw) ([raw file](https://github.com/vmware/container-service-extension/blob/0f0c386355bbb68b59bb0fd42191db9c9df30c3f/cse_def_schema/schema_2_0_0.json#L307)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

For AuthZ/N, we will need:
1. machineUserToken as a private string

Pinniped stuff we can consider as a Kubernetes application and not include it here.
</blockquote></details>

Same here, not adding machinUserToken for now.
___
*[cse_def_schema/schema_2_0_0.json, line 231 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1040#-MaZcpXw8ZznshkMYxRR:-Ma_YukN-z4AKOIOfMrs:beqb55j) ([raw file](https://github.com/vmware/container-service-extension/blob/5ed118ebc2499a89dc3e718a1997ea15c4a8d41d/cse_def_schema/schema_2_0_0.json#L231)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Will this also include the CNI version?
</blockquote></details>

As discussed offline, leaving it as-is .

**Pull request merged**
