### PR TITLE
VCDA-2786: remaining CR of Aritra and Sakthi

### PR DESCRIPTION
**Pull request by arunmk**
- Took in remaining CR comments of the clusterservice_2_x_tkgm.py
- There was a slight issue while testing unexpose of exposed cluster. Fixed it for TKGm. Same issue lies in native as well.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1195)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @rocknes)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 6 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1195#-MjeTq_64epv_WMekgHz:-MjeTq_64epv_WMekgI-:bqtwb1x) ([raw file](https://github.com/vmware/container-service-extension/blob/866111a0b683891271947cc12336164f95c92e33/cluster_scripts/v2_x_tkgm/control_plane.sh#L6)):*
> ```
>    vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_status $?"
>    vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"
> ```
vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"   
vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_status $?"
   
Recording execution status after recording error message would be ideal for the CSE code not to loose the error message.

**Review by sakthisunda — COMMENTED** [review]
minor comment

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1195#-:-MjecseFEyf1yzSd1eVK:bvlr5zj)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk and @rocknes)

**Comment by arunmk** [comment]
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 6 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1195#-MjeTq_64epv_WMekgHz:-Mjgu02NCs4WLgiV_HIq:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/866111a0b683891271947cc12336164f95c92e33/cluster_scripts/v2_x_tkgm/control_plane.sh#L6)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
>    vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_status $?"
>    vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"
> ```
vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"   
vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_status $?"
   
Recording execution status after recording error message would be ideal for the CSE code not to loose the error message.
</blockquote></details>

Done

**Pull request merged**
