### PR TITLE
[VCDA-2304] change model classes to use snake case instead of camel case

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Include changes to use dataclasses_json
* Changed rde_1_0_0 to also use dataclasses_json

Testing done
* Cluster list
* cluster create
* cluster resize 
* cluster upgrade
* cluster info

@rocknes @arunmk @sakthisunda @sahithi @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/common/entity_service.py, line 330 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXiCi7S1eWVnQOKl014:-MXiCi7S1eWVnQOKl015:bk70zcy) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/common/entity_service.py#L330)):*
> ```Python
> 
>         :param str entity_id: Id of the entity
>         :param str entity_type_id:
> ```

Missing description of variable

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1169 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjHzceDDHIhSk_ELxo:-MXjHzceDDHIhSk_ELxp:b-8tl2p) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x.py#L1169)):*
> ```Python
>                 _join_cluster(self.context.sysadmin_client,
>                               vapp,
>                               target_nodes=target_nodes)
> ```

Why did these lines change? Bad merge?
___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1143 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjI5sc9-R7Dnt5zCr7:-MXjI5sc9-R7Dnt5zCr8:b-72i198) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1143)):*
> ```Python
>                 _join_cluster(self.context.sysadmin_client,
>                               vapp,
>                               target_nodes=target_nodes)
> ```

Same as above. These are needed in the scripts.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: 14 of 19 files reviewed, 3 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1169 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjHzceDDHIhSk_ELxo:-MXmQiT11GJwRDLKw1oG:b-fxmbf8) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x.py#L1169)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Why did these lines change? Bad merge?
</blockquote></details>

The parameters were unused in the function _join_cluster(). I can add them back if the parameters are necessary for future.
___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1143 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjI5sc9-R7Dnt5zCr7:-MXmQtli2gVe2hKGheuu:bl6h5yw) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1143)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Same as above. These are needed in the scripts.
</blockquote></details>

I will add the parameters back. I removed them since it was not used in _join_cluster()
___
*[container_service_extension/rde/common/entity_service.py, line 330 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXiCi7S1eWVnQOKl014:-MXmRIKl1FVVw501Cvzn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/common/entity_service.py#L330)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Missing description of variable
</blockquote></details>

Done.

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: 14 of 19 files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1169 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjHzceDDHIhSk_ELxo:-MXmYezADvXCX-ZVLXkI:b-375p4z) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x.py#L1169)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

The parameters were unused in the function _join_cluster(). I can add them back if the parameters are necessary for future.
</blockquote></details>

OK, I thought they were used for some reason. No need to add it if they are not used. Sorry about the alarm.

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 1143 at r1](https://reviewable.io/reviews/vmware/container-service-extension/990#-MXjI5sc9-R7Dnt5zCr7:-MXmYoDd0iu-H9XkzYmR:b8l2fau) ([raw file](https://github.com/vmware/container-service-extension/blob/5f85f4d7e730e3a072da01d18c44428cae2f12da/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L1143)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I will add the parameters back. I removed them since it was not used in _join_cluster()
</blockquote></details>

No need if they were not used. Sorry about the alarm

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 19 files at r1, 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990#-:-MYcoGqh18NjUvR2euEt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/installer/configure_cse.py, line 2428 at r2](https://reviewable.io/reviews/vmware/container-service-extension/990#-MYch_IY1BB_g0gnbWt0:-MYch_IZ2jIWzRzb_A6y:b-6ei9f1) ([raw file](https://github.com/vmware/container-service-extension/blob/7bb82b836c4ac7fca20ba85dcbcd5e8054ca768e/container_service_extension/installer/configure_cse.py#L2428)):*
> ```Python
>             semantic_version.Version(def_constants.RDEVersion.RDE_2_0_0).major:
>         # RDE upgrade possible only from RDE 1.0 or RDE 2.x
>         native_entity_2_x: rde_2_x.NativeEntity = new_native_entity
> ```

This style of imported package is so hard to read :|
It took me a good 5 min of reading to realize that rde_2_x is a package.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 87 at r2](https://reviewable.io/reviews/vmware/container-service-extension/990#-MYcnzDDAB3P0DAk1YLO:-MYcnzDE9Zn80qH7iQoS:b356olv) ([raw file](https://github.com/vmware/container-service-extension/blob/cd01f255fdf47010da593092393f09cd41f7fa32/container_service_extension/rde/validators/validator_rde_2_x.py#L87)):*
> ```Python
> 
>         # TODO check the reason why there was an unreachable raise statement
>         raise NotImplementedError(f"Validator for {operation.name} not found")
> ```

The return statement above relinquishes control from the method .. so this line will never be executed.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/990)* status: 16 of 22 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 87 at r2](https://reviewable.io/reviews/vmware/container-service-extension/990#-MYcnzDDAB3P0DAk1YLO:-MYg5FITArR93lQktZFf:bw8x8fn) ([raw file](https://github.com/vmware/container-service-extension/blob/cd01f255fdf47010da593092393f09cd41f7fa32/container_service_extension/rde/validators/validator_rde_2_x.py#L87)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The return statement above relinquishes control from the method .. so this line will never be executed.
</blockquote></details>

I think the return should have been inside the if statement. I have corrected that. Thanks for catching this.

**Pull request merged**
