### PR TITLE
Porting [VCDA-2530] RDE cluster tests to cse_3_1_updates

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

Added tests for the following:
* cluster apply
* cluster delete nfs
* cluster delete
* cluster info
* cluster list

@rocknes @sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1194)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1194)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1194)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[system_tests_v2/test_cse_client.py, line 446 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1194#-Mj_yQn32v4JrS4IQbfY:-Mj_yQn32v4JrS4IQbfZ:b-cup5sl) ([raw file](https://github.com/vmware/container-service-extension/blob/bdcbf78ffa2bccc0ab5f57a46934405069917e33/system_tests_v2/test_cse_client.py#L446)):*
> ```Python
>     - worker count
>     - nfs count
>     - tempalte name
> ```

nit:template name

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1194#-:-Mk7kPIA0IVXFBS6Ot9l:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[system_tests_v2/test_cse_client.py, line 629 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1194#-Mk7kA_PDCEppVHG-95s:-Mk7kA_PDCEppVHG-95t:b-ko1klu) ([raw file](https://github.com/vmware/container-service-extension/blob/bdcbf78ffa2bccc0ab5f57a46934405069917e33/system_tests_v2/test_cse_client.py#L629)):*
> ```Python
>             [
>                 env.SYS_ADMIN_NAME,
>                 # env.CLUSTER_ADMIN_NAME,
> ```

Is this intentionally commented?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1194)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @sahithi and @sakthisunda)

___
*[system_tests_v2/test_cse_client.py, line 629 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1194#-Mk7kA_PDCEppVHG-95s:-MkiANRhDAAamv9QDJJ1:b-q52m3v) ([raw file](https://github.com/vmware/container-service-extension/blob/bdcbf78ffa2bccc0ab5f57a46934405069917e33/system_tests_v2/test_cse_client.py#L629)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this intentionally commented?
</blockquote></details>

Uncommented this part

**Pull request merged**
