### PR TITLE
VCDA-608 & VCDA-609: Enhance cluster and node commands to support NFS

### PR DESCRIPTION
**Pull request by sahithi**
1. Enhanced 'cse cluster create' command to support NFS - Add NFS node once cluster is created.
2. Modified 'cse cluster info' to display details of NFS nodes as well.
3. Created a new command 'cse node info' for all types of nodes. For NFS nodes, this displays NFS server IP and exports.

Command output

$ vcd cse cluster create haloCluster -N 1 -n TestbedPG -t ubuntu-16.04 --enable-nfs
>create_cluster: Creating cluster haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Creating cluster vApp haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Creating master node for haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Initializing cluster haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Creating 1 node(s) for haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Adding 1 node(s) to haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
create_cluster: Creating NFS node for haloCluster(529f49ba-792d-49d1-9936-4561a7866e62)
task: 5a4bff9f-6034-4678-a56a-d749399acbf2, Created cluster haloCluster(529f49ba-792d-49d1-9936-4561a7866e62), result: success

$vcd cse cluster info haloCluster
>property         value
>======        =========
>cluster_id       529f49ba-792d-49d1-9936-4561a7866e62
>leader_endpoint  10.150.211.79
>master_nodes     {'name': 'mstr-xu9j', 'ipAddress': '10.150.211.79'}
>name             haloCluster
>nfs_nodes        {'name': 'nfsd-ywzv', 'ipAddress': '10.150.211.68'} {'name': 'nfsd-zfpn', 'ipAddress': '10.150.211.81'}
>nodes            {'name': 'node-ekzz', 'ipAddress': '10.150.211.80'}
>number_of_vms    4
>status
>template         ubuntu-16.04
>vapp_href        https://10.150.198.116/api/vApp/vapp-c2434f3e-06a5-45b5-a287-4db2d29cda1c
>vapp_id          c2434f3e-06a5-45b5-a287-4db2d29cda1c
vdc_href         https://10.150.198.116/api/vdc/c3060f65-9548-4ec0-8545-b36fc344270c
vdc_name         cseOvdc

$vcd cse node info haloCluster nfsd-ywzv
>property              value
>========         =============
>exports               /var/nfs/general
                           /home
>ipAddress         10.150.211.68
>memoryMB       2048
>name                  nfsd-ywzv
>node_type         nfsd
>numberOfCpus 2
>status                Powered on

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Overall looks good.  In general this code needs more comments so it's easier to read.  For now I think we need docstrings on API calls as noted elsewhere. 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[container_service_extension/broker.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/81#-LBwi2ZwDsEvQO-KeMqp:-LBwi2ZxBWqHy4X35zHf:bmdzfy) ([raw file](https://github.com/vmware/container-service-extension/blob/56b0eb0380b253d5062893357fa2655bdccfce8e/container_service_extension/broker.py#L325)):*
> ```Python
>         return result
> 
>     def get_cluster_info(self, name, headers, body):
> ```

This and other calls that implement public API functions should have docstrings.  The docstring on get_node_info is very helpful; would like to have the same elsewhere.   

I suggest adding them at least incrementally to any function you touch.  Otherwise it's difficult to understand whether the code is implementing the API correctly. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81#-:-LBwkXm58voTtmXyz6Wx:b-evesvi)*

**Comment by pacogomez** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/nfsd-ubuntu-16.04.sh, line 6 at r1](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDHP69g9fsOGDNg3gsD:-LDHP69g9fsOGDNg3gsE:b-x9pyn9) ([raw file](https://github.com/vmware/container-service-extension/blob/56b0eb0380b253d5062893357fa2655bdccfce8e/scripts/nfsd-ubuntu-16.04.sh#L6)):*
> ```Shell
> systemctl enable nfs-kernel-server.service
> systemctl start nfs-kernel-server.service
> echo '/home *(rw,sync,no_root_squash,no_subtree_check)' >> /etc/exports
> ```

is there any reason for using `/home` and not other directory to export?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/nfsd-ubuntu-16.04.sh, line 6 at r1](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDHP69g9fsOGDNg3gsD:-LDHh--Y1nA1DaXECJRm:bb1xyjp) ([raw file](https://github.com/vmware/container-service-extension/blob/56b0eb0380b253d5062893357fa2655bdccfce8e/scripts/nfsd-ubuntu-16.04.sh#L6)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

is there any reason for using `/home` and not other directory to export?
</blockquote></details>

Usually user directories are in home, that is the reason I used home. We can always change the default to something else now or later.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[container_service_extension/broker.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/81#-LBwi2ZwDsEvQO-KeMqp:-LDI1Gak6Wn3k6ES222O:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/56b0eb0380b253d5062893357fa2655bdccfce8e/container_service_extension/broker.py#L325)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

This and other calls that implement public API functions should have docstrings.  The docstring on get_node_info is very helpful; would like to have the same elsewhere.   

I suggest adding them at least incrementally to any function you touch.  Otherwise it's difficult to understand whether the code is implementing the API correctly. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[container_service_extension/broker.py, line 548 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDbF4r47rsRhRG0qHeW:-LDbF4r47rsRhRG0qHeX:b-mguuwk) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/broker.py#L548)):*
> ```Python
>                 vapp.reload()
>                 join_cluster(self.config, vapp, template)
>             if self.body['enable_nfs'] == True:
> ```

Could this be safely represented as `if self.body[`enable_nfs']:`?

---

*[container_service_extension/processor.py, line 67 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDbGDrQ5LzyN0jr-EkJ:-LDbGDrQ5LzyN0jr-EkK:b-m636e8) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/processor.py#L67)):*
> ```Python
>             if node_name is not None:
>                 if tokens[5] == 'info':
>                     node_info_request = True
> ```

Can this be done with a single `if` statement?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
please see comments and use `vsphere-guest-run` API to talk to the nodes

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81#-:-LDbHZau5_PA9BVMMZPH:b-acz5te)*

**Comment by sahithi** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[container_service_extension/broker.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/81#-LBwi2ZwDsEvQO-KeMqp:-LEFdmBHESRD16Dc2w6-:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/56b0eb0380b253d5062893357fa2655bdccfce8e/container_service_extension/broker.py#L325)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[container_service_extension/broker.py, line 11 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDTl2yY5fgo6QlCqwHC:-LEFdkyf82yxGV3TwebT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/broker.py#L11)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

not needed, see note below
</blockquote></details>

Done.

---

*[container_service_extension/broker.py, line 428 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDTgqb6AmU_FMhU-qX8:-LEFdoDn1zJG_ICTkSiK:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/broker.py#L428)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

One can't assume CSE server has IP connectivity to the NFS server on the tenant network. Please use the `vsphere-guest-run` library to run commands on the guest OS as done in other parts of CSE. You could run directly the command on the NFS server (preferred) or on the master node.
</blockquote></details>

Done.

---

*[container_service_extension/broker.py, line 548 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDbF4r47rsRhRG0qHeW:-LEFs4Sl1Kp4vmvaiCfs:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/broker.py#L548)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Could this be safely represented as `if self.body[`enable_nfs']:`?
</blockquote></details>

Done.

---

*[container_service_extension/processor.py, line 67 at r2](https://reviewable.io/reviews/vmware/container-service-extension/81#-LDbGDrQ5LzyN0jr-EkJ:-LEFw6jn01KEjtQCbS1w:b-dm1vfx) ([raw file](https://github.com/vmware/container-service-extension/blob/8df948ce6370890242142790f012426a959c26b9/container_service_extension/processor.py#L67)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Can this be done with a single `if` statement?
</blockquote></details>

This if block style lets developers to add more commands to the NODE in future. I have followed the same 'if block style' as other commands.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81)*

**Comment by pacogomez** [comment]
:lgtm: except for some minor changes. Please also update the `README.md` file to include the changes introduced.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[container_service_extension/broker.py, line 446 at r3](https://reviewable.io/reviews/vmware/container-service-extension/81#-LEQYQqc9VCNt9Ri7dqT:-LEQYQqc9VCNt9Ri7dqU:b-76cem4) ([raw file](https://github.com/vmware/container-service-extension/blob/1a899692973c2b5f587b30081fb5432513700b27/container_service_extension/broker.py#L446)):*
> ```
> ' + '
> ```
this can be in the same in the same string and the concatenation is not needed

---

*[container_service_extension/cluster.py, line 340 at r3](https://reviewable.io/reviews/vmware/container-service-extension/81#-LEQ_4fA9DLBTZ0ITnOm:-LEQ_4fA9DLBTZ0ITnOn:b-c563lo) ([raw file](https://github.com/vmware/container-service-extension/blob/1a899692973c2b5f587b30081fb5432513700b27/container_service_extension/cluster.py#L340)):*
> ```Python
>     all_results = []
>     for node in nodes:
>         print("inside execute script" + node.get('name'))
> ```

need to use `LOGGER.debug` instead of `print`

---

*[container_service_extension/config.py, line 341 at r3](https://reviewable.io/reviews/vmware/container-service-extension/81#-LEQ_AlZDvokMA2JPbX4:-LEQ_AlZDvokMA2JPbX5:b-c563lo) ([raw file](https://github.com/vmware/container-service-extension/blob/1a899692973c2b5f587b30081fb5432513700b27/container_service_extension/config.py#L341)):*
> ```Python
>     cse_cache_dir = os.path.join(os.getcwd(), 'cse_cache')
>     cse_ova_file = os.path.join(cse_cache_dir, template['source_ova_name'])
>     print(cse_ova_file)
> ```

need to use `LOGGER.debug` instead of `print`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81#-:-LEQ_Jqz1m2pU13jOjRI:b-j2q25l)*

**Comment by sahithi** [comment]
I am going to edit the README.md in a separate task describing the NFS architecture and the usage

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[container_service_extension/broker.py, line 446 at r3](https://reviewable.io/reviews/vmware/container-service-extension/81#-LEQYQqc9VCNt9Ri7dqT:-LEQsL9pC1Qtu_CTxqjc:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/1a899692973c2b5f587b30081fb5432513700b27/container_service_extension/broker.py#L446)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

> ```
> ' + '
> ```
this can be in the same in the same string and the concatenation is not needed
</blockquote></details>

Done.

---

*[container_service_extension/cluster.py, line 340 at r3](https://reviewable.io/reviews/vmware/container-service-extension/81#-LEQ_4fA9DLBTZ0ITnOm:-LEQsLnq6FSbTZwSAoJn:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/1a899692973c2b5f587b30081fb5432513700b27/container_service_extension/cluster.py#L340)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

need to use `LOGGER.debug` instead of `print`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/81#-:-LEQsSVPBKB4F_UlHhws:b-6o69ah)*

**Pull request merged**
