### PR TITLE
[VCDA-2525] Disallow cluster sharing for TKGm clusters

### PR DESCRIPTION
**Pull request by sakthisunda**
- Disallow cluster share operation for TKGm
- Server side handling 
- Client side handling if cluster kind is explicitly provided by the user
- Tested with RDE with cluster kind TKGm
- Tested with newly created TKGm cluster using tip of CSE_3_1_UPDATES

image

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1183)

@Anirudh9794 @ltimothy7

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1183)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 239 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1183#-MjB8nGV5giyp4eZNuYw:-MjB8nGW79gfAm53GNWJ:b-1qebas) ([raw file](https://github.com/vmware/container-service-extension/blob/73b709f6b5028f43b76fa30d3ace1c08181b169b/container_service_extension/rde/utils.py#L239)):*
> ```Python
> 
> 
> def raise_error_if_unsupported_cluster_operation(cluster_kind: str):
> ```

could this function be renamed to something TKGm specific since only TKGm is unsupported here?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1183)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/rde/utils.py, line 239 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1183#-MjB8nGV5giyp4eZNuYw:-MjUxv3h8PzMUduTjnUB:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/73b709f6b5028f43b76fa30d3ace1c08181b169b/container_service_extension/rde/utils.py#L239)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

could this function be renamed to something TKGm specific since only TKGm is unsupported here?
</blockquote></details>

Done.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1183)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/client/cluster_commands.py, line 1212 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1183#-Mj_koRzBPaT51HgkM3o:-Mj_koS-CPh5E3rXiw5z:bnuymsv) ([raw file](https://github.com/vmware/container-service-extension/blob/9f85684762fb276ab78dccfec6f345b4f3e37cbe/container_service_extension/client/cluster_commands.py#L1212)):*
> ```Python
>             raise Exception("Need to specify cluster org since logged in user is in system org")  # noqa: E501
> 
>         # If cluster kind is not specified, let the server handle this check
> ```

Should we do this check at the very beginning of the function?

**Pull request merged**
