### PR TITLE
[VCDA-2222, VCDA-2066] Remove use of api version from server config file and update operation context to support clients at multiple api versions

### PR DESCRIPTION
**Pull request by rocknes**
Removed use of 'api_version' from server config.
Removed all ui plugin related code
Fixed sample generation to populate the value of 'legacy_mode' correctly.
Cleaned up utils methods and their doc strings.
Operation Context has been reworked to cache not only the client(+sys admin client) with CSE server's default api version, but also any other client at a user requested api version.
Changes in all backend code that used operation context, to use the clients at  appropriate api versions.

Misc:
Added type hinting where ever possible
Fixed most of pycharm raised issues in the files that were touched by this PR

Testing:
ToDo

This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/server/cli/server_cli.py, line 1256 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYlzHEF7aLXtglUjnId:-MYlys6k09_z9M-geqF6:b-a7jgej) ([raw file](https://github.com/vmware/container-service-extension/blob/5d4e82262e3748894dbc28d02d3398a6c4c4a070/container_service_extension/server/cli/server_cli.py#L1256)):*
> ```Python
> def _get_clients_from_config(config, log_wire_file, log_wire):
>     client = vcd_client.Client(
>         config['vcd']['host'],
> ```

Does vcd_client uses highest api version if  api_version is not specified?

**Review by rocknes — COMMENTED** [review]
> Reviewed 9 of 13 files at r1, 19 of 19 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/server/cli/server_cli.py, line 1256 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYlzHEF7aLXtglUjnId:-MYnbnXo9FNHDrr34buE:b-em4sze) ([raw file](https://github.com/vmware/container-service-extension/blob/5d4e82262e3748894dbc28d02d3398a6c4c4a070/container_service_extension/server/cli/server_cli.py#L1256)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Does vcd_client uses highest api version if  api_version is not specified?
</blockquote></details>

Yes, if api_version is specified as None or left empty, pyvcloud auto negotiates the api version to the max of what pyvcloud and VCD can support.

In this particular case, we really don't care much about the api version since we are not doing any CSE specific oepration, we are just looking for catalog items.

**Review by rocknes — COMMENTED** [review]
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, @ltimothy7, @sahithi, and @sakthisunda)

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: all files reviewed, 12 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 50 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYpokNO-xoyKxW1WeIP:-MYpokNO-xoyKxW1WeIQ:bnxnuok) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/common/utils/pyvcloud_utils.py#L50)):*
> ```Python
>         is_jwt_token: bool,
>         api_version: Optional[str]):
>     server_config = get_server_runtime_config()
> ```

Just thinking out loud here - Is it a good idea to assume that CSE server is running in the context of pyvcloud_utils?
___
*[container_service_extension/installer/config_validator.py, line 243 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYplECL4hR8PG0iXZik:-MYplECL4hR8PG0iXZil:bld8qga) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/installer/config_validator.py#L243)):*
> ```Python
> 
>     max_vcd_api_version_supported = get_max_api_version(config['service']['supported_api_versions'])  # noqa: E501
>     config['vcd']['default_api_version'] = str(max_vcd_api_version_supported)
> ```

I am loosing track of what derived keys are present. I think it is better to add this information in the doc string. Also I think this method is doing more than just validation and can be split up.
___
*[container_service_extension/installer/sample_generator.py, line 300 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYpzMQpANuqGToLvonj:-MYpzMQpANuqGToLvonk:bmksmqw) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/installer/sample_generator.py#L300)):*
> ```Python
> 
> def generate_sample_config(output=None, generate_pks_config=False,
>                            api_version=MQTT_MIN_API_VERSION):
> ```

I think api_version should be made a required param. The default param value doesn't make sense to me
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 56 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq0DbJ2AwJo2CN4ORy:-MYq0DbJ2AwJo2CN4ORz:b-5d1uka) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L56)):*
> ```Python
> import container_service_extension.server.compute_policy_manager as compute_policy_manager  # noqa: E501
> 
> DEFAULT_API_VERSION = vcd_client.ApiVersion.VERSION_35.value
> ```

I didn't get the actual reason why we are keeping a default api version in cluster_service_* files.
Won't the functions like `op_ctx.get_*_client` return the client in the highest supported API version?
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 72 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq1bxhBX2rwkykzKug:-MYq1bxhBX2rwkykzKuh:b-vwt3rf) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L72)):*
> ```Python
>         self.task_resource = None
>         self.task_update_lock = threading.Lock()
>         cloudapi_client_v35 = \
> ```

I also disagree with associating api versions with the client names because the reader may assume that a cluster_service_x module is tied to a particular api version but a ClusterService module may service requests associated with more than one api version.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 1666 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq16yv1Pb47kIjCJZ6:-MYq16yv1Pb47kIjCJZ7:b923lza) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L1666)):*
> ```Python
> 
> 
> def _get_cluster_upgrade_plan(source_template_name,
> ```

`_get_template_upgrade_targets` makes more sense to me because `_get_cluster_upgrade_plan` seems like a function which should be associated with ClusterService
___
*[container_service_extension/security/context/operation_context.py, line 79 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqBvxK6iT0mAa4Bv1u:-MYqBvxK6iT0mAa4Bv1v:b-zcq3vy) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/security/context/operation_context.py#L79)):*
> ```Python
> 
>     def _update_user_context_map(self, api_version: Optional[str]):
>         _client = vcd_utils.connect_vcd_user_via_token(
> ```

Can we add a comment saying that None will be mapped to the highest api version available?
___
*[container_service_extension/security/context/user_context.py, line 94 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqFzQA774KDimr9TvF:-MYqFzQA774KDimr9TvG:b-3814cn) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/security/context/user_context.py#L94)):*
> ```Python
>                 logger.SERVER_LOGGER.debug(msg, exc_info=True)
> 
>         return self._rights
> ```

If User cannot access the rights, exception will be thrown only when rights is accessed for the first time. I think it is better to record the exception every time the property `rights` is accessed
___
*[container_service_extension/server/request_handlers/legacy/ovdc_handler.py, line 38 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqJIBvD82bM-JvkDl6:-MYqJIBvD82bM-JvkDl7:b-573bj2) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/legacy/ovdc_handler.py#L38)):*
> ```Python
> import container_service_extension.server.request_handlers.request_utils as req_utils  # noqa: E501
> 
> DEFAULT_API_VERSION = vcd_client.ApiVersion.VERSION_33.value
> ```

I agree with having a default api version for legacy handlers.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 37 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqHcj7Ahuru8V1OQDj:-MYqHcj7Ahuru8V1OQDk:b-i9xu2x) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L37)):*
> ```Python
> 
>     # Validate the input
>     # ToDo: Should hte validation be done using a v36 client?
> ```

nit: the*
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 152 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqHmBz1WqkcI1n8ekZ:-MYqHmBz1WqkcI1n8ek_:bxs36yb) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L152)):*
> ```Python
> 
>     # Validate the input
>     # ToDo: Should hte validation be done using a v36 client?
> ```

nit: the*

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: 20 of 33 files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 50 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYpokNO-xoyKxW1WeIP:-MZH4QlW2zfYezwJnXUM:b-z08k2p) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/common/utils/pyvcloud_utils.py#L50)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just thinking out loud here - Is it a good idea to assume that CSE server is running in the context of pyvcloud_utils?
</blockquote></details>

Ideally not. But what option do we have here. 
I would like the utility files been grouped into modules, where one module guarantees the server is up while the other assumes the server isn't up.

Our util methods are not really well organized, maybe a good tech debt task for next release.
___
*[container_service_extension/installer/config_validator.py, line 243 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYplECL4hR8PG0iXZik:-MZH7OXs0x8uesREEQ1_:bvljs2o) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/installer/config_validator.py#L243)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I am loosing track of what derived keys are present. I think it is better to add this information in the doc string. Also I think this method is doing more than just validation and can be split up.
</blockquote></details>

Addressed.
___
*[container_service_extension/installer/sample_generator.py, line 300 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYpzMQpANuqGToLvonj:-MZH9Cu53Jt9Qf1ij9vt:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/installer/sample_generator.py#L300)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think api_version should be made a required param. The default param value doesn't make sense to me
</blockquote></details>

done
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 56 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq0DbJ2AwJo2CN4ORy:-MZH9Kq1CThAJGrrR0pF:btykj6f) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L56)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I didn't get the actual reason why we are keeping a default api version in cluster_service_* files.
Won't the functions like `op_ctx.get_*_client` return the client in the highest supported API version?
</blockquote></details>

We don't want to select arbitrary api version in these files. We want a very specific api version to be chosen to communicate with vCD, the exact same one that we use during development.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 72 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq1bxhBX2rwkykzKug:-MZH9c8h75l0Jp8eFKAr:boylpvh) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L72)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I also disagree with associating api versions with the client names because the reader may assume that a cluster_service_x module is tied to a particular api version but a ClusterService module may service requests associated with more than one api version.
</blockquote></details>

As discussed offline, as we build more feature into these service files based on newer api versions, we will start seeing more api versions being referenced in this file. For the time being these service files have been developed against only one api version of vCD and hence they should only refer to the api version that we have tested against.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 1666 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYq16yv1Pb47kIjCJZ6:-MZHAX4c8djDTiL5cRpg:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/rde/backend/cluster_service_1_x.py#L1666)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`_get_template_upgrade_targets` makes more sense to me because `_get_cluster_upgrade_plan` seems like a function which should be associated with ClusterService
</blockquote></details>

done
___
*[container_service_extension/security/context/operation_context.py, line 79 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqBvxK6iT0mAa4Bv1u:-MZHB2frB_suKwJpwgrh:bwg084a) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/security/context/operation_context.py#L79)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we add a comment saying that None will be mapped to the highest api version available?
</blockquote></details>

Added a comment in the __init__ section
___
*[container_service_extension/security/context/user_context.py, line 94 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqFzQA774KDimr9TvF:-MZHBJ4g32b0uZbISOiP:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/security/context/user_context.py#L94)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If User cannot access the rights, exception will be thrown only when rights is accessed for the first time. I think it is better to record the exception every time the property `rights` is accessed
</blockquote></details>

done
___
*[container_service_extension/server/request_handlers/legacy/ovdc_handler.py, line 38 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqJIBvD82bM-JvkDl6:-MZHBMAoCfS4cn0DRQBp:bb6mt9b) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/legacy/ovdc_handler.py#L38)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I agree with having a default api version for legacy handlers.
</blockquote></details>

:+1:
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 37 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqHcj7Ahuru8V1OQDj:-MZHBntM7yTOZOpl3u-V:b-7ql1td) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L37)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nit: the*
</blockquote></details>

fixed
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 152 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MYqHmBz1WqkcI1n8ekZ:-MZHBobk9pEYzrX6b7f_:b-7ql1td) ([raw file](https://github.com/vmware/container-service-extension/blob/674e00e11c06c056f41344493cb3945d70a27329/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L152)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

nit: the*
</blockquote></details>

fixed

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r5, 12 of 12 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014#-:-MZJV16I8fDBiH4VG8Ey:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/security/context/operation_context.py, line 132 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MZJSzpE4684caIwKQpf:-MZJSzpE4684caIwKQpg:b-t9fyhs) ([raw file](https://github.com/vmware/container-service-extension/blob/dbf13d15c263537d8bc6dca30f3a235748a00bab/container_service_extension/security/context/operation_context.py#L132)):*
> ```Python
>                 msg = f"Failed to logout user: {sysadmin_user_context.name}" \
>                     f"at api_version: {api_version}."
>                 logger.SERVER_LOGGER.debug(msg)
> ```

Is there any reason why we are not logging out clients in _user_context_map?

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/service.py, line 145 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MZJlFr07n3tayPHbtYF:-MZJlFr07n3tayPHbtYG:b-jpwq6m) ([raw file](https://github.com/vmware/container-service-extension/blob/dbf13d15c263537d8bc6dca30f3a235748a00bab/container_service_extension/server/service.py#L145)):*
> ```Python
>         error_msg += f"Installed CSE RDE version ({runtime_rde_version}) " \
>             f"is lower than the supported Server RDE version " \
>             f"({ext_rde_in_use}). Upgrade CSE to update RDE."
> ```

    I think the **if condition** is right. But only the error message needs to be fixed as follows:

if not ext_in_legacy_mode and ext_rde_in_use < runtime_rde_version:
        error_msg += f"Installed CSE RDE version ({ext_rde_in_use}) " \
            f"is lower than the supported Server RDE version " \
            f"({runtime_rde_version}). Upgrade CSE to update RDE."

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @sahithi, and @sakthisunda)

___
*[container_service_extension/security/context/operation_context.py, line 132 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MZJSzpE4684caIwKQpf:-MZOBDdp2RAZedPyiuGQ:b7hqt15) ([raw file](https://github.com/vmware/container-service-extension/blob/dbf13d15c263537d8bc6dca30f3a235748a00bab/container_service_extension/security/context/operation_context.py#L132)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is there any reason why we are not logging out clients in _user_context_map?
</blockquote></details>

The user session is created outside of CSE, we get the token from VCD, since we don't create the session, we shouldn't end it either.
___
*[container_service_extension/server/service.py, line 145 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1014#-MZJlFr07n3tayPHbtYF:-MZOBn790my4nrwZZxz0:b-z28ouc) ([raw file](https://github.com/vmware/container-service-extension/blob/dbf13d15c263537d8bc6dca30f3a235748a00bab/container_service_extension/server/service.py#L145)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

    I think the **if condition** is right. But only the error message needs to be fixed as follows:

if not ext_in_legacy_mode and ext_rde_in_use < runtime_rde_version:
        error_msg += f"Installed CSE RDE version ({ext_rde_in_use}) " \
            f"is lower than the supported Server RDE version " \
            f"({runtime_rde_version}). Upgrade CSE to update RDE."

</blockquote></details>

Thanks will fix it.

**Review by rocknes — COMMENTED** [review]
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1014)* status: 33 of 34 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @arunmk, @ltimothy7, @sahithi, and @sakthisunda)

**Pull request merged**
