### PR TITLE
[VCDA-2369, VCDA-2370] Add support for TKGm runtime

### PR DESCRIPTION
**Pull request by rocknes**
Add logic in CSE server to create TKGm compute policy (if missing) during install/upgrade.
Update OVDC handler to work with TKGm runtime.
Add TKGm specific checks while reading templates/processing them during cse install/upgrade/run

Testing Done:
Install CSE and make sure TKGm policy is created in the system - Success
Create TKGm template using `cse template create` and make sure that the TKGm compute policy is applied to the template. - Success

Run CSE server
Try to deploy TKGm cluster, it failed with error message that ovdc is not enabled - Success
Enable OVDC for TKGm via REST api - Success
Deploy cluster via CLI - Failed with `unable to contact guest`

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 6 of 12 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/configure_cse.py, line 1288 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCWIbNAARSNitVG17R:-MbCWIbNAARSNitVG17S:b-9k9zvo) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L1288)):*
> ```Python
>                 shared_constants.ClusterEntityKind.TKG_M.value and \
>                 not is_tkgm_enabled:
>             msg = "Found a TKGm template. However TKG+ is not enabled on " \
> ```

"However, TKGm is..."
___
*[container_service_extension/shared_constants.py, line 27 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCXW3zBT9BIvgCMoCP:-MbCXW3zBT9BIvgCMoCQ:bw6fdhf) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/shared_constants.py#L27)):*
> ```Python
>     TKG = 'TanzuKubernetesCluster'
>     TKG_PLUS = 'TKG+'
>     TKG_M = 'TKGm'
> ```

One thing that is  inconsistent to me is that the ClusterEntityKind here is called `TKG_M` while we have use `tkgm` in variables and functions such as `utils.is_tkgm_enabled` while the ClusterEntityKind is called `TKG_PLUS` and the variables and functions use `tkg_plus`.

In this case, I think it would be more consistent to rename the TKGm variables and functions as `tkg_m` so that there is a standard naming pattern. I can do this in my PR too, but what do you think?

**Review by andrew-ni — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053#-:-MbCgt_WBgt86YY5jBML:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/configure_cse.py, line 1288 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCWIbNAARSNitVG17R:-MbCyPTf3zYklOgSOipn:bvljs2o) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L1288)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

"However, TKGm is..."
</blockquote></details>

Addressed.
___
*[container_service_extension/shared_constants.py, line 27 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCXW3zBT9BIvgCMoCP:-MbCvG9m5BGg6tQz8GtQ:b-j7g4c0) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/shared_constants.py#L27)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

One thing that is  inconsistent to me is that the ClusterEntityKind here is called `TKG_M` while we have use `tkgm` in variables and functions such as `utils.is_tkgm_enabled` while the ClusterEntityKind is called `TKG_PLUS` and the variables and functions use `tkg_plus`.

In this case, I think it would be more consistent to rename the TKGm variables and functions as `tkg_m` so that there is a standard naming pattern. I can do this in my PR too, but what do you think?
</blockquote></details>

yeah I agree, we should establish a single pattern.
Thanks, I will take up your offer :)

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/configure_cse.py, line 706 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCvkX_2b2I8oqlljoA:-MbCvkX_2b2I8oqlljoB:brd8hbc) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L706)):*
> ```Python
>     # Using the Org, determine Role object (using Role-name we identified)
>     role_record = system_org.get_role_record(role_name)
>     role_record_read_only = role_record.get("isReadOnly").lower() in ["true"]
> ```

role_record_read_only =  core_utils.str_to_bool(role_record.get('isReadOnly'))?
___
*[container_service_extension/configure_cse.py, line 2192 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbD1eQI4dEvTcc2JLfC:-MbD1eQJ3Mi65q0Fymui:b3vsm64) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L2192)):*
> ```Python
>     INSTALL_LOGGER.info(msg)
> 
>     # Since TKGm clusters are being introduced in CSE 3.0.3, we don't need to
> ```

Can customers deploy TKGm when CSE server is running in API version 33? If yes, then we will have to handle the condition where CSE server is upgraded to api_version 35.0
___
*[container_service_extension/def_/models.py, line 145 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbD4IntBcija8Ri4KYc:-MbD4IntBcija8Ri4KYd:b22srw4) ([raw file](https://github.com/vmware/container-service-extension/blob/97947d5a6724dab785b0c92369f154af99c94142/container_service_extension/def_/models.py#L145)):*
> ```Python
>     task_href: str = None
>     kubernetes: str = None
>     cni: str = None
> ```

If removing cni was intended, then removing this line doesn't really remove cni attribute because there is a `self.cni = cni` in the init as well

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/def_/models.py, line 145 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbD4IntBcija8Ri4KYc:-MbHpAb14z8FNJuYyjCZ:b-g7dupu) ([raw file](https://github.com/vmware/container-service-extension/blob/97947d5a6724dab785b0c92369f154af99c94142/container_service_extension/def_/models.py#L145)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If removing cni was intended, then removing this line doesn't really remove cni attribute because there is a `self.cni = cni` in the init as well
</blockquote></details>

There were two copies of cni in this class .. look at the 2nd line of the class.
I removed the duplicate :)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: 7 of 14 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/configure_cse.py, line 706 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCvkX_2b2I8oqlljoA:-MbIASC43AUVnTTk17WT:b-7rl0jd) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L706)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

role_record_read_only =  core_utils.str_to_bool(role_record.get('isReadOnly'))?
</blockquote></details>

done.
___
*[container_service_extension/configure_cse.py, line 2192 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbD1eQI4dEvTcc2JLfC:-MbIAOBi1AAd6LMazfay:bqey95o) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/configure_cse.py#L2192)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can customers deploy TKGm when CSE server is running in API version 33? If yes, then we will have to handle the condition where CSE server is upgraded to api_version 35.0
</blockquote></details>

Yes, you are right, addressed the use case.

**Review by andrew-ni — APPROVED** [review]
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 5 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/shared_constants.py, line 27 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbCXW3zBT9BIvgCMoCP:-MbIAs2P4QsyG_q_6KQh:bcovscq) ([raw file](https://github.com/vmware/container-service-extension/blob/3d0709dd4f759d300cf9428208aaa4e6804b6b74/container_service_extension/shared_constants.py#L27)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

yeah I agree, we should establish a single pattern.
Thanks, I will take up your offer :)
</blockquote></details>

Actually went ahead and fixed all the variable and method names to adhere top tkg_m format in this PR :)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053#-:-MbIDj73BgTjKlNBzB_B:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/def_/models.py, line 145 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1053#-MbD4IntBcija8Ri4KYc:-MbIDMod2p1d9WkVJ7Fr:ban032s) ([raw file](https://github.com/vmware/container-service-extension/blob/97947d5a6724dab785b0c92369f154af99c94142/container_service_extension/def_/models.py#L145)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

There were two copies of cni in this class .. look at the 2nd line of the class.
I removed the duplicate :)
</blockquote></details>

I missed that, Thanks!

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1053)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

**Pull request merged**
