### PR TITLE
Port [VCDA-1927 & VCDA-2042] Paginate TKG and legacy native cluster responses (#868) to master

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

Testing done:

vcd cse cluster list with API server running in API version 35
vcd cse cluster list with API server running in API version 33
Check postman response for /api/cse/clusters endpont

@sakthisunda @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHWLVyD0eTi_wWHmdx:-MTHWLVyD0eTi_wWHmdy:blhael0) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L22)):*
> ```Python
>         self._uri = f"{self._uri}/{shared_constants.CSE_URL_FRAGMENT}/{ shared_constants.CSE_3_0_URL_FRAGMENT}"  # noqa: E501
>         self._clusters_uri = f"{self._uri}/clusters"
>         self._cluster_uri = f"{self._uri}/cluster"
> ```

Can the cluster url fragment be used here?
___
*[container_service_extension/client/tkgclient/api_client.py, line 240 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHWXvE4sKfJVzF2DJh:-MTHWXvE4sKfJVzF2DJi:bwwxydr) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/client/tkgclient/api_client.py#L240)):*
> ```Python
>         additional_data = None
>         if response_type == 'TkgCluster' and method == 'GET':
>             additional_data = data
> ```

Is additional_data intentionally using the same object as data? I know this is outside of the current PR, but wanted to check 
___
*[container_service_extension/server/vcdbroker.py, line 1893 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHXZfM7cOlrVxkFl8A:-MTHXZfM7cOlrVxkFl8B:bd69t1o) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/vcdbroker.py#L1893)):*
> ```Python
>                                                        c['vdc_id'])
>         clusters.append({
>             'name': c['name'],
> ```

I think enums would be cleaner for these keys
___
*[container_service_extension/server/request_handlers/native_cluster_handler.py, line 198 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHY1VK1qsBRa1hJ6aI:-MTHY1VK1qsBRa1hJ6aJ:b-x7wuc8) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/request_handlers/native_cluster_handler.py#L198)):*
> ```Python
>         'status',
>         'org_name',
>         'k8s_version',
> ```

If there are cluster enum keys, they could be used here too.
___
*[container_service_extension/server/request_handlers/request_utils.py, line 104 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHYGmS-Yw74EjP9elw:-MTHYGmS-Yw74EjP9elx:b-hn1w2v) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/request_handlers/request_utils.py#L104)):*
> ```Python
>     """
>     keys_with_invalid_value = find_diff_fields(input_spec, reference_spec,
>                                                exclude_fields=exclude_fields)
> ```

Just wanted to make sure that it is okay if ‘exclude_fields’ is None?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/tkgclient/api_client.py, line 240 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHWXvE4sKfJVzF2DJh:-MTIKEwN0aEM4AlLrUcR:b-8vzv40) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/client/tkgclient/api_client.py#L240)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Is additional_data intentionally using the same object as data? I know this is outside of the current PR, but wanted to check 
</blockquote></details>

Yes, this is intentional. data returned will only be the 'entity' part of the DE. additional_data is intended to keep data which the entity part of the defined entity won't store. Like org & clusterID.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/server/request_handlers/request_utils.py, line 104 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHYGmS-Yw74EjP9elw:-MTJ-Cne2t2PtjcEVm1N:bqm00gg) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/request_handlers/request_utils.py#L104)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Just wanted to make sure that it is okay if ‘exclude_fields’ is None?
</blockquote></details>

Currently,  caller always sets exclude_fields with some values. If it is None or not used, then this cause, TypeError in : find_diff_fields

Since, there is no mutation happening on exclude_fields in this function, it may be ok to leave as:
exclude_fields=[]. Else if None check is required.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHWLVyD0eTi_wWHmdx:-MTfq8Fo5tzdccRmq60X:b-1wcwcv) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L22)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Can the cluster url fragment be used here?
</blockquote></details>

I think it is a good idea to use the OperationType constants. But this should be done for other API endpoints as well.
@rocknes Can I create a separate task for addressing this comment?
___
*[container_service_extension/server/request_handlers/native_cluster_handler.py, line 198 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHY1VK1qsBRa1hJ6aI:-MTgiI01CsvAuvt2MtXd:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/request_handlers/native_cluster_handler.py#L198)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

If there are cluster enum keys, they could be used here too.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/request_utils.py, line 104 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHYGmS-Yw74EjP9elw:-MTIL0Jd8yM5EM3E5Rwg:b-mmbb6s) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/request_handlers/request_utils.py#L104)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Just wanted to make sure that it is okay if ‘exclude_fields’ is None?
</blockquote></details>

Thanks for catching, fixed this in `find_diff_fields` function

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/server/vcdbroker.py, line 1893 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHXZfM7cOlrVxkFl8A:-MTgiLpDD4E48FgD_QDj:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/server/vcdbroker.py#L1893)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think enums would be cleaner for these keys
</blockquote></details>

Done.

**Review by ltimothy7 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908#-:-MTh1DunB1VXVipyUxhp:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

**Review by sakthisunda — APPROVED** [review]
> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

**Review by sakthisunda — APPROVED** [review]
:lgtm: ( after addressing any outstanding review comments )

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908#-:-MUBcx8bAUWiufaERh12:b-xhpse4)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 11 of 15 files at r1, 2 of 4 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/908#-:-MUEXB9p52BA9jSScrC6:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 22 at r1](https://reviewable.io/reviews/vmware/container-service-extension/908#-MTHWLVyD0eTi_wWHmdx:-MUEXKA5AsAzNXpZekRz:bmwslxa) ([raw file](https://github.com/vmware/container-service-extension/blob/ac879e33e0100eb050428d74845b15cdbf0280ea/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L22)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think it is a good idea to use the OperationType constants. But this should be done for other API endpoints as well.
@rocknes Can I create a separate task for addressing this comment?
</blockquote></details>

wait on this one, since we will be moving from request_procesor to request_dispatcher, and the constants will change a bit.

**Pull request merged**
