### PR TITLE
[VCDA-2007] Cluster resize with exposed cluster

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
-The cluster resize workflow will now check if the cluster is exposed; if the user desires to unexpose the cluster, the associated dnat rule will be deleted, and the kubeconfig will have the external ip replaced with the internal ip.

- (Optional) Names of reviewers using @ sign + name
@arunmk @rocknes @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/953)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/953#-:-MVSOcim1nTBynbSnOgP:bnfp4nl)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/def_/cluster_service.py, line 265 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSMiZB5t0TURM7rUA6:-MVSMiZC2MPg_LieV1BO:b-j4mgay) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L265)):*
> ```Python
>         return def_entity
> 
>     def resize_cluster(self, cluster_id: str,
> ```

nit: should we rename this method to update_cluster?
___
*[container_service_extension/def_/cluster_service.py, line 835 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSN0Yt2Cb7XP_IAGkK:-MVSN0Yt2Cb7XP_IAGkL:b-scng3e) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L835)):*
> ```Python
>     @utils.run_async
>     def _monitor_update(self, cluster_id, cluster_spec):
>         """Triggers and monitors one or more async threads of resize.
> ```

nit: resize -> update
___
*[container_service_extension/def_/cluster_service.py, line 847 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSN4fh0jxgY5ANfwmY:-MVSN4fiAszWq2Hbp2IZ:bm34iea) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L847)):*
> ```Python
>         - ends the client context
> 
>         If the cluster is exposed and the spec shows to unexpose the cluster,
> ```

nit : If the cluster is exposed and the spec instructs to un-expose the cluster, it will be de-exposed.

both un-expose and de-expose and not real words.. but rule of thumb .. 
un - relates to passive state
de - relates to an action

e.g. you want to unregister a plugin, but you deregister a plugin.
___
*[container_service_extension/def_/cluster_service.py, line 946 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSNXvZ4OSrD8xNdFjV:-MVSNXv_7JM51MZfdqe3:bulx5d4) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L946)):*
> ```Python
>                       f"and nfs count {desired_nfs_count}"
>                 if unexpose_success:
>                     msg += " and unexposing the cluster"
> ```

nit: un-exposed
preserving the tense of the sentence
___
*[container_service_extension/def_/cluster_service.py, line 948 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSOQLq5KJFoQrXVCAJ:-MVSOQLrEKT3n4d6dvk5:bgh4cn7) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L948)):*
> ```Python
>                     msg += " and unexposing the cluster"
>                 elif unexpose and not unexpose_success:
>                     msg += " and failed unexposing the cluster"
> ```

nit: failed to un-expose?

**Review by rocknes — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/953)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 294 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVTcW3E8HMOrziCxc14:-MVTcW3E8HMOrziCxc15:bpre41g) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L294)):*
> ```Python
> 
>         # Check for unexposing the cluster
>         desired_expose_state: bool = cluster_spec.spec.expose
> ```

should we be reporting an error if desired exposed state is true and is_exposed is false?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Minor clarification

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/953#-:-MVTdgU-EDjk-Ox2Zn-a:b-yfbfti)* status: all files reviewed, 6 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/953)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 265 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVSMiZB5t0TURM7rUA6:-MVSSNsNDLGqdf-k-xJj:b1udki0) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L265)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: should we rename this method to update_cluster?
</blockquote></details>

I think it would be better, but I think this would be a more complicated name change. I think renaming this should also mean renaming the corresponding def_cluster_handler function and more potential testing. Renaming this function also involves looking into renaming the abstract broker. I think this is a bit too much for the naming convention given the timeline for 3.0.2
___
*[container_service_extension/def_/cluster_service.py, line 294 at r1](https://reviewable.io/reviews/vmware/container-service-extension/953#-MVTcW3E8HMOrziCxc14:-MVTg0Kz7-CinBjSos3W:bu11bwo) ([raw file](https://github.com/vmware/container-service-extension/blob/3dbbf45345f1ad62002baf1770e900a8cf2306a5/container_service_extension/def_/cluster_service.py#L294)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we be reporting an error if desired exposed state is true and is_exposed is false?
</blockquote></details>

Followed-up offline: We don't want to throw an exception because we still want the cluster's operation to go through; this goes in line with how cluster creation goes through even if exposing fails

**Pull request merged**
