### PR TITLE
[VCDA-1950] Thread local data handling enhancement  

### PR DESCRIPTION
**Pull request by sakthisunda**
- Currrenty thread local data has accessor method exist only for request id. This enhancement gives flexibility to store and access any number of values for future requirement(s). Example: Telemetry data has a similar requirement to use thread local to store UserAgent. 
- Methods added to thread local to support accessors for any data. 
- Tested the changes with request_id in thread local.
- Verfied debug log that logs request id works as expected

image

@Anirudh9794 @rocknes @ltimothy7

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/thread_local_data.py, line 12 at r1](https://reviewable.io/reviews/vmware/container-service-extension/854#-MObSY-g1XxNaOcsfPkN:-MObSY-g1XxNaOcsfPkO:brjoodj) ([raw file](https://github.com/vmware/container-service-extension/blob/915e91584aa3e6588facd161392e30a40e070d38/container_service_extension/thread_local_data.py#L12)):*
> ```Python
> # Thread data to be initialized once. This data is specific to each thread.
> THREAD_DATA = None
> REQUEST_ID = 'request_id'
> ```

I think this should go into server_constants.py
___
*[container_service_extension/thread_local_data.py, line 56 at r1](https://reviewable.io/reviews/vmware/container-service-extension/854#-MObRqyrD9khXit0igsH:-MObRqyrD9khXit0igsI:b-kfqrgu) ([raw file](https://github.com/vmware/container-service-extension/blob/915e91584aa3e6588facd161392e30a40e070d38/container_service_extension/thread_local_data.py#L56)):*
> ```Python
> 
> 
> def reset_thread_local_data(data_dict: dict = {}):
> ```

I wonder if this function should just reset all attributes in the THREAD_DATA. If the user needs to pass in a dictionary of which attributes to set, then the user could use `set_thread_local_data_from_dict`.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/thread_local_data.py, line 12 at r1](https://reviewable.io/reviews/vmware/container-service-extension/854#-MObSY-g1XxNaOcsfPkN:-MObZW7c20R3BwFTEfGW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/915e91584aa3e6588facd161392e30a40e070d38/container_service_extension/thread_local_data.py#L12)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think this should go into server_constants.py
</blockquote></details>

Done.
___
*[container_service_extension/thread_local_data.py, line 56 at r1](https://reviewable.io/reviews/vmware/container-service-extension/854#-MObRqyrD9khXit0igsH:-MObZa918D0M3ime639d:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/915e91584aa3e6588facd161392e30a40e070d38/container_service_extension/thread_local_data.py#L56)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I wonder if this function should just reset all attributes in the THREAD_DATA. If the user needs to pass in a dictionary of which attributes to set, then the user could use `set_thread_local_data_from_dict`.
</blockquote></details>

Done.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854#-:-MOdBAatBZDtNbfZUNOF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/thread_local_data.py, line 62 at r2](https://reviewable.io/reviews/vmware/container-service-extension/854#-MOdAw6e0HlD3BgQ-gzk:-MOdAw6fC6QSBeODp3V5:b-jqp3yv) ([raw file](https://github.com/vmware/container-service-extension/blob/132dede25a764d0e725c7a2799cc2f4bba46c583/container_service_extension/thread_local_data.py#L62)):*
> ```Python
>     """
>     global THREAD_DATA
>     for key in THREAD_DATA.__dict__:
> ```

why not just .clear() ?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/854)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/thread_local_data.py, line 62 at r2](https://reviewable.io/reviews/vmware/container-service-extension/854#-MOdAw6e0HlD3BgQ-gzk:-MOdIEzdEg0gvSyrAP3N:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/132dede25a764d0e725c7a2799cc2f4bba46c583/container_service_extension/thread_local_data.py#L62)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

why not just .clear() ?
</blockquote></details>

Done.

**Pull request merged**
