### PR TITLE
[VCDA-2040 and VCDA-2043] Nsxt edge gateway (updates branch)

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Nsxt edge gateway class. For updates branch

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
- tested quick ip allocation and creating a DNAT rule.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/900)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor comment

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/900#-:-MSfAHFCCNK4ILzikjyn:basp5ut)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 222 at r1](https://reviewable.io/reviews/vmware/container-service-extension/900#-MSf921w-AYePGXML26b:-MSf921w-AYePGXML26c:betb55t) ([raw file](https://github.com/vmware/container-service-extension/blob/b2ec4099d1a71494f7616ac8550bfd4dbee5afeb/container_service_extension/nsxt_backed_gateway_service.py#L222)):*
> ```Python
>             resource_url_relative_path=self._gateway_relative_path)
> 
>     def _get_external_network_available_ip_dict(self, external_network_id):
> ```

I think this function should be moved out of the Service class because only the cloudapi client is used and it is not tied to gateway. Cloudapi client can be supplied as a parameter.
___
*[container_service_extension/server_constants.py, line 87 at r1](https://reviewable.io/reviews/vmware/container-service-extension/900#-MSetg_311EueDg3xZ2t:-MSetg_311EueDg3xZ2u:blbfxkl) ([raw file](https://github.com/vmware/container-service-extension/blob/b2ec4099d1a71494f7616ac8550bfd4dbee5afeb/container_service_extension/server_constants.py#L87)):*
> ```Python
> 
> # Prefix for Gateway urn
> GATEWAY_URN_PREFIX = 'urn:vcloud:gateway:'
> ```

DEF_INTERFACE_ID_PREFIX and DEF_ENTITY_TYPE_ID_PREFIX doesn't contain the trailing ":". I think we should remove the trailing ":" from here and include it wherever the constant is used

**Comment by rocknes** [comment]
Please fix the flake8 errors.

**Review by rocknes — APPROVED** [review]
:lgtm: once flake8 errors are fixed.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/900#-:-MSg9lo--Z069CRmyQ8d:brlbqby)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 222 at r1](https://reviewable.io/reviews/vmware/container-service-extension/900#-MSf921w-AYePGXML26b:-MSg9UIfE18d6Xo3K2TN:b-wdlmqe) ([raw file](https://github.com/vmware/container-service-extension/blob/b2ec4099d1a71494f7616ac8550bfd4dbee5afeb/container_service_extension/nsxt_backed_gateway_service.py#L222)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this function should be moved out of the Service class because only the cloudapi client is used and it is not tied to gateway. Cloudapi client can be supplied as a parameter.
</blockquote></details>

I view this is an in-class utility method, it can be kept in the class or moved out of the class and retained as a module level utility method. Either approach is fine in my opinion.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/900)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 222 at r1](https://reviewable.io/reviews/vmware/container-service-extension/900#-MSf921w-AYePGXML26b:-MShzJB56TYKr0_k4kUL:b-8e50z3) ([raw file](https://github.com/vmware/container-service-extension/blob/b2ec4099d1a71494f7616ac8550bfd4dbee5afeb/container_service_extension/nsxt_backed_gateway_service.py#L222)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I view this is an in-class utility method, it can be kept in the class or moved out of the class and retained as a module level utility method. Either approach is fine in my opinion.
</blockquote></details>

I have left this utility method in the class because I think the way it forms this dict is tied to the gateway even though the calls the function makes are not tied to the gateway. 
___
*[container_service_extension/server_constants.py, line 87 at r1](https://reviewable.io/reviews/vmware/container-service-extension/900#-MSetg_311EueDg3xZ2t:-MShzdKJ1TongGNBSoVT:b-ioxi1u) ([raw file](https://github.com/vmware/container-service-extension/blob/b2ec4099d1a71494f7616ac8550bfd4dbee5afeb/container_service_extension/server_constants.py#L87)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

DEF_INTERFACE_ID_PREFIX and DEF_ENTITY_TYPE_ID_PREFIX doesn't contain the trailing ":". I think we should remove the trailing ":" from here and include it wherever the constant is used
</blockquote></details>

Done. Thank you.

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/900)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Pull request merged**
