### PR TITLE
[VCDA-2371] Tkgm client

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
-Testing done:
-ovdc enable/disable
-cluster creation (1 control plane, 1 worker)
-template list
-cluster config, info, upgrade plan (no valid upgrade targets), delete

- (Optional) Names of reviewers using @ sign + name
@arunmk @andrew-ni @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: with the minor comment.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055#-:-MbMn89xDZtDlL8emHGS:bxhck9g)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/client/cluster_commands.py, line 605 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMmX8V-6wtiWRvGL5x:-MbMmX8WAN6QxGLpbvrm:btmuw2w) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L605)):*
> ```Python
>             if not k8_runtime:
>                 console_message_printer.general_no_color(ctx.get_help())
>                 msg = "with option --sample you must specify either of options: --native, --tkg, --tkg-plus, or --tkgm"  # noqa: E501
> ```

This message needs to be env var aware. If TKG plus or TKGm is not enabled, we should not list them

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/client/cluster_commands.py, line 612 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMoOTW1nGb34cbJ78o:-MbMoOTW1nGb34cbJ78p:b-75ed4l) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L612)):*
> ```Python
>                 raise Exception(f"{shared_constants.ClusterEntityKind.TKG_PLUS.value} not enabled")  # noqa: E501
>             elif k8_runtime == shared_constants.ClusterEntityKind.TKG_M \
>                     and not utils.is_environment_variable_enabled(cli_constants.ENV_CSE_TKG_M_ENABLED):  # noqa: E501
> ```

Nit: These if conditions are a bit odd. We are doing something like:
if <error condition1>:
    raise Exception
else if <error condition2>:
    raise Exception
.
.
.
else:
    <do the job>


We should rather do:
if <error condition1>:
    raise Exception
if <error condition2>:
    raise Exception
.
.
.
<do the job>
___
*[container_service_extension/def_/cluster_service.py, line 2182 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMnjJd1MdfAhF2oFXC:-MbMnjJd1MdfAhF2oFXD:b-90z0ti) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/def_/cluster_service.py#L2182)):*
> ```Python
>     is_tkgm = TKGM_TEMPLATE_NAME_FRAGMENT in template_name
>     if is_tkgm:
>         time.sleep(40)  # hack for ubuntu 20/tkgm
> ```

This is also needed for native in rare cases. So we can remove the `is_tkgm` check.

**Review by arunmk — APPROVED** [review]
:lgtm: in general

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055#-:-MbMpGYr3ffVRexjEQnq:b-xxf71g)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

**Comment by arunmk** [comment]
___
*[container_service_extension/client/cluster_commands.py, line 612 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMoOTW1nGb34cbJ78o:-MbMpQwG9B1B_MGtQEV7:b-rzf2gg) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L612)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: These if conditions are a bit odd. We are doing something like:
if <error condition1>:
    raise Exception
else if <error condition2>:
    raise Exception
.
.
.
else:
    <do the job>


We should rather do:
if <error condition1>:
    raise Exception
if <error condition2>:
    raise Exception
.
.
.
<do the job>

</blockquote></details>

I meant to say, we are doing the job as an else which is not clean. The submission wiped some comments. We are doing:
```
if <error condition 1>
    raise E1
else if <error condition 2>
    raise E2
.
.
.
else:
    do_job
```

We should do:
```
if <error condition 1>
    raise E1
if <error condition 2>
    raise E2
.
.
.
do_job
```

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/client/cluster_commands.py, line 603 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMpd4rBJ2xAs816cry:-MbMpd4rBJ2xAs816crz:bf43sce) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L603)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         if generate_sample_config:
>             if not k8_runtime:
>                 console_message_printer.general_no_color(ctx.get_help())
>                 msg = "with option --sample you must specify either of options: --native, --tkg, --tkg-plus, or --tkgm"  # noqa: E501
>                 CLIENT_LOGGER.error(msg)
>                 raise Exception(msg)
>             elif k8_runtime == shared_constants.ClusterEntityKind.TKG_PLUS \
>                     and not utils.is_environment_variable_enabled(cli_constants.ENV_CSE_TKG_PLUS_ENABLED):  # noqa: E501
> ```
</details>

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1055)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @arunmk and @rocknes)

___
*[container_service_extension/client/cluster_commands.py, line 603 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMpd4rBJ2xAs816cry:-MbMtZJH19i8f4d5Vncr:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L603)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

> ```
>         if generate_sample_config:
>             if not k8_runtime:
>                 console_message_printer.general_no_color(ctx.get_help())
>                 msg = "with option --sample you must specify either of options: --native, --tkg, --tkg-plus, or --tkgm"  # noqa: E501
>                 CLIENT_LOGGER.error(msg)
>                 raise Exception(msg)
>             elif k8_runtime == shared_constants.ClusterEntityKind.TKG_PLUS \
>                     and not utils.is_environment_variable_enabled(cli_constants.ENV_CSE_TKG_PLUS_ENABLED):  # noqa: E501
> ```

</blockquote></details>

Done.
___
*[container_service_extension/client/cluster_commands.py, line 605 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMmX8V-6wtiWRvGL5x:-MbMpMij9e0PtKVDm2yY:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/client/cluster_commands.py#L605)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This message needs to be env var aware. If TKG plus or TKGm is not enabled, we should not list them 
</blockquote></details>

Done.
___
*[container_service_extension/def_/cluster_service.py, line 2182 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1055#-MbMnjJd1MdfAhF2oFXC:-MbMpvGD0VUaGpo-a-TX:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c5b59aef58e30a1fa186c922573eecac8e9b589b/container_service_extension/def_/cluster_service.py#L2182)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is also needed for native in rare cases. So we can remove the `is_tkgm` check.
</blockquote></details>

Done.

**Pull request merged**
