### PR TITLE
Enable backend to publish messages to MQTT bus

### PR DESCRIPTION
**Pull request by sahithi**
Enable backend to publish messages to MQTT bus.

1. Backend can now access MQTT publisher object from the BehaviorOperationContext
2. Added support to publish success, error, and update messages on behaviors via MQTT.
3. There is no longer a need for a separate thread pool for behaviors, given we can set the terminal status asynchronously now from the backend. Removed the separate thread pool dedicated for behaviors.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 42 at r1](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXXvKI744I8ydnw3_Xj:-MXXvKI744I8ydnw3_Xk:b-pwqrvj) ([raw file](https://github.com/vmware/container-service-extension/blob/3d22e044f2d02c806c247180aabdd0696ebfc8cc/container_service_extension/mqi/consumer/mqtt_consumer.py#L42)):*
> ```Python
>         self._mqtt_publisher: MQTTPublisher = None
>         self._ctpe = ConsumerThreadPoolExecutor(self.num_processors)
>         self._publish_lock = Lock()
> ```

Since the MQTTPublisher has a lock, I think we should remove the `_publish_lock`

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 42 at r1](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXXvKI744I8ydnw3_Xj:-MXYHYzwDtbgWbkXXIWe:b8tqgvm) ([raw file](https://github.com/vmware/container-service-extension/blob/3d22e044f2d02c806c247180aabdd0696ebfc8cc/container_service_extension/mqi/consumer/mqtt_consumer.py#L42)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Since the MQTTPublisher has a lock, I think we should remove the `_publish_lock`
</blockquote></details>

Done, thanks Tim.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978#-:-MX_9GkSA6oTTtwiKEiY:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 273 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MX_6-cjDZXxueoZ1bRi:-MX_6-cjDZXxueoZ1bRj:b-ixr8kl) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L273)):*
> ```Python
>         self._create_cluster_async(entity_id, input_native_entity)
>         return self.mqtt_publisher.form_behavior_payload(
>             message='create_cluster_in_progress',
> ```

Just curious, are the changes done only for create cluster?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_temp.py, line 273 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MX_6-cjDZXxueoZ1bRi:-MXdBDwO2wmIYqrkQoAN:b-911269) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/rde/backend/cluster_service_2_x_temp.py#L273)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just curious, are the changes done only for create cluster?
</blockquote></details>

Yes, this is also a temporary change. There are tasks in the backlog for all CRUD. We will have to test each one of the operations thoroughly once the hook-based behaviors are all integrated. Hook-based behaviors is still a pending item from the Extensibility team.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 94 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXdJ2dy85Wl-VYLguh0:-MXdJ2dzCGgvylOs2HWM:b-gsfmoq) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L94)):*
> ```Python
>         }
>         if status == 'success':
>             del response_json['headers']['contentType']
> ```

if ['headers']['contentType'] is deleted, is it required to be specified as what value?

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 4 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978#-:-MXesyvG38E3oU4Ne5PZ:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 63 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXer9j0CPmItNwrnYgW:-MXeq6-E9YNwwTtLr9Vq:b-4d3bvj) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_consumer.py#L63)):*
> ```Python
>     def process_mqtt_message(self, msg):
>         msg_json = json.loads(msg.payload.decode(self.fsencoding))
>         if msg_json['type'] == 'BEHAVIOR_INVOCATION':
> ```

Is it guaranteed that the 'type' key will be always present? Specially if the vCD is 10.2 or earlier?
___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 66 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXeqKdL-dsE0fTqdRqv:-MXeqKdL-dsE0fTqdRqw:b-xq35p2) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_consumer.py#L66)):*
> ```Python
>             self.process_behavior_message(msg_json=msg_json)
>         else:
>             msg_json, reply_body, status_code, req_id = utils.get_response_fields(  # noqa: E501
> ```

I never liked the fact that the actual logic to process a request sits in an util file .. :|
No need to change it in this PR but we should improve the code organization imo. @ltimothy7 
___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 17 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXesEzy14XgqxpG0-BG:-MXesEzz6q6LUMqQ3hI0:bflk021) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L17)):*
> ```Python
>         self.mqtt_client = mqtt_client
>         self.respond_topic = respond_topic
>         self._publish_lock = Lock()
> ```

I think the Lock should be at the module level. Otherwise every MQTTPublisher object will have it's own lock, thereby defeating the whole purpose of having a global lock.
___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 19 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXepyO18cd4YYEgWlY0:-MXepyO2B4Wl2gt_MZBf:b-9b8fbw) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L19)):*
> ```Python
>         self._publish_lock = Lock()
> 
>     def form_response_json(self, request_id, status_code, reply_body_str,
> ```

nit: construct_response_json
___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 63 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXerunOAlXe70C8OCTw:-MXerunPAisD6QrUmyss:b-wxqkyr) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L63)):*
> ```Python
>             "status": status
>         }
>         if status == 'running':
> ```

Can we have constants for these values?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/978)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 63 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXer9j0CPmItNwrnYgW:-MXgt-6e6QSOLfYUKftW:bkqhqew) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_consumer.py#L63)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is it guaranteed that the 'type' key will be always present? Specially if the vCD is 10.2 or earlier?
</blockquote></details>

There is no guarantee. Added a check, thanks.
___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 66 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXeqKdL-dsE0fTqdRqv:-MXgt3ZCDGw0t_rbU68c:b-x7hdxs) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_consumer.py#L66)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I never liked the fact that the actual logic to process a request sits in an util file .. :|
No need to change it in this PR but we should improve the code organization imo. @ltimothy7 
</blockquote></details>

Yes, this needs to be changed. It can cause circular imports too.
___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 17 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXesEzy14XgqxpG0-BG:-MXgm8TuBPeeHYXHz30X:b-z3pa40) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L17)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think the Lock should be at the module level. Otherwise every MQTTPublisher object will have it's own lock, thereby defeating the whole purpose of having a global lock.
</blockquote></details>

There will only be one instance of MQTT publisher as there is only one instance of MessageConsumer. I added a docstring that MQTTPublisher cannot be initialized outside of MQTTConsumer object and there can exist only one instance of MQTTCOnsumer.
___
*[container_service_extension/mqi/consumer/mqtt_publisher.py, line 63 at r2](https://reviewable.io/reviews/vmware/container-service-extension/978#-MXerunOAlXe70C8OCTw:-MXgmjge5M44jSPeCo98:b-vamuxb) ([raw file](https://github.com/vmware/container-service-extension/blob/cb913ffcaf51a6038491073647ad1e84a0b7c9b9/container_service_extension/mqi/consumer/mqtt_publisher.py#L63)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can we have constants for these values?
</blockquote></details>

This is the one and only place they are used.

**Pull request merged**
