### PR TITLE
[VCDA-3072] Server-Config-Proxy-Support

### PR DESCRIPTION
**Pull request by sakthisunda**
- Inject http proxy configuration from cse server config file
- New section namely `extra_options` in server config file
- New tkgm only proxy variable in server config:`tkgm_http_proxy, tkgm_https_proxy, tkgm_no_proxy`
- Updated cloud-init control plane and node scripts
- Tested in special testbed setup created using:[NSXT-Setup](https://confluence.eng.vmware.com/display/VCD/NSX-T+Testbed+Outbound+Access+Setup)
- Ref: [TKGm-Squid setup](https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=VCD&title=Proxy+Configuration+on+TKGm+clusters)
- verified cluster creation with no proxy setup fails with:` Error adding control plane node: failure on creating nodes:/root/control_plane.sh: wget -O $antrea_path https://github.com/vmware-tanzu/antrea/releases/download/v0.11.3/antrea.yml`
- Verified the squid access log while TKGm cluster creation for outbound requests for github vmware requests
- Verified the http-proxy.config on control-plane and worker node vm
- Completed testing on conventional TKGm setup as per: [TKGM on VCD](https://confluence.eng.vmware.com/display/VCD/TKGm+on+VCD%3A+CPI+testing)

image

image

image

image

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1260)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1260)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 118 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD0g4h2BUENp2zbFtH:-MpD0g4h2BUENp2zbFtI:b-n884ri) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L118)):*
> ```YAML
>     Environment="HTTP_PROXY={http_proxy}"
>     Environment="HTTPS_PROXY={https_proxy}"
>     Environment="http_proxy={http_proxy}"
> ```

In theory the lower case ones are not needed here, but it doesn't hurt to have them.
___
*[container_service_extension/common/constants/server_constants.py, line 770 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD0wX2-lLeaK4ONbZy:-MpD0wX2-lLeaK4ONbZz:bt6jzmv) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/common/constants/server_constants.py#L770)):*
> ```Python
> # tkgm proxy key in CSE server config -> actual key as in http-proxy.config
> class TKGmProxyKey(Enum):
>     tkgm_http_proxy = 'http_proxy'
> ```

Nit: since we'll refer to these as `TKGmProxyKey.<variable>`, it may suffice to have these as `http_proxy` etc, so that we can just refer to these as `TKGmProxyKey.http_proxy` etc
___
*[container_service_extension/installer/sample_generator.py, line 187 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1I6246ojFfLeZxLP:-MpD1I6246ojFfLeZxLQ:b-fdyt0a) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/installer/sample_generator.py#L187)):*
> ```Python
> #extra_options:
> #   tkgm_http_proxy: http://192.168.7.10:3128
> #   tkgm_https_proxy: http://192.168.7.10:3128
> ```

Nit: https maybe?
___
*[container_service_extension/installer/sample_generator.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1NKr31vd-OtPllU9:-MpD1NKr31vd-OtPllUA:bcbkrvl) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/installer/sample_generator.py#L188)):*
> ```Python
> #   tkgm_http_proxy: http://192.168.7.10:3128
> #   tkgm_https_proxy: http://192.168.7.10:3128
> #   tkgm_no_proxy: localhost,192.168.7.0/24
> ```

Also can u add 127.0.0.1 here
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1931 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1VzL88A2YSr-NZA2:-MpD1VzL88A2YSr-NZA3:baozjgh) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1931)):*
> ```Python
> 
> 
> def _get_proxy_config() -> dict:
> ```

Better to call this as `_get_tkgm_proxy_config()` since we return only tkgm proxy config
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2043 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1lBGESSyluxQa0gH:-MpD1lBGESSyluxQa0gI:b6oh3ee) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2043)):*
> ```Python
>                 control_plane_endpoint='',
>                 base64_encoded_refresh_token=base64_refresh_token.decode("utf-8"),  # noqa: E501
>                 **proxy_config
> ```

Will this fail if say someone does not specify HTTPS_PROXY in the _config_? I mean, it is okay to say `https_proxy=""` here, but if the variable itself is missing, I think we will get a python string template error.

**Review by arunmk — APPROVED** [review]
:lgtm: after chatting with Sakthi about the changes and most of my comments were not needed.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1260#-:-MpD729m2kHuanxnlttN:bsg0x8u)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @rocknes and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1260)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @arunmk and @rocknes)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 118 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD0g4h2BUENp2zbFtH:-MpD7AE-CVSOsn978Udn:bll48q) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L118)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

In theory the lower case ones are not needed here, but it doesn't hurt to have them.
</blockquote></details>

For my testbed, only lower case http_proxy worked. Also based on documentation, this included all supported variables.
___
*[container_service_extension/common/constants/server_constants.py, line 770 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD0wX2-lLeaK4ONbZy:-MpDAUVa01A1YXWHIska:b-nrohlr) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/common/constants/server_constants.py#L770)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: since we'll refer to these as `TKGmProxyKey.<variable>`, it may suffice to have these as `http_proxy` etc, so that we can just refer to these as `TKGmProxyKey.http_proxy` etc
</blockquote></details>

left side of the assignment should be the same as in server config and the right side should be the same as it is in control plane and worker node cloud-init scripts. 
___
*[container_service_extension/installer/sample_generator.py, line 188 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1NKr31vd-OtPllU9:-MpDBIW59ZCx8hqBrbNt:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/installer/sample_generator.py#L188)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Also can u add 127.0.0.1 here
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1931 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1VzL88A2YSr-NZA2:-MpDBM4F8KLQHUXJzu2j:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1931)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Better to call this as `_get_tkgm_proxy_config()` since we return only tkgm proxy config
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2043 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1260#-MpD1lBGESSyluxQa0gH:-MpDBNbl9CdtdCEanTug:b-o10vpg) ([raw file](https://github.com/vmware/container-service-extension/blob/9f761bd1a2ea6f5f1b9a964552da1cf9e83c606a/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2043)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Will this fail if say someone does not specify HTTPS_PROXY in the _config_? I mean, it is okay to say `https_proxy=""` here, but if the variable itself is missing, I think we will get a python string template error.
</blockquote></details>

No. It will not fail. The code always generates proxy variables either with right values or empty values. So, template always get a value.

Tested and verified with no <b>extra_options</b> section in server config.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1260#-:-MpICEwD0oOiZj9FVSx8:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Pull request merged**
