### PR TITLE
[VCDA-2001]Adopt RDE task management in cluster_service

### PR DESCRIPTION
**Pull request by sahithi**
Implemented a new update_task method which publishes the task updates via MQTT. 
Modified the entire file to refer to the new method for the task updates.
Removed few obsolete instance variables and created a few.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/994)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/994)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 278 at r1](https://reviewable.io/reviews/vmware/container-service-extension/994#-MY6Y9htE-XY_iNis5MG:-MY6Y9htE-XY_iNis5MH:bt7hh34) ([raw file](https://github.com/vmware/container-service-extension/blob/84a8ac459a556366d69d4dcd5905ba7ca4e71c50/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L278)):*
> ```Python
>         self._update_task(status=BehaviorTaskStatus.RUNNING,
>                           message='Hurray cluster task-update is working',
>                           progress=3)
> ```

Any reason why specific value of 3 is used?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/994)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 278 at r1](https://reviewable.io/reviews/vmware/container-service-extension/994#-MY6Y9htE-XY_iNis5MG:-MY6z_mvAdkQfdz7ESBC:bjvodmr) ([raw file](https://github.com/vmware/container-service-extension/blob/84a8ac459a556366d69d4dcd5905ba7ca4e71c50/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L278)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Any reason why specific value of 3 is used?
</blockquote></details>

No, this was just a sample message  I used for testing. We need to think about how we want to increment the progress value. It is not a priority. It is an optional field by the way.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/994#-:-MYBT8i6CAqIda4_D1zR:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/994)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Pull request merged**
