### PR TITLE
[VCDA-2601] Create subdirectory under LOCAL SCRIPTS DIR

### PR DESCRIPTION
**Pull request by Anirudh9794**
… key during cse upgrade

Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

* Create subdirectory under LOCAL_SCRIPTS_DIR to store script cache
* Ignore compute policy key during cse upgrade as it prevents updating template metadata once again after upgrade is complete.

Testing:
* Cse upgrade to check if ignoring keys work fine
* Template install and see if proper directory is created during cluster installation.

@rocknes @sahithi @ltimothy7 @sakthisunda @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1076)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1076)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/installer/templates/local_template_manager.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1076#-Mcro78y6pxRhUL0LucG:-Mcro78z1aUirddqBMrU:b-a72qar) ([raw file](https://github.com/vmware/container-service-extension/blob/130158744de69a8c6ba54087a6811e9cd0cec625/container_service_extension/installer/templates/local_template_manager.py#L115)):*
> ```Python
>         missing_metadata_keys = missing_metadata_keys - set(ignore_metadata_keys)  # noqa: E501
>         num_missing_metadata_keys = len(missing_metadata_keys)
>         if num_missing_metadata_keys == len(expected_metadata_keys):
> ```

After removing/ignoring some keys, will this condition be ever met?

Because expected key list will have the cookbook_version key.

Btw why do we want to hide this particular key? We are stamping it on the template, let it run through the whole system. If the need be the client can prune it.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/templates/local_template_manager.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1076#-Mcro78y6pxRhUL0LucG:-Mctophb1wJAxkM3Kn-4:b-9ev0so) ([raw file](https://github.com/vmware/container-service-extension/blob/130158744de69a8c6ba54087a6811e9cd0cec625/container_service_extension/installer/templates/local_template_manager.py#L115)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

After removing/ignoring some keys, will this condition be ever met?

Because expected key list will have the cookbook_version key.

Btw why do we want to hide this particular key? We are stamping it on the template, let it run through the whole system. If the need be the client can prune it.
</blockquote></details>

Before this change, all the templates (legacy and non-legacy) could have been read by calling `get_all_k8s_local_template_definition(legacy_mode=True)`.
After adding `cookbook_version` into template metadata, only legacy templates will be read with `get_all_k8s_local_template_definition(legacy_mode=True)`.

This will affect CSE upgrade because since we want CSE upgrade should be idempotent and hence we would want to read all the templates to update their metadata.

So i added the new parameter `ignore_metadata` to ignore `cookbook_version` only during cse upgrade

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1076)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/installer/templates/local_template_manager.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1076#-Mcro78y6pxRhUL0LucG:-McxF6jqCZ5oGLFjRNT1:b-6dlple) ([raw file](https://github.com/vmware/container-service-extension/blob/130158744de69a8c6ba54087a6811e9cd0cec625/container_service_extension/installer/templates/local_template_manager.py#L115)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Before this change, all the templates (legacy and non-legacy) could have been read by calling `get_all_k8s_local_template_definition(legacy_mode=True)`.
After adding `cookbook_version` into template metadata, only legacy templates will be read with `get_all_k8s_local_template_definition(legacy_mode=True)`.

This will affect CSE upgrade because since we want CSE upgrade should be idempotent and hence we would want to read all the templates to update their metadata.

So i added the new parameter `ignore_metadata` to ignore `cookbook_version` only during cse upgrade
</blockquote></details>

This still sounds very hacky to me .. let me think over it a bit and get back to you. As a general rule of thumb, we should strive to avoid as much as possible, special casing in code.

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1076#-:-MdNmn5kD5up5DN5zvNF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/installer/templates/local_template_manager.py, line 115 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1076#-Mcro78y6pxRhUL0LucG:-MdNmToJByzBtVHd3f0d:b-30db1c) ([raw file](https://github.com/vmware/container-service-extension/blob/130158744de69a8c6ba54087a6811e9cd0cec625/container_service_extension/installer/templates/local_template_manager.py#L115)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This still sounds very hacky to me .. let me think over it a bit and get back to you. As a general rule of thumb, we should strive to avoid as much as possible, special casing in code.
</blockquote></details>

Gave it some thought and it seems we need the ignore_metadata param, but I am still not convinced that this check is valid.

**Pull request merged**
