### PR TITLE
[VCDA-2249]Introduce payload versioning in the schema and model 2.0

### PR DESCRIPTION
**Pull request by sahithi**
Introduce payload versioning in the schema and model 2.0

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/964)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/964)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 215 at r1](https://reviewable.io/reviews/vmware/container-service-extension/964#-MWRdPMX0tNrlMsbwyhd:-MWRdPMX0tNrlMsbwyhe:b4w24lm) ([raw file](https://github.com/vmware/container-service-extension/blob/49ba80f08594a4c4ca282e2aad1250fc0947bde3/container_service_extension/rde/models/rde_2_0_0.py#L215)):*
> ```Python
>     api_version: str = PAYLOAD_VERSION_2_0
> 
>     def __init__(self, metadata: Metadata, spec: ClusterSpec, status=Status(),
> ```

We should not let api_version be overridden, or if we let it be overridden, we should instantiate a different object. We should also do some validation of version.
___
*[cse_def_schema/schema_2_0_0.json, line 254 at r1](https://reviewable.io/reviews/vmware/container-service-extension/964#-MWRd8r02Ww1YRAZYf2M:-MWRd8r02Ww1YRAZYf2N:bo48cch) ([raw file](https://github.com/vmware/container-service-extension/blob/49ba80f08594a4c4ca282e2aad1250fc0947bde3/cse_def_schema/schema_2_0_0.json#L254)):*
> ```JSON
>                 "additionalProperties": true
>             },
>             "api_version": {
> ```

Do you want to have the camelCase of apiVersion as part of this change or do you want to have that done to all fields at a later point?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/964)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @arunmk)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 215 at r1](https://reviewable.io/reviews/vmware/container-service-extension/964#-MWRdPMX0tNrlMsbwyhd:-MWW3cst9L8tfPy_dS-t:b-mw7j4h) ([raw file](https://github.com/vmware/container-service-extension/blob/49ba80f08594a4c4ca282e2aad1250fc0947bde3/container_service_extension/rde/models/rde_2_0_0.py#L215)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We should not let api_version be overridden, or if we let it be overridden, we should instantiate a different object. We should also do some validation of version.
</blockquote></details>

This does not override anything. It just sets the default value.

But I think this is giving a false impression that api_version is an optional param, I will remove it. 
___
*[cse_def_schema/schema_2_0_0.json, line 254 at r1](https://reviewable.io/reviews/vmware/container-service-extension/964#-MWRd8r02Ww1YRAZYf2M:-MWW3ZCj67qazP4t4Br_:b15pgds) ([raw file](https://github.com/vmware/container-service-extension/blob/49ba80f08594a4c4ca282e2aad1250fc0947bde3/cse_def_schema/schema_2_0_0.json#L254)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Do you want to have the camelCase of apiVersion as part of this change or do you want to have that done to all fields at a later point?
</blockquote></details>

We can do it later all at once.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/964)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/964)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @sahithi)

**Pull request merged**
