### PR TITLE
[VCDA-3342] Prepare the CSE for RDE 2.1.0 usage

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
- Updated the schema and replaced RDE 2.0 with 2.1

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Basic testing: cse install and rde 2.1 entity type registered

- (Optional) Names of reviewers using @ sign + name
@sahithi @Anirudh9794 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1313)

### CODE REVIEW

**Comment by ltimothy7** [comment]
Note: More thorough testing will be done with following tasks

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1313)* status: all files reviewed, 10 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/developer_guide.md, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwifnGIAedw6aNX_xlc:-MwifnGIAedw6aNX_xld:b-nw4ess) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/developer_guide.md#L52)):*
> ```Markdown
> should be moved to a new url.
> 
> ## RDE
> ```

Please do update the developer_guide file with any missing info on - how to do RDE upgrades of minor versions
___
*[container_service_extension/installer/configure_cse.py, line 1585 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwig_Or8Rb5fIKKlIFy:-Mwig_Or8Rb5fIKKlIFz:b-hlv7yg) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/installer/configure_cse.py#L1585)):*
> ```Python
> 
> 
> def _register_entity_type(
> ```

Can you please have Sakthi or Aniruddh look at the install and upgrade logic?
___
*[container_service_extension/rde/constants.py, line 84 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwhdSoEDwHcNYsCC1KX:-MwhdSoEDwHcNYsCC1KY:btiyi84) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/constants.py#L84)):*
> ```Python
> class RDEVersion(str, Enum):
>     RDE_1_0_0 = '1.0.0'
>     RDE_2_1_0 = '2.1.0'
> ```

A separate entry needs to be made here (not override). Note that this is just RDEVersion Enum, not runtimeRDE
___
*[container_service_extension/rde/constants.py, line 154 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwigu_w8CcjWEet6ij1:-Mwigu_w8CcjWEet6ij2:b-qz1uzp) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/constants.py#L154)):*
> ```Python
> MAP_VCD_API_VERSION_TO_RDE_VERSION = {
>     '35.0': RDEVersion.RDE_1_0_0.value,
>     '36.0': RDEVersion.RDE_2_1_0.value
> ```

Are we going to qualify CSE 3.1.3 for any VCD version that supports API version >=37?

If yes, we need to make an entry for 37.0, please double-check with Aashima.
___
*[container_service_extension/rde/models/common_models.py, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwihZMwERgxXKhUDE9I:-MwihZMxCDFJQx8XlmLB:beoi1tc) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/common_models.py#L83)):*
> ```Python
> @dataclass_json(undefined=Undefined.EXCLUDE)
> @dataclass(frozen=True)
> class DefEntityType2_1:
> ```

You need not change the DefEntityType version to 2.1

This class name just represents that a new property called "hooks" has been added to RDE TYPE by RDE framework.
___
*[container_service_extension/rde/models/common_models.py, line 374 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwiho-58DtDQMtHOZ46:-Mwiho-58DtDQMtHOZ47:b-p8gpjg) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/common_models.py#L374)):*
> ```Python
>             K8Interface.CSE_INTERFACE.value.id
>         ],
>         version='2.1.0',
> ```

This is good enough.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 49 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwieV0_0ZGAeD2WLxyU:-MwieV0_0ZGAeD2WLxyV:bthhyrx) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L49)):*
> ```Python
> 
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_1_0.value):  # noqa: E501
> ```

It should stay RDE 2.0.0 only here in this file.

What we are saying here is - anything greater than 2.0, redirect to cluster_handler.

Logically it wouldn't make any difference, but it tells the readers about - at what version we made a switch to the new handler and this pice of info can come in handy to debug any unforeseen issues.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwifAX-8jyAf-sgbi4D:-MwifAX-8jyAf-sgbi4E:b-f2lgwv) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L39)):*
> ```Python
>     # ToDo: Should the validation be done using a v36 client?
>     rde_validator_factory.get_validator(
>         rde_version=rde_constants.RDEVersion.RDE_2_1_0). \
> ```

I don't think we are using this file. Can you please check for the usages and delete it if we are no longer using it?
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 112 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwii93v6PnLAgSncqNn:-Mwii93v6PnLAgSncqNo:b-d5vrko) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/rde_2_1_0.py#L112)):*
> ```Python
> @dataclass_json(letter_case=LetterCase.CAMEL)
> @dataclass
> class CsiElem:
> ```

CsiElement
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 312 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwhkGJXC_tbfGmLvhSO:-MwhjLWW-5htLGTcaaGy:b-yh870x) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/rde_2_1_0.py#L312)):*
> ```Python
>             if native_entity.api_version == rde_constants.PAYLOAD_VERSION_2_1:
>                 return native_entity
>             else:
> ```

We can avoid the below logic in the else block by doing a cast like below

NativeEntity(native_entity.to_dict())

**Comment by ltimothy7** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 1585 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwig_Or8Rb5fIKKlIFy:-MwmPvPX7hT8TcOtVbCM:b-53wwba) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/installer/configure_cse.py#L1585)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you please have Sakthi or Aniruddh look at the install and upgrade logic?
</blockquote></details>

@sakthisunda Would you please take a look at the install logic?

(Upgrade logic is part of another task)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1313)* status: 10 of 18 files reviewed, 10 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/developer_guide.md, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwifnGIAedw6aNX_xlc:-MwmVX7T4CJ5wqtsSZw5:b6zg05i) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/developer_guide.md#L52)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please do update the developer_guide file with any missing info on - how to do RDE upgrades of minor versions
</blockquote></details>

Thanks Sahithi. The guide now has been helpful, and I haven't seen a need to add to the guide yet, but I will if I see this is needed.
___
*[container_service_extension/rde/constants.py, line 84 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwhdSoEDwHcNYsCC1KX:-MwmUHQg3_cJ7UrqpX6k:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/constants.py#L84)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

A separate entry needs to be made here (not override). Note that this is just RDEVersion Enum, not runtimeRDE
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 154 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwigu_w8CcjWEet6ij1:-MwmW-uGAGSWBatBJAs2:b-d0c3jb) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/constants.py#L154)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Are we going to qualify CSE 3.1.3 for any VCD version that supports API version >=37?

If yes, we need to make an entry for 37.0, please double-check with Aashima.
</blockquote></details>

As of now, it doesn't seem like we need to. If we do, I can add this entry.
___
*[container_service_extension/rde/models/common_models.py, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwihZMwERgxXKhUDE9I:-MwmUGIP2Nr7xRXpk6Ue:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/common_models.py#L83)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You need not change the DefEntityType version to 2.1

This class name just represents that a new property called "hooks" has been added to RDE TYPE by RDE framework.
</blockquote></details>

Done.



_Code quote (from container_service_extension/rde/constants.py):_
```Python
 RDE_2_1_0 
```
___
*[container_service_extension/rde/models/common_models.py, line 374 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwiho-58DtDQMtHOZ46:-MwmULgcB6IrRQCyQBKW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/common_models.py#L374)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This is good enough.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwifAX-8jyAf-sgbi4D:-MwmWuz2BNvj3QkYLiKi:b90l9e4) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L39)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't think we are using this file. Can you please check for the usages and delete it if we are no longer using it?
</blockquote></details>

Done. I have removed the v36 folder
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 49 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwieV0_0ZGAeD2WLxyU:-MwmWZHO4USzzqylr9yf:bvdsw2u) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L49)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

It should stay RDE 2.0.0 only here in this file.

What we are saying here is - anything greater than 2.0, redirect to cluster_handler.

Logically it wouldn't make any difference, but it tells the readers about - at what version we made a switch to the new handler and this pice of info can come in handy to debug any unforeseen issues.
</blockquote></details>

Thank you
Done.
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 112 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-Mwii93v6PnLAgSncqNn:-MwmUMXK5byD1WDCj3Fg:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/rde_2_1_0.py#L112)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

CsiElement
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/rde_2_1_0.py, line 312 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwhkGJXC_tbfGmLvhSO:-MwmUkQI5BelifkATFYz:bcl2gn5) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/rde_2_1_0.py#L312)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can avoid the below logic in the else block by doing a cast like below

NativeEntity(native_entity.to_dict())
</blockquote></details>

Thanks Sahithi, this is much cleaner
Done.

**Review by sahithi — APPROVED** [review]
:lgtm: I would also like Sakthi (or) Aniruddh to thoroughly review this, as I haven't been actively working on this for the past 6 months. 

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1313#-:-MwqeZrmDwyDnXR-Gniz:bkazqbu)* status: all files reviewed, 10 unresolved discussions (waiting on @ltimothy7, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_1_0.py, line 312 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1313#-MwhkGJXC_tbfGmLvhSO:-Mwqf3X3EOj1CYSG1f3j:bwk6f84) ([raw file](https://github.com/vmware/container-service-extension/blob/7cddaed985ed83a93093de0db1ec20d41b07bea0/container_service_extension/rde/models/rde_2_1_0.py#L312)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thanks Sahithi, this is much cleaner
Done.
</blockquote></details>

Hope you have tested to see if the conversion is seamless.

If it is okay I will do this testing for the upgrade workflow and have this in place for now.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1313)* status: all files reviewed, 10 unresolved discussions (waiting on @ltimothy7 and @sahithi)

**Pull request merged**
