### PR TITLE
[VCDA-1943] Move `adding TKG rights` from 'cse create-service-role' to 'cse install'

### PR DESCRIPTION
**Pull request by ChintanShahVMware**
CSE service role command creates a role in System Org.
The rights included in this role are a hard-coded list which are
necessary for CSE to operate.
The problem here was version specific.
The hard-coded list of rights include TKG specific rights as well, which
are not always present in VCD, as they were introduced in VCD 10.2. CSE
3.0.X releases are supposed to work with VCD 10.1 as well, which do not
  have TKG rights. This creates a problem in CSE service role creation.

As a fix for this problem, we are moving this process (getting this
                rights added into CSE service role) from role creation
to CSE install operation. During CSE install operation, CSE will first
check if TKG rights are present in VCD or not, and if they are, we will
add them to service role.

Current commit takes care of this process.

Signed-off-by: Chintan Shah <schintan@vmware.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875)* status: all files reviewed, 3 unresolved discussions (waiting on @ChintanShahVMware, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 738 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZXy99qsJJgNnEl6m:-MQyZXyA7uVszvW0j0X6:b-3s8mh4) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L738)):*
> ```Python
> 
> 
> def _update_user_role_with_necessary_right_bundles(client: Client,
> ```

I think specifying native and tkg rights in this function name would be clearer
___
*[container_service_extension/configure_cse.py, line 747 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZFOcB4rnFCMWO3Uj:-MQyZFOcB4rnFCMWO3Uk:b7rg8i5) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L747)):*
> ```Python
>     :param utils.ConsoleMessagePrinter msg_update_callback: Callback object.
>     :param bool log_wire: wire logging enabled
>     :rtype bool: result of operation. If the rights from any rightbundles
> ```

nit: should be "right bundles"
___
*[container_service_extension/configure_cse.py, line 752 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyYqyr595mjj6obt05:-MQyYqyr595mjj6obt06:b-dp3v2f) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L752)):*
> ```Python
>     user_role_updated = False
> 
>     if (_update_user_role_with_right_bundle(
> ```

nit: unneeded parenthesis around this function call; same for if-clause below

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875)* status: all files reviewed, 6 unresolved discussions (waiting on @ChintanShahVMware and @sahithi)

___
*[container_service_extension/configure_cse.py, line 759 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5wqXM7REWihiON6lm:-MR5wqXM7REWihiON6ln:b1i5w76) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L759)):*
> ```Python
>             log_wire=log_wire)):
> 
>         user_role_updated = True
> ```

So if just one of the if block fails, we are counting it as role updated, with no error.
I think we should just raise exception instead of passing around booleans. If any error occurs during role updating, we are potentially dealing with an improper role and it should be notified to the user.
___
*[container_service_extension/configure_cse.py, line 852 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5wgS29tw-IMeK3_57:-MR5wgS36DXfqpkbY6KZ:b-13l7mv) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L852)):*
> ```Python
>         # Update user's role with right bundle associated with native defined
>         # entity
>         if(_update_user_role_with_necessary_right_bundles(
> ```

If the right updation fails for whatever reason, we do nothing and just move on, this doesn't seem right to me.
___
*[container_service_extension/def_/utils.py, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5xwaP10u7nf6jlPvL:-MR5xwaQ0Ve0n0xMsJL7:bnzov76) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/def_/utils.py#L18)):*
> ```Python
> DEF_TKG_ENTITY_TYPE_NSS = 'tkgcluster'
> DEF_TKG_ENTITY_TYPE_VERSION = '1.0.0'
> DEF_TKG_ENTITY_TYPE_RIGHT_BUNDLE = \
> ```

If I remember correctly, Anbiruddha just made a change consolidating all the constants out of utils files. Can you please check with him.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 738 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZXy99qsJJgNnEl6m:-MRaTMygDdwigtCjAxDn:brz9f35) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L738)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think specifying native and tkg rights in this function name would be clearer
</blockquote></details>

I think function name is right; just needed to update the function description with more details. Keeping it generic like this, gives us a scope to add more right bundles in same function in future.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 738 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZXy99qsJJgNnEl6m:-MRaT_pTAtqH60X1Fe1O:bmfxipx) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L738)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

I think function name is right; just needed to update the function description with more details. Keeping it generic like this, gives us a scope to add more right bundles in same function in future.
</blockquote></details>

Updating function description.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 738 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZXy99qsJJgNnEl6m:-MRaTc_r6E59-_xYtcS5:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L738)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

Updating function description.
</blockquote></details>

Done.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 747 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyZFOcB4rnFCMWO3Uj:-MRaTecA08Xrjeipqo_Q:b-ucfknh) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L747)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: should be "right bundles"
</blockquote></details>

Thanks!

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 752 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyYqyr595mjj6obt05:-MRaTo3E3zLdy5rQGHST:b-vtmw0r) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L752)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: unneeded parenthesis around this function call; same for if-clause below
</blockquote></details>

c++ programmer Habit!
Changing it.

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 759 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5wqXM7REWihiON6lm:-MRaU27A4Z3u_suAJ3IQ:b-tssemb) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L759)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

So if just one of the if block fails, we are counting it as role updated, with no error.
I think we should just raise exception instead of passing around booleans. If any error occurs during role updating, we are potentially dealing with an improper role and it should be notified to the user.


</blockquote></details>

hmm.. What if the right bundle doesn't exist?
for an example, 10.1 doesn't have TKG right bundle... should't we silently ignore adding rights in this case?

The logic here is, add rights to right bundle if it exist, if it doesn;t just ignore it silently.

For necessary errors, we are already raising a exception in the inner function call:
_update_user_role_with_right_bundle

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875)* status: all files reviewed, 4 unresolved discussions (waiting on @ChintanShahVMware, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 752 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyYqyr595mjj6obt05:-MRaj0bS97pMHsGKt9z6:b-62cnun) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L752)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

c++ programmer Habit!
Changing it.
</blockquote></details>

No problem! Is the parenthesis showing on your screen? Or is this change not pushed. I am still seeing the parenthesis.
___
*[container_service_extension/configure_cse.py, line 759 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5wqXM7REWihiON6lm:-MRaja1C0Gs577Zxn46J:b-id5k9u) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L759)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

hmm.. What if the right bundle doesn't exist?
for an example, 10.1 doesn't have TKG right bundle... should't we silently ignore adding rights in this case?

The logic here is, add rights to right bundle if it exist, if it doesn;t just ignore it silently.

For necessary errors, we are already raising a exception in the inner function call:
_update_user_role_with_right_bundle
</blockquote></details>

Would it be possible then to only add TKG rights based on the client API version?

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 752 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MQyYqyr595mjj6obt05:-MRap5k60qOwOa68aeN7:b-a6axd4) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L752)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

No problem! Is the parenthesis showing on your screen? Or is this change not pushed. I am still seeing the parenthesis.
</blockquote></details>

haven't pushed the new change yet; addressing Aritra's comment :)

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 759 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5wqXM7REWihiON6lm:-MRapF5e1IV-FB7bgsuZ:b3sfl52) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/configure_cse.py#L759)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Would it be possible then to only add TKG rights based on the client API version?
</blockquote></details>

IMO think just checking if TKG rights are present or not is good enough

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/def_/utils.py, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5xwaP10u7nf6jlPvL:-MRaqx1L9BKiCAM2VGJ7:buit8j5) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/def_/utils.py#L18)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If I remember correctly, Anbiruddha just made a change consolidating all the constants out of utils files. Can you please check with him.
</blockquote></details>

So Aniruddha's commit is in master branch; and this review is against cse_3_0_updates branch

**Review by rocknes — APPROVED** [review]
:lgtm: once outstanding comments are addressed.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875#-:-MRbXSXu7aBBxRKiQgyP:b-c2cf9f)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/configure_cse.py, line 742 at r2](https://reviewable.io/reviews/vmware/container-service-extension/875#-MRbWiiv9JfP-WKMthLg:-MRbWiiw-3HOxp3bCzWG:b1gqdj2) ([raw file](https://github.com/vmware/container-service-extension/blob/bef7542b875bb145f4056b597e5a8bac1c089e4f/container_service_extension/configure_cse.py#L742)):*
> ```Python
>                                                    logger_debug=NULL_LOGGER,
>                                                    log_wire=False,
>                                                    config=[]):
> ```

Aniruddha mentioned few days back that empty dictionary as default param is a bad practice.
Also if we are logging out and logging back in unconditionally, we can move the code back into the main method. I don't like the fact that we are passing around the entire config. Otherwise just pass in the vcd username, password.

**Review by ltimothy7 — COMMENTED** [review]
This looks good to me; please make sure to fix the flake8 errors :)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/875#-:-MRbdR274dT2uCOT4S7Q:b549cwv)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/configure_cse.py, line 742 at r2](https://reviewable.io/reviews/vmware/container-service-extension/875#-MRbWiiv9JfP-WKMthLg:-MRcXeQ42ATDkoz6WzWt:busaxrw) ([raw file](https://github.com/vmware/container-service-extension/blob/bef7542b875bb145f4056b597e5a8bac1c089e4f/container_service_extension/configure_cse.py#L742)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Aniruddha mentioned few days back that empty dictionary as default param is a bad practice.
Also if we are logging out and logging back in unconditionally, we can move the code back into the main method. I don't like the fact that we are passing around the entire config. Otherwise just pass in the vcd username, password.
</blockquote></details>

Fixed it

**Comment by ChintanShahVMware** [comment]
___
*[container_service_extension/def_/utils.py, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/875#-MR5xwaP10u7nf6jlPvL:-MRcXiAp3C_94nx5jjo0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ea82a0122d9fe33ae36ca70232d2bf7a5916f3a1/container_service_extension/def_/utils.py#L18)):*
<details><summary><i>Previously, ChintanShahVMware wrote…</i></summary><blockquote>

So Aniruddha's commit is in master branch; and this review is against cse_3_0_updates branch
</blockquote></details>

Done.

**Pull request merged**
