### PR TITLE
[VCDA-2758] Cluster service tkgm

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
- cluster service for TKGm ova based cluster

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
deployed clusters

- (Optional) Names of reviewers using @ sign + name
@arunmk @rocknes @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1167)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1167)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1167#-Mh_96cE6UNTwkGZswtl:-Mh_96cE6UNTwkGZswtm:b-ii6upu) ([raw file](https://github.com/vmware/container-service-extension/blob/ceedab29b7789ca91c3c82cd01e5318959455000/cluster_scripts/v2_x_tkgm/control_plane.sh#L24)):*
> ```Shell
> 
>   # save image tags for later
>   if [ "$image" = "coredns" ]; then
> ```

nit: [[ ....]] double brackets are generally recommended bash supported syntax for graceful recovery on errors, where the user gets to handle the error. Single bracket abruptly breaks on any test failure. https://scriptingosx.com/2018/02/single-brackets-vs-double-brackets/

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1167#-:-Mho5b1gDEB5KKXJGl2s:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 70 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1167#-Mho1U_h8FW_9fo-Le41:-Mho1U_h8FW_9fo-Le42:bxal1nm) ([raw file](https://github.com/vmware/container-service-extension/blob/01af555fb01ff57158c51368fa0dc34dc55d2255/cluster_scripts/v2_x_tkgm/control_plane.sh#L70)):*
> ```Shell
> cp -f /etc/kubernetes/admin.conf /root/.kube/config
> chown $(id -u):$(id -g) /root/.kube/config
> export kubever=$(kubectl version --client | base64 | tr -d '\n')
> ```

I think this line can be removed. The variable `kubever` is not used anywhere in the script

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1167)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1167#-Mh_96cE6UNTwkGZswtl:-MhoH2bE7oL6bF6w47Cu:bavybqs) ([raw file](https://github.com/vmware/container-service-extension/blob/ceedab29b7789ca91c3c82cd01e5318959455000/cluster_scripts/v2_x_tkgm/control_plane.sh#L24)):*
> https://scriptingosx.com/2018/02/single-brackets-vs-double-brackets/
Thanks Sakthi
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 70 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1167#-Mho1U_h8FW_9fo-Le41:-MhoH4WuDfwfgLyWKE-U:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/01af555fb01ff57158c51368fa0dc34dc55d2255/cluster_scripts/v2_x_tkgm/control_plane.sh#L70)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this line can be removed. The variable `kubever` is not used anywhere in the script
</blockquote></details>

Done.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1167)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Pull request merged**
