### PR TITLE
[VCDA-2307] port cluster apply, delete, and create for exposed NSX-T cluster RDE 1 and 2 to main branch

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
-Ported expose NSX-T workflows to main branch for RDE 1

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested expose workflows for creating, deleting cluster and dnat rule, resize, and unexpose workflows. The worker nodes also join the cluster using the control plane node's internal IP.

PR's:
create exposed cluster: https://reviewable.io/reviews/vmware/container-service-extension/929
ipam solution: https://reviewable.io/reviews/vmware/container-service-extension/949
delete exposed cluster: https://reviewable.io/reviews/vmware/container-service-extension/951
update exposed cluster: https://reviewable.io/reviews/vmware/container-service-extension/953

- (Optional) Names of reviewers using @ sign + name
@arunmk @rocknes @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 333 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurjQ--kC_ICUnPjpi:-MYurjQ--kC_ICUnPjpj:bku6ger) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/backend/cluster_service_1_x.py#L333)):*
> ```Python
>         # Check if the desired worker and nfs count is valid and raise
>         # an exception if the cluster does not need to be unexposed
>         if not unexpose and num_workers_to_add == 0 and num_nfs_to_add == 0:
> ```

If I understand correctly, even if there are worker nodes or/and nfs nodes to be added, still raise exception based on **unexpose**
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 223 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqq6u3rpaywVwWJYs:-MYuqq6u3rpaywVwWJYt:b-svmxkw) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_1_0_0.py#L223)):*
> ```Python
>                 control_plane=control_plane,
>                 workers=workers,
>                 nfs=nfs
> ```

expose=rde_2_x_entity.spec.expose
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 233 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurPzY5tGqVRsWNUYn:-MYurPzZ0mDCNv_NO3j6:bg3p1b2) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_1_0_0.py#L233)):*
> ```Python
>                 docker_version=rde_2_x_entity.status.dockerVersion,
>                 os=rde_2_x_entity.status.os,
>                 nodes=rde_2_x_entity.status.nodes
> ```

exposed=rde_2_x.entity.status.exposed
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 229 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYupHUcCY9QvUo3SMbF:-MYupHUcCY9QvUo3SMbG:b-kkp7oj) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_2_0_0.py#L229)):*
> ```Python
>                             nodes=rde_1_x_entity.status.nodes,
>                             uid=None,
>                             cloud_properties=cloud_properties)
> ```

exposed=rde_1_x.entity.status.exposed
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 258 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqLB18RQlhFTQSVgA:-MYuqLB2ASF70UXFCNYK:b-l5aoeo) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_2_0_0.py#L258)):*
> ```Python
>                 k8_distribution=Distribution(
>                     template_name=rde_1_x_entity.spec.k8_distribution.template_name,  # noqa: E501
>                     template_revision=rde_1_x_entity.spec.k8_distribution.template_revision))  # noqa: E501
> ```

expose=rde_1_x.entity.spec.expose
___
*[container_service_extension/server/service.py, line 146 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqWH02DTgih6ouk1y:-MYuqWH02DTgih6ouk1z:b-p1kr0v) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/server/service.py#L146)):*
> ```Python
>         error_msg += f"Installed CSE RDE version ({ext_rde_in_use}) " \
>             f"is lower than the supported Server RDE version " \
>             f"({runtime_rde_version}). Upgrade CSE to update RDE."
> ```

Thanks for the fix.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 333 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurjQ--kC_ICUnPjpi:-MYvGiQ765FAnOGUcSqD:b-163ptq) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/backend/cluster_service_1_x.py#L333)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

If I understand correctly, even if there are worker nodes or/and nfs nodes to be added, still raise exception based on **unexpose**
</blockquote></details>

There will only be an exception if there is no need to unexpose the there is no change in the number of worker nodes. I will edit this error message then
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 223 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqq6u3rpaywVwWJYs:-MYvIp9vDv_LEvzQ_4v-:bm3hd9s) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_1_0_0.py#L223)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

expose=rde_2_x_entity.spec.expose
</blockquote></details>

Done. Thank you for catching this
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 233 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurPzY5tGqVRsWNUYn:-MYvJ1w9-gBb2XLm0bHv:bm3hd9s) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_1_0_0.py#L233)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

exposed=rde_2_x.entity.status.exposed
</blockquote></details>

Done. Thank you for catching this
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 229 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYupHUcCY9QvUo3SMbF:-MYvJOyP4zPPSREF8TaU:b-pt2ipc) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_2_0_0.py#L229)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

exposed=rde_1_x.entity.status.exposed
</blockquote></details>

Done. Thank you
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 258 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqLB18RQlhFTQSVgA:-MYvJgcC1BBnMAuykOrf:b-pt2ipc) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/models/rde_2_0_0.py#L258)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

expose=rde_1_x.entity.spec.expose
</blockquote></details>

Done. Thank you
___
*[container_service_extension/server/service.py, line 146 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYuqWH02DTgih6ouk1y:-MYvJhFc1v-Ec_TFVxXD:blbw6xx) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/server/service.py#L146)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Thanks for the fix.
</blockquote></details>

No problem

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 333 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurjQ--kC_ICUnPjpi:-MYvMGe1EuUbZo663pOT:bflqlfd) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/backend/cluster_service_1_x.py#L333)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

There will only be an exception if there is no need to unexpose the there is no change in the number of worker nodes. I will edit this error message then
</blockquote></details>

My question is: can there be cluster update request only to unexpose ?

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 333 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MYurjQ--kC_ICUnPjpi:-MZY_4KC1s49ldAsqfLu:b-3vcwds) ([raw file](https://github.com/vmware/container-service-extension/blob/5b795bd1d63214df6adfe64a21560460f5cc91fe/container_service_extension/rde/backend/cluster_service_1_x.py#L333)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

My question is: can there be cluster update request only to unexpose ?  
</blockquote></details>

Yes, that's right. Once the cluster has been created, you can only de-expose it, it can't be exposed at that point in time ever.
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 854 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MZYbmxkDO0EFPk8KsNa:-MZYbmxl6ydet_l9XU2m:blk6kx6) ([raw file](https://github.com/vmware/container-service-extension/blob/71fe0a47ab528f9ad4c643ca71d540367909a5ab/container_service_extension/rde/backend/cluster_service_1_x.py#L854)):*
> ```Python
>                 if def_entity.entity.status.nodes and \
>                         def_entity.entity.status.nodes.control_plane:
>                     def_entity.entity.status.nodes.control_plane.ip = expose_ip
> ```

Should n't this be just status.control_plane.ip ?

**Comment by ltimothy7** [comment]
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 854 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MZYbmxkDO0EFPk8KsNa:-MZYd12h1Q_Dx2GZjmil:bocie2) ([raw file](https://github.com/vmware/container-service-extension/blob/71fe0a47ab528f9ad4c643ca71d540367909a5ab/container_service_extension/rde/backend/cluster_service_1_x.py#L854)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should n't this be just status.control_plane.ip ?
</blockquote></details>

As of now,  I don't see a control_plane field for status

https://github.com/ltimothy7/container-service-extension/blob/3_1_nsxt_create/container_service_extension/rde/models/rde_1_0_0.py

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1015#-:-MZs3J0804H3HmQSN8sO:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 854 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1015#-MZYbmxkDO0EFPk8KsNa:-MZs28-C6TKkHQxmmYS8:b-cl0s23) ([raw file](https://github.com/vmware/container-service-extension/blob/71fe0a47ab528f9ad4c643ca71d540367909a5ab/container_service_extension/rde/backend/cluster_service_1_x.py#L854)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

As of now,  I don't see a control_plane field for status

https://github.com/ltimothy7/container-service-extension/blob/3_1_nsxt_create/container_service_extension/rde/models/rde_1_0_0.py
</blockquote></details>

ohh my bad I didn't realize that 1.0.0 and 2.0.0 spec is different in terms of structure of the control plane section.

**Pull request merged**
