### PR TITLE
[VCDA-2193] Change CSE install and upgrade workflow to install supported templates

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Cache only the templates which are supported by the current CSE version if legacy_mode is false
* install and upgrade should only install templates supported by the currently running CSE.
* Template is supported if template['min_cse_version'] >= current_cse_version <= template['max_cse_version']
* Store template's min cse version and max cse version as part of template metadata

Testing done:
* Check if CSE install installs only the supported templates
* Check if correct error is thrown if user tries to install a template which is not supported.

Required:
* Should be merged after in-place tag 3.1 is created.

@rocknes @sahithi @sakthisunda @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW-ls9W63qCI-EfH_hj:bh71wc2) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
> ```Python
> 
>     _validate_broker_config(config['broker'],
>                             legacy_mode=config['service']['legacy_mode'],
> ```

Can we write a utils method to get the legacy_mode, instead of changing signatures of all these methods?
34.0 is going to go end of life soon and we will be able to easily remove these legacy_mode checks then.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-sbMU0tvLRIFFiMpo:-MW-sbMU0tvLRIFFiMpp:bmy334c) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L45)):*
> ```Python
> 
> 
> class RemoteTemplateManager():
> ```

I am assuming changes to this file will cover install, upgrade and template install commands, correct?
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 110 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-rTMTDxuBppaf-fcr:-MW-rTMTDxuBppaf-fcs:b-xxrhbc) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L110)):*
> ```Python
>         """Remove template descriptors which is not supported."""
>         # No need to filter templates if CSE is executed in legacy mode.
>         if self.legacy_mode:
> ```

if legacy_mode is turned on, we cannot refer to templates2.yaml, is that check placed somewhere?
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 128 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-s-V68Ot2VqLAWzz1:-MW-s-V68Ot2VqLAWzz2:bneq6y9) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L128)):*
> ```
>             template_supported_cse_versions = semantic_version.SimpleSpec(
>                 f">={template_description[RemoteTemplateKey.MIN_CSE_VERSION]},"
>                 f"<={template_description[RemoteTemplateKey.MAX_CSE_VERSION]}")
> ```
These lines will raise KeyError if CSE3.1 is referring to old templates.yaml and we would want to throw appropriate error messages to the user. Is that check being done somewhere else? if not, please raise the exception here.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW0P3Xm8OeKS6zhggGQ:b-xq4q8b) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can we write a utils method to get the legacy_mode, instead of changing signatures of all these methods?
34.0 is going to go end of life soon and we will be able to easily remove these legacy_mode checks then.
</blockquote></details>

I am not sure how that method would go. Because, when install_cse calls this method or when upgrade_cse calls this method, the values present in the config cannot be cached.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 45 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-sbMU0tvLRIFFiMpo:-MW0WU6d2OTZXXsJ1drO:bb77ufg) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L45)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I am assuming changes to this file will cover install, upgrade and template install commands, correct?
</blockquote></details>

Yes.
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 110 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-rTMTDxuBppaf-fcr:-MW19LcX66o5gj01hz8h:bxboi2) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L110)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

if legacy_mode is turned on, we cannot refer to templates2.yaml, is that check placed somewhere?
</blockquote></details>

Added validation for cookbook
___
*[container_service_extension/installer/templates/remote_template_manager.py, line 128 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-s-V68Ot2VqLAWzz1:-MW19bw1EFzDnzBdsY_6:b-o383gu) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/templates/remote_template_manager.py#L128)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>             template_supported_cse_versions = semantic_version.SimpleSpec(
>                 f">={template_description[RemoteTemplateKey.MIN_CSE_VERSION]},"
>                 f"<={template_description[RemoteTemplateKey.MAX_CSE_VERSION]}")
> ```
These lines will raise KeyError if CSE3.1 is referring to old templates.yaml and we would want to throw appropriate error messages to the user. Is that check being done somewhere else? if not, please raise the exception here.
</blockquote></details>

Done. Added validation as a separate function.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW1aAz9CoIlN03hvCfh:b-qahmoj) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I am not sure how that method would go. Because, when install_cse calls this method or when upgrade_cse calls this method, the values present in the config cannot be cached.
</blockquote></details>

One way to do this in a separate file.  See if this works.

global IS_LEGACY_MODE

@run_once
def init_legacy_mode(is_legacy_mode: bool):
....global IS_LEGACY_MODE
....IS_LEGACY_MODE = is_legacy_mode

def is_legacy_mode() -> bool:
...global IS_LEGACY_MODE
...return IS_LEGACY_MODE

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW1cO9pEG5QAGWGZK_x:b9dzebs) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

One way to do this in a separate file.  See if this works.

global IS_LEGACY_MODE

@run_once
def init_legacy_mode(is_legacy_mode: bool):
....global IS_LEGACY_MODE
....IS_LEGACY_MODE = is_legacy_mode

def is_legacy_mode() -> bool:
...global IS_LEGACY_MODE
...return IS_LEGACY_MODE


</blockquote></details>

@run_once decorator is present in common/utils/init_utils.py

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW3UAjyAxcQReGiSJvw:b-gnwkef) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

@run_once decorator is present in common/utils/init_utils.py
</blockquote></details>

All these methods are stateless .. you pass in a config file to the top method and sections of it are passed around to different sub methods to validate individual sections. These methods are private, so the signature changing shouldn't affect any external consumer.

Adding a global state in a separate file is not the ideal way in my opinion.
We can have the variable in the module scope and set it in the top level method and access it in the other methods as follows

var = None


def top_method():
  global var
  var = some value

def inner_method1():
  global var
  if var == something:
   do something else


As far as the remote_template manager is concerned, I think passing it the legacy mode flag is the right thing to do.
When we remove the legacy_mode related code, the param can be removed too. Not having the param doesn't excuse us from the work of removing legacy mode related code in those methods anyways.
___
*[container_service_extension/installer/configure_cse.py, line 1269 at r2](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW3VKnYCWKG0f5AZM_S:-MW3VKnZ3l8dTmy1jUrb:b-am36js) ([raw file](https://github.com/vmware/container-service-extension/blob/a20012f070cdb6cad44f0973c1dd81d9a01a0bd4/container_service_extension/installer/configure_cse.py#L1269)):*
> ```Python
>                     msg_update_callback=msg_update_callback)
> 
>         if not found_template:
> ```

I will suggest have two booleans to detect absence and incompatibility of the template separately.
Any error message with `this happen because X or Y` is not a good error message. If we know the reason we should be as precise as possible.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: 1 of 8 files reviewed, 5 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MW6nf6rAjxbDdKQRbIz:b-h99nfs) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

All these methods are stateless .. you pass in a config file to the top method and sections of it are passed around to different sub methods to validate individual sections. These methods are private, so the signature changing shouldn't affect any external consumer.

Adding a global state in a separate file is not the ideal way in my opinion.
We can have the variable in the module scope and set it in the top level method and access it in the other methods as follows

var = None


def top_method():
  global var
  var = some value

def inner_method1():
  global var
  if var == something:
   do something else


As far as the remote_template manager is concerned, I think passing it the legacy mode flag is the right thing to do.
When we remove the legacy_mode related code, the param can be removed too. Not having the param doesn't excuse us from the work of removing legacy mode related code in those methods anyways.

</blockquote></details>

made legacy_mode a global variable in the module configure_cse.py
___
*[container_service_extension/installer/configure_cse.py, line 1269 at r2](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW3VKnYCWKG0f5AZM_S:-MW8HtHu-V4Kt9yP2rgF:bqgamma) ([raw file](https://github.com/vmware/container-service-extension/blob/a20012f070cdb6cad44f0973c1dd81d9a01a0bd4/container_service_extension/installer/configure_cse.py#L1269)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I will suggest have two booleans to detect absence and incompatibility of the template separately.
Any error message with `this happen because X or Y` is not a good error message. If we know the reason we should be as precise as possible.
</blockquote></details>

Made changes to detect incompatibility of the template

**Review by sahithi — CHANGES_REQUESTED** [review]
:lgtm:  

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958#-:-MWPyTnBA8CbreTsPGVF:b593w5t)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 150 at r1](https://reviewable.io/reviews/vmware/container-service-extension/958#-MW-ls9W63qCI-EfH_hi:-MWPkfxECasBRjI58LJh:b-s9n8jy) ([raw file](https://github.com/vmware/container-service-extension/blob/bf002428352ccc15d6698e42382157f4f1ae8b0d/container_service_extension/installer/config_validator.py#L150)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

made legacy_mode a global variable in the module configure_cse.py
</blockquote></details>

My original idea was to make the legacy_mode a global variable across the CSE code base for server runtime, install and upgrade. I don't want to derail this PR with this topic. We can take this up as a separate PR if needed.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958#-:-MWPyhLSCGTpO0-47zI5:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958#-:-MWVUS8LCJWJYeLixBDQ:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 1114 at r3](https://reviewable.io/reviews/vmware/container-service-extension/958#-MWVQYzrErt5lkVM9t5_:-MWVQYzs9GDHgw5mfJje:b-k7bqcq) ([raw file](https://github.com/vmware/container-service-extension/blob/ef10cb5d64187f43f594e359081b23784c6d9dd3/container_service_extension/installer/configure_cse.py#L1114)):*
> ```Python
>     if LEGACY_MODE:
>         msg = "Skipping template metadata update as " \
>               "CSE is executed in legacy mode."
> ```

nit: executed -> configured
___
*[container_service_extension/installer/configure_cse.py, line 1375 at r3](https://reviewable.io/reviews/vmware/container-service-extension/958#-MWVRkNB2B72qTn3uuB2:-MWVRkNB2B72qTn3uuB3:b-adj5pf) ([raw file](https://github.com/vmware/container-service-extension/blob/ef10cb5d64187f43f594e359081b23784c6d9dd3/container_service_extension/installer/configure_cse.py#L1375)):*
> ```Python
>         rtm = RemoteTemplateManager(
>             remote_template_cookbook_url=config['broker']['remote_template_cookbook_url'], # noqa: E501
>             legacy_mode=config['service']['legacy_mode'],
> ```

Use the variable LEGACY_MODE?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/configure_cse.py, line 1114 at r3](https://reviewable.io/reviews/vmware/container-service-extension/958#-MWVQYzrErt5lkVM9t5_:-MWVb7kW0Hm1xQ1z51HM:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ef10cb5d64187f43f594e359081b23784c6d9dd3/container_service_extension/installer/configure_cse.py#L1114)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: executed -> configured
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/958)* status: 6 of 9 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 1375 at r3](https://reviewable.io/reviews/vmware/container-service-extension/958#-MWVRkNB2B72qTn3uuB2:-MWVj8bAC3ZqxCKMdE3z:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ef10cb5d64187f43f594e359081b23784c6d9dd3/container_service_extension/installer/configure_cse.py#L1375)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Use the variable LEGACY_MODE?
</blockquote></details>

Done.

**Pull request merged**
