### PR TITLE
[VCDA-3206] Avoid waiting on behavior task in the Native API kubeconfig handler

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Using cluster service function for getting kubeconfig
Tested getting TKGm and native kubeconfig

- (Optional) Names of reviewers using @ sign + name
@sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1276)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1276#-:-MsaP-LFCNTBJyyOhlSY:bg7igkv)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/common/constants/server_constants.py, line 807 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaOZuLC3NoZDmYcH_f:-MsaOZuLC3NoZDmYcH_g:b-7rkvvm) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/common/constants/server_constants.py#L807)):*
> ```Python
> MAX_RDE_UPDATE_ATTEMPTS = 10
> 
> RESULT_MESSAGE_KEY = "result"
> ```


Can you rename these to BEHAVIOR_TASK_RESPONSE_RESULT_MESSAGE_KEY and BEHAVIOR_TASK_RESPONSE_RESULT_CONTENT_MESSAGE_KEY ? 

Also, add a comment that these are some of the keys of the Behavior task response that gets sent out to VCD.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1276)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaQrrhEDhw2maJBmlM:-MsaQrriCYw2HrrY1FoE:b-xb4dv6) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/rde/backend/cluster_service_factory.py#L17)):*
> ```Python
> 
> class ClusterServiceFactory:
>     def __init__(self, req_ctx: behavior_ctx.RequestContext):
> ```

This is not rue right? We can invoke this factory without invoking a behavior. In that case, we won't have a proper behavior context to pass.
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 183 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaRUNH2jb93rK2NeaW:-MsaRUNH2jb93rK2NeaX:bkzse61) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/server/request_handlers/cluster_handler.py#L183)):*
> ```Python
>     svc = cluster_service_factory.ClusterServiceFactory(_get_request_context(op_ctx)).get_cluster_service()  # noqa: E501
>     config_dict = svc.get_cluster_config(cluster_id)
> ```

Let's not get rid of the telemetry call.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1276)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/common/constants/server_constants.py, line 807 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaOZuLC3NoZDmYcH_f:-MsaVpFA9d5qgc57pAeF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/common/constants/server_constants.py#L807)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>


Can you rename these to BEHAVIOR_TASK_RESPONSE_RESULT_MESSAGE_KEY and BEHAVIOR_TASK_RESPONSE_RESULT_CONTENT_MESSAGE_KEY ? 

Also, add a comment that these are some of the keys of the Behavior task response that gets sent out to VCD.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 17 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaQrrhEDhw2maJBmlM:-MsaVnKv1QcOfPWZUr7l:b5k49r6) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/rde/backend/cluster_service_factory.py#L17)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is not rue right? We can invoke this factory without invoking a behavior. In that case, we won't have a proper behavior context to pass.
</blockquote></details>

Done. Thanks for catching this
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 183 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1276#-MsaRUNH2jb93rK2NeaW:-MsaakY55bNWIuyfMRfV:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/5d5f6d90ab809cb4ade6ee6e98fe142d7f17bf77/container_service_extension/server/request_handlers/cluster_handler.py#L183)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Let's not get rid of the telemetry call.
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1276#-:-MsgVUM3AGe7wb7LP0jl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Pull request merged**
