### PR TITLE
[VCDA-2195] Print template verification messages on console in CSE run

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Load only the templates which are supported during CSE run.
* Print message on the console if template (with required metadata keys) is not valid for the given CSE version

Testing done:
* CSE run with an unsupported template
Screen Shot 2021-03-23 at 4 23 44 PM

@sahithi @rocknes @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/968)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/968)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/968#-:-MWaHzBw1gnpFAlxqTeF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/installer/templates/local_template_manager.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/968#-MWaHe932tQRa0wqOZJN:-MWaHe947U8wzNCbyDh2:b3thgyn) ([raw file](https://github.com/vmware/container-service-extension/blob/b27eb3decb0c8cd9b215c2ad51f2dcd0b5058c37/container_service_extension/installer/templates/local_template_manager.py#L109)):*
> ```Python
> 
>         if not legacy_mode:
>             # Do not load the template in legacy_mode if
> ```

nit: in *non* legacy mode ?
___
*[container_service_extension/server/service.py, line 621 at r1](https://reviewable.io/reviews/vmware/container-service-extension/968#-MWaHrOuBBrUDlLle91y:-MWaHrOuBBrUDlLle91z:bskb6uk) ([raw file](https://github.com/vmware/container-service-extension/blob/b27eb3decb0c8cd9b215c2ad51f2dcd0b5058c37/container_service_extension/server/service.py#L621)):*
> ```
> api_version >= float(vCDApiVersion.VERSION_35.value)
> ```
this condition is same as legacy_mode == False

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/968)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @sakthisunda)

___
*[container_service_extension/installer/templates/local_template_manager.py, line 109 at r1](https://reviewable.io/reviews/vmware/container-service-extension/968#-MWaHe932tQRa0wqOZJN:-MWamWI18hshBZz9mF6X:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b27eb3decb0c8cd9b215c2ad51f2dcd0b5058c37/container_service_extension/installer/templates/local_template_manager.py#L109)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: in *non* legacy mode ?
</blockquote></details>

Done.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/968)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @sakthisunda)

___
*[container_service_extension/server/service.py, line 621 at r1](https://reviewable.io/reviews/vmware/container-service-extension/968#-MWaHrOuBBrUDlLle91y:-MWexHwO5F2dxMv-Tv65:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b27eb3decb0c8cd9b215c2ad51f2dcd0b5058c37/container_service_extension/server/service.py#L621)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

> ```
> api_version >= float(vCDApiVersion.VERSION_35.value)
> ```
this condition is same as legacy_mode == False
</blockquote></details>

Done.

**Pull request merged**
