### PR TITLE
[VCDA-2578, VCDA-2108, VCDA-2262] Cluster share fix and system user cluster sharing

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested sharing, unsharing, and sharing list for native and TKG system and non-system users

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1083)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor question.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1083#-:-McyjQcLCwk6NZEgvxDH:bu99n2)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/rde/models/common_models.py, line 144 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1083#-Mct_oPXEm0oN9cktuTA:-Mct_oPXEm0oN9cktuTB:b-j1jpyk) ([raw file](https://github.com/vmware/container-service-extension/blob/5c8a57a43f4a7c9fd4853600b121c2e74fbd1046/container_service_extension/rde/models/common_models.py#L144)):*
> ```Python
>     owner: Optional[Owner] = None
>     org: Optional[Org] = None
>     metadataSummary: Optional[list] = None
> ```

Are we not ignoring `metadataSummary` ?
Is DefEntity(**entity_dict) raising an exception?

**Comment by ltimothy7** [comment]
___
*[container_service_extension/rde/models/common_models.py, line 144 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1083#-Mct_oPXEm0oN9cktuTA:-Md4Fm1q0Hy34xsnb3iR:bl5tyfk) ([raw file](https://github.com/vmware/container-service-extension/blob/5c8a57a43f4a7c9fd4853600b121c2e74fbd1046/container_service_extension/rde/models/common_models.py#L144)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we not ignoring `metadataSummary` ?
Is DefEntity(**entity_dict) raising an exception?
</blockquote></details>

Thanks Aniruddha, This is no longer needed, it was raising an exception

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 663 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1083#-Md4IOYnEcwGvae2Yxi6:-Md4IOYo4z1IVvHoOH4g:b-rt0kr2) ([raw file](https://github.com/vmware/container-service-extension/blob/67bc5c048cfddda8c050cc6d2a5d0c956b4fb190/container_service_extension/common/utils/pyvcloud_utils.py#L663)):*
> ```Python
>             client=client,
>             resource=org_obj)
>         if org.get_vdc(vdc_name) is not None:
> ```

This function can possibly become really costly.There were customers who had thousands of orgs and thousands of vdcs in each org. I think it is better to use typed query like
https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/client.py#L1599
instead of iterating over orgs

**Review by sahithi — APPROVED** [review]
:lgtm: (few comments)
Tim, I could not review the correctness of the logical workflow as I don't remember the full context. I suggest demonstrating this piece in our next demo as a refresher to all of us.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1083#-:-MdJ4X8SCiUnAC4Nu1UK:b-86mn3t)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/common/constants/shared_constants.py, line 84 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1083#-MdJ0qrbE0iUyv9Ij18S:-MdJ0qrbE0iUyv9Ij18T:b-vvgcve) ([raw file](https://github.com/vmware/container-service-extension/blob/7ba13e5eae61942ce440e7a76257c85db5312a28/container_service_extension/common/constants/shared_constants.py#L84)):*
> ```Python
> 
> # System org constants
> SYSTEM_ORG_NAME = 'system'
> ```

Don't we already have System constant declared somewhere?
___
*[container_service_extension/rde/models/common_models.py, line 190 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1083#-MdJ3NPd6jwDuoQSFD1_:-MdJ3NPd6jwDuoQSFD1a:b-w51vb5) ([raw file](https://github.com/vmware/container-service-extension/blob/7ba13e5eae61942ce440e7a76257c85db5312a28/container_service_extension/rde/models/common_models.py#L190)):*
> ```Python
> 
> @dataclass()
> class ClusterAclEntry:
> ```

I suggest using dataclass_json annotation to enable snake case fields in the python code.
This will enable easy conversions between JSON payloads.

Please add a TODO if you want to take this task up later.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1083)* status: 10 of 19 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/common/constants/shared_constants.py, line 84 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1083#-MdJ0qrbE0iUyv9Ij18S:-MdJTQO0-btIAdlFpbUk:brpwrxs) ([raw file](https://github.com/vmware/container-service-extension/blob/7ba13e5eae61942ce440e7a76257c85db5312a28/container_service_extension/common/constants/shared_constants.py#L84)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Don't we already have System constant declared somewhere?
</blockquote></details>

Yes, I needed to move it to shared_constants so that `de_cluster_tkg` could use the constant
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 663 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1083#-Md4IOYnEcwGvae2Yxi6:-MdJTXA3AHzpQo-Nrhx9:b-fv86ee) ([raw file](https://github.com/vmware/container-service-extension/blob/67bc5c048cfddda8c050cc6d2a5d0c956b4fb190/container_service_extension/common/utils/pyvcloud_utils.py#L663)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This function can possibly become really costly.There were customers who had thousands of orgs and thousands of vdcs in each org. I think it is better to use typed query like
https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcd/client.py#L1599
instead of iterating over orgs
</blockquote></details>

Done. Thanks Aniruddha
___
*[container_service_extension/rde/models/common_models.py, line 190 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1083#-MdJ3NPd6jwDuoQSFD1_:-MdJT_JEBqkJ5Qo-eXCI:bj8s7iy) ([raw file](https://github.com/vmware/container-service-extension/blob/7ba13e5eae61942ce440e7a76257c85db5312a28/container_service_extension/rde/models/common_models.py#L190)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest using dataclass_json annotation to enable snake case fields in the python code.
This will enable easy conversions between JSON payloads.

Please add a TODO if you want to take this task up later.
</blockquote></details>

Done. Thank you, this is now a dataclass_json

**Pull request merged**
