### PR TITLE
[VCDA-2320] updated contributor docs

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

Updated contribution guide for CSE

@sakthisunda @sahithi @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013)

### CODE REVIEW

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/developer_guide.md, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYflfZt6ShXu-wpe3em:-MYflfZt6ShXu-wpe3en:b-70mvh3) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L76)):*
> ```Markdown
> ## CSE start-up
> 1. Make sure feature flags, VCD api version in extension are not changed after CSE install/upgrade
> 2. Ensure that un-supported templates are not loaded into runtime config.
> ```

unsupported templates
___
*[container_service_extension/developer_guide.md, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYflcBi074MxVKS3Lhm:-MYflcBjDEFJhpngvK4-:blsx11s) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L88)):*
> ```Markdown
> 1. Update any new NativeEntity models with sample_native_entity()
> 2. Ensure proper mapping between VCD api version and Runtime RDE version for all supported VCD API versions are available.
> 3. Update mappings in command_filter.py and make sure right commands are exposed at the right API versions
> ```

rigt command/sub-commands

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013#-:-MYfnFg9E4I3nX8E2w7h:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/developer_guide.md, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYfnbKO1LJkpblwgpU8:-MYfnbKO1LJkpblwgpU9:bn25gc) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L91)):*
> ```Markdown
> 4. Auto-negotiate the VCD api version to be used to communicate with CSE server.
>    - Update the CSE CLI supported API version set.
> 5. Dynamically compute the RDE version to use based on the CSE server side configuration.
> ```

Ensure the right clouapi endpoint is used for listing and info on clusters (defined entities).

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/developer_guide.md, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYflfZt6ShXu-wpe3em:-MYhOi9B2vW0in0pw2dS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L76)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

unsupported templates
</blockquote></details>

Done.
___
*[container_service_extension/developer_guide.md, line 88 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYflcBi074MxVKS3Lhm:-MYhOqKZ2ap7t2KJUAZw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L88)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

rigt command/sub-commands
</blockquote></details>

Done.
___
*[container_service_extension/developer_guide.md, line 91 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MYfnbKO1LJkpblwgpU8:-MYhPApJ1yh2NekiD33Z:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b8f9945dc3e634d935f012158a48de9fe95b10c7/container_service_extension/developer_guide.md#L91)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Ensure the right clouapi endpoint is used for listing and info on clusters (defined entities).
</blockquote></details>

Done.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1013)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/developer_guide.md, line 8 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1013#-MZTpAUA0Y70qKOJPfhv:-MZTpAUA0Y70qKOJPfhw:b-turglj) ([raw file](https://github.com/vmware/container-service-extension/blob/388f90b5baaf729bcaef174251bbe34977c7d81a/container_service_extension/developer_guide.md#L8)):*
> ```Markdown
> # Server
> 
> ## Terminologies
> ```

nit: Terminology

**Pull request merged**
