### PR TITLE
[VCDA-2391] Schema changes for matching TKG RDE type

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Schema changes to match TKG RDE:
Rename metadata.ovdcName -> metadata.VirtualDatacenterName (should match that of TKGs).
Rename spec.K8Distribution -> spec.distribution
spec.controlPlane, spec.nfs, spec.workers should move to spec.topology.controlPlane, spec.topology.nfs, spec.topology.nfs  respectively.

Testing done:
Cluster create (TODO)
Cluster resize. (TODO)
Cluster upgrade. (TODO)
CSE upgrade. (TODO)

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
Aniruddh, changes in schema_2_0_0.json are missing. 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024#-:-MZYhwQr97e7DzE02Owz:b-m7a434)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/behaviors/behavior_model.py, line 65 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZYhLbc43WO8P_J8wAQ:-MZYhLbc43WO8P_J8wAR:baxruki) ([raw file](https://github.com/vmware/container-service-extension/blob/69b396045aba3a36f0ae4cec704e3d11ae13a65a/container_service_extension/rde/behaviors/behavior_model.py#L65)):*
> ```Python
> class Behavior:
>     name: str
>     description: Optional[str] = None
> ```

Can you remind me of the benefits of Optional? Does it make any difference in the way dict to object are converted (or) vice versa?
Is it just a plain indicator that param is Optional?

**Review by sahithi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
@sahithi Sorry about that, i forgot to add the schema file changes in the previous commit

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/behaviors/behavior_model.py, line 65 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZYhLbc43WO8P_J8wAQ:-MZYlEb30aG98sKgVqhP:byui4r3) ([raw file](https://github.com/vmware/container-service-extension/blob/69b396045aba3a36f0ae4cec704e3d11ae13a65a/container_service_extension/rde/behaviors/behavior_model.py#L65)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you remind me of the benefits of Optional? Does it make any difference in the way dict to object are converted (or) vice versa?
Is it just a plain indicator that param is Optional?
</blockquote></details>

Optional when used with dataclasses-json will prevent errors if the value for the property is set to None.
But in general, Optional is just an indicator to static type checker that the value can be None.

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1006 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZZRlvb06UVHhzuIszD:-MZZRlvb06UVHhzuIszE:b-g3trf8) ([raw file](https://github.com/vmware/container-service-extension/blob/91832a7386c4cb8a370f6c29a4e8423a17bdc9dc/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1006)):*
> ```
>             desired_worker_count: int = cluster_spec.spec.workers.count
>             desired_nfs_count: int = cluster_spec.spec.nfs.count
> ```
cluster_spec.spec.topology.workers.count
cluster_spec.spec.topology.nfs.count

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1006 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZZRlvb06UVHhzuIszD:-MZn6obt5WtLs98zGnSW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91832a7386c4cb8a370f6c29a4e8423a17bdc9dc/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1006)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
>             desired_worker_count: int = cluster_spec.spec.workers.count
>             desired_nfs_count: int = cluster_spec.spec.nfs.count
> ```
cluster_spec.spec.topology.workers.count
cluster_spec.spec.topology.nfs.count
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r1, 3 of 3 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 181 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZs0oft5puUwQS7Jnb7:-MZs0ofu0fQFFCnh3QN1:b-ww6xgz) ([raw file](https://github.com/vmware/container-service-extension/blob/f14280e05f416255d44251ec2c5052e51b977cb2/container_service_extension/rde/models/rde_2_0_0.py#L181)):*
> ```Python
>         "metadata": {
>             "org_name": "org1",
>             "virtualDataCenterName": "ovdc1",
> ```

shouldn't this be camel case?
___
*[cse_def_schema/schema_2_0_0.json, line 2 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZs1HbRAIKfSvgdyAfS:-MZs1HbRAIKfSvgdyAfT:bhogej) ([raw file](https://github.com/vmware/container-service-extension/blob/cd5ff40e740789f312474cc39ab5844de42dcc32/cse_def_schema/schema_2_0_0.json#L2)):*
> ```JSON
> {
>         "definitions": {
> ```

Will the file location change impact cse install/upgrade?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 181 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZs0oft5puUwQS7Jnb7:-MZsFZ41Aj5f_QZ_txmm:b-iv1dc0) ([raw file](https://github.com/vmware/container-service-extension/blob/f14280e05f416255d44251ec2c5052e51b977cb2/container_service_extension/rde/models/rde_2_0_0.py#L181)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't this be camel case?
</blockquote></details>

Thanks for catching.
Done.

**Comment by Anirudh9794** [comment]
___
*[cse_def_schema/schema_2_0_0.json, line 2 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1024#-MZs1HbRAIKfSvgdyAfS:-MZsFdV441HgECTY3K6Q:b-drecss) ([raw file](https://github.com/vmware/container-service-extension/blob/cd5ff40e740789f312474cc39ab5844de42dcc32/cse_def_schema/schema_2_0_0.json#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Will the file location change impact cse install/upgrade?
</blockquote></details>

The file location has not changed. The unused schema under cse_def_schema/api_v35/ was just deleted.

**Review by sahithi — COMMENTED** [review]
:lgtm: 
Please ensure - "All the first-level properties in the schema and models must allow additional properties".

> Reviewed 3 of 3 files at r2, 8 of 9 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024#-:-MZsnFbZ7bzJpnwxDj63:b-hs0nzw)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

**Review by Anirudh9794 — COMMENTED** [review]
> All the first-level properties in the schema and models must allow additional properties".
"metadata", "spec", "status"  all allow additional properties.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024#-:-MZtAsHtEQ_925gB1cOd:bnrksln)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1024#-:-MZthKXs8t3I_SOB_SHs:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @sahithi and @sakthisunda)

**Pull request merged**
