### PR TITLE
[VCDA-2588] Set up environment for RDE based tests

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

- copy system_tests to system_tests_v2 which contain tests for RDE based operations
- add functions in system tests framework module to help create and teardown environment for RDE based tests.
  - added new role cluster_admin and cluster_author. (No module to clean up the roles created though)
  - Add support for MQTT in system tests
  - Create base_config.yaml with legacy_mode: false

Testing done:
- Run` test_cse_server.py` and make sure all the tests pass

@rocknes @sakthisunda @sahithi @ltimothy7 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070)

### CODE REVIEW

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/system_test_framework/environment.py, line 70 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_T0R2hNWaqWIy5Fq:-MfZ_T0R2hNWaqWIy5Fr:b2zpd45) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L70)):*
> ```Python
> 
> # required user info
> SYS_ADMIN_NAME = 'sys_admin'
> ```

I think we need to add the OrgAdmin user as well here
___
*[container_service_extension/system_test_framework/environment.py, line 386 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_3EGE5_5cd6kGwgB:-MfZ_3EGE5_5cd6kGwgC:b-6yehul) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L386)):*
> ```Python
>     assert result.exit_code == 0
>     result = CLI_RUNNER.invoke(
>         vcd, ['role', 'clone', ORG_ADMIN_ROLE_NAME, CLUSTER_ADMIN_ROLE_NAME],
> ```

I think ClusterAdmin role is vAppAuthor role + some rights. Not OrgAdmin role.
___
*[container_service_extension/system_test_framework/environment.py, line 417 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_MV64SN25PWbsk_v:-MfZ_MV64SN25PWbsk_w:b-4ohbbo) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L417)):*
> ```Python
>                                       result.output)
>     # Add View right for other published catalogs
>     result = CLI_RUNNER.invoke(
> ```

This role should be created by OrgAdmin user
___
*[system_tests_v2/test_cse_server.py, line 67 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZak7V4mxNVEG2kgaR:-MfZak7V4mxNVEG2kgaS:bbsrovo) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/system_tests_v2/test_cse_server.py#L67)):*
> ```Python
> 
> 
> def _remove_cse_artifacts():
> ```

We should cleanup roles and users as well here

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[container_service_extension/system_test_framework/environment.py, line 386 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_3EGE5_5cd6kGwgB:-Mf_3ZRX2wI5Zg1hleMS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L386)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think ClusterAdmin role is vAppAuthor role + some rights. Not OrgAdmin role.
</blockquote></details>

Done.
___
*[container_service_extension/system_test_framework/environment.py, line 417 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_MV64SN25PWbsk_v:-Mf_4X8Z1uionxFSn_jv:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L417)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This role should be created by OrgAdmin user
</blockquote></details>

Done.
___
*[system_tests_v2/test_cse_server.py, line 67 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZak7V4mxNVEG2kgaR:-Mf_AAOlA_nCD2euuQuO:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/system_tests_v2/test_cse_server.py#L67)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

We should cleanup roles and users as well here
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/system_test_framework/environment.py, line 70 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MfZ_T0R2hNWaqWIy5Fq:-Mfc_UFY369sthSLYfYa:biwveuj) ([raw file](https://github.com/vmware/container-service-extension/blob/39fc58cf81e69d2fe09272f13c2a732f52e702d6/container_service_extension/system_test_framework/environment.py#L70)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think we need to add the OrgAdmin user as well here
</blockquote></details>

Cluster Author role is cloned from org admin role and the tests use Cluster Author role

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 7 files at r1, 1 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070#-:-MgGySqY8oytRMQHZfYG:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @arunmk)

___
*[container_service_extension/system_test_framework/environment.py, line 535 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGwUMj2WtwvudgRjW4:-MgGwUMk1Bb2IHui1-Qm:bm2pbzz) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/container_service_extension/system_test_framework/environment.py#L535)):*
> ```Python
>             org_ids=[test_org_id])
>     except Exception:
>         pass
> ```

Please log all exceptions to some log file.
___
*[container_service_extension/system_test_framework/environment.py, line 666 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGwrrPEOL8rCoEKZGc:-MgGwrrPEOL8rCoEKZGd:b-k2lo2h) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/container_service_extension/system_test_framework/environment.py#L666)):*
> ```Python
> def check_cse_registration_as_mqtt_extension():
>     mqtt_ext_manager = MQTTExtensionManager(CLIENT)
>     cse_is_registered = mqtt_ext_manager.check_extension_exists(
> ```

nit: is_cse_registered
___
*[system_tests_v2/conftest.py, line 43 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGvBBk6ZDABuSKdFb7:-MgGvBBl3WX1QeCiG5xn:b-i75uyv) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/conftest.py#L43)):*
> ```Python
> 
>     Setup tasks:
>     - create Organization Administrator if it doesn't exist
> ```

the doc seems to be referring to wrong user roles.
___
*[system_tests_v2/README.md, line 2 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGuvEqD2qyfVJCmpum:-MgGuvErAV93ojnCKsUr:b-s64uvz) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/README.md#L2)):*
> ```Markdown
> # CSE Testing
> ```

Is this file any different from its counterpart in system_test folder?
___
*[system_tests_v2/test_cse_server.py, line 76 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGxiaN3GzQexTvdDMV:-MgGxiaN3GzQexTvdDMW:b-1l6b69) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/test_cse_server.py#L76)):*
> ```Python
>         env.delete_vapp(temp_vapp_name, vdc_href=env.VDC_HREF)
>     env.delete_catalog()
>     env.unregister_cse_in_mqtt()
> ```

Should we also try to delete all leftover RDEs if any?

If a test fails, and leaves behind RDEs, these subsequent cleanup steps will never succeed.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @arunmk and @rocknes)

___
*[container_service_extension/system_test_framework/environment.py, line 535 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGwUMj2WtwvudgRjW4:-MgINf5m-EWD5397BHKS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/container_service_extension/system_test_framework/environment.py#L535)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please log all exceptions to some log file.
</blockquote></details>

Done.
___
*[system_tests_v2/conftest.py, line 43 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGvBBk6ZDABuSKdFb7:-MgIgDQG5rjQpOwG5fYf:b19roeg) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/conftest.py#L43)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

the doc seems to be referring to wrong user roles.
</blockquote></details>

Updated the docs with correct information
___
*[system_tests_v2/README.md, line 2 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGuvEqD2qyfVJCmpum:-MgIgJyu9jqrQSjPBX7t:b-bvdfpc) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/README.md#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is this file any different from its counterpart in system_test folder?
</blockquote></details>

Added a section for logging. Updated README.
___
*[system_tests_v2/test_cse_server.py, line 76 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1070#-MgGxiaN3GzQexTvdDMV:-MgIOus88A5ZxN6xYPBh:b-u8q79u) ([raw file](https://github.com/vmware/container-service-extension/blob/e80b696dcab655c10b8621310c106f656403b777/system_tests_v2/test_cse_server.py#L76)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should we also try to delete all leftover RDEs if any?

If a test fails, and leaves behind RDEs, these subsequent cleanup steps will never succeed.
</blockquote></details>

server tests don't create RDEs as of now.
I have modified code to clean up created RDEs in the client tests.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1070)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @arunmk and @rocknes)

**Pull request merged**
