### PR TITLE
[VCDA-2064, VCDA-2065] Introduce support for feature flags and `legacy_mode` to protect apis

### PR DESCRIPTION
**Pull request by rocknes**
After the shift to request dispatcher, all available CSE apis are currently exposed simultaneously. This is a deviation from CSE 3.0.0 behavior where legacy (33.0, 34.0) cluster/node/ovdc apis and defined entity based (35.0) cluster, node, ovdc apis couldn't co-exists.

To solve this problem, this PR introduces the concept of feature flags in CSE configuration file. The request dispatcher map, will have a record of feature flags that will guard certain apis. During actual dispatch of the request to handlers, if feature flag requirements are not met, then the request will be failed and never reach the handler.

Additionally, a new entry in the service section has been introduced in this PR viz. 'legacy_mode' this automatically sets two feature flags in the config (viz. 'legacy_api' and 'non_legacy_api', that helps us to restore the original CSE 3.0 behavior related to defined entity based and legacy apis inability to co-exist.

Testing done:
Ran the CSE server with 
* 'legacy_mode` set to False and verified that the legacy apis are inaccessible while the RDE apis are accessible
* 'legacy_mode' set to True and verified that the lagacy apis are accessible while the RDE apis aren't.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/config_validator.py, line 222 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzfH03-5E7_OW7ktM7:-MUzbKRc-0rM9yTILGfZ:botzfn8) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/installer/config_validator.py#L222)):*
> ```Python
>     # Convert legacy_mode flag in service_section to corresponding
>     # feature flags
>     is_legacy_mode = config['service']['legacy_mode']
> ```

just for my own understanding - Is there any reason why we have different nomenclature `legacy_mode` and `legacy_api` ?

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943#-:-MUzfYAY3sFqv680UJy6:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk, @rocknes, and @sahithi)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_dispatcher.py, line 783 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzg5_r3LqDH1_Tw6ks:-MUzg5_r3LqDH1_Tw6kt:b-5g30hn) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L783)):*
> ```Python
> 
>     import container_service_extension.server.service as cse_service
>     server_config = cse_service.Service().get_service_config()
> ```

should this call be made after checking if the service is running?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[container_service_extension/installer/config_validator.py, line 222 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzfH03-5E7_OW7ktM7:-MUzhDqV0nOr_5V-0ulN:bn49ayh) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/installer/config_validator.py#L222)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

just for my own understanding - Is there any reason why we have different nomenclature `legacy_mode` and `legacy_api` ?
</blockquote></details>

legacy_mode - is an instruction to the server to run in a certain way.
legacy_api - denotes that the particular api is legacy.

It's a very minute difference :)
___
*[container_service_extension/server/request_dispatcher.py, line 783 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzg5_r3LqDH1_Tw6ks:-MUzhXGE2AcdzMzT3PCK:bg0daeh) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L783)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should this call be made after checking if the service is running?
</blockquote></details>

If you are inside process request .. you know that the server is running :P

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_dispatcher.py, line 783 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzg5_r3LqDH1_Tw6ks:-MUziNMd1zeVAMkkR682:b10kzlx) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L783)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If you are inside process request .. you know that the server is running :P
</blockquote></details>

My bad. Sorry about that

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_dispatcher.py, line 847 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzinv_CequWU7lAGLK:-MUzinv_CequWU7lAGLL:bto8rc0) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L847)):*
> ```Python
>     # /system operations are excluded from these checks
>     if operation not in (CseOperation.SYSTEM_INFO, CseOperation.SYSTEM_UPDATE):
>         from container_service_extension.server.service import Service
> ```

I think this import can now be removed

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/server/request_dispatcher.py, line 442 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MV-oM-aEsBIKfjUuJQn:-MV-oM-aEsBIKfjUuJQo:b67b71k) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L442)):*
> ```
>                 'required_params': [],
>                 'operation': CseOperation.V35_CLUSTER_LIST,
>                 'handler': v35_cluster_handler.cluster_list,
> ```
CseOperation.V35_CLUSTER_INFO
v35_cluster_handler.cluster_info

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_dispatcher.py, line 442 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MV-oM-aEsBIKfjUuJQn:-MV2gh_IEU9idZEEWBMR:b-laz7ux) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L442)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
>                 'required_params': [],
>                 'operation': CseOperation.V35_CLUSTER_LIST,
>                 'handler': v35_cluster_handler.cluster_list,
> ```
CseOperation.V35_CLUSTER_INFO
v35_cluster_handler.cluster_info
</blockquote></details>

Great catch .. thanks Sakthi, fixed it.
___
*[container_service_extension/server/request_dispatcher.py, line 847 at r1](https://reviewable.io/reviews/vmware/container-service-extension/943#-MUzinv_CequWU7lAGLK:-MV2gdvjEXIn6TyGGwOE:b-wu4tz3) ([raw file](https://github.com/vmware/container-service-extension/blob/2d3bba94b57d36ec01c6848257c13de33d731b54/container_service_extension/server/request_dispatcher.py#L847)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this import can now be removed
</blockquote></details>

Thanks, removed it.

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/943#-:-MV2jWTaBFSHEHF7KVpj:bnfp4nl)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, @sahithi, and @sakthisunda)

**Pull request merged**
