### PR TITLE
[VCDA-1906] system-tests-in-test-org-context

### PR DESCRIPTION
**Pull request by sakthisunda**
- Run system tests in org context that is different from org that hosts the catalog 
- Default values for org context and vdc :  test-org, test-vdc
- Override these values with development environment in test section of base_config.yaml
- Update all test cases that use broker org and vdc with test org and test vdc
- Automate the creation of test org and vdc 
- Tested with both default and override values
- Executed all system tests - PASSED
------------
image
-------------
Tests passed with all changes completed:

image

@Anirudh9794 @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824)

### CODE REVIEW

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/system_test_framework/environment.py, line 224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLsTSfO7jPfN-aaY8YH:-MLsTSfO7jPfN-aaY8YI:b2imki7) ([raw file](https://github.com/vmware/container-service-extension/blob/c2433a6eef27f6885e7502da237a8d229133b35c/container_service_extension/system_test_framework/environment.py#L224)):*
> ```Python
>     """
>     config = testutils.yaml_to_dict(BASE_CONFIG_FILEPATH)
>     cmd = f"login {config['vcd']['host']} {SYSTEM_ORG_NAME} " \
> ```

Can we move the `login` command to a separate function?
___
*[container_service_extension/system_test_framework/environment.py, line 257 at r1](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLscrnz4e_5SD10GzUn:-MLscrnz4e_5SD10GzUo:bx4tmke) ([raw file](https://github.com/vmware/container-service-extension/blob/c2433a6eef27f6885e7502da237a8d229133b35c/container_service_extension/system_test_framework/environment.py#L257)):*
> ```Python
>     result = CLI_RUNNER.invoke(vcd, cmd.split(), catch_exceptions=False)
>     assert result.exit_code == 0
>     cmd = f"vdc create {vdc_name} -p {pvdc_name}"
> ```

Just a thought - Should we be using CLI commads here to create vdc and orgs as well? One disadvantage of using vcd cli to create orgs and vdcs is that if any change breaks vcd cli, CSE tests will also fail even if the failure is not associated with CSE. Any change in the vcd cli output will also break CSE tests since we are checking terms like "Already exists" in the CLI output.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/system_test_framework/environment.py, line 224 at r1](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLsTSfO7jPfN-aaY8YH:-MLsowz--KWNax_eYTlL:bjf19zm) ([raw file](https://github.com/vmware/container-service-extension/blob/c2433a6eef27f6885e7502da237a8d229133b35c/container_service_extension/system_test_framework/environment.py#L224)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can we move the `login` command to a separate function?
</blockquote></details>

Done. Using pre-existing command string.
___
*[container_service_extension/system_test_framework/environment.py, line 257 at r1](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLscrnz4e_5SD10GzUn:-MLsp4IC6PzvERKX_y-a:b-3ewen3) ([raw file](https://github.com/vmware/container-service-extension/blob/c2433a6eef27f6885e7502da237a8d229133b35c/container_service_extension/system_test_framework/environment.py#L257)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just a thought - Should we be using CLI commads here to create vdc and orgs as well? One disadvantage of using vcd cli to create orgs and vdcs is that if any change breaks vcd cli, CSE tests will also fail even if the failure is not associated with CSE. Any change in the vcd cli output will also break CSE tests since we are checking terms like "Already exists" in the CLI output.
</blockquote></details>

we rely on vcd cli in other house keeping tasks such as creating org-admin and vapp-author etc. Unless vcd cli undergoes major revamp, this seems fine IMO.

I didn't find alternative way of checking for already existing org or vcd other than checking the result object after the command execution. 

For example the result.stdout has the following information:
Error: Status code: 500/INTERNAL_SERVER_ERROR, [ f2d2a1b7-7b90-46b5-b320-ae5be09fd3c8 ] Internal Server Error
 - Could not execute JDBC batch update
 - Batch entry 0 /* Method: unknown */ /* Method: unknown */ /* insert com.vmware.vcloud.common.model.vdc.OrgProviderVdcModel */ insert into org_prov_vdc (vcpu_in_mhz, allocation_model_type, cpu_allocation_mhz, cpu_limit_mhz, org_prov_vdc_specification_id, creation_status, description, is_enabled, fast_provisioning_enabled, folder_moref, memory_allocation_mb, memory_clone_enabled, memory_limit_mb, name, net_pool_id, network_pool_universal_id, nic_quota, org_id, overprov_factor, overprov_factor_cpu, prov_vdc_id, provisioned_network_quota, sub_rp_moref, sub_rp_vc_id, thin_provision, vdc_type, version_number, vm_discovery_enabled, vm_quota, id) values (1000, 1, 0, 0, NULL, 'NOT_READY', '', 'FALSE', 'TRUE', NULL, 0, 'TRUE', 0, 'dummy-vdc', NULL, NULL, 0, 'bdee9c8c-f8da-4b6e-a80c-d3e1c91961eb'::uuid, 0.2, 0.2, '287ac10d-51ba-4973-b501-47b6e254c824'::uuid, 0, NULL, NULL, 'TRUE', 'Flex', 0, NULL, 0, 'c4b59bd0-6fe4-42f0-8903-67ca02227ba0'::uuid) was aborted: ERROR: current transaction is aborted, commands ignored until end of transaction block  Call getNextException to see other errors in the batch.
 - ERROR: current transaction is aborted, commands ignored until end of transaction block
 - ERROR: duplicate key value violates unique constraint "uk_org_prov_vdc_name"
  <b>Detail: Key (org_id, name)=(bdee9c8c-f8da-4b6e-a80c-d3e1c91961eb, dummy-vdc) already exists. <b>(request id: f2d2a1b7-7b90-46b5-b320-ae5be09fd3c8)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/system_test_framework/environment.py, line 246 at r2](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLxm62bBZJc7ZUi45Yd:-MLxm62bBZJc7ZUi45Ye:b-53ai1z) ([raw file](https://github.com/vmware/container-service-extension/blob/aad79503b8cc55dee3de5785c307e0104a417f6e/container_service_extension/system_test_framework/environment.py#L246)):*
> ```Python
>     ovdc = pyvcloud_utils.get_vdc(
>         CLIENT, vdc_name=config['broker']['vdc'], org=org, is_admin_operation=True)  # noqa: E501
>     pvdc_element = ovdc.get_resource().ProviderVdcReference
> ```

Please add a comment here that Test framework will try to create the new ovdc from the same pvdc that the catalog org is being powered by.
___
*[container_service_extension/system_test_framework/environment.py, line 255 at r2](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLxloq64Q7-cAA2h3Tt:-MLxloq7-bGR0goL5v5n:b-4v8czp) ([raw file](https://github.com/vmware/container-service-extension/blob/aad79503b8cc55dee3de5785c307e0104a417f6e/container_service_extension/system_test_framework/environment.py#L255)):*
> ```Python
>     # If the vdc already exists, skip rest of the steps and exit successfully
>     if ALREADY_EXISTS in result.stdout:
>         assert True
> ```

We can just return.
There is no need assert a True statement :)
___
*[container_service_extension/system_test_framework/environment.py, line 263 at r2](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLxmQGv9O4ZFi5xSoHo:-MLxmQGv9O4ZFi5xSoHp:b-3gemnr) ([raw file](https://github.com/vmware/container-service-extension/blob/aad79503b8cc55dee3de5785c307e0104a417f6e/container_service_extension/system_test_framework/environment.py#L263)):*
> ```Python
>         result = CLI_RUNNER.invoke(vcd, cmd.split(), catch_exceptions=False)
>         assert result.exit_code == 0
>         cmd = f"network direct create -p {config['broker']['network']} {config['broker']['network']}"  # noqa: E501
> ```

This is wrong.
We should not assume that the external network name is same as the catalog org's  orgvdc network name.
Also the network name in the test section should be used.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/system_test_framework/environment.py, line 255 at r2](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLxloq64Q7-cAA2h3Tt:-MM-DfTv8lzq77Fx-WjE:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/aad79503b8cc55dee3de5785c307e0104a417f6e/container_service_extension/system_test_framework/environment.py#L255)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We can just return.
There is no need assert a True statement :)
</blockquote></details>

Done.
___
*[container_service_extension/system_test_framework/environment.py, line 263 at r2](https://reviewable.io/reviews/vmware/container-service-extension/824#-MLxmQGv9O4ZFi5xSoHo:-MM-DgDu9tYVU1USI0oL:bq0pwkk) ([raw file](https://github.com/vmware/container-service-extension/blob/aad79503b8cc55dee3de5785c307e0104a417f6e/container_service_extension/system_test_framework/environment.py#L263)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This is wrong.
We should not assume that the external network name is same as the catalog org's  orgvdc network name.
Also the network name in the test section should be used.
</blockquote></details>

Done.  Create test network name in test section (else default). Get the parent network of catalog orgs' orgvdc network. Use that as external/parent network for test
network.

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824#-:-MMHThN0BpjHZV1hmn5P:bg7igkv)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824#-:-MMHTliV5NXwxjq2QbL_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824#-:-MMHax3c6ZpPIerGnPCy:bqfaxmu)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/824#-:-MMIJrAX39Loxr3a_YBe:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
