### PR TITLE
[VCDA-2125] Framework to accommodate multiple RDE versions

### PR DESCRIPTION
**Pull request by sahithi**
- Factory class to get cluster_service based on RDE version - _cluster_service_factory.py_
- Factory method to _get_model(rde_version)_ in  _rde/models/utils.py_
- Strategy pattern to do conversions between RDE versions.
- Factory method to _get_validator(rde_version)_ in _validators/utils.py_ and Validator files.
-

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/converters/abstract_convert_strategy.py, line 13 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTgzXK3Cy8yJMOVf46Z:-MTgzXK3Cy8yJMOVf46_:bx7f2mx) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/abstract_convert_strategy.py#L13)):*
> ```Python
> 
>     @abc.abstractmethod
>     def convert(self, data, src_rde_version: str, destn_rde_version: str):
> ```

destn_rde_version  ---> target_rde_version
___
*[container_service_extension/rde/converters/convert_strategy_1X_2X.py, line 15 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTgziVb2DRJFM4dQvlE:-MTgziVb2DRJFM4dQvlF:b-jxxp92) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/convert_strategy_1X_2X.py#L15)):*
> ```Python
>         pass
> 
>     def convert(self, data, src_rde_version, destn_rde_version):
> ```

Currently does not take/use any state variables. So, this can be @staticmethod.
destn_rde_version  ---> target_rde_version
___
*[container_service_extension/rde/converters/utils.py, line 14 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh-JX667RjUJseDEQj:-MTh-JX667RjUJseDEQk:br2rhs4) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/utils.py#L14)):*
> ```Python
>     if strategy:
>         return strategy.convert(data=data, src_rde_version=src_rde_version,
>                                 destn_rde_version=destn_rde_version)
> ```

If there is no strategy to convert, then target_rde_version and data are at minimum required parameters. The following logic may be moved to default strategy if we know the strategy upfront.
___
*[container_service_extension/rde/models/common_models.py, line 104 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh1bhQ4sJS4m6zaevm:-MTh1bhQ4sJS4m6zaevn:b-3g19va) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/models/common_models.py#L104)):*
> ```Python
>         # TODO Replace the hard-coded '1.0.0' with the dynamically retrieved
>         #  the RDE version to use
>         NativeEntityClass = model_utils.get_model('1.0.0')
> ```

This assignment looks incomplete (may be a TODO)
___
*[container_service_extension/rde/models/common_models.py, line 181 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh2b-10-obwS9N4ta5:-MTh2b-10-obwS9N4ta6:b-3g19va) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/models/common_models.py#L181)):*
> ```Python
>             # TODO Replace the hard-coded '1.0.0' with the dynamically
>             #  retrieved the RDE version to use
>             NativeEntityClass = model_utils.get_model('1.0.0')
> ```

This assignment looks incomplete (may be a TODO)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 0 of 20 files reviewed, 5 unresolved discussions (waiting on @sakthisunda and @staticmethod)

___
*[container_service_extension/rde/converters/abstract_convert_strategy.py, line 13 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTgzXK3Cy8yJMOVf46Z:-MThVo3c2enrtMwcfcE8:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/abstract_convert_strategy.py#L13)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

destn_rde_version  ---> target_rde_version
</blockquote></details>

Done.
___
*[container_service_extension/rde/converters/convert_strategy_1X_2X.py, line 15 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTgziVb2DRJFM4dQvlE:-MThVpAm8NX75Lvx0RDy:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/convert_strategy_1X_2X.py#L15)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Currently does not take/use any state variables. So, this can be @staticmethod.
destn_rde_version  ---> target_rde_version
</blockquote></details>

Done.
___
*[container_service_extension/rde/converters/utils.py, line 14 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh-JX667RjUJseDEQj:-MThVq3MEw0djrD0yE61:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/utils.py#L14)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

If there is no strategy to convert, then target_rde_version and data are at minimum required parameters. The following logic may be moved to default strategy if we know the strategy upfront.
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/common_models.py, line 104 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh1bhQ4sJS4m6zaevm:-MThVrFU4s3kqqpNlzJA:b-jrdcx8) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/models/common_models.py#L104)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

This assignment looks incomplete (may be a TODO)
</blockquote></details>

I already put a TODO on top.
___
*[container_service_extension/rde/models/common_models.py, line 181 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTh2b-10-obwS9N4ta5:-MThVtnlA1M1MSR377uO:bblhk9m) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/models/common_models.py#L181)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

This assignment looks incomplete (may be a TODO)
</blockquote></details>

There is a TODO

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/converters/abstract_convert_strategy.py, line 8 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThQ2Ih1fs51FJFQXLq:-MThQ2Ii5YhIpucFJGy1:bmojh42) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/abstract_convert_strategy.py#L8)):*
> ```Python
> 
> 
> class AbstractConvertStrategy(abc.ABC):
> ```

I did not get the use of the Abstract class in the context of converting RDE from one schema to another. If we have to create a class for every (src, destination) pair, why can we not just make use of wrapper function?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/validators/abstract_validator.py, line 13 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThdTP-93MXMt3wH_KE:-MThbpMy8rax6ImH9a-U:b-e9qwlu) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/validators/abstract_validator.py#L13)):*
> ```Python
> 
>     @abc.abstractmethod
>     def validate(self, request_spec: dict, current_spec: dict, operation: str):
> ```

Similar comment as for converters, If we have to define multiple functions for validating specs, why can't we just make use of wrapper functions.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 4 of 11 files at r3, 3 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 6 of 20 files reviewed, 4 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/validators/validator_rde_1_x.py, line 13 at r5](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThhKGCBXMfkLg21Sh5:-MThhKGD1KWrw2jebjKx:b-axb0q7) ([raw file](https://github.com/vmware/container-service-extension/blob/8d45ad5aceaf3e511a2a7105a7f2a917b2ab0934/container_service_extension/rde/validators/validator_rde_1_x.py#L13)):*
> ```Python
> 
>     def validate(self, request_spec: dict, current_spec: dict, operation: str):
>         """Validate the input_spec against current_spec.
> ```

Since each validate is specific corresponding rde version, validat() may be moved to rde_1_x.py  as part of  dataclass: ClusterSpec. It may be helpful to avoid /validators/validator_rde_x_x.py

**Review by sakthisunda — APPROVED** [review]
:lgtm: (after review comments)

> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909#-:-MTkyrhGC_U6u0QDcbmM:b-h3igdy)* status: 7 of 20 files reviewed, 3 unresolved discussions (waiting on @sahithi and @sakthisunda)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 7 of 20 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/converters/abstract_convert_strategy.py, line 8 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThQ2Ih1fs51FJFQXLq:-MTl7YwU6KgpxuOZXG6t:bh1gf4k) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/converters/abstract_convert_strategy.py#L8)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I did not get the use of the Abstract class in the context of converting RDE from one schema to another. If we have to create a class for every (src, destination) pair, why can we not just make use of wrapper function?
</blockquote></details>

We will not have to write a converter for each conversion, only for major bump-ups.
This pattern sets a standard to follow w.r.t code organization and method signatures - for all the future conversions and validations.

Take an example of what we have today- We have three validate methods with different titles and signatures across v35 and v36 handlers with methods scattered.

If we really want, we can definitely write a decorator to leverage the method in the interfaces for these converters and validators.

Btw, I will change the class name - this is no longer abstract.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 6 of 20 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/validators/abstract_validator.py, line 13 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThdTP-93MXMt3wH_KE:-MTlR-BU2alkTQes6lqi:b-g58k12) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/validators/abstract_validator.py#L13)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Similar comment as for converters, If we have to define multiple functions for validating specs, why can't we just make use of wrapper functions.
</blockquote></details>

If the current_spec is from current NativeEntity, I am wondering if validate() method itself can be part of NativeEntity that takes an external spec as parameter? Just a thought.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 4 of 15 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/validators/validator_rde_1_x.py, line 13 at r5](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThhKGCBXMfkLg21Sh5:-MTllGwo4KPL6fNq9ShX:b-16rbah) ([raw file](https://github.com/vmware/container-service-extension/blob/8d45ad5aceaf3e511a2a7105a7f2a917b2ab0934/container_service_extension/rde/validators/validator_rde_1_x.py#L13)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Since each validate is specific corresponding rde version, validat() may be moved to rde_1_x.py  as part of  dataclass: ClusterSpec. It may be helpful to avoid /validators/validator_rde_x_x.py
</blockquote></details>

Thanks for this suggestion Sakthi. This is the right way.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 5 of 15 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 6 of 15 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 6 of 15 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/validators/abstract_validator.py, line 13 at r3](https://reviewable.io/reviews/vmware/container-service-extension/909#-MThdTP-93MXMt3wH_KE:-MTmRlQA3P5N2QppcgAZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9ad50d03aaedba6696f084e56d2d9bf0159dfe15/container_service_extension/rde/validators/abstract_validator.py#L13)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

If the current_spec is from current NativeEntity, I am wondering if validate() method itself can be part of NativeEntity that takes an external spec as parameter? Just a thought.
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 15 files at r1, 1 of 4 files at r2, 11 of 11 files at r3, 1 of 4 files at r5, 3 of 3 files at r6, 3 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909#-:-MTmVr6z1fRZG603_rjQ:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1, 1 of 4 files at r2, 2 of 11 files at r3, 2 of 9 files at r4, 3 of 3 files at r6, 4 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: all files reviewed, 5 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 25 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmUvKD-DULn0LQq1VD:-MTmUvKE1MOLcGA_TD02:b9syg0z) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/backend/cluster_service_factory.py#L25)):*
> ```Python
>         rde_version: semantic_version.Version = semantic_version.Version(rde_version_in_use)  # noqa: E501
>         if rde_version.major == 1:
>             from container_service_extension.rde.backend.cluster_service_1_x import ClusterService as ClusterService1X  # noqa: E501
> ```

Are these imports causing circular dependency?

If that is the case, I would re-evaluate the code organization.

Otherwise we can move the imports to the top of the module.
___
*[container_service_extension/rde/converters/convert_strategy_1X_2X.py, line 29 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmVhB20kxCyIbUaass:-MTmVhB20kxCyIbUaast:bt7sesg) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/converters/convert_strategy_1X_2X.py#L29)):*
> ```Python
>             pass
>         elif src_rde_version < target_rde_version:
>             # TODO convert the data from 1.0 to 2.0
> ```

I think we are missing the equality case, where we just return the object as is.
___
*[container_service_extension/rde/converters/utils.py, line 7 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmWNvNB_emMcxugixy:-MTmWNvO0-Ef38Ttxqo0:b-vla8lp) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/converters/utils.py#L7)):*
> ```Python
> 
> 
> def convert(entity: dict, target_rde_version: str, src_rde_version: str = None,
> ```

Should we call this module utils?

These is more like ModelManager/ModelConverter class.
___
*[container_service_extension/rde/models/utils.py, line 6 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmXPtmAa8rbN9YfYkL:-MTmXPtnB7ltEkGIC9AO:bbprdik) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/models/utils.py#L6)):*
> ```Python
> 
> import semantic_version
> ```

Same concern as one of the previous comment, this functionality shouldn't be called an util method.
This is a core ModelMapper or ModelRetriever class

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: all files reviewed, 5 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_factory.py, line 25 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmUvKD-DULn0LQq1VD:-MTmg-jz7zr-5X3N8qrN:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/backend/cluster_service_factory.py#L25)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Are these imports causing circular dependency?

If that is the case, I would re-evaluate the code organization.

Otherwise we can move the imports to the top of the module.
</blockquote></details>

Done.
___
*[container_service_extension/rde/converters/convert_strategy_1X_2X.py, line 29 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmVhB20kxCyIbUaass:-MTmeKnHCJMCxcRULug_:bnqcv64) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/converters/convert_strategy_1X_2X.py#L29)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we are missing the equality case, where we just return the object as is.
</blockquote></details>

Equality case is handled
I just had it commented for now - "return entity"

This method raises NotImplementedError for now. I just put the high-level structure to convey what the method is supposed to do.
Developer can re-adjust it at the time of implementation as he/she deems it fit.
___
*[container_service_extension/rde/converters/utils.py, line 7 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmWNvNB_emMcxugixy:-MTmew3s5i6mhg5Py8gk:bi7i624) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/converters/utils.py#L7)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should we call this module utils?

These is more like ModelManager/ModelConverter class.
</blockquote></details>

I called it utils for now so that this file can be used as a landing file for any other util methods. What do you think? Do we need a separate file for just a single method? I am okay refactoring this as we work on it.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/909)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

___
*[container_service_extension/rde/converters/utils.py, line 7 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmWNvNB_emMcxugixy:-MTpnztxAUSdMCTkIvcO:b-i3u7rr) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/converters/utils.py#L7)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I called it utils for now so that this file can be used as a landing file for any other util methods. What do you think? Do we need a separate file for just a single method? I am okay refactoring this as we work on it.
</blockquote></details>

I renamed it to rde_converter.py
___
*[container_service_extension/rde/models/utils.py, line 6 at r7](https://reviewable.io/reviews/vmware/container-service-extension/909#-MTmXPtmAa8rbN9YfYkL:-MTpo7718Gi7iB03QK2h:b-zeqrko) ([raw file](https://github.com/vmware/container-service-extension/blob/fc50e00c363661f05479b15d27beb7784da4c02a/container_service_extension/rde/models/utils.py#L6)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Same concern as one of the previous comment, this functionality shouldn't be called an util method.
This is a core ModelMapper or ModelRetriever class
</blockquote></details>

Renamed it to rde_factory.py

**Pull request merged**
