### PR TITLE
[VCDA-3178] updated csi and cpi to 1.1.0

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1290)

### CODE REVIEW

**Comment by ltimothy7** [comment]
> [VCDA-3178] updated csi and cpi to 1.1.0
TODO: deploy a cluster for basic testing

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1290)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1290#-MuMgfGGDhMhzDSOK3zp:-MuMgfGGDhMhzDSOK3zq:b-gp9f3w) ([raw file](https://github.com/vmware/container-service-extension/blob/28fb31ae49ff0d253acd13044f7915f777a8dc86/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L76)):*
> ```Python
> # Hardcode the Antrea CNI version until there's a better way to retrieve it
> CNI_NAME = "antrea"
> ANTREA_CNI_VERSION = 'v0.11.3'
> ```

Just want to make sure there is no change for ANTREA_CNI_VERSION

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1290)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 76 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1290#-MuMgfGGDhMhzDSOK3zp:-MuMippuBfB_txBHxIPG:b-3853ig) ([raw file](https://github.com/vmware/container-service-extension/blob/28fb31ae49ff0d253acd13044f7915f777a8dc86/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L76)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Just want to make sure there is no change for ANTREA_CNI_VERSION
</blockquote></details>

@goelaashima confirmed there is no change

**Review by arunmk — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1290#-:-MuNmjeo94VWMez_qymW:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1290#-:-MuOap5jCXznBbaPa2-h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Pull request merged**
