### PR TITLE
[VCDA-2068, 2069, 2184] Remove api version from CSE upgrade/run/install

### PR DESCRIPTION
**Pull request by rocknes**
Remove usage of api version from cse install/upgrade/run
Stamp legacy mode flag on CSE extension instead of the api version in use.

Testing Done:
* Installed CSE 3.0.2, upgraded to CSE 3.1 and made sure upgrade goes through successfully.
* Re-upgraded to 3.1 to ensure idempotency of the upgrade
* Ran CSE before and after the upgrade and got correct error messages

This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/server/cli/server_cli.py, line 1240 at r1](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX8YgJg6FlcfTT9l4av:-MX8YgJg6FlcfTT9l4aw:bpylzhs) ([raw file](https://github.com/vmware/container-service-extension/blob/dad8eef35921868b06fbd8e8438006b1b7b4d081/container_service_extension/server/cli/server_cli.py#L1240)):*
> ```Python
>             retain_temp_vapp=retain_temp_vapp,
>             ssh_key=ssh_key,
>             skip_config_decryption=skip_config_decryption,
> ```

Could you explain why `skip_config_decryption` is needed but the `decryption_password` is no longer needed?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/server/cli/server_cli.py, line 1240 at r1](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX8YgJg6FlcfTT9l4av:-MX8tl6l0S7U2wb7Jdce:b-ar2t6d) ([raw file](https://github.com/vmware/container-service-extension/blob/dad8eef35921868b06fbd8e8438006b1b7b4d081/container_service_extension/server/cli/server_cli.py#L1240)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Could you explain why `skip_config_decryption` is needed but the `decryption_password` is no longer needed?
</blockquote></details>

We are still sending the skip_config_decryption value to telemetry. While the password is not being used at all.

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/server/cli/server_cli.py, line 1240 at r1](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX8YgJg6FlcfTT9l4av:-MX91H5E-yJE1OVTDBZ7:b-s622lo) ([raw file](https://github.com/vmware/container-service-extension/blob/dad8eef35921868b06fbd8e8438006b1b7b4d081/container_service_extension/server/cli/server_cli.py#L1240)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We are still sending the skip_config_decryption value to telemetry. While the password is not being used at all.
</blockquote></details>

I see, thanks

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Minor comments

> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981#-:-MX9eEQWCOAD7AmHlxyj:by0nmtq)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/common/constants/server_constants.py, line 16 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX8joTw8v73c6jS-7Zw:-MX8joTw8v73c6jS-7Zx:bjpqhoo) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/common/constants/server_constants.py#L16)):*
> ```Python
> # CSE SERVICE;
> # keys for CSE info on the extension
> CSE_VERSION_KEY = 'cse_version'
> ```

Is it better to group the keys into an Enum?
___
*[container_service_extension/installer/configure_cse.py, line 420 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9e1jm-Cw24hIOjh3W:-MX9e1jm-Cw24hIOjh3X:bbxl9fu) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L420)):*
> ```Python
>     global LEGACY_MODE
>     LEGACY_MODE = config['service']['legacy_mode']
> ```

`legacy_mode` in the extension should be validated in this function as well
___
*[container_service_extension/installer/configure_cse.py, line 662 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9bo4i5pcgvPvjeu5N:-MX9bo4i5pcgvPvjeu5O:bwpvbk) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L662)):*
> ```Python
>         # irrespective of when these patches were released.
> 
>         target_cse_running_in_legacy_mode = config['service']['legacy_mode']
> ```

I think we can use the global variable `LEGACY_MODE` here

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 958 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9gkSf0s7tEJjIYfGk:-MX9gkSf0s7tEJjIYfGl:b6vo0ql) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L958)):*
> ```Python
> 
>     :param pyvcloud.vcd.client.Client client:
>     :param pyvcloud.vcd.client.Client client:
> ```

nit: repeated docstring
___
*[container_service_extension/installer/configure_cse.py, line 2231 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9i2XEEt83_IvPFAzq:-MX9i2XEEt83_IvPFAzr:bcfbfim) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L2231)):*
> ```Python
>             raise cse_exception.CseUpgradeError(msg)
> 
>         kind = None  # Is this a correct default value?
> ```

 
'shared_constants.NATIVE_CLUSTER_RUNTIME_INTERNAL_NAME'  is better as default. just a thought

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: all files reviewed, 6 unresolved discussions (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 16 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX8joTw8v73c6jS-7Zw:-MXJY7Gg1M1D5NAP0yNx:bsfbdik) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/common/constants/server_constants.py#L16)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is it better to group the keys into an Enum?
</blockquote></details>

Yes, but let's do it when the RDE version in use in put to work.
___
*[container_service_extension/installer/configure_cse.py, line 420 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9e1jm-Cw24hIOjh3W:-MXK-w2Q9aBuYmqjhZTD:b-sf4ia5) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L420)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`legacy_mode` in the extension should be validated in this function as well
</blockquote></details>

Thanks, added the check. I didn't extract the check into a function and reused it between upgrade and install_template, since there seems to be significant differences between the error messages.
___
*[container_service_extension/installer/configure_cse.py, line 662 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9bo4i5pcgvPvjeu5N:-MXJpsmX8egoPZm8A5x3:bu34zlw) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L662)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think we can use the global variable `LEGACY_MODE` here
</blockquote></details>

thanks :-)
___
*[container_service_extension/installer/configure_cse.py, line 958 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9gkSf0s7tEJjIYfGk:-MXJw_7r3KREhIlaMn06:b-x52gbo) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L958)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

nit: repeated docstring
</blockquote></details>

Thanks, fixed.
___
*[container_service_extension/installer/configure_cse.py, line 2231 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9i2XEEt83_IvPFAzq:-MXJy5Dd5x9Le1Z-h4rw:b-1hzgvt) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L2231)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

 
'shared_constants.NATIVE_CLUSTER_RUNTIME_INTERNAL_NAME'  is better as default. just a thought

 
</blockquote></details>

fixed the logic and default value.
___
*[container_service_extension/installer/configure_cse.py, line 2294 at r2](https://reviewable.io/reviews/vmware/container-service-extension/981#-MX9jjQb7BP_8wwbpKwU:-MX9umoLDl32OcpS3QLW:b7cbsxs) ([raw file](https://github.com/vmware/container-service-extension/blob/d3904b2c7acd30fe4314fc6ff511cc00e1143dd1/container_service_extension/installer/configure_cse.py#L2294)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Please include the following metadata as in upgrade_cluster_rde. Thanks.

server_constants.ClusterMetadataKey.CSE_VERSION: server_utils.get_installed_cse_version() 
</blockquote></details>

This metadata should already exists and we shouldn't change the version of CSE which was used to create the cluster.

**Review by sakthisunda — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/981#-:-MXK6b0B8GuQrLWbBvMY:bnfp4nl)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

**Pull request merged**
