### PR TITLE
[VCDA-2285] Enable cse 3.0 legacy to cse 3.1 legacy upgrade

### PR DESCRIPTION
**Pull request by sakthisunda**
- Upgrade path for CSE 3.0 legacy mode to CSE 3.1 legacy mode
- Recreate templates option 
- Update CSE extension
- Removed --password option from CLI 
- Tested upgrade with CSE 3.0.1 api version (33,34) to CSE 3.1 legacy mode=true
- VCDA-2294, 2299 changes are also in this file

@Anirudh9794 @rocknes 

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)* status: all files reviewed, 4 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 332 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY68j3yDeZa-_8lmq0q:-MY68j3z96nKq3m1RmrC:b-uq7nlw) ([raw file](https://github.com/vmware/container-service-extension/blob/505c7d14567e3eb902c024d9e207fb8ea3cb9d19/container_service_extension/installer/configure_cse.py#L332)):*
> ```Python
>         # Setup extension based on message bus protocol
>         if server_utils.should_use_mqtt_protocol(config):
>             _register_cse_as_mqtt_extension(client, msg_update_callback)
> ```

Can you please verify all invocation of this method and make sure that we are not passing wrong params in other places too?
___
*[container_service_extension/installer/configure_cse.py, line 559 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY68tH03IS_rhG_Cmlz:-MY68tH03IS_rhG_Cmm-:baavd01) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L559)):*
> ```Python
> # CSE 3.0.x, api v34.0
> # CSE 3.0.x, api v35.0
> # api v33.0 and v34.0 will map to legacy_mode = True
> ```

Thanks for correcting this.
___
*[container_service_extension/installer/configure_cse.py, line 717 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY694yR2oc6hQQma_UK:-MY694yR2oc6hQQma_UL:b-2yzfbu) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L717)):*
> ```Python
>                 client=client,
>                 config=config,
>                 skip_template_creation=skip_template_creation,
> ```

shouldn't the ssh key be passed too, if retain_temp_vapp option is set to True?
___
*[container_service_extension/installer/configure_cse.py, line 727 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY69CFl6v0k_HbxKoPz:-MY69CFl6v0k_HbxKoQ-:b-2yzfbu) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L727)):*
> ```Python
>                 config=config,
>                 skip_template_creation=skip_template_creation,
>                 retain_temp_vapp=retain_temp_vapp,
> ```

shouldn't the ssh key be passed too, if retain_temp_vapp option is set to True?
___
*[container_service_extension/installer/configure_cse.py, line 2010 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY69SUr6th97EUzXmDs:-MY69SUr6th97EUzXmDt:b-netz4g) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L2010)):*
> ```Python
>             msg_update_callback=msg_update_callback)
> 
>     _update_cse_extension(client=client,
> ```

fyi : legacy mode can't use MQTT as message bus.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 332 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY68j3yDeZa-_8lmq0q:-MY6VkNBBW7TJAVLi-Pc:bw453ce) ([raw file](https://github.com/vmware/container-service-extension/blob/505c7d14567e3eb902c024d9e207fb8ea3cb9d19/container_service_extension/installer/configure_cse.py#L332)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can you please verify all invocation of this method and make sure that we are not passing wrong params in other places too?
</blockquote></details>

After rebasing with the latest master verified all invocations for correctness
___
*[container_service_extension/installer/configure_cse.py, line 559 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY68tH03IS_rhG_Cmlz:-MY6WOaEDcpLaM8JxOQJ:b44tpx) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L559)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Thanks for correcting this.
</blockquote></details>

👍
___
*[container_service_extension/installer/configure_cse.py, line 717 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY694yR2oc6hQQma_UK:-MY6WV8f5E-XD25UrbaP:b-qirqso) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L717)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't the ssh key be passed too, if retain_temp_vapp option is set to True?
</blockquote></details>

yes. fixed this bug rom previous code
___
*[container_service_extension/installer/configure_cse.py, line 727 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY69CFl6v0k_HbxKoPz:-MY6XPGx21urgPp5Q2uw:b-hch0js) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L727)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't the ssh key be passed too, if retain_temp_vapp option is set to True?
</blockquote></details>


yes. fixed this bug rom previous code
___
*[container_service_extension/installer/configure_cse.py, line 2010 at r1](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY69SUr6th97EUzXmDs:-MY6XRJQ-jJztkwf1i9x:blrox06) ([raw file](https://github.com/vmware/container-service-extension/blob/8402b6fb6b866356943b17791657f3ab4a05f84b/container_service_extension/installer/configure_cse.py#L2010)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

fyi : legacy mode can't use MQTT as message bus.
</blockquote></details>

Update made specific to AMQP. thanks

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Minor comment

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993#-:-MY6xApd11w9WJFd4Ij_:bo0dolh)* status: all files reviewed, 5 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 1997 at r2](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY6wigHBwT5Sju_EfsF:-MY6wigHBwT5Sju_EfsG:b-armf9p) ([raw file](https://github.com/vmware/container-service-extension/blob/44d3571c442b2f80bc2eff63498210b2a2874691/container_service_extension/installer/configure_cse.py#L1997)):*
> ```Python
>         service with the given name and namespace are found when trying to
>         delete the amqp-based extension.
>     :raises requests.exceptions.HTTPError: (when using MQTT) if the MQTT
> ```

Since legacy mode doesn't support MQTT. I the parameter description should also change

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 1997 at r2](https://reviewable.io/reviews/vmware/container-service-extension/993#-MY6wigHBwT5Sju_EfsF:-MY7TdNKEzzQqANenxH0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/44d3571c442b2f80bc2eff63498210b2a2874691/container_service_extension/installer/configure_cse.py#L1997)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since legacy mode doesn't support MQTT. I the parameter description should also change
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993#-:-MYCnI2e-5uBcfS-QEU_:bnfp4nl)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/993)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
