### PR TITLE
[VCDA-2062] Implement request dispatcher to expose CSE REST api at multiple api versions

### PR DESCRIPTION
**Pull request by rocknes**
Current CSE can only expose REST apis at one given api versions. To improve backward compatibility of CSE server, this PR introduces a new mechanism of request processing/dispatching that will let CSE expose api endpoints at multiple api versions concurrently. This PR also revamps the entire request processor logic, the new framework is state machine driven, as a result adding new endpoints would not need core code change but only change in the api endpoint - handler table.

Testing Done:
ToDo

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
Aritra, thanks for doing this overhaul. I haven't yet reviewed few of the sections. I will review the rest in a day or two.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904#-:-MT6SAT65B0pAhK4yWRi:b-3192yj)* status: all files reviewed, 10 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/server/request_dispatcher.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6O9G5DlvPDFj_JCuK:-MT6O9G6DE4GSdiRSt8F:b-vqiw9i) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L30)):*
> ```Python
> 
> 
> CSE_REQUEST_DISPATCHER_LIST = [
> ```

Hi Aritra, Like I mentioned in one of our quick chats before, one of the concerns I had in our old style was going through the long list of values to add or edit something. To avoid that, I suggest grouping the endpoints into separate dictionaries or list of dictionaries like below 

CSE_REQUEST_DISPATCHER_LIST = [system, templates, pks, legacy_cluster, legacy_nodes, legacy_ovdc, native_cluster, native_cluster_ovdc]

This way we can move these to separate files if the need arises in the future.
___
*[container_service_extension/server/request_dispatcher.py, line 369 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6E8II6j3UFbq2ktoD:-MT6E8II6j3UFbq2ktoE:b1tnams) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L369)):*
> ```Python
>         },
>         RequestMethod.PUT: {
>             ('35.0', ): {
> ```

For (url, 36.0, PUT) -> v36_cluster_handler.cluster_update.
Do we need to write another block here?
___
*[container_service_extension/server/request_dispatcher.py, line 375 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6E4zg6xdJYqBQpKfr:-MT6E4zg6xdJYqBQpKfs:b-11bdb6) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L375)):*
> ```Python
>                 'payload_type': '*',
>                 'operation': CseOperation.V35_CLUSTER_CREATE,
>                 'handler': v35_cluster_handler.cluster_create
> ```

cluster_resize
___
*[container_service_extension/server/request_dispatcher.py, line 501 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6JmRJ2jRuu5qi29Q-:-MT6JmRJ2jRuu5qi29Q0:b-t5pk6i) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L501)):*
> ```Python
>     * */*;version=33.0
>     * application/*+json;version=33.0
>     If multiple matches are found, Will pick the first match.
> ```

What if the the "api_version" in the first match is not served by CSE but later in the list could be served?

For example:
[application/json;version=34.0, application/json;version=35.0]

Say we serve the url on 35.0 but not anymore on 34.0. We may not want to throw an error in this case because we picked the first match of 34.0
___
*[container_service_extension/server/request_dispatcher.py, line 570 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6K8FlBJ0LqaHfTsjt:-MT6K8Fm4condjJiw2_E:b6to1iv) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L570)):*
> ```Python
> 
>         if (val0, val1, val2) == ('application', 'json', 'version'):
>             selected_header = header
> ```

How about
selected_header = value.

Avoids reprocessing of the header in the method "_get_api_version_from_accept_header()"
___
*[container_service_extension/server/request_dispatcher.py, line 581 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6HCMOEs-TZvq6joVX:-MT6HCMOEs-TZvq6joVY:bxd055g) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L581)):*
> ```Python
> 
> def _get_api_version_from_accept_header(api_version_header: str):
>     api_version = '0.0'
> ```

If we are mandating that api_version is required, we can throw an error if api_version if not present in the header, right here. Why wait until "process_request" to throw the error?
___
*[container_service_extension/server/request_dispatcher.py, line 592 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6Swy12Hk9qGUkEt4i:-MT6Swy12Hk9qGUkEt4j:bwryb5u) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L592)):*
> ```Python
> 
> @handle_exception
> def process_request(message):
> ```

Please add more comments to this method on what is being processed or computed. Same with other methods like parse_accept_header.
___
*[container_service_extension/server/request_dispatcher.py, line 613 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6QW1G4BGvkUmEUkLY:-MT6QW1H29V0FncJR-vA:b43vh9m) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L613)):*
> ```Python
> 
>     request_body = None
>     # Should we do a content-type check? and allow only application/json content?  # noqa: E501
> ```

You are already doing the content check in the "parse_accept_header", right?
___
*[container_service_extension/server/request_dispatcher.py, line 645 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6MZTDDv2iqWkker4F:-MT6MZTDDv2iqWkker4G:b-o183ok) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L645)):*
> ```Python
>         matched_handler = None
>         supported_api_versions = []
>         for version in handlers.keys():
> ```

can you rename _version_ to _versions_ as this is a tuple?
___
*[container_service_extension/server/request_dispatcher.py, line 652 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6N0xz-NaxHpTZjhn6:-MT6N0xz-NaxHpTZjhn7:bs4vazx) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L652)):*
> ```Python
> 
>         if not matched_handler:
>             raise cse_exception.NotAcceptableRequestError(
> ```

I mentioned in one of my other comments, we could be missing on matching the handler for other values of accept header.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904)* status: all files reviewed, 14 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/server/request_dispatcher.py, line 122 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7fMc_1guQOJzzpFic:-MT7fMc_1guQOJzzpFid:b26zk1p) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L122)):*
> ```Python
>         RequestMethod.GET: {
>             tuple(server_constants.SUPPORTED_VCD_API_VERSIONS): {
>                 'allowed_params': ['org', 'vdc'],
> ```

I think it will be cleaner to use str enums for these keys since they are repeated often
___
*[container_service_extension/server/request_dispatcher.py, line 164 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7foJz0mp9a_SXK6Kp:-MT7foJz0mp9a_SXK6Kq:b5ols0v) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L164)):*
> ```Python
>     # /cse end points
>     {
>         'url': "cse/clusters",
> ```

I think using constants for the URL’s in this section will also be less error prone 
___
*[container_service_extension/server/request_dispatcher.py, line 553 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7hFcX0dsjJFvaBmbj:-MT7hFcX0dsjJFvaBmbk:b6c8n0e) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L553)):*
> ```Python
>     selected_header = None
>     for header, value in processed_headers.items():
>         val0 = value[0]
> ```

nit: you could do the following  to make this access simpler

‘val0, val1, val2, _ = value’
___
*[container_service_extension/server/request_dispatcher.py, line 680 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7iuvt0BakV4QbItWl:-MT7iuvt0BakV4QbItWm:bin0uw3) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L680)):*
> ```Python
>     # ToDo: Device better way to send request body to handlers.
>     if request_body:
>         # request_data[some_key] = request_body
> ```

nit: remove commented out code

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/server/request_dispatcher.py, line 30 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6O9G5DlvPDFj_JCuK:-MTfp_3n2MjdLugJ6jqU:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L30)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Hi Aritra, Like I mentioned in one of our quick chats before, one of the concerns I had in our old style was going through the long list of values to add or edit something. To avoid that, I suggest grouping the endpoints into separate dictionaries or list of dictionaries like below 

CSE_REQUEST_DISPATCHER_LIST = [system, templates, pks, legacy_cluster, legacy_nodes, legacy_ovdc, native_cluster, native_cluster_ovdc]

This way we can move these to separate files if the need arises in the future.
</blockquote></details>

done
___
*[container_service_extension/server/request_dispatcher.py, line 122 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7fMc_1guQOJzzpFic:-MTgH6m0Eo_Pr7HnSYoC:b-uhdcn5) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L122)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it will be cleaner to use str enums for these keys since they are repeated often
</blockquote></details>

Right now these fields are not being used at all for validation.
I will add the enums when the validation code comes into play.
___
*[container_service_extension/server/request_dispatcher.py, line 164 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7foJz0mp9a_SXK6Kp:-MTfpnvTCNN0vVzo9_U7:bfrvyrp) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L164)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think using constants for the URL’s in this section will also be less error prone 
</blockquote></details>

I chose hardcoded strings instead of constants because it is easier to read.
Adding new handler to an existing url is easier if the url can be found/read easily.
___
*[container_service_extension/server/request_dispatcher.py, line 369 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6E8II6j3UFbq2ktoD:-MTfq4cqCT67GRDidZGc:b-5rbh4g) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L369)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For (url, 36.0, PUT) -> v36_cluster_handler.cluster_update.
Do we need to write another block here?
</blockquote></details>

Thanks, I missed it, will add.
___
*[container_service_extension/server/request_dispatcher.py, line 375 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6E4zg6xdJYqBQpKfr:-MTfqCRt0H1rVVb9nrJk:b-k73z76) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L375)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

cluster_resize
</blockquote></details>

thanks
___
*[container_service_extension/server/request_dispatcher.py, line 501 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6JmRJ2jRuu5qi29Q-:-MTfqFk86GyAbVi5zpA1:bxkrmxs) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L501)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What if the the "api_version" in the first match is not served by CSE but later in the list could be served?

For example:
[application/json;version=34.0, application/json;version=35.0]

Say we serve the url on 35.0 but not anymore on 34.0. We may not want to throw an error in this case because we picked the first match of 34.0
</blockquote></details>

Ideally a client shouldn't send multiple accept headers. But if they do send multiple values, what it means is that the client will accept any result that the server sends back that conforms to one of the accept headers, also the server has autonomy to chose which accept header it wants to honor.
___
*[container_service_extension/server/request_dispatcher.py, line 553 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7hFcX0dsjJFvaBmbj:-MTfr9wBBaD3je1oXmur:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L553)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: you could do the following  to make this access simpler

‘val0, val1, val2, _ = value’
</blockquote></details>

done
___
*[container_service_extension/server/request_dispatcher.py, line 570 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6K8FlBJ0LqaHfTsjt:-MTfzoTe0WE_47EH-dsC:b-frqcyo) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L570)):*
> _get_api_version_from_accept_header
The second parsing is a cheap str split, unlike the regex style matching in the first method. I will prefer to keep the two methods separate to cleanly divide the responsibility of the methods.
First method, inspects headers, conforms them to a fixed standard and selects one.
Second method looks at one header string in a very specific format and picks the api version.
___
*[container_service_extension/server/request_dispatcher.py, line 581 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6HCMOEs-TZvq6joVX:-MTfrK2K1gXfjHxT83gV:b-w966t4) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L581)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

If we are mandating that api_version is required, we can throw an error if api_version if not present in the header, right here. Why wait until "process_request" to throw the error?
</blockquote></details>

Technically vCD won't allow a call to get to CSE that is missing accept header or has accept header that vCD doesn't support.
The if check here is redundant.
___
*[container_service_extension/server/request_dispatcher.py, line 592 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6Swy12Hk9qGUkEt4i:-MTg-Pb31lYPp9jb9_Dd:bebrt1w) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L592)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add more comments to this method on what is being processed or computed. Same with other methods like parse_accept_header.
</blockquote></details>

Will do
___
*[container_service_extension/server/request_dispatcher.py, line 613 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6QW1G4BGvkUmEUkLY:-MTg-euf4i726hyPYjMP:b-ayn768) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L613)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You are already doing the content check in the "parse_accept_header", right?
</blockquote></details>

no, this is not the accept header but the content-type header for request body.
___
*[container_service_extension/server/request_dispatcher.py, line 645 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6MZTDDv2iqWkker4F:-MTg-jvR8ybYzVRD09Gm:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L645)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

can you rename _version_ to _versions_ as this is a tuple?
</blockquote></details>

done
___
*[container_service_extension/server/request_dispatcher.py, line 652 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT6N0xz-NaxHpTZjhn6:-MTg-yh_5DKJLwp5HJhn:bbbyqv3) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L652)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I mentioned in one of my other comments, we could be missing on matching the handler for other values of accept header.
</blockquote></details>

Which is ok, clients are not supposed to send two accept headers with conflicting version in first place.
___
*[container_service_extension/server/request_dispatcher.py, line 680 at r1](https://reviewable.io/reviews/vmware/container-service-extension/904#-MT7iuvt0BakV4QbItWl:-MTg0iDdAtj390eJN_fA:bb7f2mf) ([raw file](https://github.com/vmware/container-service-extension/blob/a57310059c338446da9f15c5e3367d4146ce4ab7/container_service_extension/server/request_dispatcher.py#L680)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: remove commented out code
</blockquote></details>

done

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904#-:-MTlXz794GX6xzJPdm4o:bg7igkv)* status: all files reviewed, 12 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/904)* status: all files reviewed, 10 unresolved discussions (waiting on @rocknes and @sahithi)

**Pull request merged**
