### PR TITLE
[VCDA-1884] Refactoring client modules

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

Change the module names to meaningful ones:
* native_cluster_api.py -> de_cluster_native.py
* tkg_cluster_api.py -> de_cluster_tkg.py
* legacy_native_cluster_api.py -> legacy_cluster_native.py
* ovdc_policy.py -> policy_based_ovdc.py
* legacy_ovdc.py -> metadata_based_ovdc.py

Created new `cse_client` which handles calls to CSE server.

Testing done:
v33:
 * cluster commands
* ovdc commands
v35
*. cluster commands
* ovdc commands

@sahithi @rocknes @sakthisunda @ltimothy7 @ChintanShahVMware

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/808)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed 21 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/808)* status: 21 of 24 files reviewed, all discussions resolved

**Comment by ltimothy7** [comment]
:lgtm

**Review by ltimothy7 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/808#-:-MKgTyi5EdzJU2CFxKq0:bnfp4nl)* status: 21 of 24 files reviewed, all discussions resolved

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/808)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sahithi — APPROVED** [review]
Thanks for doing this Aniruddh. 
There is some inconsistency between the naming of files and class names - In few places, NativeCluster is used, ClusterTKG is used, TKGCluster, CLusterNative is used. Please keep the order of words consistent.

Can you also change the top level package _client_ -> _client-cli_?

:lgtm: 

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/808#-:-MKu4ivx681n1vxt5kXp:b77kbce)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster.py, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/808#-MKu2FFm0B0ZhvI1v-Iz:-MKu2FFm0B0ZhvI1v-J-:b-dtee6w) ([raw file](https://github.com/vmware/container-service-extension/blob/55e969deca3d550edaa4f37a214f62aeb2ca0e5e/container_service_extension/client/de_cluster.py#L51)):*
> ```
>         self._nativeCluster = DENativeCluster(client)
>         self._tkgCluster = DEClusterTKG(client)
> ```
Naming is a little off, follow the same pattern for both tkg and native.

 DEClusterTKG -> DETkgCluster

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/de_cluster.py, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/808#-MKu2FFm0B0ZhvI1v-Iz:-MKvn6D8B0yYgeJJMMFa:b-1n1beq) ([raw file](https://github.com/vmware/container-service-extension/blob/55e969deca3d550edaa4f37a214f62aeb2ca0e5e/container_service_extension/client/de_cluster.py#L51)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>         self._nativeCluster = DENativeCluster(client)
>         self._tkgCluster = DEClusterTKG(client)
> ```
Naming is a little off, follow the same pattern for both tkg and native.

 DEClusterTKG -> DETkgCluster
</blockquote></details>

Followed the convention that Aritra suggested in the thread https://vca-bos.slack.com/archives/GD555K9J5/p1603391801455800  and renamed DENativeCluster to DEClusterNative.

**Comment by Anirudh9794** [comment]
As discussed, will not be renaming the client package to `client_cli` as this will need changes in docs to indicate that we should use `container_service_extension.client_cli.cse` instead of `container_service_extension.client.cse` in `profiles.yaml`

**Pull request merged**
