### PR TITLE
[VCDA-2981] Fix cluster apply sample for tkgm

### PR DESCRIPTION
**Pull request by sakthisunda**
- Fixed cluster apply sample for tkgm
- Tested manually

image

@rocknes @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1228)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1228#-:-MlG7U6F9HqsJXehHIML:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1228)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 637 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1228#-MlGXZ5dCIHVraezDmij:-MlGXZ5e1D-GhrjebB51:be698yx) ([raw file](https://github.com/vmware/container-service-extension/blob/f5132cde42b4a5448149248d261ee490a30b72a6/container_service_extension/rde/models/rde_2_0_0.py#L637)):*
> ```Python
>             del native_entity_dict['spec']['topology']['nfs']
>             native_entity_dict['spec']['settings']['network']['expose'] = True
>             native_entity_dict['spec']['settings']['network']['pods'] = {}
> ```

Can be rewritten as 
native_entity_dict['spec']['settings']['network']['pods'] = {
  'cidr_blocks': ['100.96.0.0/11']
}

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1228)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 637 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1228#-MlGXZ5dCIHVraezDmij:-MlGZ5XH-L3AE6cdKVSD:b-w5tbry) ([raw file](https://github.com/vmware/container-service-extension/blob/f5132cde42b4a5448149248d261ee490a30b72a6/container_service_extension/rde/models/rde_2_0_0.py#L637)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can be rewritten as 
native_entity_dict['spec']['settings']['network']['pods'] = {
  'cidr_blocks': ['100.96.0.0/11']
}

</blockquote></details>

Done. thanks

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1228#-:-MlG_DxY-eHf3lwktc94:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
