### PR TITLE
[VCDA-2856] Allow CSE server to function in Only TKGm mode

### PR DESCRIPTION
**Pull request by rocknes**
* Added a new key in config file under `service` section. viz. `tkgm_only_mode`. This mode allows the provider to omit the entire `vcs` section from the config file, as well as it suppresses any piece of code in CSE that tries to connect to the vSphere server(s) either directly or via guest-run-library.
* Added relevant code in config sample generator, and config validation.
* Added checks in `cse template install`, `cse install` and `cse upgrade` to make sure that these command don't create templates if `tkgm_only_mode` is set to True in config file.
* config validation will remove `vcs` section from server runtime config if the flag `tkgm_only_mode` is set to True. This makes sure that even if the code paths in vcdbroker, cluster_service_1_x or cluster_service_2_x tries to connect to any vCenter server, the code fail with proper error message.

* Updated requirements.txt

* Fixed a bunch of style issues and flake8 bugs.

Testing done:
With `tkgm_only_mode` set to True, ran 
1. `cse install` without -t flag .. failure recorded
2. `cse install` with -t flag (on an existing CSE installation) .. failure recorded with the correct message asking user to upgrade CSE
3. `cse upgrade` without -t flag .. failure recorded
4. `cse upgrade` with -t flag .. success recorded
5. `template install` .. .failure recorded
6. `cse run` .. success recorded
7. Tried deploying native cluster .. failure recorded

With `tkgm_only_mode` set to False, ran 
1. `cse run` with `vcs` section missing .. failure recorded

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
> Reviewed 17 of 17 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by ltimothy7 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 480 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1199#-MkARlgw2U1QEw6nhXw4:-MkARlgw2U1QEw6nhXw5:bqbaevr) ([raw file](https://github.com/vmware/container-service-extension/blob/9472b57e8bd024201b9b54fe04628f58a67c0438/container_service_extension/installer/config_validator.py#L480)):*
> ```Python
> 
> 
> def _validate_vcd_and_vcs_config(
> ```

Since we have `_validate_vcd_config`, I think it would be cleaner to have just another `_validate_vcs_config` function instead of another function that checks both the vcd and vcs configs

**Review by arunmk — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199#-:-MkAUeyt4vbIWm1YgdTR:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/common/utils/server_utils.py, line 97 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1199#-MkA5PBS-XjtBKquUNKX:-MkA5PBS-XjtBKquUNKY:b3fx564) ([raw file](https://github.com/vmware/container-service-extension/blob/9472b57e8bd024201b9b54fe04628f58a67c0438/container_service_extension/common/utils/server_utils.py#L97)):*
> ```Python
> 
> 
> def is_tkgm_only_mode(config: dict = None):
> ```

`Optional[dict] = None`

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 480 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1199#-MkARlgw2U1QEw6nhXw4:-MkDlYsi47JRfKXIqZsl:bxqvrj3) ([raw file](https://github.com/vmware/container-service-extension/blob/9472b57e8bd024201b9b54fe04628f58a67c0438/container_service_extension/installer/config_validator.py#L480)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Since we have `_validate_vcd_config`, I think it would be cleaner to have just another `_validate_vcs_config` function instead of another function that checks both the vcd and vcs configs
</blockquote></details>

I did that at first and then realized that the validate vcs code anyways ends up creating the vcd client and does all the steps required to check connectivity to vcd. So I kept the old function as is, and added a new function that only checks vcd connectivity, and the decision to split the call is made as early as possible.

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @arunmk)

___
*[container_service_extension/common/utils/server_utils.py, line 97 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1199#-MkA5PBS-XjtBKquUNKX:-MkIbIaT6tc_7dLtK671:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90eb7ec5e82fe37bba763164bdcc7edca3e45a54/container_service_extension/common/utils/server_utils.py#L97)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

`Optional[dict] = None`
</blockquote></details>

Done.

**Pull request merged**
