### PR TITLE
[VCDA-2807] Revert consolidated post boot customization

### PR DESCRIPTION
**Pull request by sakthisunda**
- revert consolidated post boot customization scripts way of cluster creation 
- CRUD on CSE native cluster continue to use executing scripts using vshpere tools for cluster creation.  
- Keeping the utility method and related constants which may be in use 
- Tested cluster create, delete, resize, config with control plane, worker and NFS node

image

@rocknes @Anirudh9794 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/common/entity_service.py, line 9 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1178#-MiUjZxR3T7agrK7AA5S:-MiUjZxS0nS5km7C6IQH:b-m131m) ([raw file](https://github.com/vmware/container-service-extension/blob/04f6acbd7ea5282efee6365c69ce8acf2b09bdaf/container_service_extension/rde/common/entity_service.py#L9)):*
> ```Python
> from typing import List, Tuple, Union
> 
> import pyvcloud.vcd.client as vcd_client
> ```

We can retain these improvements.
___
*[container_service_extension/rde/common/entity_service.py, line 290 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1178#-MiUjsjY5htX_rzL-PTC:-MiUjsjZDpb22qHfQZBk:bea1zpx) ([raw file](https://github.com/vmware/container-service-extension/blob/04f6acbd7ea5282efee6365c69ce8acf2b09bdaf/container_service_extension/rde/common/entity_service.py#L290)):*
> ```Python
>         # Prevent users with rights <= EDIT/VIEW on CSE:NATIVECLUSTER from
>         # updating "private" property of RDE "status" section
>         if self._vcd_client and not pyvcloud_utils.has_full_access_to_native_cluster(self._vcd_client):  # noqa: E501
> ```

Should this pyvcloud_utils method be removed too?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/rde/common/entity_service.py, line 290 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1178#-MiUjsjY5htX_rzL-PTC:-MiX20NH3yqHy5Ujtx34:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/04f6acbd7ea5282efee6365c69ce8acf2b09bdaf/container_service_extension/rde/common/entity_service.py#L290)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should this pyvcloud_utils method be removed too?
</blockquote></details>

Done.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/rde/common/entity_service.py, line 9 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1178#-MiUjZxR3T7agrK7AA5S:-MiX27y_9gUbUot9XhPF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/04f6acbd7ea5282efee6365c69ce8acf2b09bdaf/container_service_extension/rde/common/entity_service.py#L9)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We can retain these improvements.
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1178)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

**Pull request merged**
