### PR TITLE
[VCDA-1600] Reorganize shared constants and utility methods

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Add docstrings to constant files and utility files
* Describe the scope of each of the utility modules
* move utility functions or constants to meaningful modules

The following files were split:
utils.py -> 
* server_utils.py (containing utility methods used only by the server), 
* thread_utils.py ( containing utility methods used for thread operations)
* utils.py (containing common utility methods used both by the server and the CLI) (Basic utility methods to perform data transformation and file operations.)
* Moved the function `create_org_user_id_to_name_dict` to pyvcloud_utils.py

Moved constants present in def_utils.py to def_constants.py

Moved constants which were used only in server code from `shared_constants` to `server_constants`

Added docstrings describing where the utility methods/constants present in the module should be used

Testing done:
* cse run
* cse install
* cse upgrade
* cluster create/resize/upgrade (TODO)
* ovdc update/list (TODO)

@sahithi @sakthisunda @rocknes @ChintanShahVMware @ltimothy7 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)* status: 13 of 39 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/configure_cse.py, line 767 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQPgJ_SA4-fhd8Ad3Do:-MQPgJ_SA4-fhd8Ad3Dp:b-4j8dtg) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/configure_cse.py#L767)):*
> ```Python
>         schema_svc = def_schema_svc.DefSchemaService(cloudapi_client)
>         keys_map = def_constants.MAP_API_VERSION_TO_KEYS[float(client.get_api_version())] # noqa: E501
>         defKey = def_constants.DefKey
> ```

I don't think this local variable is needed; the following uses of this variable could just call `def_constants.DefKey`
I know this PR doesn't introduce this variable, but it would be helpful to clean up
___
*[container_service_extension/service.py, line 479 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQPvPMiAkxbdaHGeDQM:-MQPvPMiAkxbdaHGeDQN:b-9dnp3q) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/service.py#L479)):*
> ```Python
>             raise_error_if_def_not_supported(cloudapi_client)
>             schema_svc = def_schema_svc.DefSchemaService(cloudapi_client)
>             defKey = def_constants.DefKey
> ```

I think this local variable also could be removed.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)* status: 14 of 39 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/thread_utils.py, line 13 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQSsxor6z-9R1nH31Yo:-MQSsxosCml9W4muETHr:bt6k4t3) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/thread_utils.py#L13)):*
> ```Python
> 
> 
> def transfer_thread_local_data_wrapper(func):
> ```

Is this method being called from anywhere else? If not mark it as private method.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)* status: 14 of 39 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/configure_cse.py, line 767 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQPgJ_SA4-fhd8Ad3Do:-MQTJ5Mt64bdAIw8pVNM:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/configure_cse.py#L767)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I don't think this local variable is needed; the following uses of this variable could just call `def_constants.DefKey`
I know this PR doesn't introduce this variable, but it would be helpful to clean up
</blockquote></details>

Done.
___
*[container_service_extension/service.py, line 479 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQPvPMiAkxbdaHGeDQM:-MQTJDA76XywvZ8z1GoT:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/service.py#L479)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think this local variable also could be removed.
</blockquote></details>

Done.
___
*[container_service_extension/thread_utils.py, line 13 at r1](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQSsxor6z-9R1nH31Yo:-MQTIasc77Y83JbYx0GF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/90b6b1d28a82dfd5ab8af5245677a599e8caa070/container_service_extension/thread_utils.py#L13)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is this method being called from anywhere else? If not mark it as private method.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
Thanks Aniruddh for doing this.

:lgtm: 

Can you see if you can group some of these files into folders? You can do the below as part of another PR or this one. If you decide to do it as a separate task, can you please create one and copy the below description in there?

Examples: 
- *Common* - shared utils and constant files between client and server can be grouped into a folder like "common" (or) "shared".

- *Generic_utils* - server_utils.py, thread_utils.py, pyvcloud_utils.py, vsphere_util.py, ovdc_utils.py, cloudapi_utils.py, logger.py can be grouped into folder "generic_utils". 

-  *Install/Configure* - Group all the files doing installation and configuration to this folder - config_validator.py, configure_cse.py, sample_generator.py, create_service_role_mgr.py

-  * Templates* - Group all the files doing the job around template installation into this folder - template_builder.py, remote_template_manager.py, template_rule.py, local_template_manager.py

- *start-up* - service.py

- * mqtt_consumer* - mqtt_extension_manager.py

- *Request_processing* - request_processor.py, request_id_fromatter.py,

- *Pks* - pks files

- *Security* - user_context.py, operation_context.py, right-bundle_manager.py, security.py etc

- *Exception folder* - exception_handler.py, exceptions.py, minor_error_codes.py

You get the idea, the above is the cursory view of the folder structure. You can take a hard look to come up with the final folder structure.

> Reviewed 39 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866#-:-MQTyFf6B3dZDCWO6Kxb:b-nmc6wf)* status: 24 of 39 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by sahithi — COMMENTED** [review]
@rocknes Please see my above comment. Share your thoughts.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866#-:-MQU4rgL0qip6g0xry5A:b-hsb4m7)* status: 24 of 39 files reviewed, 3 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
Sounds good to me, I will suggest we do the above mentioned changes in a separate PR. Too many changes in one PR is hard to review. @anirudh9794 Please document in a wiki page the changes and let's go thorough it and then implement it.

> Reviewed 5 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866#-:-MQYEk9U7x1ogieCrGcx:b-yau5lg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 19 of 39 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866#-:-MQZ8ejq75wPQ-vRxvVH:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/operation_context.py, line 42 at r2](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQYSeZ1D7_zUdACRkwt:-MQYSeZ24WA15vrA8BeN:b4h1fly) ([raw file](https://github.com/vmware/container-service-extension/blob/2a3ff083b7a92550dce9fe21af373895b7e17f4e/container_service_extension/operation_context.py#L42)):*
> ```Python
>     def cloudapi_client(self):
>         if self._cloudapi_client is None:
>             log_wire = server_utils.get_server_runtime_config() \
> ```

I think we can use noqa E501 on this line
___
*[container_service_extension/ovdc_utils.py, line 5 at r2](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQYSlnk7aw0t-LWsLde:-MQYSlnk7aw0t-LWsLdf:b7taz3g) ([raw file](https://github.com/vmware/container-service-extension/blob/2a3ff083b7a92550dce9fe21af373895b7e17f4e/container_service_extension/ovdc_utils.py#L5)):*
> ```Python
> # SPDX-License-Identifier: BSD-2-Clause
> 
> """Utilities for performing operations for metadata based ovdc."""
> ```

nit: Utilities to manage CSE metadata on Ovdcs

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/866)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/operation_context.py, line 42 at r2](https://reviewable.io/reviews/vmware/container-service-extension/866#-MQYSeZ1D7_zUdACRkwt:-MQtYRO75uNNGuGCTLeK:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2a3ff083b7a92550dce9fe21af373895b7e17f4e/container_service_extension/operation_context.py#L42)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we can use noqa E501 on this line
</blockquote></details>

Done.

**Pull request merged**
