### PR TITLE
[VCDA-2281] Stamp rde version after install and upgrade in non legacy mode

### PR DESCRIPTION
**Pull request by sakthisunda**
-  Stamp rde version : install and upgrade in non-legacy mode
-  cse run : suggest to upgrade if rde version in extension < runtime rde version to upgrade to
-  Tested with install, upgrade and run command
-  This PR has extra code that is already under review: [VCDA-2285] Enable cse 3.0 legacy to cse 3.1 legacy upgrade. This is required for testing
- Remove old entity types after upgrade
- Testing completed

@Anirudh9794 @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: all files reviewed, 3 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/installer/configure_cse.py, line 2241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDshjLDFhOVxcugQXg:-MYDshjLDFhOVxcugQXh:byqijw0) ([raw file](https://github.com/vmware/container-service-extension/blob/d3bce36e7c75ade4e5321c7b66a9c357707874f5/container_service_extension/installer/configure_cse.py#L2241)):*
> ```Python
>         config,
>         cse_clusters,
>         is_tkg_plus_enabled,
> ```

Consider the scenario - 
User creates a TKG-plus cluster with CSE 3.0 (api_version 35, enable_tkg_plus: true)
User upgrades CSE to CSE 3.1 (legacy_mode: false, enable_tkg_plus: false)

Now, if we process all the TKG-plus clusters to have RDE 2.0, when cluster list is issued, TKG-plus cluster will be shown even when CSE server is running with the configuration enable_tkg_plus: false.

I think we should fail the upgrade (as we do in other cases) if we encounter a TKG+ cluster.
___
*[container_service_extension/installer/configure_cse.py, line 2531 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDqjC17IEz-_0nt5G5:-MYDqjC21vbVezNfzN9f:b-oom0bd) ([raw file](https://github.com/vmware/container-service-extension/blob/d310035853d0a28e4c0103188605d057870a9464/container_service_extension/installer/configure_cse.py#L2531)):*
> ```Python
> 
> 
> def _def_entity_type_found(client):
> ```

_is_native_entity_type_registered() sounds more accurate to me
___
*[container_service_extension/installer/configure_cse.py, line 2532 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDr30h8Pb9K10IyYo-:-MYDr30h8Pb9K10IyYo0:b-v2y3fi) ([raw file](https://github.com/vmware/container-service-extension/blob/d310035853d0a28e4c0103188605d057870a9464/container_service_extension/installer/configure_cse.py#L2532)):*
> ```Python
> 
> def _def_entity_type_found(client):
>     """Check the presence of native entity type.
> ```

native entity type of any version*

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999#-:-MYGQqfI74FEkKTg5UZ2:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/installer/configure_cse.py, line 2241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDshjLDFhOVxcugQXg:-MYG_-Lw4LZH-IRhDg0i:bx8y9qs) ([raw file](https://github.com/vmware/container-service-extension/blob/d3bce36e7c75ade4e5321c7b66a9c357707874f5/container_service_extension/installer/configure_cse.py#L2241)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Consider the scenario - 
User creates a TKG-plus cluster with CSE 3.0 (api_version 35, enable_tkg_plus: true)
User upgrades CSE to CSE 3.1 (legacy_mode: false, enable_tkg_plus: false)

Now, if we process all the TKG-plus clusters to have RDE 2.0, when cluster list is issued, TKG-plus cluster will be shown even when CSE server is running with the configuration enable_tkg_plus: false.

I think we should fail the upgrade (as we do in other cases) if we encounter a TKG+ cluster.
</blockquote></details>

This needs to be discussed as next step, since failing upgrade for this case. Currently, scope of this task is rde stamping and removing old entity types. 
___
*[container_service_extension/installer/configure_cse.py, line 2531 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDqjC17IEz-_0nt5G5:-MYGZN6hAlk6cc3s3Q1B:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d310035853d0a28e4c0103188605d057870a9464/container_service_extension/installer/configure_cse.py#L2531)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

_is_native_entity_type_registered() sounds more accurate to me
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 2532 at r1](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYDr30h8Pb9K10IyYo-:-MYGZNOQ5OMUy8axrCeh:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d310035853d0a28e4c0103188605d057870a9464/container_service_extension/installer/configure_cse.py#L2532)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

native entity type of any version*
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/server/service.py, line 109 at r2](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYG_a2p2yDTFcgUEp8Y:-MYG_a2q8M4hUuQZHWcL:b-z7v27n) ([raw file](https://github.com/vmware/container-service-extension/blob/65d873d181fee1fac1204e3c3903b7b7240f5902/container_service_extension/server/service.py#L109)):*
> ```Python
>         is_mqtt_extension: bool):
>     cse_version = server_utils.get_installed_cse_version()
>     runtime_rde_version = semantic_version.Version(server_utils.get_rde_version_in_use())  # noqa: E501
> ```

the import has been removed.

This will cause a error

flake8 is failing currently : container_service_extension/server/service.py:108:27: F821 undefined name 'semantic_version'

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/server/service.py, line 109 at r2](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYG_a2p2yDTFcgUEp8Y:-MYGhaVbEmwyx9tj0BmH:b4qcblt) ([raw file](https://github.com/vmware/container-service-extension/blob/65d873d181fee1fac1204e3c3903b7b7240f5902/container_service_extension/server/service.py#L109)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

the import has been removed.

This will cause a error

flake8 is failing currently : container_service_extension/server/service.py:108:27: F821 undefined name 'semantic_version'
</blockquote></details>

Done. Fixed after rebasing with master. thanks

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/installer/config_validator.py, line 231 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYOMoTb5wXJPPdekk_t:-MYOMoTc16zpz8vNLd7Z:b7swkfy) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/config_validator.py#L231)):*
> ```Python
> 
>     max_vcd_api_version_supported = \
>         max([float(x) for x in config['service']['supported_api_versions']])  # noqa: E501
> ```

We have a task in backlog to get the max vcd api version by doing proper tuple comparison instead of float comparison. I think it makes sense to combine that story with this one.
___
*[container_service_extension/installer/config_validator.py, line 233 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYON9Gm09_eFBZ48P0Y:-MYON9GnEPyXqIpLdNRi:bdaf7oi) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/config_validator.py#L233)):*
> ```Python
>         max([float(x) for x in config['service']['supported_api_versions']])  # noqa: E501
>     config['service']['rde_version_in_use'] = \
>         rde_utils.get_runtime_rde_version_by_vcd_api_version(max_vcd_api_version_supported)  # noqa: E501
> ```

I think it makes more sense to store the semantic_version.Version object instead of plain string.
___
*[container_service_extension/installer/configure_cse.py, line 2352 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYONxLF9WbS7XGy3XP4:-MYONxLG729ZScJ8cZAg:bivwu7u) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/configure_cse.py#L2352)):*
> ```Python
> 
>     max_vcd_api_version_supported = \
>         max([float(x) for x in config['service']['supported_api_versions']])
> ```

This piece of logic is showing up in multiple places. I think it makes sense to make it an util function in core_utils.py

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 231 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYOMoTb5wXJPPdekk_t:-MYR3eJNAGsDXEfht8aO:bg77oqp) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/config_validator.py#L231)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We have a task in backlog to get the max vcd api version by doing proper tuple comparison instead of float comparison. I think it makes sense to combine that story with this one.
</blockquote></details>

As decided, marked as future task
___
*[container_service_extension/installer/config_validator.py, line 233 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYON9Gm09_eFBZ48P0Y:-MYR3m0x-JqG8pyq559a:b-2z1bp0) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/config_validator.py#L233)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think it makes more sense to store the semantic_version.Version object instead of plain string.
</blockquote></details>

Done. 
But, at many places **get_rde_in_use()** is expects a string version of **rde_version_in_use**. Added a TODO  in **get_rde_in_use()** for future usage for treating the return type to be **sematic version**.
___
*[container_service_extension/installer/configure_cse.py, line 2352 at r3](https://reviewable.io/reviews/vmware/container-service-extension/999#-MYONxLF9WbS7XGy3XP4:-MYR4aAQ9m9JMc-my-_1:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b7e0fe560762c97516d0111b637b35786255693e/container_service_extension/installer/configure_cse.py#L2352)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This piece of logic is showing up in multiple places. I think it makes sense to make it an util function in core_utils.py
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/999#-:-MYcIRK29p8wWG0-k9Dk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
