### PR TITLE
remove metrics server version in control plane script

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1340)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1340#-:-MzxIRNk6PsV7hxRLNda:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by arunmk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
Previously, the metrics server version was retrieved from the tkr bom file. With the current approach, tanzu-cli gives the the needed metrics server version, so we do not need to get it from the control plane code anymore.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1340#-:-MzyqXsP6QkeBUTJAK0M:bykah17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Pull request merged**
