### PR TITLE
[VCDA-3183] Fix broken CSE cluster commands

### PR DESCRIPTION
**Pull request by sakthisunda**
- Filter out the capvcd kind clusters for now to unblock CSE native/tkg clusters operations
- Issue noticed when the CLI user persona has both native and CAPVCD clusters created.
- Tested using CLI. Endpoint works fine with POSTMAN testing

@sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272#-:-MrSpWS12uY2jNq5eGl9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272#-:-MsWfle74NFhGIgu8de6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1272#-MsWfNMY1S-2fxFtZ_by:-MsWfNMZ36ztql9dA12F:b-4l6fo2) ([raw file](https://github.com/vmware/container-service-extension/blob/251f2b58af465112d58009e6dc295afa1ec516ed/container_service_extension/rde/common/entity_service.py#L242)):*
> ```Python
>         filter_string = utils.construct_filter_string(filters)
>         # TODO(): This CAPVCD filter is temporary and should be removed after
>         #  CAPVCDCluster kind adoption in CSE
> ```

I would prefer if the caller sends in the proper filter with support for !=.
Instead of hack adding the value here.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

___
*[container_service_extension/rde/common/entity_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1272#-MsWfNMY1S-2fxFtZ_by:-MsWwZod7FxsFsZC8dM0:b-o4y85j) ([raw file](https://github.com/vmware/container-service-extension/blob/251f2b58af465112d58009e6dc295afa1ec516ed/container_service_extension/rde/common/entity_service.py#L242)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I would prefer if the caller sends in the proper filter with support for !=.
Instead of hack adding the value here.
</blockquote></details>

I don't think we should be editing this method directly. This is a CSE server library method commonly being shared by CSE client as well.
In the future, if CSE server has a usecase to send back CAPVCD entities for whatsoever reason, CSE client will break again.

Please do one of the below (whichever is easier)

Simply add an optional "excludeEntityTypeFilter" as an optional param
(or)
Let CSE client ignore those entities that it cannot understand, just like how UI has the piece of logic to skip the entities that it cannot understand.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1272#-MsWfNMY1S-2fxFtZ_by:-MsXKfg6DWHz81nqmr-r:b-xkr03o) ([raw file](https://github.com/vmware/container-service-extension/blob/251f2b58af465112d58009e6dc295afa1ec516ed/container_service_extension/rde/common/entity_service.py#L242)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I don't think we should be editing this method directly. This is a CSE server library method commonly being shared by CSE client as well.
In the future, if CSE server has a usecase to send back CAPVCD entities for whatsoever reason, CSE client will break again.

Please do one of the below (whichever is easier)

Simply add an optional "excludeEntityTypeFilter" as an optional param
(or)
Let CSE client ignore those entities that it cannot understand, just like how UI has the piece of logic to skip the entities that it cannot understand.


</blockquote></details>

Done: Optional param "exclude_entity_type_filter" included with right value set by the client.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1272#-MsWfNMY1S-2fxFtZ_by:-MsXtVP73CWJOG_JxjlZ:b-8wiild) ([raw file](https://github.com/vmware/container-service-extension/blob/251f2b58af465112d58009e6dc295afa1ec516ed/container_service_extension/rde/common/entity_service.py#L242)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Done: Optional param "exclude_entity_type_filter" included with right value set by the client. 
</blockquote></details>

I meant something slightly different, sorry for not being clear before. Can we take the list of entity types as param and let the method construct the filter string?

exclude_entity_type_ids param would be a list of entity type ids that need not be retrieved.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @Anirudh9794, @rocknes, and @sahithi)

___
*[container_service_extension/rde/common/entity_service.py, line 242 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1272#-MsWfNMY1S-2fxFtZ_by:-MsYZvvLAAJJFaFdXNfV:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/251f2b58af465112d58009e6dc295afa1ec516ed/container_service_extension/rde/common/entity_service.py#L242)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I meant something slightly different, sorry for not being clear before. Can we take the list of entity types as param and let the method construct the filter string?

exclude_entity_type_ids param would be a list of entity type ids that need not be retrieved.
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1272)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
