### PR TITLE
[VCDA-2061] Determine common api versions supported by CSE and VCD

### PR DESCRIPTION
**Pull request by rocknes**
Added logic during server startup to determine the list of api versions supported by both CSE and vCD.

Testing Done:
Added a print statement during server startup to print the runtime server config that holds the api versions supported by both vCD and CSE.

{
'enforce_authorization': True,
'processors': 10,
'log_wire': True,
'telemetry': {
'enable': True,
'vac_url': 'https://vcsa.vmware.com/ph/api/hyper/send',
'collector_id': 'CSE.3_0',
'vcd_ceip_id': 'f89fd574-8f62-4b85-a2ac-329a2faf85b5',
'instance_id': 'bccae9c2-ee9c-4e35-8cfc-6a2ae346544f'
},
'supported_api_versions': ['33.0', '35.0', '34.0']
}

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/897)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/897)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/service.py, line 290 at r1](https://reviewable.io/reviews/vmware/container-service-extension/897#-MSEtHWJ2TM1STB3ldAd:-MSEtHWJ2TM1STB3ldAe:b-25z4f1) ([raw file](https://github.com/vmware/container-service-extension/blob/09241c2ca78ac01d1a31f34c2859bf05558a7b98/container_service_extension/service.py#L290)):*
> ```Python
>                 set(server_constants.SUPPORTED_VCD_API_VERSIONS)
>             common_supported_versions = \
>                 list(cse_supported_versions.intersection(vcd_supported_versions))  # noqa: E501
> ```

_supported_versions --> _supported_api_versions  ( not a must though )

**Review by sakthisunda — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/897#-:-MSEtXBbA5UAS5j5KrB-:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Review by Anirudh9794 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/897)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Comment by arunmk** [comment]
___
*[container_service_extension/service.py, line 291 at r2](https://reviewable.io/reviews/vmware/container-service-extension/897#-MSH968u3GuR9I996Gf1:-MSH968u3GuR9I996Gf2:bwnu5uy) ([raw file](https://github.com/vmware/container-service-extension/blob/abf0e764197cb0e99849956d3691db9132ea4925/container_service_extension/service.py#L291)):*
> ```Python
>             common_supported_api_versions = \
>                 list(cse_supported_api_versions.intersection(vcd_supported_api_versions))  # noqa: E501
>             self.config['service']['supported_api_versions'] = \
> ```

I couldn't find where this lvalue is used in the existing master code. Will that be coming in as another PR?

**Review by arunmk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/897)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes)

**Comment by arunmk** [comment]
:lgtm: with a comment for my understanding.

**Pull request merged**
