### PR TITLE
[VCDA-3147] Force delete cluster

### PR DESCRIPTION
**Pull request by sakthisunda**
- Force delete cluster - implementation with no regression for the existing code base
- Implementation makes sure the persona has required rights and ACL to execute with no behaviour hooks
- CLI implementation
- Personas tested with missing rights
- Persona tested with missing entityType access controls
- Tested with partially created as well as fully created cluster (Native & TKGm)
- TBD : In progress : More testing

image

image

image

image

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1287)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1287)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 807 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtPT4dn5QMpgPWZiG-B:-MtPT4dn5QMpgPWZiG-C:b-83unvd) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/common/utils/pyvcloud_utils.py#L807)):*
> ```Python
>         delete_rights = server_constants.CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS | server_constants.VAPP_DELETE_RIGHTS | server_constants.DNAT_DELETE_RIGHTS  # noqa: E501
>         cse_native_full_rights = server_constants.CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS | server_constants.CSE_NATIVE_CLUSTER_FULL_ACCESS_RIGHTS  # noqa: E501
>         missing_rights: set = delete_rights - set(role_rights)
> ```

it would be cleaner to store `set(role_rights)` in a local variable to not recreate the set in the check below

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1287)* status: 12 of 13 files reviewed, 8 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/client/cluster_commands.py, line 104 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQF3lh8nhx_OhggCvH:-MtQF3li7uEYVLKOHqEW:b-87pak0) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/client/cluster_commands.py#L104)):*
> ```Python
>                                   'cluster?')
> @click.option(
>     '-f',
> ```

If someone runs CSE server in legacy mode and invoke the delete command with --force flag, the call will go to LegacyClusterNative and fail since the method is not defined in that module. We should either hide the flag for legacy mode, or add appropriate method in the LegacyClusterNative to throw proper error.
___
*[container_service_extension/client/de_cluster.py, line 340 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQGHFT4zkyf3z32vYM:-MtQG2AGE8VFjH-cTAZT:bkvb4s1) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/client/de_cluster.py#L340)):*
> ```Python
>         return self._tkgCluster.delete_cluster_by_id(cluster_id, org=org)
> 
>     def force_delete_cluster_by_id(self, cluster_id, org=None):
> ```

I don't see any call to this method. Can you please check if this is not dead code.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 777 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQHF9v5Xdt3sFs4YPn:-MtQHF9w-WfxY9ELtlmI:b-ovr5lf) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/common/utils/pyvcloud_utils.py#L777)):*
> ```Python
> 
> 
> def get_missing_delete_cluster_rights(
> ```

nit _get_missing_rights_for_cluster_force_delete
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 809 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQIO0w4Vs1mxh6pyWE:-MtQIO0y89Ep-DehlMl-:bz9vhvu) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/common/utils/pyvcloud_utils.py#L809)):*
> ```Python
> 
>         # Either of full control or admin full control check of cluster owner
>         cse_native_full_rights: set = server_constants.CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS | server_constants.CSE_NATIVE_CLUSTER_FULL_ACCESS_RIGHTS  # noqa: E501
> ```

I am quite confused with the check being made here, as far as I understand

You need to be owner of the cluster and have at least Full Access right (having Administrator Full Access doesn't hurt) or you are not the cluster owner and have the Administrator Full Access right, correct?

The current check will skip the native entity rights altogether for  non cluster owners.

```
if is_cluster_owner:
   if not CSE_NATIVE_CLUSTER_FULL_ACCESS_RIGHTS.issubset(role_rights) and not 
       CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS.issubset(role_rights):
      add full access right to  missing_rights
else :
   if not  CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS.issubset(role_rights):
       add admin fulll access right to missing rights
```
___
*[container_service_extension/rde/acl_service.py, line 319 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQKkV46n-0pzGyBaOg:-MtQKkV5AW9_hLC_Rco5:bgs6pdj) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/acl_service.py#L319)):*
> ```Python
>         return
> 
>     def has_acl_set_for_force_delete(self, member_ids: list) -> bool:
> ```

Ideally this method should not be part of this class, this class is only responsible for grabbing the ACL entries.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2009 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQLxvL7-8Bkme_TzRy:-MtQLxvM5CDywIHNRnjC:b-ukjpcp) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/backend/cluster_service_2_x.py#L2009)):*
> ```Python
> 
>             if not has_force_delete_acl:
>                 missing_rights_msg += f"Entity Type ACL required for  " \
> ```

This message will confuse users,

The message should convey:
To force delete cluster, Full Access ACL for entity cse:nativeCLuster:2.0.0 must be grated to either the user or the org.
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1815 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQMeKp60kuSGq5pZli:-MtQMeKq494EnUwHkMyt:b-x9wkpt) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1815)):*
> ```Python
> 
>             if not has_force_delete_acl:
>                 missing_rights_msg += f"Entity Type ACL required for  " \
> ```

Same comment as in the other service file. Please improve the msg.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1287)* status: 9 of 15 files reviewed, 7 unresolved discussions (waiting on @ltimothy7 and @rocknes)

___
*[container_service_extension/client/cluster_commands.py, line 104 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQF3lh8nhx_OhggCvH:-MtjPXV55sUyuoT5xvqA:bbwt52c) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/client/cluster_commands.py#L104)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If someone runs CSE server in legacy mode and invoke the delete command with --force flag, the call will go to LegacyClusterNative and fail since the method is not defined in that module. We should either hide the flag for legacy mode, or add appropriate method in the LegacyClusterNative to throw proper error.
</blockquote></details>

thanks. Added as an unsupported flag in command_filter.py (flag hidden for legacy mode)
___
*[container_service_extension/client/de_cluster.py, line 340 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQGHFT4zkyf3z32vYM:-MtjPm5F-ko3nOa_Gt9S:b-1379k1) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/client/de_cluster.py#L340)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I don't see any call to this method. Can you please check if this is not dead code.
</blockquote></details>

double checked. <b>vcd cse cluster delete --id  --force</b>  calls this in the workflow
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 807 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtPT4dn5QMpgPWZiG-B:-MtjQkx18l-T8pfI4n0f:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/common/utils/pyvcloud_utils.py#L807)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

it would be cleaner to store `set(role_rights)` in a local variable to not recreate the set in the check below
</blockquote></details>

Done.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 777 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQHF9v5Xdt3sFs4YPn:-MtjQiOHC2Nr38F30CJO:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/common/utils/pyvcloud_utils.py#L777)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit _get_missing_rights_for_cluster_force_delete
</blockquote></details>

Done
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 809 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQIO0w4Vs1mxh6pyWE:-MtjQqta7O01bxZ_Aw5S:bjt99ze) ([raw file](https://github.com/vmware/container-service-extension/blob/b328b8167b6e27f57bd27601ae5ef6928093532d/container_service_extension/common/utils/pyvcloud_utils.py#L809)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I am quite confused with the check being made here, as far as I understand

You need to be owner of the cluster and have at least Full Access right (having Administrator Full Access doesn't hurt) or you are not the cluster owner and have the Administrator Full Access right, correct?

The current check will skip the native entity rights altogether for  non cluster owners.

```
if is_cluster_owner:
   if not CSE_NATIVE_CLUSTER_FULL_ACCESS_RIGHTS.issubset(role_rights) and not 
       CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS.issubset(role_rights):
      add full access right to  missing_rights
else :
   if not  CSE_NATIVE_CLUSTER_ADMINISTRATOR_FULL_ACCESS_RIGHTS.issubset(role_rights):
       add admin fulll access right to missing rights
```
</blockquote></details>

Rewrote the logic to avoid confusion. 
<li>check fo each right 
<li>updating the missing rights incrementally.
<li> retested
___
*[container_service_extension/rde/acl_service.py, line 319 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQKkV46n-0pzGyBaOg:-MtjRPNe2NHkhQHz29MI:b-la8iuj) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/acl_service.py#L319)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Ideally this method should not be part of this class, this class is only responsible for grabbing the ACL entries.
</blockquote></details>

Moved to rde/utils.py
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2009 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQLxvL7-8Bkme_TzRy:-MtjRXgp6pMwsxcB2irk:b-yzuc1h) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/backend/cluster_service_2_x.py#L2009)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This message will confuse users,

The message should convey:
To force delete cluster, Full Access ACL for entity cse:nativeCLuster:2.0.0 must be grated to either the user or the org.
</blockquote></details>

Error message updated as suggested. Thanks
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1815 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1287#-MtQMeKp60kuSGq5pZli:-MtjRgut0NcqQO3DqquO:ba2sjow) ([raw file](https://github.com/vmware/container-service-extension/blob/24d34414db1120bd6eeeb8bdb1b4d923b1e80577/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1815)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Same comment as in the other service file. Please improve the msg.
</blockquote></details>

Error message updated as suggested

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1287#-:-MtoLtA72J-9_7u3Oz-1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Pull request merged**
