### PR TITLE
[VCDA-1849] CSE upgrade to tag templates with placement policy when template creation is skipped

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* If `cse upgrade`is done with templates created with new metadata already present, CSE will contain templates which can be deployed even without enabling an OVDC. To prevent this, if the user skips template installation, tag the already existing templates with relevant placement policies.

* Testing done:
- created templates with current upgrades branch and ran cse upgrade with skip template creation option. Checked if the templates are being tagged with proper placement policies
- created a template after the upgrade to see if the newly created template is properly tagged with placement policies.

@rocknes @sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/configure_cse.py, line 899 at r2](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIVhdqxDir6qo-bGrW0:-MIVhdqxDir6qo-bGrW1:beiewz) ([raw file](https://github.com/vmware/container-service-extension/blob/3f2d95403f7757b588c1d8ce93499d017d62b22f/container_service_extension/configure_cse.py#L899)):*
> ```Python
>             msg_update_callback.general(msg)
>             continue
>         if kind == shared_constants.ClusterEntityKind.TKG_PLUS:
> ```

Do we need a check if not tkg_plus_enabled?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/configure_cse.py, line 899 at r2](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIVhdqxDir6qo-bGrW0:-MIVwab3ApwZtfiy_roi:b-9z9c68) ([raw file](https://github.com/vmware/container-service-extension/blob/3f2d95403f7757b588c1d8ce93499d017d62b22f/container_service_extension/configure_cse.py#L899)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Do we need a check if not tkg_plus_enabled?
</blockquote></details>

Yes. Thank you. Caught this during testing too :-)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/right_bundle_manager.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIWtd092KhCOF8iD_7s:-MIWtd092KhCOF8iD_7t:b1o0jdt) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L30)):*
> ```Python
> 
>     def get_right_bundle_by_name(self, right_bundle_name):
>         query_string = f"filter=name=={right_bundle_name}"
> ```

Is escaping(url_lib.parse.quote()) required here?  (https://reviewable.io/reviews/vmware/container-service-extension/763)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/right_bundle_manager.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIWtd092KhCOF8iD_7s:-MIWzsqSDR0_K2LfZnlF:bgklsv6) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L30)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is escaping(url_lib.parse.quote()) required here?  (https://reviewable.io/reviews/vmware/container-service-extension/763)
</blockquote></details>

looks like it is only needed for typed queries. @rocknes is escaping required here?

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: once the comments are addressed.

> Reviewed 3 of 4 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761#-:-MIXh-GmBKRPAdSDUFtD:bii7ij8)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/configure_cse.py, line 2331 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXgJFU8LhJ561ha9s1:-MIXgJFU8LhJ561ha9s2:b-3o1x1s) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/configure_cse.py#L2331)):*
> ```Python
>         org_user_dict[cluster['org_name']].append(cluster['owner_name'])
> 
>     msg = "The following users own CSE k8s clusters and will require `cse:nativeCluster Entitlement` rights to access them in CSE 3.0"  # noqa: E501
> ```

nit: rights bundle

Thanks btw :)
___
*[container_service_extension/configure_cse.py, line 2335 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXgYDRAj8wgrIDd6-q:-MIXgYDRAj8wgrIDd6-r:bvgv0jc) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/configure_cse.py#L2335)):*
> ```Python
>     INSTALL_LOGGER.info(msg)
> 
>     for org_name, user_list in org_user_dict.items():
> ```

I just realized that if there are no clusters, we will print the above line but no users following it.

Can you please compute the message first and then check if the length of msg is not 0, and only then print both the previous msg and the list of users.
___
*[container_service_extension/right_bundle_manager.py, line 14 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXcvI-0h7wWOstS7_c:-MIXcvI0-nH3WLCDiklV:b-chceqe) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L14)):*
> ```Python
> from container_service_extension.shared_constants import RequestMethod
> 
> CSE_NATIVE_RIGHT_BUNDLE_NAME = 'cse:nativeCluster Entitlement'
> ```

Is this right bundle created based on the native schema name? Maybe that can be reflected here.
___
*[container_service_extension/right_bundle_manager.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIWtd092KhCOF8iD_7s:-MIXdBhwAXPsDyic7Oel:b-sn6fsv) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L30)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is escaping(url_lib.parse.quote()) required here?  (https://reviewable.io/reviews/vmware/container-service-extension/763)
</blockquote></details>

Escaping can be skipped if ( ) ; , is not in the value. 
But to be on safe side, we should escape the value.
However we should always url encode the entire filter value.
___
*[container_service_extension/template_builder.py, line 61 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXfTWrBQFGWWCOMluW:-MIXfTWrBQFGWWCOMluX:b-6rtx2v) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/template_builder.py#L61)):*
> ```Python
>         msg_update_callback.info(msg)
>         logger.info(msg)
>     except EntityNotFoundException as err:
> ```

Technically speaking missing VDC/Org/Catalog will also generate the same exception

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/761)* status: all files reviewed, 4 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/configure_cse.py, line 2331 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXgJFU8LhJ561ha9s1:-MI_-ASm9eeBZIRhTyyb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/configure_cse.py#L2331)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: rights bundle

Thanks btw :)
</blockquote></details>

Done.
___
*[container_service_extension/configure_cse.py, line 2335 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXgYDRAj8wgrIDd6-q:-MI_QDIp4j1N1TwAEuaS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/configure_cse.py#L2335)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I just realized that if there are no clusters, we will print the above line but no users following it.

Can you please compute the message first and then check if the length of msg is not 0, and only then print both the previous msg and the list of users.
</blockquote></details>

Done.
___
*[container_service_extension/right_bundle_manager.py, line 14 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXcvI-0h7wWOstS7_c:-MI_REK-CU1PyzcwC4Ho:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L14)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is this right bundle created based on the native schema name? Maybe that can be reflected here.
</blockquote></details>

Done
___
*[container_service_extension/right_bundle_manager.py, line 30 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIWtd092KhCOF8iD_7s:-MIWzsqSDR0_K2LfZnlF:b-t4m3ft) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/right_bundle_manager.py#L30)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Escaping can be skipped if ( ) ; , is not in the value. 
But to be on safe side, we should escape the value.
However we should always url encode the entire filter value.
</blockquote></details>

As per discussion, I am leaving this as is.
___
*[container_service_extension/template_builder.py, line 61 at r3](https://reviewable.io/reviews/vmware/container-service-extension/761#-MIXfTWrBQFGWWCOMluW:-MI_T7QrBLzxGTMUZ57v:b-ej1wv0) ([raw file](https://github.com/vmware/container-service-extension/blob/dd8abd2020cea74e3418a960acafda96945ff1f8/container_service_extension/template_builder.py#L61)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Technically speaking missing VDC/Org/Catalog will also generate the same exception
</blockquote></details>

removed this except block as both the except block just logs and raises the exception.

**Pull request merged**
