### PR TITLE
Changes for combined PR

### PR DESCRIPTION
**Pull request by arunmk**
This is a temporary branch used to conduct the review process. The changes are already merged but there was not enough time for a clean review before the merge. Hence creating this artificial PR. The changes made as part of this PR will be applied to a `cse_3_1_updates`.

The overall changes are related to bringing in the TKGm functionality:

    VCDA-2776: Merge code of TKGm with immutable infra changes. (#1179)

    - also implement workaround for gosc issue
    - also implement any missing functionality

    Signed-off-by: Arun M. Krishnakumar <akrishnakuma@vmware.com>
    
        VCDA-2776: CSI and CPI integration with TKGm (#1185)

    VCDA-2475: set disk.enableUUID reusing Sakthi's code
    VCDA-2796: pass vip subnet to scripts
    VCDA-2781: reload vapp before checking status
    VCDA-2869: don't use placement policy for TKGm
    Also has:
    - fail strongly when expose_ip fails
    - handle vm.reboot failures
    - make scripts log better
    - fix resolve to use the correct way for 20.04 and beyond

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: 1 of 19 files reviewed, 1 unresolved discussion (waiting on @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 7 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCK6vvECTx6pbxRm0V:-MjCK6vw3sXRzlRsAn_Y:b-rr9xv6) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L7)):*
> ```Shell
>    error_message="$(date) $(caller): $BASH_COMMAND"
>    echo "$error_message" &>> /var/log/cse/customization/error.log
>    vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"
> ```

Recording the error message first, then recording the error status would be ideal.

Reason:
CSE code picks up the error code first then logs the error message. But if the error message is not yet recorded by then, it is showing up as <b>none</b? in the log file.  But this is a TODO

   error_message="$(date) $(caller): $BASH_COMMAND"
   echo "$error_message" &>> /var/log/cse/customization/error.log
   vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_failure_reason $error_message"
vmtoolsd --cmd "info-set guestinfo.post_customization_script_execution_status $?"

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: 18 of 19 files reviewed, 4 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 51 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCwa6W7Z9XceqU2B8w:-MjCwa6W7Z9XceqU2B8x:b-9ybt1k) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L51)):*
> ```Shell
> 
> vmtoolsd --cmd "info-set guestinfo.postcustomization.networkconfiguration.status in_progress"
>   echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
> ```

Is the spaces in front of these commands necessary? Or just for readability?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 63 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCwo0h5IXfFLUamZpf:-MjCwo0h5IXfFLUamZpg:buofhih) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L63)):*
> ```Shell
> vmtoolsd --cmd "info-set guestinfo.postcustomization.store.sshkey.status in_progress"
>   ssh_key="{ssh_key}"
>   if [[ ! -z "$ssh_key" ]];
> ```

Should this check be made before we set the status to progress and then to successfully?
I mean if the ssh key is empty then we are not doing anything at all right?
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCx0KjD46EhPVuQj_C:-MjCx0KjD46EhPVuQj_D:b-tlzkme) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L75)):*
> ```Shell
>   cat > /etc/systemd/resolved.conf << END
> [Resolve]
> DNS=10.166.1.201 8.8.8.8
> ```

Should this internal dns server be published for beta?

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: 18 of 19 files reviewed, 7 unresolved discussions (waiting on @arunmk, @ltimothy7, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 561 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjD9liPAf9XlFNZBTOw:-MjD9liQ1hFvQAwcr0DA:b84k5gm) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L561)):*
> ```Python
>         if current_template_name != desired_template_name or current_template_revision != desired_template_revision:  # noqa: E501
>             raise Exception(
>                 "Looks like an upgrade is required. "
> ```

I am not sure about the first line of error message. Also I think we can better phrase the error

"Cluster upgrade operation not supported for TKG clusters."
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 730 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjDAGs92oKpQfBE7pPi:-MjDAGs92oKpQfBE7pPj:b-qmdls9) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L730)):*
> ```Python
>             k8s_pod_cidr = TKGM_DEFAULT_POD_NETWORK_CIDR
>             if (
>                 input_native_entity.spec.settings is not None
> ```

#noqa: W504
___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 1098 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjDBISy-xD00yAPHNox:-MjDBISy-xD00yAPHNoy:b-s38f4u) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L1098)):*
> ```Python
> 
>                     # update kubeconfig with internal ip
>                     updated_kube_config = self._replace_kubeconfig_expose_ip(
> ```

We already have the current kubeconfig in the curr_native_entity right? Is there any reason to grab it again via a vcd call?

Also maybe we can rename this function to something else that clearly states that it is a text swap only. e.g. _update_control_plane_ip_value

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: 18 of 19 files reviewed, 7 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/common/constants/shared_constants.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjFai7D8_EAFFL3Yy-U:-MjFai7ECQyrR6VIa5zy:by0ft3a) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/container_service_extension/common/constants/shared_constants.py#L62)):*
> ```Python
>     NATIVE_CLUSTER_RUNTIME_INTERNAL_NAME: ClusterEntityKind.NATIVE.value,
>     TKG_PLUS_CLUSTER_RUNTIME_INTERNAL_NAME: ClusterEntityKind.TKG_PLUS.value,
>     TKG_M_CLUSTER_RUNTIME_INTERNAL_NAME: ClusterEntityKind.TKG_M.value,
> ```

redundant comma character

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186#-:-MjGFr6h5wMrWYjMySsS:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_tkgm.py, line 2076 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjGFO_M1fT4R5OT-3Jb:-MjGFO_M1fT4R5OT-3Jc:b-nqeqkq) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/container_service_extension/rde/backend/cluster_service_2_x_tkgm.py#L2076)):*
> ```Python
> 
>         parts = control_plane_join_cmd.split()
>         num_parts = 7
> ```

A small comment explaining how we got the number 7 might be useful.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 7 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: all files reviewed, 9 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[cse_def_schema/schema_2_0_0.json, line 417 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjGkMrG2YYmZyYN2G_N:-MjGkMrG2YYmZyYN2G_O:bfmmz4p) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cse_def_schema/schema_2_0_0.json#L417)):*
> ```JSON
>     },
>     "additionalProperties":true
> }
> ```

no change in this file

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1186)* status: all files reviewed, 9 unresolved discussions (waiting on @arunmk, @ltimothy7, @rocknes, and @sahithi)

___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 63 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCwo0h5IXfFLUamZpf:-MjFbM_17Jjj-vIsUN94:b23dxp) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L63)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should this check be made before we set the status to progress and then to successfully?
I mean if the ssh key is empty then we are not doing anything at all right?
</blockquote></details>

That is definitely a good point and I deliberated on that. I felt it better to have a nop phase. When we look at logs, it may become tough to decipher why some phases are skipped.
___
*[cluster_scripts/v2_x_tkgm/control_plane.sh, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1186#-MjCx0KjD46EhPVuQj_C:-MjFbkIaD-aQpQ49ARh9:bl1lw38) ([raw file](https://github.com/vmware/container-service-extension/blob/77250cdb081419672300d24dbfaafd1d2d41e112/cluster_scripts/v2_x_tkgm/control_plane.sh#L75)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should this internal dns server be published for beta? 
</blockquote></details>

Thanks, this should not be the case and I will remove it before we publish.

We definitely need to come up with a good way of doing this in the future. Maybe make it configurable.

**Comment by arunmk** [comment]
This has been merged to cse_3_1_updates

**Pull request closed without merging**
