### PR TITLE
VCDA-1995: Worker should validate master while joining

### PR DESCRIPTION
**Pull request by arunmk**
This change removes the `--discovery-token-unsafe-skip-ca-verification` in node join. This also changes script name to `nodev2.sh`. This will not immediately be merged to master but will rather accumulate in a branch with other related changes.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/892)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
Please use -s flag with your commits.
This Pr seems to have introduced flake8 errors, please fix those.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/892#-:-MS5v7Vf5mY8DO7ehntz:b-ujom3k)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Anirudh9794 and @sahithi)

**Comment by arunmk** [comment]
Done @rocknes

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/892)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)

___
*[container_service_extension/def_/cluster_service.py, line 2032 at r2](https://reviewable.io/reviews/vmware/container-service-extension/892#-MSVhn2U66rOvdnUhvda:-MSVhn2U66rOvdnUhvdb:b-3kur37) ([raw file](https://github.com/vmware/container-service-extension/blob/bbc622423d7f1af5ca613449d28afef77a6287e5/container_service_extension/def_/cluster_service.py#L2032)):*
> ```
> raise e.ScriptExecutionError(f"Error executing script in node {node_name}: {str(see)}")  # noqa: E501
> ```
Exception object is 'see'

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/892)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794, @arunmk, and @sahithi)

**Pull request closed without merging**
