### PR TITLE
[VCDA-2149] Dynamically determine the enitity class to use

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Use version string in entity type urn to dynamically figure out the destination Native entity type class

Testing done:
vcd cse cluster list
to check if entity parsing is happenning successfully

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/919)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/919)* status: 1 of 2 files reviewed, all discussions resolved

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/919)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/models/common_models.py, line 106 at r1](https://reviewable.io/reviews/vmware/container-service-extension/919#-MTwRZJ-0OVQiJPhXdIv:-MTwRZJ0530hMrwsNbzY:b-bechnd) ([raw file](https://github.com/vmware/container-service-extension/blob/a62e4aaf7baa1d0d05bee6880d73a8751aed3181/container_service_extension/rde/models/common_models.py#L106)):*
> ```Python
> 
>         # Get the entity type version from entity type urn
>         entity_type_version = self.entityType.split(":")[-1]
> ```

entity_type is not a required param.

We can mark this as a required param.

These are the places we create RDEs - 1. cluster_svc.create_cluster(), 2. cse upgrade 3. cse cli

With behaviors and Single API endpoint, we are going to slowly move away from creating RDEs as part of the cluster creation process. So, we need not worry much about (1)

That brings us down to handling (2) and (3). With that in mind, can you evaluate (2) and (3) and come up with a fix. I will also think about this when I get sometime.

**Review by sahithi — COMMENTED** [review]
:lgtm: Please do basic sanity testing by creating dummy RDEs in VCD.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/919#-:-MU5rK6l00oacEytmEiP:be01hyi)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
Tested code by creating a dummy 2.0.0 Entity Type and tried to list clusters

**Pull request merged**
