### PR TITLE
[VCDA-2563] Update TKG flags and constant names

### PR DESCRIPTION
**Pull request by rocknes**
Changed the constants and methods dealing with TKG(WCP) to TKG-S. The value of the constant were left intact, only the variable names were changed.

In CSE CLI, certain flags related to TKG+, TKG(WCP) and TKGm were changed to better reflect the marketing strategy around TKG.

TKG: --tkg/-t -> --tkg-s/-k
TKG+: --tkg-plus/-t/-k -> --tkg-plus/-p
TKGm: --tkg-m/-m -> --tkg/-t

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1071)

### CODE REVIEW

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1071)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/configure_cse.py, line 2182 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1071#-McLbBjSCif-6VNsprIs:-McLbBjSCif-6VNsprIt:b62j2yn) ([raw file](https://github.com/vmware/container-service-extension/blob/2f12cc312c53c4ec08920e96cf8be07899eaf9ed/container_service_extension/configure_cse.py#L2182)):*
> ```Python
>     elif 'tkgm' in template_name:
>         policy_name = \
>             shared_constants.TKG_M_CLUSTER_RUNTIME_INTERNAL_NAME
> ```

Should TKG_M variable names also be changed to TKG?
Similarly for the environment variable for TKGm, should it use the `TKG` instead of `TKG_M` fragment?

**Review by arunmk — APPROVED** [review]
:lgtm: 

Would there be any changes in sample generation, or does it use the strings of the ClusterEntityKind itself?

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1071#-:-McO6NcD9h0YfnLmVErD:bfqf71v)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1071#-:-McPCFSb0HTRqFgbhS19:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

**Review by rocknes — COMMENTED** [review]
No change in sample generation, some of those strings are coming from VCD so we can't change them.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1071#-:-McQCHwb0rx20rzT_rUs:bneyfqi)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/configure_cse.py, line 2182 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1071#-McLbBjSCif-6VNsprIs:-McQCNx3Bq9VgAgqrcuS:bjtb74z) ([raw file](https://github.com/vmware/container-service-extension/blob/2f12cc312c53c4ec08920e96cf8be07899eaf9ed/container_service_extension/configure_cse.py#L2182)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should TKG_M variable names also be changed to TKG?
Similarly for the environment variable for TKGm, should it use the `TKG` instead of `TKG_M` fragment?
</blockquote></details>

I thought hard about it but then decided to restrict the changes to only cli. The internal M distinction is for the developers, customers should only see TKG.. however with the environment variable I kept it as TKG_M since technically it is hidden switch and it's fine to keep it as is.

**Pull request merged**
