### PR TITLE
VCDA-1995: use token while joining clients

### PR DESCRIPTION
**Pull request by arunmk**
Signed-off-by: Arun M. Krishnakumar <arunmk@gmail.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Use token to validate master when joining cluster. Also added/refactored a little bit of code to take in scripts from the cse package.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Installed Cluster multiple times. Verified script generated and executed.

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @arunmk, @rocknes, and @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 179 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpfTmhALkI1B4BOlbh:-MTpfTmi1t_lsraic5kY:b6i44x7) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L179)):*
> ```Python
>     """Types of script for vApp template customizations in CSE."""
> 
>     SCRIPTS_DIR = "container_service_extension.rde.k8s_scripts"
> ```

nit:  SCRIPTS_DIR -> K8_SCRIPTS_DIR and K8sScriptFile

I suggest we version the scripts as well.

k8_scripts/
            1.X/
            2.X/
                mstr.sh
                node.sh
___
*[container_service_extension/common/constants/server_constants.py, line 180 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpg2RP19pu_XOBUCib:-MTpg2RQ0_NjmpFD9TE9:b-coq5m0) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L180)):*
> ```Python
> 
>     SCRIPTS_DIR = "container_service_extension.rde.k8s_scripts"
>     CLUSTER_UPGRADE_DIR = "container_service_extension.rde.k8s_scripts.cluster-upgrade" # noqa: E501
> ```

Are we moving upgrade_scripts as well to the local?
___
*[container_service_extension/common/utils/script_utils.py, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpgt7X6QMrZdWTdQeC:-MTpgt7X6QMrZdWTdQeD:b-m11e6x) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/utils/script_utils.py#L1)):*
> ```Python
> import importlib
> ```

please add a copyright header for all the new files.
___
*[container_service_extension/common/utils/script_utils.py, line 7 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpgktr8Etp-zW4xAn8:-MTpgktr8Etp-zW4xAn9:b85r6z3) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/utils/script_utils.py#L7)):*
> ```Python
> 
> 
> def get_package_file_contents(parent: str, filename: str) -> str:
> ```

docstrings
___
*[container_service_extension/rde/cluster_service.py, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpr9NK0aYH-CxkrQ3d:-MTpr9NK0aYH-CxkrQ3e:b-1pqpkf) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/rde/cluster_service.py#L24)):*
> ```Python
> from container_service_extension.common.constants.server_constants import ClusterMetadataKey  # noqa: E501
> from container_service_extension.common.constants.server_constants import CSE_CLUSTER_KUBECONFIG_PATH # noqa: E501
> from container_service_extension.common.constants.server_constants import DefEntityOperation  # noqa: E501
> ```

Do not edit this cluster_service.py. Pull my recent change and edit the new cluster_service_2_x.py

**Review by Anirudh9794 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: all files reviewed, 6 unresolved discussions (waiting on @arunmk, @rocknes, and @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 181 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTms6OY4OrvrnZ7w3eE:-MTms6OY4OrvrnZ7w3eF:bpfdfff) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L181)):*
> ```Python
>     SCRIPTS_DIR = "container_service_extension.rde.k8s_scripts"
>     CLUSTER_UPGRADE_DIR = "container_service_extension.rde.k8s_scripts.cluster-upgrade" # noqa: E501
>     CONTROL_PLANE = 'mstr.sh'
> ```

I think that we can now remove the term master from the scripts

**Comment by arunmk** [comment]
___
*[container_service_extension/common/constants/server_constants.py, line 180 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpg2RP19pu_XOBUCib:-MTrZ7A5-irlLE4beYT8:bqzn6qr) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L180)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Are we moving upgrade_scripts as well to the local?
</blockquote></details>

The upgrade scripts are not supposed to be moved and I cleaned up this part of the code. These wasn't referenced, so the variables had leaked.

**Comment by arunmk** [comment]
___
*[container_service_extension/common/constants/server_constants.py, line 181 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTms6OY4OrvrnZ7w3eE:-MTrZMiOCCpAdh-W2Szg:bq2hdr8) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L181)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think that we can now remove the term master from the scripts
</blockquote></details>

Could we do that as part of another change which fixes things up?

**Comment by arunmk** [comment]
___
*[container_service_extension/common/utils/script_utils.py, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpgt7X6QMrZdWTdQeC:-MTrZUdW9HXBjqo5vF-5:bqmjwcz) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/utils/script_utils.py#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please add a copyright header for all the new files.
</blockquote></details>

Added.

**Comment by arunmk** [comment]
___
*[container_service_extension/common/utils/script_utils.py, line 1 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpgt7X6QMrZdWTdQeC:-MTrZZw0EcVOHaevOR0L:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/utils/script_utils.py#L1)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Added.
</blockquote></details>

Done.

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/cluster_service.py, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpr9NK0aYH-CxkrQ3d:-MTrZe8E5uR6PC5B4-Qw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/rde/cluster_service.py#L24)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Do not edit this cluster_service.py. Pull my recent change and edit the new cluster_service_2_x.py
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/common/constants/server_constants.py, line 181 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTms6OY4OrvrnZ7w3eE:-MTrZkuEC2irnwJggZ8n:b-80tlqx) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L181)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Could we do that as part of another change which fixes things up?
</blockquote></details>

Sure!

**Comment by arunmk** [comment]
___
*[container_service_extension/common/constants/server_constants.py, line 179 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpfTmhALkI1B4BOlbh:-MTrZpu-EsXyq8PadqiY:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L179)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit:  SCRIPTS_DIR -> K8_SCRIPTS_DIR and K8sScriptFile

I suggest we version the scripts as well.

k8_scripts/
            1.X/
            2.X/
                mstr.sh
                node.sh
</blockquote></details>

Done

**Comment by arunmk** [comment]
___
*[container_service_extension/common/constants/server_constants.py, line 180 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpg2RP19pu_XOBUCib:-MTrZsdD4Q8CZbtnsB5a:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/constants/server_constants.py#L180)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

The upgrade scripts are not supposed to be moved and I cleaned up this part of the code. These wasn't referenced, so the variables had leaked.
</blockquote></details>

Done.

**Comment by arunmk** [comment]
___
*[container_service_extension/common/utils/script_utils.py, line 7 at r1](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTpgktr8Etp-zW4xAn8:-MTrZcQF8ZwzGisW09Ro:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/de834081163c14de7095bc8fe7e2f8431fc54d48/container_service_extension/common/utils/script_utils.py#L7)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

docstrings
</blockquote></details>

Done.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: 7 of 12 files reviewed, 5 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/common/utils/script_utils.py, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTxT7hBA07WCtWW1nGe:-MTxT7hBA07WCtWW1nGf:bbf81ko) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/common/utils/script_utils.py#L2)):*
> ```Python
> # container-service-extension
> # Copyright (c) 2020 VMware, Inc. All Rights Reserved.
> ```

2021 VMware, Inc

**Review by sakthisunda — APPROVED** [review]
> Reviewed 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: all files reviewed, 5 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 2018 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5sn6p4yTeU-fvYjb7:-MU5sn6p4yTeU-fvYjb8:b-5zzezq) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/backend/cluster_service_1_x.py#L2018)):*
> ```Python
> 
>     try:
>         templated_script = get_cluster_script_file_contents(
> ```

Any reason why named it _templated_script_? Why not as simple as "control_plane_script"?
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2018 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5uSAN8H3rQ61gZTGj:-MU5uSAN8H3rQ61gZTGk:bis8476) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/backend/cluster_service_2_x.py#L2018)):*
> ```Python
> 
>     try:
>         templated_script = get_cluster_script_file_contents(
> ```

Same here, the variable name is misleading.
___
*[container_service_extension/rde/cluster_scripts/1_x/mstr.sh, line 1 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5vDfX8VMF5pBJMmau:-MU5vDfX8VMF5pBJMmav:b4g6sv0) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/cluster_scripts/1_x/mstr.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Please move the script files one level up _container_service_extension_ package - at the level of cse_def_schema package.

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2018 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5uSAN8H3rQ61gZTGj:-MU6A3yLAxJMCgdqw4te:bkmtd6i) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/backend/cluster_service_2_x.py#L2018)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Same here, the variable name is misleading.
</blockquote></details>

This is a template of a script and not the script itself. There are placeholders to be filled in this script template and that is done in the following line `script = templated_script.format(...)`. Unless the template is filled completely, the script will not run. Hence I called it a templated_script.

Could you tell me if there is a better name for this

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/cluster_scripts/1_x/mstr.sh, line 1 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5vDfX8VMF5pBJMmau:-MU6DQ4vAFaQ7pmmqyuK:b-yl2g7k) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/cluster_scripts/1_x/mstr.sh#L1)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please move the script files one level up _container_service_extension_ package - at the level of cse_def_schema package.
</blockquote></details>

ACK, it is now directly under GITROOT and a peer of cse_def_schema. Was that what you meant?

**Comment by arunmk** [comment]
___
*[container_service_extension/common/utils/script_utils.py, line 2 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MTxT7hBA07WCtWW1nGe:-MU6DkP0DSc8TpwiELMA:b7ulu0v) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/common/utils/script_utils.py#L2)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

2021 VMware, Inc
</blockquote></details>

Done. Thanks for spotting this Sakthi

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 8 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917#-:-MUA9uMA5_61S0x57qoV:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk, @rocknes, @sahithi, and @sakthisunda)

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 2018 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5sn6p4yTeU-fvYjb7:-MUBL_QO5_uyqtLxTw4l:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/backend/cluster_service_1_x.py#L2018)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any reason why named it _templated_script_? Why not as simple as "control_plane_script"?
</blockquote></details>

Done.

**Comment by arunmk** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 2018 at r2](https://reviewable.io/reviews/vmware/container-service-extension/917#-MU5uSAN8H3rQ61gZTGj:-MUBLbGV8y5tV4nx_aUc:b-iujnrn) ([raw file](https://github.com/vmware/container-service-extension/blob/78153a27c98eee94382638147accdcf2616a9f2d/container_service_extension/rde/backend/cluster_service_2_x.py#L2018)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This is a template of a script and not the script itself. There are placeholders to be filled in this script template and that is done in the following line `script = templated_script.format(...)`. Unless the template is filled completely, the script will not run. Hence I called it a templated_script.

Could you tell me if there is a better name for this
</blockquote></details>

Done. Followed up offline and this seems to be okay.

**Review by arunmk — COMMENTED** [review]
> Dismissed @sahithi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/917#-:-MUBPJlT2lya0naxFrzD:bg7igkv)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @rocknes, @sahithi, and @sakthisunda)

**Pull request merged**
