### PR TITLE
[VCDA-2894, VCDA-2906] Improve sample cluster spec generation, Add support for TKGm 1.4.0 OVA

### PR DESCRIPTION
**Pull request by rocknes**
Improve sample cluster spec generation for native and TKGm
1. TKGm - Delete NFS section, Add default cidrs for pod and service. Change default of `expose` value to True.
2. Native - Hide pod and service cidr sections

Make sure that the new TKGm 1.4.0 OVAs are not flagged by the regex matcher.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1206)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1206#-:-MkNujw23Ci6jqDmk-D5:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1206)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 631 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1206#-MkO9xpf5b4VQvZDV_JX:-MkO9xpf5b4VQvZDV_JY:b7mj2fo) ([raw file](https://github.com/vmware/container-service-extension/blob/e76079d3f24c6513778bec7f1a18fc8aefae6220/container_service_extension/rde/models/rde_2_0_0.py#L631)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             del native_entity_dict['spec']['topology']['controlPlane']['cpu']
>             del native_entity_dict['spec']['topology']['controlPlane']['memory']  # noqa: E501
>             del native_entity_dict['spec']['topology']['workers']['cpu']
>             del native_entity_dict['spec']['topology']['workers']['memory']
> ```
</details>

We should not be deleting cpu and memory for TKGm, right?

**Review by rocknes — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1206)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/models/rde_2_0_0.py, line 631 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1206#-MkO9xpf5b4VQvZDV_JX:-MkOGAn-5RxuLuDHcwNb:b-53ey4c) ([raw file](https://github.com/vmware/container-service-extension/blob/e76079d3f24c6513778bec7f1a18fc8aefae6220/container_service_extension/rde/models/rde_2_0_0.py#L631)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>             del native_entity_dict['spec']['topology']['controlPlane']['cpu']
>             del native_entity_dict['spec']['topology']['controlPlane']['memory']  # noqa: E501
>             del native_entity_dict['spec']['topology']['workers']['cpu']
>             del native_entity_dict['spec']['topology']['workers']['memory']
> ```
We should not be deleting cpu and memory for TKGm, right?
</blockquote></details>

Right, I will fix it. Thanks for catching it.

**Pull request merged**
