### PR TITLE
[VCDA-2640] Port cluster expose feature to Cluster Service 2.x

### PR DESCRIPTION
**Pull request by rocknes**
Port `cluster expose` feature from cluster_service_1_x.py to cluster_serivce_2_x.py.

Add new field `external_ip` for RDE 2.0.0. Add associated logic to retain the internal control plane ip while exposing the cluster.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)

### CODE REVIEW

**Review by rocknes — COMMENTED** [review]
> Reviewed 4 of 6 files at r1, 2 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 1085 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZ5WBY4Dpg5pCnXmlo:-MdZ5WBY4Dpg5pCnXmlp:bkhyymf) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_1_x.py#L1085)):*
> ```Python
>                         f"Failed to unexpose cluster with error: {str(err)}",
>                         exc_info=True
>                     )
> ```

Do we usually leave the closing parenthesis on its own line or  part of the previous line? Just wondering if there is a common pattern
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1040 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZ6pqwDa1lWAqTM1TR:-MdZ6pqwDa1lWAqTM1TS:b-8yrdaz) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1040)):*
> ```Python
> 
>             self._update_cluster_entity(
>                 cluster_id, new_status,
> ```

nit: I think `new_status` should be on its own line

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: all files reviewed, 5 unresolved discussions (waiting on @rocknes)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 832 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZQX_uAxogRCJUqyHD:-MdZQX_uAxogRCJUqyHE:b18sbmk) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L832)):*
> ```Python
>                               input_native_entity: rde_2_x.NativeEntity):
>         cluster_name = ''
>         rollback = False
> ```

Default value for rollback is True.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1037 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZSmQi73Pv3s0kYAV1:-MdZSmQi73Pv3s0kYAV2:b2z04k1) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1037)):*
> ```Python
>                 new_status.cloud_properties.exposed = True
>                 if new_status.nodes and new_status.nodes.control_plane:
>                     new_status.nodes.control_plane.ip = expose_ip
> ```

I suggest adding a new property called "external_ip" in the cloud_properties. Overwriting the master internal IP doesn't seem right.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1953 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZRluECq6IgN5LRpeE:-MdZRluECq6IgN5LRpeF:bpbe9cf) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1953)):*
> ```Python
>                 curr_rde.entity.status.nodes and \
>                 curr_rde.entity.status.nodes.control_plane:
>             curr_nodes_status.control_plane.ip = curr_rde.entity.status.nodes.control_plane.ip  # noqa: E501
> ```

We should not be needing this block if we had another property called "external_ip".

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_1_x.py, line 1085 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZ5WBY4Dpg5pCnXmlo:-MdZit8y-ug9Aw5snNz2:b-an95va) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_1_x.py#L1085)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Do we usually leave the closing parenthesis on its own line or  part of the previous line? Just wondering if there is a common pattern
</blockquote></details>

Either is fine, Off late I am realizing that leaving the parenthesis on the next line, makes it much easier to see blocks.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 832 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZQX_uAxogRCJUqyHD:-MdZf0kOCcKeEZ4lMPEe:b8taoag) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L832)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Default value for rollback is True.
</blockquote></details>

We don't need the default value here. It will be picked up in the first few lines of the try block.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1040 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZ6pqwDa1lWAqTM1TR:-MdZiKG04MX_WLvXCWCa:bx3iq6m) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1040)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: I think `new_status` should be on its own line
</blockquote></details>

Addressed

**Review by rocknes — COMMENTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: 8 of 9 files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1037 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZSmQi73Pv3s0kYAV1:-Md_ONZy2t3z0J4NgUv3:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1037)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest adding a new property called "external_ip" in the cloud_properties. Overwriting the master internal IP doesn't seem right.
</blockquote></details>

Done
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1953 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdZRluECq6IgN5LRpeE:-Md_OR8w294g2wARdVXR:bb6un1j) ([raw file](https://github.com/vmware/container-service-extension/blob/57d0d86ececebfc0b508655831a060aade9630d5/container_service_extension/rde/backend/cluster_service_2_x.py#L1953)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We should not be needing this block if we had another property called "external_ip".
</blockquote></details>

Done

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1253 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdcKrpJ27MiXHTUGRjd:-MdcKrpJ27MiXHTUGRje:bphdc2a) ([raw file](https://github.com/vmware/container-service-extension/blob/a670f05b8fef30ded093d312517bcdb86a079ff9/container_service_extension/rde/backend/cluster_service_2_x.py#L1253)):*
> ```Python
>                     # external ip, we need to set it back to the true
>                     # internal ip.
>                     curr_native_entity.status.nodes.control_plane.ip = control_plane_internal_ip  # noqa: E501
> ```

This step should ideally be done in the "cse upgrade" workflow. Something like below
if rde1.status.exposed = true:
.....rde2.status.external_ip = rde1.status.nodes.master.ip
.....rde2.status.nodes.master.ip = getvapp(rde1.externalId).getmasterIp()
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 299 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdcIF7FBIQ74CCtjmmt:-MdcIF7FBIQ74CCtjmmu:b-bl2vd0) ([raw file](https://github.com/vmware/container-service-extension/blob/a670f05b8fef30ded093d312517bcdb86a079ff9/container_service_extension/rde/models/rde_1_0_0.py#L299)):*
> ```Python
>                 docker_version=rde_2_x_entity.status.docker_version,
>                 os=rde_2_x_entity.status.os,
>                 nodes=nodes,
> ```

Don't we have to update the RDE2.0 external IP in the RDE 1.0?

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: 6 of 9 files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1253 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdcKrpJ27MiXHTUGRjd:-MdcNyeu7Let8Lrq-vTx:bgd1sc6) ([raw file](https://github.com/vmware/container-service-extension/blob/a670f05b8fef30ded093d312517bcdb86a079ff9/container_service_extension/rde/backend/cluster_service_2_x.py#L1253)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     self._replace_kubeconfig_expose_ip(
>                         internal_ip=control_plane_internal_ip,
>                         cluster_id=cluster_id,
>                         vapp=vapp)
> ```
</details>

needs internal ip .. so the check and retrival of internal ip needs to happen earlier.
Also we can't really on control_plane.ip as internal ip.

`if unexpose` condition checks the condition you mentioned.

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 2 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094#-:-MdcYMKgDa82C-aLM02I:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1094)* status: 7 of 9 files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 1253 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdcKrpJ27MiXHTUGRjd:-Mdce9ep6wqqdvZJA7kV:bv4pd7p) ([raw file](https://github.com/vmware/container-service-extension/blob/a670f05b8fef30ded093d312517bcdb86a079ff9/container_service_extension/rde/backend/cluster_service_2_x.py#L1253)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

> ```
>                     self._replace_kubeconfig_expose_ip(
>                         internal_ip=control_plane_internal_ip,
>                         cluster_id=cluster_id,
>                         vapp=vapp)
> ```
needs internal ip .. so the check and retrival of internal ip needs to happen earlier.
Also we can't really on control_plane.ip as internal ip.

`if unexpose` condition checks the condition you mentioned.


</blockquote></details>

Sorry, misunderstood your comment. Addressed
___
*[container_service_extension/rde/models/rde_1_0_0.py, line 299 at r6](https://reviewable.io/reviews/vmware/container-service-extension/1094#-MdcIF7FBIQ74CCtjmmt:-Mdce2jm0mpMB2yxQD2Q:b-y0fdbm) ([raw file](https://github.com/vmware/container-service-extension/blob/a670f05b8fef30ded093d312517bcdb86a079ff9/container_service_extension/rde/models/rde_1_0_0.py#L299)):*
> Don't we have to update the RDE2.0 external IP in the RDE 1.0?
Done

**Pull request merged**
