### PR TITLE
[VCDA-1941] Cluster unshare CLI

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
- Implemented cluster unshare command for native and TKG clusters

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested with native and TKG clusters. This PR also includes a bug fix in cluster sharing.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @sakthisunda @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858)

### CODE REVIEW

**Review by arunmk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

___
*[container_service_extension/client/cluster_commands.py, line 1136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn-xN5Ea1_uAAU-6mW:-MOn-xN5Ea1_uAAU-6mX:b53nb0o) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/cluster_commands.py#L1136)):*
> ```Python
>     """  # noqa: E501
>     try:
>         if not (cluster_id or name):
> ```

What is the expected behavior if both are specified. We should probably at least validate that cluster_id and cluster_name point to the same cluster.
___
*[container_service_extension/client/de_cluster.py, line 350 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn75yP6vaeI7O7yDCO:-MOn75yP6vaeI7O7yDCP:b-631def) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster.py#L350)):*
> ```Python
>     def unshare_cluster(self, cluster_id, cluster_name, users: list, org=None,
>                         vdc=None):
>         if cluster_id:
> ```

The pattern in other functions of `if not cluster_id, get the cluster id from name` seems to be a good pattern to follow everywhere. Else we need to validate that the cluster_name and cluster_id point to the same cluster etc. In inner functions, we could omit one of them and just use cluster_id everywhere. (not sure about current pattern, this is imo)
___
*[container_service_extension/client/de_cluster_native.py, line 314 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn4MI_DxGqv_l5dYmv:-MOn4MI_DxGqv_l5dYmw:b-htjla9) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L314)):*
> ```Python
>             cluster_id = self.get_cluster_id_by_name(cluster_name, org, vdc)
> 
>         delete_users_set = set(users)
> ```

nit: We could check for to see if a modification is needed before making the call (`len(users)==0` seems to be a valid input here). For example, `setA.isdisjoint(setB)` implies early return. Also, we could potentially avoid the O(mn) loop by using set ".difference" method but it could be overkill.
___
*[container_service_extension/client/de_cluster_native.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn1dnT9ERTA_8aR2do:-MOn1dnT9ERTA_8aR2dp:b-qe24u0) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L325)):*
> ```Python
>                 delete_users_set.remove(acl_entry.username)
> 
>         if len(delete_users_set) > 0:
> ```

I think this should be a warning / notification rather than a strong error.
___
*[container_service_extension/client/de_cluster_tkg.py, line 437 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOnC8HuCtniVXMsShoR:-MOnC8HvBJYzJH3sdqqm:b-xpswtt) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_tkg.py#L437)):*
> ```Python
> 
>         # Delete cluster acl entries
>         for acl_id in delete_acl_ids:
> ```

What is the scale of unshares that we get..like if we have 100 shares and we unshare 99, we will issue 99 calls to the server if I understant this corectly.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @ltimothy7)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOnCfjdCLZoBjVWE6wB:-MOnCfjdCLZoBjVWE6wC:b9mdpln) (no related file):*
This looks good to me in general. My comments are more about myself understanding the codebase.

---

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @arunmk)

*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOnCfjdCLZoBjVWE6wB:-MOrESBH91FwoAF7T2U6:b26o6wa) (no related file):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

This looks good to me in general. My comments are more about myself understanding the codebase.
</blockquote></details>

Thank you, please let me know if there are any other changes you think should happen.

---
___
*[container_service_extension/client/cluster_commands.py, line 1136 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn-xN5Ea1_uAAU-6mW:-MOrAs2KEzXWF3aYcCA8:b-kp1gl8) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/cluster_commands.py#L1136)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

What is the expected behavior if both are specified. We should probably at least validate that cluster_id and cluster_name point to the same cluster.
</blockquote></details>

Hi Arun,
If both are specified, cluster_id takes precedence. We have included this info in the help string for the --id option. 
___
*[container_service_extension/client/de_cluster.py, line 350 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn75yP6vaeI7O7yDCO:-MOrB4hU2NdRT_OHRYwC:bj3q3gq) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster.py#L350)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

The pattern in other functions of `if not cluster_id, get the cluster id from name` seems to be a good pattern to follow everywhere. Else we need to validate that the cluster_name and cluster_id point to the same cluster etc. In inner functions, we could omit one of them and just use cluster_id everywhere. (not sure about current pattern, this is imo)
</blockquote></details>

I am not using that pattern here because the role of this statement is to determine the cluster type. Once the cluster type is determined, the unshare_cluster function for that cluster type is used (see share_cluster function). The pattern above is used for getting the cluster_id in the native and tkg unshare_cluster functions because the cluster_id needs to be used in those functions. We are not omitting `cluster_name` because the de_cluster_native and de_cluster_tkg functions can be called directly in cluster_commands.py; this is why the function parameters are the same for de_cluster, de_cluster_native, and de_cluster_tkg files.

I think it is okay if we do not validate the cluster_name and cluster_id because we have specified that cluster_id takes precedence if both parameters are passed in. We also are not validating the cluster_name and cluster_id in other cluster functions. Please let me know what you think.
___
*[container_service_extension/client/de_cluster_native.py, line 314 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn4MI_DxGqv_l5dYmv:-MOrCq080_BvqT8iY7ay:b-fp9sst) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L314)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

nit: We could check for to see if a modification is needed before making the call (`len(users)==0` seems to be a valid input here). For example, `setA.isdisjoint(setB)` implies early return. Also, we could potentially avoid the O(mn) loop by using set ".difference" method but it could be overkill.
</blockquote></details>

Thank you, Arun.  I don't think `len(users)==0` is possible because the CLI will fail if no users are specified. If the sets are disjoint, the client will get the warning that the cluster is not shared with the passed in users. 

Could you describe how the loop is O(mn)? I thought it was O(m) since it is just iterating through the native_cluster_acl_entries and the username is looked up in  delete_users_set, but it would be helpful to optimize.
___
*[container_service_extension/client/de_cluster_native.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn1dnT9ERTA_8aR2do:-MOrDlvI2tLOMQRg4Yi9:b-gcmk6f) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L325)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

I think this should be a warning / notification rather than a strong error.
</blockquote></details>

I was trying to copy an all-or-nothing approach that I have seen in vcd-cli. For example, the command `vcd cse role add-rights` takes in a list of rights, but if one right is incorrect, none of the rights are added. Let me know if you think a warning would still be better.
___
*[container_service_extension/client/de_cluster_tkg.py, line 437 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOnC8HuCtniVXMsShoR:-MOrEGT85Cx_vEHmYXjO:b-8sahsu) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_tkg.py#L437)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

What is the scale of unshares that we get..like if we have 100 shares and we unshare 99, we will issue 99 calls to the server if I understant this corectly.
</blockquote></details>

Yes, each unshare will be a call an API call. We have to make a call for each acl entry.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/client/de_cluster_native.py, line 314 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn4MI_DxGqv_l5dYmv:-MOrKLhs2ULSaglzcDHv:b6ugnwh) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L314)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Thank you, Arun.  I don't think `len(users)==0` is possible because the CLI will fail if no users are specified. If the sets are disjoint, the client will get the warning that the cluster is not shared with the passed in users. 

Could you describe how the loop is O(mn)? I thought it was O(m) since it is just iterating through the native_cluster_acl_entries and the username is looked up in  delete_users_set, but it would be helpful to optimize.
</blockquote></details>

I'm sorry it should be O(m) * O(1) since set lookup is amortized O(1) in python
___
*[container_service_extension/client/de_cluster_native.py, line 325 at r1](https://reviewable.io/reviews/vmware/container-service-extension/858#-MOn1dnT9ERTA_8aR2do:-MOrL7AV7hTrIdIHvQQh:b-egjhoc) ([raw file](https://github.com/vmware/container-service-extension/blob/9ac2c9ea0e3478bcb717c5d5185f3b944c400b72/container_service_extension/client/de_cluster_native.py#L325)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I was trying to copy an all-or-nothing approach that I have seen in vcd-cli. For example, the command `vcd cse role add-rights` takes in a list of rights, but if one right is incorrect, none of the rights are added. Let me know if you think a warning would still be better.
</blockquote></details>

That was my feeling. I let others take the call.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/de_cluster_tkg.py, line 432 at r2](https://reviewable.io/reviews/vmware/container-service-extension/858#-MP5dZkf8h5JoY4_n0y_:-MP5dZkf8h5JoY4_n0ya:b-89oze4) ([raw file](https://github.com/vmware/container-service-extension/blob/cf18e8a51ee9c170a5b2681790f2a7605d3a129d/container_service_extension/client/de_cluster_tkg.py#L432)):*
> ```Python
>             org_user_id_to_name_dict = utils.create_org_user_id_to_name_dict(
>                 self._client, org)
>             unfound_users = [org_user_id_to_name_dict[user_id] for user_id in users_ids]  # noqa: E 501
> ```

E501*

**Review by Anirudh9794 — COMMENTED** [review]
:lgtm: once decision on all-or-nothing commands is made

> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/858#-:-MP5kPVTBFrksdODqAB2:b-ymidc9)* status: all files reviewed, 4 unresolved discussions (waiting on @arunmk and @ltimothy7)

**Pull request merged**
