### PR TITLE
[VCDA-2410] Redirect v35_handler to 36_handler if runtime_rde >= 2.0

### PR DESCRIPTION
**Pull request by sakthisunda**
- Delegate RDE 2.0 operations to right handler 
- Currently, if any version=35.0 call is handled by v35 handler, which is default handler for RDE 1.0. When the runtime RDE supported is RDE 2.0, delegate that to RDE 2.0 handler(cluster_handler). Thus, all RDE 2.0 and above will be directly handled by cluster_service_2x_behavior handler.
- Reject payloads of RDE 2.0 in v35 handler
- Tested using Postman for cluster creation, resize, upgrade and delete
----------------

Screen Shot 2021-05-18 at 5 46 38 PM
Screen Shot 2021-05-18 at 5 46 20 PM
Screen Shot 2021-05-18 at 5 45 58 PM
Screen Shot 2021-05-18 at 5 45 36 PM
-----------------------------------

@Anirudh9794 @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1034#-M_cLF6y2Kqwq42P05y7:-M_cLF6y2Kqwq42P05y8:b-i6otpr) ([raw file](https://github.com/vmware/container-service-extension/blob/a49d0fb182404f759b23e7cb00cafa75e1f9f755/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L39)):*
> ```Python
>     rde_in_use = server_utils.get_rde_version_in_use()
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.cluster_create(data=data, op_ctx=op_ctx)
> ```

This would outright fail in the common cluster_handler.py because payload_version is not present.
We may have to pass the dict of the converted entity.

I just realized that we do not have 1.0 validators implemented and it is tricky to validate and then redirect the request to the cluster_handler.py. 

Once the converted_entity is passed as an input into the cluster_handler, we can rely on validation in that file. That is one way to avoid extra implementation at this point. As this is a one-time operation to support backward compatibility. I think it is okay to cut this corner.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1034#-M_cLF6y2Kqwq42P05y7:-Ma1OGc50l8CiXZcY5kr:b-29ks28) ([raw file](https://github.com/vmware/container-service-extension/blob/a49d0fb182404f759b23e7cb00cafa75e1f9f755/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L39)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This would outright fail in the common cluster_handler.py because payload_version is not present.
We may have to pass the dict of the converted entity.

I just realized that we do not have 1.0 validators implemented and it is tricky to validate and then redirect the request to the cluster_handler.py. 

Once the converted_entity is passed as an input into the cluster_handler, we can rely on validation in that file. That is one way to avoid extra implementation at this point. As this is a one-time operation to support backward compatibility. I think it is okay to cut this corner.
</blockquote></details>

<li> Converted the input entity before delegating to RDE 2.0 based generic handler
<li>  Ensure that all other input values that are outside of actual <b>spec</b> say cluster_id 
<li> similar changes to resize, upgrade

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034#-:-Ma4XbVe3Ys5LFetT6Ck:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1034#-M_cLF6y2Kqwq42P05y7:-Ma617dz508FCON5qCz7:b-z1ttk7) ([raw file](https://github.com/vmware/container-service-extension/blob/a49d0fb182404f759b23e7cb00cafa75e1f9f755/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L39)):*
> ```
>     new_native_entity: AbstractNativeEntity = rde_utils.convert_runtime_rde_to_input_rde_version_format(  # noqa: E501
>         new_rde.entity, rde_constants.RDEVersion.RDE_1_0_0)
> ```
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 44 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1034#-Ma618Gf50iKWmpe7XJ1:-Ma618Gg7CmG1CPQCCf5:bcrw7de) ([raw file](https://github.com/vmware/container-service-extension/blob/30fb31c15fafd045e7f85cf284e951db0ca844a1/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L44)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.cluster_create(
> ```

Sakthi, we need to convert the return value to 1.0 dict before sending it out. We cannot break backward compatibility

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 44 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1034#-Ma618Gf50iKWmpe7XJ1:-Ma6c_-z8KsaD8cmV8fN:bs7wumx) ([raw file](https://github.com/vmware/container-service-extension/blob/30fb31c15fafd045e7f85cf284e951db0ca844a1/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L44)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Sakthi, we need to convert the return value to 1.0 dict before sending it out. We cannot break backward compatibility
</blockquote></details>

Done.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 39 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1034#-M_cLF6y2Kqwq42P05y7:-Ma6cd8V-W3pui3bdH_P:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a49d0fb182404f759b23e7cb00cafa75e1f9f755/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L39)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>     new_native_entity: AbstractNativeEntity = rde_utils.convert_runtime_rde_to_input_rde_version_format(  # noqa: E501
>         new_rde.entity, rde_constants.RDEVersion.RDE_1_0_0)
> ```

</blockquote></details>

Done.

**Review by Anirudh9794 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: all files reviewed, 10 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 60 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB4x-U-F0POLyRZXO0:-MaB4x-U-F0POLyRZXO1:b-ppae58) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L60)):*
> ```Python
>     new_native_entity: AbstractNativeEntity = rde_utils.convert_runtime_rde_to_input_rde_version_format(  # noqa: E501
>         new_rde.entity, rde_constants.RDEVersion.RDE_1_0_0)
>     new_rde.entity = new_native_entity
> ```

new_rde.entityType = entityTypeId of the input entity type.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 101 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB4_r5E_k5wyR666fo:-MaB4_r5E_k5wyR666fp:b-ffpkre) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L101)):*
> ```Python
>     new_native_entity: AbstractNativeEntity = rde_utils.convert_runtime_rde_to_input_rde_version_format(  # noqa: E501
>         new_rde.entity, rde_constants.RDEVersion.RDE_1_0_0)
>     new_rde.entity = new_native_entity
> ```

new_rde.entityType = entityTypeId of the input entity type.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 120 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB57kX4k76_G3yixJd:-MaB57kX4k76_G3yixJe:b-c07dqb) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L120)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.cluster_delete(data=data, op_ctx=op_ctx)
> ```

Is there any reason we are not responding with the request entity type for delete?
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 144 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5KGY1j-XHT63wEqw:-MaB5KGY1j-XHT63wEqx:b-burme1) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L144)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.cluster_info(data=data, op_ctx=op_ctx)
> ```

I believe we should only be sending out 1.0 response in v35 handler. 
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 226 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5djLClOAe71jff7c:-MaB5djLClOAe71jff7d:b-lck600) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L226)):*
> ```Python
>     new_native_entity: AbstractNativeEntity = rde_utils.convert_runtime_rde_to_input_rde_version_format(  # noqa: E501
>         new_rde.entity, rde_constants.RDEVersion.RDE_1_0_0)
>     new_rde.entity = new_native_entity
> ```

new_rde.entityType = entity type id matching the request payload
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 242 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5qQM7zztMhkG4WuB:-MaB5qQM7zztMhkG4WuC:b-5i07qh) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L242)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.native_cluster_list(data=data, op_ctx=op_ctx)
> ```

Should we be looping the response to convert all the entities to 1.0?
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 328 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB61d5CIzPsr6gs2zD:-MaB61d5CIzPsr6gs2zE:b-4y02g7) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L328)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         return cluster_handler.cluster_list(data=data, op_ctx=op_ctx)
> ```

Should we be looping over the response to convert all the entities to 1.0?
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 371 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB69_26Rnklg0NKxUw:-MaB69_26Rnklg0NKxUx:bl6ueg8) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L371)):*
> ```Python
>     # Redirect to generic handler if the backend supports RDE-2.0
>     if semantic_version.Version(rde_in_use) > semantic_version.Version(rde_constants.RDEVersion.RDE_1_0_0.value):  # noqa: E501
>         return cluster_handler.nfs_node_delete(data=data, op_ctx=op_ctx)
> ```

You can remove the changes in this function as it is addressed in my PR

**Review by sahithi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: all files reviewed, 11 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 42 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaBEs8C67GJNw7uuMnw:-MaBEs8C67GJNw7uuMnx:b-i1xhhw) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L42)):*
> ```Python
>     input_entity: dict = data[RequestKey.INPUT_SPEC]
>     payload_version = input_entity.get(rde_constants.PayloadKey.PAYLOAD_VERSION_RDE_1_0.value)  # noqa: E501
>     _raise_error_if_unsupported_payload_version(payload_version)
> ```

Reject request >= 2.0 - comment
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 120 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB57kX4k76_G3yixJd:-MaBFQJb5_hiwuyGHaXS:b5lwtfi) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L120)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is there any reason we are not responding with the request entity type for delete?
</blockquote></details>

conversion to 1.0 is needed

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 42 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaBEs8C67GJNw7uuMnw:-MaFzthG8SYUqJVl_van:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L42)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Reject request >= 2.0 - comment
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 60 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB4x-U-F0POLyRZXO0:-MaFzuzBBwFcuUBT3FS1:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L60)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

new_rde.entityType = entityTypeId of the input entity type.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 101 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB4_r5E_k5wyR666fo:-MaFzwU9AKM9f8gbghqx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L101)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

new_rde.entityType = entityTypeId of the input entity type.
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 120 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB57kX4k76_G3yixJd:-MaFzyIA93b927Fo5O-u:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L120)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

conversion to 1.0 is needed
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 144 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5KGY1j-XHT63wEqw:-MaG-2wv1nsIkghRSMbK:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L144)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I believe we should only be sending out 1.0 response in v35 handler. 
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 226 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5djLClOAe71jff7c:-MaG-4-q9SXxCDxudmlz:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L226)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

new_rde.entityType = entity type id matching the request payload
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 242 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5qQM7zztMhkG4WuB:-MaG-6HK2swYdZ5UHnlI:b-bj1g1z) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L242)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should we be looping the response to convert all the entities to 1.0?
</blockquote></details>

This is a TODO and needs to be discussed
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 328 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB61d5CIzPsr6gs2zD:-MaG-J-05mCVvKcjcpHj:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L328)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Should we be looping over the response to convert all the entities to 1.0?
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 371 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB69_26Rnklg0NKxUw:-MaG-K--9fnthXwPJo8L:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L371)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

You can remove the changes in this function as it is addressed in my PR
</blockquote></details>

Done.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 242 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaB5qQM7zztMhkG4WuB:-MaG4-NXDYhmcGoXeacO:b8hlh8) ([raw file](https://github.com/vmware/container-service-extension/blob/91ddb0f7c2373cf20051318902f0bc09f6b8cb58/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L242)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

This is a TODO and needs to be discussed
</blockquote></details>

Completed as discussed. 
<li> Get values from result set
<li> iterate thru value list
<li> format conversion of each rde
<li> new list of formatted rde 
<li> assign it to result set back

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1034#-:-MaVTOS0CX5dfjEbYHK9:bg7igkv)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 55 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1034#-MaVQxYZ0cGLAyen07G2:-MaVQxYZ0cGLAyen07G3:b6se0sh) ([raw file](https://github.com/vmware/container-service-extension/blob/7e2502acfe70f905fb7e657f0955a4b03721b90f/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L55)):*
> ```Python
>     else:
>         # Based on the runtime rde, call the appropriate backend method.
>         svc = cluster_service_factory.ClusterServiceFactory(op_ctx).get_cluster_service()  # noqa: E501
> ```

This else block will only handle when runtime RDE is 1.0, for which we already have an if condition.
We can directly use cluster-service1x module in the else part. 
Just a thought. I am okay with this.

**Pull request merged**
