### PR TITLE
Port [VCDA-2040 and VCDA-2043] Nsxt edge gateway (updates branch) to master

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>
To help us process your pull request efficiently, please include: 

Original PR: https://github.com/vmware/container-service-extension/pull/900 

- (Required) Short description of changes in the PR topic line
-Porting nsxt backed gateway service class to main branch

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested quick ip allocation and adding dnat rule.

- (Optional) Names of reviewers using @ sign + name
@rocknes @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/902)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/902#-:-MSnz3cX7Ht2S9oMty69:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — CHANGES_REQUESTED** [review]
Please add reference to the original PRs that were submitted in cse_3_0_updates.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/902#-:-MTBzMtg5XuGKoeq9CdE:b-x3f3ee)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
@rocknes Just updated the Github page with the original PR and changed the title

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/902#-:-MTC3fDDENJgtnhiHVtH:b-4cbw98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/902#-:-MUBAiwv3tV_a_MFxKx8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Pull request merged**
