### PR TITLE
[VCDA-2282] Test and Fix CRUD operations via behaviors

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Update cluster_service_*_behaviors.py
* Delete entity if create fails in the sync portion

Testing done
* Create entity
* Update entity
* Delete entity

@sahithi @sakthisunda @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 485 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2_foACrLl8hQr0NKB:-M_2_foB9_EWoNWkVEI_:brareej) ([raw file](https://github.com/vmware/container-service-extension/blob/e5416c09425ee582342966fe91524508a0257615/container_service_extension/rde/backend/cluster_service_2_x.py#L485)):*
> ```Python
>         self.context.is_async = True
>         self._delete_cluster_async(cluster_name=cluster_name,
>                                    org_name=org_name, ovdc_name=ovdc_name)
> ```

nit: I think it's cleaner to give each parameter a line

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 330 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2iwiH9YbuU9rTGvVR:-M_2iwiH9YbuU9rTGvVS:b-8tocqw) ([raw file](https://github.com/vmware/container-service-extension/blob/e5416c09425ee582342966fe91524508a0257615/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L330)):*
> ```Python
>             if input_native_entity.spec.settings.rollback_on_failure:
>                 # delete defined entity
>                 self.sysadmin_entity_svc.delete_entity(entity_id)
> ```

Do we need to have **self.sysadmin_entity_svc.delete_entity(entity_id)**  in try .. catch ? Just thought. If this operation is not error prone then we may not need

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)* status: all files reviewed, 8 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 330 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2iwiH9YbuU9rTGvVR:-M_3-CGG0sxN7m4BAtlX:bw0zlys) ([raw file](https://github.com/vmware/container-service-extension/blob/e5416c09425ee582342966fe91524508a0257615/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L330)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Do we need to have **self.sysadmin_entity_svc.delete_entity(entity_id)**  in try .. catch ? Just thought. If this operation is not error prone then we may not need
</blockquote></details>

Will the deletion go through if the RDE is not in RESOLVED state? Please check.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 323 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2t8hO4irAb5l5zmBL:-M_2t8hO4irAb5l5zmBM:b5z66pr) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L323)):*
> ```Python
>             #   else entity delete will fail.
>             msg = f"Failed to create cluster {cluster_name} in org {org_name} and VDC {ovdc_name}"  # noqa: E501
>             self._update_task(BehaviorTaskStatus.ERROR,
> ```

This step of updating the task may not be required (but I see no harm in this). Raising the exception is good enough. behavior_dispatcher.py will publish the error message.

See if this is resulting in publishing the error twice and if it is causing any issues. 
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 332 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2yXFkC0bXmXxWHYs8:-M_2yXFkC0bXmXxWHYs9:b17nupl) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L332)):*
> ```Python
>             if input_native_entity.spec.settings.rollback_on_failure:
>                 # delete defined entity
>                 self.sysadmin_entity_svc.delete_entity(entity_id)
> ```

Please add 'invokeHooks=False' argument- makes it more explicit.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1010 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_3-64UChmUzSq0rjvo:-M_3-64UChmUzSq0rjvp:baipqqt) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1010)):*
> ```Python
> 
>                 try:
>                     self.entity_svc.resolve_entity(cluster_id)
> ```

There are few resolve calls in here. Please delete them if not needed.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1350 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2uN0h9E-1xWmNFj-d:-M_2uN0h9E-1xWmNFj-e:bvf9tqi) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1350)):*
> ```Python
>     @thread_utils.run_async
>     def _delete_cluster_async(self, cluster_name: str, org_name: str,
>                               ovdc_name: str, curr_entity: common_models.DefEntity):  # noqa: E501
> ```

curr_entity -> curr_rde
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1365 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2u36yB67_8dda1-Ra:-M_2u36yB67_8dda1-Rb:b-tjg5sb) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1365)):*
> ```Python
>             client_v36 = self.context.get_client(
>                 api_version=DEFAULT_API_VERSION)
>             if curr_entity.externalId:
> ```

Can you log a info message on the else condition that vapp is not present?
___
*[container_service_extension/rde/models/common_models.py, line 335 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2v2yN1nafnrM1YU21:-M_2v2yN1nafnrM1YU22:b-vshq1t) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/models/common_models.py#L335)):*
> ```Python
>                                                 # TODO Uncomment this portion when the behavior integration is complete.  # noqa: E501
>                                                 #  Uncommenting below, today (Apr 16,2021), will break the existing native api endpoints.  # noqa: E501
>                                                 hooks={
> ```

Please leave this commented until we redirect native api handlers to behavior logic.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 485 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2_foACrLl8hQr0NKB:-M_3OdYV1UKIe1rtCTB_:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/e5416c09425ee582342966fe91524508a0257615/container_service_extension/rde/backend/cluster_service_2_x.py#L485)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

nit: I think it's cleaner to give each parameter a line
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 330 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2iwiH9YbuU9rTGvVR:-M_3QxzdCBYXj2mwklav:b-gnc9vb) ([raw file](https://github.com/vmware/container-service-extension/blob/e5416c09425ee582342966fe91524508a0257615/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L330)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Will the deletion go through if the RDE is not in RESOLVED state? Please check.
</blockquote></details>

Delete will go through even if the RDE is not RESOLVED if `invokeHooks=false` is set.

Added try-catch block as Sakthi pointed out.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 323 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2t8hO4irAb5l5zmBL:-M_3QO9_8nQsGYPKpmfu:b-lw0lhx) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L323)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This step of updating the task may not be required (but I see no harm in this). Raising the exception is good enough. behavior_dispatcher.py will publish the error message.

See if this is resulting in publishing the error twice and if it is causing any issues. 
</blockquote></details>

Update_task is necessary here because if task is still running, defined entity framework will throw an error if delete entity is attempted.
I removed the `raise` statement to prevent publishing error message twice (Although I didn't see any error from VCD even when the raise statement was there).
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 332 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2yXFkC0bXmXxWHYs8:-M_3REqLCeDFvzeGeJHK:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L332)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add 'invokeHooks=False' argument- makes it more explicit.
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1010 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_3-64UChmUzSq0rjvo:-M_3RnX0BEAlfdbAVQkK:bs4jqs8) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1010)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

There are few resolve calls in here. Please delete them if not needed.
</blockquote></details>

Deleted all resolve calls.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1350 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2uN0h9E-1xWmNFj-d:-M_3S5gE7KEjimZqQSsA:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1350)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

curr_entity -> curr_rde
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 1365 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2u36yB67_8dda1-Ra:-M_3SgplDlIeJHg3uPhd:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L1365)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Can you log a info message on the else condition that vapp is not present?
</blockquote></details>

Done.
___
*[container_service_extension/rde/models/common_models.py, line 335 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2v2yN1nafnrM1YU21:-M_3SpsP3B1-yIUB4yBh:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/models/common_models.py#L335)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please leave this commented until we redirect native api handlers to behavior logic.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027#-:-M_6q08b8QDHIL-Y2OlC:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 323 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2t8hO4irAb5l5zmBL:-M_6ovju96XVDH1RRGC7:b-qx24eu) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L323)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Update_task is necessary here because if task is still running, defined entity framework will throw an error if delete entity is attempted.
I removed the `raise` statement to prevent publishing error message twice (Although I didn't see any error from VCD even when the raise statement was there).
</blockquote></details>

I suggest keep the raise as well, if VCD is not complaining.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1027)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @sahithi and @sakthisunda)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 323 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1027#-M_2t8hO4irAb5l5zmBL:-M_71k8_9h6B5avaJe96:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/326493303031c7c3e680e50281456f9fd5eb737e/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L323)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I suggest keep the raise as well, if VCD is not complaining. 
</blockquote></details>

Done.

**Pull request merged**
