### PR TITLE
[VCDA-2595] Fixed python key error on missing config legacy_mode

### PR DESCRIPTION
**Pull request by sakthisunda**
- CSE server commands on missing config legacy_mode raise key error. This is fixed to display the right error message as before.
- Validation of broker section uses 'legacy_mode' key and it happens before validating service section. 
   By doing service section validation first, we avoid this KeyError.
- Tested and verified

image

@sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077#-:-MckOSgn8ADk33UY5u97:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-Mcmg_TT1VSkdwmxYXca:b10y3o2) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
> ```Python
>                                msg_update_callback=msg_update_callback)
> 
>     _validate_broker_config(config['broker'],
> ```

Sorry, but I don't understand how moving the code block around fixes anything?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-McoCe254tr_qtJcoYk5:b-5uiya6) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Sorry, but I don't understand how moving the code block around fixes anything?
</blockquote></details>

I think `legacy_mode` key is accessed (in the function call itself) before key value types are validated by `check_keys_and_value_types()` which will create a keyError. Is that right @sakthisunda ?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-McoCK_X-Hjz7Z1M3UA1:b-xhl2ik) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think `legacy_mode` key is accessed (in the function call itself) before key value types are validated by `check_keys_and_value_types()` which will create a keyError. Is that right @sakthisunda ?
</blockquote></details>

yes. Validation of broker section uses 'legacy_mode' key and it happens before validating service section. By doing service section validation first, we avoid this KeyError.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-McoEIYIE_63HMiaTwib:b37uime) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
> updated the fix description with the above information.

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077#-:-Mcp0Ekq5GvUrBxIpD9Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-Mcp083p8muLF6t2HCzD:b4s14nd) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> updated the fix description with the above information.
</blockquote></details>

Makes sense, thanks. Please add a comment in the code explaining why the order of checks is important.

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @sakthisunda)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1077)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/installer/config_validator.py, line 167 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1077#-Mcmg_TT1VSkdwmxYXc_:-McpHtZ6EJknMygDG5EM:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c0e9c067b76b4b2860ef83309727129c98cb8036/container_service_extension/installer/config_validator.py#L167)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Makes sense, thanks. Please add a comment in the code explaining why the order of checks is important.
</blockquote></details>

Done.

**Pull request merged**
