### PR TITLE
[VCDA-2055] Implement behavior processor

### PR DESCRIPTION
**Pull request by sahithi**
- Added a new thread pool executor for behaviors (as they are synchronous long-running tasks).
- Implemented behavior request processor and created the required helper constructs
- Create a placeholder for behavior handler

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: just some clarifications

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950#-:-MVNZ--D2AFv7NU9c5uB:bwvvrti)* status: all files reviewed, 3 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/server/behavior_dispatcher.py, line 35 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNUhxyBgG7q7CRdl3U:-MVNUhxyBgG7q7CRdl3V:btnk83r) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L35)):*
> ```Python
>     entity: dict = payload['entity']
>     entity_type_id: str = payload['typeId']
>     api_version: str = payload['_metadata']['apiVersion']
> ```

Is this VCD API version?
___
*[container_service_extension/server/behavior_dispatcher.py, line 38 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNUpHDANQXQVjoHcWh:-MVNUpHDANQXQVjoHcWi:b-v66d89) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L38)):*
> ```Python
>     auth_token: str = payload['_metadata']['actAsToken']
>     # TODO requestId is yet to be submitted by Extensibility.
>     request_id: str = payload['_metadata'].get('requestId', None)
> ```

`None` is not necessary in this statement
___
*[container_service_extension/server/behavior_handler.py, line 23 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNYZdY6xnCoJmbTVla:-MVNYZdY6xnCoJmbTVlb:bk2bio6) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_handler.py#L23)):*
> ```Python
>     # entity = behavior_ctx.entity
>     # api_version = behavior_ctx.api_version
>     # TODO Get validator based on (api_version, payload_version) and validate the entity.  # noqa: E501
> ```

What will be the value for `payload_version`? Is it same as RDE version?

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950)* status: all files reviewed, 6 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 148 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNe3Vl2W9e71BkE5OE:-MVNe3Vl2W9e71BkE5OF:bad3g7c) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/mqi/consumer/mqtt_consumer.py#L148)):*
> ```
> = 'BEHAVIOR_INVOCATION':
> ```
Is this constant set by the framework? How do we get to know this type?
___
*[container_service_extension/rde/behaviors/behavior_model.py, line 116 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNebxh10FaATuKLCIK:-MVNebxh10FaATuKLCIL:b7mj4rk) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/rde/behaviors/behavior_model.py#L116)):*
> ```Python
> 
> @dataclass
> class BehaviorErrorPayload:
> ```

Is this a response payload?
___
*[container_service_extension/server/behavior_dispatcher.py, line 55 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNei5yAlEO81DUPE1Y:-MVNei5yAlEO81DUPE1Z:b-uu1nfl) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L55)):*
> ```Python
>     # Invoke the handler method.
>     return_payload = MAP_BEHAVIOR_ID_TO_HANDLER_METHOD[behavior_id](behavior_ctx)  # noqa: E501
>     if isinstance(return_payload, BehaviorErrorPayload):
> ```

return_payload  ==> Is this a response payload ?

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/mqi/consumer/mqtt_consumer.py, line 148 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNe3Vl2W9e71BkE5OE:-MVODkR18cJUq-oFUSUX:b-p462y9) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/mqi/consumer/mqtt_consumer.py#L148)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> = 'BEHAVIOR_INVOCATION':
> ```
Is this constant set by the framework? How do we get to know this type?
</blockquote></details>

Yes, this value is defined by Defined Entity framework
___
*[container_service_extension/rde/behaviors/behavior_model.py, line 116 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNebxh10FaATuKLCIK:-MVODpb9AiVXL_Dsein6:b-l0dwhh) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/rde/behaviors/behavior_model.py#L116)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is this a response payload?
</blockquote></details>

This is Error payload.

Behavior response can be either string or dict.
In the case of error, we are supposed to send the above exact format.
___
*[container_service_extension/server/behavior_dispatcher.py, line 35 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNUhxyBgG7q7CRdl3U:-MVOEFCyCFVPNygQfiWp:b2nhswy) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L35)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Is this VCD API version?
</blockquote></details>

Yes
___
*[container_service_extension/server/behavior_dispatcher.py, line 38 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNUpHDANQXQVjoHcWh:-MVOEGnNEpOq7nCSjWT2:bftd8az) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L38)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`None` is not necessary in this statement
</blockquote></details>

_requestId_ is not present as part of the request payload. It will throw a key error for the current VCD builds. The extensibility team will soon include requestId.
___
*[container_service_extension/server/behavior_dispatcher.py, line 55 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNei5yAlEO81DUPE1Y:-MVOE_z06cMt7gL6GDke:b-bl2br5) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_dispatcher.py#L55)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

return_payload  ==> Is this a response payload ?
</blockquote></details>

Renamed it to response_payload
___
*[container_service_extension/server/behavior_handler.py, line 23 at r1](https://reviewable.io/reviews/vmware/container-service-extension/950#-MVNYZdY6xnCoJmbTVla:-MVOEhlv-xZA2o-3DFwG:bkcmfc6) ([raw file](https://github.com/vmware/container-service-extension/blob/c7e9fe515572fcb8fc7e44e25e0886ab949e045c/container_service_extension/server/behavior_handler.py#L23)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

What will be the value for `payload_version`? Is it same as RDE version?
</blockquote></details>

Yet to be decided. I will set up a meeting to finalize this.

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/950#-:-MVOIThW6_IC50Kgnsgx:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Pull request merged**
