### PR TITLE
[VCDA-2387] helper method, wait for customization phase to reach desired status

### PR DESCRIPTION
**Pull request by sakthisunda**
-  Util method to support waiting for post customization phase
-  Waits for a given post customization check on a given VM config option until the customization reaches the final status of a given sequence of statuses, timeout on given time in seconds, raises exceptions for invalid status and timeout
- manually tested with a VM setting. TBD: more tests on a valid testbed
@rocknes @Anirudh9794 @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)

### CODE REVIEW

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 678 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-McoZJng0Z5VP83s1o-x:-McoZJnh1qzTk4QejdpV:b4kqbg) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L678)):*
> ```Python
>             remaining_statuses.remove(current_status)
>         # Check for successful customization: reached last status
>         if new_status == expected_target_statuses[-1]:
> ```

what if this list is empty?

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 650 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-McolA2nCJhkAQn-pz0n:-McolA2nCJhkAQn-pz0o:b-gvqsvf) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L650)):*
> ```Python
>         timeout=server_constants.DEFAULT_POST_CUSTOMIZATION_TIMEOUT_SEC,
>         poll_frequency=server_constants.DEFAULT_POST_CUSTOMIZATION_POLL_SEC,
>         expected_target_statuses=server_constants.DEFAULT_POST_CUSTOMIZATION_STATUSES):  # noqa: E501
> ```

Since we return `new_status`, we should probably have a `->` with the right type here.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 668 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-Mcos-MZBJC0d3jGknF7:-McolX6OB7AwgficsT8L:b-vn9weh) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L668)):*
> ```Python
>     """
>     start_time = datetime.now()
>     current_status = expected_target_statuses[0]
> ```

I think we should keep `current_status` as None in the beginning. Or is there a specific contract that when we get into this function, `current_status` is the first entry in the list? If so, could you please add a comment mentioning that..
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 676 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-McokTseCgwsJfoQVjPQ:-McokTseCgwsJfoQVjPR:b-iurgfd) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L676)):*
> ```Python
>         # update the remaining statuses on status change
>         if new_status != current_status:
>             remaining_statuses.remove(current_status)
> ```

I think here we should set:
```
current_status = new_status
```

**Review by arunmk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 680 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-McosmfF5v-vXd35fBDX:-McosmfF5v-vXd35fBDY:bnel5k5) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L680)):*
> ```Python
>         if new_status == expected_target_statuses[-1]:
>             return new_status
>         if datetime.now() - start_time > timedelta(seconds=timeout):
> ```

Maybe we should check script execution status before here. Else, the script will always timeout in case of error as well.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068#-:-McruH_V8yo9u4M5TE5A:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @arunmk and @sakthisunda)

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: all files reviewed, 8 unresolved discussions (waiting on @arunmk and @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 720 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJ5yioAtYgaJYwDqYq:-MdJ5yioAtYgaJYwDqYr:b-x33wo4) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/constants/server_constants.py#L720)):*
> ```Python
> 
> POST_CUSTOMIZATION_SCRIPT_EXECUTION_STATUS = 'post_customization_script_execution_status'  # noqa: E501
> DEFAULT_POST_CUSTOMIZATION_STATUSES = [cust_status.value for cust_status in PostCustomizationStatus]  # noqa: E501
> ```

nit: DEFAULT_POST_CUSTOMIZATION_STATUS_VALUES (or) DEFAULT_POST_CUSTOMIZATION_STATUS_LIST
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 650 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJ6G4o35FfY3vuQx8i:-MdJ6G4o35FfY3vuQx8j:b-1hj00t) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L650)):*
> ```Python
>         timeout=server_constants.DEFAULT_POST_CUSTOMIZATION_TIMEOUT_SEC,
>         poll_frequency=server_constants.DEFAULT_POST_CUSTOMIZATION_POLL_SEC,
>         expected_target_statuses=server_constants.DEFAULT_POST_CUSTOMIZATION_STATUSES) -> str:  # noqa: E501
> ```

expected_target_status_values
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 683 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJFKdZ9LRg-QK5qHUz:-MdJFKdZ9LRg-QK5qHV-:b9tr8sv) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L683)):*
> ```Python
>     while True:
>         new_status = get_vm_extra_config_element(vm, customization_phase)
>         if new_status not in remaining_statuses:
> ```

Please log all the exceptions.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 696 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJFtczBEXaREq6QbdE:-MdJFtczBEXaREq6QbdF:b1e7deh) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L696)):*
> ```Python
>         script_execution_status = get_vm_extra_config_element(vm, server_constants.POST_CUSTOMIZATION_SCRIPT_EXECUTION_STATUS)  # noqa: E501
>         if script_execution_status and int(script_execution_status) != 0:
>             raise exceptions.ScriptExecutionError
> ```

By the way, how are we retrieving the script error details from the VM? Is that not being stored in the VM config - something like "error_list"?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @arunmk, @rocknes, and @sahithi)

___
*[container_service_extension/common/constants/server_constants.py, line 720 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJ5yioAtYgaJYwDqYq:-MdJdzYzDqKdhZsaoJEe:b-r7tvaz) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/constants/server_constants.py#L720)):*
> DEFAULT_POST_CUSTOMIZATION_STATUS_LIST
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 650 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1068#-McolA2nCJhkAQn-pz0n:-MdJeEOEB-M2d-nP_Eng:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7bf37a9201b194f8d19b7d71e2b30dd2734d1efb/container_service_extension/common/utils/pyvcloud_utils.py#L650)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Since we return `new_status`, we should probably have a `->` with the right type here.
</blockquote></details>

Done.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 650 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJ6G4o35FfY3vuQx8i:-MdJe6aDBqfKPm4XokP7:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L650)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

expected_target_status_values
</blockquote></details>

Done.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 683 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJFKdZ9LRg-QK5qHUz:-MdJePVEAEK18PuSNOUE:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L683)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please log all the exceptions.
</blockquote></details>

Done.
___
*[container_service_extension/common/utils/pyvcloud_utils.py, line 696 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1068#-MdJFtczBEXaREq6QbdE:-MdJeRcwEEx7-5-haute:b3ftcf6) ([raw file](https://github.com/vmware/container-service-extension/blob/9381c924eb7dfb8837c610c8dc599b7d031df0be/container_service_extension/common/utils/pyvcloud_utils.py#L696)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

By the way, how are we retrieving the script error details from the VM? Is that not being stored in the VM config - something like "error_list"?
</blockquote></details>

New VM config introduced for failure reason that will be set by Customization script on any failure.

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1068)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @rocknes and @sahithi)

**Pull request merged**
