### PR TITLE
[VCDA-2057] Register, override, set acls on behaviors during CSE installation.

### PR DESCRIPTION
**Pull request by sahithi**
- Refactored rde/constants.py and rde/models/common_models.py to incorporate behaviors and facilitate dynamic installation of all RDE constructs for any RDE version of the schema.
- Modified CSE install command to perform below operations in addition to registration of native entity type.
1. Register a new CSE interface
2. Create behaviors on the CSE interface - createCluster, updateCluster, deleteCluster.
3. Override Kubeconfig behavior of VCD interface on the NativeEntityType2.0
4. Set ACLS on all of the behaviors for users to invoke.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/933)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/933)* status: 10 of 11 files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 848 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUopmif0f8Sn0W_ChkB:-MUopmif0f8Sn0W_ChkC:b-tc80i0) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L848)):*
> ```Python
> def _set_acls_on_behaviors(cloudapi_client,
>                            map_entitytypeid_to_behavior_acls: dict[str, List[BehaviorAclEntry]],  # noqa: E501
>                            msg_update_callback):
> ```

```
msg_update_callback
```
can use a default value NullPrinter()
___
*[container_service_extension/installer/configure_cse.py, line 852 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUopOD2-U5D8v6Co5tW:-MUopOD2-U5D8v6Co5tX:b8zop8x) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L852)):*
> ```Python
>     msg = ""
>     for entity_type_id, behavior_acls in map_entitytypeid_to_behavior_acls.items():  # noqa: E501
>         msg += f"Setting ACLs on behaviors of the entity type '{entity_type_id}'"  # noqa: E501
> ```

Just wondering if it is better to print the message instead of  appending the messages. In case of failure, it will be easier to figure out which entry caused the failure.
___
*[container_service_extension/installer/configure_cse.py, line 860 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoq1-e52ZQMJgpjgfK:-MUoq1-e52ZQMJgpjgfL:b-tc80i0) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L860)):*
> ```Python
> def _override_behaviors(cloudapi_client,
>                         map_interfaceid_to_behaviors: dict[str, List[Behavior]],  # noqa: E501
>                         msg_update_callback):
> ```

```
msg_update_callback
```
can use a default value NullPrinter()
___
*[container_service_extension/rde/constants.py, line 71 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoixtP37kg-NTVlQqi:-MUoixtQ6qRe4lQqAbJJ:b-7623yu) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/constants.py#L71)):*
> ```Python
>     ENTITY_TYPE = 'entity_type'
>     INTERFACES = 'interfaces'
>     MAP_INTERFACE_TO_BEHAVIORS = 'map_from_interface_id_to_behaviors'
> ```

`MAP_*` for some reason doesn't strike to me as a Key.
`*_MAP` sounds somewhat better to me.
___
*[container_service_extension/rde/utils.py, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUouwTC070ax1xukJiO:-MUouwTC070ax1xukJiP:b-lni2og) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/utils.py#L131)):*
> ```
> load_rde_schema
> ```
can we make use of `read_data_file` in `core_utils.py` ? Or we can move this method to core_utils to avoid cyclic dependency issues.
___
*[container_service_extension/rde/models/common_models.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUovoa11RKlRDoVOme8:-MUovoa11RKlRDoVOme9:b-xv347t) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/models/common_models.py#L318)):*
> ```Python
>                  BehaviorOperation.DELETE_CLUSTER.value]
>         },
>         RDEMetadataKey.MAP_INTERFACE_TO_OVERRIDE_BEHAVIORS: {
> ```

ENTITY_TYPE_TO_BEHAVIORS_MAP ?.
Do we have to specify the term "OVERRIDE"? because it should be implicit. Also, we are making use of a function `_override_behaviors`, which should make it clear that we are overriding behaviors.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/de_cluster_tkg.py, line 109 at r2](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoyKEG3s-Id1KBqW4_:-MUoyKEG3s-Id1KBqW4a:b-w4soca) ([raw file](https://github.com/vmware/container-service-extension/blob/ab4df2bfa977c70fc39c12fc28dee00f3fc45a3f/container_service_extension/client/de_cluster_tkg.py#L109)):*
> ```Python
>             (entities, status, headers, additional_details) = \
>                 self._tkg_client_api.list_tkg_clusters(
>                     common_models.EntityType.TKG_ENTITY_TYPE_1_0_0.value.id,
> ```

This should not be an ID. it should be of the format `vendor/nss/version`

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/de_cluster_tkg.py, line 145 at r2](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoyW5S-JALLW9wV5my:-MUoyW5S-JALLW9wV5mz:b-9qe6hm) ([raw file](https://github.com/vmware/container-service-extension/blob/ab4df2bfa977c70fc39c12fc28dee00f3fc45a3f/container_service_extension/client/de_cluster_tkg.py#L145)):*
> ```Python
>         response = \
>             self._tkg_client_api.list_tkg_clusters(
>                 common_models.EntityType.TKG_ENTITY_TYPE_1_0_0.value.id,
> ```

This should not be an ID. It should be of the format `vendor/nss/version`

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/933)* status: 7 of 11 files reviewed, 8 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster_tkg.py, line 109 at r2](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoyKEG3s-Id1KBqW4_:-MUpWX81CUes_wD_5Shv:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ab4df2bfa977c70fc39c12fc28dee00f3fc45a3f/container_service_extension/client/de_cluster_tkg.py#L109)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This should not be an ID. it should be of the format `vendor/nss/version`
</blockquote></details>

Done.
___
*[container_service_extension/client/de_cluster_tkg.py, line 145 at r2](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoyW5S-JALLW9wV5my:-MUpWW_-A6cKpnlmH28Z:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/ab4df2bfa977c70fc39c12fc28dee00f3fc45a3f/container_service_extension/client/de_cluster_tkg.py#L145)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

This should not be an ID. It should be of the format `vendor/nss/version`
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 848 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUopmif0f8Sn0W_ChkB:-MUpWV9D3g6K8Dv19zkk:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L848)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

```
msg_update_callback
```
can use a default value NullPrinter()
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 852 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUopOD2-U5D8v6Co5tW:-MUpWUbK9BL8qWl_jid4:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L852)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Just wondering if it is better to print the message instead of  appending the messages. In case of failure, it will be easier to figure out which entry caused the failure.
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 860 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoq1-e52ZQMJgpjgfK:-MUpWUAhAkWykbXh4Bkf:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/installer/configure_cse.py#L860)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

```
msg_update_callback
```
can use a default value NullPrinter()
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 71 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUoixtP37kg-NTVlQqi:-MUpWSbNByltJiIT_JLR:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/constants.py#L71)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

`MAP_*` for some reason doesn't strike to me as a Key.
`*_MAP` sounds somewhat better to me.

</blockquote></details>

Done.
___
*[container_service_extension/rde/utils.py, line 131 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUouwTC070ax1xukJiO:-MUpT43j1Qo4rddWLGsl:b-qdzc8x) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/utils.py#L131)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

> ```
> load_rde_schema
> ```
can we make use of `read_data_file` in `core_utils.py` ? Or we can move this method to core_utils to avoid cyclic dependency issues.
</blockquote></details>

I would like to keep it under rde package for now. We may add more rde-specific logic around this method once "selective user access" comes in from the Extensibility team. 
For example, to identify the sections that would require escalated privileges (or) cse service account. We can defer this to later.

There is no cyclic dependency as of now.
___
*[container_service_extension/rde/models/common_models.py, line 318 at r1](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUovoa11RKlRDoVOme8:-MUpUGjP-hgR7qrPw90s:b-glt6hj) ([raw file](https://github.com/vmware/container-service-extension/blob/6fe47a9f953ad028202e6db6b19c68ac457f8fd3/container_service_extension/rde/models/common_models.py#L318)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

ENTITY_TYPE_TO_BEHAVIORS_MAP ?.
Do we have to specify the term "OVERRIDE"? because it should be implicit. Also, we are making use of a function `_override_behaviors`, which should make it clear that we are overriding behaviors.
</blockquote></details>

Renamed to ENTITY_TYPE_TO_OVERRIDABLE_BEHAVIORS_MAP , thanks.

I think it adds more clarity. For developers editing this map two release down the line, it should be obvious for them to identify the section to be edited in order to "add a new list of behaviors to be overridden". They may or may not be aware of _override_behaviors sitting in configure_cse.py.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: (minor comment)

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/933#-:-MUpZODJ2MtW8xwVsS05:b-3xlrhu)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 852 at r3](https://reviewable.io/reviews/vmware/container-service-extension/933#-MUpYSfrCXkTm_RuRYHu:-MUpYSfrCXkTm_RuRYHv:b-5x1j73) ([raw file](https://github.com/vmware/container-service-extension/blob/e78c76642ce16a96af45e351d60dabc989f6a17e/container_service_extension/installer/configure_cse.py#L852)):*
> ```Python
>     msg = ""
>     for entity_type_id, behavior_acls in map_entitytypeid_to_behavior_acls.items():  # noqa: E501
>         msg += f"Setting ACLs on behaviors of the entity type '{entity_type_id}'"  # noqa: E501
> ```

 This function is still using the append and print style of logging messages.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/933)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Pull request merged**
