### PR TITLE
[VCDA-3237] Using TKR bom for antrea version

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
- Using TKR bom to get antrea version for R1 TKGm clusters
- R1 RDE should only specify "antrea" as the cni and not the version since we do not currently support the vm to update the cni version

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested with 1.3.0 (no antrea in bom), 1.4.0 (antrea 0.11.3 in bom ), and 1.4.1 (antrea 0.13.3 in bom) ovas
Verified RDE only shows "antrea"

- (Optional) Names of reviewers using @ sign + name
- @Anirudh9794 @arunmk @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:  just a minor question

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308#-:-Mw38FQo1OGR7GqIbfGH:b-j5j8od)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 170 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw37bjV3ZCxiQv3Q-ju:-Mw37bjV3ZCxiQv3Q-jv:bur1mz1) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L170)):*
> ```YAML
>       xml_version_property=$(vmtoolsd --cmd "info-get guestinfo.ovfenv" | grep "oe:key=\"VERSION\"")
>       init_k8s_version=$(echo $xml_version_property | sed 's/.*oe:value=\"//; s/\(.*\)-.*/\1/')
>       k8s_version=$(echo $OPEN_BRACKETinit_k8s_versionCLOSE_BRACKET | tr -s "+" "_")
> ```

doesn't `$(echo $init_k8s_version | ... )` work here?

**Review by arunmk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 170 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3hlJ7ArG9KxUMTNNF:-Mw3hlJ7ArG9KxUMTNNG:b3h4g90) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L170)):*
> ```YAML
>       xml_version_property=$(vmtoolsd --cmd "info-get guestinfo.ovfenv" | grep "oe:key=\"VERSION\"")
>       init_k8s_version=$(echo $xml_version_property | sed 's/.*oe:value=\"//; s/\(.*\)-.*/\1/')
>       k8s_version=$(echo $OPEN_BRACKETinit_k8s_versionCLOSE_BRACKET | tr -s "+" "_")
> ```

We can just call this `k8s_version_clean` and that will remove the OPEN_BRACKET and CLOSE_BRACKET requirement, correct?
___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 206 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3iPZO5AWCWViN1G9q:-Mw3iPZO5AWCWViN1G9r:byt6w45) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L206)):*
> ```YAML
>           echo "no antrea version found in tkr bom, will use default antrea version: $OPEN_BRACKETdefault_antrea_versionCLOSE_BRACKET" &>> /var/log/cse/customization/status.log
>         else
>           antrea_version=$(echo $OPEN_BRACKETantrea_versionCLOSE_BRACKET | sed "s/v//") # remove leading `v`, which will be added later
> ```

same here with `antrea_version_clean`

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 162 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3ibrUA4rRNuG74I47:-Mw3ibrUA4rRNuG74I48:b-ajliev) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L162)):*
> ```YAML
>       mkdir $tkr_bom_dir
>       bom_path=$tkr_bom_dir/bom
>       mkdir $bom_path
> ```

<s>mkdir $tkr_bom_dir</s>
bom_path=$tkr_bom_dir/bom
mkdir -p $bom_path



_Code quote:_
```YAML
      mkdir $tkr_bom_dir
      bom_path=$tkr_bom_dir/bom
      mkdir $bom_path
```
___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 201 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3m7TY6UBl_iD9rOkG:-Mw3m7TY6UBl_iD9rOkH:b31gxq7) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L201)):*
> ```YAML
>         wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O $yq_path
>         chmod +x $yq_path
>         antrea_version=$($yq_path e ".components.antrea[0].version" $components_path | sed 's/+.*//')
> ```

not aware of what does <b>e</b> below do? 



_Code quote:_
```YAML
$yq_path e
```

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 201 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3m7TY6UBl_iD9rOkG:-Mw3nzvX194yrVymdgjS:bx9kqim) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L201)):*
<details><summary><i>Previously, sakthisunda (Sakthi Sundaram) wrote…</i></summary><blockquote>

not aware of what does <b>e</b> below do? 
</blockquote></details>

This is shorthand for evaluate

**Review by sakthisunda — APPROVED** [review]
:lgtm: (After review comments)

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1308#-:-Mw43JsoChkRKJhuucJk:b-3z7gie)* status: all files reviewed, 5 unresolved discussions (waiting on @ltimothy7)

___
*[cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml, line 201 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1308#-Mw3m7TY6UBl_iD9rOkG:-Mw42kKDD4osb2xomSIz:b-k73z76) ([raw file](https://github.com/vmware/container-service-extension/blob/9baf9fe59ef370b2a1b945c50dd86d2b74adf943/cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml#L201)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

This is shorthand for evaluate
</blockquote></details>

thanks

**Pull request merged**
