### PR TITLE
[VCDA 2082] Fix cluster upgrade with nfs node 

### PR DESCRIPTION
**Pull request by sakthisunda**
-  Exclude NFS node from upgrading k8 cluster nodes
------------------
cluster_info_after_upgrade
successful_upgrade
upgrade_log

@andrew-ni @Anirudh9794 @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/894)

### CODE REVIEW

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/894#-:-MS5urie5IG1p2MaaOou:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by rocknes — APPROVED** [review]
Please don't forget to port this to cse_3_0_updates

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/894#-:-MS5uwT25CyV898tSPuP:b-p4gnxm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/894#-:-MS95mFI5A2jsCSSFf9s:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/894#-:-MS9FxPR7id3xN7yA6AS:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
