### PR TITLE
[Vcda 2462] Add behavior and handler for nfs node delete

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

Testing done:
- invoke behavior using `POST https://{{VCD_IP}}/cloudapi/1.0.0/entities/{{CLUSTER_ID}}/behaviors/urn:vcloud:behavior-interface:deleteNfsNode:cse:k8s:1.0.0/invocations` for valid nfs node name and invalid nfs node name

@sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037)* status: all files reviewed, 4 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 798 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0ltBy-iDRqK1cIgoN:-Ma0ltBy-iDRqK1cIgoO:b-cv51l9) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L798)):*
> ```Python
>         self._monitor_delete_nodes(cluster_id=cluster_id,
>                                    nodes_to_del=nodes_to_del)
>         return self.mqtt_publisher.construct_behavior_payload(
> ```

Is this method being used only for NFS node deletion? It looks like a generic method.
I suggest changing the (...message= msg,...) instead of NFS specific message to keep the method generic.
___
*[container_service_extension/server/behavior_dispatcher.py, line 47 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0pLJ_2OXv3OLuFQrm:-Ma0pLJ_2OXv3OLuFQrn:b-ya60qr) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/behavior_dispatcher.py#L47)):*
> ```Python
>     # Initializing Behavior operation context
>     op_ctx = OperationContext(auth_token=auth_token, is_jwt=True, request_id=request_id)  # noqa: E501
>     behavior_ctx = RequestContext(behavior_id=behavior_id,
> ```

You can add the __arguments__ to the RequestContext alongside other details like payload, entity_id, task_id, behavior_id etc.
___
*[container_service_extension/server/behavior_handler.py, line 56 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0pXTK5UY-V3ItgdXm:-Ma0pXTK5UY-V3ItgdXn:b-uxpyh3) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/behavior_handler.py#L56)):*
> ```Python
> 
> @exception_handler
> def create_cluster(behavior_ctx: RequestContext, **kwargs):
> ```

**kwargs can be removed and arguments can be part of behavior_ctx.
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 286 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0q1Xb38JmK-yGlORC:-Ma0q1Xb38JmK-yGlORD:byx7s20) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/request_handlers/cluster_handler.py#L286)):*
> ```Python
>     cluster_def_entity.entity.status.task_href = delete_nfs_node_task
> 
>     # TODO: How to get to know what format of output the caller is expecting?
> ```

What were we sending out for delete NFS node operation in the last release? We should continue to send that.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037)* status: 6 of 10 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 798 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0ltBy-iDRqK1cIgoN:-Ma5jDRXAeoqmF9NPg7O:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L798)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is this method being used only for NFS node deletion? It looks like a generic method.
I suggest changing the (...message= msg,...) instead of NFS specific message to keep the method generic.
</blockquote></details>

Done.
___
*[container_service_extension/server/behavior_dispatcher.py, line 47 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0pLJ_2OXv3OLuFQrm:-Ma5jgw23hjj1RpI830M:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/behavior_dispatcher.py#L47)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You can add the __arguments__ to the RequestContext alongside other details like payload, entity_id, task_id, behavior_id etc.
</blockquote></details>

Done.
___
*[container_service_extension/server/behavior_handler.py, line 56 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0pXTK5UY-V3ItgdXm:-Ma5pB8oBR-OZowFbPBy:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/behavior_handler.py#L56)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

**kwargs can be removed and arguments can be part of behavior_ctx.
</blockquote></details>

Done.

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037)* status: 6 of 10 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 797 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma5v6QjA8NA9Xae6hir:-Ma5v6QjA8NA9Xae6his:b-unsb0q) ([raw file](https://github.com/vmware/container-service-extension/blob/ea876373cba78c792a65cf027409ec5f9e306abf/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L797)):*
> ```Python
>         self._monitor_delete_nodes(cluster_id=cluster_id,
>                                    nodes_to_del=nodes_to_del)
>         msg = f"Deleting NFS nodes: {nodes_to_del} for cluster {curr_entity.name} ({cluster_id})"  # noqa: E501
> ```

We can remove 'NFS'. That way method and the message would suit for any non-nfs operations.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x_behaviors.py, line 797 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma5v6QjA8NA9Xae6hir:-Ma6_Eog5QW26F7fnBC_:b-f80hr8) ([raw file](https://github.com/vmware/container-service-extension/blob/ea876373cba78c792a65cf027409ec5f9e306abf/container_service_extension/rde/backend/cluster_service_2_x_behaviors.py#L797)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We can remove 'NFS'. That way method and the message would suit for any non-nfs operations.
</blockquote></details>

Actually, `delete_nodes` is currently only called to delete nfs nodes. And it is also only called by the handler function.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 286 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0q1Xb38JmK-yGlORC:-MaB2x2a5aDARRHF_nHa:b-xawqxt) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/request_handlers/cluster_handler.py#L286)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

What were we sending out for delete NFS node operation in the last release? We should continue to send that.
</blockquote></details>

As discussed, made changes so that def_cluster_handler returns 2.0 RDE response

**Review by sahithi — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1037#-:-MaB5j5M1BaktH9hnVhv:bg7igkv)* status: all files reviewed, 6 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 286 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0q1Xb38JmK-yGlORC:-MaB5d3X2JnNj-zmxt3V:boe8fxd) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/request_handlers/cluster_handler.py#L286)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

As discussed, made changes so that def_cluster_handler returns 2.0 RDE response
</blockquote></details>

You mean 1.0?
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 296 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1037#-MaB4kp45b2QiIB-y-AA:-MaB4kp45b2QiIB-y-AB:bsoju11) ([raw file](https://github.com/vmware/container-service-extension/blob/2f1db398a0902d462e773dce771969aa4597bace/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L296)):*
> ```Python
>     rde_in_use = server_utils.get_rde_version_in_use()
>     if semantic_version.Version(rde_in_use) >= semantic_version.Version(rde_constants.RDEVersion.RDE_2_0_0.value):  # noqa: E501
>         # NOTE: cluster_handler is always expected to return RDE version
> ```

sorry I read cluster_handler as v35_handler and got confused. Just add that - hence a conversion to 1.0 is needed.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/v35/def_cluster_handler.py, line 296 at r4](https://reviewable.io/reviews/vmware/container-service-extension/1037#-MaB4kp45b2QiIB-y-AA:-MaBPX3zCQiR8sZyMw9b:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2f1db398a0902d462e773dce771969aa4597bace/container_service_extension/server/request_handlers/v35/def_cluster_handler.py#L296)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

sorry I read cluster_handler as v35_handler and got confused. Just add that - hence a conversion to 1.0 is needed.
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/cluster_handler.py, line 286 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1037#-Ma0q1Xb38JmK-yGlORC:-MaB6Q40AtGLtTsBrkPZ:bw2nb8a) ([raw file](https://github.com/vmware/container-service-extension/blob/af59580958444dc3a142ce8bc752f5acdd70cdd8/container_service_extension/server/request_handlers/cluster_handler.py#L286)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

You mean 1.0?
</blockquote></details>

sorry typo while replying :P . I meant 1.0.

**Pull request merged**
