### PR TITLE
[VCDA-2148] Input validator by RDE version 

### PR DESCRIPTION
**Pull request by sakthisunda**
- Validator implementation by RDE version supported by API handler 
- Cluster spec validation 
- V36 cluster handler changes to use new validator
- Entity service, Cluster service fixes to get entity type 
- Tested on cluster creation and resize
- TODO: upgrade test

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934)

@Anirudh9794 @sahithi @rocknes

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934)* status: all files reviewed, 4 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/rde/validators/validator_factory.py, line 16 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUo_bYb4xu2UoQP6oEc:-MUo_bYb4xu2UoQP6oEd:b-khdiuk) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/rde/validators/validator_factory.py#L16)):*
> ```Python
>     """
>     rde_version: semantic_version.Version = semantic_version.Version(rde_version_supported_api_handler)  # noqa: E501
>     if rde_version.major == 1:
> ```

if rde_version == 1.0.0
if rde_version == 2.0.0

We no longer want to get one validator per major version line. We want to map handlers 1-1 to RDE validators.
35 - 1.0.0
36 - 2.0.0
37 - 2.1.0

With this code, in the next release, 37 also would get 2.0.0
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoZ5Dr4gvB6OiEMeN4:-MUoZ5Dr4gvB6OiEMeN5:bov8u7t) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/rde/validators/validator_rde_2_x.py#L24)):*
> ```Python
>         """
>         if operation == CseOperation.V36_CLUSTER_UPDATE:
>             return rde_utils.validate_cluster_update_request_and_check_cluster_upgrade(request_spec, current_spec)  # noqa: E501
> ```

This helper method can stay right here in this file. If needed, move it to rde/validators/utils.py
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 47 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoZrYMDVcRK1YxTv-2:-MUoZrYMDVcRK1YxTv-3:bvfc5fr) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L47)):*
> ```Python
>         cluster_entity_status, server_utils.get_rde_version_in_use())
> 
>     is_upgrade_operation = rde_validator_factory.get_validator(
> ```

Looks like we are using the return value of the validate method for a different purpose. Validate method doesn't have to determine whether it is an upgrade or resize.

It should be something like this:

rde_validator_factory.get_validator(2.0.0).validate()
svc.update_cluster(spec)

Then in the cluster_svc_2x.py, please add a new method update_cluster()
def update_cluster(spec):
....if change in the worker count:
...............resize_cluster()
....elif change in the template:
...............upgrade_cluster()

We will have to these validators even from behavior handlers and let us have these methods strictly follow their signatures.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoai2r3lMknwl8LyXQ:-MUoai2r3lMknwl8LyXR:b6u6axr) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L48)):*
> ```Python
> 
>     is_upgrade_operation = rde_validator_factory.get_validator(
>         rde_constants.RuntimeRDEVersion.RDE_2_X).validate(
> ```

We cannot use rde_constants.RuntimeRDeVersion.RDE_2_X here. This variable changes for every release.
Please create another constant Enum.

RDEVersion(Enum):
...1_0_0='1.0.0'
...2_0_0='2.0.0'
...2_1_0='2.1.0'

In the next release, assuming RDE version bumps up to 2.1.0, then below is how RuntimeRDEVersion Enum would get updated.
RuntimeRDEVersion(Enum):
..RDE_1_X:'1.0.0'
..RDE_2_X:'2.0.0'

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/rde/validators/validator_factory.py, line 16 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUo_bYb4xu2UoQP6oEc:-MUpsQsaClJuNbMjKEyE:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/rde/validators/validator_factory.py#L16)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

if rde_version == 1.0.0
if rde_version == 2.0.0

We no longer want to get one validator per major version line. We want to map handlers 1-1 to RDE validators.
35 - 1.0.0
36 - 2.0.0
37 - 2.1.0

With this code, in the next release, 37 also would get 2.0.0
</blockquote></details>

Done.
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 24 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoZ5Dr4gvB6OiEMeN4:-MUpsSN47_pFjXR09ZS1:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/rde/validators/validator_rde_2_x.py#L24)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

This helper method can stay right here in this file. If needed, move it to rde/validators/utils.py
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 47 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoZrYMDVcRK1YxTv-2:-MUpsTQ-Bthr3gtedQXf:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L47)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Looks like we are using the return value of the validate method for a different purpose. Validate method doesn't have to determine whether it is an upgrade or resize.

It should be something like this:

rde_validator_factory.get_validator(2.0.0).validate()
svc.update_cluster(spec)

Then in the cluster_svc_2x.py, please add a new method update_cluster()
def update_cluster(spec):
....if change in the worker count:
...............resize_cluster()
....elif change in the template:
...............upgrade_cluster()

We will have to these validators even from behavior handlers and let us have these methods strictly follow their signatures.

</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 48 at r1](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUoai2r3lMknwl8LyXQ:-MUpsTxr-6bvUkShVTJJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/8453f653bfc1442cec2aff9dc3624885d2b5afff/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L48)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We cannot use rde_constants.RuntimeRDeVersion.RDE_2_X here. This variable changes for every release.
Please create another constant Enum.

RDEVersion(Enum):
...1_0_0='1.0.0'
...2_0_0='2.0.0'
...2_1_0='2.1.0'

In the next release, assuming RDE version bumps up to 2.1.0, then below is how RuntimeRDEVersion Enum would get updated.
RuntimeRDEVersion(Enum):
..RDE_1_X:'1.0.0'
..RDE_2_X:'2.0.0'
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/utils.py, line 96 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtj2Sz8M83opEG2OUz:-MUtj2T-4k6ntLIeloYA:bf5mkgf) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/utils.py#L96)):*
> ```Python
>     workers_count = len(entity_status.nodes.workers)
>     if workers_count == 0:
>         workers = rde_2_0_0.Workers(sizing_class='System Default',
> ```

should we be using rde_2_0_0 directly here?
@sahithi Should we be making a change to get models from rde_in_use?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 553 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpy4Bs3uOl2iRJBaOg:-MUpy4Bs3uOl2iRJBaOh:b-ft7up7) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/backend/cluster_service_2_x.py#L553)):*
> ```Python
>         desired_template_revision = update_spec.spec.k8_distribution.template_revision  # noqa: E501
>         if current_template_name != desired_template_name or current_template_revision != desired_template_revision:  # noqa: E501
>             return self.upgrade_cluster(cluster_id, update_spec)
> ```

Are we assuming that cluster_service_2_x will only be called from handlers? Because other paths might not have validation done, which can result in `None` being returned.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 14 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtoBhE6Q0jgJhtDKN6:-MUtoBhE6Q0jgJhtDKN7:bbm70xd) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/validators/validator_rde_2_x.py#L14)):*
> ```Python
> 
> 
> class Validator_2_0_0(AbstractValidator):
> ```

Can you please add a TODO indicating that validators for rest of the operations in V36 will be implemented once the handler functions are copied to v36/def_cluster_handler.py?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 42 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpxH8c0rnuRWdRdhQ2:-MUpxH8c0rnuRWdRdhQ3:b-nbl25g) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L42)):*
> ```Python
>     cluster_entity: AbstractNativeEntity = \
>         NativeEntityClass(**data[RequestKey.INPUT_SPEC])  # noqa: E501
>     print(asdict(cluster_entity))
> ```

I think this was accidentally committed.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 154 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtkz773NWSTD_2GOqV:-MUtkz773NWSTD_2GOqW:bpatdz8) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/models/rde_2_0_0.py#L154)):*
> ```Python
>             if isinstance(control_plane, dict) else control_plane or ControlPlane()  # noqa: E501
>         if self.control_plane.sizing_class is None:
>             self.control_plane.sizing_class = "System Default"
> ```

I don't think there is a need for this anymore since we are not validating spec fields with null values.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/utils.py, line 96 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtj2Sz8M83opEG2OUz:-MUtrmdi09uHMJhpwqTj:b-yifli8) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/utils.py#L96)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we be using rde_2_0_0 directly here?
@sahithi Should we be making a change to get models from rde_in_use?
</blockquote></details>

This is the method that is exclusive for 2_0_0 after the method below decides which model to use:

def construct_cluster_spec_from_entity_status(entity_status: Union[rde_1_0_0.Status, rde_2_0_0.Status], rde_version_in_use: str) -> Union[rde_1_0_0.ClusterSpec, rde_2_0_0.ClusterSpec]:  # noqa: E501 ⋯ expand 8 lines
    :raises NotImplementedError
    """
    # TODO: Refactor this multiple if to rde_version -> handler pattern
    if rde_version_in_use == def_constants.RDEVersion.RDE_2_0_0.value:
        return construct_2_x_cluster_spec_from_entity_status(entity_status)
    raise NotImplementedError(f"constructing cluster spec from entity status for {rde_version_in_use} is"  # noqa:
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 553 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpy4Bs3uOl2iRJBaOg:-MUtvQfd5PJ4xb9d7bd6:b-quojhu) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/backend/cluster_service_2_x.py#L553)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we assuming that cluster_service_2_x will only be called from handlers? Because other paths might not have validation done, which can result in `None` being returned.
</blockquote></details>

Atleast for now, we follow other methods of this class.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 154 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtkz773NWSTD_2GOqV:-MUttBwk-Jne3OpdnJys:bqbtb1v) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/models/rde_2_0_0.py#L154)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I don't think there is a need for this anymore since we are not validating spec fields with null values.
</blockquote></details>

This constructor is currently in use rde/utils.py
For future, if one wants to constuct default ClusterSpec
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 14 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtoBhE6Q0jgJhtDKN6:-MUtv7Jw0KiPnNKttVhw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/validators/validator_rde_2_x.py#L14)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Can you please add a TODO indicating that validators for rest of the operations in V36 will be implemented once the handler functions are copied to v36/def_cluster_handler.py?
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 42 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpxH8c0rnuRWdRdhQ2:-MUtvDO57-O8E3B5zHKo:b8fibtk) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L42)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I think this was accidentally committed.
</blockquote></details>

Removed debug statement. thanks

**Review by sahithi — APPROVED** [review]
:lgtm: minor comments

> Reviewed 4 of 8 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934#-:-MUtvukdBbHyxEhvSIJ3:b-kfw89e)* status: 9 of 10 files reviewed, 10 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 96 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtj2Sz8M83opEG2OUz:-MUtpA2A6ff8l5752SBS:b-a2lyyb) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/utils.py#L96)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

should we be using rde_2_0_0 directly here?
@sahithi Should we be making a change to get models from rde_in_use?
</blockquote></details>

I think this method is specific to rde_2_0_0. Sakthi, can you rename the method from 2_x to 2.0.0
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 553 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpy4Bs3uOl2iRJBaOg:-MUtsM6mEgi6El2eE0Ps:bgvnqyi) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/backend/cluster_service_2_x.py#L553)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Are we assuming that cluster_service_2_x will only be called from handlers? Because other paths might not have validation done, which can result in `None` being returned.
</blockquote></details>

+1
Please raise an exception at the end - "update not supported for the specified input specification"
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 524 at r3](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtqQMXAQfInlq_BRX2:-MUtqQMXAQfInlq_BRX3:bj6o0g3) ([raw file](https://github.com/vmware/container-service-extension/blob/e56c98044409f14f3e10c6eed85c87d860f7be59/container_service_extension/rde/backend/cluster_service_2_x.py#L524)):*
> ```Python
>         return curr_entity
> 
>     def update_cluster(self, cluster_id: str, update_spec: rde_2_0_0.NativeEntity):  # noqa: E501
> ```

We are hardcoding the file to deal with rde_2_0_0.
We can create an instance variable in the ClusterService constructor to retrieve the model for the current rde_in_use.
Aniruddh, can you please fix this in a separate PR? I can create a task for you in this sprint, we can story point tomorrow.
___
*[container_service_extension/rde/models/rde_2_0_0.py, line 154 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtkz773NWSTD_2GOqV:-MUtvBgH2whnpG1BoNrE:b-2igjp0) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/models/rde_2_0_0.py#L154)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I don't think there is a need for this anymore since we are not validating spec fields with null values.
</blockquote></details>

We will still need this to populate default values for the control plane and recursive construction of model objects.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934)* status: 7 of 10 files reviewed, 10 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 96 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUtj2Sz8M83opEG2OUz:-MUtyy1U4umb9lZOl8-b:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/utils.py#L96)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think this method is specific to rde_2_0_0. Sakthi, can you rename the method from 2_x to 2.0.0
</blockquote></details>

Done.
___
*[container_service_extension/rde/backend/cluster_service_2_x.py, line 553 at r2](https://reviewable.io/reviews/vmware/container-service-extension/934#-MUpy4Bs3uOl2iRJBaOg:-MUtz5CMDmloPvbYp2ku:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/7b3cf9b17601fba1db45b33ec5e20f5ca179131c/container_service_extension/rde/backend/cluster_service_2_x.py#L553)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1
Please raise an exception at the end - "update not supported for the specified input specification"
</blockquote></details>

Done.

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 8 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/934#-:-MUuEqbM-2hB_tEpAFta:bg7igkv)* status: all files reviewed, 10 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

**Pull request merged**
