### PR TITLE
[VCDA-1825] Fix Minor error codes and add exception handling to cluster_service

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Exception handling to handle raw vsphere exceptions in vcdbroker and cluster_service
* Fetch entity ID from the header instead of making additional call to get entity by name in create cluster
* remove delete cluster comment suggesting recreation of entity if delete fails
* Avoid sending response status code as minor error code in entity_service.py and schema_service.py

@rocknes @sahithi @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
Aniruddh, I don't see any fix made in the delete cluster workflow - the one Aritra raised.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755#-:-MI6ZeKSB5fJuRn0gvvu:b-kkp4mh)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/def_/cluster_service.py, line 119 at r1](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6Y90J450hXvmeUPGS:-MI6Y90J450hXvmeUPGT:bd27gxp) ([raw file](https://github.com/vmware/container-service-extension/blob/88bc9aa7135bc20cee9c01476ca02ac1c317a190/container_service_extension/def_/cluster_service.py#L119)):*
> ```Python
>         return result.content.decode()
> 
>     def create_cluster(self, cluster_spec: def_models.ClusterEntity):
> ```

Please add a try-catch block to the sync portion of the cluster creation.
If an exception is raised after the defined entity creation, it would remain in PRECREATE state forever.
Invoke _fail_and_resolve_entity_ method in the except block.
___
*[container_service_extension/def_/cluster_service.py, line 301 at r1](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6Z6-1Dz5QtHYTQkxf:-MI6Z6-1Dz5QtHYTQkxg:b1da969) ([raw file](https://github.com/vmware/container-service-extension/blob/c114a2fcc2de43550a6280fd74b0ac1d699040eb/container_service_extension/def_/cluster_service.py#L301)):*
> ```Python
>         # attempt deleting the defined entity; lets vCD authorize the user
>         # for delete operation. If deletion of the cluster fails for any
>         # reason, defined entity will be recreated by async thread.
> ```

Please keep the first statement -   "attempt deleting the defined entity; lets vCD authorize the user for delete operation."

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 119 at r1](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6Y90J450hXvmeUPGS:-MI6_IglDLpczrK-oPmY:b-bvwl7r) ([raw file](https://github.com/vmware/container-service-extension/blob/88bc9aa7135bc20cee9c01476ca02ac1c317a190/container_service_extension/def_/cluster_service.py#L119)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please add a try-catch block to the sync portion of the cluster creation.
If an exception is raised after the defined entity creation, it would remain in PRECREATE state forever.
Invoke _fail_and_resolve_entity_ method in the except block.
</blockquote></details>

If there is an error in create_entity(), I don't think the entity will be created at all.
Previously, we made use of get_native_entity_by_name() which could have thrown an exception. I have removed the use of get_native_entity_by_name() and the cluster_id is now fetched from the Location header.
Here, if the task is invalid, then we won't have any way of getting the cluster_id to fail and resolve the entity

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 301 at r1](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6Z6-1Dz5QtHYTQkxf:-MI6axvu76P3X9t83OuU:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c114a2fcc2de43550a6280fd74b0ac1d699040eb/container_service_extension/def_/cluster_service.py#L301)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please keep the first statement -   "attempt deleting the defined entity; lets vCD authorize the user for delete operation."
</blockquote></details>

Done.

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/def_/cluster_service.py, line 1815 at r2](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6oN8A7gVwIu3oIsNv:-MI6oN8B43wo048qZyqh:b-crhvk4) ([raw file](https://github.com/vmware/container-service-extension/blob/00c28d0dcffbe979bc368a10250f9a5027337cc5/container_service_extension/def_/cluster_service.py#L1815)):*
> ```Python
>     for node_name in node_names:
>         try:
>             raise Exception("faked an error")
> ```

Is the above statement for debugging?

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/cluster_service.py, line 1815 at r2](https://reviewable.io/reviews/vmware/container-service-extension/755#-MI6oN8A7gVwIu3oIsNv:-MI6rWDV2tUVUAmmzsov:b-i6w33m) ([raw file](https://github.com/vmware/container-service-extension/blob/00c28d0dcffbe979bc368a10250f9a5027337cc5/container_service_extension/def_/cluster_service.py#L1815)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

Is the above statement for debugging?
</blockquote></details>

Yes. Sorry abt that! Thanks for catching this!

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @sahithi and @sakthisunda)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/755#-:-MIKwI_E5V0Qz6PvWkZW:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/vcdbroker.py, line 1938 at r3](https://reviewable.io/reviews/vmware/container-service-extension/755#-MIKrjE770pxdE-wOLEK:-MIKrjE88jedYHpN9cq5:b-68351w) ([raw file](https://github.com/vmware/container-service-extension/blob/11bd9bf4b0fb517f539898a20fd5b2c0297edc0d/container_service_extension/vcdbroker.py#L1938)):*
> ```Python
>     all_results = []
>     for node_name in node_names:
>         try:
> ```

Shouldn't the try block be outside the for loop?
Is there any merit in continuing the operation if it has failed on one node?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/vcdbroker.py, line 1938 at r3](https://reviewable.io/reviews/vmware/container-service-extension/755#-MIKrjE770pxdE-wOLEK:-MIKylr-7l4sNTelhP_D:b-lcu11v) ([raw file](https://github.com/vmware/container-service-extension/blob/11bd9bf4b0fb517f539898a20fd5b2c0297edc0d/container_service_extension/vcdbroker.py#L1938)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Shouldn't the try block be outside the for loop?
Is there any merit in continuing the operation if it has failed on one node?
</blockquote></details>

I can get the exact node name which failed execution of scripts when try-except is inside the for loop

**Pull request merged**
