### PR TITLE
[VCDA-2274] Fix upgrade issue related to missing rights in `cse service account`

### PR DESCRIPTION
**Pull request by rocknes**
CSE service account is missing the 'Edit' right for RightsBundles, as a result, it is unable to publish rights bundle to tenant orgs.
This workflow will break any upgrade from CSE 2.6 or prior to CSE 3.0/CSE 3.1.

Additionally there is a logic bug around how CSE publishes the right bundle to tenants. In the current implementation, CSE doesn't preserve the list of tenants who already has the right bundle published to them. This PR fixes the bug.

Additional small fixes to 
* improve flake8 compliance
* change the flag for cse create-service-role to follow standard key to ignore ssl certificate verification

Testing:
ToDo

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/965)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/installer/right_bundle_manager.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/965#-MWRhUSVCkbViCZZOJJ3:-MWRhUSVCkbViCZZOJJ4:b9xkj21) ([raw file](https://github.com/vmware/container-service-extension/blob/01dce6e56fddca620b1b1667ec93a07bae95c0fa/container_service_extension/installer/right_bundle_manager.py#L62)):*
> ```Python
>         shared_to_orgs = set()
>         page_num = 0
>         while True:
> ```

I just checked the 10.2 api explorer and tried out the POST equivalent. It adds the rights only to the specified orgs. Do you think it is a good idea to use it instead of iterating over multiple REST calls ? (Asking because we were already hit with a similar OVDC bug)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/965)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/installer/right_bundle_manager.py, line 62 at r1](https://reviewable.io/reviews/vmware/container-service-extension/965#-MWRhUSVCkbViCZZOJJ3:-MWViY4-CohSNiVAUbBz:b-ify5h2) ([raw file](https://github.com/vmware/container-service-extension/blob/01dce6e56fddca620b1b1667ec93a07bae95c0fa/container_service_extension/installer/right_bundle_manager.py#L62)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I just checked the 10.2 api explorer and tried out the POST equivalent. It adds the rights only to the specified orgs. Do you think it is a good idea to use it instead of iterating over multiple REST calls ? (Asking because we were already hit with a similar OVDC bug)
</blockquote></details>

Thanks for pointing this out. Done :)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/965#-:-MWVrG4867tL4S5Qnw-m:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/965#-:-MWX9eHw-asSKyb_tLtE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Pull request merged**
