### PR TITLE
Change the behavior definition to include "actAsToken" property

### PR DESCRIPTION
**Pull request by sahithi**
Behavior invocation requests would embed the "actAsToken" only if the corresponding definition had "actAsToken= true"
This is a recent change done by the Extensibility team for security reasons.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1096)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1096)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/behaviors/behavior_model.py, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1096#-Mdc11TEAncQWuDFXuLC:-Mdc11TFCrL845XSdhJ9:b-6xylkx) ([raw file](https://github.com/vmware/container-service-extension/blob/b23c25156991b1903b3afb4660949d1b2bba8387/container_service_extension/rde/behaviors/behavior_model.py#L52)):*
> ```Python
>     serviceId: str = MQTT_EXTENSION_URN
>     # TODO Remove this property once Extensibility team sets the default value.
>     invocation_timeout: int = 86400
> ```

Why are we setting the default value here?
The init method is already setting the default value right?

**Review by rocknes — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1096#-:-Mdc1AQaEtg8lHeIc8ki:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by sahithi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1096)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/rde/behaviors/behavior_model.py, line 52 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1096#-Mdc11TEAncQWuDFXuLC:-Mdc_itCB3rFbxgqvwZk:bvdonwx) ([raw file](https://github.com/vmware/container-service-extension/blob/b23c25156991b1903b3afb4660949d1b2bba8387/container_service_extension/rde/behaviors/behavior_model.py#L52)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Why are we setting the default value here?
The init method is already setting the default value right?
</blockquote></details>

Not sure exactly. There is no harm though.

**Pull request merged**
