### PR TITLE
[VCDA-2667] Fix CSE install/upgrade to show better message around template creation/update

### PR DESCRIPTION
**Pull request by rocknes**
Whenever `-t` flag is used with `cse install/upgrade`, warn users that without a valid template in inventory, CSE startup will fail.

Additionally there was a bug in the way templates are updated from v1 to v2, the scripts files are not re-downloaded into proper v2 script directory. This PR fixes that issue too.

Testing done:
Ran `cse upgrade` with -t flag and checked console for the error message.

Ran a proper cse upgrade from 3.0.3 to 3.1.0, output attached below

```
(cse) D:\code\cse\container-service-extension>cse upgrade -c config.yaml -st
Required Python version: >= 3.7.3
Installed Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Validating config file 'config.yaml'
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
Connected to vCloud Director (bos1-vcloud-static-170-222.eng.vmware.com:443)
Connected to vCenter Server 'vc1' as 'administrator@vsphere.local' (bos1-vcloud-static-171-33.eng.vmware.com)
Config file 'config.yaml' is valid
Upgrading CSE on vCloud Director using config file 'config.yaml'
Connected to vCD as system administrator: bos1-vcloud-static-170-222.eng.vmware.com:443
Found CSE api extension registered by CSE '3.0.3' in non-legacy mode.
Setting up placement policies for cluster types
Skipping creation of global PVDC compute policy. Policy already exists
Skipping creation of VDC placement policy 'native'. Policy already exists
Registering Runtime defined entity schema
Using RDE version: 2.0.0
Built in kubernetes interface 'urn:vcloud:interface:vmware:k8s:1.0.0' found.
Skipping creation of interface 'urn:vcloud:interface:cse:k8s:1.0.0'. Interface already exists.
Skipping creation of behavior 'urn:vcloud:behavior-interface:createCluster:cse:k8s:1.0.0' on interface 'urn:vcloud:interface:cse:k8s:1.0.0'.Behavior already found.
Skipping creation of behavior 'urn:vcloud:behavior-interface:updateCluster:cse:k8s:1.0.0' on interface 'urn:vcloud:interface:cse:k8s:1.0.0'.Behavior already found.
Skipping creation of behavior 'urn:vcloud:behavior-interface:deleteCluster:cse:k8s:1.0.0' on interface 'urn:vcloud:interface:cse:k8s:1.0.0'.Behavior already found.
Skipping creation of behavior 'urn:vcloud:behavior-interface:deleteNfsNode:cse:k8s:1.0.0' on interface 'urn:vcloud:interface:cse:k8s:1.0.0'.Behavior already found.
Skipping creation of Native Entity Type 'urn:vcloud:type:cse:nativeCluster:2.0.0'. Native Entity Type already exists.
Skipping behavior overriding for 'urn:vcloud:behavior-type:createKubeConfig:cse:nativeCluster:2.0.0:vmware:k8s:1.0.0' on entity type 'urn:vcloud:type:cse:nativeCluster:2.0.0'
Setting ACLs on behaviors of the entity type 'urn:vcloud:type:cse:nativeCluster:2.0.0'
Updated user-role: CSE Service Role with Rights-bundle: cse:nativeCluster Entitlement
Skipping creation of templates.
Please note, CSE server startup needs at least one valid template.
Please create CSE K8s template(s) using the command `cse template install`.
Processing existing templates.
Downloaded remote template cookbook from https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/template_v2.yaml
Template ubuntu-16.04_k8-1.20_weave-2.6.5 revision 2 will be processed.
Successfully updated metadata of local template : ubuntu-16.04_k8-1.20_weave-2.6.5 revision 2.
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/cust.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\cust.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/init.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\init.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/nfsd.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\nfsd.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/cluster-upgrade/docker-upgrade.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\cluster-upgrade/docker-upgrade.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/cluster-upgrade/control-plane-cni-apply.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\cluster-upgrade/control-plane-cni-apply.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/cluster-upgrade/control-plane-k8s-upgrade.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\cluster-upgrade/control-plane-k8s-upgrade.sh'...
Download complete
Downloading file from 'https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/scripts_v2/ubuntu-16.04_k8-1.20_weave-2.6.5_rev2/cluster-upgrade/worker-k8s-upgrade.sh' to 'C:\Users\Aritra\.cse_scripts\2.0.0\ubuntu-16.04_k8-1.20_weave-2.6.5_rev2\cluster-upgrade/worker-k8s-upgrade.sh'...
Download complete
Assigning placement policies to existing templates.
Processing template ubuntu-16.04_k8-1.20_weave-2.6.5 revision 2
Successfully tagged template ubuntu-16.04_k8-1.20_weave-2.6.5_rev2 with placement policy native.
Loading all CSE clusters for processing...
Assigning placement compute policy(s) to vDC(s) hosting existing CSE clusters.
Identifying vDC(s) that are currently hosting CSE clusters.
Found 1 vDC(s) hosting NATIVE CSE clusters.
Added compute policy 'native' to vDC 'test-orgvdc'
Publishing CSE native cluster right bundles to orgs where clusters are deployed
Successfully published CSE native cluster right bundle to Orgs
Removing old sizing compute policies created by CSE.
Processing Org : 'System'
Finished processing Org : 'System'
Processing Org : 'cse-org'
Processing Org VDC : 'cse-orgvdc'
Finished processing Org VDC : 'cse-orgvdc'
Finished processing Org : 'cse-org'
Processing Org : 'test-org'
Processing Org VDC : 'test-orgvdc'
Finished processing Org VDC : 'test-orgvdc'
Finished processing Org : 'test-org'
Processing existing CSE k8s clusters
Processing cluster 'cluster1'
Updating cluster1 RDE from 1.0.0 to 2.0.0
Updated cluster id of cluster 'cluster1'
Finished processing all clusters.
Removing old native entity types
Deleting entity type: urn:vcloud:type:cse:nativeCluster:1.0.0
The following users own CSE k8s clusters and will require `cse:nativeCluster Entitlement` right bundle to access them in CSE 3.1
Org : test-org -> Users : system
Updated MQTT extension 'cse'
Upgraded CSE successfully
```

Also created a cluster from this upgraded template in CSE 3.1, it went through successfully.

Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @ltimothy7 and @sahithi)

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sahithi)

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104#-:-Me79cT2EPx4oU6MfHza:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 320 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1104#-Me79gGcDe0h_zQ9z1sk:-Me79gGcDe0h_zQ9z1sl:blbab9s) ([raw file](https://github.com/vmware/container-service-extension/blob/e49f7d53380c3dbaafcddb048c0a95ceb7671772/container_service_extension/installer/configure_cse.py#L320)):*
> ```Python
> 
>         if skip_template_creation:
>             msg = "Skipping creation of templates.\nPlease note, CSE server " \
> ```

We may not need this message once you add the code to make existing templates forward compatible. I hope this message wouldn't confuse users then. 

We can rephrase this slightly to say "create templates with so and so cmd, if CSE server start up fails"

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 320 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1104#-Me79gGcDe0h_zQ9z1sk:-Me7ZtBxBx9Dj6vz9X4t:b-bqfdvj) ([raw file](https://github.com/vmware/container-service-extension/blob/e49f7d53380c3dbaafcddb048c0a95ceb7671772/container_service_extension/installer/configure_cse.py#L320)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We may not need this message once you add the code to make existing templates forward compatible. I hope this message wouldn't confuse users then. 

We can rephrase this slightly to say "create templates with so and so cmd, if CSE server start up fails"
</blockquote></details>

Well the code that I am going to add will only work *if* there is a compatible template in template_v2.yaml .. otherwise CSE will ignore all existing templates.

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104#-:-MeBQfwp48MK_OrWquB4:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 320 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1104#-Me79gGcDe0h_zQ9z1sk:-MeBrceU08sXfcuLnmHK:b-j6n715) ([raw file](https://github.com/vmware/container-service-extension/blob/e49f7d53380c3dbaafcddb048c0a95ceb7671772/container_service_extension/installer/configure_cse.py#L320)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Well the code that I am going to add will only work *if* there is a compatible template in template_v2.yaml .. otherwise CSE will ignore all existing templates.
</blockquote></details>

Nit: It is better to write multiline strings with `"""` since it helps readability of code. (same for the rest)
```
msg = """Skipping creation of templates.
Please note, CSE server startup needs at least one valid template.
Please create CSE K8s template(s) using the command `cse template install`."""
```

**Comment by arunmk** [comment]
*[a discussion](https://reviewable.io/reviews/vmware/container-service-extension/1104#-MeBv0xfC179GNmJNult:-MeBv0xfC179GNmJNulu:b-9yuw75) (no related file):*
:lgtm: Good to see that some typings have been added.

---

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @rocknes and @sahithi)

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1104)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/installer/configure_cse.py, line 320 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1104#-Me79gGcDe0h_zQ9z1sk:-MeCAzqL9CTO8sxBqLSW:bx3iq6m) ([raw file](https://github.com/vmware/container-service-extension/blob/e49f7d53380c3dbaafcddb048c0a95ceb7671772/container_service_extension/installer/configure_cse.py#L320)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

Nit: It is better to write multiline strings with `"""` since it helps readability of code. (same for the rest)
```
msg = """Skipping creation of templates.
Please note, CSE server startup needs at least one valid template.
Please create CSE K8s template(s) using the command `cse template install`."""
```
</blockquote></details>

Addressed

**Pull request merged**
