### PR TITLE
[VCDA-2557] Update help strings install upgrade template install

### PR DESCRIPTION
**Pull request by sakthisunda**
- Updated Help strings for CLI on install, upgrade, run, template install
- Fixed sample generation depending on api_version: location of template_cookbook_url and legacy mode 
- Manually verified
@sahithi @Anirudh9794

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057)* status: all files reviewed, 10 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/client/template_commands.py, line 19 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgj0Tf4QynMpvcPtuh:-Mbgj0Tf4QynMpvcPtui:bw4cca9) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/client/template_commands.py#L19)):*
> ```Python
>     """Manage native kubernetes runtime templates.
> 
> Templates that are no longer compliant with CSE template cookbook
> ```

- Install, upgrade, template commands need to talk about what legacy_mode and template_cookbook properties are and how they are connected.
- run command needs to talk about legacy_mode.

Add the below text wherever relevant:
- Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
- Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).
___
*[container_service_extension/server/cli/server_cli.py, line 629 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbgjkZ24TBrJ6AflnjY:-MbgjkZ24TBrJ6AflnjZ:b2a2wos) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L629)):*
> ```Python
>     template cookbook version and legacy_mode setting in config.
>     Set legacy_mode=true to install CSE for VCD api_version < 35.
>     Set legacy_mode=false to install CSE for VCD api_version >= 35.
> ```

Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).
___
*[container_service_extension/server/cli/server_cli.py, line 823 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgl8qM9JeCtaTkC_cP:-Mbgl8qM9JeCtaTkC_cQ:b-8jpqb1) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L823)):*
> ```Python
> 
> @cli.command('upgrade',
>              short_help="Upgrade CSE extension to version 3.1.1 on vCD")
> ```

3.1.0
___
*[container_service_extension/server/cli/server_cli.py, line 865 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgl5zZ2gz6c-QWCqYW:-Mbgl5zZ2gz6c-QWCqYX:b-8jpqb1) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L865)):*
> ```Python
>             skip_template_creation, retain_temp_vapp,
>             ssh_key_file):
>     """Upgrade existing CSE installation/entities to match CSE 3.1.1.
> ```

3.1.0
___
*[container_service_extension/server/cli/server_cli.py, line 868 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglBPvEm_onG9utN6-:-MbglBPvEm_onG9utN60:b-akzaqy) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L868)):*
> ```Python
> 
> \b
>     - Add CSE, RDE version, Legacy mode info to VCD's extension data for CSE
> ```

Please describe what is legacy_mode, where it needs to be set and when?
___
*[container_service_extension/server/cli/server_cli.py, line 874 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglRMN4TZOB7x2imLO:-MbglRMN4TZOB7x2imLP:babnzje) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L874)):*
> ```Python
>     - Install all templates from template repository linked in config file
>     - Currently installed templates that are no longer compliant with
>       CSE template cookbook specification will be ignored.
> ```

with new CSE template cookbook will not be recognized by CSE 3.1. Admins can safely delete them once new templates are installed and the existing clusters are upgraded to newer template revisions.
___
*[container_service_extension/server/cli/server_cli.py, line 877 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbgktOB2T-6GGEQadVH:-MbgktOB2T-6GGEQadVI:b-8jpqb1) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L877)):*
> ```Python
>     - Update existing CSE k8s cluster's to match CSE 3.1 k8s clusters.
>     - Upgrading legacy clusters would require new template creation supported
>       by CSE 3.1.1
> ```

3.1.0
___
*[container_service_extension/server/cli/server_cli.py, line 880 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglOOt0C2GbFqL4lN2:-MbglOOt0C2GbFqL4lN3:bbyilf4) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L880)):*
> ```
>       Set legacy_mode=true to upgrade CSE for VCD api_version < 35.
>       Set legacy_mode=false to upgrade CSE for VCD api_version >= 35.
> ```
- Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
- Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/client/template_commands.py, line 19 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgj0Tf4QynMpvcPtuh:-Mbivljq9f7RiBaC4G-t:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/client/template_commands.py#L19)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

- Install, upgrade, template commands need to talk about what legacy_mode and template_cookbook properties are and how they are connected.
- run command needs to talk about legacy_mode.

Add the below text wherever relevant:
- Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
- Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).
</blockquote></details>

Done.
___
*[container_service_extension/installer/sample_generator.py, line 300 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbeUUnN6CYs_kpYwNLA:-Mbiwvig0j349CRSpfA_:bs7wumb) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/installer/sample_generator.py#L300)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Ideally I think we should get rid of this api_version param. And simply ask if the sample config should be of type legacy or not.
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 574 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbeUovsBJXPEZKu8Uw_:-MbixnWS3EaAXgBzdJPl:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L574)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

3.1.0
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 629 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbgjkZ24TBrJ6AflnjY:-MbixosS1U7PyHTyxSya:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L629)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 823 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgl8qM9JeCtaTkC_cP:-MbixpxE-igZxZwQeDVN:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L823)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

3.1.0
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 865 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-Mbgl5zZ2gz6c-QWCqYW:-Mbixqiq1_XBCq1_y5HD:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L865)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

3.1.0
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 868 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglBPvEm_onG9utN6-:-MbiyVrbE_R-4H_46YdZ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L868)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please describe what is legacy_mode, where it needs to be set and when?
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 874 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglRMN4TZOB7x2imLO:-MbiyX85DDlwQM0Bs0lS:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L874)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

with new CSE template cookbook will not be recognized by CSE 3.1. Admins can safely delete them once new templates are installed and the existing clusters are upgraded to newer template revisions.
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 877 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbgktOB2T-6GGEQadVH:-MbiyT8ABV6bimysRdZF:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L877)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

3.1.0
</blockquote></details>

Done.
___
*[container_service_extension/server/cli/server_cli.py, line 880 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbglOOt0C2GbFqL4lN2:-MbiyUHyBL7oCv-BGQke:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c87172a81bc95b88a239ad9b3035265b4657ce99/container_service_extension/server/cli/server_cli.py#L880)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>       Set legacy_mode=true to upgrade CSE for VCD api_version < 35.
>       Set legacy_mode=false to upgrade CSE for VCD api_version >= 35.
> ```
- Set legacy_mode=true if CSE 3.1 is configured with VCD whose maximum supported api_version < 35.
- Set legacy_mode=false if CSE 3.1 is configured with VCD whose maximum supported api_version >= 35.
(Note: legacy_mode=true is a valid condition for CSE 3.1 configured with VCDwhose maximum supported api_version >= 35. However, it is strongly recommended to set the property to false to leverage the new functionality).
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057#-:-MbjNpM95zg8AH_14NAZ:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @sahithi)

___
*[container_service_extension/installer/sample_generator.py, line 307 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbjNUaB5258BB_hWMbX:-MbjNUaC7snpq9e96Jns:bzc0v81) ([raw file](https://github.com/vmware/container-service-extension/blob/4c535546573a401a523a7486889e801f11ca76bf/container_service_extension/installer/sample_generator.py#L307)):*
>= 35 :)

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057)* status: 2 of 3 files reviewed, 8 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/installer/sample_generator.py, line 307 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1057#-MbjNUaB5258BB_hWMbX:-MblWC8a3ikezT3hwTf-:bko7vcj) ([raw file](https://github.com/vmware/container-service-extension/blob/4c535546573a401a523a7486889e801f11ca76bf/container_service_extension/installer/sample_generator.py#L307)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

>= 35 :)
</blockquote></details>

thx. Done

**Review by sahithi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1057#-:-Mbx4b61AFugUZw-_ODR:bg7igkv)* status: all files reviewed, 8 unresolved discussions (waiting on @sahithi)

**Pull request merged**
