### PR TITLE
[VCDA-1705 ] New consumer model for AMQP and MQTT consumers

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
The consumer model now uses an extended ThreadPoolExecutor to process the thread, and there is one listener thread.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
For the new consumer model, there is one listener thread which submits work to a ConsumerThreadPoolExecutor (CTPE). Each thread in the CTPE processes the job, grabs a lock and publishes the response.

For testing, I have tested out multiple `vcd cse` commands with the new model.

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)

### CODE REVIEW

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/service.py, line 338 at r1](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGBHFth0a7vVtYYSHJx:-MGBHFth0a7vVtYYSHJy:bskjot4) ([raw file](https://github.com/vmware/container-service-extension/blob/9904e2c7e6f5ece5d9f4d9e407ac173e2a6b7152/container_service_extension/service.py#L338)):*
> ```Python
>             msg_update_callback.general(msg)
>             logger.SERVER_LOGGER.info(msg)
>         except Exception:
> ```

The keyboard interrupts are not handled

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/service.py, line 338 at r1](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGBHFth0a7vVtYYSHJx:-MGFTGVD5VXanxgWXprm:b-2l5nky) ([raw file](https://github.com/vmware/container-service-extension/blob/9904e2c7e6f5ece5d9f4d9e407ac173e2a6b7152/container_service_extension/service.py#L338)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Done.

The original consumer model of multiple consumers allowed the Keyboard interrupt so that only a certain number of threads would be created. For example, if the config file specified 5 threads, the user could do Ctrl+c  after 2 threads started and have the server running with 2 threads. 

Since we only have one consumer now, I think a ctrl+c while the consumer thread has not been set up should stop the server.  @rocknes What do you think?

</blockquote></details>

If im not wrong, the Message consumer runs as a single thread and in turn creates multiple processor threads. Are you sure that by catching the interrupt here, all the processor threads are also stopped? This is of course assuming that ctrl+c is intended to stop the server.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/service.py, line 338 at r1](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGBHFth0a7vVtYYSHJx:-MGKZHzn8_nNNNpH448N:b-17mg3n) ([raw file](https://github.com/vmware/container-service-extension/blob/9904e2c7e6f5ece5d9f4d9e407ac173e2a6b7152/container_service_extension/service.py#L338)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

If im not wrong, the Message consumer runs as a single thread and in turn creates multiple processor threads. Are you sure that by catching the interrupt here, all the processor threads are also stopped? This is of course assuming that ctrl+c is intended to stop the server.
</blockquote></details>

Thank you. You are right, I was not ensuring that the consumer and its thread pool stopped. I have added the consumer.stop call which will stop the thread pool. Thank you!

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r1, 1 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/sample_generator.py, line 112 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrMkzb0p1YZ0XxbYkn:-MGrMkzcCcSn9oITwXc2:b-1qx91b) ([raw file](https://github.com/vmware/container-service-extension/blob/a32b6a9057edb606b4a8224f920eafde65de5f7d/container_service_extension/sample_generator.py#L112)):*
> ```Python
> SAMPLE_SERVICE_CONFIG = {
>     'service': {
>         'listeners': 10,
> ```

I guess  config_validator directly uses this dictionary?
___
*[container_service_extension/server_constants.py, line 66 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrMy1r2o2Mw6ZPivcX:-MGrMy1r2o2Mw6ZPivcY:bej6jip) ([raw file](https://github.com/vmware/container-service-extension/blob/97353b84149e5135dfd8e1434bce35336af28b1a/container_service_extension/server_constants.py#L66)):*
> ```Python
> TOKEN_PATH = 'tokens'
> 
> # Message Consumer Thread
> ```

Can this description be a little clearer. I guess this is the base name of the message consumer threads, right?
___
*[container_service_extension/consumer/amqp_consumer.py, line 239 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrOTVmCCJBI_XuhKRC:-MGrOTVn6Lhsx3u3OD1o:b9q3m4n) ([raw file](https://github.com/vmware/container-service-extension/blob/97353b84149e5135dfd8e1434bce35336af28b1a/container_service_extension/consumer/amqp_consumer.py#L239)):*
> ```Python
>         self._ctpe.shutdown(wait=True)
>         if self._connection:
>             self._connection.ioloop.start()
> ```

shouldn't this be ioloop.stop() ? can you pleaseverify this?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/sample_generator.py, line 112 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrMkzb0p1YZ0XxbYkn:-MGxh8iFEYGUZiBLw5x5:b-5i2zgc) ([raw file](https://github.com/vmware/container-service-extension/blob/a32b6a9057edb606b4a8224f920eafde65de5f7d/container_service_extension/sample_generator.py#L112)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I guess  config_validator directly uses this dictionary?
</blockquote></details>

Yes, the config_validator uses this dictionary.
___
*[container_service_extension/server_constants.py, line 66 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrMy1r2o2Mw6ZPivcX:-MGxhZJGE4k4V6Mm0E6D:b-sfvqwd) ([raw file](https://github.com/vmware/container-service-extension/blob/97353b84149e5135dfd8e1434bce35336af28b1a/container_service_extension/server_constants.py#L66)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can this description be a little clearer. I guess this is the base name of the message consumer threads, right?
</blockquote></details>

Done. This is the name of the single consumer thread.
___
*[container_service_extension/consumer/amqp_consumer.py, line 239 at r3](https://reviewable.io/reviews/vmware/container-service-extension/727#-MGrOTVmCCJBI_XuhKRC:-MGxi5arDWR2SMaQNMSb:b5ynksn) ([raw file](https://github.com/vmware/container-service-extension/blob/97353b84149e5135dfd8e1434bce35336af28b1a/container_service_extension/consumer/amqp_consumer.py#L239)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

shouldn't this be ioloop.stop() ? can you pleaseverify this?
</blockquote></details>

The loop will stop on its own when the channel has been completely closed. It is the convention for cleanly shutting down the consumer.

https://buildmedia.readthedocs.org/media/pdf/pika/stable/pika.pdf
https://pika.readthedocs.io/en/0.13.1/examples/asynchronous_consumer_example.html

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r1, 1 of 4 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727#-:-MHFQ0sxESRdm0ASUHEn:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/consumer/consumer.py, line 16 at r4](https://reviewable.io/reviews/vmware/container-service-extension/727#-MHFPExMC5aulGpOwfC3:-MHFPExODGw5zUOwyKVh:b89imy6) ([raw file](https://github.com/vmware/container-service-extension/blob/3ae077e4a6f065baa1cd65c3977ffeadb1af09a5/container_service_extension/consumer/consumer.py#L16)):*
> ```Python
>     """Returns the consumer class for the correct message protocol."""
> 
>     def __new__(cls, config, num_processors):
> ```

I have been seeing this pattern in CSE codebase in few different places. Any idea why this specific pattern was chosen of returning different object from constructor?

I think a proper abstract class + 2 concrete classes + a factory to create the instances would have been a more standard design pattern. Please bring this up in the next standup.
___
*[container_service_extension/consumer/consumer_thread_pool_executor.py, line 4 at r4](https://reviewable.io/reviews/vmware/container-service-extension/727#-MHFPhvZ0l7lNAy6g-zX:-MHFPhv_4PS5KiNprvRq:b-ht2r6z) ([raw file](https://github.com/vmware/container-service-extension/blob/3ae077e4a6f065baa1cd65c3977ffeadb1af09a5/container_service_extension/consumer/consumer_thread_pool_executor.py#L4)):*
> ```Python
> from threading import Lock
> 
> # import container_service_extension.logger as logger
> ```

Drop this line?

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/consumer/consumer.py, line 16 at r4](https://reviewable.io/reviews/vmware/container-service-extension/727#-MHFPExMC5aulGpOwfC3:-MHOTAvR55VYukBYwVA1:bsifvdy) ([raw file](https://github.com/vmware/container-service-extension/blob/3ae077e4a6f065baa1cd65c3977ffeadb1af09a5/container_service_extension/consumer/consumer.py#L16)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I have been seeing this pattern in CSE codebase in few different places. Any idea why this specific pattern was chosen of returning different object from constructor?

I think a proper abstract class + 2 concrete classes + a factory to create the instances would have been a more standard design pattern. Please bring this up in the next standup.
</blockquote></details>

Thank you for bringing this up. I selected this patten based on ovdc.py and cluster.py; I'm open to other patterns too depending on what the team thinks. :)

**Review by rocknes — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/727)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

**Pull request merged**
