### PR TITLE
[VCDA-1927 & VCDA-2042] Paginate TKG and legacy native cluster responses

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include:

Port changes from master to cse_3_0_updates

Add a generic model to parse both TKG and native clusters.
Modify legacy native list clusters endpoint to support pagination
CLI changes to print paginated response for list cluster operation
Testing done:

vcd cse cluster list with API server running in API version 35
vcd cse cluster list with API server running in API version 33
Check postman response for /api/cse/clusters endpont

@rocknes @sahithi @arunmk @sakthisunda @ltimothy7 @ChintanShahVMware

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 10 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: 10 of 20 files reviewed, all discussions resolved

**Review by sakthisunda — APPROVED** [review]
> Reviewed 10 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/def_/cluster_service.py, line 101 at r1](https://reviewable.io/reviews/vmware/container-service-extension/868#-MQrw_kR2yOAJEn7keYS:-MQrw_kSDHjKcrR_3K0y:b-yritzc) ([raw file](https://github.com/vmware/container-service-extension/blob/fa80e4496138bef6383e97ba169689c67b7b2a8e/container_service_extension/def_/cluster_service.py#L101)):*
> ```Python
>             version=ent_type.version,
>             filters=filters)
> ```

✅ ( new change to handle no pagination requirement)
___
*[container_service_extension/def_/entity_service.py, line 223 at r1](https://reviewable.io/reviews/vmware/container-service-extension/868#-MQs-cG9A23PRqFoC8Uk:-MQs-cG9A23PRqFoC8Ul:b2t5o5m) ([raw file](https://github.com/vmware/container-service-extension/blob/fa80e4496138bef6383e97ba169689c67b7b2a8e/container_service_extension/def_/entity_service.py#L223)):*
> ```Python
>         result[PaginationKey.VALUES] = entity_list
>         return result
> ```

✅

**Review by sakthisunda — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: 27 of 29 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/request_processor.py, line 483 at r2](https://reviewable.io/reviews/vmware/container-service-extension/868#-MRRuB6ODew2FmCmXBDv:-MRRuB6ODew2FmCmXBDw:b4dzfl1) ([raw file](https://github.com/vmware/container-service-extension/blob/0b7dce47ac08c876e4055099372a4fe47795b56f/container_service_extension/request_processor.py#L483)):*
> ```Python
> 
>     from container_service_extension.logger import SERVER_LOGGER
>     SERVER_LOGGER.debug(f"********Operation type = {operation_type}")
> ```

 Just making sure that the intent is to add the above statement and not for tempoary debug.
___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 25 at r2](https://reviewable.io/reviews/vmware/container-service-extension/868#-MRRw35A19GrX8K7W24G:-MRRw35A19GrX8K7W24H:b-xvxmnj) ([raw file](https://github.com/vmware/container-service-extension/blob/0b7dce47ac08c876e4055099372a4fe47795b56f/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L25)):*
> ```Python
>     def create_cluster(self, cluster_entity_definition: def_models.NativeEntity):  # noqa: E501
>         cluster_entity_dict = asdict(cluster_entity_definition)
>         uri = self._legacy_clusters_uri
> ```


uri = self._legacy_clusters_uri 

Is self._legacy_clusters_uri initialized ?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/request_processor.py, line 483 at r2](https://reviewable.io/reviews/vmware/container-service-extension/868#-MRRuB6ODew2FmCmXBDv:-MRVodVv1OI2LZdGzNX7:b-b819dd) ([raw file](https://github.com/vmware/container-service-extension/blob/0b7dce47ac08c876e4055099372a4fe47795b56f/container_service_extension/request_processor.py#L483)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

 Just making sure that the intent is to add the above statement and not for tempoary debug.
</blockquote></details>

This was a debug line. Thanks for catching

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/cse_client/api_35/native_cluster_api.py, line 25 at r2](https://reviewable.io/reviews/vmware/container-service-extension/868#-MRRw35A19GrX8K7W24G:-MRVoDvo3eSjpF0oWSzT:b-clwqjf) ([raw file](https://github.com/vmware/container-service-extension/blob/0b7dce47ac08c876e4055099372a4fe47795b56f/container_service_extension/client/cse_client/api_35/native_cluster_api.py#L25)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>


uri = self._legacy_clusters_uri 

Is self._legacy_clusters_uri initialized ?



</blockquote></details>

Sorry, I realized I didn't have to change the url for this operation and forgot to remove this. Thanks for catching this

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: 27 of 29 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 10 of 20 files at r1, 13 of 19 files at r2, 1 of 2 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: all files reviewed, 12 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

___
*[container_service_extension/configure_cse.py, line 748 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTcHytD30Isj1vREyU:-MSTcHyu3I_rt8em1Jkv:b-fntgyn) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/configure_cse.py#L748)):*
> ```Python
>     """
>     if config is None:
>         config = []
> ```

this should be a dictionary right?
___
*[container_service_extension/utils.py, line 495 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTq3FgChl4b2pn2vQQ:-MSTq3FhEa_Pa1eaqe2b:bu2rfez) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/utils.py#L495)):*
> ```Python
>     }
> 
>     # Conditionally deleting instead of conditionally adding the entry
> ```

Do we really need to maintain the order? JSON itself has no ordering.
___
*[container_service_extension/vcdbroker.py, line 106 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTqNVD56d8RiysmCtu:-MSTqNVD56d8RiysmCtv:b-g1rqea) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L106)):*
> ```Python
>         """List all native clusters and their relevant metadata.
> 
>         :return: a list of all clusters if 'page_number' or 'page_size' are
> ```

This description is not right, we default to page 1 and default page size if the params are missing
___
*[container_service_extension/vcdbroker.py, line 1575 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTr90a9FTChpv2xvxO:-MSTr90a9FTChpv2xvxP:b-xwcrs2) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L1575)):*
> ```Python
>     """Get list of dictionaries containing data for each visible cluster.
> 
>     :param str cluster_name: name of the cluster to search for
> ```

Do we really have a need to alter the handlers that serve the old endpoint? If the new endpoint is the only one that handles pagination, the old end point handlers can be left untouched.
___
*[container_service_extension/client/de_cluster.py, line 77 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTrq_51TwjR_SMHdRz:-MSTrq_51TwjR_SMHdS-:b-p7ecyj) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/client/de_cluster.py#L77)):*
> ```Python
>                     logger.CLIENT_LOGGER.error(msg)
>                     raise Exception(msg)
>                 msg = f"User not authorized to fetch TKG clusters: {e}"
> ```

Wondering what happens to a user who doesn't have TKG rights but only NATIVE rights, the exception raised here will prevent them from viewing any native clusters.
___
*[container_service_extension/def_/cluster_service.py, line 95 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTslsEDMvpOvJAVUl9:-MSTslsF5Dzb4Xp7tIBL:b1v53rs) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/def_/cluster_service.py#L95)):*
> ```Python
>         telemetry_handler.record_user_action_details(
>             cse_operation=telemetry_constants.CseOperation.V35_CLUSTER_LIST,
>             cse_params={telemetry_constants.PayloadKey.FILTER_KEYS: ','.join(filters.keys())}  # noqa: E501
> ```

We should probably enhance telemetry to record the page number and page size data.
___
*[container_service_extension/request_handlers/native_cluster_handler.py, line 124 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTtLLN3G-1amZhHZ_G:-MSTtLLO6303FIyps3Bw:bo5qshr) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/native_cluster_handler.py#L124)):*
> ```Python
> 
> 
> def _filter_cluster_list_common_properties(cluster_list: list, common_properties: list = []) -> list:  # noqa: E501
> ```

nit: filter is not the correct verb, 
_retain_properties is a much suitable name for the method in my opinion
___
*[container_service_extension/request_handlers/native_cluster_handler.py, line 150 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTtqiS44QkllZ-iOmi:-MSTtqiS44QkllZ-iOmj:b9we233) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/native_cluster_handler.py#L150)):*
> ```Python
>                                                         page_number=page_number,  # noqa: E501
>                                                         page_size=page_size)
>     common_cluster_properties = [
> ```

nit : properties_to_retain
___
*[container_service_extension/request_handlers/v35/def_cluster_handler.py, line 137 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTu16d0gAV22Y33AC7:-MSTu16e8H309GrKwvjH:bfvk58s) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/v35/def_cluster_handler.py#L137)):*
> ```Python
> 
> 
> def native_cluster_list(data: dict, op_ctx: ctx.OperationContext):
> ```

Please put a TODO here, we are recording telemetry for the new method in legacy handler

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: all files reviewed, 10 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

___
*[container_service_extension/configure_cse.py, line 748 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTcHytD30Isj1vREyU:-MSVMKnt1CIL4Vva-UAc:b-rl488l) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/configure_cse.py#L748)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

this should be a dictionary right?
</blockquote></details>

Yes, you are right. Updated to dictionary
___
*[container_service_extension/utils.py, line 495 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTq3FgChl4b2pn2vQQ:-MSVUuOa6OJ3MBPi6zIq:b-2541e0) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/utils.py#L495)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we really need to maintain the order? JSON itself has no ordering.
</blockquote></details>

No, there is no need for maintaining order. But it is better to keep order for helping readability purposes. Should I undo this change? I added this change just to keep this function in sync with the function in master
___
*[container_service_extension/vcdbroker.py, line 106 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTqNVD56d8RiysmCtu:-MSVXuVi2TX2Gqpx9OKw:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L106)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This description is not right, we default to page 1 and default page size if the params are missing
</blockquote></details>

Done.
___
*[container_service_extension/vcdbroker.py, line 1575 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTr90a9FTChpv2xvxO:-MSVY3c18hHRszm7rfNx:b-rmxekx) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L1575)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we really have a need to alter the handlers that serve the old endpoint? If the new endpoint is the only one that handles pagination, the old end point handlers can be left untouched.
</blockquote></details>

I thought this was a helper function and not a handler. My assumption was `get_clusters_by_page()` and `list_clusters()` were the handler functions.
We made a change in pyvcloud to return paginated response if only page_number and page_size parameters were passed. I matched the behavior of the underlying pyvcloud typed query to the behavior of this function.
___
*[container_service_extension/client/de_cluster.py, line 77 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTrq_51TwjR_SMHdRz:-MSVZ5DXAEfMEFBy0MIK:b2wsrlg) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/client/de_cluster.py#L77)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Wondering what happens to a user who doesn't have TKG rights but only NATIVE rights, the exception raised here will prevent them from viewing any native clusters.
</blockquote></details>

Since there is an if check for the block to run the block if CLI is enabled for TKG only, we should not be displaying native clusters anyways. 
___
*[container_service_extension/def_/cluster_service.py, line 95 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTslsEDMvpOvJAVUl9:-MSV_H9f1gsptQPL7Kzl:b3tv7sl) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/def_/cluster_service.py#L95)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should probably enhance telemetry to record the page number and page size data.
</blockquote></details>

I thought it will be taken care in a different story. Won't the addition of another column alter telemetry tables already present?
___
*[container_service_extension/request_handlers/native_cluster_handler.py, line 124 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTtLLN3G-1amZhHZ_G:-MSVa-Xy6F3a1I_u1_Ae:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/native_cluster_handler.py#L124)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: filter is not the correct verb, 
_retain_properties is a much suitable name for the method in my opinion
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/native_cluster_handler.py, line 150 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTtqiS44QkllZ-iOmi:-MSVaOdC0FwPMhAgz8KU:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/native_cluster_handler.py#L150)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit : properties_to_retain
</blockquote></details>

Done.
___
*[container_service_extension/request_handlers/v35/def_cluster_handler.py, line 137 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTu16d0gAV22Y33AC7:-MSVbEaNEfRsIlbyGcKd:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/request_handlers/v35/def_cluster_handler.py#L137)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please put a TODO here, we are recording telemetry for the new method in legacy handler
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: 28 of 31 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

___
*[container_service_extension/utils.py, line 495 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTq3FgChl4b2pn2vQQ:-MSYnLjI8N0ENQHZMmQb:b-wgwngg) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/utils.py#L495)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

No, there is no need for maintaining order. But it is better to keep order for helping readability purposes. Should I undo this change? I added this change just to keep this function in sync with the function in master
</blockquote></details>

Let's keep the code in sync. No need to revert it.
___
*[container_service_extension/vcdbroker.py, line 1575 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTr90a9FTChpv2xvxO:-MSYmSJv7deT83KfS8-n:b-fltm9e) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L1575)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I thought this was a helper function and not a handler. My assumption was `get_clusters_by_page()` and `list_clusters()` were the handler functions.
We made a change in pyvcloud to return paginated response if only page_number and page_size parameters were passed. I matched the behavior of the underlying pyvcloud typed query to the behavior of this function.
</blockquote></details>

If this method is not called by other modules, then let's make it private/protected.
___
*[container_service_extension/client/de_cluster.py, line 77 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTrq_51TwjR_SMHdRz:-MSYmf4E1zxtIymao9Jx:b-mqxwbc) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/client/de_cluster.py#L77)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Since there is an if check for the block to run the block if CLI is enabled for TKG only, we should not be displaying native clusters anyways. 
</blockquote></details>

Got it my bad. Thanks for the clarification.
___
*[container_service_extension/def_/cluster_service.py, line 95 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTslsEDMvpOvJAVUl9:-MSYmocy2wzNpIc0l5tj:b-9pz0jo) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/def_/cluster_service.py#L95)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

I thought it will be taken care in a different story. Won't the addition of another column alter telemetry tables already present?
</blockquote></details>

Yes, it will alter the schema.
We can do it in a different story, but let's record the intent here with a TODO.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868)* status: 28 of 31 files reviewed, 4 unresolved discussions (waiting on @Anirudh9794, @rocknes, and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 1575 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTr90a9FTChpv2xvxO:-MSYoXLlAL8-fH7VG3AC:b-sck7nf) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/vcdbroker.py#L1575)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If this method is not called by other modules, then let's make it private/protected.
</blockquote></details>

This is called in upgrade code to update cluster metadata
___
*[container_service_extension/def_/cluster_service.py, line 95 at r4](https://reviewable.io/reviews/vmware/container-service-extension/868#-MSTslsEDMvpOvJAVUl9:-MSYxA509PoDnDxk5o7d:bs7wumb) ([raw file](https://github.com/vmware/container-service-extension/blob/22a0f7c2a0a4e2012142b0a332eafbd48bbb8600/container_service_extension/def_/cluster_service.py#L95)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Yes, it will alter the schema.
We can do it in a different story, but let's record the intent here with a TODO.
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/868#-:-MSgB49U3gyf4plpD0S_:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @sakthisunda)

**Pull request merged**
