### PR TITLE
[VCDA-2661] Restrict upgrades from CSE 3.0.3 to CSE 3.1.0

### PR DESCRIPTION
**Pull request by rocknes**
Signed-off-by: rocknes <aritra.iitkgp@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1098)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1098)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rocknes)

**Comment by arunmk** [comment]
:lgtm: 

As I understand, we are not blocking upgrades to 3.1.0 as of now.
I have a general question: as per this logic the user can upgrade in case there is no TKGm runtime enabled on the ovdc. This is a bit strange as CSE is a site-level server and the OVDC is at OVDC level. So in theory I could start CSE server with a different OVDC that does not have TKGm and upgrade it to 3.0 successfully. Then I could restart the server with TKGm enabled and things would work fine?

**Comment by arunmk** [comment]
:lgtm:

**Review by sahithi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1098#-:-MdxH_nEEOpKlxUa6TTq:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/installer/configure_cse.py, line 757 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1098#-MdxHPm-4p_lseIhngVY:-MdxHPm-4p_lseIhngVZ:b4sdlm3) ([raw file](https://github.com/vmware/container-service-extension/blob/ab05ed0777c935fcf515203e0a3bc049335465e0/container_service_extension/installer/configure_cse.py#L757)):*
> ```
> compute_policy_manager.get_cse_vdc_compute_policy
> ```
For the future, we should have a generic UpgradeException which would append the string with the passed-in value.

**Pull request merged**
