### PR TITLE
[VCDA-2204] modify v36 cluster handler

### PR DESCRIPTION
**Pull request by sakthisunda**
- Implementation of CRUD handlers for api version v36
- Update request dispatcher to register v36 cluster handlers
- Update crud handlers  in v36 api handler
- Update validator to get entity as params
- Tested CRUD operations using server_api_version:36 in profiles.yaml
- Telemetry changes and testing completed

@Anirudh9794 @sahithi @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947)

### CODE REVIEW

**Review by Anirudh9794 — COMMENTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @sakthisunda)

___
*[container_service_extension/common/constants/server_constants.py, line 321 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJVr9O0qVWuvM57jgn:-MVJVr9PB3iSItRC6BOM:b-2nie3n) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/common/constants/server_constants.py#L321)):*
> ```Python
> 
>     V36_CLUSTER_CREATE = ('create DEF v36 cluster', '/cse/3.0/clusters', requests.codes.accepted)  # noqa: E501
>     V36_CLUSTER_LIST = ('list DEF clusters', '/cse/3.0/cluster/%s', requests.codes.accepted)  # noqa: E501
> ```

endpoint should be `/cse/3.0/nativeclusters'.
Also, return code should be 200 and not 202
@rocknes should we be removing support for `/cse/3.0/clusters` in CSE 3.1?
___
*[container_service_extension/rde/utils.py, line 82 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJWxAq95pU_1fqBj69:-MVJWxAq95pU_1fqBj6A:bdt9vsh) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L82)):*
> ```Python
>     if rde_version == def_constants.RDEVersion.RDE_2_0_0.value:
>         return construct_2_0_0_cluster_spec_from_entity_status(entity_status)
>     # elif rde_version == def_constants.RDEVersion.RDE_2_1_0:
> ```

Was this commented code accidentally committed?

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/common/constants/server_constants.py, line 321 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJVr9O0qVWuvM57jgn:-MVJoUQN7CThTe99quaF:bzc7cn5) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/common/constants/server_constants.py#L321)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

endpoint should be `/cse/3.0/nativeclusters'.
Also, return code should be 200 and not 202
@rocknes should we be removing support for `/cse/3.0/clusters` in CSE 3.1?
</blockquote></details>

Done. Thanks. For now, leaving /cse/3.0/clusters as well.
___
*[container_service_extension/rde/utils.py, line 82 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJWxAq95pU_1fqBj69:-MVJobX38xhlAkFub2Pt:b-myh0n) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L82)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Was this commented code accidentally committed?
</blockquote></details>

This was intentional for a place-holder for future.

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947)* status: 11 of 14 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/rde/utils.py, line 72 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJP0Mh16jTqlvuBrdL:-MVJP0Mh16jTqlvuBrdM:b-djlob4) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L72)):*
> ```Python
> 
> def construct_cluster_spec_from_entity_status(entity_status: Union[rde_1_0_0.Status, rde_2_0_0.Status], rde_version: str) -> Union[rde_1_0_0.ClusterSpec, rde_2_0_0.ClusterSpec]:  # noqa: E501
>     """Construct cluster specification from entity status of given rde version.
> ```

Construct cluster spec of the specified rde version from the current status of the cluster
___
*[container_service_extension/rde/utils.py, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJPE4lA3zOBVbZNb-g:-MVJPE4lA3zOBVbZNb-h:b-o5awsg) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L75)):*
> ```Python
> 
>     :param rde_X_X_X Status entity_status: Entity Status of rde of given version  # noqa: E501
>     :param str rde_version: which version of schema
> ```

RDE version of the spec to be created from the status
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 28 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJQ1naANOSDD-Y3isv:-MVJQ1naANOSDD-Y3isw:bogla5a) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L28)):*
> ```Python
> @telemetry_handler.record_user_action_telemetry(cse_operation=telemetry_constants.CseOperation.V36_CLUSTER_APPLY)  # noqa: E501
> @request_utils.cluster_api_exception_handler
> def cluster_create(data: dict, op_ctx: ctx.OperationContext):
> ```

We need to validate the input spec against RDE 2.0.0 model first. Validation could be as simple as casting it to 2.0 model.

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947)* status: 10 of 14 files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

___
*[container_service_extension/rde/utils.py, line 72 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJP0Mh16jTqlvuBrdL:-MVMviKX7ySmL-XaJKvY:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L72)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Construct cluster spec of the specified rde version from the current status of the cluster
</blockquote></details>

Done.
___
*[container_service_extension/rde/utils.py, line 75 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJPE4lA3zOBVbZNb-g:-MVMvsu7EgC-dZEX2q7g:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/rde/utils.py#L75)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

RDE version of the spec to be created from the status
</blockquote></details>

Done.
___
*[container_service_extension/server/request_handlers/v36/def_cluster_handler.py, line 28 at r1](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVJQ1naANOSDD-Y3isv:-MVMvnkG31m8hirNQSQm:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dc639b9e8978d543d130ae0954beaa7f134989fe/container_service_extension/server/request_handlers/v36/def_cluster_handler.py#L28)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

We need to validate the input spec against RDE 2.0.0 model first. Validation could be as simple as casting it to 2.0 model.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: please ensure all cluster operations go through, thanks.

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947#-:-MVNG1P77Z7GSh-ey5pj:br2e7bk)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794 and @sahithi)

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: minor confirmation

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/947#-:-MVSDEV65edwA_5WwS3Z:b2jl6r3)* status: all files reviewed, 5 unresolved discussions (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

___
*[container_service_extension/server/request_dispatcher.py, line 456 at r3](https://reviewable.io/reviews/vmware/container-service-extension/947#-MVSCSjH2EFSyDEGpagA:-MVSCSjH2EFSyDEGpagB:b1tvlxz) ([raw file](https://github.com/vmware/container-service-extension/blob/ddc66d406ef26a6ddc73038c43a27794828fa0bb/container_service_extension/server/request_dispatcher.py#L456)):*
> ```Python
>         RequestMethod.GET: {
>             ('36.0',): {
>                 'allowed_params': ['org_name', 'ovdc_name', 'pageSize', 'page'],  # noqa: E501
> ```

The cluster list operation supports more than just `org_name` and `ovdc_name` as params right? @sahithi

**Pull request merged**
