### PR TITLE
[VCDA-1876] Update documentation for Container UI Plugin

### PR DESCRIPTION
**Pull request by andrew-ni**
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/779)

### CODE REVIEW

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/779)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794, @sahithi, and @sakthisunda)

**Review by sakthisunda — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/779)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-ni, @Anirudh9794, and @sahithi)

___
*[docs/cse2_6/CSE_UI_PLUGIN.md, line 18 at r1](https://reviewable.io/reviews/vmware/container-service-extension/779#-MJAnsE-B_9WbFIrY0LL:-MJAnsE-B_9WbFIrY0LM:b32w61) ([raw file](https://github.com/vmware/container-service-extension/blob/823182ca5e40d69c6a1efcbcd9e23010cb6f688a/docs/cse2_6/CSE_UI_PLUGIN.md#L18)):*
> ```Markdown
> ---
> 
> ## Register and publish Container Ui Plugin
> ```

UI

**Review by sakthisunda — COMMENTED** [review]
:lgtm: (minor change)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/779#-:-MJAocPQ71yrEwCaZsoZ:b-hddyi3)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-ni, @Anirudh9794, and @sahithi)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/779#-:-MJBgggm70L0swr22ze3:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-ni, @Anirudh9794, and @sahithi)

___
*[docs/cse3_0/CSE_UI_PLUGIN.md, line 12 at r1](https://reviewable.io/reviews/vmware/container-service-extension/779#-MJBgG0o41dQK2lRahvQ:-MJBgG0p-ID25tziQeSk:bxhj393) ([raw file](https://github.com/vmware/container-service-extension/blob/823182ca5e40d69c6a1efcbcd9e23010cb6f688a/docs/cse3_0/CSE_UI_PLUGIN.md#L12)):*
> ```Markdown
> ## Overview
> 
> For VCD versions before 10.2, Container UI Plugin 1.0.3 can be used to manage with CSE Kubernetes clusters directly from VCD UI
> ```

nit : manage CSE ...  no need for 'with' in between
___
*[docs/cse3_0/CSE_UI_PLUGIN.md, line 20 at r1](https://reviewable.io/reviews/vmware/container-service-extension/779#-MJBgTEi19TM-AbGCYBi:-MJBgTEi19TM-AbGCYBj:b-355ioi) ([raw file](https://github.com/vmware/container-service-extension/blob/823182ca5e40d69c6a1efcbcd9e23010cb6f688a/docs/cse3_0/CSE_UI_PLUGIN.md#L20)):*
> ```Markdown
> ---
> 
> ## Register and publish Container Ui Plugin
> ```

nit: UI

**Pull request merged**
