### PR TITLE
[VCDA-2542] preserving external ip during resize

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Tested resizing the cluster, and the cluster info shows the external ip.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1056)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1056)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1056#-:-MbeTU5Z7qQcxe5P-HKB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/def_/cluster_service.py, line 1611 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1056#-MbeTYvj6z6w4yrTVwD0:-MbeTYvk5bYzdlcTRZ2e:b-4nj53n) ([raw file](https://github.com/vmware/container-service-extension/blob/2bf7ae885ab0d76f6f5865fb4dca66e026b4cb96/container_service_extension/def_/cluster_service.py#L1611)):*
> ```Python
>         if curr_nodes_status:
>             # Retrieve external ip for exposed NSX-T cluster
>             if curr_entity.entity.status.exposed and \
> ```

Do we really need the check?
There will be some control plane ip anyways right? It will be either the master node ip or the dnat external ip. As long as we copy it here, we should be fine.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1056)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)

___
*[container_service_extension/def_/cluster_service.py, line 1611 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1056#-MbeTYvj6z6w4yrTVwD0:-Mbg01DU9Gr4daGkDgWu:b-k0m9q1) ([raw file](https://github.com/vmware/container-service-extension/blob/2bf7ae885ab0d76f6f5865fb4dca66e026b4cb96/container_service_extension/def_/cluster_service.py#L1611)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Do we really need the check?
There will be some control plane ip anyways right? It will be either the master node ip or the dnat external ip. As long as we copy it here, we should be fine.
</blockquote></details>

I think what you are saying is simpler and would be fine. Although doing that would likely need a comment why we are copying the control plane node ip instead of just using the current control plane ip in `curr_node_status`. I think it is clearer why this is in here if we check for exposed. I'm fine either way, just let me know :)

Also, I wanted to do safe checks for `nodes` and `control_plane` fields since both could technically be None.

**Review by rocknes — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1056)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ltimothy7)

___
*[container_service_extension/def_/cluster_service.py, line 1611 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1056#-MbeTYvj6z6w4yrTVwD0:-MbjMWlq0yBQNtdF-XDR:brxp9sq) ([raw file](https://github.com/vmware/container-service-extension/blob/2bf7ae885ab0d76f6f5865fb4dca66e026b4cb96/container_service_extension/def_/cluster_service.py#L1611)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think what you are saying is simpler and would be fine. Although doing that would likely need a comment why we are copying the control plane node ip instead of just using the current control plane ip in `curr_node_status`. I think it is clearer why this is in here if we check for exposed. I'm fine either way, just let me know :)

Also, I wanted to do safe checks for `nodes` and `control_plane` fields since both could technically be None.

</blockquote></details>

Sounds good.

**Pull request merged**
