### PR TITLE
[VCDA-2188] ipam solution for getting available ip

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Added helped for nsxt backed gateway service to get an available ip.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Successfully retrieved available ip.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @rocknes @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/937)

### CODE REVIEW

**Review by arunmk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/937)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 303 at r1](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUr-fdk5OkwinFTSUdX:-MUr-fdk5OkwinFTSUdY:b-swcs73) ([raw file](https://github.com/vmware/container-service-extension/blob/5fa8a0e6349b65d0881079d306617282abaa2664/container_service_extension/nsxt_backed_gateway_service.py#L303)):*
> ```Python
>         available_ips_set = set()
>         for subnet_value in subnet_values:
>             ip_ranges: list = _subnet_value_to_ip_ranges_values(subnet_value)
> ```

If there is time for this review, we should make a list of used IPs and then remove from the subnet while traversing the subnet, since it's likely that the subnet range will usually be much larger than the umber of machines. For example, suppose someone says 10.150.X.Y/16, we can have 256*256 = 65536 IPs in the list and we may have only say a few hundred used. However this approach is not bad since most people won't have such large ranges.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/937#-:-MUrIqZwDELrEdL_KTgl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @arunmk)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 303 at r1](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUr-fdk5OkwinFTSUdX:-MUrIZT3Am4YbGC9VIUb:brgj8f) ([raw file](https://github.com/vmware/container-service-extension/blob/5fa8a0e6349b65d0881079d306617282abaa2664/container_service_extension/nsxt_backed_gateway_service.py#L303)):*
<details><summary><i>Previously, arunmk (Arun M. Krishnakumar) wrote…</i></summary><blockquote>

If there is time for this review, we should make a list of used IPs and then remove from the subnet while traversing the subnet, since it's likely that the subnet range will usually be much larger than the umber of machines. For example, suppose someone says 10.150.X.Y/16, we can have 256*256 = 65536 IPs in the list and we may have only say a few hundred used. However this approach is not bad since most people won't have such large ranges.
</blockquote></details>

Alternatively, we can walk each subnet and use the used ip list to prune the current subnet, if it has any ips left, we return the first available ip. In this schema we don't have to process all the subnets.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/937)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @arunmk and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 303 at r1](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUr-fdk5OkwinFTSUdX:-MUuFa4O2ZK7SKXvfrH5:bjyio6r) ([raw file](https://github.com/vmware/container-service-extension/blob/5fa8a0e6349b65d0881079d306617282abaa2664/container_service_extension/nsxt_backed_gateway_service.py#L303)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Alternatively, we can walk each subnet and use the used ip list to prune the current subnet, if it has any ips left, we return the first available ip. In this schema we don't have to process all the subnets.
</blockquote></details>

Done. Thank you both; I have taken this approach to used the set of used ips while traversing the subnet.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/937#-:-MUzumdNE93ybCX1D1NG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @arunmk and @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 117 at r2](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUzueoqCRS9DBoOSSth:-MUzueoqCRS9DBoOSSti:b-to6fpj) ([raw file](https://github.com/vmware/container-service-extension/blob/5d03c2804e66b793678e31cd179ea13869b4517b/container_service_extension/nsxt_backed_gateway_service.py#L117)):*
> ```Python
>                 return curr_ip_str
>             curr_ip += 1
>     return ''
> ```

Is there are reason behind why we are using empty string instead of None?

**Comment by ltimothy7** [comment]
___
*[container_service_extension/nsxt_backed_gateway_service.py, line 117 at r2](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUzueoqCRS9DBoOSSth:-MV38qIOAhI0bWgSULzj:b7lbh4q) ([raw file](https://github.com/vmware/container-service-extension/blob/5d03c2804e66b793678e31cd179ea13869b4517b/container_service_extension/nsxt_backed_gateway_service.py#L117)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Is there are reason behind why we are using empty string instead of None?
</blockquote></details>

I put empty string to be consistent with the types. What do you think?

**Comment by arunmk** [comment]
___
*[container_service_extension/nsxt_backed_gateway_service.py, line 117 at r2](https://reviewable.io/reviews/vmware/container-service-extension/937#-MUzueoqCRS9DBoOSSth:-MV2aYXjD8WoKnhIf-j3:b-a6sqqx) ([raw file](https://github.com/vmware/container-service-extension/blob/5d03c2804e66b793678e31cd179ea13869b4517b/container_service_extension/nsxt_backed_gateway_service.py#L117)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I put empty string to be consistent with the types. What do you think?
</blockquote></details>

When we start using types, we can have a function that returns `str` rather than a return type of `optional|str`.  Comparison also becomes clearer since we don't need to check for `== None` and `==""`

**Pull request merged**
