### PR TITLE
[VCDA-3346] fail PUT operations for cni/csi/cpi update

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy7 <66969084+ltimothy7@users.noreply.github.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1324)

### CODE REVIEW

**Review by sahithi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1324)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1324#-MxlvoxI1BpERjy5zj9y:-MxlvoxI1BpERjy5zj9z:bkt90gx) ([raw file](https://github.com/vmware/container-service-extension/blob/7a66599a124f0e136e0759ccc081a6a606b75afb/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
> ```Python
>     ]
> 
>     if is_tkgm_cluster:
> ```

By not excluding these fields, are we simply ignoring any changes to these values (or) are we raising 400?

The goal is to raise 400 on detecting any changes to the CSI, CNI, CPI values.

**Review by sahithi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1324)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1324#-MxlvoxI1BpERjy5zj9y:-Mxlw_i_6LY_0YF0nfGJ:b-n37c8j) ([raw file](https://github.com/vmware/container-service-extension/blob/7a66599a124f0e136e0759ccc081a6a606b75afb/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

By not excluding these fields, are we simply ignoring any changes to these values (or) are we raising 400?

The goal is to raise 400 on detecting any changes to the CSI, CNI, CPI values.
</blockquote></details>

typo in the previous statement
 "By not excluding these fields" -> "By excluding these fields"

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1324)* status: all files reviewed, 1 unresolved discussion (waiting on @sahithi)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1324#-MxlvoxI1BpERjy5zj9y:-MxmWT0r89wI_NLldKuU:b8ap6xs) ([raw file](https://github.com/vmware/container-service-extension/blob/7a66599a124f0e136e0759ccc081a6a606b75afb/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

typo in the previous statement
 "By not excluding these fields" -> "By excluding these fields"
</blockquote></details>

@sahithi I removed CSI, CNI, and CPI from being in the excluded fields for this PR, so any change to them should raise an error

**Comment by ltimothy7** [comment]
___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1324#-MxlvoxI1BpERjy5zj9y:-MxmWmldB46VcBGA3HAI:b4jnamm) ([raw file](https://github.com/vmware/container-service-extension/blob/7a66599a124f0e136e0759ccc081a6a606b75afb/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

@sahithi I removed CSI, CNI, and CPI from being in the excluded fields for this PR, so any change to them should raise an error
</blockquote></details>

(Previously, these fields were being excluded)

**Review by sahithi — APPROVED** [review]
:lgtm: assuming testing is done.

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1324#-:-MxolH1y01YKfOKlwZTp:boz62fi)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/rde/validators/validator_rde_2_x.py, line 168 at r2](https://reviewable.io/reviews/vmware/container-service-extension/1324#-MxlvoxI1BpERjy5zj9y:-Mxol-BK0v5IRCu9Sj_C:bb7m07t) ([raw file](https://github.com/vmware/container-service-extension/blob/7a66599a124f0e136e0759ccc081a6a606b75afb/container_service_extension/rde/validators/validator_rde_2_x.py#L168)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

(Previously, these fields were being excluded)
</blockquote></details>

okay

**Pull request merged**
