### PR TITLE
[VCDA-3455] Document known issue - cluster create task running forever due to failure to get API token

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

- If there is an error in getting API token for a TKGm cluster, the cluster create task will run forever.
- This should be documented as a known issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1407)

### CODE REVIEW

**Comment by ltimothy7** [comment]
*[`docs/cse3_1/KNOWN_ISSUES.md` line 241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1407#-NJMUaMpAAevuJ-_dZv5:-NJMUaMpAAevuJ-_dZv6:bquibig) ([raw file](https://github.com/vmware/container-service-extension/blob/b2d864b17445de2a6f54a638eac456edefc3038f/docs/cse3_1/KNOWN_ISSUES.md#L241)):*
> ```Markdown
> ### Task for create cluster goes on forever even when cluster create has failed in CSE server
> CSE server with versions 3.1.1, 3.1.2, 3.1.3 and 3.1.4 are impacted. The issue will happen when the user's role used to deploy a TKGm kubernetes cluster is missing "Manage user's own API token" right. The cluster create task will not be marked as "failed" even when CSE server logs indicate that the cluster creation has failed.
> Adding the missing "Manage user's own API token" right to the user's role and re-attemplting the cluster creation should fix the issue.
> ```

minor: type "reattempting"

**Review by ltimothy7 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1407)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794 and @rocknes)

**Review by rocknes — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1407)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[`docs/cse3_1/KNOWN_ISSUES.md` line 241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1407#-NJMUaMpAAevuJ-_dZv5:-NJR3Pm46uV6xtg8SqUn:b-tlbvc2) ([raw file](https://github.com/vmware/container-service-extension/blob/b2d864b17445de2a6f54a638eac456edefc3038f/docs/cse3_1/KNOWN_ISSUES.md#L241)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

minor: type "reattempting"
</blockquote></details>

Minor rewording:

CSE server versions 3.1.1, 3.1.2, 3.1.3 and 3.1.4 are impacted. 

The customer will face this issue if the user used to deploy the TKGm kubernetes cluster is missing "Manage user's own API token" right from their role. 

The cluster create task will not be marked as "failed" even though CSE server logs will indicate that the cluster creation has failed.

Adding the missing right viz. "Manage user's own API token" to the user's role and re-attempting the cluster creation operation should fix the issue.

**Review by rocknes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1407)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[`docs/cse3_1/KNOWN_ISSUES.md` line 241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1407#-NJMUaMpAAevuJ-_dZv5:-NJR45Sf28_kPZvRlyqQ:bkjlq2z) ([raw file](https://github.com/vmware/container-service-extension/blob/b2d864b17445de2a6f54a638eac456edefc3038f/docs/cse3_1/KNOWN_ISSUES.md#L241)):*
> The customer will face this issue

* This issue will be observed, if the users used ....

**Comment by Anirudh9794** [comment]
*[`docs/cse3_1/KNOWN_ISSUES.md` line 241 at r1](https://reviewable.io/reviews/vmware/container-service-extension/1407#-NJMUaMpAAevuJ-_dZv5:-NJgW1PX71hFxcz6_FQe:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/b2d864b17445de2a6f54a638eac456edefc3038f/docs/cse3_1/KNOWN_ISSUES.md#L241)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

> The customer will face this issue

* This issue will be observed, if the users used ....

</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1407#-:-NJv1RrO55qUKOUToR3m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
