### PR TITLE
[VCDA-2314] Skip sizing class and storage profile validation if node count is 0

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Set defaults for k8 template name and revision to None. This enables the user to skip validation on template name and revision by sending empty values if no change in the field is desired.
* Skip validation on workers.sizingClass, workers.storageProfile, nfs.sizingClass and nfs.storageProfile if number of workers or number of nfs nodes in the entity status is 0

@sakthisunda @rocknes @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1001)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1001)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1001)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by ltimothy7 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1001#-:-MYCQTHy-EweXLz-oMQD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by ltimothy7 — COMMENTED** [review]
Please remember to fix flake8 errors

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1001#-:-MYHBSPxDwfthpl8GLni:bnjr8nk)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @sakthisunda)

**Pull request merged**
