### PR TITLE
[VCDA-1638] Use scrypt for encryption algorithm

### PR DESCRIPTION
**Pull request by ltimothy7**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
`cse encrypt` now uses the scrypt algorithm for encryption for stronger security against GPU attacks. `cse decrypt` can decrypt encrypted with scrypt of SHA-256 in CSE 2.6.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
When decrypting a SHA-256 encrypted file, the used gets a suggestion to decrypt the SHA-256 file and re-encrypt it with CSE 3.0.

The current PR successfully decrypts a file encrypted with SHA-256. The current PR also successfully encrypts and decrypts a file using scrypt. 

- (Optional) Names of reviewers using @ sign + name

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743)

### CODE REVIEW

**Review by sahithi — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743#-:-MHD5STOAUPP6sjHrECF:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/encryption_engine.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHD5CSWASHGEBz--L87:-MHD5CSWASHGEBz--L88:b-vzrh2q) ([raw file](https://github.com/vmware/container-service-extension/blob/98b4ab0e4962ea757b99e994425151e55f7f852a/container_service_extension/encryption_engine.py#L93)):*
> ```Python
>             sys.stdout.write("Configuration file encrypted with CSE 2.6 "
>                              "found. Please consider decrypting this file "
>                              "and re-encrypting it with CSE 3.0 for stronger "
> ```

How about
stronger security -> enhanced security?

**Review by andrew-ni — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743#-:-MHDU7_21QqnDiyuJJW0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743#-:-MHESQpO9gpDRivy1yye:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[requirements.txt, line 20 at r2](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHERp8dDlxmjE6jY4XY:-MHERp8fDfoxNlevCRph:bspypvc) ([raw file](https://github.com/vmware/container-service-extension/blob/c7bc6613f49eaa441b2cb18f863b4b91474943e1/requirements.txt#L20)):*
> ```vimhelp
> 
> # pyOpenSSL
> pyOpenSSL == 19.1.0
> ```

Please let Aashima know that we will need a new legal OSL file.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @rocknes and @sahithi)

___
*[requirements.txt, line 20 at r2](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHERp8dDlxmjE6jY4XY:-MHORB7QEupUmpL65XyM:bdlbb2c) ([raw file](https://github.com/vmware/container-service-extension/blob/c7bc6613f49eaa441b2cb18f863b4b91474943e1/requirements.txt#L20)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please let Aashima know that we will need a new legal OSL file.
</blockquote></details>

The PBKDF2 will not need an additional package since it uses the cryptography package.
___
*[container_service_extension/encryption_engine.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHD5CSWASHGEBz--L87:-MHOQXaT08ZY6rj5f0hR:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/98b4ab0e4962ea757b99e994425151e55f7f852a/container_service_extension/encryption_engine.py#L93)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

How about
stronger security -> enhanced security?
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743)* status: all files reviewed, 2 unresolved discussions (waiting on @ltimothy7 and @sahithi)

___
*[container_service_extension/server_cli.py, line 725 at r3](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHPsxlf8dUEjDqkhf9R:-MHPsxlg7NDhOkU1FUNJ:b-risens) ([raw file](https://github.com/vmware/container-service-extension/blob/fff0756e597fef90b2e74a795ae12d04ab088806/container_service_extension/server_cli.py#L725)):*
> ```Python
>     finally:
>         # If skip_config_decryption is false, the user will again be
>         # prompted for the password
> ```

This approach has a different problem, we can potentially fail to send telemetry data, even if the failure was not due to config decryption (aka wrong password).

Ideally service should not be in the business of reading config files at all. The CLI layer should read the file and pass around the config as a dict. Let's discuss this in scrum.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes and @sahithi)

___
*[container_service_extension/server_cli.py, line 725 at r3](https://reviewable.io/reviews/vmware/container-service-extension/743#-MHPsxlf8dUEjDqkhf9R:-MHSybs9-mzT7YRYjcS1:bwrbjl) ([raw file](https://github.com/vmware/container-service-extension/blob/fff0756e597fef90b2e74a795ae12d04ab088806/container_service_extension/server_cli.py#L725)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This approach has a different problem, we can potentially fail to send telemetry data, even if the failure was not due to config decryption (aka wrong password).

Ideally service should not be in the business of reading config files at all. The CLI layer should read the file and pass around the config as a dict. Let's discuss this in scrum.
</blockquote></details>

Done. I have created a task for this in Tech Debt

**Review by andrew-ni — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/743#-:-MHl_q5X3EFgQHpunFBl:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @rocknes and @sahithi)

**Pull request merged**
