### PR TITLE
[VCDA-1696] Upgrade cloudapi endpoints and refactor compute policy manager

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

* Refactor compute policy manager to use cloudapi version 2.0.0
* separate out cse prefixing form compute policy manager

Testing done:
* Checked paths which were affected by the change:
- `cse run`
- `cse template install`
- `cse upgrade`
- `cse install` (TODO for api version < 35)
- `vcd cse ovdc list`
- `vcd cse ovdc enable/disable`
- `vcd cse ovdc compute-policy list` (TODO)
- `vcd cse ovdc compute-policy add/remove` (TODO)

@rocknes @sahithi @ltimothy7 @sakthisunda

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/compute_policy_manager.py, line 246 at r1](https://reviewable.io/reviews/vmware/container-service-extension/801#-MK6bRbX20eXpv698LUP:-MK6bRbY8qW86S6FqbF8:b8qj1o7) ([raw file](https://github.com/vmware/container-service-extension/blob/62cab705ea7c0dab70a37b7c3a991b0662bf0bc9/container_service_extension/compute_policy_manager.py#L246)):*
> ```Python
>         return self._cloudapi_client.do_request(
>             method=RequestMethod.DELETE,
>             cloudapi_version=cloudapi_constants.CloudApiVersion.VERSION_1_0_0,
> ```

Can only cloud api 1.0.0 compute policies be deleted?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/compute_policy_manager.py, line 246 at r1](https://reviewable.io/reviews/vmware/container-service-extension/801#-MK6bRbX20eXpv698LUP:-MK6iz7V9CAqd6NC8ziv:bjwlimv) ([raw file](https://github.com/vmware/container-service-extension/blob/62cab705ea7c0dab70a37b7c3a991b0662bf0bc9/container_service_extension/compute_policy_manager.py#L246)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Can only cloud api 1.0.0 compute policies be deleted?
</blockquote></details>

No, This should be changed. Thanks for catching this

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/def_/schema_service.py, line 230 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKB92FM8zptte-0_EOk:-MKB92FM8zptte-0_EOl:bqf4i2m) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/def_/schema_service.py#L230)):*
> ```Python
>         self._cloudapi_client.do_request(
>             method=cse_shared_constants.RequestMethod.DELETE,
>             cloudapi_version=CloudApiVersion.VERSION_1_0_0,
> ```

Should these entity type functions also have api version 1.0.0 hardcoded?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/def_/schema_service.py, line 230 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKB92FM8zptte-0_EOk:-MKBLCIt47vh6CNHIqop:bfs7lp0) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/def_/schema_service.py#L230)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should these entity type functions also have api version 1.0.0 hardcoded?
</blockquote></details>

Currently only the `pvdcComputePolicies` and `vdcComputePolicies` endpoints have upgraded to `cloudapi/2.0.0`

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: all files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/compute_policy_manager.py, line 46 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKBfj772F79uEAyCO3Z:-MKBfj772F79uEAyCO3_:b-2o0y0d) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/compute_policy_manager.py#L46)):*
> ```Python
>         self._session = self._sysadmin_client.get_vcloud_session()
>         self._is_operation_supported = True
>         self._cloudapi_version = \
> ```

Does the `<_cloudapi_version>` need to be set here?
I think it would be clearer if the cloudapi_version after self._cloudapi_client was set. (Minor: You could also set the cloud api version using a one-line python if-else or a small helper function)
___
*[container_service_extension/compute_policy_manager.py, line 340 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKBempf0Op9F0P0MOBl:-MKBempf0Op9F0P0MOBm:b7qboss) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/compute_policy_manager.py#L340)):*
> ```Python
>             updated_policy = self._cloudapi_client.do_request(
>                 method=RequestMethod.PUT,
>                 cloudapi_version=cloudapi_constants.CloudApiVersion.VERSION_1_0_0,  # noqa: E501
> ```

Should this be the self._cloud_api_version in case the policy version is cloud api version 2.0.0?

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/compute_policy_manager.py, line 46 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKBfj772F79uEAyCO3Z:-MKBtwcT8QYRPgnjQXvR:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/compute_policy_manager.py#L46)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Does the `<_cloudapi_version>` need to be set here?
I think it would be clearer if the cloudapi_version after self._cloudapi_client was set. (Minor: You could also set the cloud api version using a one-line python if-else or a small helper function)
</blockquote></details>

Done.

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/compute_policy_manager.py, line 340 at r2](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKBempf0Op9F0P0MOBl:-MKBu3OC2OAnO07sCr4a:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/2f6875f441b2941017d07e84226fb35e4b190e7e/container_service_extension/compute_policy_manager.py#L340)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

Should this be the self._cloud_api_version in case the policy version is cloud api version 2.0.0?
</blockquote></details>

Done.

**Review by ltimothy7 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: all files reviewed, 3 unresolved discussions (waiting on @ltimothy7)

**Review by ltimothy7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/compute_policy_manager.py, line 21 at r3](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKGFlN460Q6pbfVS5jT:-MKGFlN460Q6pbfVS5jU:b-2s15pm) ([raw file](https://github.com/vmware/container-service-extension/blob/977f8d45fb5a6a905413f94d66a5518e208761a4/container_service_extension/compute_policy_manager.py#L21)):*
> ```
> CSE_COMPUTE_POLICY_PREFIX = 'cse----'
> ```
Also defined in cloudapi/constants

**Review by sakthisunda — APPROVED** [review]
:lgtm: (minor comment)

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801#-:-MKGK-6w2JZbowe6qUKb:b-3xlrhu)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/compute_policy_manager.py, line 21 at r3](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKGFlN460Q6pbfVS5jT:-MKM73G3DYnwAwwRlt1a:bjp2fsj) ([raw file](https://github.com/vmware/container-service-extension/blob/977f8d45fb5a6a905413f94d66a5518e208761a4/container_service_extension/compute_policy_manager.py#L21)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

> ```
> CSE_COMPUTE_POLICY_PREFIX = 'cse----'
> ```
Also defined in cloudapi/constants
</blockquote></details>

Removed the constant present in cloudapi/constants

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, 4 of 5 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/compute_policy_manager.py, line 24 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhImet0f5DgHvn5ceo:-MKhImeuAPEgRy_MCRHM:b-z3ixfz) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L24)):*
> ```Python
> _SYSTEM_DEFAULT_COMPUTE_POLICY = 'System Default'
> GLOBAL_PVDC_COMPUTE_POLICY_MIN_VERSION = 35.0
> PVDC_POLICY_TYPE_VM = "PvdcVmPolicy"
> ```

Can we rename these constants to sound a bit better?
The _VM at the end is throwing me off as to what these constants are for.
___
*[container_service_extension/compute_policy_manager.py, line 227 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKDQH-rB_iCtmbCBt:-MKhKDQH-rB_iCtmbCBu:b4pcduz) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L227)):*
> ```Python
>             resource_url_relative_path=resource.PVDC_COMPUTE_POLICIES,
>             payload=policy_info)
>         pvdc_policy['display_name'] = self.get_policy_display_name(pvdc_policy['name']) # noqa: E501
> ```

Why are we removing this field from the output?
___
*[container_service_extension/compute_policy_manager.py, line 285 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhK9SxDRM6Fhf_At2T:-MKhK9SxDRM6Fhf_At2U:b4pcduz) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L285)):*
> ```Python
>             payload=policy_info)
> 
>         created_policy['display_name'] = self.get_policy_display_name(created_policy['name']) # noqa: E501
> ```

Why are we removing this field from the output?
___
*[container_service_extension/compute_policy_manager.py, line 354 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKLd900y2aSD3saZL:-MKhKLd900y2aSD3saZM:b4pcduz) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L354)):*
> ```Python
> 
>             updated_policy['display_name'] = \
>                 self.get_policy_display_name(updated_policy['name'])
> ```

Why are we removing this field from the output?
___
*[container_service_extension/compute_policy_manager.py, line 945 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKS5MC-RSzHYgnrMZ:-MKhKS5N2Tfumm9gpXSx:bpmzwih) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L945)):*
> ```Python
>                                 unprefixed_policy_name: str):
>     policy_name = get_cse_policy_name(unprefixed_policy_name)
>     return cpm.get_pvdc_compute_policy(policy_name)
> ```

If we are returning 'display_name' selectively for only some operations, I would suggest that CPM stops returning the field altogather.
We append that field in these utility functions, that way the concept of converting name of a policy to it's non CSE version is preserved inside these utility functions only, and the main compute policy manager is completely disjoint from CSE logic!
___
*[container_service_extension/compute_policy_manager.py, line 974 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhHj4Z7hien4ImF0Ba:-MKhHj4_5-ipTHvJdML4:blris9t) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L974)):*
> ```Python
> def delete_cse_vdc_compute_policy(cpm: ComputePolicyManager,
>                                   unprefixed_policy_name: str,
>                                   is_placement_policy: bool = False):
> ```

Can we have two policies with the same name? If not, then the param is_placement_policy is unnecessary right?

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @ltimothy7, @rocknes, and @sakthisunda)

___
*[container_service_extension/compute_policy_manager.py, line 24 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhImet0f5DgHvn5ceo:-MKkIwg65XAV79Y10bTe:b8cvv7l) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can we rename these constants to sound a bit better?
The _VM at the end is throwing me off as to what these constants are for.
</blockquote></details>

renaming to `VM_PVDC_POLICY`
___
*[container_service_extension/compute_policy_manager.py, line 227 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKDQH-rB_iCtmbCBt:-MKkKdrm6DAJd5NNHJex:bodv4m9) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L227)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Why are we removing this field from the output?
</blockquote></details>

Moved the logic for adding display_name to cse utility methods
___
*[container_service_extension/compute_policy_manager.py, line 285 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhK9SxDRM6Fhf_At2T:-MKklfuq3MFHF0h_xXkz:bewgp8) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L285)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Why are we removing this field from the output?
</blockquote></details>

Moved the logic of adding display name to cse utility methods
___
*[container_service_extension/compute_policy_manager.py, line 354 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKLd900y2aSD3saZL:-MKklk-f9rm1a0hewikf:b-3hkkfo) ([raw file](https://github.com/vmware/container-service-extension/blob/db45b0d178df3d68091913d57c0b16f342dc74a3/container_service_extension/compute_policy_manager.py#L354)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Why are we removing this field from the output?
</blockquote></details>

moved the logic of adding display name to CSE utility methods
___
*[container_service_extension/compute_policy_manager.py, line 945 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhKS5MC-RSzHYgnrMZ:-MKkloxi-hU4Gcg6xyU0:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L945)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If we are returning 'display_name' selectively for only some operations, I would suggest that CPM stops returning the field altogather.
We append that field in these utility functions, that way the concept of converting name of a policy to it's non CSE version is preserved inside these utility functions only, and the main compute policy manager is completely disjoint from CSE logic!
</blockquote></details>

Done.
___
*[container_service_extension/compute_policy_manager.py, line 974 at r4](https://reviewable.io/reviews/vmware/container-service-extension/801#-MKhHj4Z7hien4ImF0Ba:-MKkMM-Z5x-WbYZVVhyW:b-r5sqfw) ([raw file](https://github.com/vmware/container-service-extension/blob/d58dfce4bb4114992874a98532985ec4e82f8104/container_service_extension/compute_policy_manager.py#L974)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can we have two policies with the same name? If not, then the param is_placement_policy is unnecessary right?
</blockquote></details>

This also makes sure that we are deleting a placement policy and any other type of policy sizing policy. But 2 policies with the same name cannot be created.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/801#-:-MKnVZlsCKiGe_r2LgX7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sakthisunda)

**Pull request merged**
