### PR TITLE
[VCDA-2669] Replace float version comparisions with version object comparisons

### PR DESCRIPTION
**Pull request by Anirudh9794**
Signed-off-by: Aniruddha Shamasundar <aniruddha.9794@gmail.com>

To help us process your pull request efficiently, please include: 

Using VCDApiVersion object for comparing versions instead of converting to float.

Testing done:
* cse upgrade
* cse run
* cluster create (TODO)
* cluster resize (TODO)

@sakthisunda @rocknes

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1180)

### CODE REVIEW

**Review by sakthisunda — APPROVED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1180)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 11 of 17 files at r1, 2 of 3 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1180)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794)

___
*[container_service_extension/client/cluster.py, line 33 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihB7zi9U1uuEEjCHFB:-MihB7zi9U1uuEEjCHFC:b5zrefx) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/cluster.py#L33)):*
> ```Python
>         :return: instance of version specific client side cluster
>         """
>         api_version = client.get_api_version()
> ```

client.get_vcd_api_version() is better to use here, no need to create the intermediate VCDApiVersion objects over and over again.
___
*[container_service_extension/client/ovdc.py, line 24 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBTOJ3S92JMpda6Vi:-MihBTOJ3S92JMpda6Vj:b5zrefx) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/ovdc.py#L24)):*
> ```Python
>         :return: instance of version specific client side Ovdc class
>         """
>         api_version = client.get_api_version()
> ```

client.get_vcd_api_version() is better to use here, no need to create the intermediate VCDApiVersion objects over and over again.
___
*[container_service_extension/client/utils.py, line 143 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBYYiBMF3hcRoNzTh:-MihBYYiBMF3hcRoNzTi:b-lm7bjo) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/utils.py#L143)):*
> ```Python
>                     common_supported_api_versions = \
>                         [VCDApiVersion(x) for x in common_supported_api_versions  # noqa: E501
>                             if VCDApiVersion(x) < VCDApiVersion('35.0')]
> ```

Please use the constants in pyvcloud client.py instead of '35.0'
___
*[container_service_extension/common/constants/server_constants.py, line 69 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBhk-EuXQ8vPKy8SU:-MihBhk-EuXQ8vPKy8SV:b-huuf0p) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/common/constants/server_constants.py#L69)):*
> ```Python
>                      + CSE_SERVICE_NAME + ':' + MQTT_EXTENSION_VERSION
> MQTT_EXTENSION_PRIORITY = 100
> MQTT_MIN_API_VERSION = VCDApiVersion('35.0')
> ```

Please use the pyvcloud client.py constant
___
*[container_service_extension/installer/config_validator.py, line 256 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBt9D2cYY7EhxVClU:-MihBt9D2cYY7EhxVClV:ba4sldt) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/installer/config_validator.py#L256)):*
> ```Python
>             common_supported_api_versions = \
>                 [x for x in common_supported_api_versions
>                  if VCDApiVersion(x) < VCDApiVersion('35.0')]
> ```

please use pyvcloud constants
___
*[container_service_extension/installer/configure_cse.py, line 212 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBz3G9LX_5ZJgpAo-:-MihBz3G9LX_5ZJgpAo0:b-qc2gnc) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/installer/configure_cse.py#L212)):*
> ```Python
>             if len(vcd_api_tokens) == 2:
>                 vcd_api_version = vcd_api_tokens[1]
>                 if VCDApiVersion(vcd_api_version) >= VCDApiVersion('35.0'):
> ```

please use constant from pyvcloud client.py
___
*[container_service_extension/lib/cloudapi/cloudapi_client.py, line 51 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihC7WE8x0wWk-GUZtz:-MihC7WFBzlWkF29586x:bk3nkuf) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/lib/cloudapi/cloudapi_client.py#L51)):*
> ```Python
> 
>     def get_vcd_api_version(self):
>         return VCDApiVersion(self._api_version)
> ```

I would prefer to cache the value of api verison directly from the client in __init__ into self._vcd_api_version = client.get_vcd_api_version() and then return it directly instead of creating a new VCDApiVersion object everytime.
___
*[container_service_extension/rde/constants.py, line 125 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihCo_y5gQTMO4iRx7J:-MihCo_y5gQTMO4iRx7K:b-bpykk0) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/rde/constants.py#L125)):*
> ```Python
> # }
> MAP_VCD_API_VERSION_TO_RUNTIME_RDE_VERSION = {
>     35: RuntimeRDEVersion.RDE_1_X.value,
> ```

This change is a little dangerous .. you are changing a map[str->str] to map[int->str] .. check all the places where this map is being used and make sure we are not passing a string key to it..
___
*[container_service_extension/server/compute_policy_manager.py, line 26 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihDF851Zi5ZPd4AZEj:-MihDF851Zi5ZPd4AZEk:b-3nxbh) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/server/compute_policy_manager.py#L26)):*
> ```Python
> CSE_COMPUTE_POLICY_PREFIX = 'cse----'
> _SYSTEM_DEFAULT_COMPUTE_POLICY = 'System Default'
> GLOBAL_PVDC_COMPUTE_POLICY_MIN_VERSION = VCDApiVersion('35.0')
> ```

pyvcloud constant please

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1180)* status: 6 of 17 files reviewed, 9 unresolved discussions (waiting on @rocknes and @sakthisunda)

___
*[container_service_extension/client/cluster.py, line 33 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihB7zi9U1uuEEjCHFB:-Mj5j77a1RMmaeHa_jdp:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/cluster.py#L33)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

client.get_vcd_api_version() is better to use here, no need to create the intermediate VCDApiVersion objects over and over again.
</blockquote></details>

Done.
___
*[container_service_extension/client/ovdc.py, line 24 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBTOJ3S92JMpda6Vi:-Mj5jYeBDYj-HUtBWWl-:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/ovdc.py#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

client.get_vcd_api_version() is better to use here, no need to create the intermediate VCDApiVersion objects over and over again.
</blockquote></details>

Done.
___
*[container_service_extension/client/utils.py, line 143 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBYYiBMF3hcRoNzTh:-Mj7-Elb72dmZIoC80Ky:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/client/utils.py#L143)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please use the constants in pyvcloud client.py instead of '35.0'
</blockquote></details>

Done.
___
*[container_service_extension/common/constants/server_constants.py, line 69 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBhk-EuXQ8vPKy8SU:-Mj7-OsA2GaIDafd3F1c:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/common/constants/server_constants.py#L69)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please use the pyvcloud client.py constant
</blockquote></details>

Done.
___
*[container_service_extension/installer/config_validator.py, line 256 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBt9D2cYY7EhxVClU:-Mj7-kM2BOu07VW5g9DJ:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/installer/config_validator.py#L256)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

please use pyvcloud constants
</blockquote></details>

Done.
___
*[container_service_extension/installer/configure_cse.py, line 212 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihBz3G9LX_5ZJgpAo-:-Mj70eDVEo57bbX4TS2s:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/installer/configure_cse.py#L212)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

please use constant from pyvcloud client.py
</blockquote></details>

Done.
___
*[container_service_extension/lib/cloudapi/cloudapi_client.py, line 51 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihC7WE8x0wWk-GUZtz:-Mj71-_-D6_-m8YNpGvI:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/lib/cloudapi/cloudapi_client.py#L51)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I would prefer to cache the value of api verison directly from the client in __init__ into self._vcd_api_version = client.get_vcd_api_version() and then return it directly instead of creating a new VCDApiVersion object everytime.
</blockquote></details>

Done.
___
*[container_service_extension/rde/constants.py, line 125 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihCo_y5gQTMO4iRx7J:-Mj71Go_2RrhhpnIgZcY:bktu52l) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/rde/constants.py#L125)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This change is a little dangerous .. you are changing a map[str->str] to map[int->str] .. check all the places where this map is being used and make sure we are not passing a string key to it..
</blockquote></details>

Checked usages for the above dict.
`get_runtime_rde_version_by_vcd_api_version` is the only place where this dict is used. This function is used as a helper function to index into the dictionary.
___
*[container_service_extension/server/compute_policy_manager.py, line 26 at r3](https://reviewable.io/reviews/vmware/container-service-extension/1180#-MihDF851Zi5ZPd4AZEj:-Mj71a4v5lIQUvQptZuP:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/cde601f10e743b2bf176988c3aeffc3cc00f6f64/container_service_extension/server/compute_policy_manager.py#L26)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

pyvcloud constant please
</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/1180#-:-Mjfa4UT0GWFS-g6Fp-i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
