### PR TITLE
[VCDA-1944] Paginate TKG and legacy native cluster responses

### PR DESCRIPTION
**Pull request by Anirudh9794**
To help us process your pull request efficiently, please include: 

* Modify TKG client to support pagination for list operation
* Modify legacy native list clusters endpoint to support pagination
* CLI changes to print paginated response for list cluster operation

Testing done:
- `vcd cse cluster list` with API server running in API version 35
- `vcd cse cluster list` with API server running in API version 33 (TODO)
- Check postman response for `/api/cse/clusters` endpont (TODO)

@rocknes @ltimothy7 @sakthisunda @arunmk @ChintanShahVMware @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859)

### CODE REVIEW

**Review by ltimothy7 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

___
*[container_service_extension/client/de_cluster.py, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension/859#-MOs3r2WD_barE12_NtG:-MOs3r2WD_barE12_NtH:b5elkzu) ([raw file](https://github.com/vmware/container-service-extension/blob/06206ac56a1d32f869ca44d7d8219a4993fd5ffd/container_service_extension/client/de_cluster.py#L83)):*
> ```Python
>             filters = client_utils.construct_filters(org=org, vdc=vdc)
>             entity_svc = def_entity_svc.DefEntityService(self._cloudapi_client)
>             has_more_results = True
> ```

I think it is cleaner to move this functionality to de_cluster_native.py

**Comment by Anirudh9794** [comment]
___
*[container_service_extension/client/de_cluster.py, line 83 at r1](https://reviewable.io/reviews/vmware/container-service-extension/859#-MOs3r2WD_barE12_NtG:-MP6nP0Z0smgPOlZmBpn:b-6u0u6) ([raw file](https://github.com/vmware/container-service-extension/blob/06206ac56a1d32f869ca44d7d8219a4993fd5ffd/container_service_extension/client/de_cluster.py#L83)):*
<details><summary><i>Previously, ltimothy7 wrote…</i></summary><blockquote>

I think it is cleaner to move this functionality to de_cluster_native.py
</blockquote></details>

Changed this portion of the code to return both native and TKG clusters.

**Review by sakthisunda — APPROVED** [review]
> Reviewed 6 of 6 files at r2, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 1646 at r2](https://reviewable.io/reviews/vmware/container-service-extension/859#-MPC8rTiDrr2HdoCFhOG:-MPC8rTiDrr2HdoCFhOH:bdtag41) ([raw file](https://github.com/vmware/container-service-extension/blob/c0c5f3f7f32ef9832f7360f0e17bd05b41853edd/container_service_extension/vcdbroker.py#L1646)):*
> ```Python
>         clusters_info = q.execute()
>         cluster_list = clusters_info['values']
>         result_total = int(clusters_info.get('resultTotal'))
> ```

we have VALUES and RESULT_TOTAL in shared_constants for hard coded values above. May be they are used for different reason.
___
*[container_service_extension/client/de_cluster_tkg.py, line 138 at r2](https://reviewable.io/reviews/vmware/container-service-extension/859#-MPCA2VmDEbzHhykNSQg:-MPCA2VmDEbzHhykNSQh:bxxwug6) ([raw file](https://github.com/vmware/container-service-extension/blob/c0c5f3f7f32ef9832f7360f0e17bd05b41853edd/container_service_extension/client/de_cluster_tkg.py#L138)):*
> ```Python
>             has_more_results = additional_details['page'] < additional_details['pageCount']  # noqa: E501
>             yield clusters, has_more_results
>             query_params[shared_constants.PaginationKey.PAGE_NUMBER] += 1
> ```

should this be query_params[shared_constants.PaginationKey.PAGE_NUMBER.value] += 1 because it was initialized above that way. I think both are same.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @ltimothy7 and @sakthisunda)

___
*[container_service_extension/vcdbroker.py, line 1646 at r2](https://reviewable.io/reviews/vmware/container-service-extension/859#-MPC8rTiDrr2HdoCFhOG:-MPCKQJS5Fb1FbFYecIN:b-3lzm8k) ([raw file](https://github.com/vmware/container-service-extension/blob/c0c5f3f7f32ef9832f7360f0e17bd05b41853edd/container_service_extension/vcdbroker.py#L1646)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

we have VALUES and RESULT_TOTAL in shared_constants for hard coded values above. May be they are used for different reason.
</blockquote></details>

I did not want to mix the keys declared in pyvcloud with those declared in cse. If we decide to change the keys in pyvcloud, we will only have to change the keys in the places where we are using it. I can change this if it is okay to use the same keys here
___
*[container_service_extension/client/de_cluster_tkg.py, line 138 at r2](https://reviewable.io/reviews/vmware/container-service-extension/859#-MPCA2VmDEbzHhykNSQg:-MPCOHAk7Mez_FSFiXAx:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/c0c5f3f7f32ef9832f7360f0e17bd05b41853edd/container_service_extension/client/de_cluster_tkg.py#L138)):*
<details><summary><i>Previously, sakthisunda wrote…</i></summary><blockquote>

should this be query_params[shared_constants.PaginationKey.PAGE_NUMBER.value] += 1 because it was initialized above that way. I think both are same.
</blockquote></details>

Done.

**Review by sahithi — APPROVED** [review]
:lgtm: after addressing the comments. Please remove the extra code from tkgclient if we are not using it.

> Reviewed 3 of 9 files at r1, 4 of 6 files at r2, 5 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859#-:-MQJscio0VA7ymIE7NbJ:b-5xlmde)* status: all files reviewed, 9 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @sakthisunda)

___
*[container_service_extension/client/de_cluster.py, line 99 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJrhb5BW7HyUxmJt2A:-MQJrhb670g_wUKIERCq:bpvhofp) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/client/de_cluster.py#L99)):*
> ```Python
>                     cluster_def_entities: List[def_models.GenericClusterDefEntity] = clusters_page_results[PaginationKey.VALUES]  # noqa: E501
>                     clusters = []
>                     for def_entity in cluster_def_entities:
> ```

def_entity -> entity
cluster_def_entities -> entities

It is implicit that these entities are clusters. If needed, please add a comment. 
___
*[container_service_extension/client/tkgclient/api_client.py, line 255 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJqbIXC1rfeYct9Raq:-MQJqbIXC1rfeYct9Rar:b-bzuke) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/client/tkgclient/api_client.py#L255)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>             additional_data = {
>                 'page': int(response_data['page']),
>                 'pageSize': int(response_data['pageSize']),
>                 'resultTotal': int(response_data['resultTotal']),
>                 'pageCount': int(response_data['pageCount']),
>                 'entityDetails': entity_details
>             }
> ```
</details>

I would suggest we remove this code, if not used anywhere. Another thing to keep track of while updating the auto-generated tkg client.
Do we have a document somewhere on how to update tkg client? If not, we should create one. Let me know, I will create a jira task
___
*[container_service_extension/def_/entity_service.py, line 215 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJppGD2kRtI574s0qs:-MQJppGD2kRtI574s0qt:b-2niex8) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/entity_service.py#L215)):*
> ```Python
>         result = {}
>         entity_list = []
>         for v in response_body['values']:
> ```

nit: v -> entity to keep it consistent with the other methods.
___
*[container_service_extension/def_/models.py, line 328 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJotfSDPoLC64SJ6i0:-MQJoiAKAo6cv9kSCyUT:b-brtsz7) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L328)):*
> ```Python
> # include the following properties:
> @dataclass()
> class GenericClusterDefEntity:
> ```

GenericClusterDefEntity -> GenericClusterEntity

Rename the existing ClusterEntity -> NativeEntity
___
*[container_service_extension/def_/models.py, line 343 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJ43nL56v2BAtTfJ6K:-MQJ43nM6U1XNErsd0Q2:b-rdszwa) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L343)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
>     # name:
>     #   de.name
>     # vdc:
>     #   de.entity.metadata.ovdc_name for native
>     #   de.entity.metadata.virtual_data_center_name
>     # org:
>     #   de.org.name
>     # runtime:
>     #   de.entity.kind
>     # version:
>     #   de.entity.status.kubernetes for native,
>     #   de.entity.spec.distribution.version for TKG
>     # status:
>     #   de.entity.status.phase for native and
>     #   de.entity.status.phase if de.entity.status else 'N/A' for TKG
>     # owner:
>     #   de.owner.name
> ```
</details>

This doesn't reflect the properties currently present.
___
*[container_service_extension/def_/models.py, line 358 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJqJjlCRhddf5_4CrF:-MQJqJjlCRhddf5_4CrG:bk79k4d) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L358)):*
> ```Python
>                 [shared_constants.ClusterEntityKind.NATIVE.value,
>                  shared_constants.ClusterEntityKind.TKG_PLUS.value]:
>             self.entity = ClusterEntity(**entity_dict) if isinstance(entity, dict) else entity  # noqa: E501
> ```

Rename ClusterEntity -> NativeEntity, now that we have TkgEntity in the server-side code.

**Review by Anirudh9794 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/859)* status: all files reviewed, 8 unresolved discussions (waiting on @ltimothy7, @sahithi, and @sakthisunda)

___
*[container_service_extension/client/de_cluster.py, line 99 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJrhb5BW7HyUxmJt2A:-MQOWMgQ9nScmi4NuzZO:bvz3wjj) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/client/de_cluster.py#L99)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

def_entity -> entity
cluster_def_entities -> entities

It is implicit that these entities are clusters. If needed, please add a comment. 
</blockquote></details>

changed cluster_def_entities to entities
changed def_entity to de as there is a conflict with the variable name entity in the next line
___
*[container_service_extension/client/tkgclient/api_client.py, line 255 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJqbIXC1rfeYct9Raq:-MQOWTZz90zxiCJH26mi:b1bl1wm) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/client/tkgclient/api_client.py#L255)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>             additional_data = {
>                 'page': int(response_data['page']),
>                 'pageSize': int(response_data['pageSize']),
>                 'resultTotal': int(response_data['resultTotal']),
>                 'pageCount': int(response_data['pageCount']),
>                 'entityDetails': entity_details
>             }
> ```
I would suggest we remove this code, if not used anywhere. Another thing to keep track of while updating the auto-generated tkg client.
Do we have a document somewhere on how to update tkg client? If not, we should create one. Let me know, I will create a jira task
</blockquote></details>

Removed the unused code changes.

There was a message pinned in the channel which I am not able to find anymore. I think a document will be a better idea. I see that there is a Jira task already created for this. Will take this up as a follow up task. Thank you!
___
*[container_service_extension/def_/entity_service.py, line 215 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJppGD2kRtI574s0qs:-MQOX2QzBJeg-7z1_sit:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/entity_service.py#L215)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

nit: v -> entity to keep it consistent with the other methods.
</blockquote></details>

Done.
___
*[container_service_extension/def_/models.py, line 328 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJotfSDPoLC64SJ6i0:-MQO_7ju2U0D8GZPDIZW:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L328)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

GenericClusterDefEntity -> GenericClusterEntity

Rename the existing ClusterEntity -> NativeEntity
</blockquote></details>

Done.
___
*[container_service_extension/def_/models.py, line 343 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJ43nL56v2BAtTfJ6K:-MQOZEfw4DB3-zSPJBLO:bv8x4ky) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L343)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
>     # name:
>     #   de.name
>     # vdc:
>     #   de.entity.metadata.ovdc_name for native
>     #   de.entity.metadata.virtual_data_center_name
>     # org:
>     #   de.org.name
>     # runtime:
>     #   de.entity.kind
>     # version:
>     #   de.entity.status.kubernetes for native,
>     #   de.entity.spec.distribution.version for TKG
>     # status:
>     #   de.entity.status.phase for native and
>     #   de.entity.status.phase if de.entity.status else 'N/A' for TKG
>     # owner:
>     #   de.owner.name
> ```
This doesn't reflect the properties currently present.
</blockquote></details>

Updated the comment with proper details
___
*[container_service_extension/def_/models.py, line 358 at r4](https://reviewable.io/reviews/vmware/container-service-extension/859#-MQJqJjlCRhddf5_4CrF:-MQPG_no5DN2Nw0fg7yb:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/dfcbd1e914278ccaec9cfd9a75d68f32fef7d562/container_service_extension/def_/models.py#L358)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Rename ClusterEntity -> NativeEntity, now that we have TkgEntity in the server-side code.
</blockquote></details>

Done.

**Pull request merged**
