### PR TITLE
[VCDA-1884] Refactoring client modules

### PR DESCRIPTION
**Pull request by Anirudh9794**
porting changes from master

Change the module names to meaningful ones:
* native_cluster_api.py -> de_cluster_native.py
* tkg_cluster_api.py -> de_cluster_tkg.py
* legacy_native_cluster_api.py -> legacy_cluster_native.py
* ovdc_policy.py -> policy_based_ovdc.py
* legacy_ovdc.py -> metadata_based_ovdc.py

Created new `cse_client` which handles calls to CSE server.

Testing done:
v33:
 * cluster commands
* ovdc commands
v35
*. cluster commands
* ovdc commands

@rocknes @sakthisunda @ltimothy7 @ChintanShahVMware @arunmk @sahithi

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)

### CODE REVIEW

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 6 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 6 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 7 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 8 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 9 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 10 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 11 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — COMMENTED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: 12 of 26 files reviewed, all discussions resolved

**Review by sakthisunda — APPROVED** [review]
> Reviewed 14 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Review by ltimothy7 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/860#-:-MP5LbMJ1l4iUg4Mfkfn:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Anirudh9794)

**Pull request merged**
