### PR TITLE
[VCDA-2040 and VCDA-2043]Edge gateway quick ip allocation and add dnat rule

### PR DESCRIPTION
**Pull request by ltimothy7**
Signed-off-by: ltimothy <ltimothy@vmware.com>

To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
Added a class that can add do quick ip allocation and can add a dnat rule to an nsxt backed edge gateway.

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
Successfully performs quick ip allocation and adds dnat rule.

- (Optional) Names of reviewers using @ sign + name
@Anirudh9794 @sakthisunda @rocknes @arunmk

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)

### CODE REVIEW

**Review by Anirudh9794 — APPROVED** [review]
:lgtm: Minor comment

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887#-:-MRuupUF8Ji5N_GmIEks:bo0dolh)* status: all files reviewed, 1 unresolved discussion (waiting on @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 81 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRupEaJA4GWslHSkrqj:-MRupEaJA4GWslHSkrqk:boaxzl9) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/nsxt_backed_gateway_service.py#L81)):*
> ```Python
>         # Edit PUT request body
>         uplink_index = _get_uplink_index(
>             put_request_body['edgeGatewayUplinks'],
> ```

Constants can be created for get response keys and put request keys (for edge gateway)

**Review by rocknes — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 98 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRxvNBfCUPY_Y8m0tMd:-MRxvNBg6PrNCW8nus1_:b-ptorxc) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/nsxt_backed_gateway_service.py#L98)):*
> ```Python
>         request_subnet_value["autoAllocateIpRanges"] = True
> 
>         self._cloudapi_client.do_request(
> ```

How are we going to get back the ips that were allocated? We will need those ips to add the DNAT rule.

Also the interface of this method depends on a lot of info, how are we going to get hold of those in CSE?
___
*[container_service_extension/server_constants.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRxvqhD-5dstLn6FwFc:-MRxvqhE9plYjB4fnkym:bfd136p) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/server_constants.py#L93)):*
> ```Python
> 
> # NSXT Gateway NAT constants
> NATS_PATH = '/nat'
> ```

slash at the beginning or end makes it quite confusing while substituting these values in the final url.
I would prefer if we call these constants as just
NATS_PATH_FRAGMENT = 'nat'

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 81 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRupEaJA4GWslHSkrqj:-MS8lcjb5PMLpSrd1L_h:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/nsxt_backed_gateway_service.py#L81)):*
<details><summary><i>Previously, Anirudh9794 wrote…</i></summary><blockquote>

Constants can be created for get response keys and put request keys (for edge gateway)
</blockquote></details>

Done.
___
*[container_service_extension/nsxt_backed_gateway_service.py, line 98 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRxvNBfCUPY_Y8m0tMd:-MS8lg4GEYBjW5xBolyV:be7bmjx) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/nsxt_backed_gateway_service.py#L98)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

How are we going to get back the ips that were allocated? We will need those ips to add the DNAT rule.

Also the interface of this method depends on a lot of info, how are we going to get hold of those in CSE?
</blockquote></details>

Thank you; the new PR removes additionaly parameters and retrieves the new ip address
___
*[container_service_extension/server_constants.py, line 93 at r1](https://reviewable.io/reviews/vmware/container-service-extension/887#-MRxvqhD-5dstLn6FwFc:-MS8lyCI0eXoxttmEq_I:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/a2cd781ac661595fbbc450b847aa0f8b6d6180db/container_service_extension/server_constants.py#L93)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

slash at the beginning or end makes it quite confusing while substituting these values in the final url.
I would prefer if we call these constants as just
NATS_PATH_FRAGMENT = 'nat'
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
:lgtm: with a minor comment

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887#-:-MSTaLig15G6UasCJMtN:b-cttxx2)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 152 at r2](https://reviewable.io/reviews/vmware/container-service-extension/887#-MST_oQ53SX4GItzAP55:-MST_oQ73RiXzblAwRRE:b-agus41) ([raw file](https://github.com/vmware/container-service-extension/blob/48c2b1b18798bfd02a8cd6e690a26e47c5e16b52/container_service_extension/nsxt_backed_gateway_service.py#L152)):*
> ```Python
>         while updated_get_gateway_response[NsxtGatewayRequestKey.STATUS] != \
>                 server_constants.NSXT_GATEWAY_REALIZED_STATUS:
>             updated_get_gateway_response = self._get_gateway()
> ```

Please add a small sleep here, else we would be just making calls to the server relentlessly.

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 152 at r2](https://reviewable.io/reviews/vmware/container-service-extension/887#-MST_oQ53SX4GItzAP55:-MSUkWX--V_O_Wt7oTIH:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/48c2b1b18798bfd02a8cd6e690a26e47c5e16b52/container_service_extension/nsxt_backed_gateway_service.py#L152)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please add a small sleep here, else we would be just making calls to the server relentlessly.
</blockquote></details>

Done.

**Review by rocknes — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @Anirudh9794, @ltimothy7, and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 154 at r3](https://reviewable.io/reviews/vmware/container-service-extension/887#-MSYjNmTAL5xWG7JlXKZ:-MSYjNmTAL5xWG7JlXK_:b194te4) ([raw file](https://github.com/vmware/container-service-extension/blob/221d93b26a3d61d5123584854a41d88600dae4cf/container_service_extension/nsxt_backed_gateway_service.py#L154)):*
> ```Python
>                 updated_get_gateway_response[NsxtGatewayRequestKey.STATUS] != \
>                 server_constants.NSXT_GATEWAY_REALIZED_STATUS:
>             time.sleep(server_constants.NSXT_PUT_REQUEST_WAIT_TIME)
> ```

This flow will cause the sleep irrespective of what is returned by vCD.

python generally follows a 

While True:
 do  operation
 make check and wait

pattern

**Review by rocknes — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: all files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @ltimothy7)

**Review by ltimothy7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Anirudh9794 and @rocknes)

___
*[container_service_extension/nsxt_backed_gateway_service.py, line 154 at r3](https://reviewable.io/reviews/vmware/container-service-extension/887#-MSYjNmTAL5xWG7JlXKZ:-MSYt9sz1_qpm5Mvckas:b-896fix) ([raw file](https://github.com/vmware/container-service-extension/blob/221d93b26a3d61d5123584854a41d88600dae4cf/container_service_extension/nsxt_backed_gateway_service.py#L154)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This flow will cause the sleep irrespective of what is returned by vCD.

python generally follows a 

While True:
 do  operation
 make check and wait

pattern

</blockquote></details>

Done.

**Review by rocknes — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vmware/container-service-extension/887#-:-MUB9vS_9pSPFaiIdoNh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Anirudh9794)

**Comment by ltimothy7** [comment]
This PR is closed because it was opened prior to the code refactoring. This PR was opened against cse_3_0_updates. Then, the PR was ported to master.

**Pull request closed without merging**
